### ISSUE TITLE
Added a force-touch action for safari, suddenly normal click is hard to click

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#1]
I added a 2 finger force touch action to safari. But now the normal 2 finger click is harder to press than normal. While on safari, normal 2 finger click is pretty hard to do. Quickly switching to finger and 2 finger clicking needs the normal amount of pressure. 

Also, adding a 2 finger force touch gesture disables the normal right click action when not force touching. Instead it had to be added manually by using "activate context menu" with the trigger "two finger click"

MPB 2016 Touchbar 15"

**Comment by fifafu** [comment]
Hi Pallav,

thanks for reporting!
Unfortunately it's necessary to block the default two finger right-click when force touch two finger click is used. However you can just assign the right-click action to two finger click.

It is possible that I need to adjust the pressure sensitivity for the new trackpad. Could you experiment a bit with the settings in the Advanced Preferences? (http://i.imgur.com/kQmEy1f.png )

Best,
Andreas

**Comment by pallavmac** [comment]
Yes. Lowering the pressure needed works. But need to put it below normal.
