### ISSUE TITLE
[BUG] Side Dock Impacts App Margins

### ISSUE THREAD

**Issue by nhlwsn** [fifafu/BetterTouchTool#10]
#### Description of your bug/question/feature request...: 
I use BTT to toggle application windows (open... in global | ⌘+H in app). This works fine. 
The margin problem arises after snapping to an area on whichever side (left or right) of the screen I have my (automatically hiding) dock on. For descriptive purposes, let's say the right:  

1.  I open an app and move it to the extreme right side. There is no gap between the app and the edge of the screen. (✓)

2.  I hide the app using my custom toggle. (✓)

3. I bring the app to the front using my custom toggle, but now there is a gap between the app edge and screen edge. (x)

This occurs with both my custom snap area (default no gap at all) and the preconfigured maximize window left/right (where the gap gets bigger than what is desired and set through the app). 

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

MacBook Pro (Retina, 13-inch, Late 2013)
macOS Sierra v. 10.12.1
BTT v 1.96

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

expected / desired:
![image](https://cloud.githubusercontent.com/assets/10737392/20889893/c7876166-bad2-11e6-97bb-ff12df303625.png)

actual:
![image](https://cloud.githubusercontent.com/assets/10737392/20889914/d70b5c5a-bad2-11e6-94c4-547ff9bdaf1e.png)

**Comment by nhlwsn** [comment]
There's also a fullscreen margin issue where, with my dock on the right side, resizing a window to full screen doesn't go all the way to the right screen edge. This only happens when my dock is on the right; when it's on the left it behaves as expected.

**Comment by fifafu** [comment]
Unfortunately that is a limitation by the system. There is no way to fix this :-(

**Comment by nhlwsn** [comment]
Darn, ok. Thanks for explaining ( ′ ᵕ ‵ )
