### ISSUE TITLE
New update has critical bugs

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#100]
#### Description of your bug/question/feature request...:
1. No way to revert back to original touchbar with a keyboard shortcut. As soon as I trigger the keyboard shortcut, touchbar blinks then BTT touchbar is forced back on. 
2. On an app which doesn't have custom actions set, the control strip goes away!

**What kind of Mac are you using?**
Touchbar 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad

**Which version of macOS are you running?**
10.12.1 Sierra

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

**Comment by fifafu** [comment]
Hi!,

thanks for reporting :-) Could you check if the behavior has been fixed with the latest update ( 1.967)?

Isn't 2. correct though? If nothing to show => hide?  I have added a checkbox to the general settings to configure that.

Best,
Andreas

**Comment by pallavmac** [comment]
2. isn't correct. 
I open any app which I have not chosen in better touch tool, it defaults to hiding the control strip. Need a fix for this asap. Shall stay on previous version for now. Please tell me if you need a video demonstration.

**Comment by pallavmac** [comment]
Basically the BTT global touchbar never shows with the control strip

**Comment by pallavmac** [comment]
Also on apps the apps where custom actions are set but only when activated (Which means it defaults to app touchbar), activating the BTT touchbar also hides the control strip.

**Comment by fifafu** [comment]
Weird, are you sure the "show control strip" checkbox is activated in the general touch bar settings?
