### ISSUE TITLE
Simple question, Programming Browser forward/back a page

### ISSUE THREAD

**Issue by mavidal** [fifafu/BetterTouchTool#1000]
---

#### Description of bug/feature request/question:
How can I program button to do browser forward and back.  My mouse is supposed to have them pre-programed but they do not work.  I tried keyboard previous and next with the program and those options did not work either.  Program does see them as button 3 and 4.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Anker USB Mouse

#### Device information:

Type of Mac: Mac PRo tower
macOS version: 10.12
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can either use the "Trigger Menubar Menu Item" action to trigger the History;Back and History;Forward items, or you can use the "Mimic standard gestures => 3F Swipe Left (Back) / 3F Swipe Right (Forward) actions.
