### ISSUE TITLE
4-finger tap sequences have become unreliable

### ISSUE THREAD

**Issue by NevinBR** [fifafu/BetterTouchTool#1001]
#### Description of bug/feature request/question:

In BTT 2.16 (and  2.15 and 2.14) my 4-finger tap sequences no longer reliably trigger. Notably, I have “Tap Sequence [1234]” set to cmd-shift-] so I can easily cycle through tabs in a window. In BTT 2.13 and earlier, it worked great.

However, with the newest versions of BTT the tap sequence is unreliable. Looking at BTT’s Live Preview, the tap sequence [1234] sometimes works properly, but other times it registers as “TipTap Right, 3 Fingers Fixed”, sometimes as “TipTap Right, 2 Fingers Fixed”, and occasionally as an unrecognized custom tap sequence.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro trackpad

#### Device information:

Type of Mac:  Late 2013, 15.4" retina MacBook Pro
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.16

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I have temporarily downgraded to BTT 2.13, where tap sequences are working properly.

**Comment by fifafu** [comment]
Thanks for reporting! Could you check whether this is resolved by v2.17 alpha?

**Comment by NevinBR** [comment]
2.17 seems to resolve this issue, thanks!
