### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by jeffmann** [fifafu/BetterTouchTool#1004]
#### Description of bug/feature request/question:
![screenshot_203](https://cloud.githubusercontent.com/assets/26687645/26521343/b7439620-42e6-11e7-8b1a-9959d37fe1e6.png)

I keep getting this randomly, every few days or so. I don't see any pattern to it. Sometimes gestures stop working, sometimes not. Sometimes only some gestures stop working, while others continue to work.

It's been going on for some time, several months. I've already tried re-downloading a fresh copy. There doesn't seem to be anything in the console about it. Restarting BTT clears the problem, until the next time it happens.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad and Magic Trackpad

#### Device information:

Type of Mac: MacBook Air
macOS version: 10.12.5
BetterTouchTool version: 2.17 (637)

**Comment by fifafu** [comment]
That's weird, are you somehow modifying the BTT binary? Otherwise it sounds like your hard disk may start to fail, because that message basically means the BTT binary or other BTT files are damaged.

**Comment by jeffmann** [comment]
No, I'm not modifying the binary, or doing anything unusual that I know of. I have a MacBook Air with SSD drive. Disk Utility First Aid doesn't report any problems, and I haven't noticed any problems with corrupted files.

I just downloaded a fresh copy of BTT 2.17 and compared it to the one in my Applications folder with VisualDiffer, and it says all the file sizes and contents are exactly the same. So I think the application itself isn't damaged. What other files could be damaged, and how can I check them?

**Comment by fifafu** [comment]
Unfortunately the diff won't necessarily help because even a flipped bit would modify the hash and wouldn't be shown in the diff.

I'll keep an eye on this, but I haven't had other reports of such an issue yet (only one or two where it turned out the hard drive was failing)  :-/

**Comment by jeffmann** [comment]
I'm afraid you're mistaken about diff, it can do a binary comparison and would certainly show a flipped bit. Additionally, `codesign -vv` reports:

> BetterTouchTool.app: valid on disk
> BetterTouchTool.app: satisfies its Designated Requirement

I can assure you that my application binary is not corrupt. I guess it's possible my SSD is failing, but I have nothing else to indicate that.

Is there something else I could check? Other files that might be corrupt?

**Comment by fifafu** [comment]
Ah you are right about the diff! 

The Preferences.nib file in the BetterTouchTool bundle is also being checked, it's in the (BetterTouchTool.app/Contents/Resources/Preferences.nib ).

**Comment by fifafu** [comment]
Could you check what MD5 hash is outputted for the Preferences.nib? (Using the "md5 Preferences.nib" terminal command. Current alphas expect a78c377333f7d0c3aa945a5bbf20e346)

**Comment by jeffmann** [comment]
> $ md5 Preferences.nib
> MD5 (Preferences.nib) = a78c377333f7d0c3aa945a5bbf20e346

The recursive diff I did on the application bundle shows that all 1176 items in it are bit-for-bit identical to the freshly-downloaded one. There's no corruption in the application itself.

Just to be clear, this doesn't happen when BTT starts up. It happens at seemingly random times, for no apparent reason. After restarting BTT, it will function as normal for a few days or even weeks.

**Comment by fifafu** [comment]
Very weird.
I just checked the code again and the specific "unexpected error" is only triggered when the md5 of the preferences.nib doesn't match.

BTT checks this in irregular intervals to prevent anybody tampering with it. In case a different md5 is detected BTT shows the message and disables all critical features. 

It seems that for some reason the md5 sometimes returns a wrong value in your case. I'm not sure what could cause this,but I'll look into it again.

**Comment by jeffmann** [comment]
Not all features get disabled. When it happened last time, I clicked the "Ok" button. Some gestures continued to work, like 4-finger swipe up/down mapped to home/end action. Others stopped working, like 5-finger swipe left/right mapped to move right/left a space action. A few minutes later, the "Unexpected Error" message came up again. So, I restarted BTT, and it's been ok since then.

**Comment by jeffmann** [comment]
I wrote above that "Sometimes only some gestures stop working, while others continue to work." But that may not be true. I have 4-finger swipe up/down mapped to home/end action. I just realized that with BTT not running, 4-fingers behaves like 2-fingers, i.e., it scrolls. So I may have thought it was doing home/end, when it was just scrolling up/down on a short page. I'll try to pay more attention, next time it happens, though that may be some time from now. Thanks for looking at it.

**Comment by wongjustin99** [comment]
I just started getting this recently, too. It has happened on both of my Mac laptops within a day. I think it's a bit far-fetched to think that both laptops went corrupt at roughly the same time.

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. Please excuse not being able to solve/reply to this earlier.
