### ISSUE TITLE
After update, BTT will not open

### ISSUE THREAD

**Issue by maudan380** [fifafu/BetterTouchTool#1007]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.
---

#### Description of bug/feature request/question:
I updated just now to the latest version of BTT. As soon as it finished the update it tried relaunching but it immediately quits.

I've tried restarting both the application and the system, to no avail.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Pro 2016 TB

#### Device information:

Type of Mac: TB 2016
macOS version: Sierra
BetterTouchTool version: Latest update 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird. Could you check if there are any crashlogs in the macOS console.app under "user reports"?

**Comment by arielge** [comment]
I have the exact same problem (also TB 2016 with Sierra). Version 2.17 could not stay open for more than a couple seconds, downgrading to 2.16 solved the issue.

Attaching one of the crash logs from console.app
[BetterTouchTool_2017-05-27-222150_Ariels-MacBook-Pro.txt](https://github.com/fifafu/BetterTouchTool/files/1034017/BetterTouchTool_2017-05-27-222150_Ariels-MacBook-Pro.txt)

**Comment by fifafu** [comment]
Ah thanks, are you both using a apple script widget on the Touch Bar? 
I'll upload a fix later today!

**Comment by arielge** [comment]
Thanks!
I indeed have an apple script TB widget.

**Comment by maudan380** [comment]
Yes! Using AppleScript as well.   
  
 Thanks for getting back to us on this so promptly!
  
  
  
  
  
  
  
  
  
  
  
  
  
    
  
  

    
  
  
  
  
  
  
          
  

  
  
>

**Comment by johntdyer** [comment]
Same here...

**Comment by fifafu** [comment]
Would be great if you could test v2.18 alpha (just released)

**Comment by maudan380** [comment]
FYI just updated to 2.20 and it seems to be working fine! 
Thanks for the fix, truly appreciate all you do!
