### ISSUE TITLE
BTT has  reached its user limit in dropbox

### ISSUE THREAD

**Issue by leafonsword** [fifafu/BetterTouchTool#1008]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I try to sync to dropbox,dropbox's offical website show:

> This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

ALL

#### Device information:

Type of Mac: macbookpro
macOS version: 10.12.4
BetterTouchTool version: 2.17

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! It should now allows more users. It's not yet reviewed by Dropbox, thus it will again complain after a 500 user limit is reached, but I hope the review will go through fast.
