### ISSUE TITLE
Hope support Chinese language!

### ISSUE THREAD

**Issue by leafonsword** [fifafu/BetterTouchTool#1009]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hope support Chinese~ 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, unfortunately currently there are no plans to release BetterTouchTool in other languages in the near future.
If I ever implement this, there will definitely be support for Chinese, but it's currently not very high on my TODO list.
