### ISSUE TITLE
Using Command + T to add a tab in Chrome or Safari will set touchbar behavior to show BTT touchbar even when behavior is set to show app default.

### ISSUE THREAD

**Issue by BeatTheFreak** [fifafu/BetterTouchTool#101]
Sorry if the title is hard to understand, but let me try to explain it a little better. 

If I set Chrome's (or Safari's) Touch Bar Behavior to "Show Default App" it will show that apps touch bar once I open it (like it should), but once I create a new tab only using command + T then the BTT touch bar appears and stays there until I hide it (shouldn't happen). 

I'm kind of bad at explaining so hopefully this video I took shows you a better demonstration (https://youtu.be/kc_bVYdTI7o).
In the video I show that Chrome is set to use its default app's touch bar. When I open a tab the setting stays the same and the BTT touch bar doesn't appear (again, it's working like it should), but when I open the tab using command + T then the BTT touch bar appears, which shouldn't happen because I set the Touch Bar Behavior to "Show Default App". 

**What kind of Mac are you using?**

MacBook Pro 2016 Touch Bar 15inch

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which version of macOS are you running?**

macOS Sierra 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Please watch the video if my explanation doesn't make sense (https://youtu.be/kc_bVYdTI7o)

Thank you and keep developing this great app!!!

**Comment by fifafu** [comment]
Hey,

could you check if the behavior has been fixed with the latest update ( 1.967)?

Best,
Andreas

**Comment by BeatTheFreak** [comment]
Hello, 

I just check and found the update and installed it. The update fixed the issue perfectly!

Thanks and developing this great app!!
