### ISSUE TITLE
BetterTouchTool Keep crashing

### ISSUE THREAD

**Issue by JustAnotherPU** [fifafu/BetterTouchTool#1011]
Hey there,

Since couple of days now BetterTouchTool Keep crashing when ever I try to go to preference or even updated it, I am on the last alpha version tried both alpha and regular version same issue.
Also Force Touch on my trackpad seem to be triggered off automatically but when I relaunch BTT is seem to switch on again, dont know what the issue here could you help please ? 

Affected : The app itself (crashing) & Trackpad Force Touch 

Device information:

Type of Mac: MacBook Pro 13' TouchBar 
macOS version: 10.12.5
BetterTouchTool version: Last alpha 

Crashlog attached 
[BetterTouchTool_2017-05-28-205838_MacBook-Pro-de-Badre.crash.zip](https://github.com/fifafu/BetterTouchTool/files/1034436/BetterTouchTool_2017-05-28-205838_MacBook-Pro-de-Badre.crash.zip)

**Comment by fifafu** [comment]
Would be great if you could test v2.18 alpha (just released)

**Comment by JustAnotherPU** [comment]
Trying to update crash as soon as I hit the update button :( 
can you post a direct link here ?

**Comment by fifafu** [comment]
Ah sure. Here you go: https://bettertouchtool.net/releases/btt2.18c.zip

**Comment by JustAnotherPU** [comment]
You Rock man its worked :D 
any info about the issue ?

**Comment by fifafu** [comment]
I moved Apple Script execution to a separate process. I think some Apple Script that was executing in your BTT setup caused the crash (could also have been an internal BTT script)
