### ISSUE TITLE
Switching Magic Mouse Inertia

### ISSUE THREAD

**Issue by sdeluxe** [fifafu/BetterTouchTool#102]
Remember that nasty MS Office 2011 Mac Problem.... in Excel an PowerPoint activated Inertia Scroll setting leads to inadverted scroll actions (_e.g. jumping 10 slides ahead_).

How about **our favourite input tool BetterTouchTool** setting the Inertia on/off ?

Then we might be able automagically switching inertia off when activating MS Office.

**Comment by fifafu** [comment]
Sorry unfortunately BTT can't do that. 

You could however add your office apps to the BetterTouchTool app list on the left. Then you can click the app-specific button and disable single finger scrolling for it..

Or... Just upgrade to office 2016 :-), it's worth it.

**Comment by sdeluxe** [comment]
THX for the info. Unfortunately disabling single finger scroll won’t fix that issue.  

I already upgraded to Office 2016 ( on the machines supporting new OS X versions) and yes, no problem there.

Those machines stuck with 10.6.8   ( Mac Pro 1,1 ) have nevertheless to stick with Office 2011.


Thank you very much, anyway.


Joachim Schlick

**Comment by fifafu** [comment]
Bettertouchtool requires 10.8 anyways (the current versions) :-) so it wouldn't even help to add this
