### ISSUE TITLE
Touchbar funcionality stopped working after restart

### ISSUE THREAD

**Issue by nashbridges** [fifafu/BetterTouchTool#1024]
#### Description of bug/feature request/question:

After a restart instead of customized by BTT control strip I see standard full row (i.e. when you press fn key) control strip. Restarting BTT doesn't help. Disabling Touch Bar support in BTT, restarting it and enabling it again doesn't help.
OS settings for Control Strip is to show app buttons + control strip by default, and to show unfolded control strip on fn.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MBP 15" with touchbar
macOS version: macOS 10.12.5 (16F73)
BetterTouchTool version: 2.20 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://cloud.githubusercontent.com/assets/380913/26716324/a42210b8-4781-11e7-9716-e1062dc203e0.png)

![image](https://cloud.githubusercontent.com/assets/380913/26716359/c45f15c4-4781-11e7-9681-63bb7f920189.png)

**Comment by nashbridges** [comment]
When I switch OS setting to "Show unfolded control strip" by default, when BTT comes in play.

**Comment by fifafu** [comment]
I can't seem to reproduce your issue however one thought:
You seem to have unchecked "Show macOS Control Strip" and "Show BetterTouchTool Icon in Control Strip". This means you'll need to configure some sort of keyboard shortcut or gesture to toggle the visibility state of the BetterTouchTool Touch Bar (using the predefined Action "Toggle BetterTouchTool Touch Bar).

**Comment by nashbridges** [comment]
Maybe I was using non-compatible combination of OS control strip settings and BTT's one (in that case it was not a tech issue, more like a documentation one). However, I do remember that it was working even with that combination, it just after a restart it stopped functioning. Anyway, I'm closing this one.
