### ISSUE TITLE
Restore Saved Mouse Position restores some constant value saved somewhere

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [fifafu/BetterTouchTool#1025]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm trying to get desktop previews to automatically show when revealing mission control with the four-finger swipe touchpad gesture. I realize there's now a built-in option for this, but it breaks the gesture for me (about four in five attempts to open mission control just gives me a fraction of the window animations, then it reverses back to normal desktop before completing), so I'm trying to do the old-school manual way of saving the mouse position, moving it to trigger desktop previews opening up, then restoring the saved position.

Thing is, `Restore Saved Mouse Position` keeps restoring a saved value from a previous `Save Current Mouse Position` action. It seems to change sometimes after I've changed my `Move Mouse to X:x Y:y` command, to another previous value, but it never restores the current position when I start the gesture.

E.g., right now, I have

```
4 Finger Swipe Up : Use Apple Default or do Nothing
    -> Save Current Mouse Position
    -> Delay Next Action by 0.50 Seconds
    -> Move Mouse to X:100.00 Y:2.00
    -> Delay Next Action by 0.50 Seconds
    -> Restore Saved Mouse Position
```
(The actions reflect that I've been trying different strategies to try to fix it, and am trying to figure out exactly what happens)

So, when I start my gesture, the mouse cursor stays where it was for half a second, then it jumps to 100,2 for half a second, then it jumps to 800,2 (a previously chosen value for the `Move Mouse to X,Y` action.

ATM, if I change the `Move Mouse` action to another value, it does indeed first jump to that value, but then it once again ends up at 800,2. 

Even if I quit and relaunch BetterTouchTool, it remembers this old 800,2 position, and keeps "restoring" the mouse position to that in the end.

I tried deleting everything (I think) besides my license from ~/Library related to BetterTouchTool, and clearing the BTT settings, but the behaviour remains the same. It also remembered my gestures when relaunching, which must mean I didn't clean out everything (`find ~/Library -iname '*bettertouch*'`).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Built-in trackpad and magic trackpad

#### Device information:

Type of Mac: 2012 Air 13"
macOS version: 10.12.5
BetterTouchTool version: 2.20 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Ernesto227** [comment]
Same issue here with MBP15 TouchBar on macOS 10.12.5 with BTT 2.20 (641)

**Comment by abertheham** [comment]
+1 running mbp non-retina 13 with magic trackpad (v1)

same macOS and BTT versions as above

**Comment by fifafu** [comment]
Should be fixed later today with a small bugfix release!

**Comment by DanielSmedegaardBuus** [comment]
Is there any ETA of the fix going out in the regular channels? Miss my old functionality :D

Or maybe, do you know which version the bug was introduced? Then I could just downgrade :) Cheers!

**Comment by Shnub** [comment]
Same problem. Seems to have started after updating to 10.12.5. Same basic setup as original poster, BTT 2.20. Cursor rarely lands up on the right spot, mostly either a previously saved position or the one entered as X/Y in the workflow.

The default "Mission Control & Immediately Show Desktop Previews" is also affected.

Right now the best workaround seems to be to have the mouse move to some fixed position (center of screen) instead of restoring from a saved value.

**Comment by DanielSmedegaardBuus** [comment]
Aw man, just got so happy seeing that an update was available, but this bug wasn't part of the fixes :'(

Is it possible to get a link to an older version from before this bug was introduced?

Thanks man :)

**Comment by fifafu** [comment]
Ah I'm sorry, I thought I had fixed that already. It should now be working again in v2.260!

**Comment by DanielSmedegaardBuus** [comment]
Yay! It works again :D Thank you! 👍
