### ISSUE TITLE
crash on wake with external monitor

### ISSUE THREAD

**Issue by gberberoglu** [fifafu/BetterTouchTool#103]
#### Description of your bug/question/feature request...:
BTT Crashes daily, more than once. I suspect it's something to do with external monitors. 

During work, I use mbp with lid closed, connected to external screens. I believe crash happens when I wake up a lid-closed, external monitor connected mbp.

**What kind of Mac are you using?**
early 2014 macbook pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

2x monitor, usb dongle for non-apple keyboard+mouse.

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

see the crash log, I have 50+ of those. first crash with similar trace happened in 14 november 2016. 

[BetterTouchTool_2016-12-13-101326_Gokhans-MacBook-Pro.crash.zip](https://github.com/fifafu/BetterTouchTool/files/648443/BetterTouchTool_2016-12-13-101326_Gokhans-MacBook-Pro.crash.zip)

```
27  com.hegenberg.BetterTouchTool 	0x000000010349ef3b -[BSTDragPointWindowController initWithDisplay:] + 119
28  com.hegenberg.BetterTouchTool 	0x00000001034f9a0d -[BSTDragPointCenter recognizeDisplays] + 1514
29  com.hegenberg.BetterTouchTool 	0x00000001034fa32a -[BSTDragPointCenter applicationDidChangeScreenParameters:] + 583
```

**Comment by fifafu** [comment]
Thanks for reporting!
That's a very weird bug, it seems to happen somewhere in a system framework.

Do you have any plugins for the macOS color picker installed?

**Comment by gberberoglu** [comment]
> Do you have any plugins for the macOS color picker installed?

no.. I don't think I have color picker app at all. I have a custom monitor calibration, with lowered whitepoint.. can it be related ?

**Comment by gberberoglu** [comment]
@fifafu is it possible to capture the crash and restart programmatically ?  that would be a good workaround, instead of me restarting manually everday :)

**Comment by fifafu** [comment]
I think this should not happen in the current versions anymore. If it still does please reopen.
