### ISSUE TITLE
Unable to remove BTT icon from TouchBar

### ISSUE THREAD

**Issue by congruencebrah** [fifafu/BetterTouchTool#1033]
#### Description of bug/feature request/question:
Cannot for the life of me figure out how to remove the BTT icon from my Touch Bar.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro 13" Touch Bar

#### Device information:

Type of Mac: Latest MacBook Pro 13"
macOS version: 10.12.4
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![fullsizerender 70](https://cloud.githubusercontent.com/assets/29169093/26757845/3c01f4c4-490e-11e7-8be7-0cbbf6030333.jpg)

I was poking around the BTT TouchBar header and remember adding a gesture, and then deleting it(gesture list is empty now). The icon just won't disappear and I can't find the option to remove it.

I've also tried going to "Settings > Keyboard > Customise Control Strip" but there's no way to do it there either.

**Comment by fifafu** [comment]
You can disable it in the Touch Bar settings in BTT (go to the Touch Bar tab, then click the "General Touch Bar settings" button.
This may require a restart of BTT to become effective.

![image](https://cloud.githubusercontent.com/assets/8820811/26761560/efbecfb4-4931-11e7-8dd1-a72f16610260.png)
