### ISSUE TITLE
Question/Request: Keyboard shortcut for special signs

### ISSUE THREAD

**Issue by rootofans** [fifafu/BetterTouchTool#1035]
Dear users,

I have a rather simple question regarding a specific feature of Better touch tool.
Is there any chance that one can create a keyboard shortcut, which can automatically paste a special sign, which is not included in the alt+xyz or alt+shift+xyz combinations?
Specifically I'd like to have a alt+whatever shortcut to get the ↑ sign without always picking it from the extra keyboard in the settings.

If I'm in the wrong section of this forum, please excuse me.
Thanks in advance.

Greets

**Comment by fifafu** [comment]
Hi,

you can use the "Insert / Paste Custom Text" predefined action!
