### ISSUE TITLE
"Hide BetterTouchTool Touch Bar if nothing to show" doesn't work.

### ISSUE THREAD

**Issue by realdannys** [fifafu/BetterTouchTool#1036]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have this option ticked so I would expect that in apps where you don't have any Touch Bar actions configured it would close the touch bar and show the default macOS controls (like show app default touch bar does on a per app basis) but unfortunately the blank BTT touch bar remains open.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 15" MacBook Pro Touch Bar
macOS version: 10.12.5 (16F73)
BetterTouchTool version:  2.20

**Comment by fifafu** [comment]
Do you have anything defined globally for the Touch Bar? Or do you maybe have an app-specific override configured?

![image](https://cloud.githubusercontent.com/assets/8820811/26761907/8f48f766-4938-11e7-97ba-d1c0c2738688.png)


"Unfortunately" I can't seem to reproduce this issue on my machines.

**Comment by realdannys** [comment]
Arghh, that was it - I had an empty entry in Global! Doh, silly me.

Thanks for the quick reply, I should have checked that!
