### ISSUE TITLE
Global icon in BTT TouchBar

### ISSUE THREAD

**Issue by sergiosala** [fifafu/BetterTouchTool#1037]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I see a Global Emoji after my configured icons in the TouchBar. Why?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MBP Touch Bar

#### Device information:

Type of Mac: Macbook Pro late 2016
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

https://cl.ly/kkgY

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You probably long pressed the BTT icon.
The global icon means that global actions will be shown regardless of any settings that may hide them. This can be triggered by long pressing the BTT icon in the Touch Bar.
