### ISSUE TITLE
[Alpha Bug] Trackpad three click → middle click

### ISSUE THREAD

**Issue by patriamsetis** [fifafu/BetterTouchTool#104]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
The latest alpha version broke the Trackpad three click → middle click. Can't middle click in Safari now. 

**What kind of Mac are you using?**
iMac 5K 2015
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Trackpad 2

**Which version of macOS are you running?**
10.12.2

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

which version of BTT are you running?

**Comment by fifafu** [comment]
Ah I think I have identified the bug already. Will release an update later!

**Comment by patriamsetis** [comment]
Hey,

The latest alpha (1.967 (557)). I just installed it a few minutes ago. Tried restarting the app and safari. I thought the palm rejection was causing the problem and turned them off but no luck. 

Just received your other email — sounds good, thanks!

John


On December 13, 2016 at 1:01:01 PM, Andreas Hegenberg (notifications@github.com) wrote:

Hey,

which version of BTT are you running?

**Comment by fifafu** [comment]
Should work again in 1.968 (559)
