### ISSUE TITLE
Mission Control not working

### ISSUE THREAD

**Issue by TECHATTACK** [fifafu/BetterTouchTool#1040]
Since Version 2.20 Mission Control is not working. If I move up Window to upper edge, it wants to snap fullscreen, but does not trigger Mission Control. (No matter how long I wait).

Is there a fix for that or do I miss something? (I use OS X Sierra 10.12.5)

**Comment by fifafu** [comment]
I don't think there has been a change to this in v2.20, however BTT by default makes it harder to trigger mission control while window snapping is enabled. It requirea more movement to show mission control.

You can disable this behavior in the advanced window snapping preferences in BTT.

**Comment by TECHATTACK** [comment]
OK, and whats the name of this option? (To disable "the more movement to activate" function)
