### ISSUE TITLE
[Bug] Removing app setting from one tab removes it from another

### ISSUE THREAD

**Issue by nashbridges** [fifafu/BetterTouchTool#1043]
#### Description of bug/feature request/question:

1. Go to "Keyboard" tab.
2. Add app specific setting for Iterm.
3. While "Iterm" is selected, switch to "Touchbar" tab.
4. Remove empty section for "Iterm"
5. Switch to "Keyboard" tab, "Iterm" setting is lost.

#### Device information:

Type of Mac: MBP 15" with touchbar
macOS version: 10.12.5
BetterTouchTool version: 2.20 (641)

**Comment by fifafu** [comment]
Sorry for not replying earlier :-(

App settings are shared across input devices. This can not be changed.

In case you still have questions, please comment - I'm currently closing some older issues.
