### ISSUE TITLE
Home, End, Page Up, and Page Down not functional

### ISSUE THREAD

**Issue by dpatel19** [fifafu/BetterTouchTool#106]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Home, End, Page Up, and Page Down not functional. 

My keyboard has button for Home, End, Page Up and Page Down but these are not functioning properly with BTT. If I set the keys to trigger these actions, they seem to have no action (does not move cursor to beginning of page, does not page up or down, etc.). However, it does break the function of Cmd + Tab'ing between different applications. Quite an odd bug.

![no work](https://cloud.githubusercontent.com/assets/9096200/21162668/a29df5dc-c15c-11e6-9777-470fc924b19c.png)

Above is screenshot of the BTT config. It seems that the buttons are being read as arrow inputs. Not a huge issue, but it would be great if they worked properly.

Thanks!
**What kind of Mac are you using?**
MacBook Pro 2011 15"
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Logitech Keyboard

**Which version of macOS are you running?**
Version 10.11.4 

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Could you try if recording them while pressing FN changes this?

**Comment by dpatel19** [comment]
Using a shortcut of <fn+Home> yields the same as <Home> (up-left arrow). The FN key doesn't seem to change the input.

**Comment by JBHollywood** [comment]
Having this problem with Page Up/Down. I have gotten BTT to do Home/End (as well as a bunch of other stuff, thanks) but a no-go on this one. This is on a 2017 27in iMac (18,3) w/MacOS Sierra 10.12.6, using Logitech G19 keyboard and G9x mouse in place of Apple keyboard & mouse. Using Logitech Gaming Software (LGS) 8.94.35.

**Comment by JBHollywood** [comment]
Spoke too soon. I went back and did the default keyboard setup in System Preferences and now Page Up/Down work globally.
