### ISSUE TITLE
Window Moving & Resizing

### ISSUE THREAD

**Issue by DVD43** [fifafu/BetterTouchTool#1060]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Window Moving & Resizing is my favorite window function in BetterTouchTool. Why does it consistently stop working after about 10 minutes?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: iMac 27" 5K 2015
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have a valid license installed?

**Comment by DVD43** [comment]
Yes, the software is registered with a valid license. I’m a long-time BTT user and one of the first to join you in the switch to a paid application.

Until recently, I have mostly ignored BTT’s window management features since, being a writer and editor, I am mostly keyboard-oriented. Also, because I have a large display, I prefer the freeform style of the Moving & Resizing to the static partitioning that is so popular. For years I used Zooom 2 to manage windows, until the developer shuttered his business last year. This year, I have been experimenting with several replacement candidates: Windownaut, Flexiglass, MaxSnap, and most recently BetterTouchTool.

Once I looked over the window management capabilities of BTT in earnest, I discovered the Moving & Resizing feature. Unfortunately, if I allowed it to sit idle long enough (not actively using it), it would stop working. The remainder of BTT continues to function, but the Moving & Resizing fails. This has happened to me half a dozen times now. Today, it worked for about half an hour, since I was actively moving windows. But then I settled down to read a lengthy internet article, and when I returned to moving windows, there was no response. I checked the mouse taps and clicks, and they were still functional, but the Moving & Resizing was not. Restarting BTT brings back the function — until it dies again.

**Comment by fifafu** [comment]
Very weird, I haven't had similar reports yet, but I'll try to reproduce the issue!

**Comment by DVD43** [comment]
The past several days I have experimented with turning the BTT window management off and using BetterSnapTool instead. No problems there. So it seems that BTT definitely has a problem.

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
