### ISSUE TITLE
BTT often stops working / kills itself silently (nearly daily)

### ISSUE THREAD

**Issue by gfarrell** [fifafu/BetterTouchTool#1065]
#### Description of bug/feature request/question:

BTT often stops working / kills itself: I'll often try to use some BTT-enabled feature on my mac and find that it's stopped working. Sometimes BTT is still running in my menu bar, sometimes it has silently killed itself. Either way I have to (re)start it to get my gestures / other features back.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad (and keyboard shortcuts too)

#### Device information:

Type of Mac: MacBook Pro (late 2014)
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Logs:
[log-62AA12.txt](https://github.com/fifafu/BetterTouchTool/files/1068751/log-62AA12.txt)
[log-64CF94.txt](https://github.com/fifafu/BetterTouchTool/files/1068752/log-64CF94.txt)

**Comment by fifafu** [comment]
Please try upgrading to v2.20 first.

**Comment by gfarrell** [comment]
@fifafu I did check for updates before posting but it said I was up-to-date.

![screen recording 2017-06-12 at 05 11 pm](https://user-images.githubusercontent.com/314331/27043539-5406a76a-4f92-11e7-8ce3-782a4c07a648.gif)

**Comment by gfarrell** [comment]
And it does so even if I check "Update to alpha versions too" or if I click "check for alpha version updates"

**Comment by fifafu** [comment]
That's weird, maybe I messed up the update description file yesterday. I'll check that when I come home from work! 

You are definitely running macOS 10.12.x? (Asking because I haven't rolled out the update for older versions yet)

**Comment by gfarrell** [comment]
Yup, copy-pasted the osx version number from system info. Will wait to see if the new version has the same crashing problem (fingers' crossed).

**Comment by Bathtor** [comment]
I have a similar issue with BT 2.20 on OS X 10.12.5 (MacBook Pro (Retina, 13-inch, Mid 2014)).
I can't say exactly since when it happened...I think the last OS X update, but I don't have any objective evidence for that.

Debug Logs:
[log-7A7A10.txt](https://github.com/fifafu/BetterTouchTool/files/1081423/log-7A7A10.txt)
[log-199558.txt](https://github.com/fifafu/BetterTouchTool/files/1081424/log-199558.txt)

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
