### ISSUE TITLE
Trigger active window or window under cursor

### ISSUE THREAD

**Issue by iPlayhard** [fifafu/BetterTouchTool#1068]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
(Section Other)
Please, can u add Triggers to **active window** or/and **window under cursor** 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard, Trackpad, NormalMice

#### Device information:

Type of Mac:MacBook Air 13
macOS version: 10.12.5
BetterTouchTool version: 2.20 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Now i can only resize or move windows under cursor but it may very useful to send shortcuts to window under cursor or active window(s) of opened apps

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry for not answering earlier... In case it is still relevant for you, you should be able to do this by using the predefined action "Activate window under cursor" and then sending a shortcut:

![image](https://user-images.githubusercontent.com/8820811/38250018-eed6d8f2-374d-11e8-8d70-639d85a68d71.png)

Alternatively you can use the predefined action "Send shortcut to specific application" and check the "send to application under cursor" option.

![image](https://user-images.githubusercontent.com/8820811/38250053-093014c0-374e-11e8-9268-d74214af239c.png)
