### ISSUE TITLE
Add option to only change raw inputs for normal mouse scroll reversal

### ISSUE THREAD

**Issue by zrgravity** [fifafu/BetterTouchTool#1069]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
It would be useful to have an additional option to only reverse normal mouse scroll for raw inputs. This would exclude remote desktop protocols and Synergy. See https://superuser.com/questions/382024/reversing-scroll-direction-across-synergy-connection for an example from another program.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal mice

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
With the next alpha later today or tomorrow you'll be able to enable a hidden setting using this terminal command (while BTT is quit):

```
defaults write com.hegenberg.BetterTouchTool BTTDontReverseSyntheticScrollEvents YES
```

I haven't tested it but it should then only reverse hardware generated events. (I don't know what Raw event should mean)
