### ISSUE TITLE
Centre mouse in a currently active window

### ISSUE THREAD

**Issue by nikitavoloboev** [fifafu/BetterTouchTool#107]
#### Description of your bug/question/feature request...:
I wish I can map a gesture to centre my mouse pointer to currently selected window. It would always be centred despite the window size. I can't seem to do it with 'Move Mouse to Position' action as when I change window to different size, it would move the mouse not to the centre.

I want a reliable action that will move the mouse pointer to the centre of currently active window.

I can do this in Keyboard Maestro app like so : 

![2016-12-14 at 01 50](https://cloud.githubusercontent.com/assets/6391776/21165468/ce53c498-c19f-11e6-9be8-5b040bfa6e69.png)

But I don't want to map a key to that and then call it from BetterTouchTool, it would be nice if I could map the gesture to this straight away. :)

**Comment by fifafu** [comment]
You currently can't center it, however you could e.g. move it to the top left of a window.

To do this, use the "Move Mouse to Position" predefined action and check the "use relative position" checkbox.

![image](https://cloud.githubusercontent.com/assets/8820811/21194404/2eaba0aa-c230-11e6-8c25-d1d0a0c1c576.png)

**Comment by fifafu** [comment]
The move mouse to position action can now use the center of a window as base.
