### ISSUE TITLE
"Disable BTT" returns to enabled on every awake from sleep

### ISSUE THREAD

**Issue by knoajp** [fifafu/BetterTouchTool#1072]
1. I click "Disable BTT" on the menu.
2. Mac goes to sleep.
3. Mac awakes.
4. BTT is being enabled.

BTT 2.20 on Mac OS X El Capitan

**Comment by snz2** [comment]
This seems to be related to a bug where the beeping sound is heard on the MacBook during sleep.
Of course, I also disable the Mac after it has been disabled.
It is a very uncomfortable bug to hear a beep every time you sleep.

**Comment by fifafu** [comment]
@snz2 no, this is not related. Also I'm pretty sure BTT doesn't cause a beeping (unless you have done specific triggers setup that could cause this). While sleeping BTT doesn't do anything at all.

**Comment by snz2** [comment]
@fifafu The problem I'm talking about is that after btt alpha was uploaded
In fact, if you exit btt completely, you will not hear a beep.
The btt release version is intermittently unresponsive, and can not be used.
Also, can it be said that it is irrelevant that btt has changed from off to on since the slip?

**Comment by snz2** [comment]
@fifafu I am sorry to see that my MacBook trackpad was broken.

**Comment by fifafu** [comment]
Ah did you get it replaced? So I can close this issue, correct?

**Comment by snz2** [comment]
@fifafu But the issue of knoajp and my problem is not another problem?
If you still seem to be close, take care.

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
