### ISSUE TITLE
Chrome browser tab drag doesn't snap

### ISSUE THREAD

**Issue by yeahforbes** [fifafu/BetterTouchTool#1075]
#### Description of bug/feature request/question:

Snap areas (corners and custom areas alike) are not active when dragging a Chrome browser tab. When a Chrome browser window only has 1 tab, dragging a tab is very similar to dragging the entire window, but with a bit more transparency effect. When a Chrome browser window has multiple tabs, dragging a tab makes a second window containing that 1 tab, and that too is like dragging a window but with a bit more transparency effect. It would be great if snap areas were active during this drag.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All mouse / trackpad type devices.

#### Device information:

Type of Mac: MacBook Pro
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.20 (640)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Using Chrome 58.0.3029.110 (64-bit) but any similar version should have the same experience. Workaround for a 1-tab window is trivial: start dragging from elsewhere instead of from the tab, and use the snap area. Workaround for popping a tab out of a multi-tab window is more tedious: drag the tab, let go, drag the now-1-tab window, and use the snap area.

**Comment by fifafu** [comment]
Sorry, unfortunately this is a system limitation. BTT can only snap real windows, the tabs won't react to any resizing commands because there is no API for this.
