### ISSUE TITLE
"2 Finger Swipe activate" in Finder and System Preferences

### ISSUE THREAD

**Issue by RyosukeOK** [fifafu/BetterTouchTool#1078]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

  - "2 Finger Swipe Right / Left" in Finder and System Preferences does not work.

  - Each shortcut key `⌘ ]` `⌘ [` can be activated.

  - My setting is set as follows.

    - Finder

      [![BetterTouchTool_Finder][1]][2]

    - System Preferences

      [![BetterTouchTool_System_Preferences][3]][4]

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

- Tried : It works when I replace “2 Finger Swipe Right / Left" with “3 Finger Swipe Right / Left”.

    →Error : Since other applications are "2 Finger Swipe", I want to unify them.

best regards

  [1]: https://i.stack.imgur.com/Bcndtm.png
  [2]: https://i.stack.imgur.com/Bcndth.png
  [3]: https://i.stack.imgur.com/d2J64m.png
  [4]: https://i.stack.imgur.com/d2J64h.png

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cygvis** [comment]
you don't mention what your trackpad settings are in system preferences...

**Comment by RyosukeOK** [comment]
Thanks!　I agree with you @cygvis !
The way to activate the shortcut key by the trackpad and move the page is indirect and roundabout, it is better to set "3F Swipe Left/Right (Page Forward/Back)" by global setting.
 By the way, "2 Finger Swipe Right / Left" with `⌘+[/]`  in Finder and System Preferences works in High Sierra (10.13.1).

### Solution
1. System Preferences -> Trackpad -> MoreGestures
<img width="668" alt="trackpad" src="https://user-images.githubusercontent.com/25970017/33974936-a4ab941e-e0ce-11e7-9d98-71175fc451fc.png">

2. BetterTouchTool -> Global
<img width="1015" alt="blank_skitch_document" src="https://user-images.githubusercontent.com/25970017/33974942-acce21e8-e0ce-11e7-823e-0a741a20431c.png">
