### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by conjugatedverb** [fifafu/BetterTouchTool#1079]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Screen entirely frozen

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version:  10.13
BetterTouchTool version: 1.7

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I know this is a beta OS, but I want to let you know that I have had to stop using BetterSnapTool for now until there is resolve. At first I thought my computer was going bad, but once I quite BetterSnapTool it stops happening and it is the only change I have made. My whole screen stalls and I can do nothing until what I assume is a spin dump and I gain control of my workstation again. I currently cannot get into console to verify this because it crashes on opening, but this is the only issue I am having.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, I'm also using 10.13 and haven't had any issues yet. I'll keep an eye on this, maybe it's just a beta bug.

**Comment by conjugatedverb** [comment]
Could be. At first I really thought something was terribly wrong, but with the app closed all is well. Lets hope the next release fixes it.

**Comment by fifafu** [comment]
Do you still encounter this issue?

**Comment by conjugatedverb** [comment]
I do. I still can’t use better snap tool in 10.13. 

It only takes about 5 minutes before my whole computer freezes and I have to restart my computer by holding the power down. If I keep it shut I don’t experience the issue at all.

**Comment by fifafu** [comment]
Very strange. Do you have other apps in the Accessibility list in System PReferences => Security & Privacy => Accessibility?

I can see that there are quite a few BST and BTT users on High Sierra already and I haven't had other similar reports yet, thus I believe it's not a common issue. Maybe there is some sort of conflict with another tool?
