### ISSUE TITLE
Shortcut triggers twice

### ISSUE THREAD

**Issue by inket** [fifafu/BetterTouchTool#108]
#### Description of your bug/question/feature request...:
In Trackpad/Global, I have this shortcut to open links as new tabs in apps:
<img width="468" alt="screen shot 2016-12-14 at 10 20 20 a" src="https://cloud.githubusercontent.com/assets/679224/21166146/092d8ca6-c1e7-11e6-9451-db66e4e724fa.png">

However, most of the time it triggers twice (2 tabs open up)

**What kind of Mac are you using?**
15" MacBook Pro with Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MBP Trackpad

**Which version of macOS are you running?**
10.12.1 and 10.12.2

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Both 1.963 and 1.968 have this issue.

**Comment by ryantrip** [comment]
I've also experience this issue (or something similar) with assigning a two finger click shortcut to preform a right click action. The right click menu appears, then disappears.

**Comment by fifafu** [comment]
@ryantrip have you disabled the system right click? I

**Comment by ryantrip** [comment]
The option is enabled.
<img width="780" alt="screen shot 2016-12-13 at 10 33 15 pm" src="https://cloud.githubusercontent.com/assets/24561062/21171963/2e76cf76-c184-11e6-8804-4a25a865269e.png">

**Comment by fifafu** [comment]
@inket unfortunately I can't reproduce your error on any of my machines. 

Are you maybe using three finger drag? (Altough I think it shouldn't work at all in that case)

**Comment by deepsweet** [comment]
absolutely the same here, ok with the latest stable and buggy with the latest alpha.

**Comment by maudan380** [comment]
I can confirm this happens to me as well - I am using 4 finger tap for this.

**Comment by fifafu** [comment]
Ha, thanks! I can reproduce it with the 4 finger tap :-) will release a fixed alpha later!

**Comment by maudan380** [comment]
Seems to be working now fine after update! at least for me. Thanks Andreas!

**Comment by fifafu** [comment]
@maudan380 thanks (that was a quick and dirty fix, I'll look deeper into it tomorrow)
