### ISSUE TITLE
Trackpad Stops working at all or simply behaves erratically.

### ISSUE THREAD

**Issue by villancikos** [fifafu/BetterTouchTool#1080]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Trackpad goes wild randomly. I'm not entirely sure if this is BTT related but so fat I exhausted all my options. Clean instal of macOS Sierra, replacing old battery, replacing trackpad. 
No success whatsoever. Trackpad randomly starts to move on "opposite" directions. If I go to the Upper Left corner the Arrow Cursor goes to the Lower Right corner and viceversa.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Trackpad (not bluetooth but embedded).

#### Device information:

Type of Mac: MacBook Pro 15'' Early 2011 (model 8,2, vintage I think is called now :( )
macOS version: Sierra 10.12.5 (16F73)
BetterTouchTool version: 2.21

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I use to restart the driver by typing: 
`sudo kextunload /System/Library/Extensions/AppleUSBMultitouch.kext` to disable
`sudo kextload /System/Library/Extensions/AppleUSBMultitouch.kext` to enable again

But now won't work, throws Kernel Panic after Restarting.
Also doing a PRAM Reset (Alt + Command + P + R at startup sometimes restarts the behaviour). Also disabling BetterTouchTool before restarting the computer tends to work that's why I feel is related.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If possible please check if the live view in BTT shows erratic touches when this happens. If so, your trackpad needs to be replaced.

**Comment by villancikos** [comment]
@fifafu  I replaced my trackpad and battery. The issue still exists but my theory is going more towards the power adapter than your app. So I guess we can close this issue 🤓  sorry for the troubles!
