### ISSUE TITLE
Support for Microsoft Sculpt Ergonomic Mouse windows button

### ISSUE THREAD

**Issue by ksmoran** [fifafu/BetterTouchTool#1081]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The Microsoft Sculpt Ergonomic Mouse has a blue windows button that I would like to remap. Currently, BTT does not recognize the click of the button, making it so that I cannot assign an action to it. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Microsoft Sculpt Ergonomic Mouse

#### Device information:

Type of Mac: 15" MacBook Pro with TouchBar (1st gen)
macOS version: 10.12.5
BetterTouchTool version: 2.20 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Product: https://www.amazon.com/Microsoft-Sculpt-Ergonomic-Mouse-L6V-00001/dp/B00D68ZVY8

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by saxon48** [comment]
Exact same issue here.

Device information:

Type of Mac: Late-2013 MacBook Pro (13")
macOS version: 10.12.5
BetterTouchTool version: 2.251 (649)

**Comment by fifafu** [comment]
Sorry, unfortunately BetterTouchTool only supports mice that send generic button events. Proprietary buttons are not supported. 

Maybe you can bind the button to some generic mouse button in the microsoft settings(if there is such a thing)? Otherwise there probably isn't a solution to this.
