### ISSUE TITLE
Clipboard action

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#1085]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Nice job on the new clipboard history action.  Thanks!  Currently, you can only select a single item in the clipboard history window for pasting. Probably already in your plans, but it would be good if you could use Shift and Control keys as usual to select any set of items for pasting. Ideally, order of selection would determine order of pasting.

#### Device information:

Type of Mac: 13" 2016 MBP
macOS version: 10.12.5
BetterTouchTool version: 2.22

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by shreezus** [comment]
The new clipboard history action is fantastic! Currently I'm using Paste for clipboard management as it shows image previews and supports horizontal scrolling. Looking forward to seeing BTT improve & keep growing!

**Comment by fifafu** [comment]
I have just added multi-select to the latest alpha (v2.24, build 646) , let's see how well this works.

Order of pasting is defined by order of selection.

**Comment by CappyD** [comment]
Nice work.  Thanks Andreas.  I found some issues with a little testing.  I selected some text, then an image, then some more text. The action nicely shows all three.  But shouldn't the display on the right show all three?  I see only the first text.

If I use shift-click to select all three and then hit return to paste into Notes, I get the first text and the image, but not the last text selection.  If I select the image, then the 2nd text, then the first text (using command clicks), then hit return, all three appear (in correct order). If I select the 2nd text, then use shift-click on the first text to select all three, then only the two texts appear (in correct order). Maybe a problem with the time involved with pasting?

Also the names in the paste selector could maybe be better.  Could you use the same ones as appear in Notes or Pages:  Paste and Match Style and Paste and Retain Style ? I'm not sure what font would be implied by "paste as plain text" in an app like notes.

Some obvious delete method is needed. Selecting one item and hitting the delete key works, but if you select several and hit delete then only the last item is deleted. It would be good to have the standard red circle with a dash or x in each item that can be clicked to delete it, or maybe allow the standard two-finger swipe to reveal a red delete.

**Comment by fifafu** [comment]
@CappyD ah yes I have only added cmd selection, shift is not yet supported, I should disable it for now.

Also the right side will always only show one item, this probably won't change because it's complicated to mix different content types and I want to keep this as simple as possible.

It really pastes plain text and doesn't match anything, it's up to the receiver app what to do with this :-)

Good point about deleting multiple, I'll add that.

**Comment by CappyD** [comment]
Ok, thanks. Yeah, kinda figured the right side might not be able to show a mix. not a big problem. So then it's not clear how the "with format", "normal", and "as plain text" types are supposed to differ. somehow that needs to be clearer if they are all needed. I assume you are sending the text with or without the formatting it had when copied, so do you just need "paste" and "paste formatted"?

**Comment by fifafu** [comment]
Jup, renaming "normal" to "with format" might me a good idea!

**Comment by CappyD** [comment]
But you've got three pastes now: "with format:" (need to drop the colon), "normal", and "as plain text". shouldn't there just be two: "with format" and "as plain text"?

By the way, moving the sliders in the clipboard action's settings page shows numbers like 100.01010 instead of integers.  also, on first use the second slider number shows "500", but when you move it and slide it back all the way right it shows "100".  It won't be clear to the user (and not to me) what distinguished "small" from "bigger".

**Comment by fifafu** [comment]
The "paste with format:" was just the title lf the menu :-) I have renamed that in the latest alpha, should be clearer now.

Bigger items are things like pictures that take more memory, I'll collect some real world data about the performance and maybe remove the sliders completely  in the future. You can also ignore the number formatting, I was just too lazy to add rounding.

**Comment by CappyD** [comment]
The paste menu looks better/clearer in 2.25, but just hitting Return seems to do paste with format, so why does is that menu item show command-Return icons? I suspect you want to drop the command icon in front of the Return icon.

**Comment by fifafu** [comment]
Yes, return and paste with format do the same.
However return can't work while the text view or searchbox is active, thus I additionally added the cmd + return which always works :-)

**Comment by brsanthu** [comment]
While we are in the topic of clipboard, I noticed that it keeps the duplicate entries. For ex., if I copy "abc" multiple times, it keeps multiple copies which can be avoided. While pasting it kind of confuses as multiple entries show up.

Thank you for this amazing feature. I used to use a separately paid app but it was nowhere as good as the one you included.
