### ISSUE TITLE
BTT crashing after recent update

### ISSUE THREAD

**Issue by wfilled** [fifafu/BetterTouchTool#1086]
Hi
BTT crashes and menubar icon disappears after launch (including startup launch). Reopening briefly shows icon before disappears. 

If I open it a second time in the short time window before it disappears, I can open the settings menu, where I can edit shortcuts etc. At this point the icon remains in the menubar (and the app works). Restarting the app causes the standard "BTT has quit unexpectedly". The bug report is attached. This dialog shows up repeatedly until "BTT relaunch" is quitted from activity monitor

Type of Mac: Early 2015 MBP
macOS version: 10.11.6
BetterTouchTool version: 2.22

---

Cheers

[BTT crashing 2017-06-17.zip](https://github.com/fifafu/BetterTouchTool/files/1082670/BTT.crashing.2017-06-17.zip)

**Comment by Whizzbizz** [comment]
I have exactly the same problem. After a re-install, BTT works for, say, 1 day, then the problem reoccurs.

**Comment by fifafu** [comment]
Ah sorry, the problem will be fixed tomorrow. (The latest alpha version is not compatible with 10.11, only with >= 10.12)

You can also disable alpha updates.

**Comment by Whizzbizz** [comment]
Thank you!

**Comment by Whizzbizz** [comment]
No more problem here after updating to BTT 2.2.5 (648).
