### ISSUE TITLE
Informational displays such as current Spotify songs, other app implementations?

### ISSUE THREAD

**Issue by sgript** [fifafu/BetterTouchTool#1089]
##---

#### Description of bug/feature request/question: 

I'm not sure if this is something that would be possible here, but it would be very cool to be able to see displays for iTunes or Spotify of the current playing song for example on the touchbar.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch bar.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

this can be done using apple script, see: https://github.com/fifafu/BetterTouchTool/issues/308
