### ISSUE TITLE
Defined icon overlaps BTT icon 

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#109]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
With 1.968, the left-most touch bar button (created for an app with no touch bar) now overlaps the BTT icon when the "show BTT touch bar, hide system control strip" option is on.  If I then set the "touch bar shows: app controls" option in the system keyboard settings, now the BTT touch bar I defined does not show at all.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks for reporting! That only happens if the "show esc button" option is disabled in the general touch bar settings in BTT, correct?

**Comment by fifafu** [comment]
Fixed with next alpha
