### ISSUE TITLE
BTT Magic Mouse speed still broken?

### ISSUE THREAD

**Issue by Ariozo66** [fifafu/BetterTouchTool#1090]
Magic Mouse speed on 2017 MacBook Pro/Sierra

Magic Mouse Speed don't work on my new 2017 macbook pr with Sierra. Can slide it, but nothing get faster or slower.

Type of Mac: 2017 MacBook Pro 15"
macOS version: 10.12.5
BetterTouchTool version: 2.21

**Comment by fifafu** [comment]
Yes, unfortunately the speed slider only works until macOS El Capitan. I'll add a info message to it soon.

**Comment by eljeffe58** [comment]
Are there plans to let BTT increase the speed over MacOS preferences maximum speed?
