### ISSUE TITLE
Corner click sometimes doesn't register until tapping on corner again

### ISSUE THREAD

**Issue by mauricelam** [fifafu/BetterTouchTool#1096]
#### Description of bug/feature request/question:
I set up top-right corner click to close the window under cursor (or rewire to Command-W in some apps).
Sometimes when I click the top right, the click doesn't get registered until I tap the corner of the trackpad again. It doesn't seem to matter how light the second touch is, as long as the first click is hard enough.

More specifically,
1. Click top right of trackpad until feedback (performing a really short click has a higher chance of reproducing the issue)
2. Notice that the click doesn't get registered. Neither as a normal click nor as a close-window event
3. Now tap on top right of the trackpad really lightly (no haptic feedback).
4. Observe that the window under the cursor is now closed.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad (force touch)

#### Device information:

Type of Mac: MacBook Pro Late 2016
macOS version: 10.12.5
BetterTouchTool version: 2.20 (640)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think this should be fixed, in case it still happens please comment again.
