### ISSUE TITLE
Finder specific actions

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#11]
Is it possible to make touchbar actions specifically for when on finder or even the desktop?

**Comment by fifafu** [comment]
You can just select finder in the application list on the left :-)

In the preferences you can define whether global actions should always be shown

**Comment by pallavmac** [comment]
Finder isn't in the application list however...

**Comment by fifafu** [comment]
By the default it should be, however you can always add it manually in case it's gone :-)

It's located in /System/Library/CoreServices/Finder.app

**Comment by fifafu** [comment]
BTW: there will soon be an option to trigger BTT actions only for windows which's title contain a configurable string. This will also work for Touch Bar actions and allow some more customization.

I'm closing this issue for now, but if you have further issues with adding Finder, please let me know.
