### ISSUE TITLE
Mapping keyboard shortcuts using the fn button?

### ISSUE THREAD

**Issue by Jmz0** [fifafu/BetterTouchTool#110]
Macbook 12" early 2016

internal keyboard

Sierra 10.12.1

I tried to map my internal keyboard to match some shortcuts that are present on my external keyboard through firmware, such as binding fn+j as left, fn+k as down, etc.

However, while the trackpad shortcuts can trigger an fn shortcut, I can't seem to map a new fn shortcut. Is this a limitation of the OS itself?

Thanks!

**Comment by fifafu** [comment]
Yes, currently you can only use FN with the key sequences feature of BTT, but not with actual shortcuts. It's a limitation by the system, but maybe I'll add a workaround in the future!
