### ISSUE TITLE
How do I get BTT to replace my global Touch Bar?

### ISSUE THREAD

**Issue by donpinkus** [fifafu/BetterTouchTool#1103]
I want to use BTT to replace my global touch bar controls.

Here is what I did:

1. clicked "TouchBar" in the top navigation
2. clicked "Global" in the side navigation
3. Added two touchbar actions

What should I do now? There is no obvious action.

My touchbar hasn't changed.

![screen shot 2017-06-20 at 5 45 03 pm](https://user-images.githubusercontent.com/987092/27362064-6c54a854-55e0-11e7-8368-16be58f794ba.png)

**Comment by brantwedel** [comment]
It must replace the entire control strip, but the following setup will allow you to switch between native TouchBar functionality and BTT Functionality quickly:

Click "General Touch Bar Settings" on the top right, then uncheck "Show macOS Touch Bar" and uncheck "Allow System Apps like iTunes xCode to replace the BTT".

I also added another TouchBar Button with the action of "Toggle BetterTouchTool Touch Bar" so I could easily switch back and fourth for apps where I wanted to use native TouchBar functionality.

I think there is a way to automatically disable Better Touch Tool Touch Bar per app by clicking on the "App Specific" dropdown on the bottom left, if you like the native touch bar support for a particular app as default.
