### ISSUE TITLE
System two finger right click disabled

### ISSUE THREAD

**Issue by ryantrip** [fifafu/BetterTouchTool#111]
When using BTT with my 2016 13" MacBook Pro with the built-in trackpad, my default two finger right click becomes disabled. I can re-enable it by select the "Do NOT override the system's default two finger haptic response", but the haptic response is not default. It set it to double feedback which feels very strange. I do not have any actions in my profile that are using the two finger click gesture that could overwrite the system setting.

The ticket for the "[...]system's default two finger haptic response" option is here:

https://github.com/fifafu/BetterTouchTool/issues/112

**Comment by fifafu** [comment]
Mh, do you have a two finger click configured in BTT?
What version of BTT are you running?

(I can reproduce the double-response issue and have just fixed it, however when not checking that option everything seems to work fine here.)

**Comment by ryantrip** [comment]
When I submitted this issue, I had no two finger click shortcuts configured in BTT. Currently, I do have one configured as a workaround to use two finger right click (with the system option for two finger right click disabled). If I remove my shortcut in BTT and enable the system two finger right click however, I cannot active the system native right click command. The trackpad with respond with a haptic response, but no action takes place. Only the ""[...]system's default two finger haptic response" option re-enables the right click action (or my workaround).

**Comment by fifafu** [comment]
Very weird, after removing the shortcut from BTT, did you re-enable the right-click in System Preferences?

**Comment by ryantrip** [comment]
Yes. The System Preferences option was enabled, and the BTT shortcut was deleted.

**Comment by fifafu** [comment]
Which version of BTT do you run?

**Comment by ryantrip** [comment]
Version 1.963 (552)

**Comment by fifafu** [comment]
Mhh then it's definitely not a common issue as 1.963 has already been installed on thousands of systems and been tested for more than a week.
Maybe something with your configuration got corrupted :-/ 

You may try to update to v.1969 which I'll be uploading in a few minutes. Otherwise I'd try to reset the BTT preferences using this terminal command: "defaults delete com.hegenberg.BetterTouchTool". Or alternatively try to create a new preset in BTT and check if the problem persists.

**Comment by ryantrip** [comment]
I will update to 1.1969 when it becomes available and test it. If that doesn't work I'll work through your two other suggestions. I'll report back here with my findings. Thank you for your quick responses and suggestions!

**Comment by fifafu** [comment]
Just uploaded 1.969 :-)

**Comment by ryantrip** [comment]
Ah I believe I just find out what was causing the issue. I had a two finger force click action enabled, and that removed my system default two finger click. Without the two finger force click action, I can right click again.

**Comment by ryantrip** [comment]
Is this the standard behavior, it is there a way to implement a two finger force click action and still use the system default two finger click?

**Comment by fifafu** [comment]
Only if you also configure the two finger click in BTT. With 1.969 the option to not override the system response should now also work correctly.

**Comment by ryantrip** [comment]
With the settings seen below, I cannot right click. If I delete the two finger force touch action I can right click again. No two finger click has been configured in BTT. I've also verified that the default system response issue is resolved as well.

<img width="346" alt="screen shot 2016-12-13 at 11 38 26 pm" src="https://cloud.githubusercontent.com/assets/24561062/21173599/56cdc124-c18d-11e6-9e48-32e547f13b21.png">
<img width="334" alt="screen shot 2016-12-13 at 11 38 45 pm" src="https://cloud.githubusercontent.com/assets/24561062/21173600/56e79586-c18d-11e6-9985-0c6791597f19.png">

**Comment by fifafu** [comment]
Yes exactly, you can't use the system right-click while also using the BTT 2 finger force click (the reason is that BTT can not know what you are about to do, thus it needs to block the system two finger click. Only if the two finger click is also configured in BTT, BTT can handle it.

**Comment by ryantrip** [comment]
Ah got it. Thank you for the help! Maybe we could document the work around as well (manually adding a two finger right click in BTT) in case others run into this as well. I believe this ticket can be closed.
