### ISSUE TITLE
How add Screen Sharing to BTT?  Additional way to select app to add

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#1110]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
It's not clear to me how to add Screen Sharing to the list of apps in BTT in order to define gestures for it (I want to replace it's touch bar). In Sierra, it doesn't seem to be a findable app that I can include using the + button below the application list in BTT. 

It would help if BTT would have a secondary means of selecting an app - for example, being able to put BTT in a "find the app" mode where I just need to click on one of the app's open windows in order for BTT to determine what to add.

#### Device information:

Type of Mac: 2016 MBP 13"
macOS version: 10.12.5
BetterTouchTool version: 2.23

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This has been added in recent BTT versions.
