### ISSUE TITLE
[Bug] Whole Screen Capture adding "0_" to start of file name.

### ISSUE THREAD

**Issue by quintrino** [fifafu/BetterTouchTool#1112]
---

#### Description of bug/feature request/question:

Screenshot feature adds 0_ to the start of the file name. 

I'm attempting to create a keyboard shortcut to save a screenshot as _Screenshot_{datetime}_ but upon saving the configuation it adds 0_ to the start of the file name.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Screenshot _capture whole screen_ feature.
 I've tested it in both the gestures and keyboard.
The issue is not present if you use the capture interactive option for a partial screenshot.

#### Device information:

Type of Mac: Macbook Pro 2015
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screenshots of screenshot issue located here.
https://imgur.com/a/82V8N?

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

I think this should be fixed in the latest alpha (2.24)

Best,
Andreas

**Comment by quintrino** [comment]
Just downloaded 2.25, all working!
