### ISSUE TITLE
Compatibility with Vectorworks 2017

### ISSUE THREAD

**Issue by mprofitl** [fifafu/BetterTouchTool#1114]
#### Description of bug/feature request/question:
The architectural program Vectorworks experiences problems with its snapping paletts when using Better Snap Tool. On the right side of the screen, and only there, the most upper palette gets cut off. I checked with the producer of Vectorworks: Other people experience the same problem. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Not input device dependent

#### Device information:

Type of Mac: iMac (Retina 5K, 27-inch, Late 2015)
macOS version: Sierra 10.12.5 (16F73)
BetterTouchTool version: 1.7

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<img width="1559" alt="paletten" src="https://user-images.githubusercontent.com/6146601/27482343-62d8b37c-5821-11e7-80fb-b8eced08da6b.png">

**Comment by fifafu** [comment]
Unfortunately this is something that only vector works can fix. BTT/BST just tells the window to resize, how the resizing is done is entirely handled by the app :-(

I'll try to file a bug report with them.
