### ISSUE TITLE
OSX Functionality: Move Left / Right a Space does not work anymore

### ISSUE THREAD

**Issue by TomFreudenberg** [fifafu/BetterTouchTool#1115]
#### Description of bug/feature request/question:

Hi I am using your BTT for long time as PRO version and really happy. But since some weeks (not sure what update (BTT or OSX) has raised this issue.

I am using normally Scroll Left / Scroll Right from my Mouse to easy switch between Spaces like multi finger gesture on Trackpad.

But by know, I can't do that when configuring "OSX Functions -> Move Left / Right a space". Seems that the function does not work anymore. I have configured now the Keyboard shortcut, that works.

Maybe you may repair the OSX Functionality options.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse with wheel with left and right click (Scroll Left and Right)

#### Device information:

Type of Mac: MacBook Pro Mid 2013
macOS version: 10.11.6
BetterTouchTool version: 2.20 (641)

**Comment by fifafu** [comment]
Are you still experiencing this? The macOS features still seem to work fine here. Have you already tried to restart your system?

**Comment by TomFreudenberg** [comment]
Hi, currently I am not able to reboot but will try. I would say, yes I have rebooted several times and this still not working on my side. But I will check.
