### ISSUE TITLE
[Feature request] 2/5 screen resize and / or user-defined predefined actions.

### ISSUE THREAD

**Issue by Charitable-Gear** [fifafu/BetterTouchTool#1117]
#### Description of bug/feature request/question:

Option to resize windows to left, centre-left, centre-right, and right-hand 2/5 of screen. 

#### Device information:

Type of Mac: Mac Pro
macOS version: 10.12.5
BetterTouchTool version: 2.21

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Resizing to half a screen is a bit much on a large monitor (32"), but 1/3 doesn't seem quite large enough. 2/5 of the screen should be just about right. Alternately, allow custom pre-defined action creation so users can define their own resize regions.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

You can use the "custom snap areas" feature to create custom regions. (Click the BTT menubar icon, then choose the "snap areas" item amd create a new one)

There are some youtube videos that show how to do it.

Best 
Andreas
