### ISSUE TITLE
Emulate Pinching to zoom (trackpad) with normal mice

### ISSUE THREAD

**Issue by niccolospa** [fifafu/BetterTouchTool#1118]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I would like to ask if there's a way to add to normal mice a shortcut to emulate trackpad pinching to zoom

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Normal Mice

#### Device information:

Type of Mac: MacBook Pro Mid 2012
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.24

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is currently not possible because Apple doesn't expose the necessary APIs to us developers.
