### ISSUE TITLE
"Do NOT override the system's default toe finger haptic response" option does not use the default haptic response

### ISSUE THREAD

**Issue by ryantrip** [fifafu/BetterTouchTool#112]
I am using BTT on a 2016 13" MacBook Pro with the built in trackpad. I could not get the system default two finger right click to work, without using this option. When the option is enabled however, the response is a double response, not the system default. I've ticketed the two finger click issue here:

[https://github.com/fifafu/BetterTouchTool/issues/111](https://github.com/fifafu/BetterTouchTool/issues/111)

**Comment by fifafu** [comment]
Will be fixed with next alpha
