### ISSUE TITLE
Clipboard History Preferences "Keep x" Issue

### ISSUE THREAD

**Issue by HFTobeason** [fifafu/BetterTouchTool#1120]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

"Keep x" sliders show decimals (see screenshot)

#### Device information:

Type of Mac: MacBook Pro (15-inch, Late 2016)
macOS version: 10.12.6 Beta (16G18a)
BetterTouchTool version: 2.25

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1108" alt="screen shot 2017-06-26 at 11 23 16" src="https://user-images.githubusercontent.com/704778/27546996-766838ca-5a62-11e7-9797-29c0d3afa0de.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Fixed in v2.260
