### ISSUE TITLE
no multitouch capable trackpad found

### ISSUE THREAD

**Issue by Genjih** [fifafu/BetterTouchTool#1122]
#### Description of bug/feature request/question:
On my just received 2017 iMac running macOS 10.12.5 and using the new Magic Mouse 2 and Magic Trackpad 2;  running BetterTouchTool 2.25 - in the Trackpads tab, get 'no multitouch capable trackpad found!' at the bottom of the panel. On the Magic Mouse tab, get 'this is the magic mouse tab, but there is no magic mouse connected! (or there is a problem with the drivers)'

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse 2
Magic Trackpad 2

#### Device information:

Type of Mac: Retina 5K, 27-inch, 2017
macOS version: 10.12.5
BetterTouchTool version: 2.25 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I did restart of updating BTT. 
<img width="1021" alt="screen shot 2017-06-26 at 1 48 00 pm monday june 26 2017" src="https://user-images.githubusercontent.com/29713904/27555060-273ce480-5a76-11e7-9ae6-0315ca909de7.png">

**Comment by fifafu** [comment]
Have you also tried to restart your machine?
Maybe the drivers somehow got confused.

**Comment by Genjih** [comment]
Yes, by 'restart' I meant a complete reboot of the iMac.

**Comment by fifafu** [comment]
Unfortunately I really don't know what could be causing that, do your macOS gestures work correctly?

Best
Andreas

**Comment by Genjih** [comment]
Yes, trackpad and mouse gestures work correctly.  I should mention that at one point we installed the Logitech G9 mouse software, as we had one connected to the system. The G9 worked fine... but later I found that trackpad and mouse gestures did NOT work... We uninstalled the Logitech software (using their uninstall app) and gestures began working again. Is it possible that the Logitech app left some 'stuff' behind that is conflicting with BTT?

**Comment by Genjih** [comment]
UPDATE: I used mdfind from a terminal to find any reference to 'logitech' and deleted any found.
I then used an app called 'appcleaner' to remove BTT. Reboot.... then download BTT again.
BTT now recognized the magic trackpad 2 and magic mouse 2.

**Comment by zelig2** [comment]
I have the same problem as Genjih. I'm using a Logitech K750 keyboard that talks to a Logitech USB receiver but have uninstalled all the references to 'logitech' that I can find on my system using mdfind. I'm only able to run BTT v2.096 because the website won't let me download a newer version.

**Comment by habalda** [comment]
I have exactly the same problem as Genjih. Appeared after I didn't use the Magic Mouse for a few days (wasn't working). When I connected the new mouse, this happened (trackpad message as well). Didn't have anything new installed. What gives?
