### ISSUE TITLE
Accidentally deleted Finder

### ISSUE THREAD

**Issue by ChemBob** [fifafu/BetterTouchTool#1123]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I accidentally deleted the Finder from the left pane in BTT. I can't figure out how to add it back. Help please.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

New MB Pro with touchbar

#### Device information:

Type of Mac: Newest MBPro loaded
macOS version: newest
BetterTouchTool version: dl'd today to try out

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Finder is located in  /System/Library/CoreServices/Finder.app (go there by pressing cmd+shift+g while the file selection window is open)

**Comment by ChemBob** [comment]
Thank you so much!
