### ISSUE TITLE
Glitch with "Run AppleScript and Show Return Value" when used with modifier keys

### ISSUE THREAD

**Issue by ameg** [fifafu/BetterTouchTool#1125]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When an applescript widget is used in conjunction with at least one button which is dependent on a modifier key, the widget flashes / glitches whenever the modifier key is pressed.

Here is one way to reproduce this:
 - Under Global, create a "Run Applescript and Show Return Value" widget, returning two different possible values; assign colours and icons to an appropriate regex (not sure if that's necessary). Also create a normal TouchBar button.
 - Under an app (e.g. iTerm), create two normal TouchBar buttons, one with a modifier key and one without
 - When the app is in the foreground, tap the modifier key. The global widget will flash / glitch, but the normal buttons remain fixed/smooth

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 13" 2017
macOS version: 10.12.5
BetterTouchTool version: 2.21

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry for not replying earlier :-(

I think this has been fixed in recent versions.

In case it's not yet solved for you please comment again- I'm currently closing some older issues.
