### ISSUE TITLE
[FEATURE REQUEST] Option to re-execute Applescript widget after button press

### ISSUE THREAD

**Issue by ameg** [fifafu/BetterTouchTool#1126]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Feature request: after pressing a "Run Applescript and Show Return Value" widget, as a final step, the Applescript would execute again and the button would reflect the new state. 

Reason: this would support a common use case, where the button directly updates the thing that it is dependent upon.

In my use case, this is a simple toggle button: pressing it switches between two keyboard input source options, and the button reflects the currently select input source (colour / test) as a visual cue:

 - Normally the icon shows that the "ABC" keyboard is in use ("ABC", and one colour)
 - Press the button, and the input source is changed to Japanese
 - Some random time later, the icon shows the new keyboard source ("Japanese", and a different colour)

Currently, the only way to ensure this updates promptly is to set the execution time ("Execute this script every x seconds") very short, e.g. 0.2 seconds. However, it still isn't instant, and it causes a huge number of unnecessary script executions which is surely not a good thing.

Ideally, my script would execute infrequently (e.g. every 10 seconds, to eventually catch those cases where input source is changed using alternative means), but would immediately update on button press / toggle.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 13" 2017
macOS version: 10.12.5
BetterTouchTool version: 2.21

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I'm sorry for not replying earlier.

This is possible by assigning the predefined action "Run Apple Script (enter directly as text)" to a widget. (Or by assigning the Run Shell Script / Task action).
