### ISSUE TITLE
Windows Creeping Up

### ISSUE THREAD

**Issue by paulmoons** [fifafu/BetterTouchTool#1128]
#### Description of BUG:

I noticed this a few versions ago and I am not sure if it has always been there but windows creep when clicked. I hasten to add that this might not even be a specific BetterTouchTool issue but it does not occur when BetterTouch Tool is not running. Also this creeping occurs to snapped windows AND non snapped ones.

The problem, in short, is that every time I click on a window that is not already touching the menu bar it "creeps" up a pixel each time it is clicked - I initially thought this was occurring with snapped windows only but it seems to happen with all windows that are not full screen or touching the menu bar. Every time I refocus (click on) a window from another one (or from the desktop), they creep up (what I presume to be) a pixel. This upward creep continues until the window hits the menu bar and then the windows stays in place no matter how many times you refocus on it.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Tested with Trackpad.

#### Device information:

Type of Mac: TouchBook Pro Late 2016
macOS version: 10.12.5
BetterTouchTool version: v2.260 (and previous versions)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

N/A

---

Thanks. :)

**Comment by paulmoons** [comment]
Dupe of: https://github.com/fifafu/BetterTouchTool/issues/1038 ?

**Comment by fifafu** [comment]
yep let's continue in #1038
