### ISSUE TITLE
Right Click of Normal Mice sometimes cannot work

### ISSUE THREAD

**Issue by jiaoshou2009** [fifafu/BetterTouchTool#113]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
After waking up, sometimes right click of normal mice will not work, only if I click once on trackpad it will back to be functional. I can't 100% repeat it, and when I was reporting this, it worked fine. 

**What kind of Mac are you using?**
15inch MacBook Pro w/ TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Normal Mice

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 
But I also occurred in 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
I have an idea what could cause this. I'll try to add a fix with the next update. Please let me know if it keeps happening afterwards.

**Comment by jiaoshou2009** [comment]
Oh sorry, I am wrong. It's left click instead of right click

**Comment by jiaoshou2009** [comment]
And I switch to a new preset (a blank one). This problem seems solved.It may due to my previous preset.

**Comment by jiaoshou2009** [comment]
I think I found the bug. The "corner click top left" will cause this problem, if I have any trackpad gesture related to it.

**Comment by giisha** [comment]
I have similar issue, and all my gestures are only forceclick ones.

**Comment by dionisokan** [comment]
First of all, I would like to say "thank you" to @fifafu for developing such a nice and useful app.

Unfortunately, problem similar to comments above happens to me frequently. Once in a while my mouse stopped registering its left click when BTT is running; only after touching or clicking on my trackpad everything becomes normal again, just like the issue of @jiaoshou2009 . 

FYI I am running BTT on macOS Sierra *(10.12.2)* on my early 2015 13-inch MacBook Pro w/ Retina Display, but if I remember it correct, this issue can date back to when I was on Yosemite and El Capitan *(10.10 and 10.11)*. The mouse I am using is a Logitech M545, and it's working properly. Apart from Force Touch click at four corners of the trackpad, my gesture list contains only non-Force Touch swipe and tap gestures.

Gratitudes in advance for looking into this issue.

**Comment by jphalip** [comment]
I've just recently run into a similar issue. All my custom events involving the right-click suddenly stopped working. I've tried restarting BTT and even rebooting my Mac multiple times, to no avail.

Events with the left-click still work fine.

I'm on OSX 10.12.3.

**Comment by emanuelthedude** [comment]
I updated to version 2.071(608) and it seems to be fixed..

**Comment by jphalip** [comment]
I'm also using version 2.071(608) and the problem is still present for me. @fifafu, should this issue be kept open?

**Comment by fifafu** [comment]
@jphalip I think your issue is different. Maybe send me an export of your gestures to boastr.net@gmail.com then I'll check what could be wrong.

**Comment by jphalip** [comment]
@fifafu Thank you, I just emailed you the report.
