### ISSUE TITLE
Dropbox sync

### ISSUE THREAD

**Issue by falkorindalo** [fifafu/BetterTouchTool#1130]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After awaken the computer from sleep, I've noticed that my Chrome browser was opened with dozen of Dropbox page tabs opened, asking me to login in order to link BetterTouchTool with Dropbox; which I actually done before leaving yesterday.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
N/A

#### Device information:

Type of Mac: Mac Pro (2013)
macOS version: 10.12.5
BetterTouchTool version: 2.25 (648)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here's a screenshot:

![bug db_btt](https://user-images.githubusercontent.com/15719066/27589936-128a1fbc-5b1b-11e7-8ffb-232a14d89b4b.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I'll continue tracking this issue here: #1174
