### ISSUE TITLE
Add flag to disable clipboard manager

### ISSUE THREAD

**Issue by utilityboy** [fifafu/BetterTouchTool#1131]
#### Description of bug/feature request/question:
Old clipboard text is being pasted.  This may be related to using other clipboard managers (Jumpcut/Alfred), but regardless this should be something that is opted-in to.  As it stands right now, I'm unable to use BTT until this is an option.  If I exit BTT, this behaviour goes away.

#### Device information:

Type of Mac: Macbook Pro Retina
macOS version: 10.12.4
BetterTouchTool version: 2.260

**Comment by fifafu** [comment]
The BetterTouchTool clipboard manager is only activated if it is assigned to a trigger/gesture in BTT.

**Comment by utilityboy** [comment]
@fifafu ok.  I'll do a little more digging into this to see if I can narrow it down a bit.

**Comment by fifafu** [comment]
In general BTT doesn't modify the clipboard history without explicitly triggering it, in which scenario do you see old content pasted? Using normal cmd+v? Or using BTT actions?

**Comment by utilityboy** [comment]
CMD+V.  It's the most bizarre thing.

**Comment by fifafu** [comment]
Are you sure you haven't accidentally set a shortcut for cmd+c in BetterTouchTool that may block the copying?

**Comment by barisione** [comment]
> The BetterTouchTool clipboard manager is only activated if it is assigned to a trigger/gesture in BTT.

But it still seems to remember what you pasted when it was not associated to any trigger.

1. Make sure there's no trigger for the clipboard manager but BTT is running.
2. Copy and paste a few things.
3. Add a keyboard shortcut for the clipboard manager
4. Trigger the shortcut
5. Observe that the things copied at step 2 are in the manager.

My problem with that is that I don't want password/credit card infos to be saved anywhere.

**Comment by fifafu** [comment]
@barisione, if assigned once it will currently stay active until BTT is restarted (even if it had been deleted afterwards)

If you delete the assignment and then restart BTT it shouldn't capture anything.

**Comment by utilityboy** [comment]
@fifafu I'm sure this is the case...  I use Alfred's clipboard manager.

**Comment by fifafu** [comment]
In the latest alpha I’m making extra sure that the clipboard manager is completely inactive if it is not added to a trigger in BTT. Thus I’m closing here for now. In case you still experience issues with the latest alpha please let me know.
