### ISSUE TITLE
Application Support folder causes finder to crash

### ISSUE THREAD

**Issue by jshrek** [fifafu/BetterTouchTool#1132]
#### Description of bug/feature request/question:
In Finder when I go to /Users/MyName/Library/Application Support/ and then click on the BetterTouchTool folder, it causes Finder to crash.

#### Device information:

Type of Mac: MacBook Pro (13-inch, Late 2011)
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.05

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Tried to upgrade to newest version of BTT but only v2.05 will run. Newer versions say that file is damaged. Had to go back to v2.05

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That is a Finder bug then. I'll close here, but maybe report it to Apple ( upgrade to latest macOS first to verify it hasn't been fixed yet)
