### ISSUE TITLE
Attempted upgrade lost all custom gestures and keyboard shortcuts

### ISSUE THREAD

**Issue by jshrek** [fifafu/BetterTouchTool#1133]
#### Description of bug/feature request/question:
Tried to upgrade to newest version (2.26) and app says it is damaged. Tried 2.20 as well and get same error. Reinstall v2.05 which runs fine, however all my custom gestures and keyboard shortcuts are gone.

#### Device information:
Type of Mac: MacBook Pro (13-inch, Late 2011)
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.05

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Trying to go to the /Users/MyName/Library/Application Support/BetterTouchTool folder will cause Finder to crash.

**Comment by fifafu** [comment]
This ia definitely not normal. Have you already tried to restart your Mac?

Otherwise try to upgrade your macOS to the latest version, maybe that Finder crash has been fixed already.
