### ISSUE TITLE
BTT Remote does not find my mac

### ISSUE THREAD

**Issue by ric-cioffi** [fifafu/BetterTouchTool#1134]
Hi,
lately I have been having issues with connecting any of my iOS devices to my mac. I am almost sure the problem is with my mac because I am able to connect to the mac of one of my friends but not to mine.

I have always been able to connect in the past, and the firewall allows incoming connections for BTT.

I am not entirely sure but if I remember correctly I had troubles connecting on the network I currently am, last time I traveled I was able to connect, and now it does not work again. This would suggest a network issue but this my friend's mac is also on the same network and I have no problems connecting to his mac.

Type of Mac: MacBook Retina mid-2013
macOS version: 10.10.5
BetterTouchTool version: 2.11

Any thoughts of what might be the problem?

Thanks, Riccardo

**Comment by fifafu** [comment]
Most likely it's a firewall issue. Have you already tried to completely disable the fw and see if it can connect afterwards? BTT Remote needs tcp and udp.

**Comment by ric-cioffi** [comment]
I don't know what tcp and ucp are but yes, I have tried to completely disable the fw and tried to connect but it doesn't work.
I should probably also mention that the ios app does not see my Mac at all, I have to try and connect through IP and port (but it doesn't work of course)

**Comment by fifafu** [comment]
What kind of wifi router are you?

**Comment by ric-cioffi** [comment]
I'm really not sure, I leave in student housing and wifi is provided by the building. As I said, however, I don't think it is a network problem because I can connect to my friend's mac on the same network :/

**Comment by fifafu** [comment]
Weird usually these are the only two things that can be problematic (wifi and firewall). Are you sure BTT Remote is enabled? (In the BTT Remote tab)

Which Firewall are you using?

**Comment by ric-cioffi** [comment]
Yes, BTT Remote is enabled. The firewall is the built-in apple firewall

**Comment by ric-cioffi** [comment]
Is there a way to backup all the settings? I was thinking of trying to uninstall and reinstall BTT. I remember it gave me a weird error a couple times but was then kept working properly.

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
