### ISSUE TITLE
Clipboard Manager Freezing Immediately

### ISSUE THREAD

**Issue by gregalanraslan** [fifafu/BetterTouchTool#1135]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Bug: Clipboard manager freezes the second I open it. Restarting it does not fix the issue at all.

Request: More lightweight clipboard manager ala CopyClip. The ability to see a list view and quickly copy an item using Command+[numberkey] would be very very helpful.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro -- Trigger is 3-finger force click

#### Device information:

Type of Mac: 2016 Pro
macOS version: 10.12.5
BetterTouchTool version: 2.260 (650)
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, could you check whether it works when using a keyboard shortcut?

There won't be a more lightweight clipboard manager in BTT (I already consider the current one quite lightweight ;-))

**Comment by gregalanraslan** [comment]
Did a key bind for command-option-alt-shift+right-arrow. Immediately crashed the entire application.

**Comment by fifafu** [comment]
Ah that's good (better than a freeze) :-) 
Could you attach the crashlog from the macOS console.app (under "User Reports")

**Comment by gregalanraslan** [comment]
Appreciate the guidance for finding the log. It’s attached.

**Comment by fifafu** [comment]
Ah damn, I think logs are not attached when replying via e-mail. Could you forward it to boastr.net@gmail.com? (or alternatively upload on the github website).

Thanks a lot!

**Comment by gregalanraslan** [comment]
Forwarded to the gmail address.

**Comment by fifafu** [comment]
The crash should be fixed in v2.261 (get via "check for alpha version updates"), let's see if this also fixes the freeze!

**Comment by gregalanraslan** [comment]
It works for both keyboard and touchpad. Though closing it causes a bit of a fly-out animation from the window (not sure if this is intentional or not, so thought I’d share).

**Comment by fifafu** [comment]
Perfect! The animations will be improved soon.
