### ISSUE TITLE
High Sierra compatability?

### ISSUE THREAD

**Issue by terronymous-boosh** [fifafu/BetterTouchTool#1137]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Clean install of High Sierra beta 2, restored applications from TM backup and BTT gives ?Cocoa warnings, and doesn't appear to run.

Removed and reinstalled, got a warning about BTT not being compatible with the version of "your data file! Please update to newer version of BTT......."

How do I find and delete this old data file?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

macbook pro track pad

#### Device information:

Type of Mac: mid-2014 macbook pro
macOS version: high sierra beta 2
BetterTouchTool version: latest (sorry I can't tell)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I haven't had any issues with the latest BTT and High Sierra (running it since the first beta).
Maybe try to download a fresh copy from https://boastr.net/downloads

Maybe you restored some very old version?

Maybe also try deleting the ~/Library/Application Support/BetterTouchTool folder.

**Comment by terronymous-boosh** [comment]
Your suggestion worked. I deleted the folder you suggested. Thank you!

**Comment by mozeryansky** [comment]
This also worked for me. Note that the license is also in that folder, so I moved it out before deleting the entire folder.

**Comment by njudd** [comment]
This also worked for me, moving the license is a great tip.
