### ISSUE TITLE
Cursor changes from pointer to cross

### ISSUE THREAD

**Issue by JanJentsch** [fifafu/BetterTouchTool#1138]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Having installed the latest version on 26th of June 2017. the cursor changes from the pointer-version to a cross everytime I hover across a safari or mail window

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

I am using MagicMouse and ext. USB keyboard

#### Device information:

Type of Mac: MacBook Pro (Mid 2012)
macOS version: 10.11.6
BetterTouchTool version: 2.260 (650)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I don't think BTT can influence your mouse cursor.
Have you already tried to restart your Mac?

**Comment by JanJentsch** [comment]
Hallo Andreas, 

ja, ich habe schon einen Neustart gemacht. Es trat definitiv nach dem gestrigen Update von BTT auf. Ich habe sonst nichts an meinem System geändert.

Viele Grüße,

Jan 









BRANDSHAPE Jan O. Jentsch
Krähenweg 9
D-22459 Hamburg

Tel 040 - 432 77 8 11
Fax 040 - 432 77 8 13
Mobil 0176 - 1040 1042
Mail jan.jentsch@brandshape.de
Web www.brandshape.de

St-Nr 45/107/02501
Inhaber Jan O. Jentsch

**Comment by fifafu** [comment]
Verschwindet das Problem wenn du BTT beendest?

**Comment by JanJentsch** [comment]
nein, leider nicht. habe ich auch schon ausprobiert. Muss gleich aber noch einmal beenden aus den Startobjekten rausnehmen und dann noch einmal neu starten - muss allerdings noch schnell einen Job fertig machen. Halte dich auf dem Laufenden. ;-)

Viele Grüße,

Jan O. Jentsch









BRANDSHAPE Jan O. Jentsch
Krähenweg 9
D-22459 Hamburg

Tel 040 - 432 77 8 11
Fax 040 - 432 77 8 13
Mobil 0176 - 1040 1042
Mail jan.jentsch@brandshape.de
Web www.brandshape.de

St-Nr 45/107/02501
Inhaber Jan O. Jentsch

**Comment by fifafu** [comment]
Ok, das klingt aber erstmal so, als ob das Problem unabhängig von BTT ist (BTT hat keinerlei Einfluss auf das System wenn es nicht läuft).

**Comment by JanJentsch** [comment]
so, habe jetzt BTT beendet und aus den Anmeldeobjekten entfernt und MacBook Pro im Save-Mode neugestartet (Neustart + gedr. Shift-Taste) Problem nicht mehr da!
Jetzt werde ich BTT wieder starten und noch einen Neustart machen. Berichte weiter ...

Viele Grüße,

Jan









BRANDSHAPE Jan O. Jentsch
Krähenweg 9
D-22459 Hamburg

Tel 040 - 432 77 8 11
Fax 040 - 432 77 8 13
Mobil 0176 - 1040 1042
Mail jan.jentsch@brandshape.de
Web www.brandshape.de

St-Nr 45/107/02501
Inhaber Jan O. Jentsch

**Comment by JanJentsch** [comment]
jetzt scheint wieder alles beim alten ... sorry, für den kurzen Aufreger! ;-)

Viele Grüße,

Jan









BRANDSHAPE Jan O. Jentsch
Krähenweg 9
D-22459 Hamburg

Tel 040 - 432 77 8 11
Fax 040 - 432 77 8 13
Mobil 0176 - 1040 1042
Mail jan.jentsch@brandshape.de
Web www.brandshape.de

St-Nr 45/107/02501
Inhaber Jan O. Jentsch

**Comment by fifafu** [comment]
Ah, wunderbar!
