### ISSUE TITLE
Cannot upgrade from v2.20 to v2.61

### ISSUE THREAD

**Issue by mojoTX** [fifafu/BetterTouchTool#1139]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm trying to upgrade from v2.2.0 to v2.61 on my MacBook Pro and I'm getting the message, "An error occurred while extracting the archive. Please try again later."

Will trying again later really resolve the issue? 🙂 

<img width="512" alt="screen shot 2017-06-27 at 14 14 16" src="https://user-images.githubusercontent.com/5694899/27605786-548e6544-5b43-11e7-933c-9f0b3dbea2ae.png">
<img width="532" alt="screen shot 2017-06-27 at 14 14 24" src="https://user-images.githubusercontent.com/5694899/27605785-548ba642-5b43-11e7-89c4-f9f21c9f561c.png">

#### Device information:

Type of Mac: MacBook Pro (15-inch, Late 2016)
macOS version: macOS 10.12.5
BetterTouchTool version: v2.20 -> v2.61

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you already tried again? I think there was a small typo about an hour ago that should be fixed already.

**Comment by mojoTX** [comment]
Yes, that fixed it, thank you!
