### ISSUE TITLE
Feature request: Multi-drag accelerates pointer motion

### ISSUE THREAD

**Issue by seweil** [fifafu/BetterTouchTool#114]
Scenario: Magic Trackpad II and multiple monitors

It's always a challenge to find a pointer speed that allows moving long distances (between monitors) and also fine selections within a window.

I'd like something like: 3 finger drag moves the pointer at 3x the normal rate.

**Comment by fifafu** [comment]
Good idea, but unfortunately I won't be able to do this with BTT as it would require deeper system integration...

Sorry!
