### ISSUE TITLE
Preferences hangs BTT

### ISSUE THREAD

**Issue by abinpuravath** [fifafu/BetterTouchTool#1145]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi after some update maybe 1-2 months ago, I keep getting a notification when BTT loads thats titled BTT Permissions and says that BTT is now ready to use in green. When I click the button "Start using BTT and open preferences" the program hangs and I have to restart it. If I just close the notification then BTT will work but I cannot add any new gesture because if I click the title bar icon and try to open preferences it hangs again. I haven't installed any new software on the comp before this began and I'm not sure how to fix this. Restarted the computer and macOS is latest version. When I tried installing previous versions of BTT it continued to not work I think till 2.07 when it said gesture file was not compatible. I love this software and earnestly seeking a fix. Thank you!!

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015), 2.7 GHz Intel Core i5, 16 GB 1867 MHz DDR3, Macintosh HD, Intel Iris Graphics 6100 1536 MB
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.261 (651)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is a file permission error. If possible try to repair permissions using Apple's Disk Utility. If this doesn't work, maybe delete the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist file (it will be regenerated with the correct permissions afterwards)

**Comment by abinpuravath** [comment]
This worked!! Thank you so much!!!
