### ISSUE TITLE
[FEATURE REQUEST] Keyboard shortcut should recognize EJECT key

### ISSUE THREAD

**Issue by jshrek** [fifafu/BetterTouchTool#1146]
#### Description of bug/feature request/question:
I have a 2011 MacBook Pro and when trying to create a keyboard shortcut, both Shortcut and Key Sequence will not recognize keypress of Eject button.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro keyboard

#### Device information:
Type of Mac: MacBook Pro 13-inch late 2011
macOS version: 10.12.4
BetterTouchTool version: 2.05

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
It is possible to add shortcut key for Eject as this does it:
https://github.com/pkamb/PowerKey
But would be nice is it was part of BTT!

**Comment by rodalpho** [comment]
Yep neither karabiner nor BTT works with the eject key due to some sort of bug introduced in Sierra. As you noted Powerkey does work to remap it, and that's what I use myself.

**Comment by jshrek** [comment]
I guess this could be marked as a FEATURE REQUEST then to somehow incorporate the PowerKey code into BTT. Thanks

**Comment by fifafu** [comment]
Sorry unfortunately I can’t add this to BTT as the method used in PowerKey would conflict with various other parts of BTT :-(
