### ISSUE TITLE
Right clicking in PhpStorm

### ISSUE THREAD

**Issue by josephnle** [fifafu/BetterTouchTool#1147]
#### Description of bug/feature request/question:
PhpStorm doesn't detect any right-click interactions when I use my built-in trackpad. Upon quitting BetterTouchTool or disabling BetterTouchTool for PhpStorm, the right-click works again. I've tried resetting both BetterTouchTool and PhpStorm to the default configuration. I have no custom gestures configured for any devices.

I tried manually configuring control + tap gestures in the Trackpad device to map to right click, but this strangely seems to allow only the physical ctrl-click to work, not ctrl-tap.

NOTE: When I connect a physical mouse, right click works as expected.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.12.5
BetterTouchTool version: 2.261 (651)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mh this seems to work fine here. Which version of PHPStorm are you using?

**Comment by josephnle** [comment]
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

**Comment by fifafu** [comment]
Unfortunately I can't seem to be able to reproduce this. Is this still happening on your machine?

Do you have any other mouse or keyboard related tools installed that could interfere with BTT?

Best 
Andreas
