### ISSUE TITLE
[Feature Request] Volume control HUD in Widget

### ISSUE THREAD

**Issue by junzologies** [fifafu/BetterTouchTool#1148]
**Description of feature request:**
Trigger the Volume control HUD when pressing the icons in the Volume Slider Widget, just like the Brightness Slider. If possible, make it such that Option+Shift will increase the volume in smaller increments as well. Thanks :)

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Touch Bar

**Comment by fifafu** [comment]
Sorry, unfortunately I don't think there is an API for this and I probably won't try to mimic the Apple hud.

If I ever find a way to show it I'll definitely add this.
