### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by tmdarlan** [fifafu/BetterTouchTool#1149]
#### Description of bug/feature request/question:
Is it possible to make a shortcut to flip the side that my external monitor is on. say when my computer is on my desk my external monitor is physically on the right of my laptop. but sometimes I swing 90deg
and place my laptop on my lap. then the eternal monitor is on the left. id like a shortcut to basically go into display arrangements and move the monitor to the other side.
---

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro General

#### Device information:

Type of Mac: MacBook Pro
macOS version: Sierra
BetterTouchTool version: 2.261

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by rodalpho** [comment]
I would use an Applescript to do this as described here, then trigger it with a BTT hotkey.

https://apple.stackexchange.com/questions/249447/change-display-arrangement-in-os-x-programmatically
