### ISSUE TITLE
New UI BTT (Mac) & BTT Remote (iOS)

### ISSUE THREAD

**Issue by fabi94music** [fifafu/BetterTouchTool#1150]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

would be great if the UI would look more "iOS" or "macOS" like.
I think especially the iOS app could look a little more polished. 
Maybe you consider this in future updates :) 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
There will be a new version of BTT Remote later this summer with an improved UI!

In general the changes to BTT's UI will always be incremental, a completely new ui is just not feasible.

I'm closing this issue but will definitely continue to improve both apps.
