### ISSUE TITLE
Touch bar apple scripts running every x seconds

### ISSUE THREAD

**Issue by klaasman** [fifafu/BetterTouchTool#1151]
#### Description of question:
Hi, I'm showing several touchbar-buttons when pressing a modifier key, one of those buttons shows the current track playing in spotify, another one  is a toggle for play/pause (with toggling UI state).

Those buttons are receiving their input from an apple script which have to run every X seconds, however, these scripts also run when the buttons aren't visible in the touchbar.

**Request**
It would be a great improvement to only run those scripts when the buttons are visible, or to determine somehow on what occasions a script may run.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.262

**Comment by fifafu** [comment]
This should be fixed in recent versions!

**Comment by klaasman** [comment]
Fantastic, thanks!
