### ISSUE TITLE
Feature request: text expansion

### ISSUE THREAD

**Issue by dzeruel** [fifafu/BetterTouchTool#1152]
# Feature request:
Hello!

The latest clipboard manager addition is really cool. I was thinking about buying Keyboard Maestro but this latest addition makes me think twice.
I would like to use BTT as some kind of a text expander as well. For example when I write "ty" it would automatically expands to "Thank you!", or pops up a menu with possible expansions. It is possible now with keystrokes but I could be refined a little bit. 

1. For example would it be possible to get rid of the text "Paste text" and indicate it somehow differently that it is a text insertion snippet.
![image](https://user-images.githubusercontent.com/3647875/27739225-2db59d58-5dae-11e7-80dd-c246aafc6c48.png)

2. It would be cool to have submenus in these floating menus to categorize snippets.

3. And last but not least it would be really nice to be able to save snippets from the new clipboard manager tool. Assign keyboard shortcuts or text strings to snippets.

4. I've just realised that when I change the text insertion into typing the content of the "text snippet" disappears.

![image](https://user-images.githubusercontent.com/3647875/27744220-f64b4cd0-5dbe-11e7-8bb9-9dfdef76d713.png)

**Comment by fifafu** [comment]
Hi,

BTT already can do text expansion using the Key Sequences feature and the "Paste Custom Text" action:

![image](https://user-images.githubusercontent.com/8820811/27843227-bb86e068-6111-11e7-9cd2-d7a8afab9a3b.png)
