### ISSUE TITLE
MacOS error: -67052

### ISSUE THREAD

**Issue by cukal** [fifafu/BetterTouchTool#1154]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BTT starts but icons disappear when going to another application or when BTT looses focus. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.12.5 OSX Sierra
BetterTouchTool version: 2.261

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

When starting BTT icons appear in the touch bar but when BTT configuration screen looses focus the icon disappear. When opening Advanced Configuration for a touch bar button and saving it the icons appear again. When clicking on the icons in touch bar it seems to crashes, same when BTT configuration screen looses focus, the icons disappear and never return until doing an Advanced Configuration save action or restart. 

Some errors from console:
```
default	02:50:07.904186 +0200	BetterTouchTool	MacOS error: -67052
*** Assertion failure in -[NSRemoteView informAuxServiceOfSelf], /Library/Caches/com.apple.xbs/Sources/ViewBridge/ViewBridge-283/NSRemoteView.m:3207
IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x0 *NO* NSRemoteViewController to client, NSError=Error Domain=com.apple.ViewBridge Code=8 "(null)" UserInfo={com.apple.ViewBridge.error.hint=__38-[NSRemoteView _advanceToConfigPhase:]_block_invoke.2466 caught NSInternalInconsistencyException '<NSRemoteView: 0x600000133e20> failed to rendezvous via aux service' with backtrace (
	0   CoreFoundation                      0x00007fff8f7a32cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffa45ae48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8f7a8042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff911f0c80 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   ViewBridge                          0x00007fffa3004b34 -[NSRemoteView informAuxServiceOfSelf] + 345
	5   ViewBridge                          0x00007fffa300547e -[NSRemoteView _finishAdvanceToConfigPhaseWithContextID:andServ, <decode: missing data>
```
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you already tried to restart your Mac? This sounds like a macOS issue.

**Comment by cukal** [comment]
Seems indeed to be a macOS issue, after a reboot I can't reproduce it anymore. BTT is working. 
Yay!
