### ISSUE TITLE
Reverts back to system touchbar. 

### ISSUE THREAD

**Issue by fgersch** [fifafu/BetterTouchTool#1157]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I've set global settings to use BTT. All looks good whilst in BTT but once loses focus system touchbar activates again BTT icon not visible either. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

touchbar

#### Device information:

Type of Mac:
macOS version: 10.12.5 
BetterTouchTool version: 2.261

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://user-images.githubusercontent.com/5508466/27762656-5c5e4c54-5e44-11e7-8a78-13171873a5af.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by jjstevenson** [comment]
I have the same problem....I can create a custom bar in Global, but the second I leave BTT it reverts back to the system touchbar.

**Comment by patrickst1** [comment]
I'm also seeing this. It started working again after backing up and trashing the preference file in `~/Library/Preferences` and the BetterTouchTool folder in `~/Library/Application Support` and rebuilding the actions. However after going back into BBT to add a few more actions the issue reoccurred.

**Comment by fifafu** [comment]
Unfortunately I can not reproduce this. Can you please check your settings in System Preferences => Keyboard? "Touch Bar shows" has to be set to "App Controls with Control Strip" for BetterTouchTool to work correctly.

![image](https://user-images.githubusercontent.com/8820811/28285426-ecb34690-6b34-11e7-8768-f67ea2023995.png)

**Comment by patrickst1** [comment]
I just double checked and mine is set up as pictured above, `Touch Bar shows` was/is set to `App Controls with Control Strip`. I have reset and reconfigured (although my config includes the `Show ESC` and `If Control Strip is hidden` options), so it's not doing it now. I'll keep watching it though. Please let me know if you need anything else.

**Comment by patrickst1** [comment]
Haven't had a problem in a week so I think that I'm chalking mine up to not have a full understanding of how it all worked together. My apologizes for posting a non-issue.

**Comment by callodacity** [comment]
@fifafu @patrickst1 glad your issue was resolved! If there's nothing else, this issue can probably be closed.
