### ISSUE TITLE
Context menu on touchbar

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#116]
#### Description of your bug/question/feature request...:
Such as when we need to correct the spelling, we won't have to right click etc.

**Comment by fifafu** [comment]
Yes, I have also thought about that! (It's not super easy, but for standard applications it should be doable :-))

**Comment by fifafu** [comment]
Sorry, unfortunately I think this can't be done. There is no API to retrieve the Context Menu items.
