### ISSUE TITLE
REQUEST: dock windows to the edge of your screen and automatically show when your cursor hits the screen edge.

### ISSUE THREAD

**Issue by fabi94music** [fifafu/BetterTouchTool#1162]
#### Description of feature request:
Dock windows to the edge of your screen and automatically show when your cursor hits the screen edge. (see http://www.irradiatedsoftware.com/tuck/) 
I find this feature very handy and at the moment I am using both apps. I would like to ditch Magnet and Tuck and only go with BTT. Can you add this feature? 

#### Device information:

Type of Mac: MacBook Pro 15inch
macOS version: 10.12.5
BetterTouchTool version: 2.261

**Comment by fifafu** [comment]
Ah sorry, this feature is not easy to implement and it's unlikely that I'll be able to add such a thing anytime soon. I'd stick with the tuck app as it looks very well done given the API limitations.
