### ISSUE TITLE
Feature Request: Apple Watch!

### ISSUE THREAD

**Issue by adamnjenk** [fifafu/BetterTouchTool#1163]
#### Description of bug/feature request/question:
I love what you've done with the touch bar, it's made my work (programmer) life so much more awesome.

It would be ridiculously awesome if I could do the same thing with my Apple Watch - configure custom buttons on it to do stuff on my Mac like kick off a build, or switch apps.

Yes, I realise that the distance between my watch and my touchbar while I'm programming is probably less than 10cm - but how cool would it be to kick off a maven build with your watch !

Thanks for a great tool - it's made my new MBP so much more functional than it otherwise would be

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple Watch!

**Comment by fifafu** [comment]
Continue to track this here: #170
