### ISSUE TITLE
Touch Bar issue 

### ISSUE THREAD

**Issue by mojiangjia** [fifafu/BetterTouchTool#1164]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When you tap the cross button on the left corner to quit BTT, you will have to tap BTT icon twice to make it work on touch bar again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.5
BetterTouchTool version: 10.12.5

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a limitation given by the API used. I’m closing here as this has already been discussed here a few times.
