### ISSUE TITLE
[FEATURE REQUEST] Smooth scrolling and an option to disable cursor acceleration for normal mouse.

### ISSUE THREAD

**Issue by acls86** [fifafu/BetterTouchTool#1166]
#### Description of feature request:

Would be great if BTT would have options for smooth scrolling (like apple trackpad) with a normal mouse wheel and the possibility to disable cursor acceleration in macOS.

At the moment to get the gestures and shortcuts I need I have to use BTT, for a good normal mouse wheel experience "SmoothScroll" and to disable acceleration "Steermouse".

Ridiculous to use so many different tools just to get there.

**Comment by fifafu** [comment]
Unfortunately these are all very complicated and work on different levels of the system. 
I won't be able to integrate them into BetterTouchTool. Sorry!
