### ISSUE TITLE
Assigned gesture buttons stopped working with new update - Logitech MX Revolution

### ISSUE THREAD

**Issue by missmercy01** [fifafu/BetterTouchTool#1167]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have been using BTT for ages and my assigned global gestures (page back and page forward) have suddenly stopped working since I installed the update today.  I've tried deleting and re-assigning the gestures to the buttons (3 & 4) and have done several re-boots to no avail.  I also assigned the gestures to the program I use them for most - Firefox (54.0.1), but still can't get the back and forward page gestures to work.  I use this feature a lot so really want it back, please help.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Logitech MX Revolution mouse - NO Logitech Control Centre software installed.

#### Device information:

Type of Mac: MacPro Mid 2010
macOS version: Yosemite 10.10.5
BetterTouchTool version: 2.265 (655)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting!
This should be fixed in v2.266 now.

**Comment by missmercy01** [comment]
Yes, thankyou, all fixed with new update.
