### ISSUE TITLE
Execute terminal command not working

### ISSUE THREAD

**Issue by GhostInTheMachines** [fifafu/BetterTouchTool#1169]
#### Description of bug/feature request/question:
Attached "Execute terminal command" to Touch Bar button on a Macbook Pro 15 but nothing happens on keypress

**Steps I have taken to add a workaround or debug issue more:**
Added advanced command to show a message on the hud to validate keypress (keypress message is displayed but still no action)
Attached an additional command to open the terminal application prior to executing the command

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Touch Bar

#### Device information:

Type of Mac: Macbook Pro 2016 with touchbar
macOS version: Siera (10.12.5)
BetterTouchTool version: 2.265(655)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by kkirigaya** [comment]
Does it work for any command? What's the exact command you're trying to use?

I'm running on the 10.12.6 beta and launching apps with `open -n /path/to/app/` works perfectly.

**Comment by fifafu** [comment]
One thing to note: BTT doens't source the $PATH currently, thus you'll need to address third party terminal tools by their full path

**Comment by GhostInTheMachines** [comment]
@kkirigaya No, I replaced my command with a simple ls command to get a directory tree and still no command appears when the terminal app opens.

**Comment by GhostInTheMachines** [comment]
@fifafu ls shouldn't require a path, it should just work in the directory that btt makes the command call.

**Comment by fifafu** [comment]
Ah you misunderstood the action. It just executes the command but this has notbing to do with Apples terminal app.

E.g. try "open ~/Downloads"

**Comment by GhostInTheMachines** [comment]
@fifafu Sorry, I should have specified that I first create a Touch Bar event that opens the apple terminal and then I "attach and additional action" which is set to "Execute terminal command"  which I have tried just to enter the simple command "ls" so that I can test that it works.
Unfortunately, it opens the terminal but then no command is executed in window.

Are you saying that I need to do something special to get the command to work with the Apple terminal application?

Ultimately I want to run a command that I have to run all the time to open an admin panel in a browser so it really doesn't matter if I see this happen in a terminal window.  Unfortunately, it does not seem to run at all which is why I started opening the Apple terminal app and attempting simple commands.

**Comment by fifafu** [comment]
Please post the command or a simplified version of it here, then I can tell you what's going wrong.

Opening the Terminal app is not necessary.

**Comment by GhostInTheMachines** [comment]
I am trying to run the command "cd ~/Sites/devdesktop/tsbvi-dev/docroot && drush uli -l tsbvi.dev.dd:8083" which is what I run from the terminal to open up a browser window that logs me in as an admin on a local development site that I am working on.
This command needs to be run from the root of the project which is why I first run the change directory command and then use the double ampersands to wait until the fist command has successfully run before executing the first command.

**Comment by fifafu** [comment]
You need to address drush with its full path, to find that path type "which drush" into the macOS terminal app.

**Comment by GhostInTheMachines** [comment]
Awesome!  that worked with the local site.
Now the other Touch bar button that I run allows me to open up a remote site in the cloud.
To get this to happen I need to run drush with an alias and it will spit out a custom one time only url such as: http://tsbviudqpcw9q5s.devcloud.acquia-sites.com/user/reset/hashToMyOneTimeLogin

So the question is... how can I get btt to open a terminal with this output?

This could be done automatically but occasionally I am asked for my rsa password so I really just need the output from the command sent to a terminal window which will allow me to handle either situation.

**Comment by GhostInTheMachines** [comment]
Or....I could setup a prompt that asks me for my password

**Comment by GhostInTheMachines** [comment]
right now when I use the command "/Applications/DevDesktop/tools/drush @tsbvi.dev uli -l" it just hangs on the password request

**Comment by GhostInTheMachines** [comment]
Should I post this on a new ticket?

**Comment by fifafu** [comment]
Sorry unfortunately BTT can’t work with terminal commands that require interaction. That’s a limitation I probably won’t be able to solve.
Maybe the tool allows you so somehow run in a non-interactive mode?

**Comment by BigSauce** [comment]
I'm unable to do a simple "Execute Terminal Command" such as `cd /`.

![image](https://user-images.githubusercontent.com/1718470/30932684-46f941d8-a396-11e7-9cab-18f5e64857c8.png)
![image](https://user-images.githubusercontent.com/1718470/30932721-57628610-a396-11e7-9a7b-5f38e46f896f.png)


Terminal doesn't open.  Nothing seems to happen.

If I do the following, then Terminal opens, but the `cd /` doesn't execute.

![image](https://user-images.githubusercontent.com/1718470/30932790-8bc2e0ee-a396-11e7-9f7f-c14024faf62e.png)

  Any ideas what I'm doing incorrectly?  Or is this a bug?

**Comment by BigSauce** [comment]
Got it.  So how might I execute a command such as `cd /` in the Terminal using BetterTouchTool?

**Comment by BigSauce** [comment]
Found out the answer on my own :)

Use an *Insert / Type / Paste Custom Text* Predefined Action.

Thanks @fifafu.  Love this tool, btw!  Thanks for making it!

**Comment by fifafu** [comment]
I think a more reliable solution would be to use the "Run Apple Script" action with a script like this:

```
tell application "Terminal"
	do script "echo hello"
end tell
```
![image](https://user-images.githubusercontent.com/8820811/30933784-d59eb03c-a3cb-11e7-9ede-d2b74c3040df.png)

**Comment by BigSauce** [comment]
Agreed.  Making the change now.

Great recommendation, and thank you!

**Comment by htkoca** [comment]
Is there any reason BTT can't reference the $PATH?

**Comment by griffincox** [comment]
In BTT using the Run Apple Script Action with:
```
activate application "iTerm"
tell application "iTerm"
	tell current session of current window
		set cmd to "serve_front_all"
		write text cmd
	end tell
end tell
```
Worked for me

serve_front_all is an alias for ~/custom_bash_scripts/serve_front_all.sh, which is in my $PATH
