### ISSUE TITLE
Closing tab on safari activates BTT touchbar

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#117]
#### Description of your bug/question/feature request...:
I have set safari to "show default touchbar"
But almost every time I close a tab, it goes to the BTT touchbar. 

**Which versions of macOS and BetterTouchTool are you running?**
BTT 1.97
MacOS 10.12.1

**Comment by fifafu** [comment]
Weird, seems to work fine on my Safari.

BetterTouchTool must for some reason think you are switching applications, do you have any special Safari Plugins installed?

**Comment by martin072** [comment]
No Problem here to. BTT 1.963
