### ISSUE TITLE
[Feature Request] After open a folder, please put the focus on it so I can continue working 

### ISSUE THREAD

**Issue by anprieto** [fifafu/BetterTouchTool#1170]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have configured BTT to open a combination of keys to open up a folder in "Pathfinder" (the app I use as an alternative to finder).  That works perfectly, but after opening it, the focus is not on that folder, so I cannot continue working with my hands, I need to use the trackpad to click on anything on the folder to set the focus there, and then I can use again the keyboard.

Is this something that can be addressed?

Thanks in advance.

#### Device information:

Type of Mac:  macbook pro touchbar
macOS version:  Sierra
BetterTouchTool version: 2.261

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by chessisamazing27** [comment]
I think it is possible to assign multiple actions to a single function and hence at the end of your combination, select add addition action and then choose left click. This will automatically select the Path Finder Window for you.

**Comment by anprieto** [comment]
That's a good suggestion, but only works if i'm already in the path finder app, and i have the mouse pointing in the files window.  If I'm in let's say the web browser, it opens the folder, but it remains in the webbrowser as it points the click to the browser.
Any other suggestion?

**Comment by anprieto** [comment]
Got it!  I added a delay, maximize the window, moved the mouse to the right position and left click.
I wasn't aware that BTT was THAT powerful. Incredible my friend.
Thanks a lot.

**Comment by callodacity** [comment]
@fifafu @anprieto since this issue has been resolved, it should be good to close 👍
