### ISSUE TITLE
(Improvement wish): Option to configure the dialog box when multiple actions are assigned under the same trigger

### ISSUE THREAD

**Issue by fabi94music** [fifafu/BetterTouchTool#1172]
#### Description of bug/feature request/question:
Would be great to change the appearance of the little box where one can choose between actions (see screenshot below => actually made with BTT :P) 
Would be great to set color/transparency and shape. 
![bildschirmfoto 2017-07-05 02 27 34_roprma](https://user-images.githubusercontent.com/29753374/27844987-bf2079e2-6129-11e7-8f98-547926fa3099.jpg)

#### Device information:

Type of Mac:
macOS version: 10.12.5
BetterTouchTool version: 2.266

**Comment by fabi94music** [comment]
Will you consider to add such a option?

**Comment by fifafu** [comment]
This menu will be completely reimplemented soon an will gain some nice features. I’m closing here as this has already been requested in other issues.

Thanks for the request!

**Comment by fabi94music** [comment]
Any release plans for that issue?

**Comment by fabi94music** [comment]
Any release plans for that update? :)
