### ISSUE TITLE
Version incompatible

### ISSUE THREAD

**Issue by erikbengtsson** [fifafu/BetterTouchTool#1175]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After updating to the latest version the automatic updating of my data files doesn't seem to be working and I get an error that my version i incompatible with my data file. Can't start the app at all.

#### Device information:

Type of Mac: MacBook Pro Retina Mid 2014
macOS version: 10.10.5
BetterTouchTool version: latest

**Comment by fifafu** [comment]
Hey,

could you check whether running this terminal command fixes the issue for you?

mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm.bac && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2.bac && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal.bac && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal.oldVersionBackup2.266 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal &&
mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm.oldVersionBackup2.266 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2.oldVersionBackup2.266 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2

**Comment by erikbengtsson** [comment]
It did, thank you very much!

**Comment by enaros** [comment]
awesome! worked for me as well, thanks a lot!

**Comment by Gareth4321** [comment]
I just got struck by this, and this command did the trick. BUT it has deleted all of my configurations, so now I have to go through and reconfigure everything. A pain in the backside, but at least I can use BTT again.

**Comment by fifafu** [comment]
@gareth4321 there are various backups in ~/Library/Application Support/BetterTouchTool which you can restore by removing the .oldversionbackup extension

**Comment by northwinds** [comment]
Unfortunately this didn't work for me:
"BetterTouchTool version incompatible
The Version of BTT you are currently using isn't compatible with the version of your data file!
Older copies of the data files are stored in ~/Library/Application Support/BetterTouchTool."|

OSX El Capitan - 10.11.6
