### ISSUE TITLE
Virus detected in VirusTotal ?

### ISSUE THREAD

**Issue by kmmypong** [fifafu/BetterTouchTool#1177]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Virus detected in VirusTotal ?

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: Latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![screen](https://user-images.githubusercontent.com/29917567/27860715-46afca30-61b0-11e7-9c54-4f32d8e182f4.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I already contacted webroot and they told me this is an error on virus total. I hope it'll be resolved soon.

**Comment by fifafu** [comment]
Hello, 

We have reported this to our developers. However, we can say that the Webroot agent is not actually detecting this file, this is just incorrect reporting in Virus Total. 

Regards, 
Webroot Advanced Malware Removal Team
