### ISSUE TITLE
Three finger swipe l/r fails

### ISSUE THREAD

**Issue by CalafAnon** [fifafu/BetterTouchTool#1178]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Three finger swipe left/right stops working, have to restart frequently. Recently Restarts also stopped helping. I had this problem, with the new version it came back, I am fairly certain that it was gone with the previous alpha.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBookPro11,5
macOS version: 10.10.5 (14F2411)
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Trackpad>Swipe... is definitely off
Btt restart helps 1 in 4

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think this should be fixed in the most current version (2.270)
