### ISSUE TITLE
The Version of BTT you are currently using isn't compatible with the version of your data file

### ISSUE THREAD

**Issue by paulittop** [fifafu/BetterTouchTool#1179]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.
Hello!
---

#### Description of bug/feature request/question:
The Version of BTT you are currently using isn't compatible with the version of your data file! Please update to a newer version of BTT. Maybe you have an old version in your startup items(autostart).

#### Device information:

Type of Mac:MacBook (13-inch, Mid 2009)
macOS version: 10.10.5 (14F2411)
BetterTouchTool version: I suppose last. Automatical updates was turned on.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by paulittop** [comment]
Thank you very much!
Now I'm understood that i can't do anything without BTT.
Have a nice day!
[btt_data_store.v2.zip](https://github.com/fifafu/BetterTouchTool/files/1124917/btt_data_store.v2.zip)

**Comment by fifafu** [comment]
Could you check whether this terminal command fixes the issue for you?

```
mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm.bac && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2.bac    
mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal.bac && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal.oldVersionBackup2.266 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal                     
mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm.oldVersionBackup2.266 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2.oldVersionBackup2.266 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2```

Just copy the whole thing into your terminal app and hit enter

**Comment by seratne** [comment]
Having the same issue, and the terminal command did not fix anything for me. Also running 10.10.5

**Comment by fifafu** [comment]
@seratne could you send me the bettertouchtool_backup.zip that was created on your desktop when running the terminal command? (to boastr.net@gmail.com)

**Comment by fifafu** [comment]
In case the above command doesn't work, please try this one. It will restore a slightly older backup (from may)

mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm.bac2 && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2.bac2 && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal.bac2 && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal.oldVersionBackup2.11 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-wal &&
mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm.oldVersionBackup2.11 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2-shm && mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2.oldVersionBackup2.11 ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2

**Comment by Harbs** [comment]
I had the same issue using 10.10.5 and the first command resolved it for me.
