### ISSUE TITLE
Having Truly Global Buttons on Touchbar

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#118]
#### Description of your bug/question/feature request...:
Can you add an option to have buttons that are truly global so that they also come on the custom touchbars. For example I would like buttons that do things like skip the song on the BTT touchbar without having to add it to all the custom touchbars. Also I know about the option to show the global touchbar buttons on the custom touchbars but I'm sure people have global buttons that they wouldn't like everywhere. 

**Other information:**
Just simply adding an advanced option to the button to make it show everywhere

**Comment by fifafu** [comment]
That's a great idea!

**Comment by Austin299792** [comment]
+1  please

**Comment by fifafu** [comment]
Added in version 1.971 / 1.972
