### ISSUE TITLE
Ignore Global for App?

### ISSUE THREAD

**Issue by bvanderw** [fifafu/BetterTouchTool#1181]
Is it possible to ignore global keyboard assignments in a particular app?

For example, I have ten global keyboard assignments defined. In one application (that for the most part provides it's own keyboard mapping), I only want one of the global assignments to be active.

Thanks....

**Comment by rodalpho** [comment]
Yes, but it's rather counter-intuitive, to say the least! 

Solution is to map the key combo or gesture for your specific application in BTT and set the action to "Use Apple Default or Do Nothing".

**Comment by fifafu** [comment]
Jup that's the way to do it currently!

**Comment by gswcm** [comment]
That trick doesn't work for Finder and Command-Up shortcut, that I globally set for "window maximize" action. The Finder gets maximized instead of navigating one level up.
