### ISSUE TITLE
Mac key sequence not working in MacVim

### ISSUE THREAD

**Issue by Sigfried** [fifafu/BetterTouchTool#1183]
#### Description of bug/feature request/question:

I'm trying to map the right option key to Ctrl. I've set it up as a key sequence:

![image](https://user-images.githubusercontent.com/1586931/27906083-14808b66-6210-11e7-9b88-19c6ae440323.png)

It works fine at the terminal, but not in MacVim. 

With Karabiner it works in MacVim as well:

![image](https://user-images.githubusercontent.com/1586931/27906445-8d463d4c-6211-11e7-8b07-2249c139fe15.png)

I don't know if this is a bug or I'm just not doing it right. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac:  MacBook Pro (Retina, 13-inch, Late 2013)
macOS version: 10.11.6
BetterTouchTool version: 2.266

**Comment by fifafu** [comment]
Hey,

Sorry, BTT is not made for remapping keys. Karabiner is the right tool for this! (It works on a different level, BTT only is useful for shortcuts that trigger actions, but not for permanently remapping keys)
