### ISSUE TITLE
Allow Touchbar actions to interact with one another

### ISSUE THREAD

**Issue by speedRS** [fifafu/BetterTouchTool#1184]
#### Description of bug/feature request/question:
Feature: Allow a specific action to update or interact with another action. 

The following is a rough example of what I'd like to achieve.

##### Action Names
Touchbar Action Name: **Currently Playing** (runs AppleScript to get the track details currently playing in Spotify)
Touchbar Action Name: **Next Song** (runs the Next predefined action)

##### Scenario

1. Click Next Song.
2. Song switches and as an additional attached action, causes the Currently Playing script to run
3. Currently Playing updates with the new track name

##### Potential Benefits
1. No need to set script interval time in particular scenarios
2. Potential for modularisation of functionality and reuse across various actions

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MacBook Pro (mid 2017)
macOS version: 10.12.5 (16F2104)
BetterTouchTool version: 2.265 (655)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Not particularly applicable here. Hopefully the use case is clear enough. I can provide further examples or more detail if it helps.

**Comment by speedRS** [comment]
If you feel it's more fitting, this could potentially be merged #1151, raised by @klassman.

**Comment by fifafu** [comment]
I’ll think about this. My main problem is to create a UI that allows you to configure this... (the feature would be awesome though)

**Comment by callodacity** [comment]
@fifafu Just an idea: rather than providing a UI to configure this, is it possible that you could provide a way to access the other Touch Bar buttons through AppleScript?

e.g.

Next Song Button 
```applescript
# script to run next song...

# script to action next button
tell application "BetterTouchTool"
  set touch_bar_buttons to every button

  repeat with touch_bar_button in touch_bar_buttons
    if the touch_bar_button label is "Currently Playing"
      touch_bar_button reload
    end if
  end repeat
end tell
```

Just a thought - would save you writing a UI for it.

**Comment by fifafu** [comment]
v2.430 now allows to update widgets/buttons using apple script. See https://updates.bettertouchtool.net/alpharls.html and  http://docs.bettertouchtool.net/docs/scripting_btt.html
