### ISSUE TITLE
Recovered Folder in Trash after logging in

### ISSUE THREAD

**Issue by Jasperdrex** [fifafu/BetterTouchTool#1187]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

Anytime you log into an account on the iMac, a folder appears in the trash called "Recovered Files".
This occurs with both standard and admin accounts.

Additional Note: The user accounts are not on the standard iMac storage, but have been moved to an additional hard drive.

e.g. System Pref ---> Users & Groups ---> Unlocked ---> Right button on account ---> Advanced options etc.....

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Using a 3rd party standard trackball ... Microsoft Trackball v1.0 (really old)

#### Device information:

Type of Mac: iMac 2.8 i5 8GB
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Confirmed its this software. Removed from auto load on log in and recovered folder doesn't appear in the the trash can.

Have added the prog into the main apps folder and in the individual account apps folder, but same issue.

When re-added. All works fine. Recovered only re appears when logging back into any account.

Additional 3rd party software installed
Avast Mac Security
No other running software on boot up.
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Why do you think this is related to BetterTouchTool? ;I don't think it is)

**Comment by Jasperdrex** [comment]
Because it only occurs when BTT software is running. When the program is removed, or the autoload-up option removed then the issue doesn't occur.

I’v tested this by making a single change each time and have discovered this only occurs with the issue I have explained. 

Have also create new accounts on the same machine and the issue is there (create accounts on the hard drive where the OS is and when the home directory has been moved to another location)

I have also installed the trial version on a different mac (same specs as the original one), again using accounts on a 2nd hard drive and on the hard drive of the original os and this too has the Recovery files folder flagging up (only when this software is running). Better still the software has this Recovery files folder appearing on the trail version on the software (without registration).

Also when just using the trial version, I haven't enabled any of the options (so its just the base system running) and haven't allowed any security & Privacy options).

Hope this help.

If needs be and I do a full clean install and retest (know that I know the same issue occurs with the Trial version)

All the best
Mark

**Comment by Jasperdrex** [comment]
Sorry about this. Just hold the fort there.

Have just done a clean installation and it looks like there is a clash with avast antivirus. Will get back to you with an update

Mark

**Comment by Jasperdrex** [comment]
Yep confirmed issue.

Its not Avast (security software). The issue only occurs when your have the home directory anywhere different from its original location.

As soon as you move it back to the original location all works fine.

Mark

**Comment by fifafu** [comment]
Sorry I have no idea what could cause this. BTT doesn’t put any files in such a folder by itself. What kind of files are placed in that “recovered files” folder?

**Comment by Jasperdrex** [comment]
no files are added, just a folder called “Recovered Files” is created in he Trash can folder. There is nothing inside this folder (empty folder)

Its really weird, only occurs as stated when the home directory has been moved.

Moving home directory example website
https://www.lifewire.com/move-macs-home-folder-new-location-2260157

Have checked Mac forums and this normally occurs when something doesn't close down normally. I have tested this by using the standard sleep mode, rest and shut down. I haven’t closed down the BTT software first before doing any of the above.

Have you replicated the issue?

The reason why I’m asking is both the computers I’m using have been reinstalled by myself (with the home directory being moved). As stated previously, no other running application on the computer other than Avast security.
The OS is running on an external SSD drive (USB3 connection being fast enough for the SSD), with the slower 1TB internal drive being used (3 partitions in this order) for recovery drive, home directory and last partition for general data. Granted not a normal configuration but the speed boost is noticeable to the Mac (and the saving to cost also noticeable).

The External SSD/internal Drive configuration works fine with no issues for just over 3 months (1st iMacs ever)

The software is fantastic (only needed for window snapping and back/forward to work on mouse/trackball) and can live with this folder niggle, just thought I’d mention it just incase there is a fix.

Thanks
Mark

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
