### ISSUE TITLE
Feature request - Tile windows, Minimize all windows + restore all windows

### ISSUE THREAD

**Issue by robertcch** [fifafu/BetterTouchTool#1189]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Since switching to Mac, I have missed the ability to instantly tile all active windows, as I end up wasting time resizing. I also wish I could minimize (not hide) all active windows and instantly restore them like I could in Windows. A workaround for the latter is Show desktop, but as soon as I access a file on the desktop, the other windows return, cluttering up the workspace.

Thank you for providing such a useful product! It's made a big difference.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

N/A

#### Device information:

Type of Mac: N/A
macOS version: N/A
BetterTouchTool version: N/A

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
While I like the idea of this, it is something that will not come to BTT. Unfortunately it is very complicated to build something like this given the macOS API limitations in that area. (I’m not saying it’s impossible, but it is too much for me to implement currently)

**Comment by robertcch** [comment]
Thanks for letting me know. I guess that’s why it’s never been done before.

A shame, as it’s such a useful feature.

Thanks for the great app!

Robert

**Comment by fifafu** [comment]
Maybe have a look at the trial version of an app called “Moom”. I think they had a similar feature (not sure how sophisticated, but maybe it is useful to you)

**Comment by robertcch** [comment]
Thanks for the tip, much appreciated.
