### ISSUE TITLE
Dragging windows freezes for a second.

### ISSUE THREAD

**Issue by deBhal** [fifafu/BetterTouchTool#1191]
#### Description of bug/feature request/question:

Dragging windows usually (but not always) freezes for about a second while some of the snap areas flicker.

Usually 2 or 3 snap areas flicker rapidly, and most of the rest flicker more slowly. The window being dragged freezes, but the mouse keeps moving. If you hold the mouse down during the freeze, the window will "catch up" when you move the mouse once the freeze is over, or if you let go of the mouse during the freeze the window stays close to where the move started, as though it received one last mouse movement after the window freezes.

I've tried to demonstrate with a gif, but the lag seems to interfere with the capture too. You can see the mouse pointer move without the window for a moment before the window catches up with it on the right-to-left drag, but the flickering barely shows in the gif.

It can It can happen any time any window is dragged, whether or not it's to a snap area, and it's been happening for a week or two, since an update around then. I've had to disable BTT :(

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

USB Mouse

#### Device information:

Type of Mac: Macbook Pro 2016
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![btt - lag dragging windows](https://user-images.githubusercontent.com/5952255/27999832-8ccb8b3c-6564-11e7-8b99-7f86cde56c43.gif)

**Comment by smaier** [comment]
same here - since 2 Weeks (second last update) - Macbook Pro Mid 2012 - Sierra 10.12.5, latest BTT. Had do disable Snap Areas now - which really sucks.

**Comment by docmars** [comment]
Same, it's getting really frustrating :(

- Macbook Pro Retina Mid-2015
- Sierra 10.12.3
- BTT 2.270

**Comment by fifafu** [comment]
Strange issue, on my systems the smap area performance has actually gotten much better with the last few changes.

Do you know whether your Macbooks have dedicated graphic cards?

For now you can also downgrade to a previous version (httpa://boastr.net/releases)

Best 
Andreas

**Comment by docmars** [comment]
I'm rocking the 2.5GHz i7 w/ Intel Iris Pro (1.5GB), 16GB system memory.

I'll roll back and see how it does. Thanks for the tip!

**Comment by docmars** [comment]
@fifafu I rolled back to 2.25 and things are fine now. Out of curiosity, I tried dragging some windows around with it running and am still noticing a very slight delay. Not enough to drive me crazy, but it's noticeable. Once I quit BTT, things are smooth as butter. :/

**Comment by deBhal** [comment]
I've got a 2.9 GHz Intel Core i7 16 GB with a Radeon Pro 460 4096 MB.

In case it helps reproduce, I'm also using two external monitors (2560 x 1440), with snap areas spread across both.

**Comment by dudeofawesome** [comment]
I'm experiencing this on multiple computers with `v2.270` since `v2.266` as well. 

- MacBook Pro 15" Late 2016
    - i7 2.6ghz, Radeon Pro 450
    - macOS 10.12.5
    - Only shows up when using an external display, both with iGPU and dGPU
- Hackintosh desktop 1
    - i5 4690k, GTX 1080 Ti
    - macOS 10.12.5
    - Shows all the time with 3 1440p displays
- Hackintosh desktop 2
    - i5 4690, GTX 960
    - macOS 10.11.6
    - Shows all the time with 2 1080p displays

**Comment by colinhiggins** [comment]
Confirmed that I was seeing the problem in 2.70. Rolling back to .261 fixed it.

![image](https://user-images.githubusercontent.com/5347796/28473428-58e5207e-6df9-11e7-9e75-d43460caf38a.png)
using an external display

**Comment by docmars** [comment]
Seems like the common thread is external displays. I neglected to mention I am using 2 external displays as well.

**Comment by xeroxoid** [comment]
Yep, same here. Reproducible on 2.270 but not 2.261.

Also have 2 external displays.

**Comment by fifafu** [comment]
I'm currently trying to reproduce the issue, but seem to be unable to on my machines.

Could anybody of you attach an export of your setup? (Using the manage presets button in BTT). Or alternatively go to the About tab in BTT and click the "Export Debug Info" button, and send me the folder BetterTouchToolDebug that will be created on your desktop (boastr.net@gmail.com)

One question:
Do you have this option enabled on your machines: ?
![image](https://user-images.githubusercontent.com/8820811/28998500-0e500b92-7a2d-11e7-8922-049b0548701b.png)

**Comment by dudeofawesome** [comment]
I have experienced the issue both with, and without that setting.

**Comment by fifafu** [comment]
Could you check whether this version changes anything? https://bettertouchtool.net/releases/btt2.271.zip

**Comment by deBhal** [comment]
The option you indicated doesn't make much difference (maybe a little bit faster?), but the one below it "Allow Snap Areas to snap if drag started inside of a snap area" dramatically improves things for me. Windows still freeze, but only for a fraction of a second.

This is short enough that I still notice it and I'd appreciate seeing it fixed, but I'm going to turn BTT back on and just drag a little bit more slowly than I would otherwise:

![screenshot_6_8_17__08_18](https://user-images.githubusercontent.com/5952255/28999233-51e4c668-7a82-11e7-80d6-46ac08e42872.jpg)


The new version changes things, but doesn't fix them. When they flash, the snap areas flash more slowly, but sometimes they flash for a very long time (as a result?). A couple of times it was long enough that I could let got of the window and get the osx spinning colour-wheel "wait" icon over the window I was dragging while the flashing went on.

Here's my settings export: https://gist.github.com/deBhal/d61147fb655c3645a34502dde9ac9aad

**Comment by fifafu** [comment]
If possible please try this version: https://bettertouchtool.net/releases/btt2.271.zip
I made some very significant changes to the way how snap areas are loaded, I hope this will resolve the issue.

**Comment by fifafu** [comment]
Sorry I just posted the wrong link. This one is correct:  https://bettertouchtool.net/releases/btt2.272.zip

**Comment by deBhal** [comment]
2.272 (661) is a very significant improvement for me, thank you! With the "Allow Snap..." advanced option off (the bad case), the problem is much rarer, and less serious. There is still a bit of weirdness and stuttering, but much less. With "Allow Snap..." enabled, I didn't see anything on my quick test, so I'm going to use that for now.

My initial impression is that this build + "Allow Snap Areas to snap if drag was started inside of a snap area" resolves the issue for me.

Note for other testers: Make sure you're testing the right patch. I had to rename the unzipped app to get OSX to run this version and not 2.271.

**Comment by dudeofawesome** [comment]
`2.272 (661)` looks perfect to me. Dragging windows is now faster than ever!

**Comment by colinhiggins** [comment]
I can't run 2.272. See attached image
![image](https://user-images.githubusercontent.com/5347796/29144228-01eb97f8-7d0d-11e7-8dbd-a2f0ecbd6b69.png)

**Comment by fifafu** [comment]
Maybe I forgot to sign the 2.272 version properly. Try 2.280 (which is available via "check for alpha version updates" or https://boastr.net/releases

**Comment by docmars** [comment]
@colinhiggins For future reference, if you right click an app and select **Open**, it will bypass this warning and give you the option to open anyway in macOS Sierra or higher.

**Comment by colinhiggins** [comment]
@fifafu, I'm seeing this crop up again in 2.305. Let me know if you want me to open a new issue since you closed this one.

**Comment by fifafu** [comment]
I had to revert the performance improvements as they caused various issues. However they should be back in 2.310 (different implementation but should be the same effect without the negatives)

You can try updating to 2.310

**Comment by colinhiggins** [comment]
Great. Not sure why it didn't auto-update, but I just did, and it seems to be working with no issues. Thanks!
