### ISSUE TITLE
Feature Request: Touch Bar action to switch to app-specific Touch Bar menu

### ISSUE THREAD

**Issue by NilsJPWerner** [fifafu/BetterTouchTool#1197]
#### Description of bug/feature request/question:
It would be awesome if an action could be added to switch to a specific apps Touch Bar menu. The specific use case I have in mind is a button to switch to the Spotify Touch Bar menu with the scrubber and playback buttons. (the bottom image: https://cdn.macrumors.com/article-new/2016/12/Screen-Shot-2016-12-23-at-9.22.13-AM.jpg)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 2016 15" Macbook Pro
macOS version: 10.12.5
BetterTouchTool version: 2.266

**Comment by fifafu** [comment]
Unfortunately the only way to show a specific apps Touch Bar is to bring that app to the front and activate it. That’s probably not what you want, but there is no way for me to access other apps Touch Bars :-(
