### ISSUE TITLE
Mouse gestures (drawings) only in defined app?

### ISSUE THREAD

**Issue by ZappoB** [fifafu/BetterTouchTool#1198]
#### Description of bug/feature request/question:

To reduce interference with other mouse gestures (e. g. Vivaldi or Firefox) it would be great, if the recognition of BTT drawings is only active in the defined app. To be clear: if I define a drawing for Safari, only when Safari is in foreground the beginn of a drawing should be recognised, otherwise not.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse, touchpad, Magic Mouse.

#### Device information:

Type of Mac: all
macOS version: Sierra
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
---

**Comment by fifafu** [comment]
I’ll look into that. (It should already be like this, if not that’s a bug)

**Comment by ZappoB** [comment]
Great, thank you!

**Comment by ZappoB** [comment]
Hi fifafu,

BTT has seen many updates since my request, sadly the mouse gestures still are recognised in any app, even if only one gesture for one app is active.

I do the workaround, that I disable BTT for Apps, in which right-mouse-movement is essential, but then all functions of BTT are lost.

It would be great, if you can have a look in this bug (as you wrote).

Have a nice weekend.

**Comment by fifafu** [comment]
It's still on my todo list. Should be fixed/ included in one of the upcoming versions (no eta though)

**Comment by ZappoB** [comment]
Thank you very much!

**Comment by fifafu** [comment]
This should now be fixed in 2.301 alpha! (get via check for alpha version updates)

**Comment by ZappoB** [comment]
Very fine, now it works as intended.

Thank you again!
