### ISSUE TITLE
[feature request] add hotkey to add new shortcuts / gestures

### ISSUE THREAD

**Issue by nikitavoloboev** [fifafu/BetterTouchTool#12]
#### Description of your bug/question/feature request...:
I wish users could press cmd + n or some other hotkey user can specify to essentially press these buttons : 

![2016-12-05 at 23 06](https://cloud.githubusercontent.com/assets/6391776/20904367/784f24e0-bb3f-11e6-850a-0b8d3bf2fb92.png)

![2016-12-05 at 23 06](https://cloud.githubusercontent.com/assets/6391776/20904373/80261098-bb3f-11e6-9697-90b910c0ceae.png)

Thank you. 

**What kind of Mac are you using?**
Macbook Retina 15"

**Which version of macOS are you running?**
El Captain

Thank you.

**Comment by fifafu** [comment]
Nice! Although using the move mouse action (relative to the window), combined with a leftclick, works for all add buttons in BTT :-)

**Comment by fifafu** [comment]
Added CMD+N and CMD+SHIFT+N to v1.964 alpha!
