### ISSUE TITLE
Start-up/Login Issue

### ISSUE THREAD

**Issue by semihyagli** [fifafu/BetterTouchTool#1201]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
_When Launch at start-up option is selected, BTT does not initialize itself unless a configured trackpad is pressed (e.g. 4 finger click)_

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
_Macbook Pro Trackpad_

#### Device information:

Type of Mac: _Macbook pro Late 2016_
macOS version: _macOS 10.12.5_
BetterTouchTool version: _2.265 (655)_

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
_Once you click on a configured click BTT starts, like in my case, I use 4 finger click to hide apps, once I click that, BTT recalls that it should restart, and restarts. I dont know if this is macOS behavior or BTT behavior, but so far hadn't noticed it (maybe it was there all along)_

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's not possible as BTT wouldn't even know about the click if is not running. Are you sure this is not just a timing issue? (It may take a few seconds until BTT launches after system start up)

**Comment by semihyagli** [comment]
I am not sure. This started happening after I installed google drive. Today, it just opened very quickly but I did the 4 finger click. Yesterday, I waited whole 15 secs until I decided to 4 finger click and start it. Of course, it could be a weird coincidence. Let me make sure of what's going on because I agree that BTT shouldn't know.

**Comment by fifafu** [comment]
Did this happen again? I’m closing here for now because I think this can’t be a BTT issue, but I’ll reopen if you still encounter the issue!

**Comment by semihyagli** [comment]
It does happen, but it is not about 4 finger click or anything defined in BTT (it was just freak coincidence). For some reason, sometimes BTT holds itself back before starting. The only thing that I can think of as a reason why is that in start-up, when google drive initializes, it immediately takes too much of the system sources for syncing, which causes BTT to delay its start. I don't think the issue is with BTT. There were times BTT managed to start itself before google drive (well, technically now it is called "back-up and sync"). I don't think there is much we can do about that. It really is google's fault. Thanks for the support!
