### ISSUE TITLE
Feature Request: Mapping to Touch ID button press

### ISSUE THREAD

**Issue by Jason-Morcos** [fifafu/BetterTouchTool#1203]
I noticed that Apple now allows users to map a specific accessibility action to triple pressing the Touch ID Button on the TouchBar within accessibility settings (10.13). It would be fantastic if users could map specific actions to double or tripping pressing the Touch ID button in BetterTouchTool (for instance, one may map Mission Control to double pressing the button)

**Comment by fifafu** [comment]
See #78. Unfortunately I have not yet found a way to make this work.
