### ISSUE TITLE
Keyboard shortcut with multiple characters, including arrow keys

### ISSUE THREAD

**Issue by dhempy** [fifafu/BetterTouchTool#1204]
#### Description of bug/feature request/question:

I'd like to have a mouse gesture that types "[up arrow][enter]" into a window. This is useful to run the previous command in a shell again. 

I can send an [up arrow] or [enter] from the "Trigger Other Keyboard Shortcut" option...but not both in sequence. 

I can send multiple characters from the "Insert/Paste Custom Text" predefined action. But I don't know how to send an [up arrow] from that tool. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All. 

#### Device information:

Type of Mac: MacBook Pro
macOS version:  OSX 10.12.5
BetterTouchTool version: BetterTouchTool v2.261 (licensed)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Sorry if this is not the correct place to request help. I've searched several ways for this answer and found no leads...so, I've either overlooked something completely obvious, or this will become a feature request.

**Comment by fifafu** [comment]
Hey, 
BTT always allows you to “attach additional actions” to any trigger. So your first action can send the up arrow, your second can send the enter key. Just click the “attach additional action” button on the right bottom side of the BTT preferences window.
