### ISSUE TITLE
Feature Request: Send Menubar-Item to other App than Active

### ISSUE THREAD

**Issue by ForestRingGames** [fifafu/BetterTouchTool#1206]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

It would be very cool to be able to send a menubar-item action to another app - or - alternatively - to be able to send any defined action to another app.

We're developing in Xcode and App Code and it would be awesome to have a hotkey in App Code to make Xcode build & run on a specific device. Currently we're using three hotkeys for three different devices - we also want to use that when App Code is in the foreground.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: iMac 2015
macOS version:  10.12.5 
BetterTouchTool version: 2.265 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can already send shortcuts to specific applications using the predefined action “send shortcut to specific app”, maybe you can somehow use that for your use case.

For triggering menu bar items I could use the fallback method used in that action - that is switching to the app, clicking the menu bar item, then switching back. Unfortunately there is no way to access an apps menu bar when the app is not frontmost.

**Comment by ForestRingGames** [comment]
Thanks for answering :) I kinda of tried all of these already.

I tried sending a shortcut to a specific app, but it does not allow to send BTT-specific shortcuts to the app. I tried to define a short cut for Xcode in BTT, then send a shortcut from AppCode to Xcode, but it does not send the BTT one (just a "normal" one).

I also tried switching to the other App, then triggering the menu bar action - or do I need to use a specific "click menu bar" action in this case? Switching to Xcode, trying to trigger menu bar did not work. I tested it by letting the menu bar open in a context menu....to see which menu bar menu is currently active and it was still the one of App Code - the app that I came from.

**Comment by kamykaze** [comment]
Hey @ForestRingGames , one thing you might want to try is using Distributed Notifications.

Basically, you set a gesture in Other to 'Receive Distributed Notification' with a custom key, then set the action to do whatever you want.

Then you can set a gesture in Xcode that 'Post Distributed Notification' with the same key. You can also do that for AppCode.

Now you can have the same (or different) shortcuts in different apps triggering the same action. In that action, you can then switch to XCode, and do your build & run action.

I'm not sure if this works exactly how you want it, but it allows you to avoid having to chain BTT shortcuts by having one central action that just "listens" to multiple triggers.

I use this when I have complex actions that I want to assign to multiple devices (keyboard, touchbar, trackpad) and don't want to duplicate the action.

Hope this helps

**Comment by ForestRingGames** [comment]
Hey @kamykaze, very good input! I've instantly tried it but unfortunately, I'm stuck at one point.

I can now trigger the shortcut to Xcode when switching from App Code....but the menu bar item trigger does not work. The menu bar actions in BTT seems to only work for the app where the original trigger came from. I even tried adding delays of ~5 seconds before and after the menu bar item trigger...even though the menu bar showed "Xcode" clearly the action was not executed.

![image](https://user-images.githubusercontent.com/21338444/28235188-4b93f98a-6909-11e7-8c2f-5e2b2c858044.png)

**Comment by kamykaze** [comment]
@ForestRingGames , Glancing at your screenshot, I see the menubar item you're trying to access has some special characters, specifically the single quote.

I'm not sure...it could be that BTT can't handle the quote. Can you try testing the same gestures with a different menubar item (one that doesn't have any special characters) and see if that's what's causing the problem?

**Comment by ForestRingGames** [comment]
@kamykaze I tested the exact same action as an Xcode-only action. So I set a menu bar item trigger for Xcode with this string and it works :)
