### ISSUE TITLE
Three finger drag stops working until BTT restart

### ISSUE THREAD

**Issue by Spirarel** [fifafu/BetterTouchTool#1207]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Three finger drag is an accessibility setting that allows you to emulate click-and-drag by simply dragging with three fingers. It's a native setting on Macs. It stops working under unknown conditions (seemly random) when I'm in the course of my day. When BTT is reset is goes back to normal.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Late 2013)
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.266 (656)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately three finger dragging alters various trackpad settings and causes many problems when used in combination with BTT. I‘m already trying to minimize the problems, but it‘s not really possible to get around all of them.

Are you using any gestures in BTT?

**Comment by Spirarel** [comment]
Huh, that's surprising. It seems this is a fairly recent issue, though. I've been using the app for years and have never needed to restart BTT before now.

Yes, but only a few [see attached]. I did a fresh install recently and imported my gestures. I've noticed the problem since that fresh install. Perhaps that's related or maybe the bug was introduced in a update in the past few weeks.

[gestures.pdf](https://github.com/fifafu/BetterTouchTool/files/1149814/gestures.pdf)

**Comment by humbamp123** [comment]
Any progress on three finger dragging?

**Comment by fifafu** [comment]
This should not happen anymore (many people reported three finger drag to work fine).
It's still not possible to completely support it while keeping all BTT gestures working, but the system functionality should work fine.

You can try the three finger drag optimizations to improve the behavior.
![image](https://user-images.githubusercontent.com/8820811/36248931-6c99e9b2-1239-11e8-884a-ae5523b694de.png)
