### ISSUE TITLE
Feature request: Window resize from any corner

### ISSUE THREAD

**Issue by jhorneai** [fifafu/BetterTouchTool#1208]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BTT currently offers window resize by holding some keyboard combination while dragging on the trackpad. This is incredibly useful. Please consider taking it one step further so that the window is resized from the corner closest to the pointer instead of always from the bottom right.

This feature was implemented brilliantly with the now discontinued Zooom/2 by CodeRage.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: any
macOS version: 10.12.5
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for your feature request! Unfortunately I have decided to not implement something like this. See #952 for more information.

**Comment by jhorneai** [comment]
Andreas, Thanks for considering the change. Also, thanks for making such a great piece of code. I depend on it every day and am lost whenever I switch to a Mac without it.  Cheers!
