### ISSUE TITLE
Gestures often not working in Microsoft Remote Desktop

### ISSUE THREAD

**Issue by notsosuperman** [fifafu/BetterTouchTool#121]
I have certain gestures set up specifically for Microsoft Remote Desktop. However, since getting a 2016 MBP they often don't work as much as they do. To reproduce this, create a app specific gesture for Microsoft Remote Desktop where a three finger click sends a alt-F4 signal, remote into a windows computer (I usually do full screen), and invoke gesture. Sometimes it will work, sometimes it doesn't. Restarting the computer seems to get it working again

**What kind of Mac are you using?**
2016 15" MBP

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.97

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

**Comment by notsosuperman** [comment]
Any idea about this issue? Thanks!

**Comment by CappyD** [comment]
I just tried defining a couple of touch bar buttons for use in Remote Desktop.  They each do simple keyboard shortcuts which work fine when done directly.  But if I use the corresponding TB buttons, they simply don't work.  I don't get it.

**Comment by notsosuperman** [comment]
So, I keep trying, hoping that this will be fixed in a release, but no luck so far. 

Any headway on this?

I have a three finger click trying to trigger alt-f4, and when I execute it, it looks as though only the Alt gets passed to the Microsoft Remote Desktop application, because the menu will highlight as if I just pressed the option/alt key, but the window does not close.

So, BTT is recognizing the gesture, and it is passing the Alt, but not the function key it appears. However, it will pass a function key by itself.

**Comment by notsosuperman** [comment]
Since it seems like this issue was not being resolved, I just switched to Royal TSX. Commands are passed fine into remote desktops here.

**Comment by CappyD** [comment]
@notsosuperman: Your comment above made me try Royal TSX, but I have not found that it works any better than MS RDP.  When I define a touch bar gesture to send something like cntl-9, they both seem to only get the 9.  Is there some setting I need in TSX or can you suggest anything for me to try?

**Comment by notsosuperman** [comment]
Open Royal TSX, right click on your RDP connection, click Properties, and
make sure the following is checked: Input > Windows Keys Passthrough. Also
make sure "Remap macOS keyboard shortcuts to their Windows Equivalent" is
checked (I am not sure if this is necessary, but it is an awesome option
anyway). Then close your connection and restart it.

I tried this with and without that checked, and only with it checked did it
pass the keystrokes through correctly.

Did that fix it for you?


Gabe Proulx
801-735-2009

**Comment by CappyD** [comment]
Thanks Gabe... that's the way I have it, but I think I found my problem:  I had defined the gesture as a  keyboard shortcut sending cntl-9.  It occurred to me that I should define it using actions: cntl-down, keyboard 9, cntl-up.  Now they seem to work.  Since I had done the same in MS RDP, I thought maybe this would work there too, but no - still fails there.  So, looks like TSX will work with the gestures properly defined.

**Comment by notsosuperman** [comment]
Weird. I do not have to use the actions. I tested and made a Ctrl-Tab
gesture as a keyboard shortcut, and had no problem with it being sent. But
hey, if you got it to work, that’s all that matters.


Gabe Proulx
801-735-2009

**Comment by chebz** [comment]
Any update when this will be fixed? This is pretty big for me, since I am limited to MS RDP and can't use most commands that require key combinations.

**Comment by fifafu** [comment]
ETA for a fix is early february when I will have a lot of time to work on BTT (see my blog https://boastr.net :-))

However it would be great if you could test something.

1. Quit BTT
2. Open a Terminal window and enter defaults write com.hegenberg.BetterTouchTool BTTShortcutSendingCompatibility2 YES
3. Open the BetterTouchTool preferences and add the Remote Desktop App to the list of Apps. Then enable "Compatibility Mode For Shortcut Sending".  (see screenshot)
4. Check if anything has changed.

![image](https://user-images.githubusercontent.com/8820811/34905257-4b621fe2-f855-11e7-9a31-323594f53732.png)

**Comment by MHX792** [comment]
Tried it with TeamViewer, unfortunately it didn't work. I would really love to see this added to BTT. Switchting from `CTRL+{X,C,V}` to `CMD+{X,C,V}` from window to window is sometimes exhausting.

**Comment by fifafu** [comment]
The new alpha version (v2.353) of BTT should work with Microsoft Remote Desktop.

**Comment by MHX792** [comment]
Thanks, but still doesn't work with TeamViewer 13.0.6447.

**Comment by fifafu** [comment]
v2.355 should also improve the shortcut behavior with TeamViewer
