### ISSUE TITLE
"BTT version incompatible"

### ISSUE THREAD

**Issue by joelismgrim** [fifafu/BetterTouchTool#1210]
#### Description of bug/feature request/question:

Upon installing a new SSD and updating to el capitan a few weeks ago, i have have persistent keychain issues which begun with BTT showing a dialog at startup stating that the version was incompatible.

Dialog box states:

"The version of BTT you are currently using isn't compatible with the version of your data file! Please update to a  newer version of BTT. maybe you have an old version in your start up items (autostart)

I did have a second HDD with another version of OS X installed on it, and i thought this was the problem. However after removing that, and still having the problem persist, i did a roll back and clean install to YOSEMITE, with the other HDD formatted.

Ran fine all day yesterday, but this morning the same dialog popped up.

any help would be much appreciated!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MBP trackpad

#### Device information:

Type of Mac: mid 2012 MBP 15"
macOS version: 10.10.5
BetterTouchTool version: 2.267

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
A restart will reset normally, but sometimes the issue persists

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting. I think this has already been solved here: #1175 thus I’m closing this issue.
