### ISSUE TITLE
MacOS crash caused by BTT ?

### ISSUE THREAD

**Issue by tb87** [fifafu/BetterTouchTool#1212]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
My brand new MBP crashed a couple times (screen stays black when I open the lid) and BTT appear in the logfiles not long before the crash. One user on Apple Communities suggested the crash might be related to BTT.

I'm not sure it _really_ is caused by BTT, but maybe you can have a look?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
None.

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.265 (655)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Please see crash logs at [https://discussions.apple.com/message/31991024?ac_cid=op123456](https://discussions.apple.com/message/31991024?ac_cid=op123456)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

The occurrences of BetterTouchTool in that log are normal and appear on every system- BTT just restarts itself after the machine wakes from sleep.
I don‘t think BTT would be responsible for the behavior you see. To be sure you could just quit using BTT for a bit and see if it still happens. (BTT doesn‘t modify the system, so it‘s not necessary to uninstall it)

**Comment by tb87** [comment]
Excellent, that's what I suspected. I'll investigate a bit further and report back if I still have doubts about BTT.

Thanks!
