### ISSUE TITLE
2.270 fails to install

### ISSUE THREAD

**Issue by lnchbx13** [fifafu/BetterTouchTool#1215]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Trying to download and install version 2.270 coming from version 2.267. It downloads and fails to unpack and install.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

It is failing to install. It's worked on all the betas so far (at least I haven't noticed any issues before now) but if the issue has to do with me having the beta version then my apologies.

#### Device information:

Type of Mac: Mid 2015 - MacBook Pro
macOS version: Version 10.13 Beta (17A306f)
BetterTouchTool version: 2.267 (Alpha I believe) installed (2.270 is the one I can't get to work)
![screenshot 2017-07-17 16 58 27](https://user-images.githubusercontent.com/15137589/28289901-6f064304-6b12-11e7-9326-f02745d580d5.jpg)
![screenshot 2017-07-17 16 58 11](https://user-images.githubusercontent.com/15137589/28289902-6f07f6b8-6b12-11e7-87d8-0f8348368b03.jpg)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by lnchbx13** [comment]
Well, not sure why the update didn't work using the update alpha version toggle within the app, but I saw on the docs a link to 2.20 and changed it to 2.270 and downloaded the zip file and it unpacked that way. I closed it out and replaced the app and now 2.270 is running. Just thought I would give you a heads up that it worked that way for whatever reason. 
![screenshot 2017-07-17 17 18 30](https://user-images.githubusercontent.com/15137589/28290314-f89f2076-6b13-11e7-8eee-3e9cded88e52.jpg)

**Comment by semihyagli** [comment]
Having the same issue, but I could not resolve it and still running the previous version. Thanks for prior post!

**Comment by fifafu** [comment]
Ah thanks for reporting, I may have copied in the wrong verification signature, thus unpacking fails for security reasons when auto updating.

I'll fix that in a few minutes.

**Comment by lnchbx13** [comment]
I used this link to download the zip file and install - http://bettertouchtool.net/releases/btt2.270.zip

**Comment by lnchbx13** [comment]
You're welcome, I didn't expect a response this quick or I probably would've just waited.

**Comment by fifafu** [comment]
Autoupdate should be working correctly now!
