### ISSUE TITLE
Q: Can I just replace default control strip with BTT icons while maintaining native per-app function?

### ISSUE THREAD

**Issue by DannySwish** [fifafu/BetterTouchTool#1216]
My goal is to replace the native global unexpanded control strip on the right of the TouchBar with my own custom icons using BetterTouchTool while still having the rest of the TouchBar (including expanded control strip via the little arrow) functioning as it would natively (contextual per-app buttons NOT created with BetterTouchTool).

Is this possible? I can disable the native control strip and have custom BTT buttons globally stuck to the right, but this disables the native contextual app buttons and obviously the option to have the original expanded control strip icon set, leaving one big blank space unless I "X" out of the BTT button layout I created. I want those 3 or 4 buttons to stay put regardless of what I'm doing, integrating the same way the native control strip does. What can I do?

**Comment by fifafu** [comment]
Unfortunately this is not possible due to API limitations. I think there is no way to make this work unless Apple gives us more options.
