### ISSUE TITLE
BTT button clears touch bar

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#122]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I'm not clear if this is a problem:  With system keyboard setting "touch bar shows: app controls" and BTT app-specific setting "touch bar behavior: show BTT touch bar; hide control strip", the left-most button is the BTT button.  What is this for?  If I tap it, the BTT touch bar I defined goes away and all that is there is an ESC button.  There seems to be no way to get my touch bar back other than to restart BTT.

**What kind of Mac are you using?**
2013 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.97

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

you can hide that button in the "General Touch Bar Settings" in BTT. It is just there to be able to hide the BTT Touch Bar.

You can get it back by using a shortcut or gesture and assigning the "Toggle BetterTouchTOol Touch Bar" predefined action.
However you are right, I think I should hide that icon by default

Best,
Andreas

**Comment by CappyD** [comment]
Thanks Andreas... Yes, I have sense realized I could hide the button and have created a keyboard gesture to redisplay my BTT-defined touch bar.  So now I can switch back and forth pretty easily even with the system control strip off.  Keeps looking better!
