### ISSUE TITLE
scroll application window in App Exposé.

### ISSUE THREAD

**Issue by kennazeng** [fifafu/BetterTouchTool#1223]
---
I am old user for bettertouchtool, I need a new feature.

#### Description of feature request

if open many many windows for one application, when using mission control App Exposé feature, display all application windows on the screen, all hidden windows display on the screen bottom, like **[this](https://www.dropbox.com/s/naki8afoi8uezq2/11.png?dl=0)**. but just few windows show in bottom,  we need using  left and right arrow key to scroll windows, that is not good.

please add a new feature: in this case, when scroll mouse wheel, scroll the windows on the screen bottom.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal mouse

#### Device information:
All Mac
All macOS Version.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry Unfortunately this is not possible due to technical restrictions (BTT can't know when App Expose is open)
