### ISSUE TITLE
Issue with touch bar control strip after awake from sleep

### ISSUE THREAD

**Issue by fulles99** [fifafu/BetterTouchTool#1224]
When I wake my MacBook Pro from sleep the touch bar's control strip is offset to the left meaning that the first icon and the < are not visible.  Restarting BTT fixes this.

It doesn't happen every time I wake from sleep though.

#### Device information:

Type of Mac: MacBook Pro 2016 13"
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.270

#### Screenshots

Touch bar after awake from sleep:
<img width="1085" alt="touch bar after awake from sleep" src="https://user-images.githubusercontent.com/30286057/28357485-7c85bc24-6c63-11e7-9ac5-035193fa7fb0.png">

Touch bar after restarting BTT:
<img width="1085" alt="touch bar after restarting btt" src="https://user-images.githubusercontent.com/30286057/28357499-871fc9ae-6c63-11e7-9d7c-ee9d9f7818e1.png">

**Comment by EricWVGG** [comment]
I have this same issue. I hadn't drawn the connection between it and wake-from-sleep, but I suppose I've never seen it pop up in the middle of work either.

I'd be happy to attach any preferences or settings files if that would be of use.
<img width="1085" alt="touch bar shot 2017-08-05 at 4 22 15 pm" src="https://user-images.githubusercontent.com/617762/28998504-cc9fc4d0-79fa-11e7-874b-6708622b3851.png">

**Comment by fifafu** [comment]
Unfortunately this is something I can't influence. However I haven't seen this behavior in the High Sierra Beta/GM so it should soon be solved!
