### ISSUE TITLE
Cannot setup Touch Bar to show Expanded Control Strip and custom BTT buttons toggled by Fn

### ISSUE THREAD

**Issue by miasma13** [fifafu/BetterTouchTool#1227]
Is it possible to use BTT in such setup that by default the Touch Bar displays expanded control strip and by holding Fn it switches to app specific BTT customized buttons?

I can only enable BTT custom buttons when Touch Bar in the System Preferences is set up to "App Controls with Control Strip". Doing so I am only able to display custom BTT buttons as a default and  expanded control strip under Fn key. But it is the reverse of what I want to achieve.

**Comment by fifafu** [comment]
With High Sierra this seems to be possible, unfortunately not with Sierra.

However as High Sierra will be released soon I'm closing here for now.
