### ISSUE TITLE
Force Quit Applications shortcut for the system failed

### ISSUE THREAD

**Issue by JingkangZhang** [fifafu/BetterTouchTool#1228]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When I enable touchbar customization on BTT, the original esc key sometimes doesn't work. I can use the command+option+esc to call force quit window, only when the esc key is from the BTT touchbar button expansion. My system esc key, however, can only be used alone, and cannot call force quit application when combined with command and option. My system esc key still fails even when turn off BTT touchbar. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
touchbar

#### Device information:

Type of Mac: MacBook Pro with touch bar 2017
macOS version: 10.12.5
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting, I’m tracking this issue here: #1116

**Comment by fifafu** [comment]
Sorry I meant #391
