### ISSUE TITLE
Add the option to remove the X button in TouchBar

### ISSUE THREAD

**Issue by tigredicarta** [fifafu/BetterTouchTool#123]
I use a shortcut to toggle BTT, but there isn't an option to hide the X icon in the TouchBar.

This is a bit strange also because the "esc" button changes its position to leave the space for the X button. It would be perfect if the close icon could be hidden or moved.

**Comment by fifafu** [comment]
Due to api limitations that's only possible when you hide the system control strip in the "general touchbar settings".
