### ISSUE TITLE
Feature request: add action to write text

### ISSUE THREAD

**Issue by PierBover** [fifafu/BetterTouchTool#1232]
I'd like to map a keyboard shortcut to write a piece of text.

As you will know, the backtick **`** is very common in programming, markdown, etc. Unfortunately when using latin keyboards it's pain to use. This symbol is an accent used to write these kind of characters `à`.

To solve this I'd like to map a shortcut to write the character itself.

It would not help to remap keys since the effect would be the same.

**Comment by fifafu** [comment]
You can use the " Paste / Type custom text" predefined action to do this.

Best
Andreas

**Comment by PierBover** [comment]
Oh I missed that. Thanks!
