### ISSUE TITLE
Better Touch Tool won't start on login, I always have to manually open it

### ISSUE THREAD

**Issue by WhyMe2** [fifafu/BetterTouchTool#1233]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you enabled "start on system start" in the BetterTouchTool preferences?

**Comment by sc-surfer** [comment]
Try adding it to your login items directly instead of relying on the checkbox in BTT settings?

**Comment by fifafu** [comment]
@tilo Because 90% of the users have never heard of login items.

**Comment by armgev** [comment]
You are being funny

**Comment by armgev** [comment]
Forget about BTT and install MagicPrefs. This is the solution. And the latter is free of charge :)
