### ISSUE TITLE
BTT touch bar close button shifts esc button to the right

### ISSUE THREAD

**Issue by andoro** [fifafu/BetterTouchTool#1234]
#### Description of bug/feature request/question:
When the BTT toolbar is opened, the esc button is not in the default position, so it's harder to find it.
Is this Close button necessary? I mean the BTT button already toggles the toolbar. If it's necessary it would be really good to change it's position, for example show it on the right side as Apple did by default.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro with Touch bar
macOS version: 10.12.5
BetterTouchTool version: 2.270 (658)

**Comment by fifafu** [comment]
Unfortunately the close button is an api limitation. I'd love to get rid of it, but that's not possible. You can choose to hide the macOS control strip in the general touchbar settings in BTT, this will also hide the x button.

Closing as duplicate #123

**Comment by andoro** [comment]
Ok thank you :)
