### ISSUE TITLE
Feature Request - Hit command when holding down mouse button 4

### ISSUE THREAD

**Issue by mattharrison** [fifafu/BetterTouchTool#1236]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I want to be able to emulate holding down command by clicking (and holding down) a mouse button. Specifically mouse button 4.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

I've got a CST-2545 with buttons for 4 and 5 and like to hit one with my palm for command

#### Device information:

Type of Mac: MacBook
macOS version: Sierra
BetterTouchTool version:  2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Currently this half works, but it keeps command in a held down state and doesn't release when the mouse button is released. I had this working in USB Overdrive, but it seems to have stopped working there.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should work if you configure it like this: (you can change the trigger by clicking the little gear icon left to the mouse button selection)

![image](https://user-images.githubusercontent.com/8820811/30249463-7b1f5da0-963d-11e7-8cc4-3d13b6939b1b.png)

**Comment by mattharrison** [comment]
Thanks I will give that a try. Didn't know about mouse up / cmd key up
