### ISSUE TITLE
Feature Request: Set scroll direction independently for mouse and trackpad

### ISSUE THREAD

**Issue by TheKuko** [fifafu/BetterTouchTool#1240]
#### Description of bug/feature request/question:

Feature request:
It would be great to be able to set scroll direction independently for classic (not magic) mouse and trackpad.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad, Mouse

#### Device information:
Type of Mac: MacBook Pro 13" 2015
macOS version: 10.12.6
BetterTouchTool version: 2.270 (658)

**Comment by greg-wolff** [comment]
For a workaround, see [Scroll Reverser](https://pilotmoon.com/scrollreverser/). This is what I use to get around this feature not being implemented in BTT.

**Comment by AlexKraemer** [comment]
In BTT, if you change from simple to advanced, and click on the mouse along the top bar, there is an option to invert scrolling for normal mice only.  Not completely independent, but has replaced scroll reverser for me.

**Comment by jhuleatt** [comment]
Yes! "Inverse scrolling for normal mice only" was exactly what I needed. Here is a screenshot in case others have trouble finding it:

![Inverse scrolling](https://i.imgur.com/NSBH3Zq.png)

**Comment by psigen** [comment]
@TheKuko: It sounds like this feature _is_ available in BetterTouchTool as noted by @jhuleatt in https://github.com/fifafu/BetterTouchTool/issues/1240#issuecomment-330922021 .  So would it make sense to close this issue?

**Comment by TheKuko** [comment]
Yes, I didn't know that it has to be closed by me. Thanks guys.
