### ISSUE TITLE
BetterTouchTool silently crashes multiple times per day

### ISSUE THREAD

**Issue by ins0mniaque** [fifafu/BetterTouchTool#1241]
#### Description of bug:

BetterTouchTool silently crashes multiple times per day while actively using the computer. I can't seem to find what triggers it, I just find my shortcuts not working anymore, or the touch bar button not there, and restart BetterTouchTool. I also often find it crashed after waking the computer, but it might just be coincidental.

#### Affected input device:

MacBook Trackpad / Touch Bar

#### Device information:

Type of Mac: MacBook Pro 13" w/ TouchBar (2017)
macOS version: 10.12.5
BetterTouchTool version: 2.266/2.270

#### Additional information:

I've attached [crash logs](https://github.com/fifafu/BetterTouchTool/files/1166368/crash.logs.zip) for both versions, but they all show the same stack trace:

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fff5c3140bc
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.SkyLight            	0x00007fffcbe28070 SLSCreateKeyboardEventWithFlagsAndStateOfLength + 528
1   com.apple.SkyLight            	0x00007fffcbe27e1c SLSCreateKeyboardEventOfLength + 349
2   com.apple.SkyLight            	0x00007fffcbe5ad92 SLSPostKeyboardEvent + 115
3   com.hegenberg.BetterTouchTool 	0x00000001039fe2e2 -[BTTShortcutter performShortcutForBindingOld:] + 806
4   com.hegenberg.BetterTouchTool 	0x00000001039f7497 -[BTTShortcutter performActionForGestureChildren:] + 957
5   com.hegenberg.BetterTouchTool 	0x00000001039f7025 -[BTTShortcutter performActionForGesture:] + 749
6   com.hegenberg.BetterTouchTool 	0x00000001039f8a92 -[BTTShortcutter performShortcutOrActionForGestureIDReal:checkOnly:additionalString:additionalNumber:bezierPathName:] + 485
7   com.hegenberg.BetterTouchTool 	0x00000001039f7a31 -[BTTShortcutter performShortcutOrActionForGestureIDMT:checkOnly:additionalString:additionalNumber:bezierPathName:] + 113
8   com.hegenberg.BetterTouchTool 	0x00000001039f78eb __113-[BTTShortcutter performShortcutOrActionForGestureID:checkOnly:additionalString:additionalNumber:bezierPathName:]_block_invoke + 50
9   libdispatch.dylib             	0x00007fffcf9b58fc _dispatch_client_callout + 8
10  libdispatch.dylib             	0x00007fffcf9c1ffb _dispatch_barrier_sync_f_slow_invoke + 295

**Comment by ins0mniaque** [comment]
Upon additional research, I have found that issue #990 seems to describe the same bug.

I've attached my [exported preset](https://github.com/fifafu/BetterTouchTool/files/1170623/Default.json.zip) in case it helps.

**Comment by fifafu** [comment]
This should be fixed now
