### ISSUE TITLE
Unable to Select Application using "Show Package Contents"

### ISSUE THREAD

**Issue by NSDodgers** [fifafu/BetterTouchTool#1242]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I am unable to select an application using "show package contents" in BTT.  I have touchbar buttons that I want to appear only when a certain application is in focus, however, that application is nested inside another package.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:

Type of Mac: 2017 15" Macbook Pro
macOS version: 10.12.6 
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In recent versions apps can be added from the list of running apps, thus this should be solved.
