### ISSUE TITLE
BTT stops responding to Finder keyboard shortcuts

### ISSUE THREAD

**Issue by prohtex** [fifafu/BetterTouchTool#1244]
I am having an issue assigning keyboard shortcuts in the Finder. I created a shortcut that triggers an  "Open Current Finder Selection With Specific App" event. The shortcut works fine exactly once. When I set it and switch to the Finder, pressing that key opens the selected file with the requested app. But if I select another file and try again, it stops working. Launching BTT and trying again works, but only for one file. If I foreground another app, then switch back to the Finder, the short works again, for just one file.

If I run "Live View" in BTT I can confirm that pressing the key combo triggers "Open Current Finder Selection With Specific App", but nothing happens after the first file.

I've tried many troubleshooting steps, including rebooting, killing the Dock, assigning different keyboard shortcuts or combos, etc. Nothing seems to work.

Type of Mac: iMac (Retina 5K, 27-inch, Late 2015)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.270

**Comment by fifafu** [comment]
I just tried this and it seems to work fine with the latest versions of BTT. If you still encounter this issue please comment again.

Best,
Andreas
