### ISSUE TITLE
Rotate complete Magic Trackpad orientation 90 degrees for "90 degree rotated" usage

### ISSUE THREAD

**Issue by spnkr** [fifafu/BetterTouchTool#1246]
Add a feature like the ```Mirror complete Magic Trackpad orientation for "upside-down" usage``` one, except rotate the input 90 degrees counterclockwise instead of 180 degrees.

Reason it would be useful:
My magic trackpad is too wide and I keep hitting it with my palms. If I could rotate it 90 degrees, so it's taller than it is wide, this would be great.

**Comment by fifafu** [comment]
Sorry, unfortunately the API only allows 180 degrees, thus I can not implement this :-(
