### ISSUE TITLE
Touchbar scrolls back after SHIFT or CMD

### ISSUE THREAD

**Issue by maudan380** [fifafu/BetterTouchTool#125]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have my touch bar so that to the far right I have to scroll to attain certain things (keyboard shortcuts mainly for typing accents). If I am scrolled all the way to the right and I am typing, as soon as I hit SHIFT or COMMAND, the touch bar scrolls back - and so I'd need to scroll back to the right to get these characters. - I'm scrolling back and forth -

**What kind of Mac are you using?**
13' 2016 TB

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2

Thank you!!

**Comment by fifafu** [comment]
Thanks for reporting! Should be fixed in 1.972

**Comment by maudan380** [comment]
Thank you!!!

**Comment by maudan380** [comment]
Hi Andreas,

I love the evolution of BTT and it has become indispensable for me. However, I keep having the same issue with the press of SHIFT or COMMAND if I open a TB group. For instance, I have a keyboard TB button for certain characters. If I am typing, that group closes every time I press SHIFT or COMMAND. Just putting it on your radar.

Keep up the wonderful job! I love BTT.

Have a great day!

Mauricio
