### ISSUE TITLE
AppleScript Widget will only show if the the return value is displayed and won't if "Only show icon, not the return value" is checked.

### ISSUE THREAD

**Issue by flyryan** [fifafu/BetterTouchTool#1258]
#### Description of bug/feature request/question:

I have a widget via AppleScript that displays the artist and song title when Spotify is playing a track. It works exactly how I'd expect it to. It displays if there is a return value (i.e. a song is playing) and disappears when it's not. To go with that, I created 3 new widgets via AppleScript for Previous, Play/Pause, and Next. I have them returning a value when Spotify is open but having them only displaying the Icon and not the return value. The goal is to have the buttons appear when Spotify is open. However, it appears the buttons won't appear when Spotify is open unless I display the return value. 

I believe this is a bug and the buttons should appear if there is a return value, even if it's not displayed. If I go into the Advanced Preferences for any of the three widgets and hit Save, the buttons will appear if Spotify is open. However, if close Spotify and re-open it, the widgets won't appear (unless I display the return value, as I stated earlier).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 2016 MBP 13-inch, 3.3 GHz Intel Core i7
macOS version: macOS Sierra 10.12.5
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here is a screenshot of the setup for one of the widgets I'm having issues with.

![Screenshot of Setup](https://user-images.githubusercontent.com/1487351/28607926-18daf024-71ac-11e7-994b-370e0e44b5ee.png)

**Comment by fifafu** [comment]
Hey,

thanks for reporting, I just fixed that. The fix will be included in the next alpha version (will be available later this weekend)

**Comment by flyryan** [comment]
Excellent! Thank you!

**Comment by flyryan** [comment]
Hi Andreas,

Did the Alpha release? My BTT hasn't updated. :-/

Thanks!

**Comment by fifafu** [comment]
Hey,

sorry, unfortunately I didn't make it last weekend. It will be released tomorrow!

Best,
Andreas
