### ISSUE TITLE
Allow hiding BTT icon

### ISSUE THREAD

**Issue by gdubicki** [fifafu/BetterTouchTool#1259]
#### Description of bug/feature request/question:

I would like to hide BTT icon. I don't change BTT settings on a daily basis and I already have too many icons there. BTT icon makes others, which I actually interact with, disappear.

#### Device information:

Type of Mac: MacBook Pro Retina 15 Late 2015
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.270

**Comment by fifafu** [comment]
Hi,

You can hide the icon in thw advanced preferences.
