### ISSUE TITLE
Problem with version numbers

### ISSUE THREAD

**Issue by BestMacsBen** [fifafu/BetterTouchTool#126]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I deploy BTT via munki within my organization and the way the CFBundleShortVersionString is formatted is causing munki to see a newer version as older. Munki compares the value of the CFBundleShortVersionString of installed vs the version it's checking for update to.

Example, current version of 1.963 is deployed, we add 1.97 to the update repo but munki interprets it as 1.963 > 1.97 (Thus 1.963 is newer) when 1.97 is the later update.

Should be an easy fix to start adding a 0 to the end of the CFBundleShortVersionString value when the the minor version is only 2 digits.

**What kind of Mac are you using?**
all Macs exhibit this behavior

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
not applicable to issue

**Which versions of macOS and BetterTouchTool are you running?**
1.963, 1.97

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Keep up the good work!

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
This sounds like a bug in munki but I'll try to keep that in mind for future updates 😊

(1.97 is obviously greater than 1.963)


Thanks for letting me know!
