### ISSUE TITLE
Conflict between Heroes of The Storm and BetterTouchTool

### ISSUE THREAD

**Issue by dariobanfi** [fifafu/BetterTouchTool#1260]
#### Description of bug/feature request/question:

Whenever BetterTouchTool is running and the game [Heroes of the Storm](http://us.battle.net/heroes/en/) is started, dragging mouse pointer (so clicking and moving the pointer) is showing a unpredictable lag.
The pointer is slowed down and doesn't keep its normal speed. The slowdown is not consistent either and lasts very shortly. 

This happens on every MacOS version (at least since Yosemite) and even with a fresh system and no custom rules set-up. I was able to reproduce this bug on different macbooks.

I do understand this is a very minor issue and feel free to close it in this case. I just solve it by closing BetterTouchTool before opening the game.
However I thought it's worth reporting it and if there is an easy solution it would be great.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse

#### Device information:

macOS version: 10.12.6
BetterTouchTool version: Latest

**Comment by rodalpho** [comment]
This won't actually fix the conflict or help you if you want to use a BTT binding inside your game, but if you click on the BTT menubar icon you can select "Disable BTT for current app".

**Comment by dariobanfi** [comment]
@rodalpho Wow thanks, I don't know why I didn't think about that!

**Comment by rodalpho** [comment]
Cool!

**Comment by fifafu** [comment]
Yep, that's probably the only solution to this problem, the bug would need to be fixed in Heros of The Storm, which is probably not going to happen.
It may however help to only disable "window snapping" for the game, see this screenshot:


![image](https://user-images.githubusercontent.com/8820811/28714698-d1f900a2-7394-11e7-8b00-7b8e0fb4ce7b.png)
