### ISSUE TITLE
Glitchy Animation with show/hide application

### ISSUE THREAD

**Issue by fabi94music** [fifafu/BetterTouchTool#1261]
#### Description of bug/feature request/question:

Bug with hiding/showing a window with a transparent sidebar e.g. messages.
When doing over BTT command on trackpad (I have "1 Finger Bottom tap left" set to hide/show messages). 
It seems that it takes a few moments to get the background color right. Looks a little glitchy.
(see screenshot GIF).

But however, when I do it via closing the windows and click on it on the dock to reopen or hide and show via e.g. Alfred the issue doesn't appear.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro Retina 2014 (15 inch)
macOS version: 10.12.6 (and earlier)
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![bug_btt](https://user-images.githubusercontent.com/29753374/28642651-69fb63b0-7253-11e7-81df-2f886ebeb420.gif)

---

**Comment by fifafu** [comment]
I have changed the order of commands in BTT from unhide => activate to activate => unhide, this may fix the described behavior (with the next alpha version sometime this weekend).

At least I can't reproduce it on my machine anymore. In case it still happens to you with versions >= 2.271 please comment again.

**Comment by fabi94music** [comment]
is 2.271 out already? :)

**Comment by fabi94music** [comment]
Hi, I tried build 2.271 (https://github.com/fifafu/BetterTouchTool/issues/1290#issuecomment-320471513) and the issue still persists.

**Comment by fifafu** [comment]
Ah that‘s unfortunate, this probably means I won‘t be able to change it in BTT as these are the only two calls made by BTT to hide/show windows :-(

**Comment by fabi94music** [comment]
Okay, but shouldn't it be the same animation when hiding the window (via x button) and than reopening via clicking the dock icon?

**Comment by fifafu** [comment]
It should, but that is something not handled by BTT but by the apps :-( (I just call the hide and show API from Apple)

**Comment by fabi94music** [comment]
Ah okay :) Thanks anyway. But you said, you could not reproduce it on your machine. So maybe something is wrong with mine? So you changed it on 2.271 right?

**Comment by fifafu** [comment]
Ahh wait, I think the fix wasn‘t included in the version I uploaded yesterday as that was just targeted at the other issue - sorry I didn‘t remember that correctly :-)

So there is still hope. The real version will definitely come later today.

**Comment by fabi94music** [comment]
Thanks a lot :) Your great! Really appreciate your support and your awesome App. BTT enriches my workflow everyday and BTT remote is really great too. 
There is only one thing I noticed => The size of files in file browser (BTT remote) are not displayed correctly. I have movies stored on an external SD card which I can access via file browser in BTT remote and the file size of my .mp4 movies are wrong (e.g. 605.89 MB instead of 4.93 GB). Maybe I open another issue.

**Comment by fifafu** [comment]
There is already an issue for that somewhere, I think something has changed with a macOS update. 
I‘ll look into that for the next bigger BTT Remote update.

**Comment by fabi94music** [comment]
Great, totally fine with that. Didn't affect usage, only cosmetically :)

**Comment by fifafu** [comment]
The new version is not yet released, but this build should contain the fix for this issue: https://bettertouchtool.net/releases/btt2.272.zip

**Comment by fifafu** [comment]
Ah I just noticed that while this fixes the animation, it changes the behavior of the action to something I don't want :-(
It now only hides the app if it's in the foreground... I'll check if I can workaround that but otherwise I'll have to revert it....

**Comment by fabi94music** [comment]
Works fine. Even when the app is not on the foreground. I have Safari on the foreground and my iMessage window shows up/hides with a my configured trackpad action.
