### ISSUE TITLE
Flux / Night Shift functionality

### ISSUE THREAD

**Issue by EricWVGG** [fifafu/BetterTouchTool#1263]
#### Description of bug/feature request/question:

It would be wickedly awesome if BTT could detect Flux or Night Shift and adapt the Touch Bar palette. It's currently around midnight, my screen is a pleasant and functional amber, and the Touch Bar is glowing like a prop from Tron.

**Comment by callodacity** [comment]
I wonder how difficult this would actually be, considering it took F.lux a long time to be stable on macOS (IMO it never fully was). This would require some knowledge of display-based private APIs.

**Comment by fifafu** [comment]
Sorry, this probably won't be added to BTT. As @callodacity mentioned it would be quite complicated :-(

I'd rather try to send this feature request to Apple.

**Comment by callodacity** [comment]
@EricWVGG you can send “Enhancement Request”’s to Apple [here](https://www.apple.com/feedback/macbookpro.html) for the MacBook Pro 👍
