### ISSUE TITLE
BTT Keeps Crashing and Reopening

### ISSUE THREAD

**Issue by nrcarnevali** [fifafu/BetterTouchTool#1268]
#### Description of bug/feature request/question:
BTT crashes randomly and then reopens. Doesnt seem to crash at any specific time. It happens about every ~5 minutes or so and the only app I am using is Chrome.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad

#### Device information:

Type of Mac: Macbook Pro Late 2013
macOS version:  10.11.6
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I ran the export debug from about menu.
[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1185396/BetterTouchToolDebug.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by nrcarnevali** [comment]
Furthermore I count 20 crashes in the "User Diag Report" section. Here are the 20 errors.
[Console_err.zip](https://github.com/fifafu/BetterTouchTool/files/1185399/Console_err.zip)

**Comment by fifafu** [comment]
It seems to crash for some reason while sending a keyboard shortcut. I looked at your setup and it looks fine. Maybe the fn+scrollup/down gesture is causing issues? Do you remember if BTT quits when using that gesture? Or is it really random?

**Comment by nrcarnevali** [comment]
Figured it out last night after I finally could repeat the behavior.

For some reason everytime I completed a two finger swipe down it crashed.

I checked BTT and I had two finger swipe down added but no shortcut or "function" tied to it.

Once I delete it all crashing stopped.

Maybe a weird bug I found? This was from an import *.json file and repeatable on two Mac's.

**Comment by fifafu** [comment]
Thanks a lot for figuring this out, this bug should be fixed with the next update!
