### ISSUE TITLE
Erratic tracking of Magic Mouse 2

### ISSUE THREAD

**Issue by roamingbob** [fifafu/BetterTouchTool#1269]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have frequent issues with my Magic Mouse 2 showing erratic tracking, most notably the pointer doing small jumps or having slight lags when slowing the transit speed to get to a precise/particular location on the screen.  
The problem seems to "accumulate" - while there are no issues after a cold start of my computer, the issues seems to appear after several hours of using my computer an mouse.  
I have not done all the testing to see if it is directly related to running the BetterTouch tool, but wanted to see if others have experienced similar issues with the BetterTouch tool.  Naturally if I bring the issue to Apple, I anticipate the first response is that it is the aftermarket product.    

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse 2
(I don't use my built in track pad with sufficient frequency to know if it also has such issues.  

#### Device information:

Type of Mac: MacBook Pro Retina (mid-2014)
macOS version: El Capitan 10.11.16
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by PinStudios** [comment]
Same here on 2016 MBP 15". Drives me insane. Do you happen to use dual external monitors? I think started experiencing this after connecting 2 external monitors (usb-c->dp, hdmi->hdmi). I have unplugged HDMI one now and the problem seems to go away or at least decrease significantly. If it's not back tomorrow (when I have office mated with all their BT stuff in the office :)), I'm trying to switch other one on (or leave HDMI one on, and ubs-c one off) to see if it's HDMI related or dual monitor related.

**Comment by fifafu** [comment]
I also don't think erratic tracking can be related to BTT, but if I'm wrong please reopen/ comment again!

**Comment by PinStudios** [comment]
@fifafu - unless you try to move mouse, it shouldn't. http://dae.me/blog/2144/on-macos-sierra-support-and-the-future-of-smoothmouse/ this shows why sierra essentially eliminated 3rd party mouse "drivers". I have already switched to logitech :(
