### ISSUE TITLE
Newer versions break sleep on hackintosh

### ISSUE THREAD

**Issue by crayonshin** [fifafu/BetterTouchTool#1270]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Newer versions of BTT have broken sleep on what was a perfectly functioning hackintosh. Before, my system would always sleep and wake perfectly. With newer BTT versions however, my system will go to sleep but when I wake it up, it goes through the whole boot process because it actually shut down instead of sleep. I troubleshooted many hours including fresh installs and step by step installation of applications before I found out it was BTT causing the problem. If I closed BTT before putting the hackintosh to sleep, it would wake up perfectly exactly where I left off. If I forget to close BTT and go to sleep, system actually power off. I think this started happening with the the big 2.10 change that changed the data format.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

BTT itself is working fine with my Magic Trackpad 2

#### Device information:

Type of Mac: hackintosh
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Luckily, I had a backup of an older version and configuration file (version 2.071). This version still works on 10.12.6 and does not break sleep so I am using it for now. Any idea what the problem could be? Let me know if there's files I can send you to diagnose the issue. I know it's a hackintosh so you might not be too concerned about fixing it but it's weird that it worked perfectly with the older BTT versions. Thanks for a great application!

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In general BTT is just an app and shouldn‘t be able to cause something like this.
However I myself had experienced something similar with the Wacom Tablet Driver that was installed on my machine and apparently sometimes crashed after boot when BetterTouchTool was trying to interact with it (due to a bug in the driver).

Do you maybe also have the Wacom Tablet driver installed?

**Comment by crayonshin** [comment]
No, I don’t own or use any Wacom devices. Today, I spent all day trying to find what is conflicting with new versions of BTT. I started with a fresh install of Sierra 10.12.6 and installed only the minimum amount of drivers/kexts/patches I needed to get all of my hardware working. I then tried many different setting in the Clover EFI boot loader I used but nothing worked. That means BTT is conflicting with something I must have instated. The older is still working fine so I am still using that. Thank you for replying to my issue thought!

Regards,
Andres

**Comment by sjamesparsonsjr** [comment]
Andres, I'm interested in your hackintosh, can you tell me more about your setup?

**Comment by crayonshin** [comment]
Sure, let’s start with the hardware:

Motherboard: Gigabyte X150M-PRO-ECC
CPU: Intel Xeon E3-1230 v5
RAM: 4 x 16GB Crucial DDR4 2133 ECC (CRUCT16G4WFD8213)
Video: Nvidia Geforce GTX 1080
Power Supply: Seasonic Flagship PRIME TITANIUM 650 SSR-650TD
NVMe SSD: Samsung 960 EVO 500GB

Now software:

OS: macOS Sierra 10.12.6 (install USB made with tonymacx86 UniBeast 7.1.1)
Initial setup done with tonymacx86 MultiBeast 9.1.0. See attached screenshot of options selected.
I use rehabman’s NVMe spoofed driver for my EVO 960: https://github.com/RehabMan/patch-nvme <https://github.com/RehabMan/patch-nvme>
Nvidia web drivers for video card, version 378.05.05.25f01
I updated Clover EFI to version 4128
Finally, Toleda’s HDMI audio script: https://github.com/toleda/audio_CloverHDMI <https://github.com/toleda/audio_CloverHDMI>

I tried installing to a regular SSD to see if the NVMe driver was causing problems but regular SSD had the same problem. I also tried installing the bare minimum I needed to get sleep working which was the MultiBeast setup without audio, ethernet and USB patches PLUS the Nvidia web drivers. The problem still occurs with this minimal setup.

Sleep works perfectly with last version of BTT before switch to JSON (2.071). Any version after that will look like it went to sleep but when I wake it up, I can see it shut down instead.

Please let me know if you need any more information. Thanks for your help!

Andres

**Comment by crayonshin** [comment]
Sorry, forgot to attach the picture with my tonymacx86 UniBeast options. Attached it to this email. Thanks again!

Andres

**Comment by crayonshin** [comment]
Sorry again! I forgot to include my WiFi card in the parts list. It’s a Chinese-made PCIe card based on Apple BCM94360CD and uses native OS drivers. Here is an eBay link:

http://www.ebay.com/itm/Broadcom-BCM94360CD-802-11ac-1750Mbps-Desktop-PCi-E-WiFi-Adapter-Hackintosh-BT/302395660256?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2055119.m1438.l2649 <http://www.ebay.com/itm/Broadcom-BCM94360CD-802-11ac-1750Mbps-Desktop-PCi-E-WiFi-Adapter-Hackintosh-BT/302395660256?ssPageName=STRK:MEBIDX:IT&_trksid=p2055119.m1438.l2649>

Thank you!

Andres

**Comment by austenc** [comment]
This is also happening for me, quitting bettertouchtool (running in the menu bar) fixes the issue. Let me know if I can help

**Comment by crayonshin** [comment]
I have upgraded my hackintosh to High Sierra 10.13. After everything was working, I updated BTT to the current 2.305 and now sleep is working perfectly again! It must be something changed in macOS because I had tried BTT 2.305 with Sierra 10.12.6 just a few days ago and sleep was still broken. So my advice is if your hackintosh is still on Sierra, use BTT 2.071 until you upgrade it to High Sierra 10.13, then you can upgrade BTT to the current version.
