### ISSUE TITLE
Global Keyboard shortcut issue on High Sierra Beta

### ISSUE THREAD

**Issue by svajiraya** [fifafu/BetterTouchTool#1272]
#### Description of bug/feature request/question:

Global Keyboard Shortcurt is not working in high Sierra beta. I had setup Cmd+shift+Opt+L to lock screen and it used to work fine on Sierra. After updating to High Sierra, it stopped working. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mac Keyboard

#### Device information:

Type of Mac: 15" MacBook Pro with Retina display (Late 2013)
macOS version: macOS High Sierra 10.13 Beta (17A315i)
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
[BTT Debug Export.zip](https://github.com/fifafu/BetterTouchTool/files/1186624/BTT.Debug.Export.zip)

**Comment by johnnyboi1994** [comment]
this happened to me as well, but in the meantime you can use Shift+Control+Power(or Eject depending on what model device you have)

**Comment by Wipeout944** [comment]
...chiming in to say me too, with BTT 2.300 and the High Sierra GM build on my 2017 MBP.

**Comment by fifafu** [comment]
If possible try 2.302 alpha, it fixed various keyboard shortcut issues.(Get via check for alpha version updates)

**Comment by Wipeout944** [comment]
...just tried that--both keyboard shortcut of same combo (Control Option Command L) and a Touchbar shortcut set to Lock Screen don't do anything. If I have BTT preferences open, that jumps to the front, but it doesn't, well, lock.

**Comment by fifafu** [comment]
Ah now I see what you mean - the predefined action "Lock Screen" is not working on the GM.
However that's not really a big problem as Apple has added a Lock Screen shortcut anyways (by default it's ctrl+cmd+q). So for now you can just assign that shorcut to your touchbar action like this:

![image](https://user-images.githubusercontent.com/8820811/30515795-c814b056-9b2e-11e7-80e7-befc292d577e.png)

But this is not related to keyboard shortcuts as far as I can tell.

**Comment by Wipeout944** [comment]
Had no idea they'd added that keyboard shortcut; thanks for that!

**Comment by fifafu** [comment]
Perfect! The predefined action will also be fixed with the next update, thus I'm closing here.

**Comment by HeffZilla** [comment]
Is this out in production already?  I ask because my Global keyboard shortcuts aren't working at all. I am on version 2.320.
