### ISSUE TITLE
Window Snapping padding issue

### ISSUE THREAD

**Issue by xemb23** [fifafu/BetterTouchTool#1275]
My issue is with window snapping. When I try to make it full screen, by dragging any app to the top of the screen, there is still some pixels of space at the bottom of the screen. No matter how I change the setting (when I go to advanced setting and window snapping) and change the padding settings, it doesn't fix it . there is always space and it bothers me. Please let me know if I am doing something wrong. 

#### Device information:

Type of Mac: Macbook Pro Touchbar 13" 2016 edition
macOS version: 10.12.5
BetterTouchTool version: 2.270

Screenshots

The space at the bottom of the screen (I set my dock to hide). You can see the orange bar (from my screen background) under my browser window. 
![image](https://user-images.githubusercontent.com/30612442/28807699-d7ecad12-7644-11e7-99c6-19a1c1c1d77e.png)

My current settings:
![image](https://user-images.githubusercontent.com/30612442/28807974-c1a249ca-7646-11e7-9335-bd470be7c9b4.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

Sorry, this is a system limitation given by Apple. It appears if the Dock is hidden. As far as I know there is no workaround. (It happens even if you resize windows manually)
