### ISSUE TITLE
Documentation link shows http://https://

### ISSUE THREAD

**Issue by uwnot** [fifafu/BetterTouchTool#1277]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

On the top of the window, where it invites to read the documentation, link is miswritten.

<img width="1127" alt="captura de pantalla 2017-08-01 a la s 11 50 04" src="https://user-images.githubusercontent.com/197329/28834299-dbbfea06-76af-11e7-8a20-26a21044525a.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 2017 15"
macOS version: 10.12.6
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting will be fixed with the next update!
