### ISSUE TITLE
"Hide BTT Touch Bar if nothing to show" <- does not work

### ISSUE THREAD

**Issue by AdamJaffrey** [fifafu/BetterTouchTool#1279]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

There is a setting to have Touch Bar support enabled, but hide the BTT button if there are no actions configured. I currently have no actions configured, but the BTT button is showing in my Touch Bar. (Screenshot below.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1035" alt="screen shot 2017-08-02 at 1 11 20 pm" src="https://user-images.githubusercontent.com/30644294/28856184-d23d7806-7784-11e7-8ce1-a508810d6b41.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by AdamJaffrey** [comment]
@fifafu Any thoughts on this issue? Is it a bug, or is my version of BTT playing up?

**Comment by fifafu** [comment]
This behavior should be better with current BTT versions. In case you still encounter it, please comment again.

**Comment by AdamJaffrey** [comment]
Hey there. This was initially fixed (thanks!) until I created a Touch Bar widget and then deleted it. Now the BTT Touch Bar icon won't go away again. I don't have any widgets or anything saved, but it still shows the BTT Touch Bar icon.

**Comment by SweetJD** [comment]
I am also experiencing this issue.
