### ISSUE TITLE
CPU Usage through the roof // System instable and unusable

### ISSUE THREAD

**Issue by PiaKlarus** [fifafu/BetterTouchTool#128]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
After setting up my own touchbar icons (mostly dock features moved to touchbar - apps etc.) I get very heavy cpu usage. Activity monitor confirms that it is btt. :-(

Besides links starting apps I added a Wi-Fi and BT toogle via Apple Script commands.

**What kind of Mac are you using?**
MacBook Pro (13-inch, Late 2016, Four Thunderbolt 3 Ports)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
Sierra 10.12.1 
BTT 1.97

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Activity Monitor Snip attached
<img width="848" alt="bildschirmfoto 2016-12-17 um 18 01 09" src="https://cloud.githubusercontent.com/assets/24624998/21288444/4a9e62ac-c483-11e6-9509-097ca4dd5b61.png">

Added Gesture Export File

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

[Pia_CPU_Lag.zip](https://github.com/fifafu/BetterTouchTool/files/658947/Pia_CPU_Lag.zip)

**Comment by fifafu** [comment]
Weird, have you tried to restart BTT?

**Comment by PiaKlarus** [comment]
If I am the only one - then it's weird.

Yes I did - got normal until I opened BTT preferences - then the CPU usage got over the top and Sierra got laggy.

Maybe because of those toggle scripts?

But it happens now directly after start...didn't even use anything.

I'll try a fresh install...maybe it helps

**Comment by fifafu** [comment]
You could also sample the process via activity monitor and send me the output (to boastr.net@gmail.com in case it contains private data)

https://support.omnigroup.com/sample-osx/

**Comment by PiaKlarus** [comment]
OK...

After todays 10.12.2 Sierra Update and a fresh installation everything works fine.

Who knows what happened before.

**Comment by PiaKlarus** [comment]
The Issue is back again - and now I have at least a first root cause...

- as I reinstalled BTT it was Version 1.96 
- now I updated to 1.97 --> Issue is back.

** Difference between versions: TouchBar - Item Placement - "Stick to right" 

Might this be the reason?
<img width="388" alt="bildschirmfoto 2016-12-20 um 06 21 02" src="https://cloud.githubusercontent.com/assets/24624998/21339098/986fcc00-c67c-11e6-9367-01b8a3d96c02.png">

**Comment by PiaKlarus** [comment]
Yep...that's the problem.

The Feature "Stick to the right side of the TouchBar" causes the heavy CPU load.

When I set those buttons back to "scrollable containers" and restart BTT the CPU usage is back to normal!!!

**Comment by PiaKlarus** [comment]
5 hours without disruption - root cause found.

**Comment by fifafu** [comment]
Thanks a lot, I'll look into that!

**Comment by fifafu** [comment]
Thank you very much, I have identified the issue and it will be fixed with the next update (probably later today)
