### ISSUE TITLE
Trackpad wrong handling of click when other finger is touched

### ISSUE THREAD

**Issue by radiax** [fifafu/BetterTouchTool#1280]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BTT makes the Trackpad works differently as in default OSX mode:
When I handle the Trackpad in following way: with 1st finger I slide over the Trackpad, I don't put finger up (so it is still touching the Trackpad) and I perform a click with secondary finger - it is not applied. So   once I do not put 1st finger up, I cannot perform 2ndary finger click. It is very annoying, as normally you just move the cursor to some position and want to click, without the need of putting the 1st finger up. May be it is just my personal habit, but disabling the BTT it works perfectly.

I tried to change the advanced settings for Trackpad, but I did not succeed.

Please try to fix that - BTT is the most perfect tool I have found on OSX, I would not like to get rid of it just because such small stupid bug.

Thank you for your excellent work!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook PRO 13", 2017 model
macOS version: Sierra, 10.12.16
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's probably not a bug but by design. Which gestures do you have configured in BTT?

**Comment by radiax** [comment]
Oh, so you think some of my gestures is in conflict with that?
I use no drawings, but several gestures - but I don't think it should cause trouble. As I cannot just disable them, I modified all of them to be applied just with FN key pressed (so the are not active). Wrong behaviour still occurs :(

**Comment by radiax** [comment]
Strange - I changed the haptic feedback for 2-4 fingers click - and now from haptic I can identify that BTT recognises my "special" click, because he gives the new special haptic feedback. Which means he takes the special click as something other than 1 finger click. I will play around with various gestures to find out which ones is that - then I can set is to normal behaviour by emulating the standard one click.

**Comment by radiax** [comment]
So - I found workaround but it is very strange. As soon as I add new trackpad gesture for "TipTap Left (1 Finger Fix)", even not adding any action to it - the strange behaviour stops. As soon as I remove it, it is back again. I guess this looks like a bug :)

**Comment by fifafu** [comment]
That's what I thought. Unfortunately BTT needs to block these clicks if a tiptap gesture is added, otherwise tip taps would always trigger a click ;-(
