### ISSUE TITLE
[Q] How come "open URL" predefined action does not open safari?

### ISSUE THREAD

**Issue by donpd** [fifafu/BetterTouchTool#1281]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm trying to create custom button shortcuts for the touch bar. I want to be able to open a specific site, like youtube on a press of a button. I went with the predefined action "Open URL/ Open URL with selection" then I typed in "www.youtube.com". When I try to run the command a popup says this:
![screen shot 2017-08-02 at 8 20 08 pm](https://user-images.githubusercontent.com/30657480/28873399-17ce2b32-77c0-11e7-8470-a5375913cdac.jpg)

I could manually select Safari to open it but I would have to do it every single time.
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 2017 Macbook Pro 13" w/ touchbar
macOS version: macOS Sierra 10.12.6
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

you need to add http:// before the www :-)
Sorry for not replying earlier!

**Comment by donpd** [comment]
I completely forgot about this. Thank you very much!! It's fine, I appreciate the help :)
