### ISSUE TITLE
CTRL is not sent through Microsoft Remote Desktop

### ISSUE THREAD

**Issue by MojoDK** [fifafu/BetterTouchTool#1283]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I've set up a TouchPad button, so when I press the button, the action is CTRL + R. When I switch to the Microsoft Remote Desktop app and presses the button, all I get is R - no CTRL. How can I make BetterTouchTool send the CTRL through Microsoft Remote Desktop?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
TouchPad

#### Device information:

Type of Mac: MacBook Pro 15" 2016
macOS version: High Sierra Beta 4
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by philrj** [comment]
I've had sporadic CTL key issues in both ARD and Screen Sharing when sending CTL-clicks on a Magic Mouse.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Magic Mouse (original)

**Device information:**

Type of Mac: MacBookAir4,1
macOS version: 10.11.6
BetterTouchTool version: 2.280

**Comment by fifafu** [comment]
Tracking this here: #121 
There will be a solution to this soon!
