### ISSUE TITLE
Battery Widget Option Request

### ISSUE THREAD

**Issue by z20235** [fifafu/BetterTouchTool#1285]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac: MacBook Pro 13" (2017)
macOS version: 10.12.6
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.): N/A

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The latest alpha version allows this in the advanced widget options!
