### ISSUE TITLE
Incorrect error when no space left

### ISSUE THREAD

**Issue by krokofant** [fifafu/BetterTouchTool#1286]
#### Description of bug/feature request/question:
When the disk space run out the follow error is show:
![image](https://user-images.githubusercontent.com/5908498/28929007-2cb8f806-786f-11e7-9adb-4a0a1c63eb91.png)

MacBook Pro
BTT 2.270
macOS 10.12.6

**Comment by fifafu** [comment]
Thanks for reporting!
However I probably won't fix this if it only affects disks that have run out of space (that's such an edge case, I think it's not worth the effort to fix)

In case this also happens with space left - please comment again.
