### ISSUE TITLE
Cannot locate Minecraft.app

### ISSUE THREAD

**Issue by Antairez** [fifafu/BetterTouchTool#129]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Since Minecraft.app launches a launcher before we could actually start the game, the game process itself can't be located by the BTT. I tried using Disable BTT For Current App from the menu icon just to get it forcefully locate the process name, it appears empty inside BTT. I could get it to work for the duration of lifetime of BTT, but the configuration won't be saved due to not having a name.
BTT gives error message "name is a required value." each time I try to close the app.

![image](https://cloud.githubusercontent.com/assets/7032726/21288603/f0a49ccc-c4c2-11e6-8b1c-071ccc377ed6.png)

**What kind of Mac are you using?**

2016 Macbook Pro Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

All

**Which versions of macOS and BetterTouchTool are you running?**

10.12.2

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by Antairez** [comment]
Can I suggest that the BTT should let the user decides the name of the process if it can't find one itself?

**Comment by fifafu** [comment]
Unfortunately BTT currently works on the app, not on a specific process. I'll check if this could be added - but I'm not sure yet.

**Comment by Antairez** [comment]
@fifafu Thanks, just wanted to point out that I'm able to get BTT to work even when it doesn't recognize the process name. It's just that savings is not possible - so when restarted all configurations will be lost.

**Comment by fifafu** [comment]
Ah that's good to know, for that issue I should be able to add a fix!

**Comment by MylesIsCool** [comment]
Hi, wanting to do this, any chance you can give further information on the workaround?

**Comment by Antairez** [comment]
@MylesIsCool I believe the issue should be fixed in the next few updates because it can be fixed by just handling the null string.

**Comment by bdausses-gm** [comment]
Same thing with VirtualBox... I need to set a gesture specific to the VirtualBox Manager GUI, but it doesn't seem to see the Manager GUI as VirtualBox... only the running VMs themselves.

**Comment by narrowtux** [comment]
I'd be very happy if you'd manage to do this. Working on a control strip for Minecraft right now, with all the special F3 buttons, it would be magical!

**Comment by fifafu** [comment]
For Minecraft you should be able to paste this snippet into BTT (the added three finger tap is just an example):

```
[
  {
    "BTTAppBundleIdentifier" : "net.java.openjdk.cmd",
    "BTTAppName" : "Minecraft",
    "BTTAppSpecificSettings" : {

    },
    "BTTTriggers" : [
      {
        "BTTTriggerType" : 104,
        "BTTTriggerTypeDescription" : "3 Finger Tap",
        "BTTTriggerClass" : "BTTTriggerTypeTouchpadAll",
        "BTTPredefinedActionType" : 5,
        "BTTPredefinedActionName" : "Mission Control",
        "BTTEnabled" : 1,
        "BTTOrder" : 0
      }
    ]
  }
]
```

Just CMD+C here and CMD+V in BTT.

**Comment by fifafu** [comment]
Current BTT versions allow you to add the app by selecting it from the list of currently running applications.

**Comment by sillyfrog** [comment]
Has anyone been able to keep this going with Minecraft 1.13? I have just got a MacBook with a TouchBar, and trying to get this going (more thoughts as to what I have done here: https://community.folivora.ai/t/touchbar-getting-it-to-work-with-java-minecraft/2514/2 ). I'm assuming something has changed in Minecraft as there is no longer a proper icon, and the app is now just named ```java```.
