### ISSUE TITLE
Scroll momentum

### ISSUE THREAD

**Issue by AlexKraemer** [fifafu/BetterTouchTool#1291]
#### Description of bug/feature request/question:

Is it possible to modify scroll momentum on normal mice?  I have a Razer Death Adder and scrolling web pages goes from pixel by pixel to straight to the bottom of the page.  There doesn't seem to be a middle ground for scrolling.  If scrolling could work a bit like it does in Windows, where a single mouse wheel "step" would scroll a specified number of pixels/lines/etc it would be great!

#### Device information:

Type of Mac: Mid 2014 15"
macOS version: 10.12.6
BetterTouchTool version: 2.270

**Comment by fifafu** [comment]
Unfortunately this currently can't be done with BTT and I'm afraid it probably won't be added either.
It should be possible to do something like this, but it's out of the scope of BTT (I never use any normal mouse, thus testing it would be very hard for me).

This is something the mouse driver should provide, thus I'd try to contact Racer about the issue.
