### ISSUE TITLE
【feature】Is it better to ignore shortcuts when I'm typing?(But still keep key-sequence enabled when typing)

### ISSUE THREAD

**Issue by ylfzq** [fifafu/BetterTouchTool#1292]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Is it better to ignore shortcuts when I'm typing? The story is:
I added 2 shortcuts to Finder:
![image](https://user-images.githubusercontent.com/8508493/29009450-08a60a96-7b56-11e7-82d8-0d4cd986c247.png)
The first is to go to parent folder using `delete` key and the second is to open the folder/file selected using 'return' key. 

It works and make me feel very convenience. But when I renaming a file, the shortcuts still make effect which makes me feel headache. Is it possible to disable shortcuts when I'm typing or provide an option to do so.

Thank you for your great work.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: Sierra 10.12.6 (16G29)
BetterTouchTool version: 2.270(658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

None

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, that's not possible. Unfortunately BTT can't know when you are typing / when a textfield is active.
