### ISSUE TITLE
Feature Req.: resizing of the clipboard window

### ISSUE THREAD

**Issue by rebdeg** [fifafu/BetterTouchTool#1293]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Please make the clipboard window resizable. For me the default size is too big.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

iMac

#### Device information:

Type of Mac: iMac
macOS version: 10.12.6
BetterTouchTool version: 2.273

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

n/a

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The clipboard window is already resizable, however the minimum width is currently ~680px.
I'll check if I can modify this constraint.

**Comment by rebdeg** [comment]
You are quite right, but it is the width which should be possible to further downsize …
Thanks for the reply, Reinier de Groot

On ma, aug. 7, 2017 at 20:17, Andreas Hegenberg <notifications@github.com> wrote:
The clipboard window is already resizable, however the minimum width is currently ~680px.
I'll check if I can modify this constraint.

**Comment by fifafu** [comment]
The next update will allow a minimum width of 500px!
For now it won't get smaller than that :-)
