### ISSUE TITLE
(feature) Ability to remap the modifier keys

### ISSUE THREAD

**Issue by eugeneseppel** [fifafu/BetterTouchTool#1294]
Please add the ability to remap the modifier keys (Ctrl, Option, Cmd) and add modifier-only shortcuts, like Opt-Shift, Ctrl-Shift

#### Description of bug/feature request/question:
Could you please add the ability to remap the modifier keys? It's needed to work with 3rd party applications (like VirtualBox or iTerm) and to work with PC keyboards. For instance remap Ctrl to Cmd and vise versa as it could be performed in Macos keyboard settings (however Macos keyboard settings are system-wide, and your application has the ability to change shortucts only for selected applications.

Thank you!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook keyboard, PC keyboard

#### Device information:

Type of Mac:
macOS version: Sierra
BetterTouchTool version: latest

**Comment by fifafu** [comment]
Sorry, BTT is not made for remapping keys. You'll have to look into tools like Karabiner to do this. (BTT works at a different level and can't do this)

**Comment by eugeneseppel** [comment]
OK, thanks for feedback!
