### ISSUE TITLE
Feature request: Paste an item per line

### ISSUE THREAD

**Issue by fturcheti** [fifafu/BetterTouchTool#1295]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

In general, when I need to paste multiple items from the Clipboard History I want to paste them in multiple lines – one item per line. So it would be helpful to have a "paste mode" for this situation, as we have "paste with format", "paste as plain text", etc.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Yep, I’ll make that the default with the next version!

**Comment by fifafu** [comment]
This is now the default in v2.280 alpha!
