### ISSUE TITLE
Request: Manual adjustment of size and position of snap areas

### ISSUE THREAD

**Issue by soundofnoise** [fifafu/BetterTouchTool#1297]
#### Description feature request
A possibility to adjust size (width/height) and position (X/Y) of snap areas manually (as is it possible to setup where window will snap to).

**Comment by fifafu** [comment]
You can already do that, see this screenshot:

![image](https://user-images.githubusercontent.com/8820811/29142129-30a4da52-7d51-11e7-8ce1-38e359040ac8.png)

**Comment by soundofnoise** [comment]
@fifafu you misunderstood me. It would be nice to have a possibility to adjust size and position of this blue box:

![20170810_5a3ea](https://user-images.githubusercontent.com/5689375/29164664-83aab824-7dc0-11e7-9713-3378707c1bf2.png)
