### ISSUE TITLE
Request: The ability to enable/disable another shortcut as a predefined Action

### ISSUE THREAD

**Issue by klimermana** [fifafu/BetterTouchTool#1298]
I would like to be able to toggle a shortcut, without having to enable/disable all of BTT (it is not a leap motion gesture), i.e. shortcut B will allow me to enable/disable shortcut A and only shortcut A. (I know there are presets, but I would have to copy everything into a second preset just to turn on/off one shortcut)

**Comment by fifafu** [comment]
You can add a new profile and just add that one shortcut to it. Then use the "Switch to Preset" action which allows you to activate a preset **in addition** to your other presets
