### ISSUE TITLE
Right-side icons for different app shows through

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#130]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
If I create icons at the right side of the touch bar for two apps, and one is wider than the other, then when I switch between the apps, the right edge of the larger one shows behind the smaller icon in the app with the small icon.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by CappyD** [comment]
BTT 1.97

**Comment by fifafu** [comment]
Could you attach a screenshot of that ?(shift+cmd+6 will take a screenshot of the touch bar)

**Comment by CappyD** [comment]
sure... here's the app with the smaller (Siri) icon showing the edge of the larger button behind it. 
![overlap](https://cloud.githubusercontent.com/assets/24412403/21290185/d9d5f6d8-c47e-11e6-9536-b3da19693a1b.jpeg)
and here's the bar with the larger icon:
![overlap2](https://cloud.githubusercontent.com/assets/24412403/21290188/0449dbd2-c47f-11e6-87a5-e41d9e89a2b4.jpeg)

**Comment by CappyD** [comment]
BTW, restarting BTT doesn't change the appearance.

**Comment by fifafu** [comment]
Ah, thanks. Now I understand :-)
I'll look into that!

**Comment by fifafu** [comment]
I think this should be fixed in 1.972
