### ISSUE TITLE
Clipboard window remember size and position

### ISSUE THREAD

**Issue by rebdeg** [fifafu/BetterTouchTool#1300]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The clipboard window does not appear on the last used position and size as it was before BTT was closed. After restart it appears at its default size in the middel of the screen.

#### Device information:

Type of Mac: iMac 5k
macOS version: 10.12.6
BetterTouchTool version: 2.273

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Added in v2.280 alpha!
