### ISSUE TITLE
How to disable BTT clipboard related function?

### ISSUE THREAD

**Issue by OscarGong** [fifafu/BetterTouchTool#1301]
#### Description of bug/feature request/question:
BTT clipboard related feature is conflicted with others Clipboard Management App.

How can I disable the BTT clipboard function?

#### Device information:

Type of Mac: Macbook Pro 2013 15 inch
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If you don't assign it to any shortcut or gesture it is completely disabled.
