### ISSUE TITLE
Feature Request: Show BTT Touch Bar while holding keys

### ISSUE THREAD

**Issue by KimchaC** [fifafu/BetterTouchTool#1302]
#### Description of bug/feature request/question:

Hi, I prefer to show the default touch bar by default, but I would like the ability to temporarily show the BTT touchbar when I hold the fn and control keys.

Just like you can setup macOS to show the expanded touchbar of F-keys while pressing fn, I would like to setup BTT to show its bar while holding fn and control.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 13" TB Macbook pro 2017
macOS version:  10.12.6
BetterTouchTool version: 2.270

**Comment by fifafu** [comment]
If you click on the "Advanced Configuration" button on any configured Touch Bar button or widget in BTT you can choose the required modifiers to make it show up.
If you only configure buttons/widgets with required modifiers it will achieve the behavior you want.

**Comment by KimchaC** [comment]
Wow amazing... you've thought of everything.

Quick tip for someone else who may find this:
Enable "Hide BTTB when nothing to if nothing to show" in the general settings to ensure the BTT toucher is hidden when you let go of the modifier keys.

**Comment by KimchaC** [comment]
Almost forgot: Thanks for making such an awesome software!

**Comment by callodacity** [comment]
@fifafu @KimchaC if I'm not mistaken, this issue can be closed?
