### ISSUE TITLE
version 2.280 is a disaster

### ISSUE THREAD

**Issue by ale82to** [fifafu/BetterTouchTool#1304]
in version 2,280
remapping two finger taps
2 finger double taps
2 fingers tip tap(left or right) wont work anymore
witha  magik trackpad without force touch stuff.

**Comment by ignaciobarrena** [comment]
2f from bottom/top is fixed, but tiptaps doesn't work.

**Comment by tonynguyen1901** [comment]
haha true that 2 fingers tip tap not working anymore

lol that's convenient i just need to come here on Github and there's already someone creating a topic on the bug im experiencing

**Comment by fifafu** [comment]
Should be working again in v2.281 ;-)
