### ISSUE TITLE
Insert / Paste Custom Text not working when inserting text with multiple characters

### ISSUE THREAD

**Issue by vstaponski** [fifafu/BetterTouchTool#1305]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Insert / Paste Custom Text not working when inserting text with multiple repeated characters.  For instance, when using 'Type Custom Text' for the word 'Attendees', it removes a 't' and an 'e', making it Atendes

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard shortcut

#### Device information:

Type of Mac: MacBook Pro 2016
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

are you using it in combination with a modifier key like CMD?
Unfortunately BTT can't "override" that modifier, thus the system sees every press like "cmd+key".

This can cause the behavior you described. I'm looking for a way to prevent this, but have not yet found any.

Best,
Andreas

**Comment by vstaponski** [comment]
The ones I am concerned with are not using the cmd key.  They are typically a phrase that is preceded by a not often used key (semi-colon).  Specifically this:
;meet is transformed to a multi-line phrase including the word 'attendees'.

**Comment by fifafu** [comment]
I think this should be fixed in the most recent versions
