### ISSUE TITLE
GitHubswn

### ISSUE THREAD

**Issue by GitHubswn** [fifafu/BetterTouchTool#1307]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

After the fixed from yesterday's issues NOW the new update affected the following:

TipTap Left (two fingers fix)
TipTap Right (two fingers fix)
Tiptap left (One finger fix)
Tiptap right (One finger fix)
Rotate left
Rotate right
2 Fingers tap
2 fingers double tap 

(2 fingers swipe from right edge)   AND  (2Fingers swipe from left edge)  TRIGGERS  (2fingers swipe down)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TRACKPAD

#### Device information:

Type of Mac: Early 2013
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.280

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should be fixed in v2.281 I just uploaded :-)

**Comment by GitHubswn** [comment]
OK those are fixed EXCEPT 
(2 fingers swipe from right edge) AND (2Fingers swipe from left edge) TRIGGERS (2fingers swipe from top edge)

**Comment by fifafu** [comment]
They seem to work fine here, could you please attach an export of your settings?

**Comment by GitHubswn** [comment]
Can you please instruct me how do I go about doing that

**Comment by fifafu** [comment]
Either by clicking the manage presets button and then using the export function, or even better go to the about tab, then click the "export debug information" button. This will create a folder on your desktop called BetterTouchToolDebug, would be great if you could send the contents to boastr.net@gmail.com.

**Comment by GitHubswn** [comment]
Thank you. I just sent it.
