### ISSUE TITLE
Citrix Viewer not detected as Citrix Reciever app

### ISSUE THREAD

**Issue by gilescope** [fifafu/BetterTouchTool#1308]
'Citrix Viewer' seems to be the window run when 'Citrix Reciever' app is launched. It would be great if we could have an app specific TouchBar for when in citix. As far as I can see at the moment it doesn't work as there isn't a 'Citrix Viewer' app to configure against. I tried renaming a copy of an app to 'Citrix Viewer' just to see if that would work but to no avail. Would be really great to get this working :-)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro with touchbar
macOS version: 10:12:9
BetterTouchTool version: 2.270

**Comment by fifafu** [comment]
With the latest version you should be able to choose it from the list of running apps.
