### ISSUE TITLE
Recognize Java apps

### ISSUE THREAD

**Issue by sc-surfer** [fifafu/BetterTouchTool#1309]
#### Description of bug/feature request/question:

BTT does not recognize Java apps as stand alone programs...thus can not assign app specific actions to them.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

#### Device information:

Type of Mac: 2016 MBP w/Touchbar
macOS version: 10.13b
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Please PLEASE add the ability to recognize Java apps and assign functions to them specifically like we can do for other apps. Right now they do not appear in the app selection sidebar.

Thanks!!

p.s. I would even pay the registration fees AGAIN for this feature!! :-)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by sc-surfer** [comment]
Also...related to this issue.

Issues with Java apps #1061

**Comment by fifafu** [comment]
Unfortunately BTT requires an app to have a bundle identifier, otherwise it can't recognize when it's frontmost. However there are many tools to package jars into app bundles. One example would be jar2app (https://github.com/Jorl17/jar2app )

Do you have an example of an app that doesn't work?

**Comment by sc-surfer** [comment]
The software that I want to use BTT with is a trading platform from E*Trade called E*Trade Pro. It launches via a regular app, but runs entirely in Java...

Will look into the jar2app, however since the launcher app does a number of things in realtime on launch such as updates etc. not sure if it will work.

**Comment by sc-surfer** [comment]
Also...used to at least work if I just left the touchbar setup as a global thing, but now the modifier keys don't seem to get trapped. I have another ticket outlining this.

**Comment by fifafu** [comment]
Ah so this app is already wrapped into a normal macOS app?

I haven't changed the way BTT sends keys since a few years, thus I assume something has changed in the ETrade app, is that possible? Was there a new version?

**Comment by sc-surfer** [comment]
Totally possible...the app self updates the java modules on every launch.

**Comment by fifafu** [comment]
I'm currently experimenting with a "compatibility" mode for shortcut sending that could work for apps that have problems recognizing them, however this would require to be set up per app.
How does the app show up in activity monitor?

**Comment by sc-surfer** [comment]
It is identified by name as a process.

**Comment by fifafu** [comment]
So maybe it would help if I'd allow to add apps by process name. Unfortunately I currently don't have a real app to test this on, the etrade app probably requires an account to be downloaded, is that correct?

**Comment by sc-surfer** [comment]
Yes. You would need an account unfortunately. I'd be happy to help out with testing if there is anything I can do that would be useful.



Here is a screenshot: Promain is the java process I want to control. E-Trade Pro is the launcher app.
![screen shot 2017-08-18 at 1 19 38 pm](https://user-images.githubusercontent.com/24858710/29476267-16fce432-8418-11e7-96fb-309861550256.png)
.

**Comment by fifafu** [comment]
If possible please download and open this debug version https://bettertouchtool.net/releases/btt2.290_debug.zip

Afterwards try to switch a few times between the etrade app and some other app. Then send me the logs that are saved in ~/Library/Application Support/BetterTouchTool/Logs/ to boastr.net@gmail.com

This will give me some idea whether the system provides enough information to identify that app.

**Comment by fifafu** [comment]
I just looked at minecraft and maybe it's the same for all java apps.

Could you check what happens when you paste this snippet into BTT? (Just cmd+c here and cmd+v in BTT)

```
[
  {
    "BTTAppBundleIdentifier" : "net.java.openjdk.cmd",
    "BTTAppName" : "Etrade Pro",
    "BTTAppSpecificSettings" : {

    },
    "BTTTriggers" : [
      {
        "BTTTriggerType" : 104,
        "BTTTriggerTypeDescription" : "3 Finger Tap",
        "BTTTriggerClass" : "BTTTriggerTypeTouchpadAll",
        "BTTPredefinedActionType" : 5,
        "BTTPredefinedActionName" : "Mission Control",
        "BTTEnabled" : 1,
        "BTTOrder" : 0
      }
    ]
  }
]
```

Does BTT then trigger mission control when you perform a three finger tap in Etrade?

**Comment by sc-surfer** [comment]
Sorry... Where do you want me to paste the code??

**Comment by sc-surfer** [comment]
Never mind....figured it out. YES, IT WORKS. Triggers mission control!!!

**Comment by sc-surfer** [comment]
Now...how do I apply this to my touchbar buttons?? :-)

**Comment by fifafu** [comment]
Note that you have the app in BTT you can just add touchbar buttons to it. However I haven't looked into the shortcut problem yet. (You can try to right click the app in BTT and enable the shortcut compatibility mode)

**Comment by sc-surfer** [comment]
Nice!! I just moved all my Touchbar actions over to the new app. Will let you know how it works when I get a chance to try it.

Thanks!!

**Comment by fifafu** [comment]
The latest version now also let's you chose from a list of all running apps, thus it should be possible to select java apps too.
