### ISSUE TITLE
Old school keyboard request: function keys all the time

### ISSUE THREAD

**Issue by yobyot** [fifafu/BetterTouchTool#131]
Could BTT offer the ability to permanently display the 12 function keys on the Touch Bar? On non-TB Macs, there's a setting in preferences to make the physical row TB replaces act as non-shifted (no "fn" key) function keys. With a TB-equipped Mac, you can specify that function keys should be shown on a per-app basis but when that app loses the focus function keys are replaced by whatever the TB is for that app.

I know it's old school, but I am a big Windows user on my Mac -- and Alt-F4 is pure muscle memory.

**Comment by fifafu** [comment]
I'll check if this is possible :-)

**Comment by joel1532** [comment]
I'd love to see this feature as well.

**Comment by fifafu** [comment]
High Sierra offers this feature and should be released very soon. Thus I'm closing here.
