### ISSUE TITLE
BetterTouchTool keys work as if you are in the app behind Launchpad while Launchpad is running

### ISSUE THREAD

**Issue by LordZorgoth** [fifafu/BetterTouchTool#1310]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have rebound ESC to Command-g for Emacs only. As a result of this, when emacs is the active application and I run Launchpad, ESC no longer gets me out of Launchpad, presumably because it's mapped to command-G in Emacs. ESC works normally if any other app was focused when I started Launchpad.

This bug persists even if I specifically set ESC to send ESC to Launchpad while in Emacs, or if I set ESC to send ESC while in Launchpad itself.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately as far as I know there is no way to detect whether launchpad is active or not, thus BTT can't differentiate between it and the previous app (macOS just continues to report emacs as the frontmost app)

In case anybody knows a way to recognize launchpad, please let me know.
