### ISSUE TITLE
Open specific window in specific part of specific space

### ISSUE THREAD

**Issue by andybergon** [fifafu/BetterTouchTool#1311]
I read in the website about features like `Window management` and `Move windows to other spaces via gesture or shortcut`. Is it possible to configure BTT to open specific windows in specific part of specific spaces (desktops)?

I tried [Stay](https://cordlessdog.com/stay/) but I discovered that when at restart time all the windows in different spaces are clashed into a single space it cannot move the windows to the correct space but only move it in the current space.

I use  a very specific layout: 3 screens with 3 spaces each one (9 spaces in total) each one with 1 or 2 specific windows. You can imagine how long it can take to rearrange those.

**Comment by fifafu** [comment]
Unfortunately the macOS Apis for this are very bad (all of them are private and undocumented) and I haven't figured out a way to do something like this. If I ever come across one I'll add it.
