### ISSUE TITLE
Exclude apps from clipboard

### ISSUE THREAD

**Issue by rebdeg** [fifafu/BetterTouchTool#1316]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of feature request:

Current version shows all items copied to the clipboard. I use 1password and don't want the copied passwords from that app appear in my clipboard. Can you please add een exclude certain apps from clipboard option to BTT and perhaps also the options to delete a specific item after a specific amount of time from the clipboard.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

n/a

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can click the BetterTouchTool menubar icon and select "disable clipboard manager for current application", it will remember that decision.

However most password managers should be ignored by default if they mark the copied data correctly. (Unless this was disabled in the clipboard manager settings)

**Comment by maclm** [comment]
I came here to open a feature request for "disable clipboard manager for specific application".
I'm glad to learn it is already implemented !
I would argue it's a bit hard to discover by yourself if you don't use the menubar icon though.
Best regards.
