### ISSUE TITLE
"Disable BTT For Current App" doesn't re-enable global shortcut key

### ISSUE THREAD

**Issue by rcj** [fifafu/BetterTouchTool#1317]
#### Description of bug:

I am using a global shortcut that toggles Caps Lock on/off when pressing/releasing the semicolon key. Under Linux I have a special keymap for this and therefore want to deactivate BTT when VMware is active. For this I selected "Disable BTT For Current App" for VMware. I can see the additional entry under Preferences and BTT is disabled when VMware has focus. Caps Lock isn't triggered and the BTT icon shows that it is inactive.

If I now switch to a different application, the BTT icon becomes active again, however the global shortcut doesn't work anymore until I restarted BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: Macbook Pro
macOS version: Sierra (10.12.6)
BetterTouchTool version: 2.270 (658)

**Comment by andygeorge** [comment]
+1 I'm seeing this behavior as well for my disable rules in iTerm. Same version of macOS, BTT v2.301 (679)

**Comment by fifafu** [comment]
Sorry for not replying earlier :-(

I think this has been fixed in recent versions.

In case it's not yet solved for you please comment again- I'm currently closing some older issues.
