### ISSUE TITLE
Remapping of keypad works only intermittently in 10.12.2

### ISSUE THREAD

**Issue by johnpane** [fifafu/BetterTouchTool#132]
I purchased BetterTouch specifically for the ability to remap keypad ^1 to regular ^1, etc, because I uses those keystroke to move around in Spaces. It has worked great until the past few days. I suspect something may have changed in the MacOS 10.12.2 software release. Now, these keystrokes work occasionally but often do not. I do not see a pattern other than after one success it is likely to fail if I immediately issue another such keystroke.

**What kind of Mac are you using?**
MacBook Pro 15" (late 2016)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
External USB keyboard

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2, 1.9.7

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
I did reboot and this did not affect the problem. Screenshot of configuration attached.

<img width="1010" alt="screen shot 2016-12-19 at 07 24 20" src="https://cloud.githubusercontent.com/assets/14841761/21312981/2119456a-c5bd-11e6-9bff-a8ac1f8ae461.png">

**Comment by johnpane** [comment]
The period of failure is consistently for 5 seconds after the last successful action.

For example, if I type ^2 on the keypad after a period of quiescence, it takes me to Space 2. Then if I repeatedly press ^5 on the keypad nothing will happen for 5 seconds, then it will succeed in taking me to Space 5. If I issue more ^n commands from the Keypad, again, they will not work for 5 seconds.

There are no such issues if I issue these same commands using the row of number keys across the top of the keyboard. I also see no issues when using the keypad for other purposes. 

Together, this evidence seems to help isolate the problem to BTT's remapping and not an issue with the keyboard commands reaching the computer, nor an issue with Spaces accepting the commands.

**Comment by johnpane** [comment]
Adding more information to this report:

When I issue one of the relevant keystrokes, BetterTouchTool reports two events like this in the Console:

default	07:26:54.587652 -0500	BetterTouchTool	trigger down
default	07:26:54.698813 -0500	BetterTouchTool	trigger down

I have noted that even when the remapping fails, these two lines are reported.

**Comment by fifafu** [comment]
Sorry for not replying to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
