### ISSUE TITLE
Gestures Won't Save

### ISSUE THREAD

**Issue by TinkSaysBoo** [fifafu/BetterTouchTool#1329]
My gestures have stopped saving.  Once I close the Better Touch Tool's screen, all gestures are erased.  I have done the following:
1. Checked for updates
2. Uninstalled & Reinstalled
3. Checked System Security

**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sounds like some sort of file permission problem. I'd try to completely delete the ~/Library/Application Support/BetterTouchTool folder and also the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist

**Comment by TinkSaysBoo** [comment]
I was not able to find either folder.  Though I think I might know what part of the issue could be.  I don't have a "global" option under application.  I can not figure out how to add it.

**Comment by fifafu** [comment]
You can open that folder by clicking Go => Go To Folder in Finder, then paste the path. Sounds like your preset somehow got corrupted. Deleting that folder should fix it immediately, however you'll need to re-add your gestures :-(
