### ISSUE TITLE
App specific gestures not working

### ISSUE THREAD

**Issue by RobWoodsArt** [fifafu/BetterTouchTool#133]
#### Bug

I'm trying to get Adobe Illustrator to ignore the vertical and horizontal scrolling of my Magic Mouse.  I've checked the appropriate items in the App Specific dropbox (including window snapping which doesn't work either) and illustrator still scrolls.  I've restarted BTT, I've restarted Illustrator and I've restarted the system - all to no avail.  Any ideas?

**Mac Pro 2013**

**Magic Mouse**

**macOS 10.12.1 BetterTouchTool 1.97**

**Comment by fifafu** [comment]
I think this should not happen in the current versions anymore. If it still does please reopen.
