### ISSUE TITLE
[BUG] Widget scripts keep running in the background when switch to another app

### ISSUE THREAD

**Issue by shimj** [fifafu/BetterTouchTool#1335]
#### Description of bug/feature request/question:

When I switch from an app to another, the widget scripts for the last app keep running periodically in the background. This happens both for widgets in/outside a button group.

In my case, I create a widget in a button group for app "X", and the script returns something from web. The action after pressing this widget button is to open another app "Y". However, the problem occurs after switch: the widget will grab from web repeatedly. Only if I switch back to app "X", reopen that group, and close the group, then the widget script stop repeating.
Another case: when screen saver begins, the widget script also keep running.

I extremely love BTT, this is my first time to report an issues on github.😄

#### Device information:

Type of Mac: Macbook Pro 2017 with touch bar
macOS version: 10.12.6
BetterTouchTool version: 2.291

**Comment by fifafu** [comment]
Thanks for reporting, I just found the typo that's causing this behavior. I'll release another small update asap.
