### ISSUE TITLE
Tap button to run script - change button appearance based on result

### ISSUE THREAD

**Issue by Jimmni** [fifafu/BetterTouchTool#1336]
I apologise for making an "Issue" - I have little doubt this is already possible and I'm just missing the correct way to do it.

I have a small Applescript that toggles my audio output source, returning either "AirPods" or "Computer" once it has done so. I wanted to set up a button on my Touch Bar that, when pressed, will run this scriptn and update its icon based on the result.

If I use "Run Apple Script and show return value" the script gets constantly run, which isn't what I'm after - I want the script to trigger when I press the button.

If I use "Run Apple Script (enter directly as text)" then I don't get the options to change the icon based on the result.

How would I achieve the result I'm after? i.e. Running a script when a button is pressed and updating the button based on the result.

Sorry for the probably stupid question!

**Comment by fifafu** [comment]
Hey,

you can assign the "Run Apple Script (enter directly as text)" as a predefined action, the options still apply to the result of that.
In widget config you'd then just have a initial script that returns the current audio output source. If you set the repeat rate to 0 it won't be repeated.

See this example: (cmd+c here, cmd+v in BTT)

```
{
  "BTTWidgetName" : "Date Update On Press",
  "BTTTriggerType" : 639,
  "BTTTriggerTypeDescription" : "Apple Script Widget",
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : 172,
  "BTTPredefinedActionName" : "Run Apple Script (enter directly as text)",
  "BTTInlineAppleScript" : "return do shell script \"date\"",
  "BTTEnabled" : 1,
  "BTTOrder" : 1,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemPadding" : 0,
    "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
    "BTTTouchBarButtonColor" : "58.650001, 58.650001, 58.650001, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarAppleScriptString" : "return do shell script \"date\"",
    "BTTTouchBarAlternateBackgroundColor" : "109.650002, 109.650002, 109.650002, 255.000000"
  }
}
```

**Comment by Jimmni** [comment]
Amazing, thank you!
