### ISSUE TITLE
Touch Bar does not update when changing between apps

### ISSUE THREAD

**Issue by ZacharyABuck** [fifafu/BetterTouchTool#1337]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Changing between applications does not change touch bar configurations (e.g. an IntelliJ specific touch bar configuration does not go away when switching to Chrome). This worked in 2.290.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.12.6
BetterTouchTool version: 2.291

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

**Comment by fifafu** [comment]
Weird, this seems to work fine here.
Could you go to the "about tab" in BTT and click the export debug info button? This will create a folder BetterTouchToolDebug on your Desktop, if possible please send that folder to boastr.net@gmail.com

**Comment by ZacharyABuck** [comment]
I've sent the export to the email address. Thank you!

**Comment by fifafu** [comment]
thank you! Unfortunately I still can't seem to reproduce it, but I don't have intellij installed. Could you check whether this also happens with other apps?

And did I understand correctly that when you switch to Chrome still the IntelliJ Touch Bar setup is shown?

**Comment by ZacharyABuck** [comment]
Ok--I've created a second configuration, and the behavior is duplicated. Here are the steps for me to reproduce the issue:
* Create a touch bar configuration for an app
* Add one button to the touch bar configuration
* Under app specific, select "Touch Bar Behavior" > "Show BTT Touch Bar, Hide System Control Strip"
* Open the app with the configuration
* Verify the custom button is displayed
* Switch to another app without a custom configuration
* Verify the custom button is still displayed
    * In the previous version of the app (2.290), the custom button would NOT be displayed--instead, the OS default would be displayed.

Note that with two apps with custom configurations, switching between them DOES change the touch bar. Navigating to an app without a configuration after switching does not change the behavior--the custom bar from the last app is still displayed. 

I'll export and send you my configuration at the address provided.

**Comment by ZacharyABuck** [comment]
Uninstalling and reinstalling (using App Cleaner to purge) did not resolve the issue. These are the options I have selected in the Touch Bar configuration:

![image](https://user-images.githubusercontent.com/12478432/29498097-19777cb6-85aa-11e7-9249-e8dbd14e406d.png)

**Comment by fifafu** [comment]
I found the issue! (It's a specific combination of settings that triggers it). I'll release a recovery update in about 30 minutes.

**Comment by ZacharyABuck** [comment]
Wonderful! Thank you so much! I didn't realize how much I had come to rely on this app until I found a bug. 🥇 It makes the Touch Bar 100x more useful!

**Comment by fifafu** [comment]
This should now be fixed in v2.292 (671)

**Comment by ZacharyABuck** [comment]
Issue appears to be resolved! Again, thank you so much!
