### ISSUE TITLE
Lost snap areas with update to 2.291

### ISSUE THREAD

**Issue by roamingbob** [fifafu/BetterTouchTool#1338]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:  MacBook Pro
macOS version: OS X Sierra 10.12.6
BetterTouchTool version: rolled up to 2.291.  I had been up to date on the full releases but can't recall the prior version number.  

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird. You could try to update to v2.292 (a little recovery update I just released). 
In case this doesn't help please go to the about tab in BTT and click the "export debug info" button. This will create a folder called "BetterTouchToolDebug" on your desktop. If possible please send that folder to boastr.net@gmail.com

I'm going to sleep now, thus I won't be able to look into it. However BTT keeps various backups in case something goes wrong. (In ~/Library/Application Support/BetterTouchTool )

**Comment by roamingbob** [comment]
Will do.  I was hesitant to go on to 2.292 since the settings seemed lost.  

I’ll export the debug info from 2.291 and 2.292, and then post them as you request.  

Thanks.  Love the tool.  This is a relatively minor annoyance.  

Bob

**Comment by roamingbob** [comment]
The updating to the v2.292 fixed the issue.  I have the 2.291 Debug info if you want it posted to boastr.net@gmail.com.  Let me know.  

Thanks for the help.

Bob

**Comment by roamingbob** [comment]
For the sake of this thread, posting the news that the update to 2.292 fixed the issue.
