### ISSUE TITLE
No longer shows script return values

### ISSUE THREAD

**Issue by aminsohm** [fifafu/BetterTouchTool#1339]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I had two scripts running, one to return the unread count of the Inbox of the Mail app and one to return the battery percentage on the touchbar. On version 2.27... it worked perfectly but now on 2.292 it's not showing any return values. I recreated the return script value widget several time and it returns the correct value when I run the script in advanced configuration, but it just doesn't show the return value on the toucher button.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MacBook Pro touch bar 13"
macOS version: Sierra
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Was this:
![uvzfgkk](https://user-images.githubusercontent.com/27874086/29498614-bfcca850-85c5-11e7-980c-96f1f27aadec.png)

Now this (I also just changed some colors, but that shouldn't be the issue):
<img width="1085" alt="touch bar shot 2017-08-20 at 4 33 44 pm" src="https://user-images.githubusercontent.com/27874086/29498609-ade2a37e-85c5-11e7-9c36-26438798336d.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mhh in general the apple script widgets seem to work fine here, could you try to just return some value and see whether that's displayed?

E.g. ```return "test"```

**Comment by aminsohm** [comment]
Still nothing

<img width="830" alt="screen shot 2017-08-20 at 6 38 28 pm" src="https://user-images.githubusercontent.com/27874086/29499436-d81d13e8-85d6-11e7-9b3c-f4fa0fa6751e.png">

<img width="1085" alt="touch bar shot 2017-08-20 at 6 38 41 pm" src="https://user-images.githubusercontent.com/27874086/29499437-dc49dd2a-85d6-11e7-956f-4f8da49660b0.png">

**Comment by fifafu** [comment]
Weird, I haven't had any similar reports yet. Maybe try to restart your Mac, possibly the Apple Script execution stuff got confused? (The internal result viewer uses a slightly different way to execute the script, thus it may still work correctly)

**Comment by aminsohm** [comment]
I've restarted the mac a few times to no avail. Is there any way I could go back to the 2.27 version? I just have two blank spaces on my touch bar now :(

And another issue that I don't know if there's any support offered for; I can't use commands such as control+p when I'm using Remote Desktop to use my work PC. Pasting text also only pastes a string of "v". Is there any fix or support for this?

Thanks

**Comment by fifafu** [comment]
Yes you can always downgrade (https://boastr.net/releases ) however I still haven't had similar bug reports yet.

It would be great if you could go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. The content of that folder may help me identify the issue (if possible please send it to boastr.net@gmail.com)

**Comment by fifafu** [comment]
could you check whether this is fixed in v2.294 alpha? (get via "Check for alpha version updates" or here: https://bettertouchtool.net/releases/btt2.294.zip )

**Comment by aminsohm** [comment]
Yeah it was fixed in the new version! Sorry it took so long to get back to you, I just started working at my first job a couple of weeks ago.
