### ISSUE TITLE
Apple remote missing 

### ISSUE THREAD

**Issue by platformc** [fifafu/BetterTouchTool#134]
#### The old Apple remote is missing in the preferences menu 
It seems to have been replaced by "Siri Remote".

Some configuration settings are still present for the old apple remote:
 Preferences --> Basic Settings --> [x] enable apple remote plugin

However since the latest update (1.963 /552) there doesn't seem to be any way to define gestures for it.

#### System
Mac Mini (Late 2014)
Mac OS Sierra
Old apple remote (plastic)

**Comment by fifafu** [comment]
Hey,

It's still available, you need to click the little arrow on the very right of the device selection bar. (There are almost no users left that can use this feature, thus it was hidden there)

Best 
Andreas

**Comment by platformc** [comment]
Hi Andreas,
thanks for the feedback - that fixed it.
BTT is a fantastic tool - you've done a great job.

regards,
Ross

I found it a bit hard to find the setting, so for the benefit of any one else who still uses an old Apple remote here is what I did:

### Step 1

 * Preferences --> Gestures --> Right click anywhere in the device selection bar --> [x] Leap Motion

### Step 2 

 * Left click on the new green triangle that has appeared in the device selection bar
 * enable Apple Remote (legacy support)

![btt](https://cloud.githubusercontent.com/assets/12755383/21340616/e35fb630-c6db-11e6-9c16-239f10ac4571.png)
