### ISSUE TITLE
Three-finger click doesn't work correctly with three-finger drag

### ISSUE THREAD

**Issue by nolani12** [fifafu/BetterTouchTool#1340]
#### Description of bug/feature request/question:

OS X, for some reason, will not let Force Touch trackpads click after performing a three-finger drag. Regular trackpads would respond by releasing the drag when clicked. To override this behavior, I have created a gesture: Three Finger Click -> Mouse Click.

However, this affects the three-finger drag adversely. Often the wrong object is selected (a ~100ms delay occurs between the initial gesture and when dragging begins), and the drag does not work correctly. There also appears to be a ~800ms cooldown period after dragging before drags will be recognized again. (Attempting to drag during this time will simply swipe.)

Would it be possible to include a setting that optimizes the three-finger click for three-finger dragging, if not removing this delay altogether?

This three-finger drag issue didn't exist with a regular trackpad, not sure why Apple hasn't included code to allow a three-finger click after dragging to release the drag. Without being able to do this, the only way to release the drag is to wait for ~600ms, or release *ALL* fingers from the trackpad, then perform a click, all while not going too fast or it won't even click at all.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Force Touch Trackpad (2015)

#### Device information:

Type of Mac: MacBook Pro Retina 2015
macOS version: ElCap (10.11)
BetterTouchTool version: 2.292 (671)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Not a bug and doesn't have any other information.

**Comment by fifafu** [comment]
Sorry, unfortunately BTT is not really compatible with three finger dragging and probably never won't be. This is because with macOS 10.9 or 10.10 Apple changed the behavior of the three finger drag and now some fundamental trackpad parameters change as soon as three finger dragging is enabled. This makes it impossible for BTT to work correctly with three finger drag enabled :-(
