### ISSUE TITLE
Ideal Touch Bar graphic size

### ISSUE THREAD

**Issue by sc-surfer** [fifafu/BetterTouchTool#1341]
to get maximum viewable size in the touchbar, what is the ideal icon hight in pixels?

**Comment by 0xenwumme** [comment]
There are several icon sizes. Apple for example uses 68 * 60, 56 * 60, 56 *60, 36 * 60, 16 * 30, 56 * 60, 18 * 60 ... The list is long.

Source of this information is the *.car file for the icons. There's a list of them available [here](https://developer.apple.com/macos/human-interface-guidelines/touch-bar/touch-bar-icons-and-images/), where you can also find recommendations for designing Touch Bar icons.

**Comment by sc-surfer** [comment]
Thanks!!

Monte

**Comment by callodacity** [comment]
@sc-surfer We can probably close this issue now, right?

**Comment by sc-surfer** [comment]
YEP!!
