### ISSUE TITLE
Touch Bar: Apple Script Widget Buttons ignore Extra Padding

### ISSUE THREAD

**Issue by Xyth** [fifafu/BetterTouchTool#1342]
Doesn't matter what Extra Padding I set for this button, it doesn't apply:

![screenshot_2017-08-21 22 29 42](https://user-images.githubusercontent.com/6845555/29515691-84ab4ee6-86c1-11e7-8742-31d379d5263e.jpg)

Same happens to any other Apple Script Widget Buttons I try to make. This problem seems to have arisen in either 2.290 or the version before.

#### Device information:

Type of Mac: 2016 15" MacBook Pro
macOS version: 10.12.6
BetterTouchTool version: 2.292

**Comment by RandomGuy2911** [comment]
Yeah, I think this is a bug with the 2.29x versions of the app. I dropped to 2.266 and the padding with Applescript widgets were just fine. I hope they fix this issue quickly.

**Comment by callodacity** [comment]
@Xyth I believe this should be fixed in 2.296, see fifafu/BetterTouchTool/issues/1394#issuecomment-325561359

**Comment by Xyth** [comment]
I can confirm this has been fixed. Thanks!
