### ISSUE TITLE
touch bar blinks when modifier keys are depressed or released

### ISSUE THREAD

**Issue by johnpane** [fifafu/BetterTouchTool#135]
#### Description of your bug/question/feature request...:

When BetterTouchTool is running, each time a modifier key is depressed or released the touchbar dims and then returns to normal brightness. The contents of the touch bar do not change; just the brightness of the display. I am not actually using any of BTT's touch bar features, but the problem occurs if "Enable Touch Bar Support" is enabled in the "General Touch Bar Settings". I disabled this and the problem went away . I first noticed the problem today after installing 1.97.

**What kind of Mac are you using?**
MacBook Pro 15" (late 2016)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
built-in keyboard

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2, 1.97

**Comment by fifafu** [comment]
Thanks for reporting! Should be fixed in 1.971
