### ISSUE TITLE
Windows no longer snap after updating to version 2.292

### ISSUE THREAD

**Issue by verdi1987** [fifafu/BetterTouchTool#1350]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

After updating from version 2.290 to 2.292, application windows no longer snap.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad, mouse

#### Device information:

Type of Mac: iMac Late 2015 (iMac17,1)
macOS version: macOS 10.12.6 (16G29)
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Snap areas are still present in edit mode. However, nothing happens when attempting to snap a window. There is no outline of the snap area. Reverting to version 2.290 restores the snap area functionality.

Possibly related to [issue 1338](https://github.com/fifafu/BetterTouchTool/issues/1338).

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you please send me an export of your current preset? (Click the manage presets button, then click export)

Issue #1338 seems to be resolved with version 2.292

**Comment by verdi1987** [comment]
Attached.

**Comment by fifafu** [comment]
Sorry Unfortunately github only allows uploads via the web interface. If possible please send it to boastr.net@gmail.com or attach it via the website 

Thank you!

**Comment by tnaseem** [comment]
I'm having the exact same issue.Snap areas are all there in the edit mode, but they don't show up when in use, nor do the windows snap. Restarting the app doesn't fix it.

Current preset file:
[Default.json.zip](https://github.com/fifafu/BetterTouchTool/files/1240758/Default.json.zip)

**Comment by fifafu** [comment]
could you check whether this is fixed in v2.294 alpha? (get via "Check for alpha version updates" or here: https://bettertouchtool.net/releases/btt2.294.zip )

**Comment by verdi1987** [comment]
Yes, it is fixed in v2.294 alpha. Thank you!

**Comment by tnaseem** [comment]
Brilliant. Works for me too. Nice work :)
