### ISSUE TITLE
Global Setting Disappears

### ISSUE THREAD

**Issue by yjlintw** [fifafu/BetterTouchTool#1352]
#### Description of bug/feature request/question:
Update to version 2.292(671), the global setting disappears

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac: Macbook Pro with Retina Display 15", 2016
macOS version: 10.12.6
BetterTouchTool version: 2.292(671)
<img width="1127" alt="screen shot 2017-08-21 at 7 15 45 pm" src="https://user-images.githubusercontent.com/1399376/29541911-34396d92-86a5-11e7-88f2-e0f0dbb5b98b.png">

**Comment by fifafu** [comment]
Mh that's bad.
If you send me an export of your preset (by clicking manage presets), I can probably repair it for your (apparently it somehow got corrupted). 

Alternatively you can create a new preset.

**Comment by yjlintw** [comment]
Create a new preset did fix the problem. I can still send you an export of my preset if you need it for debug reason.
