### ISSUE TITLE
Touch Bar: Replace App touchbar for all apps with BTT

### ISSUE THREAD

**Issue by vladikoff** [fifafu/BetterTouchTool#1353]
#### Description of bug/feature request/question:

I'm very sorry if this is a duplicate bug. Simple question:

Is it possible to hide all application touch bar buttons and just use my BTT defined buttons? 
I tried searching existing bugs and didn't find enough information on this.
Really appreciate the tool. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MBP
macOS version: 10.12
BetterTouchTool version: 2.281

**Comment by sc-surfer** [comment]
yes,  Create buttons under 'Global' and they will show up everywhere, or...

 Under Touch Bar Behavior, select 'Show BetterTouchTool....Hide system control strip' for individual apps.

Find this option by right clicking on the applications in the left region of the settings window, or from the 'App Specific' gear wheel in lower left of window.

Hope that helps.

**Comment by vladikoff** [comment]
@sc-surfer I think I got it! I had to uncheck "Show macOS control strip" !! Thank you so much!

![](http://v14d.com/i/599c899779612.jpg)

**Comment by sc-surfer** [comment]
You’re welcome!!
