### ISSUE TITLE
3 finger swipe does not work properly anymore with update

### ISSUE THREAD

**Issue by nevinjethmalani** [fifafu/BetterTouchTool#1354]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I use three fingers to swipe between tabs and it is not working properly anymore. It is 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Late 2013)
macOS version: Sierra
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
How do we downgrade to a version before the latest version? is that possible? Do you have that available anywhere?

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Are you using your thumb in the three finger swipe? Maybe try disabling thumb handling in the advanced trackpad settings and see if that helps.

**Comment by nevinjethmalani** [comment]
No, I am not using my thumb. I am just swiping with three fingers. The problem isn't fixed in the latest few releases but it is better than it was before. 

What happens is that when I try to swipe to the left or right, it scrolls a little bit instead of swiping. I have to click somewhere on the page and then swipe again to move tabs. When I am trying to move from different tabs quickly, it can be very frustrating. I have installed an older version of BTT that doesn't have this problem for now. This is happening on both Chrome and Safari.
