### ISSUE TITLE
Activate/Bring to Front Window Under Cursor - Keyboard Shortcuts

### ISSUE THREAD

**Issue by xInstead** [fifafu/BetterTouchTool#1355]
#### Description of bug/feature request/question:

Triggering a keyboard shortcut with the same shortcut through the Predefined Action "Activate/Bring to Front Window Under Cursor" doesn't work properly and only causes the mouse to activate windows under the cursor while being stuck in that process.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse 2

#### Device information:

Type of Mac: iMac Late 2012
macOS version: macOS 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Using non-identical and already app occupied keyboard shortcuts works fine on the other hand.

**Comment by fifafu** [comment]
Sorry I'm not exactly sure what you mean by 

> Triggering a keyboard shortcut with the same shortcut through the Predefined Action "Activate/Bring to Front Window Under Cursor"

Can you post an example?

**Comment by xInstead** [comment]
Simple example:

![Example](https://cldup.com/gavg339V-Z.png)

It works fine and as expected if I use any other keyboard shortcut to execute it, but once they're identical, it doesn't work. Already tried it with different matching shortcuts and the result was always the same.

**Comment by fifafu** [comment]
Ah ok. This is expected behavior but I understand that there are use cases where this might be useful. I'll check if I can add an option to allow this.

**Comment by xInstead** [comment]
Would be great. Thank you.

**Comment by fifafu** [comment]
In the new version you can click on the little gear icon on the left side of the shortcut field and check the option "Prevent recursive triggers"

![image](https://user-images.githubusercontent.com/8820811/30766106-55ac1a9e-9ff3-11e7-8ec8-c6634b791798.png)

**Comment by xInstead** [comment]
Perfect. Thank you.

**Comment by bgwwg** [comment]
It seems that if this option is toggled on, the shortcut can only be used once. Only after the app is switched away and back, the shortcut can be triggered again, but just for once. The triggering should not disable further triggers by the user.
