### ISSUE TITLE
Touchbar: "hide BTT Touch Bar if nothing to show (no action configured)" not working

### ISSUE THREAD

**Issue by snemias** [fifafu/BetterTouchTool#1358]
#### Description of bug/feature request/question:
This is about the customisation of the Touch Bar:

I've only defined actions that show up if I press e.g. option + command. Therefore I've 

SELECTED
- "hide BTT Touch Bar if nothing to show (no action configured)"

and UNSELECTED
- "Show macOS Control STrip
- Show BTT Icon in Control Strip

Since the last update I EITHER see only the customised actions (after pressing e.g. option + command) and nothing if the option (etc.) keys are no longer pressed, OR the customised actions are not showing up after pressing the option (etc.) keys.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MAcbook Pro 13"
macOS version: 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

And yes I restarted BTT, shut down the Mac already fully.

Thanks for helping. I like your product a lot.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Wipeout944** [comment]
...I'm seeing something similar on my 2017 MBP 15" (same OS and BTT version)--my Global shortcuts on the touchbar require the Command modifier and Chrome shortcuts require Command + Option. In both cases the shortcuts do not appear when pressing the modifier keys; the normal touchbar remains. Restart of BTT and the MBP did not resolve.

**Comment by fifafu** [comment]
Thanks for reporting, this seems to be a bug. I'll release a fix soon. For now you can downgrade to a previous version via https://boastr.net/releases

E.g. https://bettertouchtool.net/releases/btt2.273.zip should work fine.

**Comment by snemias** [comment]
downgraded for now. Thanx for speedy support.

**Comment by fifafu** [comment]
I think this might be fixed in the 2.293 alpha I just uploaded (get via "check for alpha version updates")
