### ISSUE TITLE
Key sequence to paste custom text not working on 10.12.2 (16C67)

### ISSUE THREAD

**Issue by christoph-bennett** [fifafu/BetterTouchTool#136]
#### Description of your bug/question/feature request...:

I have been using BTT as a sort of mini TextExpander and it has been working great until I upgraded to macOS 10.12.2 (16C67).

I am using a **13" MacBook Pro, late 2016 with TouchBar**. I am using the internal keyboard.
The version of BTT is **1.97 (561)**

<img width="1014" alt="screen shot 2016-12-20 at 11 46 05" src="https://cloud.githubusercontent.com/assets/15220677/21347677/f07d700a-c6a9-11e6-8635-f92719c76009.png">

**Comment by fifafu** [comment]
Weird, that still seems to work fine here. Have you already tried if restarting your system fixes this?

Does anything happen instead?

**Comment by christoph-bennett** [comment]
I am very sorry. I thought the restart after updating macOS would be sufficient. I had restarted BTT several times though. Classic user error.

Thanks again.

**Comment by fifafu** [comment]
No problem! Please let me know if this happens again!
