### ISSUE TITLE
three finger grab broken in some audio plugins on latest update 

### ISSUE THREAD

**Issue by Sebastian-blu** [fifafu/BetterTouchTool#1360]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
my three finger grab is not fully releasing when using sound toys audio plugins within bitwig DAW after the latest update. if I grab a knob and move it then go to grab another knob and adjust both knobs are then adjusted when only the second should be. it seems to just be the soundtoys manufacturer that is affected, and I am using it as a vst 2  but it works fine when I quit BTT. I don't have any trackpad assignments within BTT and this issue is knew as of the latest btt  update

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

trackpad

#### Device information:

Type of Mac:2016 mbp w tb
macOS version: 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
could you check whether this is fixed in v2.294 alpha? (get via "Check for alpha version updates" or here: https://bettertouchtool.net/releases/btt2.294.zip )

**Comment by Sebastian-blu** [comment]
Absolutely!! I'll check when I get home thanks for all your hard work, btt is the best 😎

Barry

**Comment by Sebastian-blu** [comment]
Awesome! Looks like it's all fixed.

Should I make a new note if it comes up again or just replay here?

If you ever need any use cases for promo of btt I use it with Sibelius music notation software to give me easy access to notation. Let me know if that could be useful. 

Cheers thanks. 



Barry

**Comment by Sebastian-blu** [comment]
I can’t get it to connect to my magic mouse 2, I just got it so I don’t know if this is a new bug but I didn’t see it as a problem on GIT

**Comment by Sebastian-blu** [comment]
Actually Magic Mouse 2 was recognized by the live viewer after assigning I assigned a gesture. But I am not seeing correct battery read out and changing mouse speed is not doing anything. Also I can't seem to figure how to two finger tap to drag? Ok that's all for now thanks

Barry

**Comment by fifafu** [comment]
If I remember correctly I have disable the battery readout for Magic Mouse 2 due to performance issues. Changing mouse speed is currently unsupported on macOS 10.11, you can only change it in System Preferences :-(


BTT doesn't have two finger dragging, but you can use double-tap to drag if you add a "Single Finger Tap (left)" gesture and assign the leftclick action.

**Comment by Sebastian-blu** [comment]
Ok thanks a bunch

Barry

**Comment by Sebastian-blu** [comment]
hey its back to its old tricks here. same issue as before on newest update 2.305 mouse grab is doing what it did on this thread in the first place
