### ISSUE TITLE
Application or window specific window snapping

### ISSUE THREAD

**Issue by paulmoons** [fifafu/BetterTouchTool#1361]
#### Description of bug/feature request/question:

Feature Request -- Application or window specific window snapping settings. It would be nice if I can set specific window sizes/locations for certain apps, for example, I would always like Thunderbird to snap to the right at 1/3 screen space and would like Calendar to always snap to 2/3 on the right (both with some edge space).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All devices/Windows Snapping

#### Device information:

N/A

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Just an idea. :)

**Comment by fifafu** [comment]
Currently you can achieve this using custom snap areas (they can be defined per app).

**Comment by paulmoons** [comment]
Well that's me looking stupid lol. I'll have another look.

**Comment by paulmoons** [comment]
Still feel stupid but thanks for the heads-up. I have taken a look and have implemented it with some changes to my original workflow idea. Thanks again and sorry for wasting your time. :(
