### ISSUE TITLE
Remove Modifier Doesn't Remove Button

### ISSUE THREAD

**Issue by krich11** [fifafu/BetterTouchTool#1362]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I created a couple of buttons to only show up in a particular application and only when a modifier key was pressed (option).  After testing it out, I decided that it would be better if the buttons showed up in that particular application, but without modifier keys.  I changed both of the buttons in Advanced Configuration, unchecked the modifier key (option) and clicked save.

Now, the buttons show up in the application both with and without the modifier key pressed.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac:  MacBook Pro 15 (2016)
macOS version: 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Restarting BTT does not clear up the issue.  I did not restart my system yet because I assume you would want to know about this bug.  Considering everything this wonderful application does without requiring a restart, I figure it is not reasonable to require a restart to change modifier keys.  At some point in the next day or two I will restart and report back if this issue doesn't clear up.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is the expected behavior, you wouldn't want buttons to hide whenever you press a modifier key.

Or did I not understand the issue?

**Comment by snemias** [comment]
I've the impression this ticket and the following one 
https://github.com/fifafu/BetterTouchTool/issues/1358
refer to the same problem.

**Comment by krich11** [comment]
I found a solution and I believe it is my misunderstanding of how BTT decides when to hide buttons.  Originally, I had removed the modifiers from all of my buttons.  I expected that I would see those buttons hide when pressing a modifier key similar to what you see with globally scoped buttons.  As I reported, this was not the case.  The buttons with no modifier keys remained on the touch bar even when a modifier key was pressed.  So, in further testing, I found that this behavior was caused by not having any buttons with modifier keys defined at the application scope.  Once I defined a button with a modifier key at the application scope, it started working as I expected.  The non-modifier buttons disappeared and the modifier buttons appeared.  This seems like it's performing as designed. Maybe a setting in the future to make it behave by hiding non-modifier buttons when modifier keys are pressed.

In any case, I'm okay for now.  This can be closed or marked as a future feature as you decide.

**Comment by fifafu** [comment]
Ah that may actually be a bug. I'll look into this :-)

**Comment by fifafu** [comment]
I think this might be fixed in the 2.293 alpha I just uploaded (get via "check for alpha version updates")

**Comment by Wipeout944** [comment]
Doesn't appear to have fixed my problem, but mine may not be identical to OP's. On alpha, when I press the modifiers (globally or for Chrome) nothing happens--same behavior as 2.292.

**Comment by fifafu** [comment]
could you check whether this is fixed in v2.294 alpha? (get via "Check for alpha version updates" or here: https://bettertouchtool.net/releases/btt2.294.zip )
