### ISSUE TITLE
Broken TouchBar after update to latest stable

### ISSUE THREAD

**Issue by SanduLu** [fifafu/BetterTouchTool#1365]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
"Run Apple Script and Show Return Value" does not work anymore for TouchBar after update to 2.292. I can still edit the options and "Run Script" shows the expected result. But the TouchBar does not update anymore.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you post some of the scripts you are using? The script widget seems to work fine here and I haven't had many issue reports yet, thus I believe it must be some specific combination of things that lead to this.

If possible go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. That folder would help me a lot for identifying the issue. (Please send it to boastr.net@gmail.com)

For now you can of course also downgrade to the previous release (https://boastr.net/releases)

**Comment by SanduLu** [comment]
Here are some screenshots with the scripts & their result, and the overall setup.

Widget should show alternate icon, but doesn't:
<img width="1013" alt="screen shot 2017-08-23 at 16 35 45" src="https://user-images.githubusercontent.com/30205068/29637132-2defe402-8821-11e7-805e-e282c517abe9.png">

Widget should show window title, but shows widget name:
<img width="1015" alt="screen shot 2017-08-23 at 16 37 14" src="https://user-images.githubusercontent.com/30205068/29637182-5e2eb6c0-8821-11e7-8f82-2fd30f5e33f3.png">

My TouchBar configuration:
<img width="1011" alt="screen shot 2017-08-23 at 16 37 48" src="https://user-images.githubusercontent.com/30205068/29637252-908fb448-8821-11e7-8d69-b736758f383b.png">

General TouchBar Settings:
<img width="871" alt="screen shot 2017-08-23 at 16 41 01" src="https://user-images.githubusercontent.com/30205068/29637373-ee59e904-8821-11e7-8470-4d13a5b05b87.png">

**Comment by SanduLu** [comment]
I'd assume the issue might be related to
"Touch Bar Apple Script widgets should not refresh anymore while the BTT Touch Bar is not visible"

**Comment by fifafu** [comment]
Thanks for reporting! I think I may have identified the issue. (Do you have app-specific Touch Bar behavior defined for Chrome?)

If you want you can downgrade to https://bettertouchtool.net/releases/btt2.270.zip for now.

**Comment by SanduLu** [comment]
Do you have an ETA for the fix?

**Comment by fifafu** [comment]
I think it should be fixed in the alpha I just uploaded (get via "check for alpha version updates")
