### ISSUE TITLE
1 finger tap top middle not working constantly

### ISSUE THREAD

**Issue by mapan** [fifafu/BetterTouchTool#1367]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
1 finger tap top middle on Macbook pro touchpad not working smoothly like previous versions, have to tap multiple times to trigger.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: Pro
macOS version: 0.12.6
BetterTouchTool version: 2.292(671)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://user-images.githubusercontent.com/2045841/29641974-193ec51a-881b-11e7-8d3f-f0d84707879c.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by universvm** [comment]
I have the same issue and also noticed that there is such a thin part considered top be "top" that makes Tap Top Middle almost unusable on 2016/2017 MBP. I almost have to calculate the centre of the trackpad and hope my finger is not too big.


I am not sure if you can customise these areas, although it would be perfect.

**Comment by fifafu** [comment]
@universvm you can increase the area by changing these options:

![image](https://user-images.githubusercontent.com/8820811/30249395-f0faf180-963b-11e7-9de5-e58a07a65607.png)
