### ISSUE TITLE
Palm Rejection Macbook Pro 2017 - need some help

### ISSUE THREAD

**Issue by koba261** [fifafu/BetterTouchTool#1369]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
completely unable to use my new MBP due to ridiculous trackpad. I have tried using BTT and unfortunately does not help - I have checked thumb/palm rejection to no avail. Any tips would be appreciated - I am on the verge of returning the MBP.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad

#### Device information:

Type of Mac: 2017
macOS version: 10.12.6
BetterTouchTool version: 2.291 (latest)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately BTT's palm rejection can not influence the system gestures / mouse movement.
Honestly, returning the MBP is really the only option, because I don't think Apple will be able to improve the behavior significantly.
