### ISSUE TITLE
BetterTouchTool using significant energy

### ISSUE THREAD

**Issue by lrozema** [fifafu/BetterTouchTool#137]
Whenever I look at the battery pull-down it says that BetterTouchTool is an app using significant energy. When looking at the activity monitor for the past 8 hours its average is 13.42 (next being Slack with 6.66 and then Safari with 2.84). Since I only occasionally press a button on the touchbar I don't think this is correct.

MacBook Pro (13 inch, Late 2016) 3.3Ghz Intel Core i7, 16 Gbyte RAM

Only using the Touch Bar functionality and one keyboard mapping of cmd-` for showing/hiding the touchbar from BTT, most of other stuff even disabled.

Mac OS Sierra 10.12.2. BTT 1.97 (561)

Already did a restart but still see BTT show up with fluctuating Energy impact often higher then Safari while I am just typing this message. The Touch Bar itself is only showing static icons from BTT. When I show the Safari Touch Bar (hide the BTT) then the energy impact seems to go down drastically.

**Comment by fifafu** [comment]
Possibly the same as #128 ?

**Comment by lrozema** [comment]
It sounds similar but I have all all buttons (with icons add and show text unchecked) with scrollable main container. So no right alignment. And I noticed because I was coding in my Terminal with vim and it became so laggy even hang for seconds sometimes. After closing BTT everything was smooth again. So unfortunately no more BTT for now. What I also noticed was that after closing BTT the fn key (that changes the touch bar to showing the Fn keys did not show the Fn keys for a few hours while the rest of the touch bar seemed to work normally.

**Comment by fifafu** [comment]
I think I have identified a few performance issues with the TouchBar implementation. The next update will significantly improve this and should solve the issue. I'll probably upload it later today.

**Comment by PiaKlarus** [comment]
go for it fifafu..app is awesome - but unusable with this bug ;)

**Comment by fifafu** [comment]
1.971 should reduce this by a lot for most users

**Comment by PiaKlarus** [comment]
Oh yeah...updated about an hour ago and it's working absolutely fabulous !!!

**Danke meine Lieber - geile Arbeit!

**Comment by lrozema** [comment]
In the beginning it seemed better but after a while it showed up in the list again. When looking in the activitiy monitor the average energy impact is indeed lower but BTT sometimes still uses a lot of energy while the bar is not doing anything useful. Just now I had to close BTT again because my Safari was sooo slow. Opened two pages which took forever. Then I quite BTT which even freezed Safari for a few seconds (while also the BTT itself was hanging). Once BTT was closed the pages both finished loading instantly. Now my laptop is responsive again. So I am not sure if it is time for celebration yet... Anyway I have 40 days left to test this. 😄 For now I will see if I can live without BTT, also Rocket seems interesting.

**Comment by fifafu** [comment]
In case thw cpu usage is high for some unknown reason, please take a sample using activity monitor and send it to boastr.net@gmail.com (the omnigroup has instructions on how to do that here: https://support.omnigroup.com/sample-osx/ )

**Comment by PiaKlarus** [comment]
I for myself didn't experience strange cpu usage but I got really strange touchbar button behaviours...they moved to strange places so I disabled TouchBar support completely...

BTT average cpu usage is at 0,7%

**Comment by fifafu** [comment]
@PiaKlarus that will be fixed with the next alpha (see #146)
