### ISSUE TITLE
Global TouchBar Buttons not show up anymore outside of apps with custom Touchbar Buttons

### ISSUE THREAD

**Issue by bartrail** [fifafu/BetterTouchTool#1372]
#### Description of bug/feature request/question:
I have some global Touchbar buttons defined that should only appear when pressing `alt` - since the last update to Version 2.293 these global buttons only appear in apps that have custom Touchbar Buttons (in my case, Chrome, PHPStorm, iTerm) - before I could press `alt` anywhere and see my global Touchbar buttons (screenshot, maximize window etc).
When I remove the `alt` modifier - the global Buttons also don't appear anymore.
But when I think about it, it might also be since the last Sierra Update to 10.12.6. I'm not sure about that.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro Touchbar

#### Device information:

Type of Mac: MacBook Pro (15-inch, Late 2016)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
- Please see [screenshots of configuration](http://imgur.com/a/6dWne) and [Debug-Info](https://drive.google.com/open?id=0ByojhSKWu-H5NU1pS0RqOVpJLVU) + including my `touchbar-presets.json`) 
- I have some global Keyboard bindings which are still working
- I have recognized that custom Touchbar Buttons sometimes disappear when inside an app (since I started using your awesome app in dec 2016). But pressing the `alt` modifier for global Touchbar Buttons shows the global ones; releasing `alt` shows the normal app specific buttons back. This _workaround_ still works when I'm in one of my customized apps - but as the title/description says, they do not show up anymore when outside of them (Finder, Desktop, Mail..)

**Comment by fifafu** [comment]
Should be fixed in 2.296!

**Comment by bartrail** [comment]
yes indeed! Great! thank you
