### ISSUE TITLE
Touchbar stopped working with update to 2.293

### ISSUE THREAD

**Issue by RichardTsc** [fifafu/BetterTouchTool#1374]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After updating to 2.293, all my BTT TouchBar functionalities have stopped working. I have restarted BTT and deactivated/activated the presets. All my TouchBar buttons are linked to modifiers and usually they appear by pressing the respective modifier keys. But after the update, no BTT TouchBar button is appearing. 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Is it possible that you forced the BTT Touch Bar hidden by either pressing the BTT Touch Bar icon or using the Toggle Touch Bar action?
Since ~2.290 BTT remembers that more strictly (to avoid a few issues). I think if you toggle the BTT Touch Bar again using the BTT Touchbar icon or the predefined action, it will work correctly again.

**Comment by RichardTsc** [comment]
Indeed - created a temporary keyboard shortcut for calling the BTT Touchbar toggle action and pressed it once. Now it is working again as before. Thanks very much for the rapid solution!!

**Comment by Wipeout944** [comment]
@fifafu aha! This finally solved my issue in #1362. Merely updating to 2.293 didn't, but turning the BTT Touchbar Icon on, pressing it, and turning the icon back off now has my shortcuts that require modifiers appearing.

**Comment by fifafu** [comment]
I should probably add some sort of indicator that shows the BetterTouchTool Touchbar is "disabled".

I'll think about that. Maybe I'll just always show it when modifiers are included and make the current behavior optional.

**Comment by fifafu** [comment]
In v2.294 alpha I changed the behavior so it will always show when modifiers are involved. Closing here.
