### ISSUE TITLE
"Switch to login screen" Bug

### ISSUE THREAD

**Issue by karama8484** [fifafu/BetterTouchTool#1375]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Having a five finger click gesture assigned to "Switch to login screen" causes a bug. Clicking on the user icon causes the screen to black out for one second and go back to the login screen making it impossible to type in password to login. The only solution is to close the computer lid and re-open it. Switching to login screen without using Better Touch Tool gesture does not cause this issue. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: Macbook Pro Late 2012
macOS version: 10.12.6
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Closing and re-opening the lid fixes it. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If possible use the "Lock Screen" action instead. Unfortunately the "Switch to Login Screen" has various problems since macOS 10.12, but I don't think I can fix them :-(
