### ISSUE TITLE
"Bug" / Sudden change: No thumb recognition for 4-finger tap

### ISSUE THREAD

**Issue by AriBerlin** [fifafu/BetterTouchTool#1376]
For unknown reasons, the "4-finger tap" suddenly stopped being recognized, if the thumb was part of the finger combination. This was not the case previously and I am not aware of having performed any system or BTT updates.

The solution for me was to uncheck the "Thumb/Palm handling" filter under Advanced > Trackpad > Palm & Thumb Recognition, as has been pointed out before in Issue #1347.

Still surprising, why the change suddenly came up

**Comment by fifafu** [comment]
Since a few versions the 4 finger taps require that all fingers touch the trackpad more or less at the same time if thumb handling is active. I have increased the allowed time a bit with v2.296, maybe try again with this version.

**Comment by 01msmr** [comment]
As of macOS High Sierra - 10.13.2 [dev] Beta (17C60c) - the four finger tap doesn´t work at all.

Force Klicks don´t get the appropriate feedback.
