### ISSUE TITLE
2 finger wipe down and 2 finger swipe from bottom edge not triggering.

### ISSUE THREAD

**Issue by gregwarrior** [fifafu/BetterTouchTool#1377]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
2 finger wipe down and 2 finger swipe from bottom edge not triggering.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: MacOs 10.12.6 
BetterTouchTool version: 2.292(671)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

2 finger swipe from top edge is still working. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should be fixed in the latest update
