### ISSUE TITLE
Application specific snap areas no longer work after upgrading to 2.292

### ISSUE THREAD

**Issue by mhoofe** [fifafu/BetterTouchTool#1378]
#### Description of bug/feature request/question:

When dragging an application window, no specific snap created for this application shows up. Only snap areas which are not "limited" to any application show up. The snap areas do show up when editing them, so they are not "lost" or anything.

To reproduce:
- Create a snap area and set "Application Name" to some application (e.g. Safari)
- Save the snap area
- Open the application and move it's window around

Expected:
- The snap area for the application shows up
Actual:
- No snap area shows up

As soon as the "Application Name" is removed from the snap area, the snap area shows up again!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Any

#### Device information:

Type of Mac: iMac
macOS version: 10.11.6
BetterTouchTool version: 2.292 + 2.293

**Comment by tigersoul925** [comment]
Same problem. Hackintosh 10.12.6

**Comment by fifafu** [comment]
Thanks for reporting, will be fixed with the next update, probably tomorrow or sunday. (Previous versions are available here: https://boastr.net/releases)

**Comment by fifafu** [comment]
Fixed in v2.296
