### ISSUE TITLE
Deleted snap areas keep returning

### ISSUE THREAD

**Issue by robhuska** [fifafu/BetterTouchTool#138]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have had issues with snap areas returning after deleting them. It doesn't happen right away, maybe after a reboot, and it only happens after I delete the final snap area that is left.

**What kind of Mac are you using?**
Retina iMac 21.5" Late 2015

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
N/A

**Which versions of macOS and BetterTouchTool are you running?**
Yosemite 10.11.6
BTT 1.963 (552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into this!

**Comment by fifafu** [comment]
Hope this has been fixed with the new version (will be released tomorrow), if not, please let me know.
