### ISSUE TITLE
Snap Areas no longer work after update

### ISSUE THREAD

**Issue by Jtgraff22** [fifafu/BetterTouchTool#1380]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Every since the new update came out 2.293 (672), the custom snap areas haven't been working. The other snap areas, including the corners, halves of the screen still work, but not the custom ones.

#### Device information:

Type of Mac: 2016 Macbook Pro Touchbar
macOS version: Sierra 10.12.5
BetterTouchTool version: 2.293 (672)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey, are your custom ones app specific? If so this will be fixed in the next update.

**Comment by Jtgraff22** [comment]
Yes they are, thanks so much

**Comment by fifafu** [comment]
could you check whether this is fixed in v2.294 alpha? (get via "Check for alpha version updates" or here: https://bettertouchtool.net/releases/btt2.294.zip )

**Comment by Jtgraff22** [comment]
Yes, it works great now, thanks so much for the quick fix!
