### ISSUE TITLE
Chrome and Firefox not snapping on OS X Sierra

### ISSUE THREAD

**Issue by andreixk** [fifafu/BetterTouchTool#1381]
#### Description of bug/feature request/question:

The Chrome and Firefox browser windows (NOT the tab) "snaps" to the edge and resizes to  the correct size, but the position (with respect to its top-left corner) is unchanged (see photo before and after snapping)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad, Bluetooth mouse.

#### Device information:

Type of Mac: MacBook Pro (Retina, mid-2015)
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I have exact same set up on OS X El Capitan - works just fine there

<img width="1440" alt="screen shot 2017-08-25 at 23 29 54" src="https://user-images.githubusercontent.com/17452117/29738318-82511020-89ed-11e7-86fc-14d053e492a7.png">
<img width="317" alt="screen shot 2017-08-25 at 23 30 02" src="https://user-images.githubusercontent.com/17452117/29738322-85cc071e-89ed-11e7-80f2-c79071f2cba7.png">

**Comment by fifafu** [comment]
I think restarting your system will fix this issue. In some rare cases the macOS API gets stuck (I haven't seen this in quite a while but the symptoms look like this)

**Comment by andreixk** [comment]
you are right, except it took two restarts for some odd reason.
