### ISSUE TITLE
Creating Touchbar shortcut for speech in Safari

### ISSUE THREAD

**Issue by Roman828** [fifafu/BetterTouchTool#1382]
I use the speech functionality in macOS every single day.  In order to use it, you first highlight a section of text, then you right click and select "Speech" and then another pop up screen comes up to toggle the speech on or off.  So there are multiple steps to turn on and off.  Safari does not have a keyboard shortcut for this.  I can see in the BTT that i can select right click but then there are 2 more operations that I need for the touchbar shortcut.  Any ideas?

**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think you should be able to use the predefined action "Trigger Menubar Menu-Item" to trigger the speech menu item.

You'd enter something like this: Edit;Speech;Start Speaking;

**Comment by Roman828** [comment]
Andreas:

Good evening.  Awesome.  That worked perfectly.  This is a great application and looking forward to discovering more uses.  Also, use Better Snap Tool every day on iMac.


Sincerely,




Rusty Peterson, ChFC, CLU, CRPC(c)


Investment Advisor Representative


[cid:515DA866-567E-408B-8EE6-D313D389031F@InvestorsAdvisoryGroup.local]


N19 W24200 Riverwood Drive, Suite 150

Waukesha, WI 53188-1193

Phone: 262-446-8137

Fax:  262-446-8135

Cell:  262-613-3933

Our Mission Statement:  To guide our clients in making sound wealth
management decisions throughout the stages of their lives so they may
fulfill their passions and achieve their dreams.


Our Spiritual Commitment:  Out of love for our Lord and Savior and in the
service of others, we will help our clients fulfill their purpose, achieve
their greatness, and accomplish their dreams.


Securities offered through

LPL Financial

Member FINRA/SIPC


Investment advice offered through Investors Advisory Group,
a registered investment advisor and separate entity from LPL Financial.
LPL Financial and Investors Advisory Group do not accept orders and/or
instructions regarding your account by e-mail, voice mail, fax or any
alternate method.  Transactional details do not supersede normal trade
confirmations or statements.  E-mail sent through the Internet is not secure
or confidential.  LPL Financial reserves the right to monitor all e-mail.


Any information provided in this e-mail has been prepared from sources
believed to be reliable, but is not guaranteed by LPL Financial or Investors
Advisory Group and is not a complete summary or statement of all available
data necessary for making an investment decision.  Any information provided
is for informational purposes only and does not constitute a recommendation.
LPL Financial, Investors Advisory Group,  or their employees may own
options, rights or warrants to purchase any of the securities mentioned in
e-mail.  This e-mail is intended only for the person or entity to which it
is addressed and may contain confidential and/or privileged material.  Any
review, retransmission, dissemination or other use of, or taking of any
action in reliance upon, this information by persons or entities other than
the intended recipient is prohibited.  If you received this message in
error, please contact the sender immediately and delete the material from
your computer

On Aug 27, 2017, at 11:38 AM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


I think you should be able to use the predefined action "Trigger Menubar Menu-Item" to trigger the speech menu item.

You'd enter something like this: Edit;Speech;Start Speaking;
