### ISSUE TITLE
New "App controls with control strip" setting pop-up message

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#1386]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have always had "touchbar shows app controls" as my keyboard setting because I don't want lose the touchbar space to the control strip. As of this latest update, I now see this pop-up whenever I open the BTT prefs: "Unfortunately the BTT touchbar support can only work if you select 'touchbar shows app controls with control strip' in system prefs->keyboard". Thankfully, my touch bars still work as before. I VERY much do not want to be forced to show the control strip and have it rob real estate from my touch bar. If you don't really intend to force that (as I dearly hope), then please remove this pop-up message. Otherwise, I am very much loving the current BTT!

#### Device information:

Type of Mac: 13" 2016 MBPro 
macOS version: 10.12.6
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Oh you are right, it also seems to work with that setting! This means it only doesn't work if "Expanded Control Strip" or Function keys is selected.

I'll fix the popup.

**Comment by CappyD** [comment]
Thanks Andreas!

**Comment by CappyD** [comment]
Hi Andreas… was that popup fix supposed to be in 2.294? Because I’m still seeing it.




On Aug 27, 2017, at 5:16 PM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

Oh you are right, it also seems to work with that setting! This means it only doesn't work if "Expanded Control Strip" or Function keys is selected.

I'll fix the popup.
