### ISSUE TITLE
Klicking 2x within a second does Drag in some apps

### ISSUE THREAD

**Issue by sboesebeck** [fifafu/BetterTouchTool#1388]
#### Description

in some Apps (like IntelliJ or iTerm2) when clicking two times within less then a second, it seems like BTT executes a drag instead of two separate clicks resulting in Text being marked or Tabs being removed.

This bug was fixed in some of privious versions, but is back now

It does not occur when tapping

#### Affected input device
Magic Trackpad (forcetouch)

#### Device information:

Type of Mac: macbook pro 2017 and iMac 2011
macOS version: 10.12.6
BetterTouchTool version: 2.292 (671)

**Comment by fifafu** [comment]
See #1371 

Should be fixed in 2.296!

**Comment by sboesebeck** [comment]
works! Thanks!
