### ISSUE TITLE
function key does not work as a modifier key

### ISSUE THREAD

**Issue by EricWVGG** [fifafu/BetterTouchTool#1389]
#### Description of bug/feature request/question:

When creating a keyboard shortcut, one can use "Click to record a shortcut" to map actions to ctrl-J, option-J, or command-J, but not function-J.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook built-in keyboard.

#### Device information:

Type of Mac: Macbook Pro 2016 with Touch Bar
macOS version: Sierra
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I would like to map function -I, -J, -K, and -L to up, left, down, right arrow keys. The function modifier key is in just the right place to make this intuitive; the other modifier keys are less accessible and would conflict with more advanced combinations like shift-arrow and control-arrow shortcuts.

**Comment by fifafu** [comment]
sorry unfortunately macOS doesn't support fn shortcuts by default. You can however use the "key sequences" feature in BTT, however they won't block the input.

**Comment by EricWVGG** [comment]
Yup, tried that, was a little wonky.

Odd though, I was prompted to try this by a friend who is doing it successfully with Karabiner Elements (which I formerly used quite heavily before switching to a Touch Bar laptop, where BTT reigns supreme). Well, thank you, at any rate.

**Comment by fifafu** [comment]
Karabiner Element works at a lower level, it is definitely better suited for these kind of things. BetterTouchTool does pretty basic shortcuts using the systems default functionalities
