### ISSUE TITLE
Need Duplicate Button in Touchbar Config

### ISSUE THREAD

**Issue by nantaphop** [fifafu/BetterTouchTool#139]
As a button, it should have a duplicate button feature.

For example, I custom touchbar for my code editor to insert some snippet code which each button do the same except the text on button and the text that paste when I passed that button.

**Comment by fifafu** [comment]
Hey,

you can press cmd+c and cmd+v to duplicate a gesture, does this work for you?

Best,
Andreas

**Comment by nantaphop** [comment]
Oh, I didn’t think about this. Thank , it’s work
