### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TheBiggestD** [fifafu/BetterTouchTool#1390]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

It would be nice if one could exclude specific programs (password programs) from the clipboard manager.

#### Device information:

Type of Mac: MacBook Air (mid 2012)
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.292 (671)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Most password manager should exclude themselves if they follow some common practices. Which one does't work for you?

You can however already disable BTT's clipboard manager for specific apps. Just go to the app, then click the BTT menubar icon and select "Disable Clipboard Manager for current app". BTT will remember that decision.
