### ISSUE TITLE
[bug] Latest update (2.295) breaks layout of custom touch bar buttons.

### ISSUE THREAD

**Issue by callodacity** [fifafu/BetterTouchTool#1394]
#### Description of bug

Latest update (2.295) breaks layout of custom touch bar buttons.

#### Device information:

Type of Mac: MacBook Pro 13" 2016
macOS version: 10.12.6
BetterTouchTool version: 2.295

#### Additional information

I have some custom buttons in the global layout for the TouchBar.
When I updated to the newest version, this layout breaks.

This is what it looks like before the update:
<img width="1085" alt="touch bar shot 2017-08-29 at 1 15 48 pm" src="https://user-images.githubusercontent.com/1011648/29802983-3acb94ce-8cbc-11e7-8c86-77beb244889b.png">

After I updated, this is immediately what I saw:

<img width="1085" alt="touch bar shot 2017-08-29 at 1 14 33 pm" src="https://user-images.githubusercontent.com/1011648/29802989-460535f2-8cbc-11e7-9f5a-5998592d1cd3.png">

(with the button pressed, so you can see where it is).
<img width="1085" alt="touch bar shot 2017-08-29 at 1 14 35 pm" src="https://user-images.githubusercontent.com/1011648/29802987-446eb0c4-8cbc-11e7-85d0-6b547fbc2023.png">

If I configure the button on the far right to "stick to left side" it now goes *above* the `esc` button - which it shouldn't do:

<img width="1085" alt="touch bar shot 2017-08-29 at 1 15 35 pm" src="https://user-images.githubusercontent.com/1011648/29802984-3f03c64c-8cbc-11e7-82ec-577859d31f89.png">

When I re-configure it to "stick to the right side" it stays in the correct position, until I switch applications in which case the TouchBar display flickers and the layout breaks (like in the first picture).

[Here's my current presets layout file](https://github.com/fifafu/BetterTouchTool/files/1259017/Default.json.zip).

**Comment by callodacity** [comment]
Downgraded to 2.294 and it's working normally.

**Comment by fifafu** [comment]
The only change that I made was that BTT now respects the padding value that is entered in the advanced widget settings. Do you maybe have a negative value entered there?

**Comment by callodacity** [comment]
Nope, they're both set to 0. I also checked the other widgets in the top level and they don't have negative values either.

![screenshot_2017-08-29 15 47 08_ivv4ri](https://user-images.githubusercontent.com/1011648/29806207-6117ab3a-8cd1-11e7-8b29-6c82264f907f.png)

I just installed the 2.295 update again, and it still doesn't work. 2.294 works fine (FWIW I've restarted and cleared the app cache too).

**Comment by fifafu** [comment]
arg sorry I found a typo that may cause this, I'll check asap

**Comment by fifafu** [comment]
Sorry again, it's fixed now in 2.296!

**Comment by callodacity** [comment]
Verified that it's working again now 👍 

Thank you for the extremely rapid feedback and fix! Very impressive 🎉 👏
