### ISSUE TITLE
Feature Request: Eliminate the left  side BTT esc "X"

### ISSUE THREAD

**Issue by mbjesq** [fifafu/BetterTouchTool#1396]
Some of us 2017 Macbook Pro users need BTT do deal with issues of accidentally hitting touch strip buttons with our left hands while at rest.  (We tend to be non-touch typists.) . Being able to get rid of the ESC button is important for us.  Now, let's also NOT HAVE the "X" to toggle out of BTT there when BTT is enabled.  It's not necessary -- because the BTT button inserted into the touchbar is already there to toggle BTT off.  The "X" provides only a redundant function and replaces a similar problem that we are using BTT to avoid.  Thanks.

**Comment by fifafu** [comment]
It's not possible unless you uncheck "show macos control strip" in the BetterTouchTool general touchbar settings.

I'm currently in mobile but you'll find various issues here that request the same.
