### ISSUE TITLE
[Feature Request] Move space/desktop to next monitor

### ISSUE THREAD

**Issue by talpr** [fifafu/BetterTouchTool#1397]
Feature request: Add action to move the current space to the next/previous monitor

When opening mission control (and expanding the spaces area), it is possible to drag spaces between monitors. However, this doesn't work for the "current" space, and there is no way (in MacOS or BTT) to create a shortcut for this. That means that in order to move the current space to a different monitor, one would have to:

1. Switch to a different space
2. Open mission control, and expand the spaces area
3. Drag the "original" space to the desired monitor

It would be great if there was a way to do this via BTT only using the keyboard.

**Comment by fifafu** [comment]
Hi Taplr,

sorry unfortunately I think this is a macOS limitation. If possible you should report this issue to Apple and hope they will implement it as this would be too much work for me to integrate in BTT.

Best,
Andreas
