### ISSUE TITLE
Hide Global-BTT-Touchbar, if there are app specific default actions

### ISSUE THREAD

**Issue by phirin** [fifafu/BetterTouchTool#1398]
Hi! 

Is it possible to hide the Global-BTT-Touchbar, if there are app specific actions by default? 

I know that it's possible the other way round by choosing each app and click "Show App Default Touch Bar". But I'd like to leave the default apps' Touchbars basically and just be able to turn on the BTT-Global-Touchbar for diverse apps.

**Comment by fifafu** [comment]
Sorry that's not possible as BTT doesn't know whether an app has a custom touch bar and as far as I know there is no way to get that info.
