### ISSUE TITLE
Global keyboard shortcuts stop working randomly

### ISSUE THREAD

**Issue by OktarinTentakel** [fifafu/BetterTouchTool#1399]
#### Description of bug/feature request/question:

Since the update this morning all global keyboard shortcuts stop to work after some minutes of BetterTouchTool running.

Restarting the program fixes this shortly for an undefined amount of time, but the shortcuts disappear randomly shortly afterwards.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MacBook Pro
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.296

**Comment by OktarinTentakel** [comment]
Addition: Switching to Lock-Screen and back fixes this also temporarily.

An example use case (as in my case), would be setting certain Windows shortcuts like CTRL+S to Command+S and alter PageDown and PageUp to ^ARROW_DOWN and ^ARROW_UP

These shortcuts just stop working globally after a few minutes.

**Comment by nickw444** [comment]
Also having this issue with the latest version of BTT.

**Comment by S4TNEW** [comment]
Same here. Have set up some simple windows shortcut replacements (ctrl+c, ctrl+v and so on).

Type of Mac: iMac 2011
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.296

**Comment by fifafu** [comment]
Maybe try updating to the latest alpha version, I haven't been able to reproduce the issue yet, but I made some small changes that may help.

**Comment by OktarinTentakel** [comment]
Trying that right now, i'll give you feedback.

**Comment by OktarinTentakel** [comment]
Alpha seems stable in keeping the bindings.

I'll add to this ticket if the problem reoccurrs later down the line or in the next stable.

Thanks for the help so far.

**Comment by nickw444** [comment]
Upgrading to the latest alpha solved the issue for me shortly after placing my first comment 👍
