### ISSUE TITLE
Touchbar doesn't appear under some circumstances

### ISSUE THREAD

**Issue by pokeylope** [fifafu/BetterTouchTool#14]
MacBook Pro with touchbar, 10.12.1, BTT 1.96 (547)

I'm seeing issues with the custom touchbar when using various combinations of two options. The first option is System Preferences -> Keyboard -> "Touch Bar shows", and the second option is Touch Bar Behavior in the right-click menu for an app in BTT.

### When the first option is set to "App Controls with Control Strip" (the default):

When Touch Bar Behavior is set to show touchbar and control strip, things mostly work fine. The only minor issue is that if you hit the X to hide the BTT touchbar, you then have to hit the BTT icon twice to make it reappear.

If Touch Bar Behavior is set to show touchbar and hide control strip, the BTT touchbar appears as expected until a modifier key (shift/fn/control/option/command) is pressed. When that happens, it switches to showing the control strip in addition to the BTT touchbar.

### When the first option is set to an option other than the default, such as "App Controls":

With Touch Bar Behavior set to show touchbar and control strip, the BTT touchbar for the app doesn't appear at all.

With show touchbar and hide control strip, the BTT touchbar disappears when a modifier key is pressed. It reappears after switching to a different app and switching back.

**Comment by fifafu** [comment]
Hi!
Thanks for reporting. Most of this are API limitations, but I may be able to workaround them in future versions.

Currently I recommend to use the default settings in system preferences.

**Comment by fifafu** [comment]
Should be fixed with the new alpha version.
