### ISSUE TITLE
Keyboard lags over time.

### ISSUE THREAD

**Issue by sod1684** [fifafu/BetterTouchTool#140]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

After letting BTT run for a while, typing gets progressively slower and lags (to the point it is unusable). Restarting BTT resets it. The lag starts to occur after a few minutes. 

It only appears to happen when I am typing at a reasonably fast speed.

I am only using BTT to display icons on the touch bar, and window snapping. 

**What kind of Mac are you using?**

MacBook Pro (15-inch, 2016)
2.9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Keyboard. 

**Which versions of macOS and BetterTouchTool are you running?**

OSX 10.12.2 (16C67) 
BTT 1.97

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

None.

**Comment by sod1684** [comment]
After a day, I finally gave up and disabled BTT. The lag is too much. Using better snap tool for the moment.

**Comment by fifafu** [comment]
Hi Sod,

you should try version 1.971 (or the current stable one 1.93). 1.97 had some performance bugs.

**Comment by sod1684** [comment]
Thanks, just see the update now. I'll update and let you know.

**Comment by sod1684** [comment]
Ok initial tests look great. Lag appears to have vanished. Thanks!
