### ISSUE TITLE
Not possible to input predefined text with a specific touchbar button

### ISSUE THREAD

**Issue by pandix** [fifafu/BetterTouchTool#1400]
Hello everyone,

Maybe someone already succeed to do so, but I can't find a way to add a specific text when I click on a button I created.

For example, I would like to create "mail1" "mail2" and "mail3" buttons that paste my whole mail adress in different input (like login page on websites) or in plain text in word, notepad etc ...
(not related to the copy/paste function on ios, I've just said that to explain my purpose)

Actually I'm using spark 3 software but having recently bought a macbook pro with touchbar, I found your wonderful app.

Is there any possibility to do so ?

Thanks in advance.

Panda

**Comment by sc-surfer** [comment]
YES PLEASE!! I would also like to have buttons enter text strings.

**Comment by fifafu** [comment]
You can use the predefined action "paste / type custom text" ( or similar)

**Comment by sc-surfer** [comment]
Got it! Hadn't realized that. Thanks. 

Maybe can close this ticket now?

**Comment by pandix** [comment]
Yes, thank you, it worked !
