### ISSUE TITLE
Snap areas are no longer are hidden when the checkbox 'Make snap area invisible' is selected

### ISSUE THREAD

**Issue by amanson** [fifafu/BetterTouchTool#1401]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead

---

#### Description of bug/feature request/question:
Snap areas are no longer are hidden when the checkbox 'Make snap area invisible' is selected. They are always displayed no matter what is selected.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac: iMac
macOS version: 10.12.6
BetterTouchTool version: 2.295 (674)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by zachcumming** [comment]
I have experienced the same issue on my Macbook Pro 2016 using an external display. I have snap areas setup on my external display and they show even when the box 'Make snap area invisible' is toggled off and back on.

**Comment by fifafu** [comment]
If possible  try updating to the current alpha version 2.297 (via "check for alpha version updates"), this should be fixed now.
