### ISSUE TITLE
Cannot Disable BTT for the current App

### ISSUE THREAD

**Issue by Vrywinding** [fifafu/BetterTouchTool#1402]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Normally I can disable BTT for the current App

But when I use Microsoft office 2016 such as Word, Powerpoint

I only see the option "Enable BTT for active App"

But BTT does work for the current App

It causes lots of troubles to  Microsoft office apps

so I have no choices to disable BTT

Really want this feature back.

#### Device information:

Type of Mac: MBP 2015
macOS version: 10.11.6
BetterTouchTool version: 2.296(675)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

thanks for reporting. I'll release a little fix later today!

**Comment by fifafu** [comment]
If possible  try updating to the current alpha version 2.297 (via "check for alpha version updates"), this should be fixed now.

**Comment by Vrywinding** [comment]
I've updated to the new version

and will try to see the compatibility with MS Office 

Thanks for your helps!
