### ISSUE TITLE
A possibility to add buttons to control strip

### ISSUE THREAD

**Issue by Leksat** [fifafu/BetterTouchTool#1403]
Would it be possible to allow adding custom buttons to the control strip? According to https://github.com/fifafu/BetterTouchTool/issues/223#issuecomment-271267493, it should be:
> Unfortunately modifying the control strip is not possible to to api limitations. (Only a button with an icon works)

In my case I only need ⏩ button and another one for toggling iTerm (which previously was bind to F12).
If that would be feasible, I'd leave the default apps bar and used these buttons from a control strip.

**Comment by fifafu** [comment]
Sorry maybe my comment was misleading.
It's not possible to add more buttons to the control strip. I can only add the BTT icon and no other icons in addition to that.
