### ISSUE TITLE
Have to tap twice before BTT Touch Bar menu shows up

### ISSUE THREAD

**Issue by Evilsine** [fifafu/BetterTouchTool#1405]
#### Description of bug/feature request/question:

Sometimes I have to tap the BTT button twice before BTT Touch Bar menu shows up.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 10.12.6 (16G29)

**Comment by fifafu** [comment]
That happens when you close the BetterTouchTool touchbar using the x button. Unfortunately it's an api limitation and I haven't found a workaround for it. Only way is to always close the bar using the BTT icon or predefined action.
