### ISSUE TITLE
4 finger swipe up brings mission control instead of the configured action in BTT

### ISSUE THREAD

**Issue by simonCGN** [fifafu/BetterTouchTool#1406]
#### Description of bug/feature request/question:
Having configured "4 fingers swipe up" to insert a new tab in Safari in BTT and also having no 4 finger gesture configured in macOS system preferences still brings up Mission Control. Mission control is configured to appear with 3 fingers up in system preference. So somehow the configuration in BTT is disregarded/overwritten by macOS.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad on MacBook Pro

#### Device information:

Type of Mac: Macbook Pro 15" 2017
macOS version: 10.12.6
BetterTouchTool version: 2.296

**Comment by fifafu** [comment]
That can happen,  especially when using the thumb in such gestures. Unfortunately the only way to make this work reliable is to also deactivate the three finger swipe in system preferences and reconfigure it in BTT.
