### ISSUE TITLE
Snap to Maximize Doesn't Work on First Try

### ISSUE THREAD

**Issue by vexir** [fifafu/BetterTouchTool#1408]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Windows no longer immediately maximize when dragged to the top of the screen. Instead, the window automatically gets moved down a few pixels and has to be forced up into the top of the screen before the maximize happens.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad, external mice.

#### Device information:

Type of Mac: Macbook Pro 15 in
macOS version: Latest
BetterTouchTool version: 2.293 (672)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have your menubar hidden?

**Comment by fifafu** [comment]
If possible  try updating to the current alpha version 2.297 (via "check for alpha version updates")

**Comment by vexir** [comment]
My menubar is hidden, yes. And issue still occurs on 2.297, though it seems... and I know this will be frustrating to hear... better? But not quite all the way there? The mouse cursor still bounces back down.

**Comment by fifafu** [comment]
The bouncing back is intentional, you can disable it by unchecking the "delay mission control" option in the advanced window snapping preferences.

However when disabling it will more easily trigger the system's mission control while dragging a window to the top.
