### ISSUE TITLE
Add Trigger Predefined Actions for MS Windows type keyboard short cuts

### ISSUE THREAD

**Issue by gmaddry** [fifafu/BetterTouchTool#1409]
I am a new Mac user switching from using MS Windows for a long time. Home and End on windows moves cursor to beginning of line and end of line. It would be useful for us newbies to have these actions part of your Trigger Predefined Actions.

**Comment by fifafu** [comment]
They are both already in the list of predefined actions. Search for "Home" and "End".

**Comment by gmaddry** [comment]
I did and found Home - Beginning of page not beginning of line. I had 
overlooked the search function but had found those keys anyway.
I used search and only found Beginning of page. Am I missing something 
else? I don't mean to be wasting your time for something you have 
already done but I can't find what I was asking for.
Regards,
Gray Maddry

------ Original Message ------

**Comment by fifafu** [comment]
Ah sorry, I thought you just wanted the home and end keys. I missed the beginning and end of line part:-)

On macOS you can use cmd+left and right arrow to move the cursor to the beginning or end  of the line.

**Comment by gmaddry** [comment]
Well I didn't do a good job of making myself clear on what I  wanted. I think below better describes what I meant
Home and End will go to start and end of line
ShiftHome and ShiftEnd will select to start and end of line
CtrlHome and CtrlEnd will go to start and end of document
ShiftCtrlHome and ShiftCtrlEnd will select to start and end of document
