### ISSUE TITLE
Sleep the touchbar when using BTT. 

### ISSUE THREAD

**Issue by mcparlandj** [fifafu/BetterTouchTool#1410]
I'm using a new MBP with touch bar. I'm one of those people that is having and issue bumping the esc key all the time. So i bought BTT and am basically using it to remap the control strip and move the esc key. 
The issue i'm having is when i used the OS control strip, i could set the touch bar to goto sleep after a few seconds. I can't seem to do that now that I'm using BTT. 
These laptops don't have the best battery life, so I'd be nice to be able to put the touch bar to sleep like I use to before installing BTT. 
Am I just not seeing the option to do this? Or does it not exist? 
Thanks!

**Comment by fifafu** [comment]
Mhh the Touchbar sleep is handled by the system and BTT should not influence this. Are you sure you have waited long enough? (not touching the trackpad or keyboard)
