### ISSUE TITLE
Mac Licensed version of BTT does not start on startup when check box is checked

### ISSUE THREAD

**Issue by ektoplasm** [fifafu/BetterTouchTool#1411]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Licensed version of BTT does not start on startup when check box is checked

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

2016 13" macbookpro

#### Device information:

Type of Mac: 2016 13" macbookpro
macOS version: 10.12.6
BetterTouchTool version: 2.296

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

this behavior started after I purchased & activated a BTT license

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I fixed some things in the most recent version. This should now be working correctly again.

**Comment by NikolayEntin** [comment]
Could you please refer to a version, where you believe the issue is fixed?
I run 2.310 (also licensed), which is reported as latest available on HighSierra, and BTT doesn't start automatically. Manually - no problem

**Comment by schlachtzeuger** [comment]
Also, I'm running a licensed 2.313  and it does not start on my MBP running OSX 10.12.6 either =(

**Comment by fifafu** [comment]
Make sure to check the "Launch On Startup" option in the BetterTouchTool preferences. If that doesn't fix it, please delete all old references you may have in System Preferences -> Users & Groups -> Login items
