### ISSUE TITLE
Closing preferences window through Dock

### ISSUE THREAD

**Issue by unknown--** [fifafu/BetterTouchTool#1412]
#### Description of bug/feature request/question:

Closing the app icon through the Dock's 'Quit' context item kills the entire process thus disabling all BTT features. For some apps, quitting the dock icon leaves the process going in the background which would make sense for BTT.

#### Device information:

Type of Mac:
macOS version: 10.11.4
BetterTouchTool version: 2.296

**Comment by fifafu** [comment]
Sorry this is only for apps that have two separate processss. BTT is just one app, thus quitting it will quit it entirely.

This won't change.
