### ISSUE TITLE
New release with changing tab shortcut in Safari

### ISSUE THREAD

**Issue by kathychenmx** [fifafu/BetterTouchTool#1413]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I use three fingers swipe left/right to change tabs in Safari but with the new update, it also follows a show desktop which is very annoying.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

trackpad

#### Device information:

Type of Mac:Macbook pro
macOS version: Sierra 10.12.8
BetterTouchTool version: 2.296

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by kathychenmx** [comment]
The gesture works fine when Safari is full screen.

**Comment by fifafu** [comment]
Do you have disabled the show desktop gesture in system preferences -> trackpad? BTT doesn't override them.

**Comment by kathychenmx** [comment]
Hi, I tried this method but this time the three finger gesture is the same as two finger swipe right/left in Safari which goes to the previous page but not previous tab.

Best regards,
Meixu

**Comment by fifafu** [comment]
You may also need to disable the swipe between pages in system preferences and reconfigure it in BTT. Unfortunately BTT has no knowledge about the system gestures and can't block them.

**Comment by kathychenmx** [comment]
Hi, thanks for the info and I'll try that. But before this update everything is fine and I can use both gestures. Three finger swipe for tabs and four fingers for pages in system. I'm just a little bit puzzled.

Best regards,
Meixu

**Comment by fifafu** [comment]
That's weird, in general there hasn't been a change that should influence the behavior.

However there have been changes to thumb recognition. Do you use the thumb as part of your swipes? Maybe try turning off thumb handling in the advanced BetterTouchTool touchpad settings.
