### ISSUE TITLE
[feature request] Increase/decrease iTunes volume

### ISSUE THREAD

**Issue by maclm** [fifafu/BetterTouchTool#1418]
#### Please add increase/decrease iTunes volume functionality

This is the only thing I still use Quicksilver for... and would happily replace it totally with BTT.

<img width="656" alt="ss 2017-08-31 a 11 42 58" src="https://user-images.githubusercontent.com/7873914/29932188-909995a0-8e41-11e7-9ca4-2b5be3e5f915.png">

**Comment by fifafu** [comment]
What exactly do you need?
Have you seen the volume up and volume down predefined actions?

If you really only want to change the volume for iTunes you could use BTT to trigger a little Apple Script like this 

```
tell application "iTunes"
	if the sound volume is greater than 5 then
		set sound volume to (sound volume - 5)
	else
		set sound volume to 0
	end if
end tell
```

**Comment by maclm** [comment]
Sorry for the delay,

just for the record, inspired by your suggestion, I came up with two one-liner AppleScript :

    tell application "iTunes" to set sound volume to (sound volume - 5)

for volume down, and

    tell application "iTunes" to set sound volume to (sound volume + 5)

for volume up.
Best regards.
