### ISSUE TITLE
Keyboard shortcuts with enabling/disabling BTT are causing infinite loops.

### ISSUE THREAD

**Issue by xdumaine** [fifafu/BetterTouchTool#1419]
#### Description of bug/feature request/question:

Keyboard shortcuts with enabling/disabling BTT are causing infinite loops. I have shortcuts that look like this, so that I can press ctrl-c and send both cmd-c and ctrl-c to the app. This used to work quite well. Now, it seems, this is causing an infinite loop of key presses and I have to quit better touch tool to stop it.

![image](https://user-images.githubusercontent.com/833911/29938345-73237ada-8e56-11e7-87de-9f5e3dd20cb6.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: Mac Pro
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This would always have caused an infinite loop as you are triggering ctrl+c in your actions (which BTT just sees as normal key presses, thus triggering the action again and again).

However the next version of BTT will have an option in keyboard shortcut settings to prevent such recursions 

![image](https://user-images.githubusercontent.com/8820811/30248219-ef745922-9623-11e7-957d-472c58b8dafd.png)

**Comment by xdumaine** [comment]
I use the shortcut for about two years without any problems and all of a
sudden it started being recursive so it did definitely didn't always cause
problems

**Comment by fifafu** [comment]
That's very strange as this has definitely been the standard behavior since BTT exists :-) maybe something else was blocking the shortcut from reaching BTT again?

Well BTT 2.300 alpha has the option to disable recursive triggers. Would be great if you could try it.
