### ISSUE TITLE
Side mouse button as modifier

### ISSUE THREAD

**Issue by jvdnguyen** [fifafu/BetterTouchTool#1420]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Is it possible using BetterTouchTool to have a side mouse button act as a modifier? Like if I hold down the side mouse button it acts as if Shift, or Alt, was held down? 

#### Device information:

Type of Mac: MacBook Pro 15" 2015
macOS version: Sierra
BetterTouchTool version: most recent 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think configuring it like this should work:
![image](https://user-images.githubusercontent.com/8820811/30244606-c56a2696-95c1-11e7-9801-0162e7c9a201.png)

Basically add the button twice to BTT, then set one to trigger only on mouse-up and one to trigger on mouse-down (this can be done in the advanced settings when clicking the little gear icon left to the button recognition field).
