### ISSUE TITLE
Making buttons with german umlaut characters (Ä, ä, Ö, ö, Ü, ü, ß)

### ISSUE THREAD

**Issue by Nikolas45** [fifafu/BetterTouchTool#1425]
#### Description of bug/feature request/question:
I wanted to set up BTT for quick access to german umlaut letters (these guys: Ä, ä, Ö, ö, Ü, ü, ß - the last one is a sharp "s") on my US keyboard for Mail. But it does't seem to work. My first approach was to switch the keyboard setting to german and use the on-screen keyboard to enter them. But the behaviour was unexpected:

Name of the button: Ä
Assigned key: Ä
Character actually printed: ä

Name of the button: ä
Assigned key: Ä (although I used ä)
Character actually printed: ä (correct)

Ö, ö, Ü and ü behave similarly.

Name of the button: ß
Assigned key: SS (this is obviously only a substitution for the actual letter)
Character actually printed: ß (correct)

This might be interesting in itself but this whole approach is getting me nowhere because as soon as I switch the keyboard to US again, the assignments change to the characters of the US keyboard.

So I was looking for a way to enter my fancy german letters into the "shortcut" filed while having the US keyboard layout active, but I couldn't find a way:

- Keeping "A" pressed an then selecting the "Ä" doesn't work.
- Copy-and-pasting an "Ä" from somewhere else seems to work at first, but then it automatically gets replaced by an "A".
- Using Unicode-Hex as input device and typing option-00C4 stops at option-0.

I can't think of any way to realise my wanted behaviour. 
Thanks a lot!
-Nikolas

#### Affected input device:
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 13 inch, 2017
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information:
Might be related to [#669](https://github.com/fifafu/BetterTouchTool/issues/669) and/or [#666](https://github.com/fifafu/BetterTouchTool/issues/666)

**Comment by fifafu** [comment]
Hey,

you could use the "Insert / Type / Paste Custom String" predefined action".

I think this should work. If not please comment again.
