### ISSUE TITLE
v2.297 breaks 'Disable BTT for Current App'

### ISSUE THREAD

**Issue by spnkr** [fifafu/BetterTouchTool#1426]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
choosing 'Disable BTT for Current App' when running Sketch on OS X 10.12.5 does not disable BTT for sketch. maybe happens with other apps, haven't tried.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
effects multiple trackpad gestures (built in trackpad)--pinch in/out, three and four finger pinches as well, maybe more.

#### Device information:

Type of Mac:macbook pro late 2013 1tb 16gb i7 2.6ghz
macOS version: 10.12.5
BetterTouchTool version:  2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
i love BTT

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Fixed in the upcoming update. Thanks for reporting!
