### ISSUE TITLE
Is there a way to disable the "chaining" of shortcuts?

### ISSUE THREAD

**Issue by stevenkkim** [fifafu/BetterTouchTool#1428]
#### Description of bug/feature request/question:

Is there a way to disable the "chaining" of shortcuts?

For example, I would like to make 2 shortcuts:
1) Control + Spacebar triggers Return, and
2) When I type the Return key, I want nothing to happen (No Action)

However, when I do these two shortcuts, BTT chains them together, so Control + Spacebar triggers Return, AND Return triggers No Action, so as a result Control + Spacebar triggers No Action, which is not the desired outcome.

Sorry if I'm missing something obvious, but is there a way to disable the chaining of shortcuts so i can get the 2 separate shortcuts that I'm looking for? Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MacBook Pro 13-inch Early 2015
macOS version: 10.12.6
BetterTouchTool version: 2.297

**Comment by fifafu** [comment]
The next version will have an option "Prevent recursive triggers":

![image](https://user-images.githubusercontent.com/8820811/30244592-5a36fc3c-95c1-11e7-9e22-b1932b6529ce.png)

Should be ready tomorrow evening.

**Comment by gmyers-amfam** [comment]
I'm using BTT 2.347 and am having trouble finding this option for my keyboard shortcuts. How do I get to it?

**Comment by fifafu** [comment]
If possible please update to the latest alpha (2.355) because there have been some changes recently.
To get to this screen press the little cog icon.
![image](https://user-images.githubusercontent.com/8820811/36997546-40eb8296-20ba-11e8-801b-9fa42908e8ba.png)
