### ISSUE TITLE
Add "Delay Until Repeat" parameter for key repeats

### ISSUE THREAD

**Issue by jphalip** [fifafu/BetterTouchTool#143]
It's great that one can now control the key repeat rate for keyboard events. However, the repeating sequence gets triggered as soon as the key is pressed, which differs from the usual behavior of key repeats on the Mac. For this, OSX has a "Delay Until Repeat" parameter. It'd be great if the same parameter could be added in BTT.

Basically what this would do is add a delay between the moment the key is pressed and the moment the repeats sequence starts.

**What kind of Mac are you using?**

Macbook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Keyboard

**Which versions of macOS and BetterTouchTool are you running?**

OSX Sierra 10.12.1
BTT 1.963

**Comment by fifafu** [comment]
Yes# good idea! I'll add this soon :-)

**Comment by fifafu** [comment]
Will be available with next alpha update (1.978) later today.

**Comment by hoskope** [comment]
I'd love to be able to set delay between for eg. mouse clicks. If i have additional actions chained together.
