### ISSUE TITLE
BetterTouchTool - No change of touchbar context as you switch/focus on other apps

### ISSUE THREAD

**Issue by sgript** [fifafu/BetterTouchTool#1430]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Basically as I switch to another app my touch bar buttons don't change but remain stuck. I have to reinstall to get it to fix itself, then reload my preferences and make minor adjustments again, such as:
<img width="1127" alt="screenshot_2017-09-03 15 59 23_x7ybqt" src="https://user-images.githubusercontent.com/7774083/30004101-e40e7dfa-90c0-11e7-9b0a-7fdaf796c82c.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 15" Macbook Pro w/ TouchBar 2016
macOS version: MacOS Sierra (10.12.6)
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Workaround which I mentioned is a reinstall, but after a while it goes back to the same issue again, this is my second reinstall.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Are you sure the problem wasn't solved through the update to v2.297? Did you experience the issue with this version?

**Comment by sgript** [comment]
@fifafu I'm currently on 2.297, it seems to have happened ever since I started using this version. Let me know if there's anything else I can provide you with that may help!

**Comment by fifafu** [comment]
Maybe go to the about tab in BetterTouchTool and click the export debug info button. This will create a folder called BetterTouchToolDebug on your desktop, you can send that to boastr.net@gmail.com

**Comment by sgript** [comment]
@fifafu I have sent the email 👍

**Comment by sgript** [comment]
Also I wanted to say I can temporarily get it working again if I just switch the touch bar settings back to default (showing MacOS' default control strip)  then back to the settings I've put in that screenshot (hiding the default control strip). But after a while it breaks again.
