### ISSUE TITLE
Example preset for Custom Media Playback and Volume Controls

### ISSUE THREAD

**Issue by mkhalife** [fifafu/BetterTouchTool#1433]
Here is a config I'd like to share which gives you clean looking media playback buttons that are fixed to the right of the BTT touch bar. I found myself no longer using any of the Apple default Touch Bar functions, but I still wanted the fixed media controls, so I created this. 

Here's what it looks like:

<img width="1085" alt="touch bar shot 2017-09-04 at 12 54 47 am" src="https://user-images.githubusercontent.com/28989127/30012810-af02047e-9110-11e7-94f5-9ff57417dd50.png">

...and here's the config file: [MediaButtons.json.zip](https://github.com/fifafu/BetterTouchTool/files/1273742/MediaButtons.json.zip)

**Comment by fifafu** [comment]
Thank you! I added it to the knowledge base :-)
