### ISSUE TITLE
Bluetooth Headphones (Question)

### ISSUE THREAD

**Issue by brandonr49** [fifafu/BetterTouchTool#1434]
I have bluetooth headphones with play/pause and skip forward/back buttons. Does BTT catch these? Can I use them to trigger actions? I can't seem to find any mention for anything like this in a workflow. 

Type of Mac: Macbook Pro Retina
macOS version: 10.12.6
BetterTouchTool version: 2.297

**Comment by fifafu** [comment]
Hey,

Sorry BetterTouchTool currently can't.
It's on my list of things to look into, but currently only with relatively low priority.

Best 
Andreas

**Comment by brandonr49** [comment]
Sad to hear but I found some free tools that handle it.
Better touch tool is awesome though!

**Comment by fifafu** [comment]
Thanks! I'll look at the code and check how much work it would be to integrate :-)
