### ISSUE TITLE
Crashes when opening preferences

### ISSUE THREAD

**Issue by FMS-Cat** [fifafu/BetterTouchTool#1435]
It becomes to crash when opening preferences. everytime.
The bug occurs from recent version that has an dialog below.

![](https://i.imgur.com/nf0yYLd.png)

Both selecting "Start using BTT & open preferences" in this dialog and clicking "⚙ Preferences" from menu bar causes same issue.
Before crashing, there are a few seconds of freeze.
I still can use BTT as before by not opening preferences window. settings has taken over and working properly but window snapping effect has resetted.

---

Type of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.297

---

[BetterTouchTool_2017-09-04-165421_XNDMBP.crash.txt](https://github.com/fifafu/BetterTouchTool/files/1273993/BetterTouchTool_2017-09-04-165421_XNDMBP.crash.txt)

**Comment by fifafu** [comment]
Mhm the crashlog looks very weird. For some reason BTT doesn't seem to be able to save some changes and ends up trying in an endless loop. Maybe it's a file permission problem. 

You could try  to delete the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist, this will clear the BTT settings but also make sure a valid configuration is re-created.

**Comment by FMS-Cat** [comment]
Yeah, it solves my problem. Thanks!
Good luck to your development :+1:
