### ISSUE TITLE
Tweetbot does flicker when being maximized

### ISSUE THREAD

**Issue by BreiteSeite** [fifafu/BetterTouchTool#1436]
#### Description of bug/feature request/question:
1) Configure keyboard shortcut `Command-Option-Control-ArrowLeft` to `Maximize Windows Left`
2) Open Tweetbot
3) Press `Command-Option-Control-ArrowLeft`
4) Watch how Tweetbot changes window size 4 times until it finally is snapped/maximized onto the left side.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard?

#### Device information:

Type of Mac: MacBook Pro 2016
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Not sure if to report here or to Tweetbot. Thought i try here first, because i read in the latest changelog things being fixed for IntelliJ IDEs.

**Comment by fifafu** [comment]
I don't own Tweetbot, but this may happen if an app can not be resized to fit e.g. the exact half of the screen due to constraints given by the app. In this case BTT has to "try" whether it can snap the window because there is no way for BTT to know the maximum/minimum size of that app in advance.

**Comment by BreiteSeite** [comment]
@fifafu it seems like they create a sort of an invisible window (in which Tweetbot is aligned to the left), because when i maximize to the right, Tweetbots left border is exactly on the center of my screen (and because of the fixed size of the Application Window, i have space to the right. So Maximizing to the right behaves completely nonlogical for the end-user. So should i report this to Tweetbot?

**Comment by fifafu** [comment]
Yes, if the Tweetbot window is not resizable the only option would be to request a resizable window from the Tweetbot develoeprs :-(
