### ISSUE TITLE
BTT does not enable MBP

### ISSUE THREAD

**Issue by pnbr0014** [fifafu/BetterTouchTool#1437]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Since the last update, BTT cannot be enabled. When I click the icon it says "Enable BTT (Currently Disabled)" It cannot change from that state.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Affects everything because the entire program is disabled

#### Device information:

Type of Mac: MacBook Pro 15 inch Mid 2014
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, I haven't had similar reports yet. Do you have a valid license installed?

**Comment by pnbr0014** [comment]
Hey man. Yes I do have a valid license I just found an older version online
I'm gonna try that to verify if it works.

For some reason the little icon at the top just keeps flashing every time I
press a key as well it's almost like it wants to be enabled but something
isn't letting it.

**Comment by pnbr0014** [comment]
ok I installed the older version and I can confirm that it works

**Comment by Vename** [comment]
I have the same issue. The previous version works fine

**Comment by fifafu** [comment]
If possible please go to the about tab in BetterTouchTool and click the export debug info button. This will create a folder called BetterTouchToolDebug on your desktop. Would be great if you could send that to boastr.net@gmail.com referencing this issue.

**Comment by pewallin** [comment]
I have the same issue. Just sent an email with my debug info.

**Comment by fifafu** [comment]
Could you check whether for some reason BTT is disabled globally in the app-specifics?
See this screenshot:

![image](https://user-images.githubusercontent.com/8820811/30054435-648b5f86-922c-11e7-8337-1c86db937627.png)

**Comment by pewallin** [comment]
It was! Pretty sure I didn't set it myself though... Anyway, I enabled it for global and now it works again - thanks!

**Comment by pnbr0014** [comment]
haha yeah same! just disabled it. seems this version came with the option pre set

Best regards,

**Comment by fifafu** [comment]
It didn't come pre set, but the setting was ignored/handled differently in previous versions. Apparently on a few systems that setting was active (either by accident or due to some bug in previous versions).
 I'll unify the menubar disable option and this settings with the next update to get rid of the issue forever ;-).

**Comment by pnbr0014** [comment]
excellent. Thanks for the swift response to the bug too man this has been the single most useful tool on my mac since I bought it. Good job

**Comment by fifafu** [comment]
Fixed in upcoming version.
