### ISSUE TITLE
Sleep / Wake Failure - Accessibility API

### ISSUE THREAD

**Issue by m8xxo** [fifafu/BetterTouchTool#1438]
Hi

Love the app, which I am mainly using to get something useful out of the touchbar on my MBP. 

Sadly, since downloading the app my MBP has crashed every time it sleeps. When I turn back on, I receive the error:

Sleep Wake Failure
0x10004000014
Stackshot reason: Watchdog

I have finally been able to stop the failures, by disabling the Accessibility API. 

Is this a known issue?  Any idea of a resolution?  Or is it possible to disable the Accessibility API pop ups?

MBP 2016 , MacOS Sierra 10.12.6

**Comment by fifafu** [comment]
That's very weird. BTT is just a regular app and should not be able to cause sleep wake failures and the accessibility API should also not play a role here.

Are you really sure this is related?
