### ISSUE TITLE
Two finger tap is slow

### ISSUE THREAD

**Issue by kuglee** [fifafu/BetterTouchTool#1439]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Two finger tap is slow.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Air 13" Early 2015 trackpad

#### Device information:

Type of Mac: MacBook Air 13" Early 2015
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You probably have added a two finger double-tap, don't you? In that case BTT has to wait for the second tap before triggering the normal two finger tap.

**Comment by kuglee** [comment]
Yeah. I totally forgot about that. Thanks and keep up the good work!
