### ISSUE TITLE
Keyboard shortcuts with different key bindings

### ISSUE THREAD

**Issue by klkl0808** [fifafu/BetterTouchTool#144]
I love to define new keyboard shortcuts with BTT. Since I frequently change the input source to other languages, the key bindings of special characters change. I.e. the physical key is linked to a different character.
Now, I would like to leave my keyboard shortcuts unchanged in different input languages. In other words, I would like the shortcuts to be triggered by the physical keys rather than the linked characters. Is this somehow possible in the current version?

My info:
MacBook Pro 2016
macOS Sierra
BTT version 1.963

Konstantin

**Comment by fifafu** [comment]
Unfortunately that's not possible with the current setup BTT uses. This may change in the future, but it's not very likely as it would require big changes ;-(

I'm closing this for now - I'm aware of the issue and if I ever find a good solution to it I may implement it.

**Comment by klkl0808** [comment]
Is it somehow possible to define a shortcut conditional on the current input language? This would be a handy workaround, I guess.
