### ISSUE TITLE
[Feature Request/Bug] Disable BTT when text dialog opens

### ISSUE THREAD

**Issue by tbgulli** [fifafu/BetterTouchTool#1441]
I don't know if that is possible but it would be awesome if BTT commands would be disabled when a text dialog opens. I have over 30 hotkeys for Lightroom and have noticed that when I disable BTT to enter some text, then close the text dialog, BTT goes back to being enable again without me enabling it.

**Comment by fifafu** [comment]
Sorry unfortunately BTT can't recognize such dialogues.

There had been a bug that caused issues with enabling/disabling BTT however that should be fixed in v2.297
