### ISSUE TITLE
BTT Not working

### ISSUE THREAD

**Issue by Roman828** [fifafu/BetterTouchTool#1443]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:  I have a brand new MacBook Pro 15" and have configured several BTT Touchbar shortcuts in both global settings and app specific settings.  This morning when I turned on my computer, the BTT Touchbar icons are not showing up for any program or even the global.  The stock toucher settings are showing up.

I cannot seem to find what happened in the Preferences.

Suggestions

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 15" MacBook Pro
macOS version: 10.12.6
BetterTouchTool version: 2.2292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Roman828** [comment]
I did restart my system and the issue remains that BTT is not working.

**Comment by Roman828** [comment]
I just updated to version 2.297 and then restarted the computer but still not getting any Touchbar items to show up.  When I open BTT it shows the Touchbar items that I have created so they are still there it is just not being used.

**Comment by fifafu** [comment]
Did you maybe hide them? Have you tried pressing the BTT icon in the control strip to show them?

One important thing: In System Preferences => Keyboard, the setting should be "App Controls with Control Strip" or only "App Controls". The other options are not compatible with BTT.

**Comment by Roman828** [comment]
I have tried opening up BTT in the menu bar at the top and they show up but not working.

I check Keyboard preferences and it is set to the App Control with control strip.

Not sure what is going on but it just started today.


Ideas?


Sincerely,




Rusty Peterson, ChFC, CLU, CRPC(c)


Investment Advisor Representative


[cid:515DA866-567E-408B-8EE6-D313D389031F@InvestorsAdvisoryGroup.local]


N19 W24200 Riverwood Drive, Suite 150

Waukesha, WI 53188-1193

Phone: 262-446-8137

Fax:  262-446-8135

Cell:  262-613-3933

Our Mission Statement:  To guide our clients in making sound wealth
management decisions throughout the stages of their lives so they may
fulfill their passions and achieve their dreams.


Our Spiritual Commitment:  Out of love for our Lord and Savior and in the
service of others, we will help our clients fulfill their purpose, achieve
their greatness, and accomplish their dreams.


Securities offered through

LPL Financial

Member FINRA/SIPC


Investment advice offered through Investors Advisory Group,
a registered investment advisor and separate entity from LPL Financial.
LPL Financial and Investors Advisory Group do not accept orders and/or
instructions regarding your account by e-mail, voice mail, fax or any
alternate method.  Transactional details do not supersede normal trade
confirmations or statements.  E-mail sent through the Internet is not secure
or confidential.  LPL Financial reserves the right to monitor all e-mail.


Any information provided in this e-mail has been prepared from sources
believed to be reliable, but is not guaranteed by LPL Financial or Investors
Advisory Group and is not a complete summary or statement of all available
data necessary for making an investment decision.  Any information provided
is for informational purposes only and does not constitute a recommendation.
LPL Financial, Investors Advisory Group,  or their employees may own
options, rights or warrants to purchase any of the securities mentioned in
e-mail.  This e-mail is intended only for the person or entity to which it
is addressed and may contain confidential and/or privileged material.  Any
review, retransmission, dissemination or other use of, or taking of any
action in reliance upon, this information by persons or entities other than
the intended recipient is prohibited.  If you received this message in
error, please contact the sender immediately and delete the material from
your computer

On Sep 6, 2017, at 3:11 PM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you maybe hide them? Have you tried pressing the BTT icon in the control strip to show them?

One important thing: In System Preferences => Keyboard, the setting should be "App Controls with Control Strip" or only "App Controls". The other options are not compatible with BTT.

**Comment by fifafu** [comment]
I meant the BetterTouchTool button on the Touchbar (in the control strip). Or isn't that being shown either?

**Comment by Roman828** [comment]
Andreas:

Good morning.  That was it!!!  I pressed the BTT icon on the Control Strip and they showed up again.

I must have inadvertently pressed that.  Thanks for solving the mystery.

Thanks also for developing this tool.  It is a great timesaver.


Sincerely,




Rusty Peterson, ChFC, CLU, CRPC(c)


Investment Advisor Representative


[cid:515DA866-567E-408B-8EE6-D313D389031F@InvestorsAdvisoryGroup.local]


N19 W24200 Riverwood Drive, Suite 150

Waukesha, WI 53188-1193

Phone: 262-446-8137

Fax:  262-446-8135

Cell:  262-613-3933

Our Mission Statement:  To guide our clients in making sound wealth
management decisions throughout the stages of their lives so they may
fulfill their passions and achieve their dreams.


Our Spiritual Commitment:  Out of love for our Lord and Savior and in the
service of others, we will help our clients fulfill their purpose, achieve
their greatness, and accomplish their dreams.


Securities offered through

LPL Financial

Member FINRA/SIPC


Investment advice offered through Investors Advisory Group,
a registered investment advisor and separate entity from LPL Financial.
LPL Financial and Investors Advisory Group do not accept orders and/or
instructions regarding your account by e-mail, voice mail, fax or any
alternate method.  Transactional details do not supersede normal trade
confirmations or statements.  E-mail sent through the Internet is not secure
or confidential.  LPL Financial reserves the right to monitor all e-mail.


Any information provided in this e-mail has been prepared from sources
believed to be reliable, but is not guaranteed by LPL Financial or Investors
Advisory Group and is not a complete summary or statement of all available
data necessary for making an investment decision.  Any information provided
is for informational purposes only and does not constitute a recommendation.
LPL Financial, Investors Advisory Group,  or their employees may own
options, rights or warrants to purchase any of the securities mentioned in
e-mail.  This e-mail is intended only for the person or entity to which it
is addressed and may contain confidential and/or privileged material.  Any
review, retransmission, dissemination or other use of, or taking of any
action in reliance upon, this information by persons or entities other than
the intended recipient is prohibited.  If you received this message in
error, please contact the sender immediately and delete the material from
your computer

On Sep 6, 2017, at 3:11 PM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you maybe hide them? Have you tried pressing the BTT icon in the control strip to show them?

One important thing: In System Preferences => Keyboard, the setting should be "App Controls with Control Strip" or only "App Controls". The other options are not compatible with BTT.
