### ISSUE TITLE
BTT stops working in Mac Mail using Trackpad

### ISSUE THREAD

**Issue by AZrob** [fifafu/BetterTouchTool#1444]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

#### Description of bug/feature request/question:
I have BTT set to issue a CMD-CTL-A keystroke within Mac Mail so I can archive my emails. This sequence is invoked with a 3-finger click on my Magic Trackpad. For the past several months, I have noticed that this sequence will work for a bit and then stop working, usually after I have executed it a few times archiving a few emails. If I reset BTT, it starts working again. This did not happen when I originally got BTT a couple of years ago.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad

#### Device information:
Type of Mac:
Mac Mini 2012 version
macOS version: 
10.12.2
BetterTouchTool version: 
2.297 (676)
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird. I just archived like 100 mails using your setup, tried it on my Magic Trackpad 1 & 2 and also on my internal trackpad.

It would be great if you could reproduce the issue, then go to the about tab in BTT and click the "export debug info" button. This will create a folder on your Desktop called BetterTouchToolDebug. If you send that to boastr.net@gmail.com I may be able to reproduce the issue.

**Comment by AZrob** [comment]
Will do…I have to say I LOVE your app!

**Comment by AZrob** [comment]
Never mind. What I thought was a problem turned out to be an issue with my Mac.
