### ISSUE TITLE
Show/ Hidde Hidden files in finder

### ISSUE THREAD

**Issue by koro-xx** [fifafu/BetterTouchTool#1447]
#### Description of bug/feature request/question:

The "Show/ Hidde Hidden files in finder" closes all open finder windows and does NOT re-open them. This is very annoying since you usually want to use that action when you opened a folder and decided you want to see the hidden files in it.
I don't know what method BTT is using, but if you do 
```
defaults write com.apple.Finder AppleShowAllFiles true
killall Finder
```
it should reopen the finder windows that were opened.

#### Device information:

Type of Mac: macbook pro
macOS version: 10.12.6
BetterTouchTool version: 2.297

**Comment by fifafu** [comment]
On your macOS version you can use cmd+shift+. to toggle the hidden files.

**Comment by koro-xx** [comment]
Thanks, I'm aware. 
I just thought you might want to change that action since nobody expects "show/hide hidden files" to actually close all finder windows.

**Comment by fifafu** [comment]
The next version of BTT will use the Shift+CMD+. shortcut instead of the old way so this shouldn't be an issue anymore :-)
