### ISSUE TITLE
Poor Palm Recognition on the external Magic Trackpad 2

### ISSUE THREAD

**Issue by dysquard** [fifafu/BetterTouchTool#1448]
#### Description of bug/feature request/question:

Palm recognition is poor in Magic Trackpad 2

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2

#### Device information:

Type of Mac: MacBook Pro 2016 Late , 15 inch 
macOS version:  10.12 
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I'm using  Magic Trackpad 2 under my keyboard, and the palm recognition is TOO poor comparing to the built-in trackpad. 
Most people may place the external trackpad on the left or right side of keyboard, thus I believe Apple didn't take our situation into consideration that it lies under keyboard like the built-in one. It's terrible for us to accidentally touch the trackpad almost during every typing movement.
As I saw in the BTT trackpad setting , there's Thumb/Palm Handling but it's enabled by default and seems to have no effect on the external trackpad ( I also doubt whether it is useful for built-in trackpad because no palm recognition problem occurs on built-in trackpad before I use  BTT).

For temporary solution I made such a lifter, which could lift my both hands up to avoid touching the trackpad while typing. 
![img_4326 copy](https://user-images.githubusercontent.com/16001323/30172394-5321e5e2-9427-11e7-918c-f3ab727b22e6.png)
It works ,but not convenient nor elegant in some way. I still want the external Magic Trackpad to behaves like the built-in one.

Can BTT provide a feature to solve this problem ? Thanks

**Comment by fifafu** [comment]
Unfortunately BTT can not influence the systems palm recognition, it can only influence it for BTT's own gestures (but it will probably never be better than Apple's palm rejection)
