### ISSUE TITLE
When using Mouse Up trigger on external mouse back button, the next middle click does not work

### ISSUE THREAD

**Issue by vjpr** [fifafu/BetterTouchTool#1449]
#### Description of bug/feature request/question:

When using Mouse Up trigger on external mouse back button, the next middle click does not work.

1. In Chrome, configure Mouse 4 to trigger context menu action `History;Back` on `Mouse Up`.
2. Click on a link. Then press back button on mouse, then try middle click something.

The first time, nothing.

The second time, it works again.

#### Other info

- I have middle click bound to three finger press gesture, and the this still works. So its something to do with the `Mouse Up` trigger interfering with the middle click.
- Also, the mouse back and forwards buttons still work fine, its only the middle click.
- Happens in other applications too, not just Chrome.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse

#### Device information:

Type of Mac:
macOS version: Sierra
BetterTouchTool version: 2.297

**Comment by fifafu** [comment]
Thanks for reporting!

This should be fixed in the next version later this weekend. If the next update doesn't fix it for you, please comment again!
