### ISSUE TITLE
Issues with Back/Forward Mouse Buttons in RDP Seesions from Parallels 

### ISSUE THREAD

**Issue by Cyberprog** [fifafu/BetterTouchTool#145]
Hi,

I'm running OS X Sierra, with Parallels 12. Within Parallels I'm running a Windows 10 VM, and then from there I use Devolutions Remote Desktop Manager.

I use BetterTouchTool to make the back/forward buttons work again, which seemed to work ok with OS X El Capitan, but sadly no longer do so.

When I'm within Parallels, I can use the back/forward function fine with BetterTouchTool, but when I'm in a remote desktop session within parallels, I cannot use that functionality.

Hardware wise, I'm using a Mid 2015 MacBook Pro, and I've tried with both my Dell Corded Premium USB Mouse, and my BlueTooth Logitech mouse (whose model number has long since worn off, along with most of the click on one of the buttons...)

Is this a known issue?

Regards,

Alex Threlfall

**Comment by fifafu** [comment]
Unfortunately I think something within Parallels has changed - I'd try to report the issue to them. I'm not sure if it can be fixed in BTT.
