### ISSUE TITLE
BTT Remote app stopped to connect to BTT on iMac.

### ISSUE THREAD

**Issue by BerikYoem** [fifafu/BetterTouchTool#1453]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BTT Remote stopped connecting to BTT on iMac.

The BTT Remote app used work great until couple of days ago. Then it suddenly stopped to connect to my iMac.

It finds my iMac on my home network very easily but it just keep saying 'timeout while connecting'

I use an Airport Extreme as my wifi network device. It seems all the networks work as usual. 

What I have tried are;

1. Removing and re-installing the BTT Remote app and BTT from both iPhone and iMac.

2. Tried to connect by manually putting the IP and Port.

3. Restarting the BTT, iMac and the Airport Extreme.

None of above made any changes. It still shows the 'timeout while connecting' as the attached screen shot.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
BTT Remote app on iPhone.

#### Device information:

Type of Mac: 

macOS version: 
![screen shot 2017-09-08 at 9 30 42 pm](https://user-images.githubusercontent.com/31767222/30211382-2e7c8c52-94e4-11e7-8dc0-2f84eaf1799e.png)

BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![img_7098 png](https://user-images.githubusercontent.com/31767222/30210922-015fbbec-94e2-11e7-992b-5b87820db145.PNG)
![screen shot 2017-09-08 at 9 19 58 pm](https://user-images.githubusercontent.com/31767222/30210928-0ad4ae44-94e2-11e7-8efb-99e3e07d7fb2.png)
![screen shot 2017-09-08 at 9 21 03 pm](https://user-images.githubusercontent.com/31767222/30210931-0cf0d126-94e2-11e7-8adc-930bc0051a32.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is probably some sort of Firewall issue, unfortunately they are always hard to debug. Did you change your firewall settings recently?

**Comment by BerikYoem** [comment]
Thanks for the very quick comment.

I haven't changed anything on the Firewall setting. 

I was able to connect until sometime in the morning then suddenly I couldn't connect to the iMac in the afternoon. Nothing was changed in the meantime by myself.

**Comment by fifafu** [comment]
Have you already tried to restart your Mac? Maybe the network stack somehow got confused.

**Comment by BerikYoem** [comment]
Yes I have tried to restart my iMac, iPhone and Airport Extreme. Nothing has been changed.

**Comment by fifafu** [comment]
Weird :-(
There hasn't been a change on the BetterTouchTool side either but I'm not sure what else could cause this. Did you install any other network related software?

**Comment by BerikYoem** [comment]
Nope... I didn't install any software recently... That's the thing drive me crazy too. Coz it used to work seamlessly then just stopped.... Probably something was changed without me knowing but I have no clue...

**Comment by fifafu** [comment]
Maybe try to delete the app from your phone and reinstall it from the Mac App Store. Or try to use the "manual connect" option and see whether it works when providing the ip and port manually.

**Comment by BerikYoem** [comment]
Yes I did trying manual connection and deleting and re-instaling the apps.... it just didn't work.... 

Anything I can try with the Firewall? I have tried removing the BTT from the Firewall and adding it again.. no luck though....

**Comment by fifafu** [comment]
Only thing may be to turn the Firewall off completely and check whether that changes anything. (Then we would at least know that it's caused by the Firewall)

**Comment by BerikYoem** [comment]
I've just tried turning the Firewall off and tried to connect again. It's still the same... It doesn't connect and just shows 'timeout while connecting' .....

**Comment by BerikYoem** [comment]
Is there anything I can try more? I've got a second hand MacBook Pro with me now and migranted the settings and apps from my iMac into the MBP. The BTT Remote from my iPhone still can detect my iMac and MBP but can't connect to the both of the machines.

**Comment by fifafu** [comment]
Mhh I'm kind of out of ideas. It somehow sounds like your router is the issue, but there hasn't been a change to that, correct?

You could try to competely erase the BetterTouchTool settings by deleting the ~/Library/Application Support/BetterTouchTool folder and the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist

**Comment by ast03** [comment]
Did this last suggestion of deleting the settings work?

**Comment by fifafu** [comment]
I have one more idea: try opening the Keychain App and delete the certificate and key called BetterTouchToolRemote. Maybe something is wrong with that.

**Comment by BerikYoem** [comment]
Right.

The last suggestion of removing the BetterTouchToolRemote certificate and key from my keychain did work. 

I almost gave up after trying removing/re-installing the app and turning on and off the firewall and even tried to reset the router but nothing worked.

However, removing the certs and keys from my keychain worked. Now I can control my iMac and MBP on my palm again :D 

Thank you so much for not forgetting me and coming back to solve the issue. I appreciate your effort.

Cheers


P.S. I thought it would be a bit helpful if I attach some screen shots of the certificate and the keys from my keychain. 

The first screen shots are the old certs and keys in the keychain.

![scrnshot1](https://user-images.githubusercontent.com/31767222/31711085-5bfc6696-b43a-11e7-850c-b8639f8043fb.jpg)

 The second screen shots below are after deleting the certs and keys. 

After deleting the certs and keys, I restarted the BTT app on my Mac and tried to connect from my iPhone. The my Mac showed a dialog to give a permission of access as the first time when I had the BTT app. Now, it woks as I like. Love it!

![scrnshot2](https://user-images.githubusercontent.com/31767222/31711442-7d82cfc0-b43b-11e7-9716-e7477a7344bd.jpg)
