### ISSUE TITLE
Cannot enable BTT

### ISSUE THREAD

**Issue by thegleb** [fifafu/BetterTouchTool#1455]
#### Description of bug/feature request/question:

The icon remains grayed out and occasionally flashes as if BTT tries to enable itself before disabling again. Tried restarting many times, reinstalling, etc. BTT starts disabled and I cannot re-enable it.

#### Device information:

Type of Mac: MacBookPro13,3
macOS version: 10.13 Beta (17A360a)
BetterTouchTool version: v2.297 (676)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Not sure what debugging info is best but I can provide whatever needed.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Please have a look here: #1437
