### ISSUE TITLE
Is it possible to assign two finger tap and override Apple's default right click?

### ISSUE THREAD

**Issue by nikitavoloboev** [fifafu/BetterTouchTool#1457]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I want to assign two finger tap in Safari to do middle click. However when I tried doing it, it works but after it still issues the right click. I would really like to prevent that and just do the middle click.

Thank you for any help.

**Comment by fifafu** [comment]
To achieve this you will need to disable the right-click in System Preferences => Trackpad.
You can then add a two finger tap in BTT's global section and assign it to right-click and then add a two finger tap to Chrome and assign it to middle-click.

**Comment by nikitavoloboev** [comment]
Thank you. This works. 💛

**Comment by nikitavoloboev** [comment]
I am trying to do this in Safari : 

![2017-09-10 at 00 50](https://user-images.githubusercontent.com/6391776/30244616-15855e0c-95c2-11e7-925d-85f56b0e4313.png)

However it does not seem to work. Perhaps I need to set some delay?

**Comment by fifafu** [comment]
Mhm yes, maybe! You can add a delay by using the predefined action "Delay Next Action"

**Comment by nikitavoloboev** [comment]
That worked. 🎊
