### ISSUE TITLE
TouchBar layouts are messed up after starting BTT on 1.971

### ISSUE THREAD

**Issue by AuroraWright** [fifafu/BetterTouchTool#146]
TouchBar layout for an app is messed up after BTT starts (wrong padding/spacing apparently), but fixes itself after I change the padding/spacing of a button (even just selecting a button, clicking on its settings cog and clicking "Save" is enough to fix). This was introduced in 1.971.

**What kind of Mac are you using?**
MacBook Pro 15" 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
Sierra 10.12.2, BTT 1.971

**Comment by fifafu** [comment]
Thanks, will be fixed with next alpha later today!

**Comment by fifafu** [comment]
Would be great if you could check whether 1.972 fixes the issue for you!

**Comment by AuroraWright** [comment]
The issue is partially fixed, now the touchbar layouts change just after switching from other apps.
To reproduce: go to the settings of a button and Save, go to the app with a custom layout. Layout shows properly. Then switch to another app (I see this with apps which don't have a custom layout at least) and back to the app with the custom layout, the layout changed (buttons are larger?).
[Here are](http://imgur.com/a/aKfjm) the touchbar settings, the proper layout and the bugged layout shown after switching back from another app.

**Comment by fifafu** [comment]
@AuroraWright could you check if 1.973 fixes this?

**Comment by AuroraWright** [comment]
Yeah, it's fixed, thanks!

**Comment by AuroraWright** [comment]
0.974 seems to have a similar issue again, only just after BTT starts. To reproduce: open BTT while the focus is on an app with official TouchBar support, switch to an app with custom BTT TouchBar. The "esc" button on the left is partially covered by the first custom button.

**Comment by fifafu** [comment]
@AuroraWright weird, I can't seem to reproduce it anymore. Does it fix itself after a while?

**Comment by AuroraWright** [comment]
Ah, I'm sorry. It seems it only happens when you open BTT while the current app has no touchbar layout at all (official or BTT) and then switch to an app with a custom layout. In my case, it happens reliably if I close BTT, focus on the Discord messaging app window, open BTT (nothing shows on touchbar), then switch to Firefox which has a custom layout.
