### ISSUE TITLE
Bug with touch bar: BTT button cut off

### ISSUE THREAD

**Issue by wescaiju** [fifafu/BetterTouchTool#1460]
#### Description of bug/feature request/question:

After sleeping and waking, a bug sometimes occurs in the touch bar tool (I haven't pinned down a consistent context where the bug arises). The BTT button gets pushed to the left and cut off from the standard button stack location. Note, I modified the default button set by removing Siri. Everything else is default. Please see images in the additional information section.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

1. Normal: https://imgur.com/240DRjB.png
2. Bug: https://imgur.com/AWPXosu.png

**Comment by ads1029** [comment]
Same thing happens here.

**Comment by fifafu** [comment]
Unfortunately this is something I can not influence in BTT as it's system behavior. However I haven't seen this happening on High Sierra yet. (BTT uses various tricks to display it's stuff on the Touch Bar and Apple doesn't really support this unfortunately).
