### ISSUE TITLE
Can't hide BetterTouchTool button on TB when there is no buttons configured.

### ISSUE THREAD

**Issue by JulyIGHOR** [fifafu/BetterTouchTool#1462]
#### Description of bug/feature request/question:

I wish BetterTouchTool button on Touch Bar disappears if current app have no configured buttons/widgets.
Also on not configured apps it useless since I press it and nothing happens. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 13" TB
macOS version: macOS Sierra latest
BetterTouchTool version: latest release

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image_2017-09-10_21-00-55](https://user-images.githubusercontent.com/3390357/30252011-368b9bbc-966b-11e7-93de-bbc199a01da0.png)

**Comment by fifafu** [comment]
This is currently not possible due to API limitations. However you can completely hide the control strip button in the general touchbar settings in BTT.
(you can then use the predefined action "toggle BetterTouchTool Touchbar" to show/hide the BTT Touch Bar)

**Comment by JulyIGHOR** [comment]
Thanks for answer.
