### ISSUE TITLE
Safari crash after open Better Touch Tool

### ISSUE THREAD

**Issue by lui2man2chun** [fifafu/BetterTouchTool#1465]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
My BetterTouchTool is working normal on other app without Safari. In Safari, if i open some tab and change to another tab, I will get a popup window "Safari Web Content quit unexpectedly."  I have tried Disable BTT for all App, but the problem is still here, until I quit the BTT

Process:               com.apple.WebKit.WebContent [1424]
Path:                  /System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent
Identifier:            com.apple.WebKit.WebContent
Version:               12603 (12603.3.8)
Build Info:            WebKit2-7603003008000000~1
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Safari [1342]
User ID:               501

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Just USB Mouse

#### Device information:

Type of Mac: iMac (27-inch, Late 2013)
macOS version: Mac OS X 10.12.6 
BetterTouchTool version: 2.300(678)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I'm very sure this is not caused by BTT. Do you have any system modifications installed that integrate deeply into the system? (E.g. SiMBL plugins)

BTT may trigger some function that in the end causes the crash, but I'm pretty sure some other addon is the real culprit.
