### ISSUE TITLE
Top 2cm of trackpad not recognised by BTT

### ISSUE THREAD

**Issue by havumigi** [fifafu/BetterTouchTool#1469]
#### Description of bug/feature request/question:

On my mid 2012 non-retina Macbook Pro, touches on the top 2cm or so of the trackpad are not recognised by BTT. If I use the bottom ca. 80% of the trackpad, everything works as expected, but if any finger is on the top section, the thee- and five-finger events I have set up in BTT are not recognised.

This is all visible in BTT's live view - sliding a finger down from the top of the trackpad starts to move the cursor straight away, but the touch doesn't show up in the live view until around 2cm down.

Cursor movement, two-finger scrolling and four-finger space switching (controlled by the OS) work fine anywhere on the trackpad.

This has only been a problem for a week or two - I think since installing version 2.297. Downgrading to an earlier version didn't seen to help though.

(I also wrote this as a comment to issue #1417 as my symptoms were similar to what jebediah2 posted there - submitted as a separate issue now that I've understood what the problem is.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Trackpad

#### Device information:

Type of Mac: Macbook Pro 15" Mid 2012, Unibody (non-retina)
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Workaround: if top 2cm of trackpad are avoided, all gestures work as intended

**Comment by fifafu** [comment]
Could you please try the latest alpha? (V2.301)
You can get it by clicking the "check for alpha version updates" button in the BetterTouchTool menubar menu.

**Comment by havumigi** [comment]
Thanks for the quick reply - the issue is still present with V2.301.

**Comment by fifafu** [comment]
Mh could you try to turn off thumb handling in the advanced trackpad settings in BTT?

**Comment by havumigi** [comment]
That's fixed it for me, thanks!!

**Comment by villancikos** [comment]
I also had this issue and deactivating that option fixed it. But I am still on the 2.304 version.
