### ISSUE TITLE
Flickering Touch Bar with modifier key presses

### ISSUE THREAD

**Issue by Jackalton** [fifafu/BetterTouchTool#147]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

With BTT running – even with Touch Bar disabled in its Preferences – pressing the Cmd, Shift, Alt or Fn key in any app causes a brief dimming and undimming of the Touch Bar. Subsequently releasing of the key does the same.

**What kind of Mac are you using?**
13" MacBook Pro TB

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
BTT 1.97 (561)
OS X 10.12.2

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
See #135

**Comment by Jackalton** [comment]
👌🏻

*Ronan Macdonald*
*Freelance writer, editor and media producer*
*Music** | **Technology** | **Computing*
*Facebook <https://www.facebook.com/ronanmacdonaldmt> |* *Twitter
<https://twitter.com/ronanmacdonald> | LinkedIn
<http://www.linkedin.com/pub/ronan-macdonald/8/343/3b7>*

On 21 December 2016 at 14:00:28, Andreas Hegenberg (notifications@github.com)
wrote:

See #135 <https://github.com/fifafu/BetterTouchTool/issues/135>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fifafu/BetterTouchTool/issues/147#issuecomment-268529385>,
or mute the thread
