### ISSUE TITLE
"q" key does not work when BTT(free) is enabled

### ISSUE THREAD

**Issue by akshuu** [fifafu/BetterTouchTool#1471]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

the keyboard key "q" does not work. All other keys are fine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard with Touchbar enabled.

#### Device information:

Type of Mac: Macbook Pro 2017 (15")
macOS version: 10.12.6 
BetterTouchTool version: 2.297 (676) 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You probably have created a shortcut that either is just q or fn+q in the keyboard tab in BetterTouchTool. If you delete that shortcut your key will work again.
