### ISSUE TITLE
[Feature Request] Add native application controls widget to Touch Bar customizations

### ISSUE THREAD

**Issue by morkus64** [fifafu/BetterTouchTool#1476]
Currently it seems that application specific controls (those native to the application, not those set up through BTT) are only available if the BTT bar is closed and "Show MacOS Control Strip" is enabled. I would like to be able to not use the MacOS control strip at all (primarily because it forces the terrible, no good, very bad left escape button on us) while still seeing application specific controls (without having to set each app up individually).

The end result would be:

| ----- APP CONTROLS ----- <|> ----- BTT -----|

(Or reversed)

**Comment by fifafu** [comment]
Unfortunately this is not possible due to API limitations. Sorry!
