### ISSUE TITLE
2/3/4 finger swipe sensitivity settings has too many decimal points

### ISSUE THREAD

**Issue by ceilingcat** [fifafu/BetterTouchTool#1477]
#### Description of bug/feature request/question:

2/3/4 finger swipe sensitivity settings (Advanced --> Swipe) shows at least 11 decimal points (with the 11th partially clipped). I think at most 2 decimal points (giving 101 possible levels of sensitivity) would be enough. Practically though, I think I probably won't be able to use more than 20 levels (from 1 to 20, for example).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

n/a

#### Device information:

Type of Mac: MacBook Pro 13" 2016
macOS version: El Capitan
BetterTouchTool version: https://github.com/fifafu/BetterTouchTool/issues

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting, will be fixed in the next version!
