### ISSUE TITLE
BTT refuses to re-enable since latest update

### ISSUE THREAD

**Issue by firelite** [fifafu/BetterTouchTool#1479]
#### Description of bug/feature request/question:

BTT won't re-enable (automatically or manually) after latest auto-update.  Still won't re-enable after BTT restart and quit/reopen.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

#### Device information:

Type of Mac: iMac (Retina 5K, 27-inch, Late 2014)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.297 (676)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If possible try 2.302 alpha, this should be fixed already.(Get via check for alpha version updates)
