### ISSUE TITLE
Allow Icon Only in Touch Bar Button

### ISSUE THREAD

**Issue by wowthatisrandom** [fifafu/BetterTouchTool#148]
#### Description of your feature request...:
Would love the ability to just use an icon as an item in the touch bar. Currently if you do not add a title the button is not added to the touchbar.

**What kind of Mac are you using?**
13" Macbook Pro w TouchBar
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
1.971

**Comment by fifafu** [comment]
You can click the little gear icon and choose the icon only option there :-)
