### ISSUE TITLE
Touch Bar icon overlay issue

### ISSUE THREAD

**Issue by ads1029** [fifafu/BetterTouchTool#1483]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

activating toucher shoutout in both Chrome and Safari seems to raise this issue a lot. I tried to restart BTT 5 times and this issue keeps showing up in 5 mins every time.
[Imgur](https://i.imgur.com/pGxn2iT.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 2017 mid 13inch MBP
macOS version: Sierra
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately BTT can't influence this behavior of the touch bar. However I have not yet seen this happening on High Sierra, so this may be fixed soon :-)

I'm closing here as I have no possibility to influence it :-(
