### ISSUE TITLE
Can't Enable BTT

### ISSUE THREAD

**Issue by cajpetro** [fifafu/BetterTouchTool#1485]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BTT Loads when I open it, but it's disabled by default somehow and clicking enable doesn't do anything. I've been using the program for many months and this is a brand new phenomenon. I tried quitting and re-opening the program and restarting my computer a few times, nothing worked yet.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro

#### Device information:

Type of Mac: Macbook Pro Retina mid2012
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If possible try 2.302 alpha, this should be fixed.(Get via check for alpha version updates)
