### ISSUE TITLE
BTT Quits (or crashes?) Intermittently During Use

### ISSUE THREAD

**Issue by bradrhoad** [fifafu/BetterTouchTool#1487]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

My BTT keeps quitting randomly throughout the day. I don't get a crash error or anything else, but it just shuts down, and I notice it's not running when I try to use a gesture and nothing happens. I just have to then reopen BTT. I can't pinpoint exactly what gesture or other situation is causing it to close.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

have you already checked if there is any crashlog in the macOS Console.app under "User Reports"?

![image](https://user-images.githubusercontent.com/8820811/30516410-ca915018-9b3e-11e7-9228-775bb3f94579.png)

**Comment by bradrhoad** [comment]
Hi, yes, I have quite a few for BTT. Attached here. Thanks

[BTTCrashLogs_Thread1487.zip](https://github.com/fifafu/BetterTouchTool/files/1314576/BTTCrashLogs_Thread1487.zip)

**Comment by fifafu** [comment]
@bradrhoad I think these might happen if you somewhere have a gesture/shortcut that doesn't have an action assigned. (Of course it should still not crash, I'll be looking into that)

**Comment by bradrhoad** [comment]
Hey, this looks to have fixed the problem. I went in and cleaned up any gestures without actions, and it looks like the crashes have ceased. Thanks!
