### ISSUE TITLE
Unresponsive clicks in Google Chrome

### ISSUE THREAD

**Issue by ntorring** [fifafu/BetterTouchTool#1489]
#### Description of bug/feature request/question:
With the latest Google Chrome version 61.0.3163.91, clicking on some web page items seem unresponsive, as if the click up is not registered. It seems to only affect the Magic Mouse (Configured with middle button click). Native UI elements in Google Chrome seem unaffected.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
- Magic Mouse

#### Device information:
Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Seems similar to issue with iTunes, still present in macOS Sierra (https://github.com/fifafu/BetterTouchTool/issues/216)
Only workaround is to disable BTT for Google Chrome

**Comment by fifafu** [comment]
See #1445
