### ISSUE TITLE
Make an "Enabled" checkbox for trackpad gestures

### ISSUE THREAD

**Issue by sethblumberg** [fifafu/BetterTouchTool#149]
For Keyboard Shortcuts, BTT has an "Enabled" column with checkboxes, so that shortcuts can be switched off.  It would be useful to have this for Trackpad gestures as well.

Over time, I have made lots of shortcuts but some of them I end up not using (or even remembering), so I'd like to disable them.  But I still want to keep them around so that if I were to return to trying to make one of them work, I could easily see what I've tried in the past.

**What kind of Mac are you using?**
2010 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

all trackpads

**Which versions of macOS and BetterTouchTool are you running?**

OS X 10.11.6 El Capitan

**Comment by CappyD** [comment]
I agree.  For consistency, it would be good if the Enabled and Notes fields (as seen in the Keyboard gestures section) were available for all of the gesture types.

**Comment by fifafu** [comment]
Good idea, I'm tracking this here already: #63
