### ISSUE TITLE
`Lock Screen` action appears broken on macOS 10.13 High Sierra

### ISSUE THREAD

**Issue by erikphansen** [fifafu/BetterTouchTool#1491]
#### Description of bug/feature request/question:

The BTT Lock Screen action is not working in the macOS 10.13 GM (10.13 Beta (17A362a)). I can't comment on how it worked in previous beta versions of 10.13 as this is the first version of 10.13 that I tried. The Lock Screen action worked fine in 10.12.x.

#### Device information:

Type of Mac: Late 2013 15" MacBook Pro
macOS version: 10.13 Beta (17A362a)
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I also noticed the LaunchBar's Lock Screen action is much slower than it was in previous OS versions indicating there's been a change to the hooks used to lock the system.

**Comment by cleverjackal** [comment]
What if you just remap it to Control Command Q (the new native lock screen gesture)?

**Comment by erikphansen** [comment]
I started to just use the new ⌘⌃Q shortcut to lock the screen after I posted this, but I didn't even think to remap my gesture to use that keyboard shortcut. D'oh! Thanks for the suggestion. It works great.

**Comment by fifafu** [comment]
It's also fixed in the latest BTT versions.
