### ISSUE TITLE
Action to send sequence of keys

### ISSUE THREAD

**Issue by ben174** [fifafu/BetterTouchTool#1492]
#### Description of bug/feature request/question:

I'd like to be able to map CMD-S to send the sequence of keys `esc` `:` `w` in terminal. This will, in effect, allow me to map CMD-S to save in vim.

**Comment by fifafu** [comment]
You can already send sequences by using the attach additional action button. However I don't know whether vim will like this. However vim is super flexible i'm sure you can define a save shortcut in vim.
