### ISSUE TITLE
Can't use tiptap after scroll down

### ISSUE THREAD

**Issue by sharlinchang** [fifafu/BetterTouchTool#1493]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Can't use tiptap after scroll down

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse 1

#### Device information:

Type of Mac:mbp 13
macOS version: 10.11.6
BetterTouchTool version: 2.3

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
setting: tiptap left -> left click
tiptap will only work on the first time, then I have to release all the finger from mouse so that I can tap again. Kind of annoying.  

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is intentional as otherwise it would often trigger the gesture accidentally.
