### ISSUE TITLE
Modify ESC button size, color and other attributes like any other Touch Bar button

### ISSUE THREAD

**Issue by zupodaniel** [fifafu/BetterTouchTool#1497]
#### Description of feature request:

Today is not possible to modify the appearance of esc button generated by "Show left button on the left side of Touch Bar". I can include my own customized ESC, but it doesn't have the same behaviour of the original button like reported in [issue 1468](https://github.com/fifafu/BetterTouchTool/issues/1468).

I think that at least one of these issues could be addressed to improve BTT Touch Bar support.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All devices.

**Comment by fifafu** [comment]
I have added an ESC action which mimics the behaviour of the original ESC button when assigned to a Touch Bar button.

![image](https://user-images.githubusercontent.com/8820811/30765473-25811df4-9ff0-11e7-8bf7-e2f17c7e9fd9.png)
