### ISSUE TITLE
[Bug] Safari Pinch to Zoom customization disable all gestures in safari

### ISSUE THREAD

**Issue by ckizer** [fifafu/BetterTouchTool#15]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

Safari Gestures:
If I disable the pinch to zoom to prevent going out to thumbnail view, I can no longer expand to zoom in on text. All gestures are disabled and not just pinch to zoom.

**What kind of Mac are you using?**
Touchbar MacBook Pro 2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad

**Which version of macOS are you running?**
10.12.2 Beta (16C53a)

**Comment by al3xandru** [comment]
I cannot say if this is exactly the issue I'm seeing, but I cannot get any of the Pinch actions to do anything in Safari.

1. HW: TouchBar MacBook Pro 13" Late 2016
2. Input device: MacBook Trackpad
3. macOS: 10.12.1
4. BTT: 1.963 (552)

**Comment by fifafu** [comment]
Unfortunately this can not be fixed.

@al3xandru your issue should be fixed with the new alpha.
