### ISSUE TITLE
Right-side TB button moves

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#150]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have an app touch bar defined with a button stuck to the right side.  If I click on the desktop making Finder active (and for which I have no TB defined in BTT) and then click on the app's window again, the app's TB reappears but the right-side icon is now moved a little bit to the left.  If I switch to another app that has a right-side button and return to the app, then the right-side button is all the way at the left as it should be.  (it was at the right place in the intermediate app as well)  

Note that I have system setting "touch bar shows: app controls" and BTT app-specific setting "show BTT TB, hide control strip".

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.972

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
COuld you check if 1.973 fixes this?

**Comment by CappyD** [comment]
Hi Andreas... no, I'm afraid this one is still there.

**Comment by fifafu** [comment]
Ok, I have done some more experiments and hope it's also fixed with 1.974. Please let me know!

**Comment by CappyD** [comment]
Yep... looks like you got it!  Thanks!

**Comment by CappyD** [comment]
Well, this is weird.  After playing with it a bit more, I've seen the right-side button move from the right side all the way to the left side of the bar when I switch out of the app and then back to it.  Doesn't always happen, and I can't quite figure out the circumstances for when it does.

**Comment by CappyD** [comment]
That's with 1.976 BTW.  When I can recreate it, it usually requires switching from the app to a bunch of other apps without defined TBs and then back to the app with a right-side button.

**Comment by fifafu** [comment]
Thanks I think it may be relatee to #158. My vacation starts today so expect many improvements during the next two weeks :-)

**Comment by CappyD** [comment]
so far, I haven't been able to reproduce this under 1.977, so I think it fixes this.
