### ISSUE TITLE
4 Fingers swipe not working

### ISSUE THREAD

**Issue by andybergon** [fifafu/BetterTouchTool#1500]
#### Description of bug/feature request/question:
I tried to bind the `cmd+tab` command to the 4 finger swipe but when I try to use it It switches between spaces, that is the default 3 (and 4) finger action. I attached a screen where you can see the correctly set up gestures and that the system correctly recognize the gesture but it doesn't do the right action.

Maybe this is related to the message that appears under the 4 finger gesture to disable the 4 finger gesture but I can't find it under `Preferences > Trackpad` as the message says.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MBP15 late 2016
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://user-images.githubusercontent.com/5220825/30620553-f2396d88-9d9d-11e7-8516-d9a40fdd1dc3.png)

![image](https://user-images.githubusercontent.com/5220825/30620670-99753014-9d9e-11e7-9577-ca464e2fa920.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by andybergon** [comment]
This worked for me. Took a while to find.
Probably going to buy a license of this great product :)

![](https://d26dzxoao6i3hh.cloudfront.net/items/060u1K1K2E0I0h462924/Image%202017-09-22%20at%206.44.52%20PM.public.2S170l2x180X.png)

**Comment by nenadn** [comment]
Hi,

Do you know how to make "4 finger swipe up" to do "scroll up"? the same with "4 finger swipe down" -> "scroll down". I figured that it would be very useful for resting the hand having four fingers on trackpad while scrolling.

Can find the setting for it though..

Thanks,

Nenad
