### ISSUE TITLE
Touchbar - Can't display icon only

### ISSUE THREAD

**Issue by abdulfhussain** [fifafu/BetterTouchTool#1503]
I am trying to add buttons to the touchbar, I want to display only the icon and not text, when I select the checkbox to only show the icon, the text disappears but so does the icon image, I get a small button with only a dot in it.  The only way to get the icon back is to delete the button and re-add it, I can't just uncheck the checkbox.

This working working fine in an older version

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Tompz** [comment]
had this issue too.  If you go back into the button settings and set the width and height to 22px, then it should work for you.

**Comment by abdulfhussain** [comment]
Thank you, that worked.  Much appreciated.

**Comment by fifafu** [comment]
I think this should be fixed in v2.305 alpha!
