### ISSUE TITLE
BTT overriding mission control gesture

### ISSUE THREAD

**Issue by patrickhousley** [fifafu/BetterTouchTool#1504]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Ever since I updated to 2.304, my system three finger swipe up settings are overridden when I open BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.11.6
BetterTouchTool version: 2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
To restore my setting, I have to close BTT, open trackpad settings and change the mission control gesture from three finger to four then back to three. Also with BTT open, four finger swipe up seems to open mission control.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by ngjunjie1991** [comment]
Same issue is happening to me, and the workaround is the same as what you've posted.

**Device information:**
Type of Mac: MacBook Pro (15-inch, Mid 2012)
macOS version: 10.10.5
BetterTouchTool version: 2.304

**Comment by canondetortugas** [comment]
I have the same issue and same workaround.

**Device information:**
Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2013)
macOS version: 10.11.1
BetterTouchTool version: 2.304

**Comment by patrickhousley** [comment]
Looks good @fifafu. Thanks for addressing so quickly.
