### ISSUE TITLE
Please add (Quit App) in the Predefined Action list

### ISSUE THREAD

**Issue by MiRO92** [fifafu/BetterTouchTool#1507]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Feature request:
**Please add (Quit App) in the Predefined Action list, I really really need it, Please 🙏🏻🙏🏻🙏🏻**🙏🏻🙏🏻

#### Device information:

Type of Mac: MacBook Pro with Touch Bar (late 2016)

**Comment by fifafu** [comment]
You can just assign the keyboard shortcut "cmd+q"

**Comment by MiRO92** [comment]
I know and i did tried it, but it has an issue, if I want to quit the app and the app window is inactive then it will quit the Active app that am on,

For example If I'm working in Google Chrome (which it's active) and I want to quit Adobe Photoshop (which it's inactive window) then it will quit Google chrome

any fix?

**Comment by MiRO92** [comment]
@fifafu I wish you can add these to BetterTouchTool
<img width="660" alt="screen shot 2017-09-20 at 20 46 13" src="https://user-images.githubusercontent.com/3205572/30658875-cf1f4e74-9e44-11e7-8386-de070c9b882a.png">

**Comment by cleverjackal** [comment]
Just go to the app switch with Command Tab, and then press Command Q with Photoshop highlighted

**Comment by fifafu** [comment]
Even better than that use the "Activate/Bring To Front Window Under Cursor" action in combination with CMD+Q

See this screenshot: 
![image](https://user-images.githubusercontent.com/8820811/30765579-a6e20098-9ff0-11e7-82b3-71c5817c5d1a.png)
![image](https://user-images.githubusercontent.com/8820811/30765591-b7329930-9ff0-11e7-85a7-955cb7a3bfef.png)
