### ISSUE TITLE
Snapping moves window to next space, how to disable?

### ISSUE THREAD

**Issue by alexanderswoo** [fifafu/BetterTouchTool#1509]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi, whenever I want to snap a window to the right side, it moves the window to the next space, which I do not want. -Is it possible to turn this of somewhere? a mac preference?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
macbook trackpad

#### Device information:

Type of Mac: macbook pro 15 inch, late 2013
macOS version: siearra 10.12.6
BetterTouchTool version: 2.267

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can use this terminal command to increase the time before snapping:

```
defaults write com.apple.dock workspaces-edge-delay -float 2.0; killall Dock
```

(2.0 is the time in seconds)

**Comment by alexanderswoo** [comment]
Thanks, that helped and solved my problem!

Alex
