### ISSUE TITLE
Cannot save colors in Colors dialog 

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#151]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
This concerns the Colors dialog that is presented when selecting the touch bar button color.  I assume this is the standard Apple Colors dialog available elsewhere such as in Mail.  In Mail, for example, I can drag a selected color from the large color swatch at bottom-left and drop it on one of the 20 small boxes at bottom-right to save that color for future use.  But the color does not get dropped and remembered when trying to do the same in BTT.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.972

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks for reporting, should be fixed with upcoming 1.974 in a few minutes!

**Comment by CappyD** [comment]
Looks like you got this one fixed too... I can now save a color.  Thanks again!
