### ISSUE TITLE
Leap Motion functionality as per documentation

### ISSUE THREAD

**Issue by planetceres** [fifafu/BetterTouchTool#1510]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Has Leap Motion support been permanently disabled? I recently purchased BetterTouchTool based on the statement in the [http://docs.bettertouchtool.net/docs/leap.html](docs) that Leap would stay in BTT, but that updates for it wouldn't continue. This was ok, since it was working with no issues.

As of today though, I am no longer able to access my Leap presets or configure new ones through BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Leap Motion

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: Sierra 10.12.6 (16G29)
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The versions that include the Leap functionality will stay available and should continue to work fine , e.g. https://bettertouchtool.net/releases/btt2.297b.zip

However It probably won't be included in future updates anymore ( on the one hand because it caused issues with High Sierra, on the other hand because only a handful of people used it)

**Comment by ddiazescandon** [comment]
Please don't! Leap is insanely  useful just because btt.  Even if we're a  handful of people, you can stop working about mouse movements but please don't stop the support for gestures.

**Comment by fifafu** [comment]
The old BTT versions won't go away so you will be able to continue using it if you want to.  I just can't justify to work on this anymore. Less than 0,1% of BTT's users are using Leap functionality  and Leap itself has basically abandoned the Mac platform.
I would need to upgrade to their new framework, but their new framework is already kind of deprecated so this doesn't make sense. Leap seems to completely focus on AR/VR now :-(

In case you want to downgrade BTT, you may need to go to ~/Library/Application Support/BetterTouchTool and rename the 
btt_data_store.v2.oldVersionBackup2.2xx to btt_data_store.v2
btt_data_store.v2-shm.oldVersionBackup2.2xx to btt_data_store.v2-shm
btt_data_store.v2-wal.oldVersionBackup2.2xx to btt_data_store.v2-wal

**Comment by planetceres** [comment]
I restored to version 2.297, but it seems like all of my custom presets have been lost. Is there any way to recover these?

**Comment by gildardoperez** [comment]
All versions available for BTT:
`https://bettertouchtool.net/releases/?C=M;O=D`

Version specified by @planetceres: 
`https://bettertouchtool.net/releases/btt2.297b.zip`

Make sure to remove all of you other assets before you unzip and install:
`rm -rf ~/Library/Application Support/BetterTouchTool`

Recover your key and follow the steps, make sure to always skip newest version..this version includes Leap Motion for BetterTouchTool.

Thanks

**Comment by planetceres** [comment]
I have been using 2.297b as suggested, but every once in a while BetterTouchTool upgrades automatically, and I have to go through the process of reinstalling and restoring my presets again.

I can confirm that "Enable automatic update checking" is disabled in the General settings. Besides this checkbox, is there any other way to prevent the automatic updates?

I understand that Leap Motion functionality is a very small minority of BTT users, but for me it is the _only_ reason I use BTT.

**Comment by rohanrehman** [comment]
Posting from Tokyo. early license supporter. own 2 leap motion devices. I guess no choice but to use 2.297b.

**Comment by iDonev** [comment]
Hello!

I have been trying to get 2.297b to work for some time but unfortunately I'm not able to. Each time I launch BTT, I get a "BTT Version Expired" message. 

I have already tried removing the BTT folder as instructed by @gildardoperez but to no avail. Am I missing something?

Thank!

Best Regards,
Iskren

**Comment by fifafu** [comment]
@idonev, this folder also contained your license info, you need to double click your license file again to make it work.

**Comment by iDonev** [comment]
@fifafu Awesome! Apparently the issue was that I was using BTT in trial mode to begin with (just finished reinstalling macOS). As soon as I added my license key everything worked like a charm :)
