### ISSUE TITLE
Icon size set to 1 1 when dropping icon images

### ISSUE THREAD

**Issue by jeanfabre** [fifafu/BetterTouchTool#1511]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The size of icons is set to 1 and 1 automatically after I dropped an icon on the button

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: macbookpro 15" 2017
macOS version: 10.12.6
BetterTouchTool version: 2304 (682)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry I had a typo in there. Should be fixed in 2.305.

**Comment by jeanfabre** [comment]
Thanks :)
