### ISSUE TITLE
More advanced resizing

### ISSUE THREAD

**Issue by simongade** [fifafu/BetterTouchTool#1512]
#### Description of bug/feature request/question:
Feature request
With a large monitor, the current choices for resizing are limited. I would e.g. like to resize to the top half of the left third of the screen. Or maybe even the top third of the left third of the screen.
It is of course not possible to create an excessive amount of options so I suggest making it user configurable, possibly in the same way Moom has solved it.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac: iMac 27-inch
macOS version: 10.12.6
BetterTouchTool version: 2.304

**Comment by fifafu** [comment]
Have you already tried the custom snap area feature in BTT? (Click the menubar icon, then select snap areas)

**Comment by simongade** [comment]
Hi Andreas,

Yes, I’ve tried it but that’s not exactly what I’m looking for.

First of all, I’d like everything to line up perfectly which is almost impossible with snap areas. I’d like to define, say “the screen is 6x6. I want to maximise to the top left 2x2” (that would be the top third of the left third of the screen).
Secondly, I have an iMac at home, a MacBook Pro, and a 34” monitor at work (connected to the MacBook Pro). That’s a lot work needing to be done.
Thirdly, I love my trackpad and keyboard combos and want to setup everything so that e.g. shift+alt+tap top left is top third of the left third of the screen. Makes it extremely easy to remember and I can have a plethora of maximising options for different types of jobs.


Simon

**Comment by simongade** [comment]
Oh, and thank you for the quick reply!

I already “sold” BTT to a few friends that also love it :-)

**Comment by fifafu** [comment]
Unfortunately this kind of grid snapping probably won't be added to BTT in the near term.
However you can assign keyboard shortcuts to snap areas, and if necessary you can edit the snap areas in json format to make everything align correctly. I'll post an example later.

**Comment by simongade** [comment]
Understood.

I think I’ll use a combination of Moom (with hotkeys) and BTT invoking those hotkeys.

By the way, there’s a slight inconsistency in the naming of gestures:
1 Finger Tap Top Left
1 Finger Bottom Tap Left
1 Finger Tap Top Middle

They should all be
1 Finger Tap Top/Middle/Bottom Left/Middle/Right


Simon

**Comment by fifafu** [comment]
Yep, Moom is definitely the right tool for this job!! 

You are right, I'll fix that. Thanks for reporting :-)
