### ISSUE TITLE
TouchBar disappeared in 2.304

### ISSUE THREAD

**Issue by vladikoff** [fifafu/BetterTouchTool#1513]
---

#### Description of bug/feature request/question:

I just updated to latest BTT and my custom touchbar disappeared  :(
It reverted back to the default OS X thing. Any ideas?

#### Device information:

Type of Mac: MBPp with the touchbar
macOS version: 10.12.6
BetterTouchTool version: 2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by vladikoff** [comment]
Ok i got it back by going into settings, checking "Show BTT button", pressing it. Then unchecking it again

![](http://v14d.com/i/59c3eefde4ca3.jpg)

**Comment by vladikoff** [comment]
After waking up my machine from sleep the BTT touchbar disappeared again :(

**Comment by fifafu** [comment]
How do you toggle the BetterTouchTool Touchbar if you don't show the BTT icon in the control strip? Do you have a gesture or shortcut configured with the predefined action "toggle BetterTouchTool Touchbar"?

**Comment by vladikoff** [comment]
Here's my config: 

![](http://v14d.com/i/59c3fc603bc46.png)


> How do you toggle the BetterTouchTool Touchbar if you don't show the BTT icon in the control strip? 

I try to **ALWAYS** show the BTT bar, permanent buttons. I don't like app specific buttons. 

> Do you have a gesture or shortcut configured with the predefined action "toggle BetterTouchTool Touchbar"?

Nope


Thanks for the quick response!

**Comment by vladikoff** [comment]
I think the main regression with the 2.304 update is this:

If I had the BTT only touchbar strip enabled it would stay on it after the computer came back from sleep. With 2.304 it's not the case anymore.

**Comment by fifafu** [comment]
Unfortunately I'm currently unable to reproduce this here.

If possible please go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. If you send me the contents of this folder to boastr.net@gmail.com I'll check what's wrong!

**Comment by fifafu** [comment]
Ah I think I might have an idea.
Could you try to add the "Unlock Screen" action to BTT and check whether it works afterwards? (you don't have to actually use this gesture)

![image](https://user-images.githubusercontent.com/8820811/30720910-c3972c08-9f29-11e7-9488-a7c966eaba6f.png)

**Comment by vladikoff** [comment]
> Could you try to add the "Unlock Screen" action to BTT and check whether it works afterwards?

No luck, sent you the debug info though

**Comment by rssalerno** [comment]
I updated to 2.304 (682) and I'm having the exact same issue.  My global touchbar setup is gone.  Reappears if I do the touchbar button trick, disappears after sleep. Tried to downgrade but my data file is no longer compatible.  Seems like the BetterTouchTool Touch Bar is toggling off.  Screenshots attached... Please help.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/1527028/30727552-f28af15c-9f1f-11e7-8763-f05bf7ca8369.png">

**Comment by fantaaaaaa** [comment]
Same here :(

**Comment by kelaun** [comment]
I'm having the same issue as well.
I've yet to find a solution for this.

**Comment by swangear** [comment]
I'm having the same problem, very frustrating. The "unlock screen" gesture suggested earlier didn't work for me either.

**Comment by fifafu** [comment]
I'll upload an alpha version that will fix this in about an hour.

**Comment by vladikoff** [comment]
@fifafu Thank you so much for the fix and support. Download the latest version and life is good again 👍

**Comment by swangear** [comment]
Agreed, thank you so much! Working perfectly

**Comment by rssalerno** [comment]
Great software, great support.  My Macbook is sane again.  Thank you!!
