### ISSUE TITLE
Trackpad disable when keying enhancement request

### ISSUE THREAD

**Issue by SeaJester** [fifafu/BetterTouchTool#1515]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  ProcType of Mac:
macOS version: Sierra 10.12.6 (16G29)
BetterTouchTool version: 2.304 (682)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I have had surgery on my hands and there is an arc from my little finger to my thumb that I cannot straighten. As a result either thumb will consistently touch the pad.  What would really help is to have it disable when I start keying and have some very positive gesture to enable.  Thank you so much.. as it is it has helped quite a bit.

Craig

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can enable this in the advanced settings, however BTT can only affect it's on gestures for technical reasons:

![image](https://user-images.githubusercontent.com/8820811/30753145-c1153fb6-9fbe-11e7-86a4-d46da2b95ffd.png)
