### ISSUE TITLE
My BTT isn't working for chrome

### ISSUE THREAD

**Issue by rockcola** [fifafu/BetterTouchTool#1516]
#### Description of bug/feature request/question:
Whenever I use BTT in chrome, it will jump to safari. 
For example, I click the youtube button and it will not open it in chrome but in safari.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: MacOS Sierra
macOS version: 10.12.6
BetterTouchTool version: 2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
My predefined action is open url: http://www.youtube.com/

**Comment by fifafu** [comment]
You need to make chrome your default browser if you want BTT to open the urls with Chrome
