### ISSUE TITLE
Two Issues in the new update 2.304 (682)

### ISSUE THREAD

**Issue by ddiazescandon** [fifafu/BetterTouchTool#1517]
### Description of bug/feature request/question:
Leap motion not working any more and my Intuos Wacom is not recognized at all.

Before this update I could use my wacom and leap motion to control several actions, like swipe desktops and snapshots within btt. I checked and there seems to be no more support for leap motion at the btt app, and its suppose to be an update with leap motion controller support in next upgrades ...or it seems so  in the blog. But there is no word about wacom, and It was working just fine 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Leap Motion
Intuos Wacom

#### Device information:
Type of Mac: iMac 2013
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.304 (682)

---

**Comment by ddiazescandon** [comment]
Also, live view is not working at all, nor even magic mouse.

**Comment by fifafu** [comment]
Leap and the experimental Wacom support are currently both not available in the latest BTT version. See the release notes: https://updates.bettertouchtool.net/bettertouchtool_release_notes.html

Wacom will be back as soon as the High Sierra related bug is fixed.
Unfortunately Leap support will probably not come back. It caused issues on High Sierra and there are almost no Leap users left, thus I can't justify to spend the time to switch to their new framework.


Live View for Magic mouse will be back this evening!

**Comment by roinigo** [comment]
Hi! How can i re-install a wacom compatible version of BTT, please ?

**Comment by fifafu** [comment]
BTT 2.315 alpha should bring back the basic wacom support.
