### ISSUE TITLE
BTT touchbar not hiding

### ISSUE THREAD

**Issue by tnaz** [fifafu/BetterTouchTool#152]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

BTT touchbar does not hide on apps where nothing is configured, even if there are no global actions configured. so when an application has no configurations the touch bar displays "you have not yet configured actions in bettertouchtool." this is in contrast to the settings i have set up in general touch bar settings by checking the "hide bettertouchtool touch bar if nothing to show" option

**What kind of Mac are you using?**
MPB touchbar 2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
touch bar

**Which versions of macOS and BetterTouchTool are you running?**

10.12.2 BTT 1.972
**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Mhh, this seems to work fine for me. Could you send me an export of your setup to boastr.net@gmail.com? (via the export preset button in the BetterTouchTool window)

**Comment by fifafu** [comment]
Thank you! I think I may have identified the issue. Could you check if 1.973 works correctly for you? (via alpha update)

**Comment by tnaz** [comment]
perfect! 1.973 does the job!

**Comment by tnaz** [comment]
this problem seems to be occurring again with the 1.980 update. when switching back and forth to applications the message "you have not yet configured actions in btt" comes up again, forcing me to hit the X to display the application's (e.g safari default) touch bar.

**Comment by fifafu** [comment]
Mhh, I can't

**Comment by tnaz** [comment]
yes, still activated.

**Comment by tnaz** [comment]
looks like the latest update works!
