### ISSUE TITLE
Clicking goes through programs

### ISSUE THREAD

**Issue by borisspektor** [fifafu/BetterTouchTool#1521]
#### Description of bug/feature request/question:
When working with Android Studio/Appcode (Also Terminal and probably other programs as well) clicking on the text, then alt-switching to another program and clicking somewhere there selects the text in the previous program
Possibly related is an issue where I click somewhere in the terminal and then clicking anywhere selects (and instantly deselects) the text between first cursor and second (and it repeats for repeated clicks on different places) 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:
Type of Mac: MacBook Pro 15 2017
macOS version: 10.12.6
BetterTouchTool version: 2.304(682)

**Comment by fifafu** [comment]
I can't seem to be able to reproduce this. Does this still occur in the latest version of BTT? (2.310)

**Comment by borisspektor** [comment]
@fifafu yes, I updated to the latest version and still get this. Have you tested it with Terminal and Android Studio?

**Comment by fifafu** [comment]
I think this is the same issue and should be fixed with the next update: #1578

**Comment by borisspektor** [comment]
@fifafu yes seems like the same issue. What version was it fixed in?

**Comment by fifafu** [comment]
The update is not yet available (will be in a few days). Every version >= 3.12 will contain the fix.

**Comment by borisspektor** [comment]
ok thanks!

*Boris Spektor*
Mobile Team Leader
*M* +972.52.82.32.454
*E* boris@soom.la <refael@soom.la>
[image: Google Products] <http://soom.la/>
soom.la

On Wed, Oct 18, 2017 at 1:56 AM, Andreas Hegenberg <notifications@github.com
