### ISSUE TITLE
Make Presets sync with a Cloud Storage

### ISSUE THREAD

**Issue by andybergon** [fifafu/BetterTouchTool#1522]
#### Description of bug/feature request/question:
It would be great to have BTT sync the presets with a cloud storage system like Google Drive ([Storing Application Data API](https://developers.google.com/drive/v3/web/appdata)) or other services like Dropbox/GitHub (but I don't know if they have an easy integration like Drive).

**Comment by fifafu** [comment]
Hey,

You can activate dropbox sync in the advanced preferences :-)

**Comment by andybergon** [comment]
Wow that's great!
