### ISSUE TITLE
Touchbar customization goes away after sleep/wake in Version 2.304

### ISSUE THREAD

**Issue by yo3yo3yo3yo3** [fifafu/BetterTouchTool#1523]
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.): Touchbar.

Type of Mac: 2017 MacBook Pro 15-inch. 
macOS version: 10.12.6
BetterTouchTool version: Version 2.304 (682)

![img_5772](https://user-images.githubusercontent.com/22380423/30762858-4ba9fa7e-9fa9-11e7-8906-b010422b54f4.jpg)
![img_5773](https://user-images.githubusercontent.com/22380423/30762857-4ba75f12-9fa9-11e7-98e1-6754741c9b53.jpg)

**Comment by fifafu** [comment]
This should be fixed in 2.305 ;-)

**Comment by yo3yo3yo3yo3** [comment]
Sweeeeet. This is what I want to hear, thank you. Would checking for alpha updates now help at all? Or just wait for the next major release?

**Comment by fifafu** [comment]
Yes, please try the alpha update. Let me know if it fixed your issue if possible.

**Comment by yo3yo3yo3yo3** [comment]
Just installed the alpha update. It's fixed! It does briefly load up the default Apple Touchbar stuff but then automatically switches over to my customized one very quickly. I vaguely remember it simply displaying the customized BTT Touchbar at all times before with no switching back and forth (which seems like the ideal situation), but I'm now happy to at least have it switch to the BTT customized Touchbar upon waking up without any effort from me. Seriously, thanks for responding so quickly and for the help.

**Comment by fifafu** [comment]
I think it has always briefly flashed the original touch bar, this is because BTT needs to restart itself after the Mac wakes from sleep in order to re-initialize.
