### ISSUE TITLE
Mouse cursor speed request

### ISSUE THREAD

**Issue by jonteamere** [fifafu/BetterTouchTool#1525]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I like how you've allowed the ability to adjust mouse cursor speed. However, I die a little bit inside when I can't get the numbers 'even' with the slider. Is there any way you'd consider adding the ability to 'type in' a speed OR make the slider a bit more uniform? Pref for *typable cursor speed*.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse. Regular old mouse. But I guess it applies to Magic Mouse as well.

#### Device information:

Type of Mac: 2017 MBP-R-TB
macOS version:  10.12.6 Sierra
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

NA

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I have made the slider labels editable, will be included in the next update ;-)
