### ISSUE TITLE
Re: #1087 ioreg processes for clamshell mode not terminating

### ISSUE THREAD

**Issue by kevinross** [fifafu/BetterTouchTool#1526]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Are there docs to disable what's described in #1087 and force clamshell mode? I have 51 ioreg procs running right now and that number is growing.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad

#### Device information:

Type of Mac: MBP early 2015
macOS version: 10.9
BetterTouchTool version: 2.05

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Related: #1087 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
```defaults write com.hegenberg.BetterTouchTool BTTClamshellCheckDisabled YES```

However ioreg should automatically close itself, have you already tried to restart your system?
