### ISSUE TITLE
Activate/Bring to Front Window Under Cursor - Second Monitor & Google Chrome

### ISSUE THREAD

**Issue by xInstead** [fifafu/BetterTouchTool#1527]
#### Description of bug/feature request/question:

This one is just a little thing but it still bugs me every time since I always have to keep in mind not running into it and it also spoils the overall great workflow I have set up. 

It's regarding two monitors or a second monitor and mainly Google Chrome. All my mouse gestures are triggered through the Predefined Action "Activate/Bring to Front Window Under Cursor". So for example I close targeted windows directly with a "2 Finger Tap" which triggers ⌘W.

Now the problem with Chrome is whenever I have a window open on each of my monitor and then switch the focus to the Finder for example, BTT remembers the last activated Chrome window and ignores my next "Activate/Bring to Front Window Under Cursor" action that I use on Chrome. So if I plan to close a Chrome window with my "2 Finger Tap" and target the one that wasn't activated at last, it still closes the other window that was activated last before I switched to the Finder.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse 2

#### Device information:

Type of Mac: iMac Late 2012
macOS version: macOS 10.12.6
BetterTouchTool version: 2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

It doesn't happen when both Chrome windows are located on the same monitor, no matter which one.

**Comment by fifafu** [comment]
In order to close the window below cursor please use the predefined action "Close WIndow Under Cursor"

**Comment by xInstead** [comment]
Unfortunately it doesn't solve the problem in this case. If you have Chrome windows with tabs open, it's going to close the whole windows even though I only want to close single tabs.

**Comment by fifafu** [comment]
Ah that's true. I don't know whether there is a way to achieve this but I'll check

**Comment by xInstead** [comment]
I just found a workaround or compromise.

In the system settings under Mission Control, if you uncheck "Displays have seperate Spaces", then it works as desired. It's totally fine like this, so don't waste too much time trying to figure out how to make it work the other way around.
