### ISSUE TITLE
4 fingers swipe triggers also 3 fingers swipe

### ISSUE THREAD

**Issue by andybergon** [fifafu/BetterTouchTool#1528]
#### Description of bug/feature request/question:
If a swipe the touchpad with 4 fingers both the 3 and 4 fingers shortcuts are called.
This happens even if I enabled the apposite option in the settings.

![image](https://user-images.githubusercontent.com/5220825/30768930-87e0110a-a007-11e7-9f44-975458024e21.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MBP15 late 2016
macOS version: 10.12.6
BetterTouchTool version: 2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I can't seem to reproduce this. Is it triggering the BTT Three/Four Finger swipe or the system's gestures? (In order to use BTT successfully disable the system gestures)

**Comment by andybergon** [comment]
I cannot reproduce this. It is working even without disabling system gestures.
I will reopen this if it re-happens.

**Comment by andybergon** [comment]
Actually I just discovered that the 4 fingers swipe works when the 3 finger swipe action is unable to perform (I use the default change desktop/full screen app). So if I have only 1 desktop the 4 fingers action works correctly (switching between windows of the same app, but it should not be relevant).

@fifafu With disabling the system gestures you mean manually disabling all the gesture here?

![image](https://user-images.githubusercontent.com/5220825/31313528-878e914a-abdd-11e7-9c27-e04a2c49b079.png)

**Comment by andybergon** [comment]
Disabling the `Swipe between full-screen apps` works.

@fifafu 
Is there a specific BTT `Predefined Action` for changing space or the only way is to assign the keyboard shortcut `^+rightArrow`?
