### ISSUE TITLE
Where can I download older versions of BTT?

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#1531]
Just wondering if I can do this because of the disabled three-finger drag issue.

**Comment by fifafu** [comment]
https://boastr.net/releases 
However the current versions seem to work fine here with three finger drag enabled.

**Comment by cleverjackal** [comment]
Great, thanks! I'm still having the issue though. I'll find out more and get back to you.

**Comment by cleverjackal** [comment]
@fifafu Good news! I've figured out the version which causes this problem.

BTT Version | Works?
2.295 | Yes
2.300 | Yes
2.301 | No
2.304 | No
2.305 | No
2.307 | No

So something changed between 2.300 and 2.301 which causes this problem.

**How to reproduce:**

1. Run the current version (2.307 is fine) on a clean installation (you can just delete the library folder). Open BTT.
2. Add the trackpad gesture "TipTap Left (2 Finger Fix)" and assign it to some keyboard shortcut. You may also use the middle or the right TipTap, or even the 3 Finger Fix. The problem will occur for all of them (though the problem doesn't occur with the 1 Finger Fix TipTap).
3. Try three finger dragging from the beginning of a sentence horizontally  the sentence in Safari. You'll notice that although you started dragging from the beginning of word 1, the text will _start being selected_ from word 2 or 3.

Step 4 is the issue. It should start selecting from the beginning of word 1, exactly where you started dragging it from. You can test this by trying steps 1-4 with 2.300 – it will work fine.

**Comment by cleverjackal** [comment]
Thanks a lot for the link as well. I'll stay on 2.300 for now! It's saved me a lot of pain :)

**Comment by fifafu** [comment]
Ah thanks for the detailed description.
I can reproduce the issue, unfortunately there is no optimal way to solve it.

I'll make a option that toggles between the current and the old behavior. (The current may be slower to start the three finger drag but increases snap area & window snapping performance, the old one lowers snap area / window snapping performance but is better at three finger drags.)

I wish Apple would revert to the 3 finger drag logic they had until macOS 10.9/10.10 :-(

**Comment by cleverjackal** [comment]
Oh, no problem! Honestly a toggle like that would be more than amazing! Having to work around Apple's changes must now be fun. I'm just glad I've found a version that works, so I'm quite happy to keep using that for now. Thank you again.

**Comment by fifafu** [comment]
The latest alpha has a option for that, I hope it works correclty:

![image](https://user-images.githubusercontent.com/8820811/31052966-3c70720a-a692-11e7-9285-b16321f9f3c8.png)

**Comment by cleverjackal** [comment]
Wow, it worked. Thank you so much! I needed to upgrade because my actions were converted to the new format and I had no backup, but I didn't want to bother you with that as well. So thanks for taking care of everything!

**Comment by cleverjackal** [comment]
@fifafu Hey, I just wanted to mention that I'm using the latest version (2.318) on High Sierra, and the three finger drag optimization option works perfectly! Thanks so much for taking the time to fix this.
