### ISSUE TITLE
Mouse click often didn't work

### ISSUE THREAD

**Issue by Saratxe** [fifafu/BetterTouchTool#1533]
#### Description of bug/feature request/question:

Left Mouse click often didn't work. I need to click 3-4 time before the mouse click is done if BTT is running. First I thought my Magic Mouse is broken over the years. But if I quit BTT everything is fine and works again without problems. 

Magic Trackpad works fine all the time.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: iMac mid 2011, 16GB RAM
macOS version: 10.12.6
BetterTouchTool version: 2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In which applications do you experience this? (Google Chrome currently has a bug that can cause such behavior)

**Comment by Saratxe** [comment]
Yes, I noticed this problem in Chrome.

**Comment by leonk** [comment]
Also experiencing this with Chrome.  Have currently disabled Better Touch Tool as it's become unusable to work with it.

**Comment by fifafu** [comment]
Please try the current BetterTouchTool alpha (2.307). I have added a temporary workaround as discussed with the Chromium team. (Get via "check for alpha version updates")

Closing here as this issue is tracked here: #1445
