### ISSUE TITLE
After updated trackpad2 " click "sometimes can not be used

### ISSUE THREAD

**Issue by tigerpa666666** [fifafu/BetterTouchTool#1534]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:iMac (Retina 5K, 27-inch, Late 2015)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Does this still happen with the latest version? I can't seem to reproduce any problems with the click.

**Comment by tigerpa666666** [comment]
Sorry，after check ，My trackpad2 has a little  hardware problem with "force touch".Now it is ok.thank you!
