### ISSUE TITLE
Volume controls don't work on High Sierra

### ISSUE THREAD

**Issue by Clevprof** [fifafu/BetterTouchTool#1535]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After updating to High Sierra the feature where I can control the volume with my apple remote aluminium remote no longer works, I have tried using shortcuts but this doesn't work.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple aluminium remote

#### Device information:

Type of Mac: Mac Mini 2012 version
macOS version: High Sierra
BetterTouchTool version: 2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by spachner** [comment]
Me too, volume control does not work anymore. 
Device information:

Type of Mac: iMac 17 late 2009
macOS version: High Sierra
BetterTouchTool version: 2.305

Since volume control does not work either with EyeTV when BTT is turned off I assume a general problem with MacOS and not a specific one of BTT

regards

spachner

**Comment by fifafu** [comment]
Unfortunately I can't seem to be able to reproduce this. Does this still happen on your machines?

**Comment by Clevprof** [comment]
It’s all working now thanks

**Comment by spachner** [comment]
Magicly it is working now. Thanks for the effort

**Comment by Clevprof** [comment]
When i emailed you this was not working, the only update i have knowingly done is update to the latest version of high sierra (last night) and this works fine. I did not have a chance to test this out until you had emailed.

**Comment by Clevprof** [comment]
My apologies, got mixed up with the email addresses
