### ISSUE TITLE
Is it possible to make the F-keys the system-wide touch bar default?

### ISSUE THREAD

**Issue by emendelson** [fifafu/BetterTouchTool#1536]
The title is the whole question. Is it possible to use BetterTouchTool so that the F1-F12 keys are displayed by default in the Touch Bar (with the Fn key bringing up the normal touch bar, perhaps)? Or has Apple made this impossible?

I tried doing this in the latest version, but had no success.

Thank you!

**Comment by fifafu** [comment]
In macOS High Sierra, which will be released tomorrow, this is possible in System Preferences => Keyboard.
