### ISSUE TITLE
Mission Control functionality

### ISSUE THREAD

**Issue by akella** [fifafu/BetterTouchTool#1537]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I can only trigger Mission Control right now. In native Mac OS method (three fingers down only) i can control speed of the Expose right now. Slowly swiping - gives me slow Mission Control.
Is it possible to do the same with BTT? Not to just run Mission Control by some hotkey, but to continually control its animation with 4-3 fingers swipes.
If they don't give external applications this possibility i can understand that.
And thank you for your great app!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.12.6
BetterTouchTool version:  2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, unfortunately Apple has no public API to do this, thus I can't integrate it into BTT :-(
