### ISSUE TITLE
Bug - Remove delay from actions when modifying external monitor brightness

### ISSUE THREAD

**Issue by aassaly** [fifafu/BetterTouchTool#154]
Overview:
BTT has 4 different screen brightness commands (raise/lower brightness, and raise/lower brightness of an external display). The issue I am reporting ONLY applies to the actions affecting the brightness of the external display.

#### Description of your bug/question/feature request...:
Raising/lowering brightness of an external delay action has some timing issues.

There is a long delay processing the action whenever I try to raise/lower the brightness multiple times (by tapping the action on the TouchBar several times). The action itself is recognized without delay, but the time it takes to process the action before the subsequent action occurs is very long. Basically BTT waits for the on-screen brightness HUD to fully finish changing brightnesses by 1 notch before processing the next command.

It would be nice if the command didn't wait for the action to finish, and simply processed the next action right away. This would remove my frustrations of waiting for the brightness to change several seconds after trying to do so.

I tried improving the situation by attaching additional actions to my action. I simply repeated the same action multiple times for each custom action I created (i.e. My raise external brightness command processes the BTT action "Brightness Up (External Display) 2 times in a row). This attempt to solve my problem didn't work either because BTT still waits for the first action to finish before starting the next.

Actions to raise/lower brightness of my built-in display seem to function properly without delays.

**What kind of Mac are you using?**
MacBook Pro 15" TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
TouchBar

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.2 (16C68)
BTT 1.971 (562)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Restarting my system or reinstalling BTT has no effect.

**Comment by fifafu** [comment]
Unfortunately this is not BTT taking too long, but the monitor. I can not fix this in BTT as BTT just calls a system action to change the brightness.
 You probably also got the LG 5k display?

**Comment by aassaly** [comment]
Yes, I have both of the LG Ultrafine Displays (4k and 5k).

I'm pretty sure if I had an external Apple keyboard I would be able to adjust the external displays' brightnesses with it, and that a delay wouldn't be experienced. I will buy one tomorrow to try it out and report back.

Too bad there is no way to natively adjust the brightness of external displays with the TouchBar.

**Comment by fifafu** [comment]
@aassaly I have the external Apple keyboard and the delay is there. It's a display/macOS issue!
