### ISSUE TITLE
Cant create touchbar button that opens terminal and executes SSH command

### ISSUE THREAD

**Issue by Lindwe** [fifafu/BetterTouchTool#1540]
Cant create touchbar button that opens terminal and executes SSH command. 

It opens the terminal but does not execute "ssh "host" -L 1333:localhost:8080"

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.6
BetterTouchTool version: 2.305

**Comment by EricWVGG** [comment]
I got this working. 

1. make a file called ssh-to-localhost.command
2. the contents of the file should be your connection command
3. chmod 0700 (of course)
4. make a BTT button, with Predefined Action: Execute Terminal Command
5. The terminal command should read: "open -a Terminal.app ~/ssh-to-localhost.command"

**Comment by fifafu** [comment]
If you are using the execute terminal command, try this:

"/usr/bin/ssh "host" -L 1333:localhost:8080"

Alternatively you can use an apple script action to trigger arbitrary commands in terminal

Running directly in background:
```
do shell script "echo test"
```

Opening a terminal and running the command there:
```
tell application "Terminal"
	activate
	do script "echo hello"
end tell
```
