### ISSUE TITLE
Touch Bar icons are stretched / Show dimensions for icon

### ISSUE THREAD

**Issue by EricWVGG** [fifafu/BetterTouchTool#1541]
A recent release of BTT has introduced inputs for icon width and height. Now many of my BTT icons are stretched because I didn't design them to 22x22.

1) Could you tell me where these icons are stored in the Library so I can dig them out and manually input the dimensions?

2) Perhaps a "get dimensions from PNG file" function might be useful?

**Comment by fifafu** [comment]
Hi Eric,

Easiest is to activate the "keep aspect ratio" checkbox in the general touchbar settings in BTT.

**Comment by EricWVGG** [comment]
That seems to lock the height to the aspect of the inputted width, but I don't know what the width of my button graphics are.

**Comment by fifafu** [comment]
The checkbox basically restores the old behavior so the icons should look like in the old versions if set to 22x22. Unfortunately the icons are only stored in a database not on the file system.

Are you using the default BTT icons or some custom icons you added?

**Comment by EricWVGG** [comment]
custom

**Comment by fifafu** [comment]
Sorry for not replying to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions, please create a new issue - I'm now much more responsive than a few months ago.
