### ISSUE TITLE
macOS High Sierra Touchbar resets to default (non-BTT) layout

### ISSUE THREAD

**Issue by phunkfoo** [fifafu/BetterTouchTool#1543]
#### Description of bug/feature request/question:
1. In "Preferences -> Keyboard" set:
    + "Touchbar Shows": "App Controls with Control Strip"
    + "Press Fn key to": "Expand Control Strip"
2. Setup a custom button for BTT with an associated action (I've setup "Lock Screen")
3. In BTT -> Advanced Settings, set "Disable BTT while holding" to "fn"
4. Save and test that button shows up and performs the expected action
5. Press Fn Key

Once the Fn key is pressed, the BTT modified touchbar never shows up again. Note: It is not disabled, and the touchbar just stays on the expanded Control Strip.

Workaround: setup a second custom BTT button and under the button's "Advanced Configuration" set it to "Only show when modifiers are pressed" (I've set it to Shift + CTRL [remapped to CapsLock on my device]). Once Shift + CTRL is pressed, the BTT customised touchbar is up again (and stays like that until I next press Fn).

This happens after upgrading Sierra to High Sierra in-place. I will test with a fresh install of High Sierra once I can get my hands on a usb-c pendrive or usb-c -> usb adapter (next couple days).

Fully aware that this might be an issue with my system and keen to test on a clean install.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar / Keyboard

#### Device information:

Type of Mac: 2017 MBPr 13"
macOS version: macOS 10.13 (17A365)
BetterTouchTool version: 2.307 (685)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

See workaround above.

**Comment by fifafu** [comment]
this should be fixed in v2.310!
