### ISSUE TITLE
fn button no longer displays expanded native touch bar when "Show BetterTouchTool Touch Bar, Hide System Control Strip" enabled, Mac OS 10.13

### ISSUE THREAD

**Issue by ifeign** [fifafu/BetterTouchTool#1544]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Pressing the fn button no longer displays expanded native touch bar when "Show BetterTouchTool Touch Bar, Hide System Control Strip." Worked flawlessly before I upgraded from the final version of Sierra.

Weirdly it does work when "Press fn key to show F1, F2, etc. Keys" but not with "Expand control strip"

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch bar

#### Device information:

Type of Mac: 2017 Macbook Pro 15"
macOS version: 10.13
BetterTouchTool version: 2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately that seems like a bug in 10.13.0, however Apple has already fixed it in 10.13.1 beta which should be released in 3-4 weeks to all users. I don't think there is anything I can do for now :-(

**Comment by ifeign** [comment]
Thanks for the clarification! It's really not a big deal, I just cmd-tab to
another app and back if I need the expanded controls. I think I can survive
3 more weeks of that lol.

**Comment by ifeign** [comment]
Just updated to 10.13.1, this issue persists.

**Comment by r3donnx** [comment]
Adding keyboard sequence with FN button assigned to "Toggle BetterTouchTool Touch Bar" action almost solved the problem. Now when I hold the fn button expended controls show up, when I release it switches the Touch Bar to default app controls and if I press fn once more it switches back to BetterTouchTool touchbar

<img width="1127" alt="screen shot 2017-11-09 at 10 07 05" src="https://user-images.githubusercontent.com/23448062/32595137-52f3980e-c537-11e7-82a4-a3bc4bd89021.png">
