### ISSUE TITLE
Competition between the Calendar.app and the BetterTouchTool

### ISSUE THREAD

**Issue by freeway1118** [fifafu/BetterTouchTool#1545]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Competition between the Calendar.app and the BetterTouchTool:

Type of Mac: MacBook, iMac
macOS version: Mac OS Siera 10.12.6
BetterTouchTool version: 2.304(682)

#### Additional information:
I have been struggling to cure a certain bug when I use the default Calendar App.  It is difficult to explain the situation so that please see the below URL which is describing the situation of this issue. Once I open a task on my calendar, then cursor automatically generate the new item without any indication no sooner than I clicked the cursor on the arbitrary point in the calendar field. Further worse, this new item cannot close, showing the caution: "Calendar was unable to save changes to the event", and also multiply the same type of the null calendar items whenever I click on anywhere in the calender field until I turn the Calendar App down.

[![Screenshot from Gyazo](https://gyazo.com/eb7c6ff1e0d39802d4caf4e2fcc61216/raw)](https://gyazo.com/eb7c6ff1e0d39802d4caf4e2fcc61216)

Today, I decided to ask the way of how to reveal this frigging issue to Apple Customer support, then they suggested me to make another account tentatively to check if this test account will also show the same issue. The result was that no similar issues were found, so we decided that the reason might be the other apps those open when I log into my account. Then, they asked me to delete the StartupItems folder in the right under the Library folder in the Macintosh HD as those seem the cause of this problem. After restarting my Mac to see if the same issue will occur or not, and unfortunately, it occurred.

They wondered a little, then directed me to close all the apps, which are to be opened automatically at the time when I log-in, registered in the Users&Groups field in the System Preferences. Once I closed all of them, this symptom ceased. Then trying to select the app one by one to see which one is the cause of this issue, then finally we realized that the BetterTouchTool was the one causing this symptom.

I am Tosh, and my email address: freeway1118@outlook.com was licensed by BetterTouchTool. I was really relying on the function of BetterTouchTool, so please check whether the identical situation happens or not, and heal it. 

Thanks and Sincerely

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I'll try to reproduce this. For now you can just click the BTT menubar icon and select "disable for active app" (it will remember that decision)

**Comment by freeway1118** [comment]
Thanks, wait for your update.

**Comment by fifafu** [comment]
Mhh I can't seem to reproduce this. Maybe it's fixed on macOS High Sierra?

**Comment by freeway1118** [comment]
It seems like YES, OS High Sierra relieves this issue. Thank you for your cooperation.
