### ISSUE TITLE
Export Import settings loose icon size settings

### ISSUE THREAD

**Issue by jeanfabre** [fifafu/BetterTouchTool#1546]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When you export and reimport a touchbar setup, the icon sizes all reverts to default 22*22

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
TouchBar

#### Device information:

Type of Mac: MacBook Pro 2017
macOS version: 10.12.6
BetterTouchTool version: 2.304 (682)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should be fixed with the latest alpha! Thanks for reporting!
