### ISSUE TITLE
Safari pinch in gesture on macOS High Sierra

### ISSUE THREAD

**Issue by kuglee** [fifafu/BetterTouchTool#1548]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Safari uses the pinch in gesture to show all tabs and it interferes with the pinch in gesture of BetterTouchTool. Sometimes the gesture works sometimes it doesn't.
Note: It was working fine in macOS Sierra.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Air 13" Early 2015 trackpad

#### Device information:

Type of Mac: MacBook Air 13" Early 2015
macOS version: Sierra 10.13.0
BetterTouchTool version: 2.305 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
It seems to work fine here, however I'm already on 10.13.1 beta, so maybe Apple has fixed something already.
