### ISSUE TITLE
Touch bar doesn't send modified keys

### ISSUE THREAD

**Issue by jbarfell** [fifafu/BetterTouchTool#1549]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When configuring button on touch bar to send key shortcut keys such as option-F11 only F11 is sent, no option modifier.  The specific application is vm fusion 8.5 in full screen mode.  Tried setting shortcut keys and setting touch bar to those.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12.16
BetterTouchTool version: 2.301 (679)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry unfortunately that's an issue with VMWare Fusion which ignores the modifier keys. BTT is sending them correctly.

**Comment by fifafu** [comment]
#121
