### ISSUE TITLE
TipTap Middle is a hit and miss on new MacBook Pro

### ISSUE THREAD

**Issue by AuroraWright** [fifafu/BetterTouchTool#155]
#### Description of your bug/question/feature request...:
The TipTap Middle (2 fingers fix) gesture works rarely on the trackpad of the late 2016 MBP. I attached a few "live view" screenshots of cases where it doesn't get detected. I also reset all my settings except for the gestures/touchbar buttons. The gesture works reliably on my old 2010 MBP instead.

**What kind of Mac are you using?**
2016 15" MacBook Pro
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Builtin Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2, BTT 1.974

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
http://imgur.com/a/OOS4k

**Comment by fifafu** [comment]
Do you still encounter issues with the two finger tip taps? For me they seem to work fine with the new MBP.
