### ISSUE TITLE
BTT Unexpected Tab Behavior

### ISSUE THREAD

**Issue by ediskrad73** [fifafu/BetterTouchTool#1550]
#### Description of bug/feature request/question:
With BTT on, my tabs with TotalFinder do not respond properly. I've disabled BTT and TotalFinder, and BTT seems to be the culprit. I use the "Disable BetterTouchTool while holding" option and the behavior ends immediately, so there must be something with BTT that doesn't play nice with TotalFinder. 

I cannot find any setting in BTT that would cause this. I've reset all settings several times, reinstalled BTT and TotalFinder. It only happens on clicks, not taps.

See video below for example. Tabs will stick to the bar and cursor, overlap, not respond at all. I've reached out to the dev of TotalFinder and they have no clue what's going on, so I thought I would try here.

Any sort of workaround or resolution would be appreciated. Both of these apps are must-haves on my machine and I don't want to compromise one for the other.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad click only. Not taps.

#### Device information:

Type of Mac: MacBook Pro 2017 15"
macOS version: 10.13 High Sierra
BetterTouchTool version: 2.307 (685)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screen capture:
https://www.youtube.com/watch?v=iUEVwVHH7So

**Comment by fifafu** [comment]
I think this might be fixed with the upcoming version (>= 2.312). In case it still happens after the release, please comment again.
