### ISSUE TITLE
Single finger force click

### ISSUE THREAD

**Issue by theonlygusti** [fifafu/BetterTouchTool#1555]
I don't care if the left click can be blocked or not

**Comment by fifafu** [comment]
Unfortunately it's also not possible to block the default force click action. But maybe I'll add it at some point regardless of the issues. However I'll be closing here as there are already multiple discussions about this.

**Comment by fifafu** [comment]
I have added it with the latest alpha (2.315). It works great as cmd+click to open a new tab in browsers :-) (although many use cases are tricky to realize because of the mentioned left-click that always happens)
