### ISSUE TITLE
Clicks in chrome not registering......

### ISSUE THREAD

**Issue by collinbell** [fifafu/BetterTouchTool#1556]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
chrome requires multiple clicks to register action. Thought it was a browser issue and after multiple restarts of browser, computer and BTT no resolution. Finally quit BTT altogether and issue no longer exists.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
mouse

#### Device information:

Type of Mac: 13" MBP with touchbar, 2016 with four thunderbolt usb-c ports
macOS version: 10.12.16
BetterTouchTool version: 2.305 (and previous version, updated to see if there was already a fix)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #1445
