### ISSUE TITLE
Shift + Scroll Down triggers "Scroll Right" action

### ISSUE THREAD

**Issue by shillem** [fifafu/BetterTouchTool#1557]
#### Description of bug/feature request/question:
The click wheel button is identified as "Scroll Right". I mapped Mission Control to this button.

But when I use SHIFT + Scroll Down (to scroll horizontally) Mission Control is triggered, but not when I use SHIFT + Scroll Up (horizontal scrolling is triggered correctly).
If I remove the "Scroll Right" action from BTT then I'm able to scroll horizontally both ways.

In the screenshot are the only 4 actions I mapped.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Logitech M720 Triathlon

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.13
BetterTouchTool version: 2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![screen shot 2017-09-28 at 14 04 55](https://user-images.githubusercontent.com/5537484/30965556-10ed6aa4-a456-11e7-90f9-6f519e3d0393.png)

**Comment by shillem** [comment]
Hmm, I just realized it's what BTT reads from the buttons clicked on the mouse. It's the click wheel button that doesn't have a specific button number and sends Scroll Right, am I right?

**Comment by fifafu** [comment]
Yes you are probably right. Is there maybe an option in your mouse driver to change the function of the scroll buttons?

**Comment by shillem** [comment]
There would be the [Logitech software](http://docs.bettertouchtool.net/docs/normal_mice_problems.html) but I don't fell like installing any of that just to enable a couple more of buttons. I prefer to keep it like that. It's really sad that Logitech removed something that was working before...

Anyway I believe that this issue can be marked as resolved
