### ISSUE TITLE
Unwanted movement in SketchUp 2017

### ISSUE THREAD

**Issue by BodeyM** [fifafu/BetterTouchTool#1559]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm running SketchUp 2017. When I click on a button on the control bar of SketchUp, the 3D view starts being drug upwards. When BTT is disabled for SketchUp this does not happen.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

ForceTouch Trackpad

#### Device information:

Type of Mac: 2016 MacBook Pro with TouchBar
macOS version: Sierra
BetterTouchTool version: 2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here is a screen capture of the issue: https://www.youtube.com/watch?v=2QY9NEe72jw

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I can reproduce this, however it seems to be a bug in sketchups event handling.

For now disable BTT for sketchup (Click the BTT menubar icon and select disable for current application, it will remember that decision)

**Comment by BodeyM** [comment]
Cool. Thanks for looking into it.
