### ISSUE TITLE
BTT launch calls non-existent server, issues warnings.

### ISSUE THREAD

**Issue by keypress** [fifafu/BetterTouchTool#1560]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

On boot or BTT (re)start, or when selecting BTT preferences:  A system dialogue appears twice, claiming: "There was a problem connecting to the server "<server name>”. The server may not exist or it is unavailable at this time. Check the server name or IP address, check your network connection, and then try again."

True, the local server no longer exists. Seven MM2 gestures are used with standard assigned actions. I can find no references to this or any server in BTT settings. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse 2

#### Device information:

Type of Mac: iMac (27-inch, Mid 2010), Magic Mouse 2 
macOS version: Mac OS Sierra 10.12.6 
BetterTouchTool version: 2.304(682)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

BTT functions OK only after clearing the 2 system dialogues.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mhm, BTT doesn't connect to any server but to my update server and that wouldn't cause such a message.

Do you maybe have (maybe in the past) connected to network shares that may still be registered somewhere? As BTT calls various system APIs on launch it's possible that one of them tries to find some system files on a now non-existing network drive or something like this?

**Comment by keypress** [comment]
Thanks for your reply.

I looked for those stale connections everywhere without success to narrow this down to BTT.  Do you have a list of likely APIs I could reference to look further? BTT raises those dialogue boxes when the Mac is woken up, too, if that helps narrow things.

**Comment by fifafu** [comment]
Mhh, maybe it's related to the login items.
Could you check whether there are some items marked with a warning sign in System Preferences => Users & Groups => Login Items

**Comment by keypress** [comment]
This appear to have corrected the problem.  Thank You!
