### ISSUE TITLE
 TouchBar Button Color - Does not save correct inputed color 

### ISSUE THREAD

**Issue by ianizaguirre** [fifafu/BetterTouchTool#1562]
---

#### Description of bug/feature request/question:
When you click "Advanced Configuration" for a TouchBar button and then click TouchBar Button Color and input a Hex Color # or an RGB color # and then click "Save"... as soon as you reopen the TouchBar Button Color to check if it saved correctly - it shows a slightly different Hex color # or RGB color # from the color I just originally inputted.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TouchBar

#### Device information:

Type of Mac: Pro (15 -inch, 2017)
macOS version: macOS Sierra / Version 10.12.6 
BetterTouchTool version: **2.297** **AND** after I updated, it is still a problem on the current **2.305**

---

**Comment by fifafu** [comment]
Thanks this will be fixed in the next update! (using different color space)
