### ISSUE TITLE
3 Finger Force Click not working under high Sierra when using BTT. Works without BTT

### ISSUE THREAD

**Issue by knurrrrrrt** [fifafu/BetterTouchTool#1563]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

3 Finger Force Click not working under high Sierra when using BTT. Works without BTT

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad

#### Device information:

Type of Mac: Mac Pro Trashcan
macOS version: 10.13
BetterTouchTool version: 2.308

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
What does a 3 Finger Force click do without BTT? Just the same as a 1 finger force click?

**Comment by knurrrrrrt** [comment]
Hi Andreas, was ich meinte ist, dass es kein force feedback gibt und auch die in BTT dafür angelegte Aktion nicht ausgeführt wird.

LG, Knut

**Comment by fifafu** [comment]
Unfortunately I can't seem to be able to reproduce this :-(
You are not using a Hackintosh setup, correct? (because I have had one similar report for a user with a hackintosh).

Could you check whether your force click settings look like in this screenshot?
![image](https://user-images.githubusercontent.com/8820811/31056093-b1e36184-a6cc-11e7-8dde-a7dad331b8c5.png)

**Comment by fifafu** [comment]
Let's continue to track this here, as the issues may be related: #1558
