### ISSUE TITLE
Live View - "Last Recognized Gesture" not showing any gestures as recognised

### ISSUE THREAD

**Issue by redyetidave** [fifafu/BetterTouchTool#1564]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Using the Live View, the "Last Recognized Gesture" doesn't show anything at all as being recognised so it's hard to test:

https://gyazo.com/cdf3fa4c75390af222d774eb0d05e284

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: Mac OSX Sierra 10.12.6 (16G29)
BetterTouchTool version: 2.304 (682)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have configured any gestures for the Magic Mouse in BTT? This seems to work fine here.

**Comment by redyetidave** [comment]
I have 1 gesture Magic Mouse. Global. 3 Finger Click -> Middle Click (this is all that I use BTT for but it's worth it!).

I've attached the Default.json file.

I have just done a full uninstall of BTT using Clean My Mac to delete all Plists etc. Then reinstalled.

No change.

As a _possibly_ related note: I've also been driven half mad for the last day due to many left-single-clicks not registering. Around 10% of the time I click and the click event isn't registered (at least, in Chrome). It's very hard to reproduce but after quitting BTT the problem goes away. However... now that I've reinstalled it doesn't seem to be happening. This seems to have convinced with the new version of BTT.

[Default.txt](https://github.com/fifafu/BetterTouchTool/files/1344847/Default.txt)

**Comment by fifafu** [comment]
I have added a workaround for the Chrome bug (https://bugs.chromium.org/p/chromium/issues/detail?id=763642&q=click&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified ) with the latest BTT version.

Unfortunately Three Finger Click => Middle Click is one of the only combinations that can not be shown in the live view because its recognition is done by a different system than the other gestures. ;-(

**Comment by redyetidave** [comment]
The Chrome bug is great to have a work around for! Thank you very much! :)

Re. the original problem (Live view not reporting gestures); I assumed that standard things like "left click" were expected to be reported. But am I right that actually it only shows any custome gestures which have been configured?
