### ISSUE TITLE
Magic Mouse 2 left click erratic response on Sierra MBP 2016

### ISSUE THREAD

**Issue by beltersdream** [fifafu/BetterTouchTool#1565]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Left click not working with precision, most times have to click twice. Works fine without BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MBP 2016 15" with Sierra. Magic Mouse 2.

#### Device information:

Type of Mac: MBP 2016 15"
macOS version: Sierra
BetterTouchTool version: 2.305 (683)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by clayb** [comment]
I've been experiencing this same issue since the last BTT update.

**Comment by mikrohard** [comment]
I also had this issue (mostly on chrome right after mouse movement). But I can also confirm that it seems to be fixed by installing the latest alpha (2.308).

**Comment by fifafu** [comment]
You probably encountered this Chrome bug: #1445
