### ISSUE TITLE
"Rectangles ?" issue

### ISSUE THREAD

**Issue by Loic3012** [fifafu/BetterTouchTool#1566]
#### Description of bug/feature request/question:

How to remove these type of rectangles when I move a window ? It's like window snapping, I disabled all this in the preferences but it still remains.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Screen

#### Device information:

Type of Mac: Macbook pro 15-inch Late 2016
macOS version: Mac os High Sierra 10.13
BetterTouchTool version: 2.308

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Link to the video of my problem : https://streamable.com/f38n4

---

**Comment by fifafu** [comment]
Hey,

you have added custom snap areas. To delete them click the btt menubar icon, go to snap areas and click edit snap areas. Then click the big x button every area you want to delete.

Alternatively you can reset them in the advanced preferences
![image](https://user-images.githubusercontent.com/8820811/31045267-0977b5b4-a5e0-11e7-81a6-e7c3372caf4d.png)
