### ISSUE TITLE
PLAY/PAUSE iTunes Vs Youtube (safari)

### ISSUE THREAD

**Issue by GitHubswn** [fifafu/BetterTouchTool#1567]
PLAY/PAUSE for iTunes and YouTube interfering 
Can we add a 'Predefined Action' for iTunes now? 
---

#### Description of bug/feature request/question:

I have set up PLAY/PAUSE in Global from 'predefined Action' but it loos like High Sierra changed how it handles PLAY/PAUSE. Now when I gesture play/pause it plays or pauses videos on YouTube instead of iTunes, regardless if I'm on Safari or other applications.

**** I actually like this changed, but I would also want a Global 'predefined Action' for iTunes? 

#### Device information:

Type of Mac: Early 2013
macOS version: 10.13  High Sierra
BetterTouchTool version: 2.308

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can use the "Run Apple Script" action and use this script:

```
tell application "iTunes"
	playpause
end tell
```
