### ISSUE TITLE
Touchbar close (x) button moves the esc key when the BTT touchbar is active. 

### ISSUE THREAD

**Issue by phuibonhoa** [fifafu/BetterTouchTool#1568]
#### Description of bug/feature request/question:
When the better touch tool touchbar options are showing, a close button on the touch bar (to return to the default touch bar buttons) is displayed on the far left on the touchbar.  This means the esc key is moved to the right.  It would be nice to move the close button to the right-side or at least have the option.  

For those of us who hit esc a lot, having the esc key sometimes moved to the right is annoying enough, that it stops me from using the custom touchbar features that BTT enables.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 13' MBP
macOS version: 10.13
BetterTouchTool version: 2.304

**Comment by fifafu** [comment]
This is not possible due to api limitations.
Only option to get rid of the close button is to hide the macOS control strip in the BTT general touchbar settings
