### ISSUE TITLE
Keyboard shortcuts for hold instead of single press.

### ISSUE THREAD

**Issue by krishnakumar-kapil** [fifafu/BetterTouchTool#157]
#### Description of your bug/question/feature request...:
I currently use caps lock as control and am trying to get vim setup for hjkl as arrow keys. What happens is that if i hold them they don't continue performing the action as if I would if holding the arrow keys. 
![image](https://cloud.githubusercontent.com/assets/9093134/21447210/4e598b24-c8f7-11e6-843b-d21efec0e3a9.png)

**What kind of Mac are you using?**
I am using MacBook Pro (Retina, 13-inch, Mid 2014)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Keyboard

**Which versions of macOS and BetterTouchTool are you running?**
Sierra and 1.963

**Comment by krishnakumar-kapil** [comment]
https://github.com/fifafu/BetterTouchTool/issues/120

Oops...

**Comment by fifafu** [comment]
Sorry for not replying earlier. 
You need to enable key repeat like in this screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/24304708/a4aaf516-10ba-11e7-812d-b0f6b247ade5.png)
