### ISSUE TITLE
BTT remote not finding mac laptops

### ISSUE THREAD

**Issue by ast03** [fifafu/BetterTouchTool#1570]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
My BTT remote on my iphone or another iphone i use wont find my mac or another mac i tried. I tried manually entering the IP and port with no success. Not sure what changed. All four devices have the latest update for BTT. same wifi. tried restarting all four devices. Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macs and iphones

#### Device information:

Type of Mac: macbook pro
macOS version: 10.9.5 for one mac and 10.12.4 for the other
BetterTouchTool version: 2.05(605) for one mac and 2.305(683) for the other

the iphones have the latest BBT app

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Has something changed with your wifi setup? Sounds like something is blocking the connections? (Firewall or Router)

**Comment by ast03** [comment]
Thank you for the quick reply. I have not changed anything regarding my router or wifi. I don't think I have any firewalls besides what comes standard with my mac and its set to allow all connections from BTT. I'm trying it now on a completely different wifi network with no luck still so i don't think it's router related. I can't think of what has changed.

**Comment by ast03** [comment]
I went to system preferences, network, wifi, advanced, TCP/IP, and changed configure IPv4 from 'using DHCP' to off. applied the changed, turned wifi off and back on, and then changed the configure IPv4 back to "using DHCP'. idk what that changed exactly but it worked.

**Comment by fifafu** [comment]
Maybe the network stack was somehow in a weird state and got reset by that! Glad you got it resolved and thanks for letting me know how you did it!
