### ISSUE TITLE
Buttons calling Function Keys fail

### ISSUE THREAD

**Issue by jetbootjack** [fifafu/BetterTouchTool#1574]
#### Description of bug/feature request/question:

I have created a couple of application specific touch bar layouts - using them with Crossover and some emulation software.

Each custom button is a custom keyboard shortcut to an F-key.

All the F-keys work just fine when I use them in the touch bar - but my custom short cuts only partially work, some shortcut keys (once calling F5, F9 work just fine) - others do not. 

it appears that if the F-Key is a menu item then the shortcut works (so F5 is the shortcut to Reset, or F9 is Menu) - those keys not referred to in the applications menus seem not to work.

But the F-keys always work just fine if I use tree F-key Touch Bar itself - so the system is recognising the keys, but just not when I create a custom button for them...

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 14,3
macOS version: 10.13.1
BetterTouchTool version: 2.308

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

The assignment of F keys:

![btt f-key](https://user-images.githubusercontent.com/6617872/31093296-2e80de74-a7a9-11e7-8c96-fe61dcdd5bd7.jpeg)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by jetbootjack** [comment]
I have now noticed this behaviour in native mac applications too - custom buttons as custom keyboard shortcuts to an F-key seem unreliable - some work, some do not  (in Boxer or FSUAE or CocoaMSX).

But if I create global versions of custom buttons as custom keyboard shortcuts to an F-key they work - just not app specific ones...

**Comment by fifafu** [comment]
Weird. Are you pressing any modifier keys while touching the buttons? (E.g. CMD or Shift)

**Comment by jetbootjack** [comment]
No modifier keys, just standard F-keys seem totally hit and miss.

One other thing I have noticed is that if I create a global Touch Bar Button and assign the Custom Keyboard Shortcut to F1 then go to system preferences/keyboard/input sources pressing the custom button does nothing.

And by that I mean in system preferences/keyboard/input sources holding fn and pressing F1 causes the audio ”donk” and the top row of F-keys to appear in the keyboard image window - pressing the custom shortcut cause the “donk” sound, but no keyboard image change. Any F-key I assign to a custom touchbar button has the same behaviour.

sTeVE

**Comment by jetbootjack** [comment]
Any ideas on this issue - I want to use BTT and am only held back bu this issue and cannot see any workaround...

I also see this issue "Using BTT escape key functionality problems. #1621" which look to be in a similar ballpark as mine perhaps?

sTeVE

**Comment by fifafu** [comment]
Unfortunately I haven't been able to reproduce this. F Keys seem to be working fine here.

Here is one example (you can copy & paste the json into BTT)

```
{
  "BTTTouchBarButtonName" : "F1",
  "BTTTriggerType" : 629,
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShortcutToSend" : "122",
  "BTTEnabled" : 1,
  "BTTOrder" : 1
}
```

**Comment by jetbootjack** [comment]
So my weirdness continues - on my non Touch Bar iMac I can copy and paste your sample into BTT - on my MacBook Pro I cannot copy and paste it!!

Both are running 10.3.2

sTeVE

**Comment by jetbootjack** [comment]
Okay so I figured that out - and got it pasting okay, no idea what went wrong last week :-)

That example you gave does not work for me in any of the specific apps that I want to create custom Touch Bar strips for, but standard "fn key + f1" gives me a valid F1 input...

However in finder and elsewhere the F1 shortcut you supplied works just fine - in Safari for instance, as do the ones I create...

I am so very confused, is this some issue with WINE and BTT - but then why does it misbehave the same way in other apps like kat5200 too, which is a native OSX app?

sTeVE

**Comment by fifafu** [comment]
This is a more general issue with some apps that don't use the default keyboard APIs. I'm currently working for a fix that should work in all instances. I'm closing here as this is not directly related to Function Keys etc.. It should be solved soon.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I wasn't able to solve/reply to this earlier.

**Comment by jetbootjack** [comment]
Fantastic - good to hear!

And no need to apologise - BTT is great, glad you’ve gotten to the bottom of the problem!

sTeVE
