### ISSUE TITLE
Mouse Drag Events carry over from one window to another

### ISSUE THREAD

**Issue by ben174** [fifafu/BetterTouchTool#1578]
#### Description of bug/feature request/question:

Seems related to #1445 - but since that issue is closed as resolved, and this isn't completely Chrome-specific, I figured it was worthy of a dedicated issue.  

##### Steps to reproduce:

1. Launch Terminal.app and Chrome side by side.
2. Give Terminal.app focus
3. Click and drag on your Chrome window to give it focus.

##### Behavior without BTT running:

Chrome gets focus, Terminal.app remains in its current state.

##### Behavior with BTT running:

Chrome gets focus, Terminal.app text becomes highlighted in the window range in which the drag occurred in the Crome window. e.g. if I click and drag 50%-75% vertically in the Chrome window, the terminal will become highlighted in that same area. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse 2

#### Device information:

Type of Mac: MBP 2017 Touch Bar 13"
macOS version: Sierra
BetterTouchTool version:  2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I can create a screen capture video if necessary. The problem is quite easy to reproduce.

**Comment by ben174** [comment]
I believe this is related to the 'Shake mouse pointer to locate' accessibility option. As a temporary fix, disable this option in System Preferences -> Accessibility

**Comment by ben174** [comment]
Yea I've confirmed this is a bug which occurs when the mouse cursor gets big. If you open up System Preferences -> Accessibility -> Display and increase the 'Cursor Size' option to max - things start to spaz out pretty bad. If you turn off BTT, it works normally.

**Comment by fifafu** [comment]
I'll continue to track this issue here: #1580
