### ISSUE TITLE
Touch Bar Visual Bug  

### ISSUE THREAD

**Issue by aaronweewee** [fifafu/BetterTouchTool#158]
#### Description of your bug/question/feature request...:
There is a bug that causes old touch bar visuals to permanently remain there even after restarting my mac and BTT

I've included screen shots and marked it out with red lines and dots to show the problem. Parts marked red are not suppose to be there. It is a visual bug as those buttons do not function and they belong to a different set of presets or are for different apps. 

**What kind of Mac are you using?**
MacBook Pro 13-Inch, Late 2016 touch bar model
Processor: 3.1 GHz INtel COre i5
Memory: 16GB
Graphics Intel Iris Graphics 550 1536 MB

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.2
BTT: 1.975

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
<img width="1085" alt="touch bar shot 2016-12-23 at 2 46 08 pm" src="https://cloud.githubusercontent.com/assets/24728980/21448620/c4d6d6d0-c91f-11e6-8b88-fcf830be82ef.png">
<img width="1085" alt="touch bar shot 2016-12-23 at 2 43 14 pm" src="https://cloud.githubusercontent.com/assets/24728980/21448621/c4db6a10-c91f-11e6-98fa-3ab0756a09b3.png">

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
That's weird. Does this happen all the time? Or after doing something specific

**Comment by fifafu** [comment]
Could you maybe send me an export of your settings to boastr.net@gmail.com or attach it here? (via the preset export button in the preferences)

**Comment by aaronweewee** [comment]
Alright, here it is

It happen right after i updated from 1.970 to 1.975.
I re installed BTT as well back to 1.96x and it was fine, upon updating to now 1.976 the problem re occured again.

I am unsure of what triggers it, usually its when im switching back to chrome from another app. There are instances where it will be perfectly fine after switching from one app to another though, but its very seldom, about 1 in 50 times. 

[BTT Chrome.zip](https://github.com/fifafu/BetterTouchTool/files/670435/BTT.Chrome.zip)

**Comment by fifafu** [comment]
Very weird # I'll look into it this evening!

**Comment by aaronweewee** [comment]
I've tried to recreate a new Preset to check for reoccurrence, and it seems that the bug occurs once I've selected 
Chrome> App specific > Touch Bar behaviour > Show BTT, Hide Control strip.

I've also noticed that it sometimes bringing up images from other presets stored, or the "You have not configured anything..." icon.

I've included a new screen shot which highlights the bug again. 
Hope you guys can fix it, this is truly a wonderful app :))

When touch bar behaviour is set as "Default"
<img width="1085" alt="touch bar shot 2016-12-23 at 4 41 18 pm" src="https://cloud.githubusercontent.com/assets/24728980/21450081/a6ee87ee-c92e-11e6-9267-03577b31d9b5.png">

Set as "Show BTT, Hide control strip"
<img width="1085" alt="touch bar shot 2016-12-23 at 4 39 25 pm" src="https://cloud.githubusercontent.com/assets/24728980/21450060/71e0a74e-c92e-11e6-9fda-3782d75c5fef.png">



Hope this helps, all the best!!

**Comment by R-V-S** [comment]
I just ran into this issue on updating to 1.976. Using macOS 10.12.2.

Note the "You have not yet configured actions in BetterTouchTool" message peeking out from beneath my buttons for Chrome:

![image](https://cloud.githubusercontent.com/assets/253313/21457095/9383bd8e-c8fa-11e6-93f9-c3ed38824acf.png)

**Comment by fifafu** [comment]
Thank you! I'm currently working on the fix :-)

**Comment by fifafu** [comment]
Would be great if you could test v1.977

**Comment by R-V-S** [comment]
v1.977 seems to be working well on my end. Thanks!

**Comment by aaronweewee** [comment]
Yup, it seems to be pretty good on 1.977, wow thanks for such a quick fix :)))
