### ISSUE TITLE
Muse control strip icon not displayed

### ISSUE THREAD

**Issue by mickaelperrin** [fifafu/BetterTouchTool#1581]
#### Description of bug/feature request/question:

* Control strip BTT icon overwrite the control strip Muse icon app.
* BTT hangs randomly when trying to display Muse icon app.

This happens only if the option Show BetterTouchTool Icon in Control Strip is checked.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MBP 2016 TB
macOS version: 10.12.6
BetterTouchTool version: 2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[Muse](https://github.com/xzzz9097/Muse) is an awesome TouchBar icon that allows to quickly control Spotify.
![Muse](https://raw.githubusercontent.com/xzzz9097/Muse/master/Screenshots/TouchBar.png)

Like BTT it normally adds a control strip icon
<img width="1085" alt="capture d ecran touch bar 2017-10-04 a 16 22 41" src="https://user-images.githubusercontent.com/5844226/31180986-6cfe378c-a920-11e7-990d-178cfea414d5.png">

**Comment by fifafu** [comment]
Unfortunately there can only be one icon in that place, this is a system limitation and not fixable as far as I know.
