### ISSUE TITLE
Feature request: Move all windows of the active app to another space/display

### ISSUE THREAD

**Issue by juliaanvaneijndt** [fifafu/BetterTouchTool#1582]
#### Description of bug/feature request/question:

I'd like to be able to move all windows of the active app to another space/display at the same time (this would be useful when connecting to an external display); I thought that the `Dock Options > Assign to` would work, but I couldn't figure how to do it…

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

I was thinking of a shortcut but any input device would be nice

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2016, Touch Bar)
macOS version: 10.13
BetterTouchTool version: 2.304

**Comment by fifafu** [comment]
Unfortunately there is no (public) API that would allow me to do something like this as far as I know. I'm not sure whether there are undocumented functions in macOS that could do this, but currently I don't know any :-(

I'm closing here for now, but will reopen in case I find anything
