### ISSUE TITLE
Feature request: Insert Emoticons into "Insert/Paste/Paste custom text" text field

### ISSUE THREAD

**Issue by patrickmast** [fifafu/BetterTouchTool#1585]
Can we have the option to add real Emoticons in the "Insert / Paste / Paste custom text" text field?

![2017-10-07_18-27-29](https://user-images.githubusercontent.com/424387/31309849-5c168176-ab8d-11e7-8e3b-14a3231450e0.png)

**Comment by fifafu** [comment]
You should be able to do this by pressing opt+cmd+space to show the emoji keyboard.

**Comment by patrickmast** [comment]
Sorry, does not work here. I also have a Emoji-button on the Touch Bar, but it also does not trigger the emoji keyboard in that text field.

**Comment by fifafu** [comment]
Weird, I'll check that!

**Comment by patrickmast** [comment]
Thanks! I hope this can replace my TextExpander settings.

**Comment by fifafu** [comment]
Fixed in upcoming version.

**Comment by patrickmast** [comment]
Yes, pasting emojis works OK. Typing them , not yet.
