### ISSUE TITLE
[Feature Request] Silent volume increment

### ISSUE THREAD

**Issue by Sir-Cumference** [fifafu/BetterTouchTool#1587]
Normally, pressing shift + volume up/down will increment the volume silently. This is perfect if my volume is too high (and thus the "pop" sound would hurt my ears) or if I'm listening to music and do not want the "pop" to distract me. Disabling the feedback sound altogether would make it hard to find the right volume.

I was wondering if you could allow us to silently increment the volume through keyboard shortcuts, gestures, etc. Right now, if I have a gesture/shortcut for increasing the volume, holding shift will not silence it.

Thanks.

**Comment by fifafu** [comment]
Hey,

you can use the "Run Apple Script" predefined action to do this.
Using a script like this:

```
set theOutput to output volume of (get volume settings)
set volume output volume (theOutput + 6.25)
```

And this
```
set theOutput to output volume of (get volume settings)
set volume output volume (theOutput - 6.25)
```

There are probably better scripts, it should be easy to find them via google
