### ISSUE TITLE
[Feature Request] Hide window under cursor

### ISSUE THREAD

**Issue by yahyavi** [fifafu/BetterTouchTool#1588]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hide window under cursor. There is an option to minimize/maximize windows under cursor. But not hide the window (as in CMD+H ). This will allow switching to hidden apps using the application switcher. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Tried it on trackpad.

#### Device information:

Type of Mac: Macbook Pro
macOS version: High Sierra
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by xInstead** [comment]
You can create it yourself.
Assign any gesture to the predefined action "Activate/Bring to Front Window Under Cursor" and attach an additional action with "CMD+H" as keyboard shortcut.

**Comment by yahyavi** [comment]
Thanks. Yes, that solves it. 
But I still think it would be good to have it as one of the default interactions with a window just like minimize and maximize.

**Comment by xInstead** [comment]
Well, it's basically the same.
You can actually adjust almost all of your gestures like this. I did it and the workflow feels great. I do less clicking, thinking or worrying since I'm triggering actions directly under the cursor in the windows or apps I aim for.
