### ISSUE TITLE
Spotify and iTunes track names on Touchbar

### ISSUE THREAD

**Issue by Tompz** [fifafu/BetterTouchTool#1589]
Hi all,

Just a quick ask - as I've just used the threads on here with great results so far:

Is there any way to have the Artist and Track name as scrolling text please?

I really like the idea of being able to limit the size of touchbar info by number of characters displayed, but would love to have the info scrolling.

Code I used on BTT:

```
tell application "System Events"
	set num to count (every process whose name is "iTunes")
end tell
set maxSize to 20

if num > 0 then
	tell application "iTunes"
		set playState to (player state as text)
		if playState is equal to "playing" then
			set trackName to name of current track
			set artistName to artist of current track
			set albumName to album of current track
			if length of trackName is greater than maxSize then
				set trackName to text 1 thru (maxSize - 3) of trackName & "..."
			end if
			if length of artistName is greater than maxSize then
				set artistName to text 1 thru (maxSize - 3) of artistName & "..."
			end if
			set trackInfo to trackName & " | " & artistName
		else
			set trackInfo to ""
		end if
		return trackInfo
	end tell
else
	set trackInfo to "iTunes close"
	return trackInfo
end if
```
Thanks in advance!

**Comment by fifafu** [comment]
Unfortunately scrolling text is currently not possible. I'll see if I can add it with an upcoming update, but I'm not sure yet.

**Comment by Tompz** [comment]
Thanks for the response, I did have it scrolling beforehand but needed to shorten the string.

**Comment by brantwedel** [comment]
You can use apple script string operations to "scroll" any text once a second (set update in BTT to under 0.5s for best results) ... keep in mind this means your entire applescript needs to run very often and could reduce performance, etc.:
```
set stringToScroll to trackInfo # the tex you want to scroll
set speed to 2 # letters per second
set maxLength to 16 # max letters

if length of stringToScroll < maxLength then
	return stringToScroll
end if

set stringToScroll to stringToScroll & " ... "
if (maxLength < length of stringToScroll) then
	set maxLength to (length of stringToScroll) - 1
end if

set t to (time of (current date))
set p to (t * speed) mod (length of stringToScroll)

return (text (p + 1) thru ((p + 1) + maxLength) of (stringToScroll & stringToScroll)) & "..."
```







Usage in above example:
```
tell application "System Events"
	set num to count (every process whose name is "iTunes")
end tell
set maxSize to 20

if num > 0 then
	tell application "iTunes"
		set playState to (player state as text)
		if playState is equal to "playing" then
			set trackName to name of current track
			set artistName to artist of current track
			set albumName to album of current track
			if length of trackName is greater than maxSize then
				set trackName to text 1 thru (maxSize - 3) of trackName & "..."
			end if
			if length of artistName is greater than maxSize then
				set artistName to text 1 thru (maxSize - 3) of artistName & "..."
			end if
			set trackInfo to trackName & " | " & artistName
		else
			set trackInfo to ""
		end if
		// return trackInfo


                set stringToScroll to trackInfo # the text you want to scroll
                set speed to 2 # letters per second
                set maxLength to 16 # max letters

                if length of stringToScroll < maxLength then
                	return stringToScroll
                end if

                set stringToScroll to stringToScroll & " ... "
                if (maxLength < length of stringToScroll) then
                	set maxLength to (length of stringToScroll) - 1
                end if

                set t to (time of (current date))
                set p to (t * speed) mod (length of stringToScroll)

                return (text (p + 1) thru ((p + 1) + maxLength) of (stringToScroll & stringToScroll)) & "..."


	end tell
else
	set trackInfo to "iTunes close"
	return trackInfo
end if
```

**Comment by Tompz** [comment]
Awesome, thank you for taking the time to respond.

I guess you could just have it run once, whenever the songs changes?   This way it wouldn’t take up resources?

Thanks again!

**Comment by brantwedel** [comment]
Since running the script needs to be done for each scroll "animation frame" as it just shifts the letters 1 by one each second, it would need to be called at least once a second continuously. The intensive part is not the text scrolling as much, but the `tell application` commands that call into iTunes ... and those need to be called repeatedly to see if the song changes in any case.

The best you could do to reduce performance impact is maybe run the script each second, but save the trackInfo so that you only need to call the `tell application` sections once every 10 seconds (saving strings/data between runs of an apple script is a bit tricky, but possible).

I can provide an example of only updating the trackInfo text every 10 seconds or so to reduce calls to `tell application` if you think you need more performance.

**Comment by fifafu** [comment]
Fyi: I plan to add a native scrolling feature with one of the next few updates.

**Comment by Tompz** [comment]
Thanks guys!   I’ll have a play with this and see what works.

Perhaps the native scrolling feature will be all I ever dreamed of....

Really appreciate the help

**Comment by JayPalm** [comment]
Just checking in, has this been implemented yet? Can't seem to find the option to make the text scroll in a size limited box, so I'm assuming not.
