### ISSUE TITLE
having to restart BTT to re enable the mirror trackpad function quite often.

### ISSUE THREAD

**Issue by Deerl** [fifafu/BetterTouchTool#159]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

**What kind of Mac are you using?**

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by nbrewster-broadsoft** [comment]
**Description of your bug/question/feature request...:**

Frequently (especially after returning from sleep), my trackpad is no longer mirrored. I have to re-open BetterTouchTool. Sometimes just starting it is enough; other times I have to go into the Trackpad settings and un-check and then re-check the "Mirror complete Magic Trackpad orientation for "upside-down" usage" setting.

**What kind of Mac are you using?**
MacBook Pro (Retina, 15-inch, Mid 2014)
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B25
  SMC Version (system):	2.19f12

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Apple Magic Trackpad - Model No. A1339.

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.4 (16E195)
BetterTouchTool 2.071 (by the way it would be nice if you allowed cut-paste from the About screen!)

**Other information:**
(none)

**Comment by lucian1900** [comment]
Same happens to me. Only un-ticking and ticking the option restores the functionality.

**Comment by mauigirl** [comment]
Same loss of trackpad mirroring, it seems to be related to the random crashing listed here:
https://github.com/fifafu/BetterTouchTool/issues/831

I have disabled the menu bar icon but still crashing. It crashes 100% upon sleep/wake but also randomly while working through the day. Sometimes just restarting BTT works but most of the time have to go back into advanced trackpad settings, untick and retick the mirroring box.

Mac OS 10.12.5
MBP Mid-2012
2.7 Intel Core i7
16GB RAM

**Comment by derekvan** [comment]
My mirroring works fine across sleep/wake, but fails at seemingly random times. I will get a short beach ball, then the mirroring will have stopped. 10.12.5

**Comment by radhacrshna** [comment]
I am facing the same issue.

Description of your bug/question/feature request...:

**What kind of Mac are you using?**
  MacBook Pro (Retina, 13-inch, Early 2015)
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	MBP121.0167.B33
  SMC Version (system):	2.28f7

Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?
Apple Magic Trackpad (First Generation)

Which versions of macOS and BetterTouchTool are you running?
macOS Sierra 10.12.6
BTT 2.310

**Comment by fifafu** [comment]
Not sure if this is the exactly the same issue, but I'll continue to track this here: https://github.com/fifafu/BetterTouchTool/issues/935
