### ISSUE TITLE
[Bug] Typo

### ISSUE THREAD

**Issue by Sir-Cumference** [fifafu/BetterTouchTool#1591]
The "Activate/Bring to Front Window Under Cusor" action misspells "cursor" as "cusor".

**Comment by fifafu** [comment]
Thanks for reporting! Fixed with the upcoming version

**Comment by Sir-Cumference** [comment]
@fifafu Found one another typo. In Advanced Settings > Drawing Gestures, "Show gesture drawing instructions/tipps" misspells "tips" as "tipps".
