### ISSUE TITLE
UI Inconsistency - Trackpad options

### ISSUE THREAD

**Issue by andybergon** [fifafu/BetterTouchTool#1593]
#### Description of bug/feature request/question:
Inconsistency about decimal numbers in Trackpad options. 
One of them have the leading zero, the other don't.

![image](https://user-images.githubusercontent.com/5220825/31322658-e3e58636-ac93-11e7-9378-116d68844da4.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
BTT Settings UI

#### Device information:

Type of Mac: MBP 15" late 2016
macOS version: 10.12.6
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting. Fixed in the upcoming version.
