### ISSUE TITLE
Mac 10.11.6, BTT 2.310 add to login items does not "stick" 

### ISSUE THREAD

**Issue by solo-act** [fifafu/BetterTouchTool#1597]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

I can add BTT to login items (unlock, add, lock) but it only stays there until restart then it's gone. All my other apps "stick" in the login items list. I can but BTT in there, but it always gets removed after restart. 

Late 2009 Mac Pro 
OS 10.11.6 
BTT 2.310

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by ButtaJones** [comment]
Same problem here.

Mid 2012 MBP
OS 10.10.5
BTT 2.310

**Comment by fifafu** [comment]
You need to enable launch on startup in the BetterTouchTool preferences,  then it will stick.

**Comment by solo-act** [comment]
Thanks - must have gotten unchecked over the process of several updates because it always stuck until about 2 updates ago. Is checked now and “sticking”.
