### ISSUE TITLE
Suppress Default Action on Keyboard?

### ISSUE THREAD

**Issue by macintacos** [fifafu/BetterTouchTool#1598]
#### Description of bug/feature request/question:
I'd really like the ability to essentially suppress the default action for my keyboard--currently, one of the keys I'd like to map is currently mapped to turning the Brightness of my display up, but I'd really like to be able to just override it entirely and then invoke an action (pausing music, in my case). I've "gotten around" it by just turning the brightnes back up and then envoking play/pause, but it's fairly inelegant.

Any chance that this is just some feature that I've missed? The only option I can find is "Apple Default or Do Nothing", but I'm trying to remove the "Apple Default" part and just haev the "Do Nothing" part.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Pro w/ Touch Bar, 2017, 15"
macOS version: 10.13.1
BetterTouchTool version: 2.310

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately BTT isn't the right tool for such complete key remapping. However you should look into Karabiner Elements, it's great for this kind of stuff.
