### ISSUE TITLE
[Information] Compatibility with other TB Apps

### ISSUE THREAD

**Issue by ZV95** [fifafu/BetterTouchTool#16]
Hey! So just touching base about an interesting finding I had today. I am not sure if I consider this a bug per-se, but I think it is worth mentioning and considering. 

In addition to BTT, I also have an application called [Rocket](http://julianthayn.com/rocket) (currently BETA 0.7) installed. With BTT's new features, I have mostly forgotten about the existence of Rocket Launcher, but today I did attempt to activate it, and I noticed that with BTT running as well, Rocket does not activate when the keyboard shortcut is activated. 

The message I wish to relay is that interactions between BTT and other apps should be considered in what takes priority. For example, in this case, I think that if I directly activate Rocket, it should enable rather than BTT but when it is closed have BTT come back to the foreground. 

Just a thought!

Thanks for all the great updates!

**Comment by fifafu** [comment]
I have thought about this for a while, but unfortunately it is quite complicated. Rocket would need to somehow tell BTT that it's about to show, BTT would need to hide in response.
Therefore both apps would need to integrate some mechanism to talk to each other and decide what to do.

I'll keep this open, but I'm not sure if it is realistic at this point without Apple offering better APIs

**Comment by ZV95** [comment]
Too bad to hear but thanks for looking into it!
