### ISSUE TITLE
Improvement to Mission Control & Immediately Show Desktop Preview

### ISSUE THREAD

**Issue by paulmoons** [fifafu/BetterTouchTool#160]
I just did a fresh install on Sierra and noticed the new "Mission Control & Immediately Show Desktop Preview" action and after trying it found it a bit slow. There was a noticeable (probably half a second) delay between showing the windows and the desktop preview which isn't there when I use a group of cobbled together additional actions I found on the Internet somewhere.

Using the following makes the display of Mission control and the desktop previews pretty much instantaneous and I don't notice the visual delay the new command has. Just thought I'd share my settings in case it will help update the official action or others bugged by the delay. :) .

My gesture settings: 

4 Finger Swipe DOWN | Mission Control
   --> Save Current Mouse Position
   --> Delay next action by 0.03 seconds
   --> Move mouse to X:50.00 Y:0.00
   --> Restore Saved Mouse Position

I am using a 13" MacBook Pro with Touch Bar and am using the built in track pad to perform this action.

I am running the latest MacOS (v10.12.2) and BetterTouch Tool v1.963

I hope this helps some.

**Comment by fifafu** [comment]
Unfortunately this won't work in case the system is under load. The BetterTouchTool action should always work. I think there is currently no solution that works fast amd reliable in all situations.

**Comment by paulmoons** [comment]
I actually figured this was about compatibility with all situations and especially with older hardware. Thanks again for taking a look.
