### ISSUE TITLE
Open Finder new window sequence doesn't work

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#1604]
Here is the action:

    1. Open Finder
    2. Delay next action by 1 second
    3. Menubar-Item: File;New Finder Window

It works less than half of the time for me. If you focus on a window like Safari and try to invoke it using the keyboard, it just don'ts work. You have to press it twice.

**Comment by fifafu** [comment]
Yes such things are hard to do reliably with just the delay stuff. However you should be able to do it quite successfully using this little Apple Script and the "Run Apple Script" predefined action:

```
tell application "Finder" to make new Finder window
tell application "Finder" to activate
```

**Comment by cleverjackal** [comment]
This seems to work better than the others I've tried, but unfortunately it causes the current windows to pop up as well :/

**Comment by cleverjackal** [comment]
Thanks though
