### ISSUE TITLE
[Feature request] Allow to drag windows by pressing "alt+clicking" everywhere but inside the window 

### ISSUE THREAD

**Issue by caipivara** [fifafu/BetterTouchTool#1605]
Hi

Theres a feature of Gnome that I love and is that if you press a key (maybe alt) and let click pressed everywhere inside a window of any program, you can drag the window to other place.

Currently you need to move your mouse to the top bar of the program (and based on the program sometimes is not an easy task, for example for `Slack` or `Chrome` app where you need to click in the top of the window and is not a bar, it works because you know that there should be a bar that let you move windows but slack dont have it visible as a bar)

By bar I mean this bar:
<img width="558" alt="asd" src="https://user-images.githubusercontent.com/76348/31416145-eec25e76-adec-11e7-9179-3f40a651076e.png">

A lot of times you just want to move a window to other place, not necessarily to maximize it but to move it.

**Comment by fifafu** [comment]
Tracking this here: #1458 (I may add this soon)
