### ISSUE TITLE
WACOM ?

### ISSUE THREAD

**Issue by roinigo** [fifafu/BetterTouchTool#1608]
Hi,
When does the "wacom touch issue" will be solved, please...?

**Comment by fifafu** [comment]
There are currently no definite plans for that due to issues with the Wacom driver and High Sierra
You can downgrade to previous versions however (https://boastr.net/releases)

**Comment by roinigo** [comment]
Thank's for the answer. I'm using El capitan by the way

**Comment by roinigo** [comment]
Hi! I can't find the last wacom compatible version of BTT... :(

**Comment by roinigo** [comment]
This driving me crazy !!!
Iget this message : "The Version of BTT you are currently using isn't compatible with the version of your data file!" with older version of BTT (Wacom compatible...)

**Comment by fifafu** [comment]
Ah, BTT keeps old copies of the data store in ~/Library/Application Support/BetterTouchTool (just remove the oldversionbackup extension for the version you want to restore)

**Comment by roinigo** [comment]
Thank's for your help...
I did remove the oldversionbackups...and i still got the same message: "The Version of BTT you are currently using isn't compatible with the version of your data file! Please update to a newer version of BTT. Maybe you have an old version in your startup items(autostart)"

**Comment by fifafu** [comment]
2.297 should work (https://updates.bettertouchtool.net/bettertouchtool_release_notes.html  )

**Comment by roinigo** [comment]
2.297 give me this : "_This version of BetterTouchTool is no longer supported. Gestures etc. will no longer work.
Please update to the most current version. 
For more information please visit 
https://bettertouchtool.com_"

:(((((

**Comment by fifafu** [comment]
Are you sure you have a valid license installed? (Try double clicking your license file again)

**Comment by roinigo** [comment]
I have a valid license installed, of course... I have a "Registration successful" message by double-clicking it.
It's a very weard issue. I just don't understrand why i got this message by installing older versions...

**Comment by roinigo** [comment]
..Eurêka !!!!!! ;)
I reload BTT and import my old presets and it works now !
Thank's a lot for your help fifafu !!!

**Comment by fifafu** [comment]
Awesome! Btw.: it looks like Wacom support will be back in the current version in about 3 weeks.

**Comment by roinigo** [comment]
That's a good news ! ;) Thank's !

**Comment by fifafu** [comment]
The new alpha (2.315) should restore basic Wacom support.
