### ISSUE TITLE
Doesn't activate on important apps anymore, like Chrome

### ISSUE THREAD

**Issue by NearlyNormal** [fifafu/BetterTouchTool#1609]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Used to bring up my touch pad keys with all apps because I only have a 'Global' setup. Now doesn't activate on most apps.  Chrome and Gmail in it are the worst. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro 

#### Device information:

Type of Mac: Macbook Pro 
macOS version: Sierra 10.12.6 
BetterTouchTool version: 2.304 (682) 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
- 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you already tried the current version? (2.310)

**Comment by NearlyNormal** [comment]
Yes. Updated now to 2.310, and restarted both Chrome and BetterTouch. Same issue. 

The cockpit kind of UI is not easy to use, but I haven't changed anything. The same settings used to work.

**Comment by fifafu** [comment]
Mh I think I haven't had similar reports yet.
What exactly do you mean by "touch pad keys"?

**Comment by NearlyNormal** [comment]
The keys that show in the touch bar. Which is the entire point of this paid app. The touchbar by Apple has ESC key highly sensitive, and my typing style keeps touching it by mistake. I cannot disable the original Apple touch bar in any way. So I use this tool to change the keys that appear, and WHERE they appear (I've moved ESC to the right). This used to work.

**Comment by fifafu** [comment]
You can download previous versions here : https://boastr.net/releases however I assume it's just some configuration error. Maybe try running this terminal command to reset your general BTT settings (this won't reset your trigger setup):

defaults delete com.hegenberg.BetterTouchTool 

For refunds please contact my reseller Fastspring.

**Comment by NearlyNormal** [comment]
How can I confirm that the settings are correct. The same settings that
used to work with the version a few versions ago, does not work now. What
precisely has changed? I couldn't find the documentation. Deleting setup
stuff with that command hasn't helped.



On Thu, Oct 12, 2017 at 2:08 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Did you maybe change the app specific settings for Chrome? 

You can go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. If possible please send that folder to boastr.net@gmail.com

**Comment by fifafu** [comment]
Your settings seem to work fine here, see this screenshot:
<img width="1085" alt="touch bar shot 2017-10-12 at 22 01 00" src="https://user-images.githubusercontent.com/8820811/31516441-dbb21396-af98-11e7-9e4e-7fc958dd4f6d.png">

Doesn't it look like this on your machine?

**Comment by NearlyNormal** [comment]
These are settings from July I thought? Anyway, how can I then Export the
settings, then perhaps reinstall the whole tool altogether?

On Thu, Oct 12, 2017 at 4:01 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
The files all have dates from today, so I think these might be from today? Why do you think they are from July?

You can copy the files that begin with btt_data_store.v2 to ~/Library/Application Support/BetterTouchTool and the com.hegenberg.BetterTouchTool.plist to ~/Library/Preferences/ 

(all while BTT is quit)

**Comment by fifafu** [comment]
If possible please reply here on Github so other people can also profit of this.

Did you maybe change the Touch Bar settings in System Preferences => Keyboard? For BTT to work the should be set to "App Controls with Control Strip" (some other settings also work, but this is the safest)

**Comment by NearlyNormal** [comment]
Yes, that was it! So it's got nothing to do with BTT. It's the setting in
the Apple Preferences. Thank you, it works now.



On Thu, Oct 12, 2017 at 4:55 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Ah perfect!
However didn't BTT show a warning popup about this every time you opened the prefs? (That's a bug then)

Which setting did you have active in system preferences?

**Comment by fifafu** [comment]
> Actually, not fully done yet. The ESC keys and the four other keys (Volume - and +, and brightness - and +) which are the only five keys I'd like to show, are NOT showing by themselves. There's a close button "X" on the left now, which reveals the original ESC key from the idiotic Apple touchbar, and on the right there are still some other icons on the touch-bar. This never happened before. I used to see only the 5 buttons I need. 

> A screenshot of my touch bar here: https://imgur.com/a/GQBby

> All I need are the 5 buttons, ESC, V-, V+, B- and B+. How can I do that? 


Configure it like this: 
![image](https://user-images.githubusercontent.com/8820811/31520121-17f22268-afa5-11e7-8184-1b02b6bb8d00.png)

**Comment by NearlyNormal** [comment]
That’s how it’s configured. Doesn’t work. I’m wondering if this is a useful
app at all. Way too much tinkering for marginal gain. Used to be good
enough, not sure what we are upgrading. Anyway looks like you wish to close
this thread.

**Comment by fifafu** [comment]
This definitely works. You probably didn't uncheck the "show macOS Control strip" checkbox.
