### ISSUE TITLE
BTT causes reboot on sleep wake.

### ISSUE THREAD

**Issue by volkanbeyaz** [fifafu/BetterTouchTool#1610]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

First of all it is very important because every time I sleep computer It restarts. The restart is immediate after I wake the computer, I mean wake screen never comes on, I see the bios directly.
Another thing is, If I wake the computer just after it sleeps, it works fine, the problem happens when the computer sleeps for some time (I dont know how much).

When I run command : pmset -g log | grep -i failure
I get this error message: Drivers Failure during wake due to 0x04000027

If I quit better touch tool and then sleep the computer, everything works fine as before. By the way I am a new user of BTT, I has been just one week.

#### Device information:

Type of Mac: Hackintosh PC (Asus Maximus Ranger VIII, Intel 6700K)
macOS version: 10.12.5
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, this is a hackintosh problem. Other hackintosh users reported it has been fixed on 10.13. Unfortunately this can't be addressed in BTT.

**Comment by volkanbeyaz** [comment]
Thanks.
