### ISSUE TITLE
Shutdown/sleep timer

### ISSUE THREAD

**Issue by Shiryuck** [fifafu/BetterTouchTool#1611]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I listen to the music lying relaxed in my bed or sofa, something that I miss in Remote BTT is a Shutdown timer. What do you think about that? :-) Could be possible?.

Greetings.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

you can use the predefined action "Run Apple Script In Background" with this Apple Script:

```
tell application "System Events"
	set sleepTimeInMinutes to 30 --means sleep after 30 minutes
	set sleepDelayTime to sleepTimeInMinutes * 60
	delay sleepDelayTime
	sleep
end tell
```
