### ISSUE TITLE
Do not change actions when system layout change

### ISSUE THREAD

**Issue by jrmgx** [fifafu/BetterTouchTool#1614]
#### Description of bug/feature request/question:

I setup BTT actions with my French keyboard and everything is fine, but when I change the system layout to US (as I have a US workstation with external US keyboard at work) all the actions in BTT change too, so nothing works anymore

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

I think that is the case with every input devices

#### Device information:

Type of Mac: macbook pro mid 2015
macOS version: 10.12.6 (16G29)
BetterTouchTool version: lastest 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Not a crash

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, unfortunately this is not possible. 
(There might be ways but I haven't found a good reliable one. All the keyboard APIs work with the actual physical keys, not with the characters they produce)

**Comment by jrmgx** [comment]
thank you for you help
