### ISSUE TITLE
Command Box

### ISSUE THREAD

**Issue by LibertarianVoter** [fifafu/BetterTouchTool#1617]

**Comment by fifafu** [comment]
I think alfred is suited way better for this ;-)

**Comment by fifafu** [comment]
(if you want to trigger BTT actions using Alfred, right-click the action in BTT, and select "copy link", then configure Alfred to open that link)

**Comment by fifafu** [comment]
Closing here for now as this is not something that will come to BTT in the near future.
If I decide to implement it I'll notify you here.
