### ISSUE TITLE
Touch Bar Margins Disappear on Wake-up

### ISSUE THREAD

**Issue by R-V-S** [fifafu/BetterTouchTool#162]
When coming back to my computer after a break (so the computer has been sleeping), I've noticed that the touch bar icons display oddly. Margins are missing, as well as two of my buttons. It looks like this:

![image](https://cloud.githubusercontent.com/assets/253313/21460577/f4d60232-c917-11e6-81f0-2f69e909f814.png)

When it should look like this:

![image](https://cloud.githubusercontent.com/assets/253313/21460579/fb5d6f28-c917-11e6-97b8-94ea107a0e09.png)

The moment I switch apps or perform any action that re-initializes the touch bar, it's fine. It remains fine until the next time my computer sleeps (at least I believe that's the cause of it).

---

System: 15" Macbook Pro 2016 w/ Radeon Pro 460
OS: macOS 10.12.2
Touch Bar version: 1.977 (though I believe this cropped up in an earlier version)

**Comment by R-V-S** [comment]
Seems to be resolved in 1.985. The touch bar still loads with the icons jumbled, but after a second or two, they snap into place.

**Comment by fifafu** [comment]
Thanks for reporting! I'll try to further improve it, but closing for now.
