### ISSUE TITLE
BTT: 4 finger click is registered twice in files app

### ISSUE THREAD

**Issue by semihyagli** [fifafu/BetterTouchTool#1623]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question: 
I am using 4 finger click to hide/close windows. That is I assigned 4 finger click to cmd+W. While the functionality works perfect in safari tab closing, it registers twice in finder (one for the folder that the cursor is on and another for the folder that is active, so closes them both) and in google chrome it behaves like cmd+Q although it closes all tabs and leaves chrome hidden. I am using the latest build of BTT. Note that in previous builds I only recall having the issue with chrome only.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad

#### Device information:

Type of Mac: MacBook Pro, November 2016
macOS version: High Sierra (10.13)
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Once again, functionality works perfect for just about anything else. In safari, I had no issues.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by semihyagli** [comment]
Sorry, my bad. I realized that the attached functionality is the issue. I had assigned "close application (works in mission control)" functionality to 4 finger click as well. The secondary closing is due to that.  Although, I dont know if there are technical difficulties to it, can we assign "cmd+W" and "close in mission control" to the same trackpad action and not have the issue described above. That is, is it possible to tweak "close in mission control" to just work in mission control. Though this might be confusing to some users. 

Thanks

**Comment by fifafu** [comment]
Unfortunately I currently don't know of any way to detect whether Mission Control is active or now, thus BTT can't adapt its behavior just for Mission Control :-(

**Comment by fifafu** [comment]
Closing for now, I'll post an update in case I find a solution.

**Comment by semihyagli** [comment]
That's fine. I assigned 4 click force touch to cmd+Q and mission control quit. Although, in mission control it does not quit, it just hides the application. But I can live with that.
