### ISSUE TITLE
Allow multiple BTTAppBundleIdentifier

### ISSUE THREAD

**Issue by keyboardsurfer** [fifafu/BetterTouchTool#1624]
#### Description of bug/feature request/question:

I've got a configuration and don't want to maintain multiple versions for a .eap and a stable version.
The easiest way to allow this on my end, is allowing multiple values within BTTAppBundleIdentifier.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Everything that can be limited to an app.

**Comment by fifafu** [comment]
Tracking this here: #1551 (not sure yet whether/when this will be possible)
