### ISSUE TITLE
Mouse selection in Xcode not working properly

### ISSUE THREAD

**Issue by sroebert** [fifafu/BetterTouchTool#1635]
#### Description of bug/feature request/question:

When BetterTouchTool is running, text selection in Xcode is not working properly anymore. When trying to select text by holding shift and selecting using the mouse cursor, it only works properly when waiting for a bit to click with the mouse. If selecting too fast, it does not work and only moves the cursor. This does not happen when BetterTouchTool is not running.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse/keyboard in Xcode.

#### Device information:

Type of Mac: MacBook Pro 15 inch, late 2016
macOS version: 10.13
BetterTouchTool version: 2.310

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by sroebert** [comment]
Yes, that solves it 👍
