### ISSUE TITLE
"Maximize Window to Next Monitor" suddenly not working.

### ISSUE THREAD

**Issue by ZakMalik** [fifafu/BetterTouchTool#164]
Hey guys, I assigned Maximize Window to Next Monitor to one of the Function keys. It was working fine before but now it suddenly doesn't work. I've tried different F keys but no luck. Any idea why it could have broken?

MacBook Pro TouchBar (15-inch, 2016)
2.9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Radeon Pro 460 4096 MB
Intel HD Graphics 530 1536 MB

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Apple external USB keyboard

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.2
BetterTouchTool 1.977

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
The second monitor is a 4k external display connected via HDMI to Thunderbolt 2 hub then Thunderbolt 2 to USB-C into the MacBook Pro.

**Comment by fifafu** [comment]
Maybe same as #2 ? (that will be fixed sometime in January when I get my 5k display to test :-))

**Comment by ZakMalik** [comment]
Hmm. Well this worked perfectly fine but suddenly it doesn't. It works with my other MBP for example. Perhaps I should trash some prefs?

**Comment by fifafu** [comment]
Have you looked at the setting mentioned in the other thread? 
I think that may also be causing your issue.
