### ISSUE TITLE
After update to Macos High Sierra - clicks are all silent (haptic feedback only) on Trackpad

### ISSUE THREAD

**Issue by gahabana** [fifafu/BetterTouchTool#1643]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi, after upgrading to MacOs (10.13) to High Sierra, BTT clikks (2 , 3 finger ForceClick) have become either completely silent and feedback much lower then it used to be.
I tried changing in Preferences-Trackpad-ForceTouchpad to change 'Haptic Response to Force Clicks' and tried everything but ALL of them are silent.
Both on regular release as well as 2.311 (688) Alpha release.

Tx for advice if there is any other setting that could help ? 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Trackpad

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #1558 
If possible please provide more information about your Mac.
