### ISSUE TITLE
Can't use Control  + {Option, Command, Shift}  + Arrow{Up,Left,Bottom,Right}

### ISSUE THREAD

**Issue by safareli** [fifafu/BetterTouchTool#1644]
When i'm creating new Keyboard Trigger I can't use shortcut like: 
```
Control 
+ {any combination: Option, Command, Shift} 
+ Arrow{Up,Left,Bottom,Right}
```
Is there a reason for it, should I uncheck something? or is it a bug?

#### Device information:

Type of Mac: MacBook Pro 2014
macOS version: 10.13 (High Siera)
BetterTouchTool version:  2.310

#### Additional information
When I'm typing some shortcut which is "insertable" but when I'm typing the shortcut above it's grayed out.

**Comment by tflo** [comment]
I had the same issue with assigning <kbd>⌃</kbd><kbd>⌥</kbd><kbd>←</kbd> and <kbd>⌃</kbd><kbd>⌥</kbd><kbd>→</kbd>.

I could assign the shortcuts after enabling “Trigger on key down instead of key up” in the shortcut preferences. (The little gear icon.)

After you have assigned the shortcut you can disable the setting again.

– Tom

**Comment by DaveBurns** [comment]
Experiencing the same issue. BTT 2.310, macOS 10.12.2, late 2011 MBP.

To reproduce, no need for the Option/Command/Shift keys. Just try Control-Left or Control-Right. Enabling "trigger on key down" lets me enter the shortcut but the shortcut doesn't actually work. I've tried removing the "trigger on key down" after adding the shortcut but it still doesn't work. Other shortcuts do work.

db

**Comment by CJSF2323** [comment]
Same issue. This combination works for my other computer, which I had installed BTT on years ago. However, can't get it to work on this new installation. Tried using "trigger on key down" to set it up, but no dice. BTT 2.3.13, MacOS 10.12.6, Mid 2011 MBA

**Comment by fifafu** [comment]
This will be fixed with a little update later this week. (There has been a change to macOS but I have added a workaround)
