### ISSUE TITLE
Shut Down Predefined Action

### ISSUE THREAD

**Issue by djw44** [fifafu/BetterTouchTool#165]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Would like to have a predefined action for Shutdown so I don't have to hold the power button down for 3 or 4 seconds or choose Apple=>Shutdown=>Yes.  

**What kind of Mac are you using?**
Macbook Pro (late 2016 with Touch Bar)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad, Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by curtisblackwell** [comment]
Power button on the TouchBar MacBook Pro? Where?

In any case, I'd like this feature, too. I used to use `ctrl` + `opt` + `cmd` + `eject`, but since there's no more eject button… Ideally I'd be able to just replace `eject` with the Touch Sensor button (or whatever it's called).

**Comment by fifafu** [comment]
I'm going through some older issues, so if this is not relevant to you anymore, please ignore.

You can achieve shutdown by using the trigger menubar menu-item action and combine it with sending the return key:

![image](https://user-images.githubusercontent.com/8820811/35757664-8300bfe6-0870-11e8-804f-03b221e32b52.png)

Alternatively you could use the apple script action with this: ```tell app "System Events" to shut down```
