### ISSUE TITLE
Single Clicks not registering on Spotify

### ISSUE THREAD

**Issue by davemorton** [fifafu/BetterTouchTool#1652]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Quick single left clicks don't register on Spotify. Similar to the bug earlier with Chrome. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse (not 2)

#### Device information:

Type of Mac: Late 2011 Macbook Pro
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Ah that's probably because spotify uses electron which is based on chrome... I'll add it to the exception list with the next update, so BTT will apply the same workaround for it.

Chrome has just fixed the issue with their latest beta version, so it will also be fixed in Spotify eventually.

**Comment by davemorton** [comment]
Right on. Thanks for responding so quick. I love BTT!

**Comment by davemorton** [comment]
Hi there... Just checking in! Still having the same issue. Any idea when the next update will be out?

**Comment by fifafu** [comment]
It'll probably be released later this week - if you want to try it now, you can download the test build here: https://bettertouchtool.net/releases/btt2.314b.zip

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
