### ISSUE TITLE
⌘+double-clicking on the menubar will still select/highlight menu-items (file, edit, view, etc)

### ISSUE THREAD

**Issue by cygvis** [fifafu/BetterTouchTool#1653]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I just updated BST from app store & have a new issue.

I use BST with BTT, where I have things set so that a ⌘+doubleclick action on the menubar will do a keyboard shortcut (CMD+OPT+CTRL+C, which is my BST shortcut for “center window”). But after doing this action, if I then hover over a menu bar menu-item (file, edit, etc), they remain highlighted as if I'm still holding down the left mouse button. It won't highlight menubar items for apps on the right side.

_**NOTE**: Just tested & it does this for **any keyboard shortcut** actually... not just BST ones._

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

⌘ + any device

#### Device information:

Type of Mac: MacBook Pro (Retina, Mid 2012)
macOS version: 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cygvis** [comment]
This issue is no longer occurring

**Comment by fifafu** [comment]
Ah yes, this has been fixed with the last update. Thanks for closing!
