### ISSUE TITLE
How do I hide the logo which says What action did BTT do ?

### ISSUE THREAD

**Issue by shramanshraman** [fifafu/BetterTouchTool#1662]
For example https://i.imgur.com/ZvErVhO.png

How do I hide this kind of logo or window.
<img width="304" alt="screen shot 2017-10-23 at 6 43 26 pm" src="https://user-images.githubusercontent.com/18033699/31980343-7e3b0288-b969-11e7-8ee8-cc87e4199ce8.png">

**Comment by ZV95** [comment]
This appears to be the HUD overview. To edit it, go into BTT, select the item that is causing the HUD overlay, and in the bottom of the page you'll see a little preferences button next to the gesture. Click on that and unselect the HUD Overlay option. 
![ss 2017-10-25 at 11 17 20](https://user-images.githubusercontent.com/18543749/32006943-27f584d6-b976-11e7-86f1-cee9bd700692.jpg)
![ss 2017-10-25 at 11 18 11](https://user-images.githubusercontent.com/18543749/32006960-356a6dac-b976-11e7-8e38-87662e2f48e3.jpg)

**Comment by shramanshraman** [comment]
THANK YOU!
