### ISSUE TITLE
[Feature Request] Pre-Built Features

### ISSUE THREAD

**Issue by ZV95** [fifafu/BetterTouchTool#1667]
## Feature Request - Pre-Built Features

I am writing to request the addition of a library of 'pre-built' BTT actions.  I would like to suggest that any user can submit an action to this library and it could be used right here on GitHub. 

The features that I believe would need to be added would be to export and input a single BTT action, and then somewhere that it can be shared to. 

The purpose of this would be to have users expand how they use BTT and encourage innovation from dedicated users to create actions that are useful for others. This would especially be useful for multi-step actions - for example, the creation of a BTT that runs a script to clear caches could be pre-written and then tied to a single BTT action with a good haptic response and notification.

**Comment by fifafu** [comment]
I will soon (2-3 weeks) present a little platform for sharing presets. Stay tuned :-)
