### ISSUE TITLE
Question: How to have sequences of characters sent.

### ISSUE THREAD

**Issue by jduhamel** [fifafu/BetterTouchTool#1676]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm trying to figure out how to have the F10 key press A,A,A,B (repeat) with a 150ms delay between key presses and a 250ms delay on the repeat. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: imac
macOS version: 10.13
BetterTouchTool version: 2.311
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can use the "attach additional action" button and the predefined action "delay next action" to do this.
Sorry currently traveling, so I can't attach a screenshot.

**Comment by jduhamel** [comment]
I can see how to do a Chain of F10->a, delay, a, delay, a, delay, b, new delay, F10.  But I don’t see how to make the F10 a toggle on or off. 

—Joe

**Comment by fifafu** [comment]
Ah now I understand. Honestly for such remappings the app called "Karabiner Elements" is much better.
You can however try to click the little gear icon on the left of the f12 key shortcut box, then choose the "trigger on keydown" and choose the delay there.
