### ISSUE TITLE
Dragging related bugs in Affinity Photo

### ISSUE THREAD

**Issue by tommit** [fifafu/BetterTouchTool#1678]
#### Description of bug/feature request/question:

There are all kinds of problems when using [Affinity Photo](https://itunes.apple.com/fi/app/affinity-photo/id824183456). These are just some off the top of my head:

- When you're in a dialog window which has multiple sliders (for example the Levels Adjustment Layer settings) and you one after the other click-drag the knobs on the sliders to adjust their values, then sometimes it happens that the slider-knob you drag doesn't move but instead what moves is the slider you dragged just before the last one.

- When you select the Rectangular Marquee Tool and click-drag on the canvas to make a rectangular selection and you click somewhere in the gui or even click at the macOS Menu Bar (for example, let's say you click at a layer that's different from the currently selected one, or you click to select a different tool), then sometimes this really weird thing happens, where the view of the canvas slowly pans all the way as far as it can go towards where you made the last click, and the canvas view becomes stuck there such that you can't anymore pan the view by sliding two-fingers on the trackpad. In this situation, you have to select the View Tool and click-drag a bit to pan it that way, and after that you can again pan normally by sliding two fingers on the trackpad.

- When you click a button in a dialog window (for example the "Apply" button in the Gaussian Blur Filter settings), sometimes the only thing that happens is that the clicked button goes visually to a "pressed" state (the button's background color becomes darker, that is) and nothing else. In this situation, you have to click the "Apply" button again for it to actually "apply" the filter/whatever in question and for the dialog window to go away.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Apple Magic Trackpad 2

#### Device information:

Type of Mac: iMac (21.5-inch, Late 2013)
macOS version: 10.13.1 Beta (17B46a) [But this bug has been there for many years]
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

In the macOS System Preferences > Trackpad > Point & Click, I have the following settings:
![system preferences - trackpad](https://user-images.githubusercontent.com/7393895/32126007-444fc706-bb77-11e7-82d3-d653b885f705.png)

To make Affinity Photo usable, the only thing I can do is to add Affinity Photo to the list of managed applications in BetterTouchTool, right click on it, and select "Disable BTT completely for 'Affinity Photo'".

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by tommit** [comment]
Yes, it seems the alpha version 2.313 (691) has fixed all the aforementioned issues. Nice.
