### ISSUE TITLE
[Feature request] Enable blacklisting

### ISSUE THREAD

**Issue by waxfingers** [fifafu/BetterTouchTool#1679]
Case: I'd like to stablish a global shortcut for ALL applications but 1, and at also assign SAME shortcut for that 1 app, but with different behaviour. Example
F4 (Global) = fullscreen
F4 (iTerm) = show/hide iTerm

Kind of karabiner's conditionals with a GUI... which allow tons of flexibility +)

Thank you

**Comment by fifafu** [comment]
Hi,

sorry for not replying back then.
I think this is standard behavior in BTT. If you set app-specific shortcuts they will always override global shortcuts for that one app.

In case you still have questions, please comment - I'm currently closing some older issues.
