### ISSUE TITLE
Trackpad Click To Drag Issue

### ISSUE THREAD

**Issue by amodestgenius** [fifafu/BetterTouchTool#1680]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When I drag a window by using the click to drag function and then let go, if I immediately click somewhere else, it'll move the window to that position. This is only true if I don't remove my finger before moving the cursor to the new position. If I click to drag a window and then remove my finger from the trackpad, if I move the cursor and click somewhere else, it will not drag the window to that spot. This error goes away when I quit BetterTouchTool

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad

#### Device information:

Type of Mac: Macbook Pro 15" mid-2015
macOS version: 10.13 High Sierra
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by amodestgenius** [comment]
It's fixed! Thank you so much!
