### ISSUE TITLE
Cursor jumps when typing

### ISSUE THREAD

**Issue by IndigoHomme** [fifafu/BetterTouchTool#1683]
#### Description of bug/feature request/question:
With BTT enabled the cursor jumps around when typing. Disable BTT and no problems.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Air trackpad

#### Device information:

Type of Mac: MacBook Air
macOS version: 10.12.6
BetterTouchTool version: 2.3.10

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You probably accidentally trigger a gesture you have configured (maybe corner taps?). To solve this you should either remove these gestures or try to use the feature to disable gesture recognition while typing:

![image](https://user-images.githubusercontent.com/8820811/32702932-7da0abfa-c7ee-11e7-896d-db1b40f8afde.png)
