### ISSUE TITLE
every update withdraw BTT from startup apps

### ISSUE THREAD

**Issue by peytonkelvin** [fifafu/BetterTouchTool#1684]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
With every update, BTT won't launch after a startup. User needs to go to preference/users/Login items and add it up again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro retina 2015, MacBook Pro Touch bar 2017

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

thanks !

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You need to enable the launch on startup option in the BetterTouchTool preferences, it will handle the login items automatically then.
