### ISSUE TITLE
Touch Bar Settings Hides Controls

### ISSUE THREAD

**Issue by sparticvs** [fifafu/BetterTouchTool#1686]
#### Description of bug/feature request/question:
I use the following Keyboard configuration:

**Touch Bar shows** App Controls
**Press Fn key to** Show Control Strip

However, it seems that in this mode, I am not able to see any of my Global  Widgets in the Control Strip.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:

Type of Mac: 15" MBP - 2016 Model
macOS version: 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

General Touch Bar Settings (only the following are selected):
+ Enable Touch Bar Support
  + Show macOS Control Strip
    + Show BetterTouchTool Icon in Control Strip
+ Show ESC Button on the left side of the Touch Bar icons

Widget Settings (Spotify script):
+ Item Placement: Stick to left side of the Touch Bar
+ Always show this button while BTT Touch Bar is visible (even if global actions are hidden)

I'm not entirely sure what I am missing. It only seems to show up for me with the "App Controls with Control Strip" setting. Any help fixing this would be greatly appreciated.

**Comment by fifafu** [comment]
On 10.12 BTT can only work correctly if the Control Strip and App Controls option is selected. On 10.13 it also seems to work with other options.

**Comment by sparticvs** [comment]
I see. Thank you for the response. I guess I will wait then. :-)
