### ISSUE TITLE
Three Finger TipTaps require large distance between fingers

### ISSUE THREAD

**Issue by proactivematter** [fifafu/BetterTouchTool#1687]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I've configured 2 finger TipTaps and these work perfectly, but three 3 TipTaps aren't recognized unless I spread my fingers a much wider distance apart - which is just not natural for me.

As I use both 2 finger and 3 finger TipTaps for the same type of activity (navigating tabs in firefox), I wonder this can be fixed so that I don't have to switch stances.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Pro 15" 2017 Trackpad

#### Device information:

Type of Mac: Macbook pro 15" 2017
macOS version: High Sierra 10.13
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I've tried fiddling with the "Maximum Allowed Distance Between Fingers" setting, but it did not make any difference.

#### P.S:

Man, Fifafu, might I take this moment to say how incredibly awesome you are? I would have returned this MacBook if it weren't for this hot piece software that you have made. Seriously, that ESC key was driving me crazy, as were other touchbar elements that would get activated when I intuitively rested my hands in-between typing bursts. This is my first MacOS device and wow, I am now so excited thinking about all the possibilities your software opens up. I have so many questions for you, but I know you're a busy man - as am I in my own right. Maybe another time! =)

All the best.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

thanks for reporting! I think I forgot to adjust the "spread" for the newer bigger trackpads.
Will be fixed with the next update in a few days :-)
