### ISSUE TITLE
turn off volume popup from btt remote

### ISSUE THREAD

**Issue by Sebastian-blu** [fifafu/BetterTouchTool#1688]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I am wondering if I could turn off the volume popup when using the small increment volume button on BTT remote. Or is this a system file I would need to deactivate?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB

#### Device information:

Type of Mac:
macOS version: 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is always shown by the system when modifying the volume by simulating the key presses.
I don't think it's possible to get around that :-(

You could instead configure an action that uses Apple Script to modify the volume, however you couldn't use the default volume buttons in BTT Remote anymore.

**Comment by fifafu** [comment]
Oh actually, there is a possibility to turn it off completely (but this will then also be true for the volume keys on the keyboard).

See http://www.mackungfu.org/get-rid-of-the-volume-brightness-screen-overlays-mac

**Comment by Sebastian-blu** [comment]
It doesn’t pop when using the touch bar slider or the menu bar slider could the remote point to that instead? I ask because it looks like that fix doesn’t work in Sierra unless u turn off SIP. Not a big deal just an idea. Thanks again!

Barry
