### ISSUE TITLE
Dragging issue in Dashboard 

### ISSUE THREAD

**Issue by FeindFire** [fifafu/BetterTouchTool#1689]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

As of updating to High Sierra, I have issues dragging widgets in the Dashboard. After clicking an item, then clicking elsewhere, my Mac behaves as if I had dragged and released, rather than inputing two complete clicks. The widget does not follow my cursor between clicks, but rather snaps to the location of the second click at the time of the second click.

I would consider BetterTouchTool to be completely incompatible with the Dashboard in this state.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Internal ForceTouch trackpad, Logitech M570, two models of wired usb mice branded Microsoft, one branded Dell, one branded Lenovo

#### Device information:

Type of Mac: 2015 Retina MacBook Pro
macOS version: High Sierra 10.13
BetterTouchTool version: 2.311 (688)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by FeindFire** [comment]
This version has solved the problem. It also seems to have introduced a new, but very minor graphical issue where widgets stutter and flash a little while being dragged. This is ignorable at best, and a nuisance at worst. BetterTouchTool is most definitely compatible with the Dashboard again. Thanks for the fix!

**Comment by FeindFire** [comment]
Same day, about 4 hours later, and the stuttering and flashing hasn't been seen for at least two hours, regardless of BTT running. Will update if the issue returns
