### ISSUE TITLE
4 finger tap erroneously activated

### ISSUE THREAD

**Issue by mcarreira** [fifafu/BetterTouchTool#169]
I’m having a problem with the 4 finger tap gesture that I defined in BTT.

When I perform the “pinch with thumb and 3 fingers” or “spread with thumb and 3 fingers”, the 4 finger tap gesture gets activated.

The spread and pinch with thumb and 3 fingers gestures are being detected by the system, not BTT.

I'm using:
MacBook Pro Retina late 2013;
Input device: MacBook Trackpad;
macOS: Sierra 10.12.2
BTT: 1.963

**Comment by fifafu** [comment]
Thanks for reporting!

Unfortunately BTT can't work correctly while the system gestures are still active. You'll need to disable them for BTT to work correctly.

**Comment by mcarreira** [comment]
Ok. In that case, I'll replicate the system configuration in BTT. Thanks for replying
