### ISSUE TITLE
left click green window button, zoom window below cursor doesn't work

### ISSUE THREAD

**Issue by rolomoto** [fifafu/BetterTouchTool#1690]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

this trigger and predefined action are supposed to fit finder to screen but it doesn't work with all applications. If I open a new finder window from google drive in the menu bar it opens a small window. When I click the green button it gets a little bigger but doesn't fit to screen.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

mac mini

#### Device information:

Type of Mac: mac mini
macOS version: 10.12.6
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You need to use "maximize window" instead of "zoom window below cursor"

**Comment by nknotts** [comment]
@fifafu I just stumbled into this work around and it works great as a temporary fix but it is not the same as the previously working `zoom window below cursor`. `zoom window below cursor` would toggle between big and small while `maximize window` only makes windows larger. Is there any idea on why `zoom window below cursor` no longer works?

**Comment by fifafu** [comment]
Zoom window is just a system functionality that BTT calls. It does the same as hitting the green zoom button so it depends on the app and system implementation of that feature.

**Comment by nknotts** [comment]
@fifafu Do you to know what system call is made (when BTT is disabled) when clicking the green button while holding alt (the green button with the plus sign). This is the functionality that `zoom window below cursor` used to mimic but now only partly works.

For some specific examples, the built-in `Terminal.app` correctly toggles with `zoom window below cursor` enabled but `Visual Studio Code` does not respond to clicking the green button 
 while `zoom window below cursor` is enabled. With BTT disabled, `Visual Studio Code` behaves as expected when clicking the green button while holding alt.

**Comment by jgtherrien** [comment]
fifafu, many thanks for the info.  Have been scratching my brain on this one, and that's messy.  There are a lot of instructions from old articles that talk about getting this functionality but using the old method of "zoom below..." as the function to get old school fill screen. so you may keep hearing about it.  PS, love BTT and now am slinging windows around my screen like a legit keyboard jockey
