### ISSUE TITLE
Drawing Not Working.

### ISSUE THREAD

**Issue by Hawkcode** [fifafu/BetterTouchTool#1691]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I can not add a drawing, I can draw it but when I release the Mouse button it goes away.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MBP New Model, Using Trackpad or Logitech Mouse

#### Device information:

Type of Mac: MBP
macOS version: 10.13
BetterTouchTool version: 2.311 (688) I tried it with the release version also.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Are you sure you are recording it in the Drawing tab in BTT? See this screenshot:
![image](https://user-images.githubusercontent.com/8820811/32700956-77aea9ca-c7cd-11e7-84ad-1366ceb3c7d8.png)

**Comment by Hawkcode** [comment]
Absolutely. I have 3 other drawings, that I set up a while ago. Went to add another one. When I release the right click button after drawing it clears the drawing.


--Richard S Albrecht--
2019 Salem Rd
Elgin, IL 60123
847-652-3563

Skype: HawkCode

**Comment by fifafu** [comment]
Oh actually I think the draw recording window only supports left mouse drags. Could you try that? I think I haven't added the code necessary to support right mouse drawing there.
