### ISSUE TITLE
macOS 10.13.2 (17C60c)

### ISSUE THREAD

**Issue by pyummm** [fifafu/BetterTouchTool#1698]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

after macOS upgrade, BTT lost mouse gestures recognision, have do hardware clicks

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse 2

#### Device information:

Type of Mac: macbook pro mid15
macOS version: 10.13.2
BetterTouchTool version: 2.3.10(687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #1693
