### ISSUE TITLE
BTT stop working completely

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#1699]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BTT stop working completely on latest high Sierra beta

#### Device information:

Type of Mac: mbp 15" 2016
macOS version: 10.13.2 Beta (17C60c)
BetterTouchTool version: 2.311

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #1693
