### ISSUE TITLE
Vertical alignment in the names of apps/actions

### ISSUE THREAD

**Issue by artdevjs** [fifafu/BetterTouchTool#17]
#### Description of your bug/question/feature request...:
I noticed this bug today, BetterTouchTool 1.961

**What kind of Mac are you using?**
MacBook Pro (Retina, 13-inch, Mid 2014)

**Which version of macOS are you running?**
macOS Sierra 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
![qau6zynp4hyxk9xsznfvwhg3esfbhucxac8tsti2bst7wmihz9wayd7m1kg0muhnjg5gedboihm_fvasd-2een0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://cloud.githubusercontent.com/assets/7567983/20910530/be9e05f8-bb6a-11e6-981c-e5651c7c827c.png)

**Comment by fifafu** [comment]
Thanks for reporting!

**Comment by fifafu** [comment]
Should be fixed with the next update (release tomorrow)
