### ISSUE TITLE
Click behaving as click-drag

### ISSUE THREAD

**Issue by peppermintesse** [fifafu/BetterTouchTool#1700]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Similar to issue 1689, but different OS and more symptoms that may be related.

When I click (single left click) on an item in the Dashboard (such as the Weather or Translation widget), a second click elsewhere moves the widget to the location of the second click.  (The widget doesn't follow the path of cursor movement, but just appears in the new destination location instantly.) It's behaving like it's interpreting the click to be a click-hold.

I'm also experiencing a "click = click-hold" problem when clicking on a tweet in Tweetbot (vers. 2.5.3). I click on a tweet, then click on the tweet above it, or even to a location on the Desktop or into a Chrome window, it looks like I'm trying to drag it there (a ghostly, semi-transparent tweet appears then disappears). It doesn't happen every time.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad

#### Device information:

Type of Mac: iMac (Retina 5K, 27-inch, Late 2015)
macOS version: 10.12.6 
(However, this issue is not new to this OS version; it has been happening for a little while. Not sure how long though.)
BetterTouchTool version: 2.310 (687) 
I did update it, and restart. It's still happening.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screenshot of the "click = click-hold".
<img width="627" alt="screen shot 2017-11-02 at 1 51 04 pm" src="https://user-images.githubusercontent.com/33331807/32349770-65bfe6b6-bfd5-11e7-8375-92feba7c8de5.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by ediskrad73** [comment]
i have the same issue, especially with Tweetbot and TotalFinder

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by peppermintesse** [comment]
I just installed the 2.131 (691) release and I'm no longer able to reproduce the problem. Great work; thank you!
