### ISSUE TITLE
Wakes from sleep, causing slow battery drain

### ISSUE THREAD

**Issue by zippomanhollis** [fifafu/BetterTouchTool#1701]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Bug.  Computer seems to be repeatedly waking from sleep while closed and not in use.  Noticed because battery was draining unexpectedly.  Have not noticed the behavior when btt is turned off.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
NA

#### Device information:

Type of Mac: 2017 15" MacBook Pro with TouchBar. 3.1 GHz, 500 Gb solid state, Radeon Pro 560 Graphics
macOS version: macOS Sierra 10.12.6
BetterTouchTool version: 2.311

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

attached console log
[btt_bug_console_log.txt](https://github.com/fifafu/BetterTouchTool/files/1439976/btt_bug_console_log.txt)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I don't think this can be caused by BTT. (The logs just show that BTT restarts after waking from sleep, which it always does when your mac wake from sleep)

Usually such wakes can only be caused by external hardware, do you have anything connected via USB?

**Comment by zippomanhollis** [comment]
I am so sorry, when I saw that in the log, I started trying to debug and one of the things I did to troubleshoot was turn off BTT, and when I did, the dark wakes stopped. BUT it was just coincidental; there was an issue with some of apples' settings causing them, and it happened to not do it the day that I had BTT off.  Sorry for the false report.   BTT is awesome!
