### ISSUE TITLE
Window Snapping: centralising a window

### ISSUE THREAD

**Issue by lfpippa** [fifafu/BetterTouchTool#1702]
Is there a way to centralise a window in Window Snapping? Other applications can do that by dragging the desired window to the very bottom of the screen, resulting in the very original state of such window (i.e. Safari is a rectangle in the middle of the screen). For some reason I thought BetterTouchTool did the same a while ago. Am I wrong or can't I just find the configuration to do so?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse and Normal Mouse

#### Device information:

Type of Mac: MacBook Pro (non-Retina)
macOS version: High Sierra 10.13.1 (17B48)
BetterTouchTool version: 2.310

**Comment by fifafu** [comment]
Centering a window is possible, however currently it doesn't resize the window. It just takes it like it is and centers it on your monitor.
You can use custom snap areas if you want to have this behavior when dragging a window to the bottom of the screen.

Is this what you want, or does it need to be resized as well?

The Snap Area would need to be set up like this:
![image](https://user-images.githubusercontent.com/8820811/32701061-916b11a8-c7cf-11e7-9803-7153e4642cc2.png)
