### ISSUE TITLE
Mouse Hover Not Working on External USB Mouse

### ISSUE THREAD

**Issue by jamesterr556** [fifafu/BetterTouchTool#1703]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Mouse hover does not work with one of my mouses. I added the left click as a button then deleted it and then my mouse stopped hovering. Only effects one of my mouses. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Regular mouse. 

#### Device information:

Type of Mac: MacBook Air (13-inch, Early 2014)
macOS version: Version 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, I don't think BTT could cause this. Have you tried to restart your machine?

**Comment by jamesterr556** [comment]
Hi,

I’ve tried restarting my computer, a clean OSX install, uninstalling BTT and reseting the pram and smc. It literally happened after I assigned the left click button in BTT and then I unassigned it and it stopped working.

**Comment by fifafu** [comment]
Ah, but if BTT is closed/uninstalled it is definitely not caused by BTT (BTT doesn't do anything if it's closed)

**Comment by jamesterr556** [comment]
My thoughts were that it reset something on my computer.

**Comment by fifafu** [comment]
It doesn't modify any system settings. Did you maybe install some driver for your mouse? What kind of mouse is it?

**Comment by jamesterr556** [comment]
It's a Microsoft ergonomic mouse and no I didn't. The hovering works on my track pad not on my mouse.

Do know how to reset it?

Kind Regards,

James Tam
