### ISSUE TITLE
Issue with External Magic Trackpad 2

### ISSUE THREAD

**Issue by sparticvs** [fifafu/BetterTouchTool#1704]
#### Description of bug/feature request/question:
External touchpad (Magic Trackpad 2) does not recognize any actions registered with BTT. I can still make these actions with the built in touchpad on the MBP.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad 2

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.13.2 Beta
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I am not sure if this is due to the new version of BTT or if it's because of the new beta. I updated both at the same time.

**Comment by fifafu** [comment]
see #1693
