### ISSUE TITLE
[Question] How can I use my mouse button to simulate holding down Shift?

### ISSUE THREAD

**Issue by swordsx48** [fifafu/BetterTouchTool#1708]
#### Description of bug/feature request/question:

Seems like something pretty simple to do. I must be an idiot with BTT. I set my side mouse button to act as shift key down, but then it just stays 'down'. When I let it go, I want the shift key to come back up. I wasn't able to assign an action upon letting go of the button, and I wasn't able to find a 'hold shift' action to use instead. Any suggestions? This should be easy! I know I'm doing something wrong. Thanks in advance!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Normal Mouse

#### Device information:

Type of Mac: iMac 14,2
macOS version: 10.12.3
BetterTouchTool version: 2.313

**Comment by fifafu** [comment]
To do this you need to create two separate triggers. One that triggers on mouse down (default) and one that triggers on mouse-up (can be configured via the little gear icon next to the recorder field).

See this screenshot:
![image](https://user-images.githubusercontent.com/8820811/32700709-14b7e588-c7c9-11e7-968c-46a6b13a6da9.png)
