### ISSUE TITLE
Feature/Setting: Customizable Margin between Global Actions & App-Specific in Touch Bar

### ISSUE THREAD

**Issue by dafurman** [fifafu/BetterTouchTool#1709]
#### Description of feature request:
Can a preference be added to adjust the margin between global actions and app specific actions?
I'd like a little bit more space between the two, and ideally it should be customizable.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:
Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.13
BetterTouchTool version: 2.311 (688)

**Comment by fifafu** [comment]
I think for now it's easiest to just add a black button without label and adjust the size by using the "free space after button" (can be negative) and/or "extra padding (inside) values"

Like this: (copy & paste into BTT)
```
{
  "BTTTouchBarButtonName" : " ",
  "BTTTriggerType" : 629,
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTEnabled" : 1,
  "BTTOrder" : 4,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemIconHeight" : 22,
    "BTTTouchBarItemIconWidth" : 22,
    "BTTTouchBarItemPadding" : 0,
    "BTTTouchBarFreeSpaceAfterButton" : "-20.000000",
    "BTTTouchBarButtonColor" : "0.000000, 0.000000, 0.000000, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarAlternateBackgroundColor" : "0.000000, 0.000000, 0.000000, 0.000000"
  }
}
```

I'll close here as I think this is a good enough solution, but I'll keep it in mind as a extra feature when I rework the TouchBar stuff.

**Comment by dafurman** [comment]
Oh that's actually a great idea. I didn't think making it black would actually make it totally invisible. Thanks!
