### ISSUE TITLE
BTT icon appears in middle of touch bar

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#171]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have a global keyboard gesture defined that switches to a preset.  In the preset, I have a global touch bar button that launches Activity Monitor and then returns to the default preset. (I don't have a BTT-defined TB for Act. Mon.)  If I use the global keyboard gesture and then the global TB button to start Activity Monitor, and then quit Activity Monitor with Command-Q, I find that the BTT icon is now in the middle of the BTT-defined TB of the current active app.  The BTT icon also properly appears at the left side of the TB. 

Note that I have system keyboard setting "TB shows app controls", and all of my BTT-defined TBs have behavior "show BTT TB, hide system control strip", and I have general BTT TB settings "show macOS controls strip", "show BTT icon in control strip", "show BTT icon on left side if control strip hidden"

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.978

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks for reporting! Does this only happen when switching presets? Or have you encountered other situations that also caused that?

Does unchecking the "show btt icon on left side if control strip is hidden " fix it?

**Comment by CappyD** [comment]
Yes, that does fix it... though, of course, then I don't have the icon to switch to the app's default touch bar.  But hopefully that gives you a clue where the problem is.

**Comment by CappyD** [comment]
Related to this is another issue using the above set up:  if I use my global keyboard gesture while the active app is one without a BTT-defined touch bar, then the preset's global TB does not display.  It works (the preset's global TB displays) if I start from an app with a BTT-defined TB. Shouldn't the preset's TB display regardless of the currently active app?

**Comment by fifafu** [comment]
Should be fixed with the next update.
