### ISSUE TITLE
Unable to Mark Key Sequence Order as Irrelevant

### ISSUE THREAD

**Issue by ilyakam** [fifafu/BetterTouchTool#1710]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I am unable to mark the Key Sequence order as irrelevant.

##### Steps to reproduce:

1. Record a key sequence for <kbd>ctrl</kbd><kbd>shift</kbd><kbd>esc</kbd> to `Launch Activity Monitor.app`
1. Attempt to set it so that I don't necessarily have to press <kbd>ctrl</kbd>, then <kbd>shift</kbd>, then <kbd>esc</kbd>
1. Get frustrated with the fact that the checkboxes for "Order Relevant" cannot be unchecked
1. Get frustrated with the fact that a shortcut containing <kbd>esc</kbd> cannot be recorded

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Keyboard and External Apple Keyboard

#### Device information:

I've tested on two machines:
Type of Mac: MacBook Pro (15-inch, Late 2011) & MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.11.6 and 10.13.2 Beta (17C60c)
BetterTouchTool version: 2.310 (687) and 2.313 (691)

##### Screenshot

![sequence](https://user-images.githubusercontent.com/183227/32476251-f65ad160-c32a-11e7-893e-d29893313286.png)

##### Workaround

The workaround is to remember to press and hold the buttons in order. First <kbd>ctrl</kbd>, then <kbd>shift</kbd>, and then <kbd>esc</kbd>.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

that's expected behavior, BTT can only handled random orders for the UP Keys.

You can however use a normal shortcut, not key sequence to achieve your desired behavior.
Copy & paste this json into BTT:

```
{
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : 49,
  "BTTPredefinedActionName" : "Open Application \/ File \/ Apple Script …",
  "BTTLaunchPath" : "file:\/\/\/Applications\/Utilities\/Activity%20Monitor.app",
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 53,
  "BTTShortcutModifierKeys" : 393216,
  "BTTOrder" : 3
}
```

I think there might have been a bug with recording some special keys like esc. This will be fixed with the next update.
