### ISSUE TITLE
Three finger click and Three finger tap not working

### ISSUE THREAD

**Issue by justplainlawr** [fifafu/BetterTouchTool#1711]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Created an gesture for three finger click and three finger tap, to be mapped to mouse middle click, both global in app and in Safari. Does not seem to be recognized, looks like the gesture is just interpreted as a left click.

#### Device information:

Type of Mac: 2016 MacBook Pro Touchbar 13"
macOS version: 10.13.2 Beta (17C60c)
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #1693
