### ISSUE TITLE
ctrl+cmd+arrow shortcut not being captured

### ISSUE THREAD

**Issue by yasseryahia** [fifafu/BetterTouchTool#1713]
#### Description of bug/feature request/question:
I used to have the ctrl+cmd+arrow combination to switch window between different monitors on my mac ... I tried to change the direction of the arrow from left to right and now I don't have the old combination and the new combination is not being accepted 

Every time I try to use this as a shortcut combination it just doesn't take it and asks me to type a shortcut once again!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: macbook pro
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.313

**Comment by fifafu** [comment]
Thanks for reporting. Something seems to have changed in macOS at some point. I have identified the issue and it will be fixed with the next update.

For now you can copy & paste these two jsons into BTT:

```
{
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 123,
  "BTTShortcutModifierKeys" : 9961472
}
```
```
{
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 124,
  "BTTShortcutModifierKeys" : 9961472
}
```
