### ISSUE TITLE
BTT constantly disabling trackpad launchpad and show desktop gestures

### ISSUE THREAD

**Issue by ahaswell** [fifafu/BetterTouchTool#1714]
I have a 2017 5k iMac with a magic trackpad 2 and bettertouchtool keeps disabling the "launchpad" and "show desktop" gestures in system preferences > trackpad > more gestures. I try to do a pinch gesture to get to the launchpad only to find the gesture has been disabled, re-enable it in system preferences only to have it disabled again within a day. This is driving me crazy. I have a macbook pro and it does not do the same thing i've never had these auto disabled on the macbook pro. I've had it happen on two different 2017 imacs. Please advise.

Type of Mac: 5k iMac 2017
macOS version: 10.13.1
BetterTouchTool version: 2.313
<img width="655" alt="screen shot 2017-11-07 at 16 00 53" src="https://user-images.githubusercontent.com/16106249/32524496-e9c2bd82-c3d4-11e7-99e8-8669e646f363.png">

**Comment by fifafu** [comment]
Unfortunately I'm not yet sure what is causing this, but I'm looking into it. See this issue: #1620
