### ISSUE TITLE
Full screen touch bar bug

### ISSUE THREAD

**Issue by lejukes** [fifafu/BetterTouchTool#1715]
#### Description of bug/feature request/question:
I am currently having a problem with the touchbar feature on BTT. When I watch a video on youtube in fullscreen. The fullscreen button to the left of the touchbar is HALF blocked off (I can only see half of the button) by the (x) button to close the better touch tool on the touch bar. 

This problem occurred when I updated my mac from sierra to high sierra. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar 

#### Device information:

Type of Mac: Macbook pro touch bar 13 (2016 model)
macOS version: 10.13 (High sierra) 
BetterTouchTool version: 2.311

**Comment by fifafu** [comment]
Could you attach a screenshot of that? I'm not sure if I understand correctly - it seems to look ok here.
Which browser are you using?

**Comment by lejukes** [comment]
<img width="1085" alt="touch bar shot 2017-11-18 at 04 17 13" src="https://user-images.githubusercontent.com/33472697/32978818-8e58c9b4-cc17-11e7-8245-13cd467a92f1.png">

**Comment by lejukes** [comment]
Im currently using chrome

**Comment by lejukes** [comment]
So there's no fix? bruh

**Comment by fifafu** [comment]
Unfortunately this can not be fixed with currently available APIs ::-(
