### ISSUE TITLE
2finger force click no working with MacOs 10.3.2 Beta 2 (17C67b)

### ISSUE THREAD

**Issue by gahabana** [fifafu/BetterTouchTool#1716]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

after update to beta 2 of 10.3.2 2 finger force click no longer works.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

macbook trackpad 

#### Device information:

Type of Mac: macbook pro 13" with touchbar mid 2017
macOS version: 10.3.2. Beta 2
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #1693 (Please provide feedback to Apple if possible)
