### ISSUE TITLE
buttons in touchbar are still usable while laptop is locked.

### ISSUE THREAD

**Issue by sod1684** [fifafu/BetterTouchTool#1719]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I lock my laptop, the buttons on the touchbar are still visible, and can be used even if you don't have access to the laptop.

It should hide the buttons, or allow to show only certain ones on the lock screen. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.13.1 (17B48)
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![settings](https://user-images.githubusercontent.com/20973346/32586190-a7af8500-c51a-11e7-8eee-d189d7a225d0.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by sod1684** [comment]
As a workaround, any buttons that can potentially cause issues, I have set them to render on the right side. So the login message covers it.

**Comment by fifafu** [comment]
An even better workaround would be to add the /System/Library/CoreServices/loginwindow.app to the app list in BTT and set the app specific touchbar settings to "always show system touchbar"

**Comment by sod1684** [comment]
Awesome thanks. I set it to totally disable BTT when that app is active.

**Comment by fifafu** [comment]
Actually I think I'll just make this the official workaround, because there are also legitimate use cases where people would want the touch bar on the login screen.
