### ISSUE TITLE
Utility actions: paste custom text doesn't seem to work as it should

### ISSUE THREAD

**Issue by childrenof9** [fifafu/BetterTouchTool#172]
I would like to paste a custom text when I am using a touchbar button. It does paste text, but It pasts text I copied using cmd-c before. It is not pasting the text I put in the screen.

macbook pro 15" 2016

touchbar

sierra 10.12.2, Btt: 1.978

**Comment by childrenof9** [comment]
I did a small test: I want to use it in Ableton live in the area where you can look for plugins/samples. Here it doesn't work: it pastes text I used cmd-c on. In chrome paste custom text works as intended.

**Comment by fifafu** [comment]
Sorry for not replying to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions, please create a new issue - I'm now much more responsive than a few months ago.
