### ISSUE TITLE
Please stop asking for Accessibility Permissions when not needed.

### ISSUE THREAD

**Issue by ludagoo** [fifafu/BetterTouchTool#1721]
#### Description of bug/feature request/question:
I want to use BTT just to make my Magic Mouse 2 click on single finger tap. This seems to work great without giving BTT Accessibility Permissions. Yet BTT is constantly asking for Permissions. Installing BTT is already a leap for me because I am a big believer in keeping my macOS as vanilla as possible. This makes me want to uninstall it.

**Comment by fifafu** [comment]
Sorry, unfortunately this is not supported (BTT relies on the Accessibility API and even if it seems to work without it in some cases, it may cause random crashes or other undefined behavior.)

However I don't think the Accessibility API should worry you. I don't think there is anything that is prevented by the Accessibility API that can not be achieved by other means (although more complicated) in non-sandboxed apps like BTT. (For sandboxed apps the situation is very different though, there the accessibility api makes sense)

**Comment by ludagoo** [comment]
Ok thanks for the answer. I guess I'm not your target audience. Keep up the good work.

**Comment by fifafu** [comment]
Yup, in the past I allowed running BTT without the accessibility api, but it caused so many random bugs and a lot of wasted time. 

However if you have specific concerns about the API I'm glad to provide more information or show ways to achieve the same without the API. In my opinion the permissions provide a false sense of security.
