### ISSUE TITLE
Possibility of catching key presses while passing through corresponding action?

### ISSUE THREAD

**Issue by nathanshelly** [fifafu/BetterTouchTool#1723]
Wondering if a particular setup is possible. I would like to disable a key but allow the corresponding action through when pressing a different custom key combination. For example I would like to disable the Delete key but allow the keyboard shortcut Ctrl+H to delete a character. When I try to map Delete to No Action and Ctrl+H to Delete then Delete no longer does anything as desired but Ctrl+H also does nothing. Thanks in advance for any help/instruction anyone can give here!

**Comment by fifafu** [comment]
Hey,

you could use the "prevent recursive triggers" option in the shortcut settings. However in general Karabiner Elements is probably a better app for such remappings.

See this screenshot on how it would need to be setup in BTT:

![image](https://user-images.githubusercontent.com/8820811/32698795-8b05c7c8-c7ab-11e7-8cc8-7068023e1871.png)
