### ISSUE TITLE
Mirror Trackpad feature not working

### ISSUE THREAD

**Issue by bkudria** [fifafu/BetterTouchTool#1726]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

"Mirror trackpad orientation"  feature has stopped working.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic TrackPad

#### Device information:

Type of Mac: 2016 15in Macbook Prop
macOS version: 10.12.6
BetterTouchTool version: 2.313 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This feature worked yesterday on with 2.310. It stopped working today, and updating to 2.313 did not help.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you already tried to restart your Mac?

**Comment by bkudria** [comment]
Sorry for delay, it mysteriously started working again! Thanks!
