### ISSUE TITLE
BetterTouchTool hanging consistently, destroying user experience

### ISSUE THREAD

**Issue by brian-crane** [fifafu/BetterTouchTool#1727]
Around 10 times a day all my shortcuts stop working completely and I need to restart the application.... This is destroying my productivity.... why is BTT hanging in the menu bar and not responding?  I have to click on the BTT icon in the menu bar and then all shortcuts I entered in last few minutes execute instantly and at the same time.

I have a paid license but the program is less stable than most free applications.

i have 10.11.15 OSX El Capitan

please fix this if you can, BTT has become completely unusable for me and the issue has persisted for weeks. Can i get an older version of BTT in the mean time.  BTT has stopped working 100% of time at this point

**Comment by fifafu** [comment]
Please provide all the information asked in the GitHub issue  template.

In case BTT hangs please run this terminal  command and attach the file that was created on your Desktop.

sample BetterTouchTool -file ~/Desktop/BetterTouchToolSample.txt
