### ISSUE TITLE
BTT Script Runner hogging CPU

### ISSUE THREAD

**Issue by sayeska** [fifafu/BetterTouchTool#1731]
Been having issues lately with battery draining quickly, and my MacBook heating up. Found the culprit to be the BTT script runner. This resolves upon force-quitting the process, or upon restarting BTT. It does recur consistently about 30 mins after force-quitting the process on activity monitor. I have only 3 (very simple) scripts running every 5 seconds interacting with Spotify. 

Device is a standard late 2016 rMBP 13" with touch bar. 
Latest version of BTT is installed.
Screenshot below

<img width="415" alt="screen shot 2017-11-13 at 19 14 09" src="https://user-images.githubusercontent.com/29161417/32744458-74fdad04-c8a7-11e7-8b3e-f074e6b4f335.png">

**Comment by fifafu** [comment]
Could you posts your script here?

**Comment by sayeska** [comment]
Sure. One script to display current song. Another two to change icon to reflect whether repeating/shuffling is active: 
<img width="607" alt="screen shot 2017-11-13 at 20 02 33" src="https://user-images.githubusercontent.com/29161417/32746512-c9496e4c-c8ad-11e7-819a-979b8906ad4d.png">
<img width="600" alt="screen shot 2017-11-13 at 20 01 28" src="https://user-images.githubusercontent.com/29161417/32746516-cc4f154c-c8ad-11e7-9408-af72c56538a5.png">
<img width="614" alt="screen shot 2017-11-13 at 20 00 45" src="https://user-images.githubusercontent.com/29161417/32746518-ce505c8e-c8ad-11e7-9127-1fa7596cf4f4.png">

**Comment by sayeska** [comment]
I do have other scripts that I've "turned off" by choosing the display only if 'x' modifier is pressed.

**Comment by fifafu** [comment]
thank you! I'll try running the scripts you posted on my machine and see whether that let's me reproduce the issue.

**Comment by sayeska** [comment]
It's been a couple of hours now with no recurrence. Turns out this script was the culprit, an old battery % solution. Ill leave it below in case that helps at all with patching, although its probably just an issue with the script itself. 

<img width="693" alt="screen shot 2017-11-13 at 22 30 34" src="https://user-images.githubusercontent.com/29161417/32752853-a3089694-c8c2-11e7-909a-1ac48aba1289.png">

> on returnnumbersinstring(inputString)
> 	set s to quoted form of inputString
> 	do shell script "sed s/[a-zA-Z\\']//g <<< " & s
> 	set dx to the result
> 	set numlist to {}
> 	repeat with i from 1 to count of words in dx
> 		set this_item to word i of dx
> 		try
> 			set this_item to this_item as number
> 			set the end of numlist to this_item
> 		end try
> 	end repeat
> 	return numlist
> end returnnumbersinstring
> 
> set value to returnnumbersinstring(do shell script "ioreg -l | grep -i capacity | tr '\\n' ' | ' | awk '{printf(\"%.2f%%\\n\", $10/$5 * 100)}'")
> -- will output...
> -- 79.63%
> 
> set valueround to (round value)
> set symbol to "%"
> set display to valueround & symbol
> set final to display as text
