### ISSUE TITLE
Upper Left Hand Corner Glitches Mouse To Move Current Window Open

### ISSUE THREAD

**Issue by Gibby116** [fifafu/BetterTouchTool#1733]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question: 
Whenever I bring my mouse, whether it be on my trackpad or an external mouse, to the upper left hand corner on my screen, my mouse immediately moves my current window open to where it is, or moves it somewhere else on screen.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mouse
In the form of a trackpad or external. 

#### Device information:

Type of Mac: 2015 Macbook Pro
macOS version: High Sierra 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![untitled](https://user-images.githubusercontent.com/33639873/32760641-3071c740-c8bd-11e7-9039-f1ff9d78e502.gif)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you maybe have some action setup for "Move Mouse To Top Left Corner" in the other tab in BTT?

<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/32858116-a44c6e3e-ca4a-11e7-86bc-f934a0f931c2.png">

**Comment by Gibby116** [comment]
I'm an idiot. That was indeed the problem. 

Thanks-
