### ISSUE TITLE
An error occurred while saving

### ISSUE THREAD

**Issue by Axelph** [fifafu/BetterTouchTool#1735]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---
 I get a pop-up from time to time saying "An error occurred while saving" after I restored from a Time Machine backup.

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.13.1
BetterTouchTool version: 2.313 (691)

<img width="432" alt="screen shot 2017-11-13 at 23 04 48" src="https://user-images.githubusercontent.com/9390363/32765932-ed186ae6-c8c9-11e7-8dcf-8f3314811f47.png">

<img width="1183" alt="screen shot 2017-11-13 at 23 26 54" src="https://user-images.githubusercontent.com/9390363/32765998-2b235b70-c8ca-11e7-81d1-05554bcef6fb.png">

---

I got this from the Console app: error: Attempt to add read-only file at path file:///Users/UserHere/Library/Application%20Support/BetterTouchTool/btt_data_store.v2 read/write. Adding it read-only instead. This will be a hard error in the future; you must specify the NSReadOnlyPersistentStoreOption.

**Comment by fifafu** [comment]
Hi Alex,

something seems to be wrong with the file permissions of the BTT database.
The files are located in ~/Library/Application Support/BetterTouchTool

Changing the permissions to something like 755 should work using this terminal command
```
sudo chmod -R 755 ~/Library/Application\ Support/BetterTouchTool  
```

**Comment by Axelph** [comment]
That worked! Thank you!
