### ISSUE TITLE
Feature: paste uuid

### ISSUE THREAD

**Issue by Torbilicious** [fifafu/BetterTouchTool#1737]
#### Description of bug/feature request/question:
I find myself often in the situation to generate a uuid and paste it somewhere. I would find it usefull to be able to automate this with betterTouchtool.

I could even imagine this feature to be extended to be able to execute a shell command and paste its output.
For example for the uuid: paste the result of `uuidgen | tr 'A-Z' 'a-z'` at the current position.
But this should be mode complicated and therefore optional :)

**Comment by fifafu** [comment]
Would something like this work for you? (See screenshot)
<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/32857609-a2be3626-ca48-11e7-878e-3b0860bc4dc8.png">

Basically it executes this terminal command: ```uuidgen | tr 'A-Z' 'a-z' | pbcopy```, then waits for 0,2 seconds to be sure, and then sends cmd+v to the system.

You can copy & paste this json into BTT:
```
{
  "BTTTriggerType" : 104,
  "BTTTriggerTypeDescription" : "3 Finger Tap",
  "BTTTriggerClass" : "BTTTriggerTypeTouchpadAll",
  "BTTPredefinedActionType" : 137,
  "BTTPredefinedActionName" : "Execute Terminal Command",
  "BTTTerminalCommand" : "uuidgen | tr 'A-Z' 'a-z' | pbcopy",
  "BTTEnabled" : 1,
  "BTTOrder" : 0,
  "BTTAdditionalActions" : [
    {
      "BTTTriggerType" : -1,
      "BTTTriggerClass" : "BTTTriggerTypeTouchpadAll",
      "BTTPredefinedActionType" : 129,
      "BTTPredefinedActionName" : "Delay Next Action",
      "BTTDelayNextActionBy" : "0.200000",
      "BTTEnabled" : 1,
      "BTTOrder" : 0
    },
    {
      "BTTTriggerType" : -1,
      "BTTTriggerClass" : "BTTTriggerTypeTouchpadAll",
      "BTTPredefinedActionType" : -1,
      "BTTPredefinedActionName" : "No Action",
      "BTTShortcutToSend" : "55,9",
      "BTTEnabled" : 1,
      "BTTOrder" : 1
    }
  ]
}
```

**Comment by Torbilicious** [comment]
Sorry for the late reply, but yes something like this should work for me
