### ISSUE TITLE
Plus character (+) not being recognized in keyboard shortcut

### ISSUE THREAD

**Issue by cygvis** [fifafu/BetterTouchTool#174]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request…:
Whenever I try to create keyboard shortcut action that includes a SHIFT-modifier, BTT doesn’t recognize the alternative character (should be + instead of =). 

For example, I’m trying COMMAND-SHIFT-“+“ but BTT only shows COMMAND-SHIFT-“=“.

I use this shortcut for the macOS zoom accessibility feature. 

**What kind of Mac are you using?**
MacBook Pro (Retina, Mid 2012) (10,1)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackad (⬅︎ misspelled, btw)

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 (16C67)
BTT 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
<img width="167" alt="screenshot 2016-12-27 at 7 16 11 pm" src="https://cloud.githubusercontent.com/assets/1134679/21511663/03f05d68-cc69-11e6-9b5b-5d4f53be45f7.png">
<img width="164" alt="screenshot 2016-12-27 at 7 16 00 pm" src="https://cloud.githubusercontent.com/assets/1134679/21511664/040dc8a8-cc69-11e6-99e5-b4597d4494b7.png">

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by tmmcz** [comment]
UPDATE: I realized I was using the wrong keyboard modifiers. It’s actually COMMAND-OPTION-“+” to zoom.

BTT recognizes it okay, but it still shows as “=“. Not a big deal. Just confusing maybe.
<img width="181" alt="screenshot 2016-12-27 at 7 24 33 pm" src="https://cloud.githubusercontent.com/assets/1134679/21511745/3f9db65c-cc6a-11e6-8c90-2159140c11a0.png">
