### ISSUE TITLE
TipTap (1 Finger Fix) firing twice on CMD+Click

### ISSUE THREAD

**Issue by rudifer** [fifafu/BetterTouchTool#1740]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Noticed less than a week ago though previously worked steady since originally configured 3 years ago. TipTap Left (1 Finger Fix) for CMD+CLICK is set so that new links open in new tab. 3/5 times it opens new tabs twice instead of once.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad 

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: High Sierra - 10.13.2 Beta
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Haven't come up with a workaround yet. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by piotrnikov** [comment]
Hey I'm having the same problem which seems to have appeared with the most recent beta.
In my case it's the 4 Finger Tap (which I've assigned to a Middle Click), that seems to double Click really fast when I activate it.
I tried fooling around with some settings but nothing has worked so far...

**Comment by fifafu** [comment]
If you are on the latest developer beta make sure to update BTT to v2.314

**Comment by piotrnikov** [comment]
Ahh! I didn't know a new version had come out (I was still on 313 and clicking Check Alpha version wasn't telling me anything). 
I downloaded the new version from your blog. And the double tapping problem I was having seems to have gone away (at least for me).
Thanks!!!

**Comment by rudifer** [comment]
Same, just found that updated link to 2.314 and updated. So far so good.
Thanks!
