### ISSUE TITLE
ctrl + alt + arrow keys not working

### ISSUE THREAD

**Issue by NoKnowYou** [fifafu/BetterTouchTool#1741]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
ctrl + alt + arrow keys not working. 
Any other combination with (ctrl + alt + "X") is working. Only the arrow keys are not recognized in this combination. 
This issue occurred with upgrading from Sierra to High Sierra. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Air 13-inch, Early 2015
macOS version: 10.13.1 High Sierra
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

this should be fixed in this build: https://bettertouchtool.net/releases/btt2.314b.zip (it's not yet available via autoupdate, but will be in a few days)
