### ISSUE TITLE
No Differentitation Between 4 Finger Tap & Double-tap

### ISSUE THREAD

**Issue by kenreeser** [fifafu/BetterTouchTool#1743]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The latest version of BTT won't differentiate between a 4-finger tap and double-tap—regardless of the  how long I set the 3 & 4-finger double-tap delay setting. The 4-finger double-tap overrides the 4-finger tap approximately 90% of the time.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
2015 MBP trackpad

#### Device information:

Type of Mac: 2015 MBP
macOS version: 10.13.1
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check if this also happens in this build? (Because I currently seem to be unable to reproduce it):

https://bettertouchtool.net/releases/btt2.314b.zip

**Comment by kenreeser** [comment]
Hi Andreas,

That fixed the problem with the 4-finger tap & double-tap conflicting one another—actually the 4-finger double-tap kept appearing no matter whether I did a single or double-tap. Thanks very much for fixing this so quickly.

Regards,

Ken Reeser
Phone & Text: 407.409.3875
E-mail: ken@reesers.us
LinkedIn Profile: http://www.linkedin.com/in/kenreeser2

___________________________________________________________________________

**Comment by fifafu** [comment]
Awesome - in case this happens again, please let me know.

**Comment by kenreeser** [comment]
Hi Andreas,

It looks like you'll need to re-open this ticket because the update you sent out this morning, didn't seem to include the fix you incorporated in the special version you sent me (see your past message below). I just re-downloaded that version and installed it. Please send out another update with the fix included. The issue was 4-finger tap & double-tap conflict with one another—actually the 4-finger double-tap kept appearing no matter whether I did a single or double-tap and it's back. Thanks very much.

Regards,

Ken Reeser
Phone & Text: 407.409.3875
E-mail: ken@reesers.us
LinkedIn Profile: http://www.linkedin.com/in/kenreeser2

___________________________________________________________________________

**Comment by kenreeser** [comment]
Hi Andreas,

Please review this thread. I've reported the 4-finger issue reappeared on 12/1/17 and it still persists in version 2.324 (709). Please fix again—It's very aggravating.

Regards,

Ken Reeser
Phone & Text: 407.409.3875
E-mail: ken@reesers.us
LinkedIn Profile: http://www.linkedin.com/in/kenreeser2

___________________________________________________________________________
