### ISSUE TITLE
Assigning only Modifier Keys to mouse buttons

### ISSUE THREAD

**Issue by Hugovdd** [fifafu/BetterTouchTool#1746]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi, is there any way of having a mouse button act as a combination of keyboard modifier keys?
For example: Mouse Button 5 + 1 would output CMD + SHIFT + 1

Thanks

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Multibutton mice

**Comment by fifafu** [comment]
It should be possible like this:
(you can configure a button to trigger on mouse down or mouse up by clicking the little gear icon on the left of the mouse button recording field)

<img width="1099" alt="grafik" src="https://user-images.githubusercontent.com/8820811/32911012-24824a68-cb0b-11e7-8a00-916fac6bf11b.png">

**Comment by Hugovdd** [comment]
I'm an idiot, I thought UP and DOWN were key arrows. THANK YOU

**Comment by tpj2018** [comment]
Is there a way to do this the other way around?

I would like to have a mouse click DOWN action as well.
