### ISSUE TITLE
No Force Touch Feedback on High Sierra

### ISSUE THREAD

**Issue by targumanu** [fifafu/BetterTouchTool#1749]
#### Description of bug/feature request/question:

After upgrading to High Sierra, there is no haptic feedback for force touch gestures assigned in BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2

#### Device information:

Type of Mac: iMac (21.5-inch, Late 2012)
macOS version: High Sierra 10.13.1 (17B48)
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Due to Apple dropping support for APFS on HD/Fusion drives, I had to re-install macOS. The issue persists even after a clean OS install.

**Comment by fifafu** [comment]
See #1558 (I yet need to figure out whats causing this however there are some workarounds in that thread). Only very very few users have reported this issue, thus I assume it's limited so some specific hardware.
