### ISSUE TITLE
v2.314 doesn't seem to work on my macOS 10.13.2 Beta machine

### ISSUE THREAD

**Issue by martinlabuschin** [fifafu/BetterTouchTool#1751]
#### Description of bug:

Just purchased, since this claims to work in macOS 10.13.2 Beta. Unfortunately, it doesn't.
Configuration:
<img width="1127" alt="screen shot 2017-11-17 at 14 06 39" src="https://user-images.githubusercontent.com/4237881/32948746-9cad8f76-cba0-11e7-8cce-5fc3f9772d84.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad
Magic Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.13.2 Beta (17C67b)
BetterTouchTool version: 2.314

**Comment by fifafu** [comment]
Update to the latest macOS beta.

**Comment by martinlabuschin** [comment]
works, thank you!
