### ISSUE TITLE
[Request] BTT TouchBar should not move the esc key

### ISSUE THREAD

**Issue by c-mendoza** [fifafu/BetterTouchTool#1753]
When using a custom BTT Touch Bar and displaying the system Control Strip, the `esc` key is moved to the right to make way for the BTT close button (the x in a circle). The request is to have an option so that the `esc` key remains where it always is, and the close button is placed on the right... or perhaps to not display the close button at all, given that pressing the BTT button in the Control Strip closes the BTT Touch Bar.

**Comment by fifafu** [comment]
Unfortunately this is not possible due to API limitations. (Only if you disable the system control strip in the general touchbar settings in BTT)

**Comment by c-mendoza** [comment]
Ah, good to know. Thanks.
