### ISSUE TITLE
5f tap problem

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#1754]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
my 5f tap always end up double triggering,

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

macbook pro 25" 2016

#### Device information:

Type of Mac:macbook pro 15"
macOS version: 10.13.2 Beta (17C79a)
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If you are on the developer beta, please upgrade to v2.314

**Comment by justinpma** [comment]
my latest update only show 2.313

**Comment by fifafu** [comment]
ALso if you check alpha updates?
In that case please download here:  https://bettertouchtool.net/releases/btt2.314b.zip

**Comment by justinpma** [comment]
that works thank you
