### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by baernabyjones** [fifafu/BetterTouchTool#1756]
#### Description of bug/feature request/question:
I have not been able to figure out a way to have multiple fingers be able to simply control the mouse tracking. I would like to be able to use 4 or 5 fingers just to control the mouse instead of having to use a single finger to move the pointer. Is this not an option or am I just too dumb to figure out how to enable this?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by theonlygusti** [comment]
I can see cases in which this would be useful.

E.g. playing minecraft with a bow requires you to "right"-click, I use two fingers to do that, but then trying to aim can trigger the scrolling.

So, in this case, two fingers to control mouse movement instead of scrolling would be useful. I bet there are many more cases besides.

**Comment by fifafu** [comment]
It could be useful. However it'd be very complicated to add, as BTT would need to override various system behavior. Currently I don't think this will be added to BTT.

Sorry!
