### ISSUE TITLE
Microsoft Remote Dekstop: Modifier keys don't work as expected.

### ISSUE THREAD

**Issue by chebz** [fifafu/BetterTouchTool#1757]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Microsoft Remote Dekstop: key combinations don't work. e.g. Shift+any letter (Shift+A) should produce capital 'A', instead produces 'a'. Same if trying to make a button with multiple actions (e.g. 1. Shift down, 2. A, 3. Shift Up - would still produce 'a' in RDP). Same for other modifier keys. They work on their own but not in combination. Another example is alt+tab - both keys work on their own, but not in a combination.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch bar

#### Device information:

Type of Mac: MB Pro 2017
macOS version: 10.12.6
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
see #121 (there may be a solution soon)
