### ISSUE TITLE
Fn key to show control strip not working with BTT in High Sierra

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#1758]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I just installed High Sierra on my MBP. I have been using BTT with the macOS keyboard settings: Touch bar shows: App Controls, and Press Fn key to: Show Control Strip. And for every app I have in BTT, I use App Specific: Touch bar behavior: Show BTT bar, hide control strip. Before I installed High Sierra (I was running Sierra), this allowed me to define the entire touch bar and to press Fn to pop up the macOS control strip. But now under High Sierra, pressing Fn does nothing - that is, the BTT-defined bar for the current app stays displayed. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
touch bar

#### Device information:

Type of Mac: 2016 MacBook Pro 13"
macOS version: 11.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to be working fine here, but I'm running the developer beta of 10.13.2. So Apple may have fixed it in that version already.

You could maybe workaround it by disabling BTT when fn is pressed (see screenshot)

<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/32993787-54c0c0a2-cd5d-11e7-8ebb-d92da223f383.png">

**Comment by CappyD** [comment]
yep... that trick works. Thanks Andreas. Hopefully it will be back to normal in 10.13.2 since that's what you're seeing.
