### ISSUE TITLE
Typo under "How to connect Siri Remote"

### ISSUE THREAD

**Issue by rich86** [fifafu/BetterTouchTool#176]
#### Description of your bug/question/feature request...:
After clicking upon "How to connect Siri Remote" to access the window "Pairing your Siri Remote with your Mac", a message appears: "Status: Siri Remote Connected Successfuly". - "Successfully" is spelt incorrectly.

**Which versions of macOS and BetterTouchTool are you running?**
System Version: macOS 10.12.3 (16D17a)
BetterTouchTool: Version: 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
<img width="480" alt="screenshot 2016-12-28 12 03 39" src="https://cloud.githubusercontent.com/assets/74527/21521720/76831d96-ccf7-11e6-995f-2cd003c63d97.png">

**Comment by fifafu** [comment]
Fixed with next update (release tomorrow)
