### ISSUE TITLE
Touch bar becomes unresponsive in Mission Control mode

### ISSUE THREAD

**Issue by x600** [fifafu/BetterTouchTool#1760]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

1) Added button to toggle Mission Control mode
2) When this mode is on, BTT touch bar is not reacting (Even escape). The only way to exit this mode is to use keyboard escape button (i have +- button assigned to escape)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch bar

#### Device information:

Type of Mac:
 - Late 2016, 13''
macOS version:
- high sierra latest
BetterTouchTool version: 
- 2.313
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately Mission Control seems to block the touches - this may not be fixable.

**Comment by x600** [comment]
Maybe then to show system control strip in this mode? In this case at least escape will work? And it will be possible to say add Mission Control button to system control strip to toggle it back...

Otherwise you get stuck there ;)

**Comment by fifafu** [comment]
There is no way to programatically detect whether Mission Control is active or not as far as I know. Thus I can not just hide the Touch Bar for Mission Control (I could hide it based on the BTT action but not bring it back afterwards) ...

You can just click somewhere, so I don't think it's that bad.

**Comment by x600** [comment]
On another topic: it is possible to figure "muted" state and show a different icon/change button bg color?

**Comment by fifafu** [comment]
that should be possible using apple script, but I currently don't have a ready to use one abailable.
This could help: https://github.com/fifafu/BetterTouchTool/issues/436

**Comment by jxie0755** [comment]
This is very unfortunate I guess. Originally I use trackpad gestures for a lot of commands but only F3 key for mission control. Because I can hit F3 with left hand, and use right hand to move the cursor to the window I want, and hit F3 again to switch to the window. This gives me a "left, right, left" pace to do things very fast when a lot of switching needs to happen.

Now I guess I need to have a new habit of "left, right, right" now. It wasn't that bad if I use mouse, but very uncomfortable if use the trackpad. 

Anyway, all the other functions of BTT on touch bar has been great, thanks!

**Comment by fifafu** [comment]
Unfortunately it doesn't look like it's possible to fix this. macOS just disables the App Touch Bar when Mission Control or Application Switcher is active.

I'd recommend to map capslock key to esc in System Preferences => Keyboard => Modifier Keys. It takes some getting used to, but is a pretty good ESC replacement.
