### ISSUE TITLE
BTT Using significant battery

### ISSUE THREAD

**Issue by justinp320** [fifafu/BetterTouchTool#1762]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I don't really know what the energy impact numbers exactly mean on activity monitor but I've never seen any application use this much energy

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
I only use BTT to have my spotify now-playing and music controls on the touch bar and I cannot understand how that is using so much energy

#### Device information:

Type of Mac: 2016 Macbook Pro 15"
macOS version: 10.13 High Sierra
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<img width="729" alt="screen shot 2017-11-19 at 3 45 24 pm" src="https://user-images.githubusercontent.com/33816208/32997162-0271d078-cd41-11e7-9a70-e761eb1f8e71.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Probably your script is generating some high CPU usage, BTT itself shouldn't use that much.
Could you send me an export of your setup? (boastr.net@gmail.com, you can use the Manage Preset => Export functionality)
