### ISSUE TITLE
Feature: possibility to search w/ other engine than Google

### ISSUE THREAD

**Issue by Buzut** [fifafu/BetterTouchTool#1765]
#### Description of feature request:

Hi,
I've been using BTT for several year now and it is awesome! 

I'm using a lot the ability to select a text and tap (or whatever you configure) to start a Google search on that selection. Would it be possible to configure the search engine used for that? Or at least to use the browser's default engine?

Thanks

**Comment by fifafu** [comment]
You can use the "Open URL With Selection" action. This allows you to input any URL e.g. 
https://www.google.de/search?hl=de&q=%@

The %@ will be replaced with the selection.

**Comment by Buzut** [comment]
No wayyyyyyy! I thought it was missing for so long, and yet it was at my fingertips.
This is absolutely awesome. `https://duckduckgo.com/?q=%@` and search is now made with DuckDuckGo.

Thank you for your prompt answer btw.

Best
