### ISSUE TITLE
Crash when putting the computer to sleep

### ISSUE THREAD

**Issue by matrouthier** [fifafu/BetterTouchTool#1767]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I notice that the app has closed almost one time out of three when I open the lid of my MacBook Pro Retina.  I use only the most basic features.  I would really expect more stability.

#### Device information:

Type of Mac: MacBookPro
macOS version: latest, 10.13.1
BetterTouchTool version: latest, 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I don't see crash logs in Console.app?

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, maybe something on your system is blocking BTT from restarting correctly after sleep?

Could you check whether the BTTRelaunch process is running in activity monitor after starting BTT?

**Comment by matrouthier** [comment]
Yes, BTTRelaunch is running right now.

I'm not sure what's going on.  I have a MacBook Pro (15-inch, Late 2016), with the fingerprint sensor.  This is how I log in after I wake the computer up.

Mathieu


On Nov 21, 2017, at 2:02 AM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


That's weird, maybe something on your system is blocking BTT from restarting correctly after sleep?

Could you check whether the BTTRelaunch process is running in activity monitor after starting BTT?

**Comment by fifafu** [comment]
In case this happens again - If possible, please go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. It would be great if you could send that to boastr.net@gmail.com

**Comment by matrouthier** [comment]
It happened again:
- the gestures do not react.
- the BTT icon is not in the menu bar.
- active processes include BTTRelaunch, BetterTouchTool and BetterTouchToolScriptRunner.
- BetterTouchTool uses around 1% and 5% CPU.

However, after I finished writing this, the icon had came back up by itself and now gestures work.  I'll try to pay more attention next time.

**Comment by fifafu** [comment]
BTT always restarts sleep - however this should only take a few seconds.

**Comment by matrouthier** [comment]
It needs to restart after sleep?  It can't just remain active like a regular app?


On Nov 25, 2017, at 6:16 PM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


BTT always restarts sleep - however this should only take a few seconds.

**Comment by fifafu** [comment]
Exactly. (BTT uses various undocumented APIs and the most reliable way to reset them after sleep is to restart itself.)

**Comment by matrouthier** [comment]
Regarding the time it takes to restart after a sleep, I tried to notice what's going on a bit better...  In my experienbce, actually the app always restarts fine.  However, it can take up to 30 seconds to reappear on the menu bar.  Is there anything I can do to help you improve that?

**Comment by fifafu** [comment]
I have recently made some changes that may make the restart a bit faster. I'll try to improve this even more with future updates, but that's a different issue so I'm closing here.
