### ISSUE TITLE
slow lauch

### ISSUE THREAD

**Issue by matrouthier** [fifafu/BetterTouchTool#1768]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The app takes up to 7 seconds to launch.  That's twice as long as launching Photoshop.  Something's got to be wrong!

#### Device information:

Type of Mac: MacBook Pro Retina
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Startup time can depend on many things. How many triggers do you have configured?

Also BTT may have to wait for hardware to become ready - maybe check if disconnecting any external hardware improves startup time.

Here BTT starts in about 2-3 seconds (Photoshop CC 2017 ~15 seconds)
