### ISSUE TITLE
Control strip icon needs 2 taps to reopen BTT icons

### ISSUE THREAD

**Issue by MFCBS** [fifafu/BetterTouchTool#177]
#### Description of your bug/question/feature request...:
After closing the BTT icons on the touch bar by pressing the (X) on the left edge, the BTT icon in the control strip needs 2 taps to open the icons again.

**What kind of Mac are you using?**
Late 2016 Macbook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
MacOS 10.12.2 (16C67) 
BetterTouchTool 1.978

**Comment by fifafu** [comment]
Unfortunately I can not recognize when the x button is pressed (it's a a system button without API as far as I can tell). Thus this currently can not be fixed, however I will continue looking for a solution and add it if I ever find one.

However I'll close this issue for now as there is currently no solution.

**Comment by fitzage** [comment]
Hmmm…so instead of checking if the close button is pressed, can you instead check to see if the BTT bar is already active before activating it?

I don't know anything about how this all works, so that's just me spitballing.

**Comment by fifafu** [comment]
Nope, unfortunately also no API for that as far as I can tell.

**Comment by fitzage** [comment]
OK, thanks. I'll just have to get used to deactivating it with the BTT button, if I can. It's just the other one is where the esc button normally is, so it's so easy.
