### ISSUE TITLE
Other Section of Bettertouchtool no longer working in 3.215

### ISSUE THREAD

**Issue by brockvsherman** [fifafu/BetterTouchTool#1770]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

The other section of Bettertouchtool is no longer working since 3.214. Zoom under cursor and double-click main menubar no longer perform the selected actions.

Double-click on Mouse

#### Device information:

iMac 2017
10.13.2 beta (17C79a
BetterTouchTool version: 3.215
<img width="874" alt="screen 2017-11-21 08 20 16" src="https://user-images.githubusercontent.com/33869535/33077218-d5f5a498-ce94-11e7-9a83-1da2224ba0d3.png">
<img width="874" alt="screen 2017-11-21 08 20 16" src="https://user-images.githubusercontent.com/33869535/33077236-e3105196-ce94-11e7-882a-51f4de915458.png">

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Should be fixed in 2.316 alpha

**Comment by brockvsherman** [comment]
Many thanks Andreas for the rapid update and particularly for all you hard work dealing with the 10.13.2 beta updates fiasco from Apple. Did apple again allow you to access com.apple.hid.multitouch.user-access in the latest 10.13.2 betas. If so I hope that they do not take away that which they giveth.

Have a wonderful holiday and many thanks for developing one of the most useful utilities I own.

Brock V. Sherman
brock@sherman.direct
