### ISSUE TITLE
Can't use thumb for TipTap gestures any more

### ISSUE THREAD

**Issue by jieliu8sc** [fifafu/BetterTouchTool#1771]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
On version 1.77 or earlier, I am able to use thumb instead of index finger for TipTap gestures. On later version, using thumb doesn't work anymore. This is very frustrating, as it feels much more comfortable for me to use thumb instead of index finger for TipTap gestures. Please fix this.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: 
macOS version: Sierra, 10.12.6
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can turn off thumb handling in the advanced trackpad settings.

**Comment by jieliu8sc** [comment]
Thank you! I love this tool and you should start a company focusing on this!
