### ISSUE TITLE
3/2 finger click, left/right finger harder gestures don't work

### ISSUE THREAD

**Issue by jieliu8sc** [fifafu/BetterTouchTool#1777]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
3 finger click, left/right finger harder gestures don't work at all.  2 finger click, left/right finger harder gestures get activated when I use 2 finger click.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: Sierra, 10.12.6
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can't use two/three finger clicks at the same time as the ones where one finger presses harder :-) 

How should I differentiate between what you'd like to trigger in such a setup?

**Comment by jieliu8sc** [comment]
I see. I thought in that case 3 finger click gets triggered when the force is even on all 3 finger. Maybe in the UI it should warn user about this. Thank you!

**Comment by fifafu** [comment]
The problem is that the force is never even, it's good enough to differentiate between the left/right, but not for much more :-) (you can observe this in the live view, it's quite interesting)

**Comment by jieliu8sc** [comment]
Yeah I realized that. I tested those gestures, they worked 80% of time for me.
I am wondering if you can add TipTap with 4 finger fixed. For people who uses the thumb they'd be great. TipTap gestures are the most reliable ones in my experience

**Comment by fifafu** [comment]
That should be possible. Would be great if you could create a new issue for that or change the title of this one :-)

**Comment by jieliu8sc** [comment]
Created new issue https://github.com/fifafu/BetterTouchTool/issues/1778 . Thank you Andreas
