### ISSUE TITLE
text expansion feature request

### ISSUE THREAD

**Issue by dzeruel** [fifafu/BetterTouchTool#1780]
#### Description of bug/feature request/question:
Hello! 
My request is related to #1152. It would be really nice to have Keyboard Maestro or Text Expander like features, especially text expansion. I know BTT can do it now but it would be good to improve it a little.

**Comment by fifafu** [comment]
That's already possible. Just use the key sequences feature in combination with the predefined action "paste / type custom text"

**Comment by dzeruel** [comment]
Yeah, but I used to have many snippets in other applications. 
I was able to open those snippets in floating submenus. It is possible to implement with BTT but not at a level that I could leave Keyboard Maestro.

E.g. when I change the snippet insertion to typing I don't see the content which makes the "snippet management" hard.

![image](https://user-images.githubusercontent.com/3647875/33172733-9bf17132-d051-11e7-828f-21a2c7e29b4a.png)

**Comment by fifafu** [comment]
Ah, that's a bug. :-)
I'll fix this. Submenus will be added to BTT, but this will take some time before it's released.

**Comment by edl867** [comment]
I am not sure if this is the correct place to ask, but is it possible to use keys like pagedown or pageup in the replacement predefined action? 
If so, I can't figure out how to enter them. 

What I am hoping to do is tell safari that when page down is pressed, do a page down, but then one or two up arrows. 

I want safari to pagedown, but not quite a full screen set. 
I did a lot of searching, but haven't found the path for this functionality in BTT.

**Comment by fifafu** [comment]
@edl867 something like this should work:
![image](https://user-images.githubusercontent.com/8820811/35687172-5169a608-076e-11e8-9251-a019b884a55f.png)

Just make sure to enable the prevent recursive triggers option:
![image](https://user-images.githubusercontent.com/8820811/35687222-6e314ff2-076e-11e8-9f43-8b3a85e3fd42.png)

**Comment by edl867** [comment]
Thank you, that did what I needed. I never would have gotten there on my own though.
