### ISSUE TITLE
BTT buttons next to standard macOS button without the control panel

### ISSUE THREAD

**Issue by CyborgSemon** [fifafu/BetterTouchTool#1788]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of feature request:
Is it possible to integrate the standard Touch bar customisation with BTT? For example, having both custom made buttons and widgets from BTT right next to software specific buttons? like page reload on Chrome or the Trash button on Finder?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 13" Touch bar
macOS version: 10.12.6
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

No, unfortunately there is no API do do something like this. BTT can only overlay the system Touch Bar.
