### ISSUE TITLE
Touch bar won't work in Mission Control mode 

### ISSUE THREAD

**Issue by jxie0755** [fifafu/BetterTouchTool#1796]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

For Touchbar, Mission Control function can only be used for launching mission control, I can not hit it again to quit mission control. Apple's own touch bar and the keyboard F3 button can do it this way. But if this same mission control function was used in touchpad, keyboard shortcut, mouse actions, will work very well. Only not executable in touch bar. It seems that when system is in Mission Control mode, the whole touchbar will not work until quit Mission Control, not just the one that enters Mission Control.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

macbook pro touch bar

#### Device information:

Type of Mac: anyone with a touch bar
macOS version: all os versions
BetterTouchTool version: all versions

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a known limitation: #1537

**Comment by fifafu** [comment]
Sorry I  linked the wrong issue. That should be the correct one: https://github.com/fifafu/BetterTouchTool/issues/1760
