### ISSUE TITLE
[Request] BTT Touchbar toogle while pressing a button

### ISSUE THREAD

**Issue by hiiwave** [fifafu/BetterTouchTool#1797]
#### Description of bug/feature request/question:

By using the predefined action, I could enable BTT touch bar by pressing some key (like option key), and disable it by pressing it again.

I wonder if it could be made such that the BTT touch bar is enabled during the pressing of a key, and disabled as soon as such key is released. Just like the default behavior of F1 - F12 while Fn is begin pressed.

Thanks a lot.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

**Comment by fifafu** [comment]
For every button you add to the BTT Touch Bar you can choose which modifier keys need to be pressed (after clicking the little gear icon)

Alternatively you can disable BTT competely by pressing any combination of modifier keys (this can be configured in the advanced BetterTouchTool preferences)

Or you can configure a keyboard shortcut and assign the predefined action "toggle BetterTouchTool Touchbar"

**Comment by hiiwave** [comment]
Your second suggestion is mostly what I want:
"Alternatively you can disable BTT competely by pressing any combination of modifier keys (this can be configured in the advanced BetterTouchTool preferences)"

I wonder if I can do the opposite way: enable BTT touchbar completely by pressing any combination of modifier keys, and disable BTT (hence showing the default touch bar) when that modifier key is not being pressed.

Thanks.

**Comment by hiiwave** [comment]
Oh I found that I could actually do it using your first suggestion, by assigning the same modifier key for all buttons added to the BTT touch bar.

Thanks a lot!
