### ISSUE TITLE
TipTap Right not working

### ISSUE THREAD

**Issue by djw44** [fifafu/BetterTouchTool#18]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

Upgraded to 1.961.  TipTap Right stopped working.  TipTap Left still works.  Tried deleting and re-adding as well as restarting.  No luck

**What kind of Mac are you using?**
Macbook Air 11" (late 2010)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Built in track pad on Macbook Air

**Which version of macOS are you running?**
10.11.6 El Capitan

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi!

Thanks a lot for reporting.
Just to troubleshoot: are you having your fingers "further" apart when doing the right tip tap?
I added a distance treshold to prevent accidental taps (see #7 ), maybe I need to increase that.

Does it work if you put your fingers nearer together?

**Comment by djw44** [comment]
Andreas
First of all, thank you so much for the quick reply.  I did not expect a response so quickly.

You are exactly right.  I typically use my index finger and middle finger for the TipTap.  The “spread” I use between them is my natural resting position. (I have average size hands.)  That has always worked just fine for me.  Now, with the 1.961 release, it seems intermittent at best.  However, if I move my fingers close to each other (no distance between them), the gesture works fine.  I guess I just have to remember this and put my fingers closer together.  I understand the need for the distance threshold, especially with the very wide trackpad on the nee MBPro.  (I have on order to replace my Macbook Air).  Whether you need to increase the distance threshold or not is, I guess, up to your users.  Now that I know what the issue is, I can adjust.  

Thanks again for your response.  I am a big fan of BBT.  Keep up the great work.

David


David J Weiss
davidj.weiss@yahoo.com

**Comment by wgrimshaw** [comment]
Just chiming in to say that I had the same issue; I thought that left/right tip taps were broken and spent a while trying to diagnose the issue before finding the answer here. Would a slider to customize the threshold be possible?

**Comment by trentonsmith-wf** [comment]
Adding the threshold to advanced settings would be much appreciated.

**Comment by fifafu** [comment]
I'll release an updated build that slightly increases the treshold and makes it configurable later today!

**Comment by djw44** [comment]
Awesome.  Thanks.

**Comment by fifafu** [comment]
FYI: Version 1.963 contains a slider in the advanced Trackpad preferences that let's you change the maximum allowed distance between fingers.
