### ISSUE TITLE
Global touch bar in BTT is not really global

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#180]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Probably related to #171:  If you define a touch bar button in "Global" in the default (or maybe any) preset, that button only shows when the active app has a TB defined in BTT.  Otherwise, the default TB (if any) is shown.  It doesn't seem that any of the global or app-specific TB options change this.  This does not seem consistent with the behavior of a global keyboard gesture which seems to work in any app.  

This issue seem to make it impossible to define a TB button that changes focus to an app without a BTT TB and then do something in that app.  

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.978

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Mhh the global ones should always show unless you have explicitly set that app to "Show App Default Touch Bar" in the app specific settings. Or alternatively you may have hidden the Touch Bar, then tapping the BTT icon in the Control Strip should fix it.

Are you sure that isn't the case?

**Comment by CappyD** [comment]
I have all TBs set to "show BTT TB, hide control strip" and am not hiding the TB (not sure how I would do that).  After more testing, it appears that TB buttons defined in the Global section of a particular preset only show up in the apps that are defined in the preset.  Is that correct and is that what you intended?  Note that the global keyboard gestures I've defined work in apps that are not added to the preset in which the global keyboard gestures are defined.  For example, I have defined the \ key to do forward delete as a global keyboard gesture in the Default preset.  But that key works in any app whether the app has been added to the Default preset or not.

**Comment by fifafu** [comment]
Ahh, yes presets are completely separated. If another preset is loaded BTT doesn't know anything defined in the other preset.

**Comment by CappyD** [comment]
Ok, but then how does the global keyboard gesture work outside of its preset?

**Comment by fifafu** [comment]
It shouldn't :-) that may actually be a bug that causes BTT to not unregister the previously loaded keyboard shortcuts when switching presets.

**Comment by CappyD** [comment]
Maybe I shouldn't have mentioned it (😊) because it is massively useful to be able to define a key that works everywhere.  It would be difficult to add every possible app to the preset where you would want a key like forward delete to work - could be anyplace that takes typed input.  Same basic concept with having a truly global TB button.
