### ISSUE TITLE
BTT process freezing up when pulling up clipboard history

### ISSUE THREAD

**Issue by andyconlin** [fifafu/BetterTouchTool#1800]
#### Description of bug/feature request/question:
BTT process freezing up when pulling up clipboard history.  
I just used the keyboard shortcut I have to bring up clipboard history.  The window popped up but was unresponsive.  Behind, other apps functioned as normal.  Hovering over the icon in the menu bar gives spinning beach ball, hovering over other icons (f.lux, dropbox, etc.) is standard pointer.
Stopped via Activity Monitor quit process.

I recently copied a large amount of data from an excel doc, could that be bogging it down?

Is it safe to delete these files (in `~/Library/Application Support/BetterTouchTool/`, as a temporary fix?  Will they be automatically recreated?  
![image](https://user-images.githubusercontent.com/24281063/33351143-9377cf9e-d45f-11e7-8f98-ca1960805b80.png)

Or, better yet, is there a way to access my clipboard history through another route to delete just the large clipboard items (would an .sqlite client work?)

An interesting observation: after copying something else to the clipboard, the BTT clipboard history window pops up (when requested) and functions fine (search bar works quickly, etc.) until I click on the large item in the list.  It seems that it is the rendering of large clipboard items in the preview window that is slowing it down(?).  For now, a workaround will be to copy something new then search for desired clipboard history item or scroll past the items in question.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
N/A

#### Device information:

Type of Mac: Macbook Pro (13-inch, Mid 2010)
macOS version: 10.12.6
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://user-images.githubusercontent.com/24281063/33351277-2f98340e-d460-11e7-8626-b3bf8a6a8711.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
tracking this here: #1625 (it's basically the same issue, there should be a solution soon)
