### ISSUE TITLE
Can't drag with remapped mouse button

### ISSUE THREAD

**Issue by ezuk** [fifafu/BetterTouchTool#1804]
#### Description of bug/feature request/question:

I remapped my mouse middle button to left button (it's a trackball). I am able to click and get a left click. However, dragging does not work - when I click with the "original" left mouse button I can drag, but the remapped one simply does not drag.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Kensington Expert Mouse trackball

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.12.6
BetterTouchTool version: 2.313 (691)

**Comment by fifafu** [comment]
Sorry, unfortunately that's not something BTT can do. (BTT isn't really useful for completely remapping keys or buttons, it would require deeper system integration to do this in a good way)

There are better tools for this, like USB Overdrive.
