### ISSUE TITLE
Cursor jumps around randomly when typing

### ISSUE THREAD

**Issue by IndigoHomme** [fifafu/BetterTouchTool#1805]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

In the midst of typing, the cursor jumps to another location.
If I quit BTT this doesn't happen.
The frequency is often enough that it is incredibly annoying.
Restarting BTT alleviates the issue for a while - the duration is indeterminate.
I restart the system often enough to know this isn't the issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad, MacBook Air

#### Device information:

Type of Mac: MacBook Air 2014
macOS version:  10.13.1
BetterTouchTool version: 2.315

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You probably have some gesture configured in BTT that you accidentally trigger.
Maybe corner taps?

Try deleting them or try to use the options to disable gesture recognition while typing (in the advanced trackpad prefs)
