### ISSUE TITLE
Suddenly stop working, Version Expired

### ISSUE THREAD

**Issue by lukassr** [fifafu/BetterTouchTool#1806]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The app stop working, "BTT Version Expired" message. The message say to update to the most current version, but I'm already having the last BTT version available.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All input devices.

#### Device information:

Type of Mac: MacBook Pro 15-inch, 2017, i7 2.8GHz, 16 GB RAM
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="627" alt="screen shot 2017-11-29 at 10 33 55 pm" src="https://user-images.githubusercontent.com/10482758/33409103-751e8714-d558-11e7-9532-3b9b418703f5.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by lukassr** [comment]
#

**Comment by thanhdeptrai** [comment]
I'm having the same issues, BTT doesn't work anymore! Tried all version from https://bettertouchtool.net/releases/

**Comment by gitCurator** [comment]
maybe
    related to the recent MacOS update: Security Update 2017-001 ???

PS: there were two security updates issued today(Nov 30)

**Comment by thanhdeptrai** [comment]
I saw that update but I haven't applied it yet, so I don't think that's the problem

**Comment by lukassr** [comment]
I thought about that too, but the update didn't fix it.
I also tried installing the alpha versions, like it said in #839 , but it didn't fix it either.

**Comment by croissantfriend** [comment]
I've been having the same issues. I'm on MacOS 10.13.1 and I've tried BTT 2.291, 2.313, 2.314, and 2.316.  On trying to start BTT I get the version expired error, then I'm either told that I'm on the latest version (e.g. 2.313 with Alpha updates enabled) or that I'm up-to-date. In the program, I'm told that either my Magic Mouse is disconnected or that there's a problem with drivers.
I've tried the Terminal commands from [here](https://github.com/fifafu/BetterTouchTool/issues/1179) as well.

**Comment by fifafu** [comment]
Hey,

are you on the trial version of BTT?

Best
Andreas

**Comment by croissantfriend** [comment]
Yes I am.

**Comment by hannes-ucsc** [comment]
Same here. What worked for me was to set the date forward past the trial expiration and then back. Then I purchased a license which I intended to do anyways.

**Comment by fifafu** [comment]
Sorry I think I accidentally expired the trials early today :-P
Will upload a fixed version in a few minutes.

**Comment by hannes-ucsc** [comment]
However, when I click check for update:

<img width="532" alt="screen shot 2017-11-29 at 9 51 57 pm" src="https://user-images.githubusercontent.com/5143256/33416094-a1062ac0-d54f-11e7-8b70-5a6fd52c07ae.png">

BTT is in /Applications I copied it there manually.

**Comment by fifafu** [comment]
That's an error from the sparkle updater framework, I think you may need to restart it again.

**Comment by hannes-ucsc** [comment]
Same after restart. I'll open a new ticket.

**Comment by fifafu** [comment]
A version (2.317) that fixes the expired issue is now available via autoupdate.

**Comment by croissantfriend** [comment]
Perfect, everything is back to normal now. Thanks so much!

On Nov 29, 2017, at 10:10 PM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


A version (2.317) that fixes the expired issue is now available via autoupdate.
