### ISSUE TITLE
"BetterTouchTool can’t be updated when it’s running from a read-only volume"

### ISSUE THREAD

**Issue by hannes-ucsc** [fifafu/BetterTouchTool#1807]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When selecting `Version 2.313 (691) | Check for regular updates` in the BTT icon menu I get:

<img width="532" alt="screen shot 2017-11-29 at 9 51 57 pm" src="https://user-images.githubusercontent.com/5143256/33416524-e8dd9eee-d551-11e7-9bad-9873a422a281.png">

even though it's located in /Applications

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.12.6 (16G1036)
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

A few days ago, when I first installed BTT, I ran the extracted ZIP from the Downloads folder. BTT offered to move itself, but that failed. So I copied this version manually from the extracted zip to /Applications. The zip was extracted with ForkLift, the copy was done with ForkLift, too. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by hannes-ucsc** [comment]
Gee, sorry. I just used Finder to extract the ZIP and move the bundle to /Applications. That fixes it.

**Comment by fifafu** [comment]
Ah the problem here is forklift.
Unfortunately this is a "security" feature in macOS. You need to copy it via Finder to the /Applications folder.

**Comment by hannes-ucsc** [comment]
Out of curiosity, do you know if its the extraction or the copying that's broken in ForkLift?

**Comment by fifafu** [comment]
The copying as far as I know.
It's not broken, but Apple introduced a feature called "App Translocation" which causes this when not using Finder to copy the file.

I'm not sure about the details though. I'll read up on it.
