### ISSUE TITLE
After purchasing BTT remote Pro I tried to get the lisence for BetterTouchTool for Mac but it showed me Registration Error.

### ISSUE THREAD

**Issue by tortoo** [fifafu/BetterTouchTool#1818]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

 @fifafu Hi fifafu. I purchased BTT remote Pro yesterday but couldn't get the lisence for BetterTouchTool for Mac. It showed 
![image](https://user-images.githubusercontent.com/28673736/33471513-ba128068-d6a8-11e7-9396-b49681dc49c5.png). I've already sent a mail to this address boastr.net@gmail.com but there was no reply. Please help me to check that. Thank you very much!

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mh, is your Iphone jailbroken? (Jailbreak breaks the verification process)

**Comment by tortoo** [comment]
Yeah, it's jailbroken indeed and the version is ios 9.3.2.😹

**Comment by fifafu** [comment]
If you forward me the receipt I'll generate a license manually! (Or you can use any other ios device to generate the license)

**Comment by fifafu** [comment]
(Boastr.net@gmail.com)

**Comment by tortoo** [comment]
But all my ios devices are jailbroken🙈. I've sent the mail already. Thanks!

**Comment by tortoo** [comment]
After importing the license file it took effect immediately! I do love this app!😸
