### ISSUE TITLE
BetterTouchTool Crash Report 

### ISSUE THREAD

**Issue by metronym** [fifafu/BetterTouchTool#182]
#### Description of your bug/question/feature request...:
Crash report.

**What kind of Mac are you using?**
MacBook Pro (17-inch, Early 2011)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse and MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.2
BetterTouchTool 1.963 (552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

[BetterTouchTool_2016-12-30-165821_epsilon.crash.zip](https://github.com/fifafu/BetterTouchTool/files/679050/BetterTouchTool_2016-12-30-165821_epsilon.crash.zip)

**Comment by fifafu** [comment]
I think this should be fixed in the current versions. I'm closing here. Thanks for reporting!
