### ISSUE TITLE
FEATURE REQUEST: Ability to hide 'x' icon

### ISSUE THREAD

**Issue by alphanumericcharactersorsinglehyphens** [fifafu/BetterTouchTool#1824]
As circled below. The extra room would be nice, and look cleaner

<img width="1085" alt="touch bar shot 2017-12-01 at 16 10 38" src="https://user-images.githubusercontent.com/34166754/33491724-08a8ba58-d6b3-11e7-86c9-24d45a20b115.png">

**Comment by fifafu** [comment]
Due to API limitations this is only possible if you hide the macOS control strip in the BetterTouchTool general touchbar settings.
