### ISSUE TITLE
Sliders for touch bar.

### ISSUE THREAD

**Issue by aaronweewee** [fifafu/BetterTouchTool#183]
Would it be possible to add the volume and brightness macOS control strip style button/sliders into the predefined action? For customisation purposes. :)

Albeit much more difficult, It would be really awesome if you could also include a way to add sliders into the touch bar and allow us to program it, for eg, scrubbing through a video, or music player. 
Imagine placing a small spotify scrubber on the global touch bar 💯 💯 💯 

It might not be possible, but maybe?

**Comment by fifafu** [comment]
Yes this is planned soon after the next public release is out. It will be available sometime in January.

**Comment by childrenof9** [comment]
yeah would be so great! like adding sliders with MIDI CC!!! :D

**Comment by edgardluz** [comment]
Another vote for sliders, this would allow us to hide the default MacOs Control Strip while keeping the volume/brightness sliders as well as hiding that stupid/useless X button that pushes the Esc key to a different location.

**Comment by whodean** [comment]
Is this coming?

**Comment by RoydeGroot** [comment]
Hi There! 
What is the status of this development?
Would love yo have the possibility to have a control strip like slider and ditch the controlstrip.

Thanks in advance!

**Comment by fifafu** [comment]
@RoydeGroot the current version of BTT contains a brightness slider, a volume slider and a customizable Apple Script slider.
