### ISSUE TITLE
[Suggestion] Better touch bar apple script caching

### ISSUE THREAD

**Issue by robgraeber** [fifafu/BetterTouchTool#1830]
Better touch bar apple script caching

I noticed when going from a button group back to the main BTT touch bar, all the applescript widgets reload from scratch. It would be nice if those applescript widgets showed the last seen value and only refresh if it's within it's refresh interval.

Personally half my touch bar is applescript curl requests, so it discourages me from using button groups often.

**Comment by fifafu** [comment]
This has been added in 2.332
