### ISSUE TITLE
map wired earpod button?

### ISSUE THREAD

**Issue by ursbraem** [fifafu/BetterTouchTool#1831]
#### Description of bug/feature request/question:
I saw #1434, hope I'm not duplicating. Is it possible to map the wired earpods (not airpod) button somehow? My Voip-App (from the biggest national telco...) doesn't recognize when I press it (expecting to hang up a call) – instead iTunes opens and plays Justin Timberlake

**Comment by fifafu** [comment]
Tracking this here: #167 may be possible in one of the next updates, but not yet :-(
