### ISSUE TITLE
Feature Request: Focus Follows Mouse

### ISSUE THREAD

**Issue by bobodoll131** [fifafu/BetterTouchTool#1834]
It seems to me like BetterTouchTool has all the ingredients for auto-raise focus follows mouse. It can identify which app the cursor is hovering over (i.e. when moving windows without bringing them to the front). It has a predefined action to activate window under cursor. All trackpad gestures even work on the background windows being hovered over. But however much I try, I can't combine the above capabilities to automatically activate a window being hovered over. Is it possible to combine them into a single setting or option?

Type of Mac: Macbook Pro 15" 2017
macOS version: 10.12
BetterTouchTool version: 2.318

**Comment by fifafu** [comment]
Unfortunately this would require constantly checking the window under the cursor using the Accessibility API. This would have a high energy impact and could cause various weird issues.

Thus this probably won't be added to BTT unless a better API is added to macOS.
