### ISSUE TITLE
GESTURES reported as "already in use."

### ISSUE THREAD

**Issue by chrissia33** [fifafu/BetterTouchTool#1835]
I was attempting to assign a few app-specific gestures for Colibri, Two-Finger Swipe Right and Two-Finger Swipe Left from Edge of Trackpad, both of them are demarked as "already in use."  I do have Two Finger Swipe in use in Global but I do not have Two-Finger Swipe Left From Edge in use anywhere.

I have restarted BTT as a remedy but no luck.
 

#### Device information:

Mac Pro 2013 6-core
macOS version: 10.13.1
BetterTouchTool version: 2.318 (702) 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Thank UYou
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's just a reminder because it will override the global gestures for that app. You can ignore it if you are aware of that.
