### ISSUE TITLE
Check for alpha version updates fails

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#1836]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
since installing 2.315 (694), when I select "check for alpha version updates" I either get the "checking" pop-up followed by nothing (this only on the very first time after restart), or I don't even get the pop-up (all other times).

#### Device information:

Type of Mac: 2016 13" MacBook Pro with touchbar
macOS version: 10.13.1
BetterTouchTool version: 2.315

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think this was a bug in one of the alpha or pre-alpha versions :-)
Unfortunately you'll need to download the update manually (https://boastr.net/releases)

**Comment by CappyD** [comment]
Thanks Andreas. I kinda thought that might be it. So, I downloaded 2.318, put it Applications folder, and started from there but it still complains about read-only drive and tells me launch from Applications. Seems this came up before, but I don’t recall how to make it happy.

On Dec 5, 2017, at 2:50 AM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

I think this was a bug in one of the alpha or pre-alpha versions :-)
Unfortunately you'll need to download the update manually (https://boastr.net/releases)

**Comment by fifafu** [comment]
Oh are you using any third party file manager? Due to some sierra security feature you need to move it with Finder to the Applications folder.

**Comment by CappyD** [comment]
Thanks again Andreas… yep, that was it. I use a finder alternative (pathfinder) and moved it to Applications with that. I redownloaded and used Finder to move and it was able to do the check for updates.

Thanks,
--David



On Dec 5, 2017, at 9:22 AM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

Oh are you using any third party file manager? Due to some sierra security feature you need to move it with Finder to the Applications folder.
