### ISSUE TITLE
Screenshot of current Window

### ISSUE THREAD

**Issue by omz45** [fifafu/BetterTouchTool#1837]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
This is a request
*tool is amazing btw, great work*

Would be nice if the following functionality could be available

Currently (as a tester) I take multiple screenshots of the current window by doing the following

Cmd +Shift + 4, Space, Left Mouse Click

I am aware of the functionality that automates the Cmd + Shift + 4 command and I have assigned this to a TouchBar button

I am also aware of the Attach Additional Action option, I have tried to add a 'Space' action followed by a 'Left Mouse Click' action however I think it performs the actions all in one go where are the space bar action needs to occur after the Cmd+Shift+4 not at the same time. The same applies for the Left Mouse click

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar 

#### Device information:

Type of Mac: MacBook Pro 2016 Touchbar
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can use the action "capture screenshot (configurable)" and check the "start interaction in window selection mode" checkbox

**Comment by fifafu** [comment]
You may need to add a little delay using the "delay next action" predefined action before triggering the left-click.

![image](https://user-images.githubusercontent.com/8820811/33606280-40a52286-d9bd-11e7-9123-5587c2516e84.png)

**Comment by omz45** [comment]
Thanks Andreas, you are a genius!

Many Thanks
Omar
