### ISSUE TITLE
Can't map undo?

### ISSUE THREAD

**Issue by wedgekase** [fifafu/BetterTouchTool#1838]
I'm a new user and I must be missing something. I'm trying to map a button on my normal mouse to a simple undo command (Cmd+Z). I can't seem to manage how to do it. 

My other buttons got mapped to other keyboard sequences just fine.

The keyboard shortcut recording won't record Cmd+Z specifically because it's being used by BTT as its undo. And I can't find anywhere to create a custom keyboard sequence that I can use as a predefined action. 

I've tried pressing Cmd+Shift+Z, and then right clicking to Cut the Shift, but that doesn't work. I've tried pressing Cmd+(and another letter besides Z), and then selecting the other letter and typing Z to replace it, but that doesn't work either.

This has to be easier than this, right? What am I doing wrong?

#### Device information:

Type of Mac: Mac Pro 5,1
macOS version: High Sierra (latest update)
BetterTouchTool version: 2.318

**Comment by NevinBR** [comment]
This works for me:

1a. Click in the “Custom Keyboard Shortcut” box.
1b. Type “⌘Z” in the box. Nothing appears and the box is deselected.
1c. Without doing anything else, press “⌘⇧Z”. The box now shows “⌘Z”.

**Comment by wedgekase** [comment]
That totally works! THANK YOU SO MUCH!!!!

**Comment by fifafu** [comment]
Thanks for reporting. This will be fixed with the next update.

**Comment by fifafu** [comment]
this should be fixed in v2.319 alpha
