### ISSUE TITLE
Extra BTT Button(s) Added to BTT Button Bar

### ISSUE THREAD

**Issue by clayton-grey** [fifafu/BetterTouchTool#184]
BTT is adding extra BTT icons to the touch bar. I'm not entirely sure what's causing it. I've setup 3 custom utility buttons for Blender (applications specific). I'm consistently getting 1 extra ([see here](http://imgur.com/a/OMtPp)). I've had an instance where there were 2 extras, 1 which was overlapping the other buttons, which was what made me notice the issue in the first place.

**What kind of Mac are you using?**

New MBP.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**

10.12.2, 1.978

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Restarting the app clears extras. I've tried toggling all of the global settings. This seems to have no effect on the extra buttons. Just wanted to make note of this behavior if you haven't seen it.

**Comment by fifafu** [comment]
That's interesting, thanks for reporting! Can you reproduce this reliably with your settings? If so, would you be able to attach an export of your setup (via the export preset button) or mail it to me? (Boastr.net@gmail.com)

**Comment by sc-surfer** [comment]
Just installed the newest version and registered. STOKED on the ability to customize the Touch Bar.

However, having this same issue. After restarting BTT the problem resolved.

2016 MBP W/ newest OSX Sierra

**Comment by fifafu** [comment]
Unfortunately (or luckily) I haven't be able to reproduce this issue. Maybe Apple fixed it?

In case this still happens for you, please let me know.
