### ISSUE TITLE
Normal mouse gestures makes BTT crash on OS X 10.13.2

### ISSUE THREAD

**Issue by ggarrigu** [fifafu/BetterTouchTool#1843]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I tried to find a similar issue but each time it was with specific actions or hardware (ForceTouch trackpad etc).
I'm just using a classic mouse, (ASUS ROG) with 5 button (Left and right click, middle click, and 2 : one up and one down of the thumb for right-handed).
At the moment i only have actions on the thumb's buttons, with window snapping activated.
Unfortunately, BTT is crashing even while i'm not using those, so i can't really tell you that a particular action trigger the crashes. Maybe it crashing faster while i'm using window snapping.
I joined 2 crashes reports, hope it'll help you to solve the recent issues with 10.13.2,
I'm a junior dev (C, JAVA/APEX), so if you need other logs or else, let me know.

Thank you.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Standard [Asus ROG mouse](https://www.google.fr/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiv_oCXmvjXAhWLnRoKHayLDT4QjRwIBw&url=https%3A%2F%2Fwww.newegg.com%2FProduct%2FProduct.aspx%3FItem%3DN82E16826785062&psig=AOvVaw0z7xLKPfngN66fpbY5ziKE&ust=1512746540794196) with 5 buttons

#### Device information:

Type of Mac: MacBook Air (13-inch, Early 2014)
macOS version: High Sierra 10.13.2 (17C88)
BetterTouchTool version: 2.318 (702)

![screen shot 2017-12-07 at 16 04 52](https://user-images.githubusercontent.com/7969420/33722407-21f45164-db6a-11e7-890b-a1a2c36ad99a.jpg)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[BTT Crash.txt](https://github.com/fifafu/BetterTouchTool/files/1539535/BTT.Crash.txt)
[BTT Crash 2.txt](https://github.com/fifafu/BetterTouchTool/files/1539562/BTT.Crash.2.txt)

![screen shot 2017-12-07 at 16 05 31](https://user-images.githubusercontent.com/7969420/33722414-274554f6-db6a-11e7-83b0-c065214fad79.jpg)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That looks like a macOS bug. Have you already tried to restart your Mac?
 If so I'll forward it to Apple.

**Comment by ggarrigu** [comment]
@fifafu Thanks for your answer. Of course i restarted many times. It doesn't change anything.
I opened a new issue 'cause BTT wasn't crashing before 10.13.2 beta update. If it's not coming from BTT, feel free to close the issue.
I'm sending the reports to Apple at least 10 times a day xD, not sure, however, that they will do anything about it :(

**Comment by fifafu** [comment]
Yep, it's the same as #2020. I'm currently testing some workarounds so stay tuned.
