### ISSUE TITLE
Dreamweaver Key Commands/Touchbar Buttons

### ISSUE THREAD

**Issue by EdgeMarketing** [fifafu/BetterTouchTool#1844]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I use BTT to change cmd+u in Dreamweaver to cmd+s, sft+cmd+u...i LOVE it for that feature alone, but i use it for others too. Suddenly, it stopped working, as have the rest of my Dreamweaver keyboard shortcuts. I have deleted and re-added them to no avail, also tried adding them as touchbar buttons as well, the bar won't even show up. Tried restarting too. My Photoshop one does though when i am in Photoshop. Help?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook, Touchbar and Keyboard

#### Device information:

Type of Mac: MacBook Pro 2016 w/ Touchbar
macOS version: High Sierra 10.13.1
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Did something change with dreamweaver?
Maybe try to delete it from BTT and add the Dreamweaver application again. Maybe the App ID or something similar changed.
