### ISSUE TITLE
Three finger swipe scrolls content

### ISSUE THREAD

**Issue by chbk** [fifafu/BetterTouchTool#1846]
#### Description of bug/feature request/question:

I set three finger horizontal swipes to switch tabs. These gestures work in every app except Atom, which also scrolls when switching tabs (sometimes even scrolling back to top).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Air
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Also posted about the issue in the [Atom repository](https://github.com/atom/atom/issues/16304)

**Comment by chbk** [comment]
Similar issue: #881

**Comment by fifafu** [comment]
Yup let's continue in #881. I think this will be improved with the next version.
