### ISSUE TITLE
On a new Macbook Pro with latest updates I get a stream of the same error messages:

### ISSUE THREAD

**Issue by imraanc** [fifafu/BetterTouchTool#1847]
It says "the operation couldn't be completed. NSSQ Lite Error Domain error 8"

**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you tried to restart your machine?
Sounds like some sort of file permission error.

**Comment by imraanc** [comment]
I've tried. Doesn't work. There's another issue I just saw with the same
result.
https://github.com/fifafu/BetterTouchTool/issues/1660
A backup from Time Machine to a new machine with a TouchBar.
Seems to be related to those two things BUT uninstalling and re-installing
doesn't help either. I don't know how to trash the configuration files and
start again completely. Also pop up keeps coming up when I go to system
preferences.

**Comment by fifafu** [comment]
The configuration files are located in ~/Library/Application Support/BetterTouchTool and in ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist

The popup thing also sounds like a file permission error, so maybe check the permissions of the files before deleting them. Maybe setting the correct permissions will fix the issue.

**Comment by imraanc** [comment]
Thanks so much.  How do I set the permissions?

________________________________

**Comment by fifafu** [comment]
Ah sorry for the delayed reply. You should be able to right-click files in finder and then change the permissions like described here:
https://support.apple.com/kb/PH25287

<img width="377" alt="grafik" src="https://user-images.githubusercontent.com/8820811/34084558-f82cfa36-e382-11e7-9181-ed61dcf6c83c.png">
