### ISSUE TITLE
BetterSnapTool Feature Request: Center on Current Monitor

### ISSUE THREAD

**Issue by gokieks** [fifafu/BetterTouchTool#1849]
**#### Description of bug/feature request/question:**
There are times when I would like to have a window be exactly centered on my screen.  As there there is already a "Center on next monitor" feature in BetterSnapTool, I can accomplish this by using that function N times (N being the number of monitors in use), but I would really like to be able to do it without having do it repeatedly, and it seems like all the app functionality to accomplish this should already be present.

And if possible, would like for this to be in both BST and BTT, as I use both (BST on desktop, BTT on laptop).

**Comment by fifafu** [comment]
Is your request different from the existing "center" action? See this screenshot:

<img width="764" alt="grafik" src="https://user-images.githubusercontent.com/8820811/33857786-72c873a2-decd-11e7-8045-bda9c92152d1.png">

**Comment by fifafu** [comment]
Btt also has this as predefined action :-)

**Comment by gokieks** [comment]
Oh, it's a predefined action... I was looking in the window snapping / moving / resizing sections.  So I guess it already has everything I need... thanks!
