### ISSUE TITLE
Confused by BTT Remote

### ISSUE THREAD

**Issue by davidt0305** [fifafu/BetterTouchTool#185]
Running BTT 1.963 and BTT Remote on my iPad pro.

I created some custom gestures for remote, but can't seem to find how to actually activate or use them on the remote. Also the buttons on the left side of the remote looks like can be customized, but can't figure out how?

**Comment by fifafu** [comment]
Hey David,

what kind of custom gestures did you add? Could you maybe attach an export of your setup (via the export preset button in the BTT Preferences)

The buttons on the left currently can't be customized, maybe I can add this with a future update.

Best,
Andreas
