### ISSUE TITLE
[Feature request] Keep button group open between switching windows

### ISSUE THREAD

**Issue by lightheaded** [fifafu/BetterTouchTool#1854]
#### Description of feature request:
The new Touch Bar coupled with the BetterTouchTool allows a superb opportunity to have alll the possible window resize/move icons available at a glance. What I have made, is a Button Group which contains a whole bunch of buttons (Maximize Window, Maximize Window Left, Maximize Window Right, Resize window to Left Third etc.). This way I could rearrange my 4 windows in a jiffy, **but** currently it's not as easy due to the *button group being closed* after I switch to a new application.

I would like to have an option for the *button group to stay open while switching focus between applications**. Perhaps under "Advanced configuration" under the Touch Bar Button Group.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:
Type of Mac: Macbook Pro 2017
macOS version: 10.13.1 (17B1003)
BetterTouchTool version: 2.318

**Comment by fifafu** [comment]
Tracking this here #369
