### ISSUE TITLE
GITHUB Request

### ISSUE THREAD

**Issue by CyborgSemon** [fifafu/BetterTouchTool#1855]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of request:

I know this is the biggest request of them all, but it would be awesome to tidy up the github issues page. since there are 35 pages (as of 11/12/2017) of requests / bugs / questions.

Only if you have time of course :P

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I'm regularly going through them. Most of them are feature requests or problems where I may not be able to help directly but other users may be able to help.  If I don't close them I think they might have some value and/or may be implemented in the future.
Quite often users are replying to relatively old issues or feature requests.

Next year I'll probably work full time on my apps and will be able to close/implement many ;-)
