### ISSUE TITLE
[Feature Request] Allow different settings for different monitor sizes

### ISSUE THREAD

**Issue by Zoratt** [fifafu/BetterTouchTool#1859]
**Description of bug/feature request/question:**
I use a 13" MacBook Pro by itself, and also plugged into a 27" monitor. On the MacBook Pro, I would like to set the maximize windows left and right to be 65%, but when on the 27" monitor, I would like it to be set to 50%. 

**Device information:**

Type of Mac: 2016 MacBook Pro 13"
macOS version:  10.13.1
BetterTouchTool version: 2.318

**Comment by fifafu** [comment]
Currently I don't plan to make these settings display specific as the current implementation is super simple and doesn't have any logic.

However you can use custom snap areas, these are specific to the display.
