### ISSUE TITLE
App specific TouchBar buttons...how to set an app that doesn't exist in the apps folder.

### ISSUE THREAD

**Issue by sc-surfer** [fifafu/BetterTouchTool#186]
I bough BTT to enable me to create custom buttons to trigger transactions in E*Trade Elite Pro. 

The issue is that the App I launch to start the platform is not the app where I want the custom Touch Bar.  The platform runs in Java. The app I launch stays active, but does nothing. The Java app is where I want the custom buttons to work. The problem is that I can't select the Java app in the picker because it does not exist as a standalone app.

If I launch the Activity Monitor I see the process that I want to link to the custom buttons.

I really hope that makes sense. I'm not a programmer or anything so thats the best description I could come up with.  

Is there any way to make this work? Perhaps some other way to specify the app than through the file picker??

REALLY hope there is a way to make this happen.

Feel free to ask for more specific info if you need it.

**What kind of Mac are you using?**

2016 MBP 15" TouchBar, 
OSX 10.12.2, 
BTT 1.978(569)

**Which versions of macOS and BetterTouchTool are you running?**

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by sc-surfer** [comment]
Followup....FYI

It looks like I'm dealing with a similar issue as outlined in this ticket.

"Cannot locate Minecraft.app #129"

**Comment by dax50** [comment]
Same thing for me...Trading on a java plattform of a german broker.

I located the java app in /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Home/Contents/Home/bin in Finder. But the problem with BTT is that I am not able to 'look' into the JavaAppletPlugin.plugin Container when I should pick the app because it is greyed out.
Really hope this can be fixed since using a customized Touchbar with my trading apps would be more than awesome!

Best regards,
dax

**Comment by sc-surfer** [comment]
Still hoping for a fig on this!! Any chance it is in the works?

Monte

**Comment by sc-surfer** [comment]
As an update...

Not only is there no way to select a Java applet in BTT, on recent update of BTT, keystrokes from BTT no longer received by Java applet even though it is the current 'app' in the foreground. PLEASE HELP!!
