### ISSUE TITLE
Touch Bar Volume Slider resets Volume Balance. 

### ISSUE THREAD

**Issue by lbibass** [fifafu/BetterTouchTool#1861]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

Issue: Changing volume from the touch bar slider resets volume balance. 

#### Device information:

Type of Mac: mid 2017 macbook pro 
macOS version: high sierra 
BetterTouchTool version: AHHHHHH

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think that's the same issue as https://github.com/fifafu/BetterTouchTool/issues/971
Does this also happen with the normal touch bar volume slider? (On my system it looks like it does)

**Comment by lbibass** [comment]
Lemme check!

Thank You,

 Evan Dries
