### ISSUE TITLE
Update Freezing During Extraction

### ISSUE THREAD

**Issue by skaro123** [fifafu/BetterTouchTool#1862]
While trying to run a standard update I am getting a freeze during extraction.  The process gets to about 60% completion and then hangs. 

I can terminate BetterTouch and restart the application but if I leave the process running, other applications become unresponsive and in some cases require a reboot MacOS.  MacOS will become unresponsive as well.

Type of Mac: MacBook Air
macOS version: 10.13.1
BetterTouchTool version: 2.313 (691)

**Comment by fifafu** [comment]
Mh I don't think this can be a problem with BTT. Maybe some files got corrupted or there are weird file permission errors.

I'd try to competely delete the app folder and download a fresh copy directly from my website (https://boastr.net)
