### ISSUE TITLE
Has to click TouchBar twice in order to register

### ISSUE THREAD

**Issue by danielywang** [fifafu/BetterTouchTool#1866]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.1
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Which touch bar icon?

If you close the BetterTouchTool touchbar using the x button, that’s a known limitation. Only close out by pressing the icon in the control strip.

**Comment by danielywang** [comment]
Thanks. That works better.
