### ISSUE TITLE
"There's no application set to open the URL"

### ISSUE THREAD

**Issue by danielywang** [fifafu/BetterTouchTool#1869]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When I click a button I have set up to open Google Drive in Safari on the Touch Bar, a box pops up that says, "There's no application set to open the URL". I selected Safari in the pop up selector, but it only works if I select Safari every single time. 

#### Device information:

Type of Mac: MacBook Pro 15 2017
macOS version: 10.13.1
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Does your link include the https:// part?

**Comment by danielywang** [comment]
Thanks so much, that worked :) 👍
