### ISSUE TITLE
add actions to set and toggle 'do not disturb' mode of the notification center

### ISSUE THREAD

**Issue by gretel** [fifafu/BetterTouchTool#187]
#### Description of your bug/question/feature request...:
watching movies using BTT Remote is great. i can easily toggle fullscreen mode - but for now the notification center might disturb showing it's popups.
i kindly request adding the according actions.

**What kind of Mac are you using?**

MacBook Pro '16

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

most

**Which versions of macOS and BetterTouchTool are you running?**

10.12.3, 1.9.78

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

<img width="410" alt="system preferencessnap001" src="https://cloud.githubusercontent.com/assets/80815/21580498/32fc0388-cffb-11e6-8db5-c30264407525.png">

**Comment by fifafu** [comment]
Good idea, I'll add this!

**Comment by fifafu** [comment]
A do not disturb toggle action has been added recently.

**Comment by Osmosis311** [comment]
Is there any way to get feedback so the button can reflect the current DND status?
