### ISSUE TITLE
Ctrl-left and ctrl-right not triggering

### ISSUE THREAD

**Issue by DaveBurns** [fifafu/BetterTouchTool#1870]
#### Description of bug/feature request/question:

I have two keyboard shortcuts set up to mimic Windows: Ctrl-Left should trigger Option-Left and Ctrl-Right should trigger Option-Right. Neither seems to work. I tried putting some HUD text there to see if the shortcut was being seen and it didn't show. I do have two other shortcuts: Home and End map to Cmd-Left and Cmd-Right. I tried HUD displays on those and those worked.

Rebooting doesn't seem to work. Nor does restarting BTT or deleting and recreating the shortcuts.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Both my MBP's internal keyboard and my external keyboard.

#### Device information:

Type of Mac: Late 2011 15-inch MBP.
macOS version:  10.12.6
BetterTouchTool version:  2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Please let me know what I can do to help diagnose.

---

**Comment by fifafu** [comment]
This seems to be working fine here. Do you have other apps running that capture global keyboard shortcuts?

**Comment by DaveBurns** [comment]
I couldn't think of any app that I installed so I searched under System Preferences -> Keyboard -> Shortcuts and under Mission Control I found some using those already: Mission Control -> Move left a space and Move right a space. I disabled them and now things look like they are working.

Thanks,
db
