### ISSUE TITLE
Enabling/Disabling Gestures in all tabs (currently only available in the Keyboard section)

### ISSUE THREAD

**Issue by n0mar** [fifafu/BetterTouchTool#1875]
Please allow us to enable and disable gestures in all tabs. This feature is *only* present in the Keyboard Gestures section.

Please see attached screenshot:

<img src="https://user-images.githubusercontent.com/3734562/33991839-6a2a941a-e124-11e7-93ba-4430f00d3fdc.png">

This feature is not present as of the latest public version of BetterTouchTool, 2.318.

Thanks!

**Comment by fifafu** [comment]
I'm tracking this here: #2129
