### ISSUE TITLE
Adjust magic mouse scroll sensitivity

### ISSUE THREAD

**Issue by tbird2** [fifafu/BetterTouchTool#188]
Feature request:

Applications or websites that zoom on scroll are horrible with a Magic Mouse because it's too sensitive and can start zooming in and out wildly on accident, when you don't intend, and with the slightest one-finger scrolling movement. Sometimes I will just go to click on something, and it will start zooming during the click, before it registers the click, by just touching the mouse the brief moment before I actually click, it will first register a scroll, and thus start zooming. Other times, I'm not paying attention and let my guard down and just rest my finger on my mouse, and whoa everything starts zooming in or out.

Since Apple and the various apps that use scroll to zoom don't have any good workarounds, it would be great if BTT was able to somehow reduce the sensitivity so that it will only scroll when the swipe is much more deliberate.

I know BTT can "Disable single finger scrolling" in the Gesture settings, and then I can use 2-finger scrolling instead, and that's a nice option for those that want that. But, I'd rather not disable single finger scrolling in every situation. I'd like it if it only started scrolling if the single finger swipe was more than, say, 1cm in under 0.1 seconds, or something. It's scrolling after moving my finger only 0.001mm even if I'm only moving very slowly. It's ridiculously sensitive. And, it's starting to scroll during the 0.0001 seconds as I press down to click. If it could wait 0.1 seconds to see if I'm going to click or make some other gesture before assuming the first thing I want to do is start scrolling, that would be good too. 

It would also be nice to not start scrolling if the mouse is moving or being clicked. The default behavior is that it allows me to scroll/zoom while the mouse is moving or being clicked. I can't think of a reason I would ever need that. I'm either moving/clicking things OR I want to scroll. I'm never moving/clicking things AND scrolling at the same time. Whenever I scroll WHILE I'm doing something else, that's unintended. So, it would be nice to have an option to avoid that. In other situations, it's nice to be able to scroll any time, so I think it should be an option. During scrolling, I doubt I would want it to stop scrolling as soon as I move the mouse -- I would only want it to not start scrolling if I'm moving or clicking the mouse.

This happens in Google Maps, Adobe apps, and recently I've been using it on circuits.io in their circuit editor and it drives me crazy. I have to constantly reset the zoom.

Please let me know if I missed this feature or some other solution to this problem. 

Thanks.

**Comment by fifafu** [comment]
Unfortunately this is something Apple would have to implement as it would be complicated & error prone to  do by a third party app :-(
I'd suggest to submit the same issue to Apple.
