### ISSUE TITLE
modifiers keys have no effect

### ISSUE THREAD

**Issue by dorindon** [fifafu/BetterTouchTool#1882]
When I define a GLOBAL gesture, for example 3 finger tap to close the front window, or 4 finger tap to hide the window, or 2 finger double tap to search for an evernote note, and many others, I am unable to create more identical gestures with different modifier keys and different actions. 
---

Hello,
 I am a registered user of BTT, currently using version 2.318 on Sierra 10.12.6 on an IMAC Retina and latest Apple magic trackpad. 
Congratulations for a great app. 
I could not find the answer to my question in the help or forums.

When I define a GLOBAL gesture, for example 3 finger tap to close the front window, or 4 finger tap to hide the window, or 2 finger double tap to search for an evernote note, and many others, I am unable to create more identical gestures with different modifier keys and different actions. 

For example, if the 3 finger tap closes the window, then the same 3 finger tap using any modifier keys and any other completely different action will trigger closing the window. Same is true for other gestures. Whatever modifier I add and new action I create with the 4 finger tap, the result will be a 'hide window' action.
I have tried absolutely everything imaginable to troubleshoot this problem for the past few weeks and am unable to find a solution.
I am therefore extremely limited in the spectrum of gestures I have access to.
Herzlichen Dank for your help and congratulations for a great app !

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple Magic Trackpad

#### Device information:

Type of Mac: IMAC retina
macOS version:  10.12.6
BetterTouchTool version: 2.318
latest Apple Magic Trackpad

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I restarted the app and computer many many times, checked sys pref  ⇨ trackpad and accessibility.
Note that this happens in multiple apps, for example window closing happens in all apps I tested.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to work fine here.
Does your configuration look like this screenshot?
![image](https://user-images.githubusercontent.com/8820811/34062034-df4ba998-e1ea-11e7-8894-7f75197006bf.png)

**Comment by dorindon** [comment]
Hello,

I deleted all of my gestures and re-created them. It now works. I do not understand what happened because it lasted for a few weeks. 

If the problem recurs and points for example to an conflict with another open app, I will contact you again.

I have one further setup question: 
- if I use a 2 finger tap to access the context menu, do you recommend unchecking in MAC OS Sys Pref the 2 finger tap secondary tap to access the context menu and re-defining it (how?) in BTT, or leaving it defined in MAC OS Sys Pref?
- should I uncheck point to click and redefine it in BTT? how?

I apologize for taking your time and thank you very much for your help

![image](https://user-images.githubusercontent.com/30017084/34062709-635189d0-e1ee-11e7-8653-e8faa46fe1f1.png)

**Comment by fifafu** [comment]
You should disable ithe seondary click option if you want to trigger it using BTT.
However this only makes sense if you assign different actions to two finger tap and two finger click in BTT. Otherwise I'd just use the system setting.

**Comment by dorindon** [comment]
Herzlichen Dank. I very much appreciate your time and help, and thanks so much for creating the app. Keep up the good work ! A great acquisition for Siemens!
