### ISSUE TITLE
Trigger Context Menu does not work

### ISSUE THREAD

**Issue by castorpollux285** [fifafu/BetterTouchTool#1883]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When I try to trigger a context menu item, the context menu is opened, but the item is not triggered. I tried (6);(6) as well as writing the name of the item.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal Mice, Button 3

#### Device information:

Type of Mac: iMac 27" end 2013
macOS version: 10.12.6
BetterTouchTool version:  2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This only works for standard menus, some apps don't use the default API to show their context menus.

Which app are you trying to do this in?

**Comment by castorpollux285** [comment]
I´m using it in BusyCal.

I also tried a workaround, with right click and arrow keys, but it also only opens the context menu and ignores the arrow keys.

**Comment by castorpollux285** [comment]
Workaround is with additional actions.

**Comment by fifafu** [comment]
Which item are you trying to trigger exactly? (I just tried a few things in busycal and it seemed to work correctly)

**Comment by castorpollux285** [comment]
I´m trying to change the calendar of an event.

I move the cursor over an event, and press "button 3" on my mouse, which should trigger the context menu item "Kalender" -> "Arbeit Aktuell".

I tried (6);(6) in "Trigger Context Menu Item", but only the context menu opens.

Attached is a screenshot of what I want to trigger.

But I also tried other menu items, they didn´t work neither.

**Comment by supersaiyansubtlety** [comment]
I'm having the same issue in Chrome. I tried to make a three finger tap trigger the "Open Link in New Tab" item. I tried both the title of the item and (1), neither worked, the context menu just opened and sat there as with castorpollux.

**Comment by supersaiyansubtlety** [comment]
This randomly started working for me, so apparently it's inconsistent.

**Comment by fifafu** [comment]
I think this should be working with current versions (at least for apps that use default cocoa context menus)
