### ISSUE TITLE
Frequently hangs on launch

### ISSUE THREAD

**Issue by 75th** [fifafu/BetterTouchTool#1884]
#### Description of bug/feature request/question:

The app hangs on launch or after waking from sleep very frequently for me. It sometimes requires a reboot to make it start working again, especially if it hung after waking from sleep and not on reboot. When it hangs, there's some console output, the icon fails to appear in the menu bar, and of course no gestures work.

When it launches *correctly*, the same console output still appears, and then *more* appears; so the errors in the first lines don't seem to be causing the actual problem.

#### Device information:

Type of Mac: MacBookAir6,2
macOS version: 10.12.6
BetterTouchTool version: 2.318 (702)

##### Hang-on-launch output

    default	11:08:12.369352 -0600	BetterTouchTool	UNIX error exception: 17
    default	11:08:12.369815 -0600	BetterTouchTool	0x608000462f40 opened /private/var/db/mds/system/mdsDirectory.db: 50540 bytes
    default	11:08:12.371595 -0600	BetterTouchTool	UNIX error exception: 17
    default	11:08:12.372305 -0600	BetterTouchTool	UNIX error exception: 17
    default	11:08:12.372502 -0600	BetterTouchTool	UNIX error exception: 17
    default	11:08:12.578959 -0600	BetterTouchTool	annotation:  Failed to load optimized model at path '/Applications/BetterTouchTool.app/Contents/Resources/BetterTouchTool_DataModel.momd/BetterTouchTool_DataModel 48.omo'

##### Successful launch output

    default 11:27:53.486841 -0600   BetterTouchTool UNIX error exception: 17
    default 11:27:53.487282 -0600   BetterTouchTool 0x608000266bc0 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
    default 11:27:53.488331 -0600   BetterTouchTool UNIX error exception: 17
    default 11:27:53.489094 -0600   BetterTouchTool UNIX error exception: 17
    default 11:27:53.489232 -0600   BetterTouchTool UNIX error exception: 17
    default 11:27:53.655061 -0600   BetterTouchTool annotation:  Failed to load optimized model at path '/Applications/BetterTouchTool.app/Contents/Resources/BetterTouchTool_DataModel.momd/BetterTouchTool_DataModel 48.omo'
    default 11:27:53.841639 -0600   BetterTouchTool MacOS error: -67052
    default 11:27:53.841998 -0600   BetterTouchTool UNIX error exception: 17
    default 11:27:53.842862 -0600   BetterTouchTool UNIX error exception: 17
    default 11:27:53.846640 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:53.846958 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:54.382540 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:54.382874 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:54.384908 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:54.384910 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:54.385258 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:54.385326 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:54.385578 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:54.385806 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:54.588147 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:54.588428 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:54.708248 -0600   BetterTouchTool MacOS error: -67052
    default 11:27:54.711182 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:54.711478 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:55.271518 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:55.271813 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:55.273393 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:55.273454 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:55.273691 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:55.273822 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:55.273975 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:55.274084 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:55.338908 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (BetterTouchTool[1900])
    default 11:27:55.339218 -0600   trustd  asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (BetterTouchTool[1900])
    default 11:27:55.448853 -0600   BetterTouchTool Bonjour Service Published: domain(local.) type(_bttremote._tcp.) name(Gizmonic) port(52879)

**Comment by fifafu** [comment]
Yep the errors can be ignored. That's just macOS 10.12.x stuff.
If possible please run this command in case BTT hangs:

```sample BetterTouchTool -file ~/Desktop/BetterTouchToolSample.txt```
This will create a file called BetterTouchToolSample.txt on your Desktop, this may be very helpful to identify the issue.

**Comment by 75th** [comment]
[Here you go!](https://github.com/fifafu/BetterTouchTool/files/1568512/BetterTouchToolSample.txt)

**Comment by 75th** [comment]
@fifafu Just upgraded to High Sierra; the problem persists.
[Here's another sample.](https://github.com/fifafu/BetterTouchTool/files/1623427/BetterTouchToolHangOnHighSierra.txt) Any insight?

**Comment by fifafu** [comment]
Looks like macOS is trying to mount some network share when BTT tries to synchronize the login items.

Do you maybe have some old network share configured?

**Comment by fifafu** [comment]
I think this should be fixed in v2.332
