### ISSUE TITLE
Question: How to retain previous returned value in touchbar widget as variable?

### ISSUE THREAD

**Issue by danbrag** [fifafu/BetterTouchTool#1885]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi! I was curious if an Applescript widget which runs automatically would be able to store the previous returned value in a variable somewhere?

For example, if a widget returns a value of 234.454 and then i re-run the script and want to compare the new number vs. the old number, can I do that somehow? Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 2017 Touch Bar
macOS version: High Sierra
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Currently that's not possible, but it will be added soon!
There have been various requests for variables (e.g. #1801), thus I'm closing here.

**Comment by danbrag** [comment]
Thanks! I couldn't find anything which was exactly the same.

Either way thanks again and great work!
