### ISSUE TITLE
Feature request: Move mouse relative to mouse position 

### ISSUE THREAD

**Issue by castorpollux285** [fifafu/BetterTouchTool#1886]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I´d like to move the mouse to a position relative to the current mouse position. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal Mouse

#### Device information:

Type of Mac: iMac 27" end 2013
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is now possible using the "move mouse to position" predefined action.
