### ISSUE TITLE
how to 1- backup 2- paste clipboard content 3- add a pause

### ISSUE THREAD

**Issue by dorindon** [fifafu/BetterTouchTool#1887]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---
Hello, I am a registered user of BTT, currently using version 2.318 on Sierra 10.12.6 on an IMAC Retina and latest Apple magic trackpad. I could not find the answer to my question in the help or forums.

1- how do I backup/export my gestures ?

2- is there a way to insert a pause for example 0.2 sec or 0.5 sec between sequential actions ? I have the impression that some of the problems I have with multiple sequential actions (for example call up an app and then paste) are due to insufficient time between actions.

3- I cannot find a predefined action equivalent to simply pasting current clipboard contents (Cmd-V)

Herzlichen Dank for your help 

Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Apple Magic Trackpad
 IMAC retina mac
OS version: 10.12.6 
BetterTouchTool version: 2.318
 latest Apple Magic Trackpad

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by ErikMinekus** [comment]
1) Click Manage Presets on the left, then click Export Highlighted.

2) Auxiliary Actions > Delay Next Action

3) Setting Custom Keyboard Action to Cmd+V doesn't work?

**Comment by dorindon** [comment]
thanks very much Eric. Cmd-V does not work, precisely I think, because it requires some kind of delay after loading the app. 
You are very kind to take the time to answer my question.

**Comment by dorindon** [comment]
@ErikMinekus 
It now all works perfectly after inserting a few 0.2 second delays between the actions.
Now I can use Cmd-V which I tried in vain in the first place, and there is no need for a special paste action.
Thank you so much !!

**Comment by fifafu** [comment]
Great, thanks @ErikMinekus for solving this.
