### ISSUE TITLE
Feature Request: Prevent windows from overlapping during resize

### ISSUE THREAD

**Issue by MichaelScript** [fifafu/BetterTouchTool#1890]
Similar to using the native fullscreen and you have two apps side by side, when you move one of the windows the other window resizes along with it. It would be nice to be able to do this with BTT but with multiple windows where if you hold down a hotkey while resizing it would adjust the sizes of the other windows that would normally just be covered by the window you are resizing.

More generally it would be nice to be able to tile windows in a way similar to i3 or bspwm.

**Comment by fifafu** [comment]
Sorry, the APIs available for window resizing are not good enough to do something like this without beeing annoyingly sluggish. Even to get such a feature working at all would be quite hard.

Thus unfortunately this is something I won't be able to add to BTT (at least in the near future).
