### ISSUE TITLE
Crashes on macOS 10.13.2

### ISSUE THREAD

**Issue by djradev** [fifafu/BetterTouchTool#1891]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

BetterTouchTool constantly crashes on macOS 10.13.2

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro

#### Device information:

Type of Mac: MacBook Pro Mid 2015
macOS version: 10.13.2 (17C88)
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Please see attached crash report
[BetterTouchTool_2017-12-17-123626_R2D2.crash.txt](https://github.com/fifafu/BetterTouchTool/files/1565569/BetterTouchTool_2017-12-17-123626_R2D2.crash.txt)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is the same as https://github.com/fifafu/BetterTouchTool/issues/1856
Unfortunately it seems to be a system framework that crashes and only seems to crash on very few machines. I have reported it to Apple, let's hope for a fix.

As the crash seems to be related to Bluetooth, try to remove any bluetooth triggers you may have configured in the other section in BTT.

<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/34079452-0f50f794-e32e-11e7-8787-b36109332b24.png">

**Comment by djradev** [comment]
Hi, thanks for the reply. I don't have any bluetooth triggers. Only macbook's trackpad gestures, will try to remove them all to see what will happen.

**Comment by yaseent** [comment]
Hi,

I'm experiencing the same issue.

MacOS 10.13.2 (17C88)
MacBook Air (13-inch, Early 2015)

I have no Bluetooth Triggers.

I am using a Microsoft Sculpt Touch Mouse (Bluetooth Mouse)

I've attached my very first crash, and my most recent crash.

I have also noticed, that it does not occur only when High Sierra comes out of sleep, but also when I reboot the machine or fresh boot from being shutdown. BTT will occasionally not even start up, though it is set to automatically set to start when OSX logs in.

[BetterTouchTool_2017-12-21-142356_Yaseens-MacBook-Air.txt](https://github.com/fifafu/BetterTouchTool/files/1606112/BetterTouchTool_2017-12-21-142356_Yaseens-MacBook-Air.txt)
[BetterTouchTool_2018-01-05-110311_Yaseens-MacBook-Air.txt](https://github.com/fifafu/BetterTouchTool/files/1606114/BetterTouchTool_2018-01-05-110311_Yaseens-MacBook-Air.txt)

**Comment by dannyPechersky** [comment]
I have this same issue, no bluetooth triggers either.

Mac OS X 10.13.2 (17C205)
MacBook Pro (Retina, 13-inch, Early 2015)
BetterTouchTool version: 2.320

BTT consistently crashes when my computer connects to a bluetooth device (bluetooth headphones, iOS personal hotspot)
Launching BTT while connected to a bluetooth device is fine.

Here is my most recent crash:

[BetterTouchTool_2018-01-16-092034.crash.txt](https://github.com/fifafu/BetterTouchTool/files/1635465/BetterTouchTool_2018-01-16-092034.crash.txt)

**Comment by MateuszDabrowski** [comment]
Same here.

Mac OS X 10.13.2 (17C205)
MacBook Air (13-inch, Early 2015)
BetterTouchTool version: 2.318

BTT gets killed every 1-2 days due to bluetooth connection (headphones, speakers).
No bluetooth actions created.

**Comment by yaseent** [comment]
Hello,

I do not seem to be experiencing this issue any longer. Thank you :)
