### ISSUE TITLE
Recording keyboard shortcut Command-N also adds a new item to shortcut list

### ISSUE THREAD

**Issue by olliebaum** [fifafu/BetterTouchTool#1892]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When recording a shortcut for a keyboard shortcut item, using Command-N will create a new shortcut item and sometimes not register the newly recorded shortcut.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: Macbook Air 2013
macOS version: 10.13.1
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should already be fixed in the latest alpha version (v2.319)
