### ISSUE TITLE
Error when checking for updates

### ISSUE THREAD

**Issue by NevinBR** [fifafu/BetterTouchTool#1894]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Recently, when I have BTT check for updates, it gives an alert that says “Update Error! An error occurred in retrieving update information. Please try again later.”

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

N/A

#### Device information:

Type of Mac: 2013 MacBook Pro, 15.4″
macOS version: 10.12.6
BetterTouchTool version: 2.319 (704)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Were you checking for alpha udpates? I think I had disabled the alpha route for 10.12.x, it should be active again now.

**Comment by NevinBR** [comment]
Ah yes, thanks.
