### ISSUE TITLE
Q: is there a way to add buttons to the default app bar?

### ISSUE THREAD

**Issue by estatematt** [fifafu/BetterTouchTool#1897]
The default Finder touchbar implementation is pretty great but it doesn't have a volume  slider.  Is there any way I can add one without having to flip between BTT and the finder buttons manually?

**Comment by fifafu** [comment]
Nope unfortunately this is not possible due to API limitations. How for volume you can just use the control strip slider, or is there a reason you don't use that?

**Comment by estatematt** [comment]
Yes, in the finder, for one-touch access, it appears as if I have to choose between an expanded "control strip (w/volume)" and "app controls (no volume)"  

BTT seems to operate either on its own control strip or completely taking over the entire touchbar leaving no room for these snazzy multilevel contextual buttons like "sort by..." Or "share..."

**Comment by estatematt** [comment]
(That's all to say, it seems impossible to have the share button and a volume slider readily accessible

**Comment by fifafu** [comment]
Do you know you can drag the volume icon in the control strip? No need to tap it first

**Comment by estatematt** [comment]
Yes.  Now BTT, on all apps is part of the control strip, meaning that everywhere there's an extra X box and the volume slider is redundant.  Gosh, I love BTT but it seems like apple has not made it easy for developers here.

**Comment by bar714** [comment]
Actually, you can set it up so BTT has separate interfaces per app, which would allow you to create a brand new Finder interface, effectively duplicate the vanilla one (maybe add/remove some features as per your liking), then add a volume slider. As for the "X" button, you can actually change it so BTT is the only Touch Bar that you should ever see: first, go to "General Touch Bar Settings" in top right of BTT, then uncheck "Show macOS control strip", then uncheck "If control strip is hidden: Show BTT Icon on left side." If you do that, you should never have to see the unfriendly default toolbar ever again!
