### ISSUE TITLE
Cannot add a gesture action using keyboard combination

### ISSUE THREAD

**Issue by n9yty** [fifafu/BetterTouchTool#1898]
Trying to set up an application-specific gesture.  I selected the application, then add gesture, but regardless of what keyboard combination I type into the box it never shows up in the upper area for this gesture.

If I pick a predfined action it will show up, but typing a keyboard combination will not.

Type of Mac:  Macbook Pro 2015
macOS version:  10.12.6
BetterTouchTool version: 2.319

**Comment by fifafu** [comment]
Oops, sorry. Fixed in 2.320 alpha (get via "check for alpha version updates")
