### ISSUE TITLE
Option for keyboard shorcut to bypass other BTT shortcut mappings

### ISSUE THREAD

**Issue by darvelo** [fifafu/BetterTouchTool#190]
#### Description of your feature request:

I like to set the shortcuts cmd+w and cmd+e to move a Space to the left or right. The positioning feels natural to my fingers. Unfortunately this means cmd+w, which is used in many apps for closing tabs and windows, is remapped. I'd like to map option+w to perform the original cmd+w function, but BTT recognizes this as a call  to the already-remapped cmd+w and moves left a Space instead. I'd like to be able to tell BTT that a mapping should pass through directly to the app, bypassing the internal BTT mappings.

**What kind of Mac are you using?**

MBP 2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Keyboard

**Which versions of macOS and BetterTouchTool are you running?**

OSX 10.12.2
BTT 1.978 (569)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

I've tried using using option+w to do BTT's Trigger Menubar Action shortcut, with the value `File;Close Tab||Close Project||Close Window||Close` but this doesn't work 100% as desired.

**Comment by fifafu** [comment]
The next update will include an option to "Prevent recursive triggers". This should be doing what you need.

![image](https://user-images.githubusercontent.com/8820811/30249130-342f5c5e-9635-11e7-9698-e362cdb42635.png)
