### ISSUE TITLE
[BUG] Fullscreen issue

### ISSUE THREAD

**Issue by CyborgSemon** [fifafu/BetterTouchTool#1900]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug:

When in fullscreen mode like a video on youtube, the exit fullscreen button somehow gets into the BTT touch bar app on the left behind the esc button.

#### Device information:

Type of Mac: MBP 13" Touch bar
macOS version: 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

BTT turned on while full screen
<img width="1085" alt="touch bar shot 2017-12-19 at 5 39 49 pm" src="https://user-images.githubusercontent.com/26075792/34141048-ad04def4-e4e3-11e7-974a-60f178192af1.png">

BTT turned off while full screen
<img width="1085" alt="touch bar shot 2017-12-19 at 5 40 00 pm" src="https://user-images.githubusercontent.com/26075792/34141054-b8fe7b5c-e4e3-11e7-8841-c2974ade28bd.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, unfortunately this can't be prevented due to API limitations :-( (as far as I know)
