### ISSUE TITLE
Unable to remap keys on keyboar

### ISSUE THREAD

**Issue by zingfrid** [fifafu/BetterTouchTool#1902]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm using different key layout and want Ctrl-C/Ctrl-V works. I'm trying to re-map it using BTT. Please, see video in attachment. On previous version I was able to do it without any issues.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
3-rd party Keyboard.

#### Device information:

Type of Mac: Mac mini
macOS version: High Sierra 10.13.2
BetterTouchTool version: 2.319

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Video with actual issue.
https://youtu.be/ChQHC78bdmA
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's a bug in the 2.319 alpha. Please update to 2.320 alpha.

**Comment by zingfrid** [comment]
I go to https://www.boastr.net/downloads/ press Download Trial button and get 319 version. Where I can get 320?

**Comment by fifafu** [comment]
For me it correctly downloads 2.320, maybe try again? (Maybe your browser had an old file in the cache?)

Otherwise use the "Check for alpha version update" button that should allow you to update.
