### ISSUE TITLE
how to access context SUB menu item, for example a menu item in the services sub menu

### ISSUE THREAD

**Issue by dorindon** [fifafu/BetterTouchTool#1904]
---

#### Description of bug/feature request/question:
Hello, I am a registered user of BTT, and have not found the answer in the forum
I have written a number of gestures which access the context menu with the Trigger Context Menu Item action, and they all work fine.
I don't understand how to activate a sub menu of the context menu, for example an item of the services sub-menu.
For example I wanted to create an Add to Evernote gesture as per below.

Thanks very much for your time and help

![image](https://user-images.githubusercontent.com/30017084/34170488-53d22de8-e4eb-11e7-888a-9b7179ea9de1.png)

#### Device information:

Type of Mac: IMAC retina
macOS version:  10.12.6
BetterTouchTool version: 2.318
latest Apple Magic Trackpad

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by waxfingers** [comment]
I use shortcuts, so I add application Finder the on the Keyboard tab > Trigger Context Menu Item
Then write > Services; Add to Evernote
It is a semicolon!! It's not very refined as it literally displays the dilaogs, terminal or better applescript seems faster and more effecient and flexible but takes longer to set... the poor man's fix =)

**Comment by dorindon** [comment]
@waxfingers 
thank you very much for your comment.
I am very sorry: I don't understand.
Let's take an example : I am in the app Apple Mail, I highlight text in an email and I want to create a new Evernote note containing that text.
Normally, I would highlight the text  ⇨ 2 finger tap for the context menu  ⇨ Services menu  ⇨ Add to Evernote.
I would highlight the text on my own (not using a BTT gesture)
then create a BTT gesture with the following action  ⇨ trigger context menu  ⇨ Services ? and after that ? I am confused.
thank you for your patience !

**Comment by waxfingers** [comment]
Servies ; Add to Evernote

**Comment by dorindon** [comment]
@waxfingers 
Now I understand ! thank you very much ! 
I will give it a try

**Comment by dorindon** [comment]
@waxfingers 

I found a solution in the meantime. Certainly not as intelligent as the one you propose, but it works.
It serves to access Add to Evernote as per the menu in the image in my previous post.
The first 'a' highlights add to iTunes and the second add to Evernote.
thanks again

![image](https://user-images.githubusercontent.com/30017084/34177863-7360c9de-e505-11e7-9bab-1ff3e610ffad.png)

**Comment by dorindon** [comment]
@waxfingers 

It's me again ! I just had an idea.

I very much like the browser called Vivaldi, so called for 'high power users'. Vivaldi has a number of features that accelerates workflow.

The big drawback is that the Vivaldi context menu does not provide access to the Services menu. 

Do you think that your automator 'create your own services menu' approach will help or does it presume that the app gives access to the services menu via the context menu?

**Comment by waxfingers** [comment]
I think the solution you found is perfectly valid. I can totally relate to the "quick & dirty baby steps" :P 
Just these days had to come with something similar as the settings I was targetting in inDesign were  (to the best of my knowledge) burried under innaccesible submenus. When one has to repeat an action 500 times... in few minutes created some shortcuts that speeded WF and made my wrist grateful. BTW, beware 'cause if you move a simple shortcut near a complex one, the later tends to "eat it".  

About Vivaldi, I still have it... though almost no use for it these days. By preference Opera, Safari and Firefox, Vivaldi. You can surely use BTT ro access the context menus in Vivaldi, as in the example above. But maybe, just maybe if you're using a lot certain submenu/servicies, you can spend some time exploring creating a service with automator and getting to know a bit about osx's own tools and other options that (again) you could also later trigger through BTT =)

**Comment by dorindon** [comment]
@waxfingers 
Thanks for the tip about simple vs complex shortcuts
Like you, I used to have Vivaldi and stopped using it. I only recently - in the past week- rediscovered it and it is now my preferred browser. 
Forget about which browser gets the best rating in terms of speed: it is a question of milliseconds.
In terms of workflow, I very much enjoy many features built into Vivaldi, such as stacked and tiled tabs, notes and snapshots attached to web pages and much more. 
Yes, you can find most of these functions in other browsers via extensions, but somehow built-in seems faster and more effective than an add-on or extension.
I am in the process of building my BTT gesture library for Vivaldi.
Just in case you would be interested.

**Comment by waxfingers** [comment]
Glad to contribute and thanks for the heads up. If you think you problem has been adressed you might consider closing the issue; it can be reopened at a later time if need be nad it's one less thing in dev's todo. Cheers

**Comment by dorindon** [comment]
Good idea. I will close the issue. thanks again very much
