### ISSUE TITLE
connecting a new siri remote

### ISSUE THREAD

**Issue by jurgenvinju** [fifafu/BetterTouchTool#1906]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Just bought a new Apple Tv Siri Remote 4 and trying to connect it to my MBP. The device seems to pair up fine using the bluetooth preferences in system configuration tool, but BTT does not recognize this device as a Siri Remote (yet).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Siri Remote 

#### Device information:

Type of Mac:  MacBook Pro (Retina, 13-inch, Late 2013)
macOS version: 10.12.6 (16G1036)
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The new siri remote requires at least macOS 10.13.2

**Comment by jurgenvinju** [comment]
thanks! upgrading now...

**Comment by jurgenvinju** [comment]
confirmed. thanks!
