### ISSUE TITLE
4-button anchored bar shifted to the left while running BTT = arrow to expand to default bar hidden 

### ISSUE THREAD

**Issue by cameronhope** [fifafu/BetterTouchTool#1907]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
(SOMETIMES) When running BTT, the 4 non-app specific buttons appear with an empty slot on far right. The 4th button, - the BTT button on the bar and the arrow to expand the 4-button to the default bar (standard hardware controls) - are therefore hidden under app-specific bar or a blank bar if no app specific bar is running. 

Restart of BTT does fix it, but the issue can reoccur during operation. Possibly linked to sleep/wake, often find this issue after reopening laptop. 

Has persisted through last 3 updates of BTT

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
'17 MBP TB 15" 

#### Device information:

Type of Mac:
macOS version: 10.12.6
BetterTouchTool version: Current

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
As far as I know this is fixed in macOS 10.13.x, unfortunately this can not be fixed completely for older macOS versions as far as I know ;-(
