### ISSUE TITLE
Left Mouse Button Intermittently stops working

### ISSUE THREAD

**Issue by JonJC** [fifafu/BetterTouchTool#191]
#### Description of your bug/question/feature request...:
I'm using a Logitec mouse.
The Left Mouse Button Intermittently stops working - I click it but nothing happens. If I then click on my Mac's TrackPad that click is recognised and from then the left mouse button works again.
This only happens when BTT is running.

**What kind of Mac are you using?**
MacBookPro 13" 

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Logitec Mouse

**Which versions of macOS and BetterTouchTool are you running?**
Sierra 10.12.1
BTT v1.9.6.3 (552)

**Comment by medalliated** [comment]
I'm experiencing the same problem.

MBP 15" 

Logitech MX Master

El Capitan 10.11.6
BTT v 1.978

**Comment by fpenguin** [comment]
I have the same issue.

Macbook Air 13"
Sierra 10.12.2 + Logitech G700s
BTT v1.963 (552)

**Comment by fifafu** [comment]
I'll look into this!

**Comment by JonJC** [comment]
thanks! BTW - love everything else about your product, very cool...

**Comment by bits** [comment]
This issue occurs for me several times an hour with a Logitech Anywhere MX — a real flow-crusher of a bug when left clicks sometimes have no result.

Unplugging and re-plugging the USB nano receiver also overcomes the issue and left clicks have effect again for some time.  It might recur a few seconds later or it may work for 20 minutes before failing again.

The normal mouse's other button clicks are not impacted, and continue to trigger normally while the left is impacted.

The issue did not occur from 2012 until a couple of weeks ago, I think (but not certain) concurrent with the upgrade to 1.963 (552) [OS X 10.11.6 / MBP 15" Mid-2015]

Thanks for looking into it.

**Comment by dionisokan** [comment]
Same issue here on macOS 10.12.2 Sierra, MacBook Pro early 2015 w/ Retina Screen.
I am using a Logitech M545 mouse, and latest BetterTouchTool.

**Comment by sdrygalski** [comment]
Same issue. I isolated problem to better touch tool. When I use right mouse button (because left is inactive until I press trackapd) to exit bettertouchtool everything is working ok again. :)

**Comment by sdrygalski** [comment]
Problem is affecting logitech anywhere mx 2 and logitech master mx. I tried to reinstall drivers, work without drivers at all, install 3rd party drivers (http://www.usboverdrive.com/USBOverdrive/News.html) and nothing helps.

**Comment by sdrygalski** [comment]
it's really painful to work like this so @fifafu I could beta test potential fixes if you need someone

**Comment by fifafu** [comment]
Unfortunately I haven't been able to reproduce this yet, if you can find any pattern please let me know. Have you already tried the current alpha version? (1.989)

**Comment by sdrygalski** [comment]
I installed alpha and nothing has changed. I can't really see any patterns, left mouse button just stop working after over a dozen of clicks. Sometimes it is several dozens. In all programs...

**Comment by bits** [comment]
Once the mouse's left clicks stop having effect, left clicks triggered with Karabiner MouseKeys also have no effect.  Other mouse buttons generated by the mouse or MouseKeys continue to work throughout and are not affected.  

To unjam, either any tap/click on the touchpad (which does have effect), quit BetterTouchTool, or unplug-replug theUSB receiver reliably returns left clicks from both "devices" to normal operation.  Until they stop working again.  

If BetterTouchTool is not running, the left clicks work at all times.  The effect is the same whether Karabiner is loaded or not.  BetterTouchTool being loaded is definitely the hinge point to triggering the problem.

@fifafu, please let me know how I can help.

**Comment by sdrygalski** [comment]
Guys, any alternatives to betterTouchTool if I use it only for keyboard shortcuts? It's clearly a deal breaker for me.

**Comment by dionisokan** [comment]
@sdrygalski, if you are looking for tools that provides custom keyboard shortcuts to launch applications, I think [Manico](https://itunes.apple.com/us/app/manico/id724472954) would be a nice choice. However if you need something more powerful I recommend [Hammerspoon](http://www.hammerspoon.org/) which bridges various system level APIs into a Lua scripting engine.

**Comment by fifafu** [comment]
I think Keyboard Maestro is also a very good alternative for Keyboard Shortcuts!

I'll get a Logitech MX master mouse soon, maybe I'll be able to reproduce the issue then.

**Comment by bits** [comment]
I have not experienced this issue since upgrading to 2.01 (597).  I've just taken 2.02 and will post if I see the issue recur.

**Comment by fifafu** [comment]
@bits I made some changes in >= v2.0 to target this, maybe they helped :-)

**Comment by bits** [comment]
Your changes did the trick.  Zero occurrences running 2.02 for a few days and 2.01 for a day or two before that.

Thank you.

**Comment by sdrygalski** [comment]
Unfortunately after this fix now I have problems with trackpad in macbook. Very similar to what was happening with mouse. I press trackpad many times and nothing is happening. I need to move my mouse 1/5 of screen to another place, go back and now button/link/program is clickable again. It's happening a lot of times.

When I turn off better touch tool completely or disable it for all apps this problem is not happening.

I think it could be hard to fix it, so maybe better touch tool could have option to disable everything related to mouse and trackpads? I use betterTouchTool almost only for altering keyboard and shortcuts and calling system commands (like notification center) so I would gladly disable all touch related stuff. @fifafu what do you think?

**Comment by sdrygalski** [comment]
It was my fault, more info here: https://github.com/fifafu/BetterTouchTool/issues/667#issuecomment-290830405

**Comment by tarwin** [comment]
I actually have the problem with the trackpad (built into laptop) now. Randomly it gets into a "mode" where I just can't left click anything. Right click still works, so I use that to close BTT, and things work again. I use double finger press for right click.

Macbook Pro 15in mid 2015
Sierra 10.12.5

**Comment by bits** [comment]
@fifafu I've been experiencing this issue again, since roughly a month ago (maybe more?).  Unfortunately, I didn't note the version where it began again.  I'm currently on 2.318.  Symptoms are as previously described.

I'm happy to help you debug, let me know what would help you.

**Comment by ruchenguang** [comment]
Same issue! 
Macbook Pro 15 2016 with touch bar
macOS High Sierra 10.13.2
Input device: Logitech MX Master (first generation)

**Comment by JamesTreasure** [comment]
I've also just started noticing this. I did a fresh install of OSX at the start of the week now I can't use my Mac with BTT as left click only seems to work 50% of the time.

Macbook Air 2013
macOS High Sierra 10.12.6
Input Device: Touchpad

**Comment by bits** [comment]
The frequency of occurrence has grown recently — it now happening multiple times per hour again.

It's very halting to productive flow to have clicks not register reliably.  Left click being the the prime action and all.

Please let me know what I can do to help you isolate.

BTT 2.340 / macOS 10.13.3 / MBP 15 2015

**Comment by MHX792** [comment]
Any ETA for fix? After using BTT for years, I needed to pause it because it is very annoying... :(
