### ISSUE TITLE
bettertouchtool only works for a few minutes

### ISSUE THREAD

**Issue by murongchenxing** [fifafu/BetterTouchTool#1910]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
bettertouchtool only work for a couple of minutes and then just do not respond to all the gestures, restart the app can solve the problem, but after a few minutes it will again lose responding. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
macbook trackpad.

#### Device information:

Type of Mac:macbook pro 2017
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have a valid license installed? BetterTouchTool usually only does this if it's a cracked version.

If so, please go to the about tab in BetterTouchTool and click the export debug info button. This will create a folder called BetterTouchToolDebug on your desktop. If possible please send me the contents (boastr.net@gmail.com)

**Comment by murongchenxing** [comment]
I don't know, I just downloaded this app from some website and installed it. maybe because I haven't got a valid license. I'm gonna go get one and try again, thanks a lot! :)
