### ISSUE TITLE
Trigger other keyboard shortcut not working

### ISSUE THREAD

**Issue by HoiJean** [fifafu/BetterTouchTool#1911]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When i try to add a shortcut key and add a trigger shortcut, it doesn't save it, Assigned Action stays:  No Action.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro Keyboard

#### Device information:

Type of Mac: Macbook Pro 15 
macOS version: 10.13.2
BetterTouchTool version: 2.319

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
https://i.imgur.com/5lerk1F.png

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Please update to 2.230 alpha (via check for alpha version updates)

**Comment by HoiJean** [comment]
Thank you, it works!
