### ISSUE TITLE
[Bug] BTT applying keyboard shortcuts to Spotlight Search

### ISSUE THREAD

**Issue by miechu** [fifafu/BetterTouchTool#1913]
#### Description of bug/feature request/question:
BTT doesn't recognize that app lost focus (to Spotlight Search cmd+space) and is applying the keyboard shortcut combo to Spotlight Search.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Air 13" 2013
macOS version: High Sierra 10.13.2 (17C88)
BetterTouchTool version: 2.318 (702) - latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

1. I've mapped enter to open files (like a sane person would do), the keyboard shortcut to open files in finder is cmd+arrow down
2. Open Finder
3. Open Spotlight Search via cmd+space
4. Search for something and try to open it via enter

Result: pressing enter results in moving to next item below (like pressing arrow down)
Expected: open item and not interpret any keyboard shortcuts while in Spotlight Search

Screenshot of keyconfig for Finder: https://ibb.co/kiDkH6

**Comment by fifafu** [comment]
Sorry, unfortunately Spotlight doesn't tell when it became frontmost. Thus this is not possible as far as I know.

**Comment by harsilspatel** [comment]
Instead of mapping _return_ to _cmd+arrowDown_, you can map it to _cmd+O_
Tried and tested, works with spotlight! 🙂
