### ISSUE TITLE
Chrome specific keyboard shortcut can't assign other keyboard shortcut

### ISSUE THREAD

**Issue by drewdouglass1** [fifafu/BetterTouchTool#1914]
#### Description of bug/feature request/question:
I am trying to create a keyboard shortcut just for Chrome that replaces the enter key with CMD+Enter so that I can open a new tab when I type something in the address bar. However, when I try to set it up based on the docs it shows the "Assigned Action" as "No Action". If I choose a "Predefined Action" then it works as expected.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Logitech K350 WIreless keyboard

#### Device information:
Type of Mac: MBP 2016 with Touchbar
macOS version: 10.12.6 (16G1114)
BetterTouchTool version: 2.319

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://user-images.githubusercontent.com/26604925/34214534-ca447f14-e570-11e7-9491-e8dffd2db1db.png)

**Comment by drewdouglass1** [comment]
I was able figure out a workaround a few minutes after I submitted this request.

**Comment by drewdouglass1** [comment]
If

**Comment by fifafu** [comment]
Sorry, please update to the 2.320 alpha (via check for alpha version updates)

**Comment by drewdouglass1** [comment]
Thanks Andreas.  This tool is amazing btw. Just updated and works as expected.
