### ISSUE TITLE
Critical: Trackpad Scrolling Unusable While BTT is Open

### ISSUE THREAD

**Issue by vexir** [fifafu/BetterTouchTool#1919]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Scrolling with the Macbook Pro trackpad lags by almost a full second while BTT is active. This problem started this morning. Quitting BTT immediately resolves the problem; restarting BTT brings the problem back after 1-2 min. I can't use BTT at all in this state as it adds friction across every app that involves scrolling, including all browsers (Chrome, Safari) and all document viewers (Preview, Adobe Reader).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: High Sierra 10.13.1 (17B1003)
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Maybe check if there is any process that is eating a lot of CPU (via activity monitor).

**Comment by vexir** [comment]
Yes, I did so. That's how I remembered BTT was running and likely the only 3rd party app that affected the trackpad. Killing it immediately fixed the problem, and starting it almost immediately brought it back.

**Comment by fifafu** [comment]
Yes, but BTT alone doesn't cause scroll issues. Usually something like this can happen if some process is taking a lot of CPU and thus makes it impossible for BTT to process the events fast enough.

Have you already tried to restart your Mac?

**Comment by GameCake** [comment]
I did, several times. I also restarted it in safe mode and reset the SMC. Safe mode fixed it, because BTT presumably wasn’t running. SMC Reset did nothing. 

Is there a log I can output from BTT that might help diagnose?

**Comment by vexir** [comment]
I did, several times. I also restarted it in safe mode and reset the SMC. Safe mode fixed it, because BTT presumably wasn’t running. SMC Reset did nothing.

Is there a log I can output from BTT that might help diagnose?

**Comment by fifafu** [comment]
Unfortunately there probably won't be logs, as BTT is not actively doing anything with the scroll events.
Can you think of anything you installed or did before this started to happen? (There hasn't been a change to BTT that influences scrolling recently).

I'd however recommend updating to macOS 10.13.2 as Apple has fixed various issues with that version.

**Comment by vexir** [comment]
I seem to remember Karabiner-Elements having an update earlier in the day. I’ll update OSX and report back later tonight.

**Comment by vexir** [comment]
@fifafu Upgrading OSX seems to have done the trick. I'll close.
