### ISSUE TITLE
BTT menu icon disappears, stops working, and then reappears after one minute.

### ISSUE THREAD

**Issue by bcodeine** [fifafu/BetterTouchTool#1920]
#### Description of bug/feature request/question:
When I gesture on the magic mouse, BTT menu icon disappears, and BTT functionality stops.  After a minute, the BTT menu icon reappears and functionality is restored.  This cycle happens over and over again and does not stop.
 I have tried erasing BTT library files and reinstalling BTT app, restarting computer, but still it crashes.

Two possible causes:
1)  I installed the latest Apple security update.
2) I tried using the "Manage Presets" feature for the first time.
Unfortunately, I did both of these today before noticing the issue, but I noticed it right after the trying "Manage Presets".

Before this, BTT has worked great.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse

#### Device information:

Type of Mac:  desktop
macOS version: 10.12.6
BetterTouchTool version: 2.320 (705)

[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1581303/BetterTouchToolDebug.zip)

[Problem Report.txt](https://github.com/fifafu/BetterTouchTool/files/1581307/Problem.Report.txt)

**Comment by FligMupple** [comment]
I have the exact same problem. Started a few days ago.

**Comment by fifafu** [comment]
This crash can currently happen if you have triggers added to BTT, but not assigned an action to them. Removing these should fix it.

I'm looking into what exactly is causing this. However I'm already tracking this in another issue, thus I'm closing here.

**Comment by bcodeine** [comment]
I use triggers with no actions to stop the mouse gestures from doing things in certain apps.  So I just assigned some unused key combos into the formerly unassigned triggers and so far so good.  Thanks for the quick solution!!
