### ISSUE TITLE
Cannot assign a Custom Keyboard shortcut

### ISSUE THREAD

**Issue by connorsadlervelo** [fifafu/BetterTouchTool#1921]
#### Description of bug/feature request/question:
I Cannot assign a Custom Keyboard shortcut at all
I add an entry and assign a gesure and associated keyboard shortcut, but it does not "stick"

Steps
- Trackpads tab
- Add new gesture
- On touchpad gesture, select 2 finger swipe right  (or anything)
- On custom keyboard shortcut, hit Control + Tab
- it kind of looks like it worked, I see the gesture and control + tab in the list
- but Assigned Action/Shortcut still says No Action in the list
- exit Preferences
- rerun Preferences
- the entry in the list is still there but no keyboard shortcut is assigned

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro Trackpad

#### Device information:

Type of Mac: Macbook Pro 2017 (3 weeks old) with touchbar
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.319

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I cannot find a workaround
I have tried restarting the Macbook and it didn't help

**Comment by fifafu** [comment]
sorry that was a bug in the 2.319 alpha. Please update to 2.320 (via "check for alpha version updates")

**Comment by connorsadlervelo** [comment]
Thanks, that works!
