### ISSUE TITLE
BetterSnap Tool works even its unninstalled. 

### ISSUE THREAD

**Issue by cinges** [fifafu/BetterTouchTool#1922]
Hi, I installed BetterSnap tool, and there was probem with double animation for resizing. One was original, ugly blue with white border and second was mine I set. I didnt figure out, how to solve it, so I unninstall BetterSnap tool with AppCleaner, and there MacOS still snapping windows! (only original animation) how can I solve it?

**Comment by fifafu** [comment]
Bettersnaptool definitely doesn't work if it's not running :-)

Do you maybe have another window snapping app running? or my other app, BetterTouchTool?

**Comment by cinges** [comment]
oooh.. I didnt find option for snapping in better touch tool before..! I thought that there is no such option. Now its okay, my fault..:(
