### ISSUE TITLE
Bug: All applescript formatting changed

### ISSUE THREAD

**Issue by bar714** [fifafu/BetterTouchTool#1928]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
All my custom AppleScript widgets for Touch Bar have suddenly disappeared. I went into settings to discover that their formatting was changed and any attempt to compile/run was met with syntax errors. I tried making a VERY simple button to show the output muted of (get volume settings) and even that wouldn't work due to "syntax errors." It has suddenly fixed itself for no apparent reason (while I was typing this, after having given up hope) so I'm not sure that this should be a high priority at all, just figured I would document this for others' reference. I LOVE this tool by the way. Thank you for devoting your personal time to this project.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MBP Touch Bar

#### Device information:

Type of Mac: MBP 2017 w/ TB
macOS version: 10.13
BetterTouchTool version: currentzx

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird. BTT doesn't save formatting, but it relies on the system Apple SCript service. Maybe that service crashed, which would explain why the syntax coloring didn't work anymore.

I'll close here for now, but if it happens again, please reply again.

**Comment by merlinND** [comment]
Something similar happened to me before: formatting, compile / check, and script running had all stopped running. It turns out the Apple SCript service itself was the cause, and I just had to restart that to get everything to work again.
