### ISSUE TITLE
Bug: predefined action 'Show / Hide hidden files in Finder' does not work

### ISSUE THREAD

**Issue by StyloBill** [fifafu/BetterTouchTool#1929]
#### Description of bug/feature request/question:

The predefined action 'Show / Hide hidden files in Finder' does not work and nothing happens when triggering it.

#### Device information:

Type of Mac: MacBook Pro 13 early 2015
macOS version: 10.13.2
BetterTouchTool version: 2.320

**Comment by fifafu** [comment]
Weird, does pressing "shift+cmd+." manually work for you? (That's all BTT does)

**Comment by StyloBill** [comment]
Nope, this shortcut has been changed in High Sierra and is not working anymore. In High Sierra it changes the view to the column view.
I've been looking for a new shortcut to show hidden files in Finder, but was not able to find one.

**Comment by fifafu** [comment]
It definitely works fine here on High Sierra on both of my machines. Have you maybe overridden the cmd+shift+. shortcut in BTT or in System Preferences => Keyboard => Shortcuts?

**Comment by StyloBill** [comment]
Ok so I know what the issue is. I've purchased this MacBook recently and it has a Canadian-French keyboard layout. My previous Mac had the US layout and was on Sierra. With the Canadian-French keyboard layout, the Finder shortcuts are not the same for some reason, so every time I input Shift+CMD+.  , it triggers Shit+CMD+" (the " char is on the same key as the . char, so Shift triggers the " char), which is the shortcut for the column view.

I'll try to change this in the preferences, or to override this in BTT.

Thank you and sorry to have wasted your time!

<img width="321" alt="capture d ecran 2017-12-28 a 11 55 34" src="https://user-images.githubusercontent.com/5800483/34417435-8d820bd0-ebc6-11e7-8312-d17572e3a9f2.png">
