### ISSUE TITLE
CMD + arrow doesn't repeat.

### ISSUE THREAD

**Issue by TeffenEllis** [fifafu/BetterTouchTool#193]
#### Description of your bug/question/feature request...:
I'd like to make shortcut that maps command+arrow to option+arrow. This would let me move my text caret between words.
I'm able to do this on key up, though triggering on key down with a repeat does not produce any effect. 
I added a HUD overlay to test this key combination and it does appear when pressed, though there is no caret movement.

Thank you for your help. BetterTouchTool has saved my hands :-)

**What kind of Mac are you using?**
2015 MacBook
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Built-in Keyboard

**Which versions of macOS and BetterTouchTool are you running?**
 Sierra 10.12.2, BTT 1.963

**Comment by fifafu** [comment]
Thanks for reporting! I'm tracking the issue here: #199
