### ISSUE TITLE
[Bug] Cannot set opacity in colour picker

### ISSUE THREAD

**Issue by n0mar** [fifafu/BetterTouchTool#1930]
#### Description of bug/feature request/question:

- Enable Advanced Settings

- Advanced Settings > Window Snapping > Appearance of preview window: > Background color:

- Select colour

- **Cannot choose opacity options**

#### Device information:

Type of Mac: MacBook Pro 2016 with Touch Bar
macOS version: macOS 10.13.2 (17C88)
BetterTouchTool version: 2.138 (702)

**Comment by fifafu** [comment]
Mh, this seems to work fine here, is the opacity slider not available at all?

![image](https://user-images.githubusercontent.com/8820811/34416953-f6255712-ebc3-11e7-9b49-ab456193c3e9.png)

**Comment by n0mar** [comment]
Hi @fifafu!  
Seems to be a High Sierra bug that has sorted itself out. **This issue can be closed.**

Thanks!
