### ISSUE TITLE
[Bug] General Touchbar Settings: it stopped working

### ISSUE THREAD

**Issue by raffoz** [fifafu/BetterTouchTool#1932]
#### Description of bug/feature request/question:
I changed something in General Touchbar Settings and it worked.
I could have widgets and so on.
Now, without any reason, it doesn't work anymore.

I just see the normal Touchbar: I cannot understand why.
I'm playing around, I tried everything.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:
Type of Mac: MacBook Pro 15
macOS version: 10.13.2
BetterTouchTool version: 2.320

**Comment by raffoz** [comment]
If from menu bar I disable and then reable BTT, it reworks.

**Comment by Jonathan123456Hub** [comment]
I have exactly the same issue - only by disabling and reenabling BTT as Raffoz suggested - Is this a bug?

**Comment by Jonathan123456Hub** [comment]
I have to go through the enable/disable process quite frequently - It would be great if the developer would provide an update to this common issue

**Comment by fifafu** [comment]
I don't think there is a common issue. The Touch Bar gets hidden if you press the X button, and you can bring it back by tapping the BTT icon or by using the predefined action "Toggle BetterTouchTool TouchBar"

If I misunderstood - please comment again or create a new issue.

**Comment by Jonathan123456Hub** [comment]
“X’ key does not hide touch bar 


I set up a button called “Toggle” using the predefined action “Toggle BetterTouchTool TouchBar” - once selected the default system Touch Bar appears without the Toggle button - How do you toggle back to the custom bar?




Sent with Unibox

**Comment by Jonathan123456Hub** [comment]
I now set the Toggle in BTT remote - does not toggle




Sent with Unibox

**Comment by Jonathan123456Hub** [comment]
It now toggle a number of times from BTT remote - then sticks to default


Only remedy is to quit and restart the app




Sent with Unibox
