### ISSUE TITLE
[BUG] "Allow system apps like iTunes or Xcode to replace BTT Control Strip Icon" not working

### ISSUE THREAD

**Issue by growler17** [fifafu/BetterTouchTool#1933]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The TouchBar flag "Allow system apps like iTunes or Xcode to replace BTT Control Strip Icon" does not function properly with most system apps. It appears to only work properly with Safari. 

Does NOT work with reminders, mail, calendar, notes, reminders, photos, messages, Xcode, iBooks, system preferences, and I reckon any other Mac system app! On these apps the BTT TouchBar widgets always take precedence and are displayed unless I manually shutdown BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook TouchBar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: High Sierra 10.13.2
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<img width="847" alt="tb_settings" src="https://user-images.githubusercontent.com/7841219/34424817-6235ba3e-ebdb-11e7-920d-1f10a501e852.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately I have not found a solution to this problem, thus I'm closing here as I don't think it can be fixed (currently cleaning up a bit).

Currently the best way is to disable the "Show BetterTouchTool Icon in Control Strip" option. I'll remove the other checkbox soon.
