### ISSUE TITLE
BUG: Text box issue with Custom Apple Script Slider

### ISSUE THREAD

**Issue by horvathb** [fifafu/BetterTouchTool#1935]
Adding line breaks to the text area in the custom apple script slider reduces the size of the text box. After a few line breaks the text area completely disappears. See screenshot.

Type of Mac: 2017 13" rMBP
macOS version: 10.13.2
BetterTouchTool version: 2.320

<img width="1440" alt="screen shot 2017-12-29 at 13 16 51" src="https://user-images.githubusercontent.com/5796027/34437074-6ce4e99e-ec9b-11e7-9465-cf53d035a494.png">

**Comment by fifafu** [comment]
Thanks for reporting! Will be fixed with the next update later this week.
