### ISSUE TITLE
apple Magic Mouse middle click

### ISSUE THREAD

**Issue by vidotto** [fifafu/BetterTouchTool#194]
I cannot crete a gesture working for reproducing a middle click action in Apple Magic Mouse.
Up to about one week ago I had a gesture that worked perfectly (3 Finger Click -> Middle Click), but now I cannot obtain a Middle Click action, even if I select gestures different form 3 Finger Click.

Mac Book Pro with OS X Sierra 10.12.2 (16C67)
Apple Magic Mouse
Better Touch ver. 10.12.2 (16C67)

Any suggestion is warmly welcomed.
Many thanks and Happy New Year.

**Comment by fifafu** [comment]
Have you been able to get it to work?
Have you already tried to restart BTT/your Computer? In general 3 Finger Click => Middle Click should work fine.

**Comment by vidotto** [comment]
In fact it worked perfectly in the past. I have already tried to restart BTT, the computer, to reinstall BTT and recreate the gesture…none worked. 
In the Live Live the gesture is not recognized at all...


******************************
 Prof. Francesco Vidotto
 Università di Torino
 DISAFA
 Via L. Da Vinci, 44
 10095 GRUGLIASCO (TO)
 ITALY
 tel. +39 011 6708781
 fax +39 011 2368781
 www.disafa.unito.it
orcid.org/0000-0002-0971-1445
******************************

**Comment by smurfless1** [comment]
Same: 10.12.3 and 1.994. I tried 2 and 3-finger tap and click, but there just aren't any middle clicks going to the system

**Comment by vidotto** [comment]
Still not working with BTT version 2.02 (598)

**Comment by smurfless1** [comment]
I upgraded to 2.02 and restarted the mac and it started to work. No idea.

db

**Comment by vidotto** [comment]
Nope. Upgraded to 2.02, restarted BTT, restarted Mac. Still not working.
Completely uninstalled BTT, restarted Mac, reinstalled BTT, created gesture...nothing.
I noticed, by using live view, that whatever gesture I select, the Predefined Action "Middle click" is never recognized. Really strange, indeed.

**Comment by fifafu** [comment]
I haven't had any other reports of such an issue for the last few versions. In case you still encounter this please go to the about tab in BTT, then click the export debug info button. This will create a folder "BetterTouchToolDebug" on your Desktop. If you send that to me I may be able to reproduce it (boastr.net@gmail.com)

For now I'm closing here.
