### ISSUE TITLE
Account option request - "log in" so you don't lose your data

### ISSUE THREAD

**Issue by itsnosolution** [fifafu/BetterTouchTool#1940]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
It would be nice to have a "log in" / accounts option so that we dont lose everything if we get a new computer or have to reinstall. 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can use the dropbox sync in the advanced preferences.

Alternatively you can use the Manage Presets => Export to save a copy of your settings.
