### ISSUE TITLE
How to create an apple script that reads the recent notification form notification centre 

### ISSUE THREAD

**Issue by nottayo** [fifafu/BetterTouchTool#1941]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hello,
I’m trying to create an apple script that reads the recent notification form notification centre and then I can add this to the touch bar using Better touch tools. Please if you can be of any assistance :)

#### Device information:

Type of Mac:MACBOOK PRO 2016 15"
macOS version: 10.13.2
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately I don't know whether that's possible (I don't think so). Thus I'm closing here. If you can find a solution please let me know.
