### ISSUE TITLE
Gets stuck on key repeat

### ISSUE THREAD

**Issue by PaulWen** [fifafu/BetterTouchTool#1945]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have the 'ijkl' keys combined with the cmd-key remapped to the arrow keys with key hold repeating enabled. Uncountable times while using cmd+i to move the cursor 'up', the cursor has gotten stuck moving up and I am unable to regain control of it without killing btt.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook keyboard

#### Device information:

Type of Mac: MacBook Pro 15 (mid 2017)
macOS version: 10.13.2 (17C88) 
BetterTouchTool version: 10.13.2 (17C88)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Workaround: I added a "Restart BTT" button to the touch bar in order to quickly restart BTT if the problem occures.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
With recent versions the keyboard stuff has completely been rewritten. Does this still happen to you?

**Comment by PaulWen** [comment]
Thank you for the feedback! I have not experienced this issue for a while now so it seems to be fixed.
