### ISSUE TITLE
BTT crashes daily

### ISSUE THREAD

**Issue by yo3yo3yo3yo3** [fifafu/BetterTouchTool#1947]
_#### Description of bug/feature request/question:_ While working on 2017 MacBook Pro with Touch Bar, my custom Touch Bar configuration made in BTT will just disappear several times throughout the day and I see that the BTT app has quit. If I relaunch the app, my custom Touch Bar comes back. This was going on for 4-5 weeks and I actually tried updating to an Alpha version which has not helped. Have tried restarting computer as well. 

_#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):_ Touch Bar.

_#### Device information:_

Type of Mac:  2017 MacBook Pro with Touch Bar
macOS version: 10.13.2 (17C88) - macOS High Sierra
BetterTouchTool version: 2.320 (705)

_#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):_  I haven't changed any BTT settings for several months. This just started happening in early December 2017. When this issue occurs, I normally relaunch BTT right away to get my custom Touch Bar back, but for the first time just now, I tried just waiting and seeing what would happen and apparently the custom Touch Bar came back on its own after 30-60 seconds. 

I did not know about Console.app and User Diagnostic reports before reading about it here. There are 20 crash logs from BTT! :) I will attach some to this. Thanks. 

[BetterTouchTool_2018-01-02-074612_MBP15-CH.pdf](https://github.com/fifafu/BetterTouchTool/files/1598616/BetterTouchTool_2018-01-02-074612_MBP15-CH.pdf)
[BetterTouchTool_2017-12-29-202441_MBP15-CH.pdf](https://github.com/fifafu/BetterTouchTool/files/1598617/BetterTouchTool_2017-12-29-202441_MBP15-CH.pdf)
[BetterTouchTool_2017-12-29-080802_MBP15-CH.pdf](https://github.com/fifafu/BetterTouchTool/files/1598618/BetterTouchTool_2017-12-29-080802_MBP15-CH.pdf)
[BetterTouchTool_2017-12-17-165106_MBP15-CH.pdf](https://github.com/fifafu/BetterTouchTool/files/1598619/BetterTouchTool_2017-12-17-165106_MBP15-CH.pdf)
[BetterTouchTool_2017-12-07-180356_MBP15-CH.pdf](https://github.com/fifafu/BetterTouchTool/files/1598620/BetterTouchTool_2017-12-07-180356_MBP15-CH.pdf)

**Comment by fifafu** [comment]
Unfortunately this is a macOS bug in 10.13.2.
I have already reported it to Apple.

It only seems to happen on very few systems though, thus reproducing it is hard. If you can find any pattern as to when that happens, please let me know.

**Comment by yo3yo3yo3yo3** [comment]
**If I disable the Touch Bar customizations in BTT, will that stop BTT from crashing?** That could be an option for me since I frequently use a USB external keyboard and mouse. 

I spend a lot of time working in Parallels Desktop 13 running a Windows 10 VM on my Mac. For me, this issue has only happened at random while typing on the external keyboard in Windows and not interacting with the Touch Bar at all. Not sure how useful that information is. Was hoping my crash logs might help.

Thanks for the quick response! Glad to hear this has at least been reported to Apple.

**Comment by TaylerUva** [comment]
I have a Mac without the touch bar and I am also experiencing this issue. I experience random crashes but do not get any dialogs, my BTT simply stops working and I have to open it again. Its hard to tell when it crashes as I don't notice until I try to use an action and it doesn't work.

**Comment by fifafu** [comment]
Tracking this here: #2020
