### ISSUE TITLE
Clicked on mouse right button once, but system think it’s a dragging action

### ISSUE THREAD

**Issue by afaye0211** [fifafu/BetterTouchTool#1948]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
It happens **VERY OFTEN**, I only clicked on mouse right button once, but system performs like I‘m pressing the right mutton, it drag items. 

This is really annoy and I’ve already reported this once.
https://github.com/fifafu/BetterTouchTool/issues/1705

Do you notice this is still happening and not fixed yet?
Thanks!
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mouse

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.320 (705)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by afaye0211** [comment]
Hello?
Any update?

**Comment by fifafu** [comment]
Unfortunately I have never been able to reproduce this and haven't had similar reports yet. 
Can you reproduce this issue somehow?
