### ISSUE TITLE
BTT uses dedicated GPU (MacBookPro 2010)

### ISSUE THREAD

**Issue by kwaaak** [fifafu/BetterTouchTool#195]
BetterTouchTool and BetterSnapTool use the dedicated GPU.
This seems to be unnecessary and contributes to higher energy consumption/lower battery life.

**What kind of Mac are you using?**
MacBook Pro 2010

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.2
BTT 1.963

![bildschirmfoto 2017-01-02 um 19 18 38](https://cloud.githubusercontent.com/assets/1127491/21594348/da371062-d121-11e6-8ae6-e20c21a146a8.png)

**Comment by fifafu** [comment]
Unfortunately I have not found a solution to this and I don't have a MBP 2010 to test on :-(

It seems to be a macOS bug as it only happens on the 2010 MBP and on no other machines, however it's really hard to debug and I currently doubt I'll ever be able to fix it (unless Apple releases a fix).

I looked at ebay for a cheap MBP 2010, however they are still quite expensive...

**Comment by kwaaak** [comment]
That is very unfortunate indeed.
Both BTT and BST are also listed in the menu bar battery dropdown menu
![bildschirmfoto 2017-01-13 um 02 17 46](https://cloud.githubusercontent.com/assets/1127491/21914924/a6a45fb2-d936-11e6-91e3-26d1f33e3bc0.png)

If there is anything I can do or run to narrow down the bug, let me know.

**Comment by kwaaak** [comment]
Looks like it was fixed in 10.12.3 (16D32)

![bildschirmfoto 2017-01-26 um 09 20 24](https://cloud.githubusercontent.com/assets/1127491/22324297/c1dc4a48-e3a8-11e6-8077-f6a4a9150a41.png)

**Comment by fifafu** [comment]
@kwaaak omg that's awesome :-) I almost bought an old Macbook the other day
