### ISSUE TITLE
Window Snapping: Interfering with full-screen games/apps

### ISSUE THREAD

**Issue by bisko** [fifafu/BetterTouchTool#1950]
#### Description of bug/feature request/question:
A few weeks ago I noticed that I can't reliably play strategy games, because whenever I tried to do a "drag-selection" to select multiple units, the cursor "froze" for a fraction of a second before starting to move again. It was frustrating, but I played it off as something specific to the game I played.

Today I was playing another game and noticed the same thing was happening whenever I just clicked the left button: click the button and the cursor freezes for a moment and then starts moving again. 

I researched around to what might be causing this (still didn't realize it was because of BTT) and saw some suggestions that mouse actions can be affected by third-party apps. Since BTT was the only one I have installed, I started messing around with settings. 

After some trial and error, seems like the culprit is Window Snapping. At the moment I disable it, the issue goes away in the game.

An interesting point is that the issue is not happening outside of games. Other fullscreen apps work properly.

#### To reproduce: 
1. Start a game - Noticed this with the first StarCraft and Heroes of the Storm (both free, so easier testing :))
2. Start playing
3. Try to move the cursor around the screen and while moving click the left mouse button
4. Notice the cursor stopping for a fraction of the second at the moment of the click
5. Try to make a drag selection ( to select multiple units in StarCraft for example ). 
6. Notice how the cursor and the selection don't move for a fraction of the second and then start working again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
External Bluetooth mouse - Razer Orochi 2016

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) (with TouchBar)
macOS version: 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
The only workaround I've found is to disable Window Snapping while playing games, which is a bit annoying, as I have to go into settings and manually change it.

**Comment by fifafu** [comment]
Unfortunately this can happen if apps don't support an Apple API correctly. However you can disable BTT or Window Snapping for these problematic apps.

Just add the games to the BTT App List and disable window snapping for them like shown in this screenshot:
![image](https://user-images.githubusercontent.com/8820811/34640149-9283b1f0-f2ed-11e7-874c-1b129e751df0.png)

**Comment by bisko** [comment]
Sorry for getting that long to get back to you! 

This fixed the issue! Thank you for pointing me in the right direction!

I'm also happy to report that some of the game developers are already taking care of that in updates and we don't have to add exceptions.
