### ISSUE TITLE
Text cursor sometimes jumps backwards sporadically when typing

### ISSUE THREAD

**Issue by Pripps** [fifafu/BetterTouchTool#1952]
#### Description of bug/feature request/question:
Text cursor jumps backwards sporadically when typing/entering text. (Email, Notes, Pages, etc).

I've tested and isolated BTT by forcefully and rapidly input random text with and without BTT active. Additionally I disconnected all external devices. I also tested with various settings both for the os and BTT. (Can't figure it out).

What happens is while typing, the cursor randomly sometimes jumps back 1 or more letters making typing very faulty and annoying.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Internal keyboard

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.13.2
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I attached a video showing what is happening.  This behaviour I can't provoke wo BTT activated.  It happens regardless of the current app for text input is setup in BTT or not.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnosti
[Cursor jumps.zip](https://github.com/fifafu/BetterTouchTool/files/1600268/Cursor.jumps.zip)

c Reports" section.

**Comment by fifafu** [comment]
You probably have some gesture configured in BTT that you accidentally trigger while typing.
Maybe corner taps?

**Comment by Pripps** [comment]
Thanks for rapid response!

I use a touchpad 2 on the side with the internal touchpad disabled by the "ignore built-in touchpad" setting.

(Swedish OS.. Sorry!)



Kind regards,
Klas Wikberg

**Comment by Pripps** [comment]
Just discovered that one corner click on the interna still triggers "sleep monitor”, despite the setting to ignore it.

Will try w this setting off.  Thanks.

/Klas

**Comment by Pripps** [comment]
You were right of course :) - I had a left arrow triggered by tap on middle left.

I’m just a bit confused that the internal touchpad still triggers BTT while it is set to ignore..?

Is there a more reliable way to completely disconnect the internal touchpad within BTT while using an external?

Thank you anyway!

**Comment by Pripps** [comment]
And I just found that setting.  Thanks again!  Sorry for all the responses.

/Klas
