### ISSUE TITLE
The app used 90% cpu power

### ISSUE THREAD

**Issue by FriGo74** [fifafu/BetterTouchTool#1954]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
App started to rev up my Macbook pro, Activity Monitor showed 90% cpu usage, fan was blasting...very unusual for a app

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13.2 High Sierra
BetterTouchTool version: Latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mh do you have any custom scripts added to BTT?

**Comment by FriGo74** [comment]
I used this version of it https://github.com/krunkosaurus/bettertouchtool-crypto
The crypto toolbar

**Comment by fifafu** [comment]
I think there have been various fixes related to this in the latest version. If it still happens please let me know. Also I really recommend https://github.com/chrislennon/Crypto-Touchbar-App
