### ISSUE TITLE
how to access context menu items with a variable name

### ISSUE THREAD

**Issue by dorindon** [fifafu/BetterTouchTool#1958]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hello,

Most context menu items have a fixed name. Some however are variable. I am learning german and often use the dictionary. 
If I right click on a german word, for example Gesetz in the article below, the context menu item reads **Look up "Gesetz"**
How do I write a context menu action when an item is variable ?

thanks very much for your time and help

![image](https://user-images.githubusercontent.com/30017084/34599281-979f3a62-f1f1-11e7-8fdc-c032e9cd0f71.png)

#### Device information:

Type of Mac:iMac Retina display late 2014
Apple Magic Trackpad
macOS version: Sierra latest version
BetterTouchTool version: latest version

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can either use numbers like this:
```(1)```

Or you can use a star for wild card matches:
```Look Up*```

![image](https://user-images.githubusercontent.com/8820811/34639989-c09bb31a-f2ea-11e7-8724-f0bc95d8cae5.png)

**Comment by dorindon** [comment]
thanks very much !

**Comment by dorindon** [comment]
Hello, 
I like your suggestion of the (1) method of accessing context menu items by number instead of text.
How about submenu items (for example the submenu of the context services menu): for example, let's assume that services is the 3rd item in the context menu and Add to Evernote is the 4th item of the services context submenu.
Could I write BTT context item as below ?
(3);(4)
Do I need to add spaces of any special character?
thanks again very much

**Comment by dorindon** [comment]
how does one Reopen a closed issue ?
thank you
