### ISSUE TITLE
Relative mouse position not working for Chrome

### ISSUE THREAD

**Issue by sdevan45** [fifafu/BetterTouchTool#1960]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm trying to get BTT to click at a coordinate position in Chrome.  No matter what coordinates I enter for the relative mouse position for the Chrome window, it always clicks in the same spot -- the favorites star at the right end of the url entry field.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
I'm using a Logitech MX mouse, but I'm not using the Logitech driver.  I use SteerMouse.  

#### Device information:

Type of Mac: iMac
macOS version: 10.13.2
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, this seems to work fine here.
Are you sure the relative checkbox is enabled? See this screenshot:

![image](https://user-images.githubusercontent.com/8820811/34639816-7e21fd62-f2e7-11e7-822a-e85a84a111cd.png)

**Comment by sdevan45** [comment]
Yup, I'm sure. That is weird. I wonder if one of my other extensions is 
causing the problem. I'll check that out and let you know.

Steve


Andreas Hegenberg wrote:

**Comment by sdevan45** [comment]
Here you go

**Comment by fifafu** [comment]
Does this still not work for you?

**Comment by sdevan45** [comment]
I’ve got it working. Thanks for the follow up.
