### ISSUE TITLE
Import/Export of settings/shortcuts with new MacBook?

### ISSUE THREAD

**Issue by rootofans** [fifafu/BetterTouchTool#1962]
Hello community,

last time I had a problem I was happy to see how quick and friendly I got help here - that's why I approach y'all again.

I recently got a new Mac and was already able to transfer my BTT licence on my new device, however I was unsuccessful trying to import all the shortcuts and settings I created on my old MacBook over the years. Is there a way to export those from my old device and somehow "install" them on my new Mac, or do I need to create/add every shortcut separately?

Thanks in advance - looking forward for some help.

Greets.
rootofans

**Comment by fifafu** [comment]
You should be able to click the "Manage Presets" button and then the export button. This will export all the gestures and shortcuts in your current preset.

Alternatively you can copy the ~/Library/Application Support/BetterTouchTool  folder and the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist

**Comment by rootofans** [comment]
Unfortunately neither of those options seem to work for me. I updated on the newest version.

When I try to export the Default/Master-file in the "manage presets" menu, the download doesn't start on my old Mac (It does on the new one though; It also does when I create a new one on the old one). Besides that I can't find the folder/file you described the pathway to.

**Comment by fifafu** [comment]
You can go to the folder by pressing cmd+shift+g or by using the "go to" menu item in Finder.

**Comment by rootofans** [comment]
That worked perfectly, thanks a lot Andreas!

**Comment by Worie** [comment]
I guess it happens on my Mac, too: MacBook Pro mid 2014 13", macOS 10.13.1, BTT 2.332 ¯\_(ツ)_/¯

**Comment by fifafu** [comment]
@Worie what exactly?

**Comment by Worie** [comment]
We've talked about it [here](https://github.com/fifafu/BetterTouchTool/issues/2021) - when I posted it, meant the export part

**Comment by celina** [comment]
Exports aren't working for me either. I'd like to share a widget I've made but any preset exports have blank BTTTriggers. 

Are there any workarounds for this issue that don't requiring someone to replace all their settings with mine?

**Comment by fifafu** [comment]
In general I think exports are working fine. There may however be an issue when trying to override an existing export. Try to give it a new name if that's the case.

**Comment by celina** [comment]
@fifafu I am using a different name for every export.

This is the output of my Default preset (named Default-export-21.json)
```
{
  "BTTPresetName" : "Default",
  "BTTPresetUUID" : "C9D5B576-7D4B-4F24-BE48-C0FCC0BF5667",
  "BTTPresetContent" : [
    {
      "BTTAppBundleIdentifier" : "BT.G",
      "BTTAppName" : "Global",
      "BTTAppSpecificSettings" : {

      },
      "BTTTriggers" : [

      ]
    },
    {
      "BTTAppBundleIdentifier" : "com.apple.finder",
      "BTTAppName" : "Finder",
      "BTTAppSpecificSettings" : {
        "BTTDisableWindowSnapping" : 1,
        "BTTTouchBarMode" : 1
      },
      "BTTTriggers" : [

      ]
    },
    {
      "BTTAppBundleIdentifier" : "com.google.Chrome",
      "BTTAppName" : "Google Chrome",
      "BTTAppProcessMatchMode" : 2,
      "BTTAppProcessName" : "Google Chrome",
      "BTTAppSpecificSettings" : {
        "BTTTouchBarMode" : 2
      },
      "BTTTriggers" : [

      ]
    },
    {
      "BTTAppBundleIdentifier" : "com.hegenberg.BetterTouchTool",
      "BTTAppName" : "BetterTouchTool",
      "BTTAppProcessMatchMode" : 2,
      "BTTAppProcessName" : "BetterTouchTool",
      "BTTAppSpecificSettings" : {
        "BTTTouchBarMode" : 2
      },
      "BTTTriggers" : [

      ]
    },
  ],
  "BTTPresetSnapAreas" : [

  ]
}
```

Does the information in this export look correct? 
This preset contains 4 buttons and 1 widget. When I import it there are no buttons.

**Comment by celina** [comment]
This appears to be an issue with version 2.340.
I reverted to BetterTouchTool version 2.332 and the export functionality works as expected- the exported .json file contains my buttons and can be imported.

**Comment by fifafu** [comment]
Mhh I don't think 2.340 has changed anything with the preset stuff :-/  Maybe it was just restarting BTT that solved the issue?

It seems to work fine here with >= 2.340 but I will try it on another Mac. Which macOS version are you on?

**Comment by celina** [comment]
I apologize- I had imported a new Default and that new Default can be exported without issues.

I am on macOS 10.13.3.

The original Default preset, the one that cannot be unchecked and has Master next to it, exports the .json file I posted above that does not contain the buttons that are saved to it. This looks to be the case in both versions 2.332 and 2.340.

Is there a way the buttons in Default/Master can be moved to a different (exportable) preset?

**Comment by fifafu** [comment]
I have just fixed an issue with preset exports in 2.400 alpha - I think this might also solve the issue discussed here.

**Comment by tablatronix** [comment]
copying folder did not work for me, when I opened btt it showed a new preset, but when I activate it , it doens't show any settings. Any ideas?

**Comment by fifafu** [comment]
Copying and replacing the folder (while BTT is quit) definitely works. It is where BTT stores all the gesture and preset settings. Maybe you didn't quit BTT before doing it?

**Comment by tablatronix** [comment]
I didn't quit the first time.
But I tried again while not running, I also tried wiping the folder out before copying, same result

**Comment by fifafu** [comment]
If you are sure you copied it correctly it means the folder you copied already contains the empty preset. This is the only location where BTT stores preset data.

Or maybe you have the wrong tab selected in BTT?

**Comment by tablatronix** [comment]
looks like some settings are working ( snaopping ) but preset is not, just shows the purple circles.

**Comment by tablatronix** [comment]
Yup wrong tab....
