### ISSUE TITLE
Insert current time as keyboard shortcut

### ISSUE THREAD

**Issue by fabrik42** [fifafu/BetterTouchTool#1963]
First of all, thank you for this great tool! I think I barely use 1% of its capabilities, but I couldn't live without these tweaks. :)

#### Description of feature request/question:

I would like to add a custom key sequence / shortcut to insert the current date at my current cursor position. 

I was thinking about something like a double backslash leader key: 
If I press the combination `\\d`, insert the current date, if I press `\\t`, insert current time.

Is this possible with BetterTouchTool? I would try to create a small shell script and try to insert the output of this script at the current cursor, but I am not sure how. It seems like the built-in functions of BTT don't support that.

Best,
Christian

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Keyboard

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

you can do this using the predefined action "Insert Type / Paste Custom Text".
See this screenshot:

![image](https://user-images.githubusercontent.com/8820811/34651039-e5a8fc54-f3ca-11e7-85b8-34d481030244.png)

**Comment by fabrik42** [comment]
Thank you! This is a great start! Would it be possible to use the output of a custom terminal script at this point?

**Comment by fifafu** [comment]
You could use the execute terminal command, combine it with the pbcopy terminal command and then attach an additional action that does cmd+v.

```date|pbcopy```

**Comment by fabrik42** [comment]
Ah, good idea! I will give it a try. :) Thanks!
