### ISSUE TITLE
Expired trial removal

### ISSUE THREAD

**Issue by SiemenGijbels** [fifafu/BetterTouchTool#1964]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi, my girlfriend downloaded the BetterTouchTool trial in order to deal with High Sierra's horrible media key decisions. Now her trial has expired and there was no way to remove the keybinds. I tried deleting the program, the ~/Library/Preferences etc, but her whole function key row doesn't work anymore now. I tried restarting her Mac, also didn't work. BetterTouchTool was also removed from Login Items. Any suggestions?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MacBook Pro 15 inch Mid 2014
macOS version: 10.13
BetterTouchTool version: None anymore lol

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If you quit BTT it doesn't influence the system or the function row anymore. (The BTT touchbar things are just an overlay and as soon as BTT is quit, it doesn't so anything at all)

To get rid of the app just delete it from the place where you put it after downloading it. (Quitting it however is enough)

Maybe you modified the Touchbar settings in system preferences -> keyboard.


Best
Andreas

**Comment by SiemenGijbels** [comment]
Indeed, I still had the "Use F1, F2, etc. keys as standard function keys" option on. Thank you!
