### ISSUE TITLE
BTT crashes often with new monitor

### ISSUE THREAD

**Issue by NickHibma** [fifafu/BetterTouchTool#1965]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

When I hook up my laptop to a second screen, the new main screen, BetterTouchTool often crashes. This crash has been sent to Apple. I don't know if you get those as well.

#### Device information:

Type of Mac: MacBook Air (13-inch, Early 2014), 1.7GHz Intel Core i7, 8GB 1600MHz DDR3, SSD, Intel 5000 Graphics Cars
macOS version: 10.13.2
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1609727/BetterTouchToolDebug.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Tracking this here: #2020 (it's all the same crash, but it's a bug in the current macOS version :-()
