### ISSUE TITLE
Request: Mouse Click Down / Up actions

### ISSUE THREAD

**Issue by tpj2018** [fifafu/BetterTouchTool#1966]
Request: Mouse Click Down / Up actions

Are these in the pipeline soon?

Thanks!

**Comment by fifafu** [comment]
Hey,

sorry for not replying earlier, I had a very busy month at work (was my last month before going self employed :-))

I think what you ask for is already possible, although a bit hidde.
See this screenshot:
![image](https://user-images.githubusercontent.com/8820811/35755895-66ccafd0-0869-11e8-9fe3-b7a2ca0cc36a.png)
