### ISSUE TITLE
Cannot type "z"

### ISSUE THREAD

**Issue by hkim1596** [fifafu/BetterTouchTool#1967]
Since last month, I cannot type "z" anymore. I guess after the latest Alpha update. When I quit BTT, it works well. This is not an issue related to one mac, because all of my macs have the same problem. I have installed Karabiner as well on my macs. Am I the only person with this issue?

**Comment by fifafu** [comment]
You have probably configured a shortcut for z or for fn + z in the keyboard tab in BetterTouchTool. Remove that to fix your issue.

**Comment by hkim1596** [comment]
Thank you so much for your prompt answer. As I have set up too many actions, I wasn’t able to reexamine all those assigned shortcuts. You fixed it without even seeing my presets! Thanks a lot!
Best regards,
Heejin


On January 8, 2018 at 3:45:38 PM, Andreas Hegenberg (notifications@github.com) wrote:

You have probably configured a shortcut for z or for fn + z in the keyboard tab in BetterTouchTool. Remove that to fix your issue.

**Comment by fifafu** [comment]
Perfect! :-)
