### ISSUE TITLE
Touch Bar spacing optimisation

### ISSUE THREAD

**Issue by aaronweewee** [fifafu/BetterTouchTool#197]
A small feature request, customise or remove the unused space around
the exit BTT button. The touch bar has limited space and maximising the usable space would be ideal here. 

I've attached an Screen shot of my touch bar highlighting areas where it is unusable

<img width="1085" alt="touch bar shot 2017-01-03 at 5 28 14 pm" src="https://cloud.githubusercontent.com/assets/24728980/21603819/e03c01de-d1da-11e6-87e8-0c910dd54059.png">

**Comment by fifafu** [comment]
Good point!
For now you could also hide the BTT button in the general Touch Bar settings and replace it with your own (just assign the "Toggle BetterTouchTool Touch Bar" predefined action)

**Comment by fifafu** [comment]
1.80 now allows you to configure the space after esc and after the btt icon in the general settings!
