### ISSUE TITLE
Drawings recognize that the success rate is much lower than the macgestur.

### ISSUE THREAD

**Issue by dficonfont** [fifafu/BetterTouchTool#1970]
It is recommended to reference Macgesture's recognition logic or to increase the recognition success rate.

https://github.com/MacGesture/MacGesture

Drawings的识别成功率比Macgesture低太多。
建议参考Macgesture的识别逻辑，或者提高一下识别成功率。

**Comment by fifafu** [comment]
BTT Drawings currently can not handle straight lines. This will however be added soon.
Currently you need to add at least one curve or corner.
