### ISSUE TITLE
BTT Remote Dark Gray shape icons

### ISSUE THREAD

**Issue by sielo** [fifafu/BetterTouchTool#1972]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
**A possible BUG:**
I've just started using BetterTouchTool and BTT Remote. I don't have MacBook Pro with Touch Bar so I'm using my iPhone 6 instead of TouchBar.
I've configured several Triggers with my own icons (like: Chrome, TextEdit, TeamViewer). I can see my icons inside BetterTouchTool. But on my iPhone in BTT Remote there are only dark gray shapes of my icons (Google Chrome is round dark gray shape, TeamViewer is rectangle dark gray shape).
Am I doing something wrong ?

**A kind request:**
Is there any possibility to arrange actions as Icons like on iPhone's Home Screen (with small title below) ? It would be more convenient than a list (in some cases).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
I'm using BTT Remote on iPhone 6. But I've tried also iPhone X and the bug persists.

#### Device information:

Type of Mac: iMac Late 2009
macOS version: MacOS High Sierra 10.13.2
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting, this will be fixed with the next update of BTT Remote
