### ISSUE TITLE
BTT is "untouchable" while visible on t.bar when sierra starts.

### ISSUE THREAD

**Issue by R3W1ND** [fifafu/BetterTouchTool#1974]
I am on the 13" 2016Oct w touchbar macBook Pro. 
When I start my ultrabook I can see BTT on the touchbar
but no matter how hard I try i cannot select it .
I need to restart it from the menu bar, to become 
touchable again.

**Comment by R3W1ND** [comment]
![screen shot 2018-01-10 at 13 02 39](https://user-images.githubusercontent.com/35294935/34769547-c469c620-f606-11e7-87e6-f54ed9b90169.png)
![screen shot 2018-01-10 at 13 03 49](https://user-images.githubusercontent.com/35294935/34769549-c4f88e28-f606-11e7-9d28-1eb4121854fe.png)
![screen shot 2018-01-10 at 13 03 34](https://user-images.githubusercontent.com/35294935/34769550-c51b1a06-f606-11e7-8def-5a41642cf21b.png)

**Comment by fifafu** [comment]
Does this still happen with the latest version?
