### ISSUE TITLE
"Move Mouse To X Corner" Not Functioning on Drag

### ISSUE THREAD

**Issue by thisisted** [fifafu/BetterTouchTool#1975]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
My setup: From the "Other" category, I have "Move Mouse To Top Right Corner" to trigger Show Desktop. This works when I hover my cursor there, however when I am dragging a file and move the cursor to the corner, BTT does not activate the command.

Ultimately my goal is to build on Apple's current Hot Corners Exposé implementation by integrating a 0.75 second delay in BTT's approach, so dragging and holding a file to the corner would activate Show Desktop, and it would filter out any time my cursor briefly touches the corner (when web browsing for example). 

#### Device information:

Type of Mac: Mid-2015 MacBook
macOS version: 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Unrelated but worthy of note: There's a slight inconsistency with finding this Github issue site from the BTT app. It's available from the menubar menu, but not in the BTT app itself. I searched through the former for a little while as I assumed it'd be there. All I found from the app itself is a button to email you on the About screen. To better gather input from users/customers in context, I recommend linking to this area from the About screen as well. 
Lastly: thank you for making such a badass app. I've been using it since 2012 :)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
thanks for reporting, I have just fixed it and it will work with the next update (available sometime next week)

**Comment by thisisted** [comment]
Thank you for addressing it! I should note that I've received the newest 2.340 update - when I navigate to the Other tab in BTT and set the trigger to Move Mouse To Top Right Corner, the new dialogue of delay and Trigger while dragging appears, but after pressing Save, the trigger is not recorded/set in the list. Excited to try it out when it's all working!
