### ISSUE TITLE
"BTTAppSpecificSettings" are not read when importing preset.

### ISSUE THREAD

**Issue by sielo** [fifafu/BetterTouchTool#1977]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When You import preset from file BTT doesn't read anything from "BTTAppSpecificSettings".
That means that "App specific" settings are in "default" mode and one has to toggle them again.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You are right, thanks a lot for reporting.
Will be fixed in the next version (alpha will be there in a few hours)
