### ISSUE TITLE
BTT constantly uses CPU when idle and slowly drains battery

### ISSUE THREAD

**Issue by alexchandel** [fifafu/BetterTouchTool#198]
BTT consistently uses an average of 1.5% CPU, even when it's completely idle, and no keyboard or mouse events are happening, and no windows are being switched between or moving. 1.5% may not sound like much, but it adds up to significant energy usage over time, and can become a problem for lengthy car rides and international flights.

If no keystrokes or mouse movements are occurring, BTT should use 0 CPU.

**What kind of Mac are you using?** MacBook Pro (Retina, 13-inch, Late 2012)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?** I have 4 keyboard shortcuts defined, one trackpad gesture, and window snapping.

**Which versions of macOS and BetterTouchTool are you running?** 10.12.2, 1.963

Additionally, I note that even if I delete the trackpad gesture (so that BTT isn't tracking any mouse movements) and move the mouse around, BTT CPU usage spikes up another 1%.

**Comment by fifafu** [comment]
That's weird, in general BTT should not use significant amounts of CPU in your described use case (no input events, no window switching). There are only a few timers that run in the background (those are necessary to check various stuff), however they run only like every 30 seconds or so (and  they use the systems functionality to decide when they should run exactly to decrease energy usage).

I have just observed activity monitor for a while, and BTT was on 0 CPU for most of the time.

Are there any special triggers you may have configured in BTT like Bluetooth LE?

**Comment by gwagen03579** [comment]
I can confirm that BTT also appears to have a shockingly large energy impact on my own system. It is currently the highest energy impact of all apps I am running (Safari, messages, pdf expert). Perhaps it has something to do with the new widgets on the touch bar?

**Comment by fifafu** [comment]
What's your average Energy Impact after using BTT for a while? (While the BTT Preferences are closed)

![image](https://cloud.githubusercontent.com/assets/8820811/21815383/b196ab22-d75c-11e6-8542-b099e6a1cb82.png)

**Comment by alexchandel** [comment]
@fifafu

I have window-snapping enabled, and 4 global keyboard shortcuts for window snapping, but that's it.

What confuses me even more is that moving/shaking the mouse around bumps it another 1+%, even though I have no mouse events active, and I'm not dragging any windows or snapping them. It shouldn't use any CPU when I'm just moving my mouse.

The average energy impact is 1.7, making it # 3 on the list. (I run a lean system, and usually uninstall powerhungry apps in favor of better-programmed ones)

**Comment by alexchandel** [comment]
Would it help if I disabled the "Animate preview window" or "Rounded corners" options? Are those power-hungry?

Should I check "Disable the Snap Area feature"? Surely that requires 0 CPU, since you can just interrogate window positions later?

**Comment by fifafu** [comment]
everything below 3 is normal, however I'm continuously adding optimizations where possible.

I think your mouse moving issue may be something that can be improved for people that don't have any gestures configured in BTT (as BTT is still mostly a gesture tool, it always monitors the trackpads, but that's not really necessary when no gestures are configured).

Animate preview window uses some CPU, rounded corners do not. The Snap Area feature only uses CPU if you actually have Snap Areas configured.

**Comment by alexchandel** [comment]
@fifafu 

My value may be a lower bound, since I've only been using this computer for about 1 of the last 8 hours, and it was awake running idly before that (with no mouse movements).

That would be very nice if it were improved, since I feel the compulsion to turn off BTT before traveling now after my laptop died too early last time.

**Comment by fifafu** [comment]
Don't get your hopes up too high though, all optimizations that are feasible are pretty minimal.

**Comment by alexchandel** [comment]
@fifafu 

That makes no sense though. I move my mouse a lot, and I'd consider a 1-1.5% reduction in CPU usage huge for an app that should be using 0.

**Comment by fifafu** [comment]
@alexchandel would be great if you'd check how v1.986 behaves on your system.

**Comment by fantaaaaaa** [comment]
<img width="615" alt="screenshot 2017-02-01 23 25 49" src="https://cloud.githubusercontent.com/assets/24585031/22528971/d305aefe-e8d5-11e6-8e60-adcbfa4ac958.png">

mine is over 6%. what can i do to check whats wrong? i have some scripts running as apple script widgets but they run every 5 minutes only and use around 50% for about 2 seconds.

**Comment by fifafu** [comment]
@fantaaaaaa have you been doing a lot of setup in the BTT ui? (The UI isn't really optimized for CPU usage because it's not used very often)

But even if it's only every 5 minutes, 50% cpu for 2 seconds is quite something. What are your scripts doing?

**Comment by fantaaaaaa** [comment]
I am curling some URLs to retrieve results (about 6 URLs for 6 buttons). 

What exactly do you mean by "lot of setup in the gui"? I have been tweaking the settings a lot in the last 2 days to customize my touchbar.
