### ISSUE TITLE
Run applescript only once 

### ISSUE THREAD

**Issue by gjwinkel** [fifafu/BetterTouchTool#1980]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I am trying to initialise a toggle button (mute/unmute) by running a script once at the start. To then run it again when pressing the button. I have set the slider ('execute this script every x seconds') to zero. But the script keeps running. Anything I am doing wrong?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15"
macOS version: High Sierra
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
So happy that I can customise my touchbar!

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, you were right! I fixed this in v2.231 alpha (get via check for alpha version updates)
