### ISSUE TITLE
BTT Remote: Add easy access for menus

### ISSUE THREAD

**Issue by kuglee** [fifafu/BetterTouchTool#1983]
It'd be great if shortcuts to menus and submenus could be added to Custom Actions or to be able to favorite them for easy access. It's tedious to browse them every time using the app.

**Comment by fifafu** [comment]
You can use the predefined action "Trigger Menubar Menu Item" to set this up

![image](https://user-images.githubusercontent.com/8820811/34907683-985c9214-f882-11e7-9aa1-8b50bf206743.png)
