### ISSUE TITLE
"no padding if you maximize window" still leaves gap on the bottom when dock is set to auto-hide

### ISSUE THREAD

**Issue by jerkstore369** [fifafu/BetterTouchTool#1986]
macos 10.12.6
BTT 2.318

I don't understand. I checked off "no padding if you maximize window" but there's still a gap at the bottom of the screen when I maximize. I even checked "leave gap above dock" and set it to 0. Doesn't work. I have BTT setup so that when I use certain keys and left click on the green traffic button the window will fill the bottom half of the screen. When I do this the gap at the bottom is filled. Why would it fill then but not on maximize? Weird.

**Comment by fifafu** [comment]
Hey,

unfortunately this is a system limitation on macOS <= 10.12. You'll need to update to 10.13 if you want BTT to be able to fully maximize while the Dock is hidden.

Best,
Andreas

**Comment by jerkstore369** [comment]
ok, thanks.
