### ISSUE TITLE
New Action: Change Sound Device

### ISSUE THREAD

**Issue by knoajp** [fifafu/BetterTouchTool#1987]
I want to change the Mac's output sound device by BTT.

I have three speakers on my Mac (A, B and Internal Speakers).
Then, the most ideal functionality for me is: "Toggle A and B".
"Change to next output sound device (loop)" is also helps me.

Thank you.

**Comment by wrobelda** [comment]
Install SwitchAudioSource (brew install switchaudio-osx), Add new button with "Execute Terminal Command" action and put this in the box:

"/usr/local/bin/SwitchAudioSource -n"

This will toggle sound output device.

**Comment by knoajp** [comment]
Good solution !!
Thank you very much :-)
