### ISSUE TITLE
CTRL + Arrow works but only on key up, not on key down

### ISSUE THREAD

**Issue by nathanielcook** [fifafu/BetterTouchTool#199]
#### Description of your bug/question/feature request...:
I use BetterTouchTool to remap the control key for CTRL+LEFT and CTRL+RIGHT to ALT+LEFT and ALT+RIGHT, respectively. This is done for synergy between Windows (Parallels) and macOS. (I used to map Windows to match macOS, but was annoyed that a single tap to ALT sets focus to the menu bar in Windows applications that have a menu bar.) Anyway, the remap works, but only on key up, not on key down. I need to be able to hold CTRL+LEFT down and repeat the key. (I used to use Karabiner for this, but alas, Karabiner doesn't work for Sierra.) When I turn on "Trigger on Key Down" the keyboard shortcut no longer works. Checking "Repeat Action" doesn't help either. So for now I am stuck to Key-Up only.

**What kind of Mac are you using?**
MacBook Pro (Retina, 15-inch, Mid 2014)
macOS Sierra 10.12.2

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
The built-in Macbook Pro keyboard.

**Which versions of macOS and BetterTouchTool are you running?**
1.963 (552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Nothing useful that I can think of

**Comment by TeffenEllis** [comment]
Is this on the bugfix roadmap? Command + arrow still is able to repeat.

Cheers

**Comment by nathanielcook** [comment]
FYI to all those tracking this issue, Karabiner Elements for Sierra now supports application specific shortcut behavior. I am using Karabiner Elements now as a workaround for this outstanding issue with BTT. The following Karabiner Elements rule maps CMD+ARROW and CMD+SHIFT+ARROW for all applications except Parallels Desktop windows. So far it is working fine for me (as of Karabiner Elements v0.91.13). I have not noticed any issues with running both Karabiner Elements and BTT simultaneously. Hope it is useful to someone.
```
"rules": [
    {
        "description": "Change ctrl+left, ctrl+right to alt+left, alt+right",
        "manipulators": [
            {
                "conditions": [
                    {
                        "bundle_identifiers": [
                            "^com\\.parallels\\.desktop$",
                            "^com\\.parallels\\.vm$",
                            "^com\\.parallels\\.desktop\\.console$",
                            "^com\\.parallels\\.winapp\\."
                        ],
                        "type": "frontmost_application_unless"
                    }
                ],
                "from": {
                    "key_code": "left_arrow",
                    "modifiers": {
                        "mandatory": [
                            "left_control"
                        ],
                        "optional": [
                            "left_shift"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "left_arrow",
                        "modifiers": [
                            "left_option"
                        ]
                    }
                ],
                "type": "basic"
            },
            {
                "conditions": [
                    {
                        "bundle_identifiers": [
                            "^com\\.parallels\\.desktop$",
                            "^com\\.parallels\\.vm$",
                            "^com\\.parallels\\.desktop\\.console$",
                            "^com\\.parallels\\.winapp\\."
                        ],
                        "type": "frontmost_application_unless"
                    }
                ],
                "from": {
                    "key_code": "right_arrow",
                    "modifiers": {
                        "mandatory": [
                            "left_control"
                        ],
                        "optional": [
                            "left_shift"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "right_arrow",
                        "modifiers": [
                            "left_option"
                        ]
                    }
                ],
                "type": "basic"
            }
        ]
    }
]
```

**Comment by fifafu** [comment]
I believe this works in recent versions of BTT.

Sorry for not replying to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions, please create a new issue - I'm now much more responsive than a few months ago.
