### ISSUE TITLE
Issues After Yosemite Upgrade

### ISSUE THREAD

**Issue by krawfo** [fifafu/BetterTouchTool#1990]
#### Description of bug/feature request/question:
BTT worked fine before 0SX upgrade.
Programmed Button 4 = 3F swipe right (page fwd)
      "                   "      3   3F swipe left (page back)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Logitech M525 Mouse

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 
iMac
Yosemite 10.10.5
BTT 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by krawfo** [comment]
Anyone ??

**Comment by fifafu** [comment]
Unfortunately I currently don't have a machine that can run yosemite anymore.
Are the buttons recognized correctly if you assign some other action?

**Comment by krawfo** [comment]
I gave up on Yosemite and upgraded to Sierra.  Everything works better now except pressing on the scroll wheel.  The assigned action say "Closes Window Below Cursor".  In the past, only the current tab in Chrome would close.  Even if I have 3 tabs open and click on the currently active tab it closes chrome entirely.
Thanks.
    On Friday, February 2, 2018, 6:22:41 AM EST, Andreas Hegenberg <notifications@github.com> wrote:  
 
 
Unfortunately I currently don't have a machine that can run yosemite anymore.
Are the buttons recognized correctly if you assign some other action?

**Comment by fifafu** [comment]
Mh if that's the case it was a change in Chrome. If you want to close single tabs assign cmd+w instead
