### ISSUE TITLE
Hackintosh issue

### ISSUE THREAD

**Issue by donkeishlong** [fifafu/BetterTouchTool#1991]
Type of Mac: Hackintosh Desktop
macOS version: High Sierra
BetterTouchTool version: 2.320

I don't know if you even want to open the box of supporting Hackintoshes but I just recently built one and it works flawlessly except for one issue. When BTT is running, the system will hang usually when asleep for a prolonged period of time and requires a hard reboot to get back into the system. This only happens when I have BTT running. If I quit BTT and let the system sleep, there are no issues. I also checked the console and usually in the middle of the night I see this message and not much is noted in the console after that until I reboot the system:

(com.apple.xpc.launchd.oneshot.0x1000000c.BetterTouchTool[930]) Service exited due to signal: Terminated: 15 sent by BTTRelaunch[932]

(com.hegenberg.BTTRelaunch.1680[932]) Service exited due to signal: Terminated: 15 sent by BetterTouchTool[939]

assertion failed: 17C88: libxpc.dylib + 72637 [F7E5F1BC-614B-39CB-B6CE-92A9C7B7EC0B]: 0x89

If you're interested in helping and want more specific information please let me know and I'll try to help.

**Comment by fifafu** [comment]
Unfortunately I really don't know anything about hackintoshs and can't really give support here.
The message you see just means that your mac has woken up from sleep and BTT restarted itself (which it always does when the computer wakes from sleep).

So maybe some device is waking up your Hackintosh?
