### ISSUE TITLE
Feature Request: Percist touch bar in configured applications and remove close button

### ISSUE THREAD

**Issue by presidenten** [fifafu/BetterTouchTool#1992]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description feature request:

Can we please get a toggle option in basic settings to persist the configured touch bar actions to always have the configured touch bar actions be visible and also get rid och the "close" button on the left that is hogging space. 

I mean, we can toggle the BetterTouchTool by tapping the BetterTouchTool icon. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: Macbook pro
macOS version: High Sierra
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The close button is automatically added by the system and can only be removed if you go to the general touchbar settings in BTT and disable the macOS control strip. This can not be changed given the current apis.

The actions always stay visible unless you explicitly toggle them off.

**Comment by presidenten** [comment]
Ok! Thanks for the quick feedback!
