### ISSUE TITLE
Rotate 90 or 270 degrees

### ISSUE THREAD

**Issue by 5illip** [fifafu/BetterTouchTool#1993]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Some desk setups work better with the Magic Trackpad in "portrait" mode. Allowing the inputs to adjust to a trackpad that is turned 90 or 270 degrees would allow this.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad

#### Device information:

Type of Mac: any
macOS version: ant
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately the available apis don't allow this. Thus I can not add this feature to BTT.
