### ISSUE TITLE
[Feature Request] Action: Show hidden dock

### ISSUE THREAD

**Issue by jpalmieri** [fifafu/BetterTouchTool#1995]
#### Description of feature request/question:

If there is an API for it in OSX, an action to show the hidden dock. For example, when the dock preferences are set to "Automatically show and hide the dock", it would be helpful to have a keyboard shortcut to temporarily show the dock (e.g., to check badges on app icons).

If this API is unavailable, a different approach might be to have "toggle the 'Automatically show and hide the dock' preference" as an action.

#### Device information:

Type of Mac: Macbook Pro (Retina mid-2012)
macOS version: 10.13.2
BetterTouchTool version: 2.318

**Comment by Worie** [comment]
Can't you just trigger default shortcut (CMD+ALT+D) for it?

**Comment by jpalmieri** [comment]
That was exactly what I was looking for. Thanks, @Worie. 👍
