### ISSUE TITLE
persistent Operation Couldn't be completed (NSSQLiteErrorDomain Error 8) error

### ISSUE THREAD

**Issue by drewskoots** [fifafu/BetterTouchTool#1996]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have recently started receiving "NSSQLiteErrorDomain Error 8" warnings from BetterTouchTool when waking from sleep but also seemingly randomly while using my laptop. After clicking OK, another dialog box opens asking if I would like to quit without saving changes, even though I haven't changed anything

. The functionality of BetterTouchTool is not affected, but the Dialog Windows are quite annoying.

#### Device information:

Type of Mac: Mid 2012 Macbook Pro
macOS version: 10.13.02
BetterTouchTool version: 2.318(702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![screen shot 4](https://user-images.githubusercontent.com/3580682/35117485-c27de38a-fc5c-11e7-9a8b-80aa1e16379c.png)
![screen shot 7](https://user-images.githubusercontent.com/3580682/35117517-d65279ca-fc5c-11e7-8649-432c06b18d52.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is probably a file permission problem. Maybe something somehow changed the file permissions of the data files in ~/Library/Application Support/BetterTouchTool which causes BTT to be unable to write them.

You could either delete the complete folder, then BTT will recreate the files with the correct permissions, or you can manually check and repair the file permissions.
Unfortunately deleting the folder will also delete your BetterTouchTool settings, but you could export your current setup first.

Best 
Andreas

**Comment by drewskoots** [comment]
That seems to have done the trick at for now. Thanks!
