### ISSUE TITLE
Play/Pause and Next Shortcuts No Longer Work with iTunes on High Sierra

### ISSUE THREAD

**Issue by Haravikk** [fifafu/BetterTouchTool#1997]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

After finally updating to High Sierra, things are mostly going smoothly. However, I'm having one issue with BTT, which is that the Play/Pause and Next options, which I've bound to F1 and F6 on my keyboard respectively, are no longer working.

Play/pause at least seem to work just fine in other programs, for example Quicktime, or when viewing video in Safari, so far it's only iTunes that is being affected that I can see. All my other shorts such as mute (F2), volume down (F3) and volume up (F4) and Spotlight (F5) are working just fine.

I wouldn't be surprised if the fault is with iTunes; Apple has really been dropping the ball on it lately, but it's strange as it's the same iTunes version I had before updating. In my case I went from El Capitan to High Sierra (I'm not quick to adopt new macOS versions).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Microsoft Ergo Sculpt Keyboard (the keyboard has a switch for shifting between media keys and function keys, so I'm using the latter with BTT to replace the missing media functions.

#### Device information:

Type of Mac: Mac Mini 6,2
macOS version: 10.13.2 (with supplemental update)
BetterTouchTool version: 2.318

#### Additional Information
iTunes 12.7.2.20

**Comment by Haravikk** [comment]
Huh, turns out it may have had something to do with Notification Centre; in it I just discovered there's a new widget "Now Playing", which is functionally identical to the iTunes widget, I tried swapping them and the shortcuts now work just fine again.

So for anyone having the same issue; open Notification Centre, edit, and remove the iTunes widget, and replace it with Now Playing, and this ought to resolve it, at least until the next iTunes disaster.

Is the iTunes-specific widget now obsolete?

**Comment by fifafu** [comment]
Unfortunately I think this is how High Sierra handles this now.
Your workaround seems to be a good solution - in case the send shortcut to specific app action doesn't work consistently you can also use this little apple script:

```
tell application "iTunes"

	playpause

end tell
```
