### ISSUE TITLE
Crash after connecting to bluetooth headset

### ISSUE THREAD

**Issue by wangcheng678** [fifafu/BetterTouchTool#1998]
#### Description of bug/feature request/question:

BTT occasionally crashes when I connect a bluetooth headset to the computer. 

But it doesn't crash every time I do so, more like once or twice per day. (I connect and disconnect the headset frequently everyday).

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
macOS version: 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I cannot reproduce the bug. I'll try to send the crash report to you via email. Please notice mail from me (Cheng Wang).

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by wangcheng678** [comment]
This problem still exist in version 2.332.

**Comment by fifafu** [comment]
This is being tracked here: https://github.com/fifafu/BetterTouchTool/issues/2020
