### ISSUE TITLE
Clicking causes scrolling on my magic mouse

### ISSUE THREAD

**Issue by rahilsondhi** [fifafu/BetterTouchTool#20]
#### Description of your bug/question/feature request...:

When I use my magic mouse and I click, it causes a little bit of a scroll. It's very annoying and causes me to miss my click target. Any idea how to solve this?

**What kind of Mac are you using?**

MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Magic Mouse

**Which version of macOS are you running?**

macOS Sierra 10.12.1

**Comment by fifafu** [comment]
Hey,

does this also happen when BTT is closed?

Best,
Andreas

**Comment by rahilsondhi** [comment]
Nope, it doesn't. When I quit BTT, the clicking is reliable.

**Comment by rahilsondhi** [comment]
Never mind. After some more testing, this happens without BTT too. I haven't found a solution yet.
