### ISSUE TITLE
applescript doesn't work on TouchBar, but works on Trackpad

### ISSUE THREAD

**Issue by vytautasgimbutas** [fifafu/BetterTouchTool#200]
#### Description of your bug/question/feature request...:
I'm trying to add a button to run this applescript on TouchBar:
```
tell application "iTerm"
	create window with default profile
	tell application "System Events" to tell process "iTerm2" to keystroke "ssh server"
	tell application "System Events" to tell process "iTerm2" to keystroke return
end tell
```

but it just opens something a couple times and doesn't happen what I expect - run new terminal, enter text and click enter. *It works if I bind it to magic trackpad shortcut!*

**What kind of Mac are you using?**
tMBP 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
macos sierra, BTT 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by vytautasgimbutas** [comment]
Figured out a workaround:
1) applescript just
```
tell application "iTerm"
	create window with default profile
end tell
```
2) paste test "ssh server"
3) send "return" to iTerm

not a very nice workaround but works. :)

**Comment by fifafu** [comment]
That's weird, in general there shouldn't be a difference as BTT just executes the Apple Script.

I'll look into it!
