### ISSUE TITLE
bettertouchtool mac os and apple remote (appletv4)

### ISSUE THREAD

**Issue by schee435** [fifafu/BetterTouchTool#2000]
I run bettertouchtool on mac os en use the apple remote so i can control kodi and some more programs. I installed everything like i need and everything works perfect. But after a while the commands a not following. The remote still works but not the way i configured it. When ik restart Bettertouchtool everything works fin again. Can anybody tell me what is going on. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

affected only the apple remote 

#### Device information:

Type of Mac:mac mini
macOS version: high sierra 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether this still happens on the latest version of BTT (2.332) ?

I'm continuing this issue here, I think it's the same thing: https://github.com/fifafu/BetterTouchTool/issues/1606
