### ISSUE TITLE
What is the status of three-finger dragging?

### ISSUE THREAD

**Issue by jeffmann** [fifafu/BetterTouchTool#2001]
#### Description of bug/feature request/question:
Due to arthritis in my hands and shoulders, I need to use three-finger dragging. I'm not really able to use the trackpad without it. I also rely on BTT to assist in controlling the computer with less strain, and it's a big help!

So I was disappointed to read this from Andreas, in issue #1340:
> Sorry, unfortunately BTT is not really compatible with three finger dragging and probably never won't be. This is because with macOS 10.9 or 10.10 Apple changed the behavior of the three finger drag and now some fundamental trackpad parameters change as soon as three finger dragging is enabled. This makes it impossible for BTT to work correctly with three finger drag enabled :-(

Currently I don't seem to have any problems with it. Will it not be supported in the future? Is it only related to the force touch trackpad? I don't have one, but I was thinking of upgrading. Should I expect that it won't work? What are the problems, what doesn't work right? Are there work-arounds, some gestures that can't be used?

I also just found in BTT Preferences "three finger drag optimizations". I didn't have it turned on. When I turned it on, I didn't notice a difference. What is it for? I tried to look in the [user manual](https://docs.bettertouchtool.net/docs/trackpad.html), but for that page it just says "documentation not yet available".

**Comment by tpj2018** [comment]
i would advice you to install karabiner. Map your mouse buttons to your keyboard for your left hand. And move the mouse with 1 finger drag. Karabiner and BTT do not bite eachother.

**Comment by fifafu** [comment]
@proactivematter the thing you described is exactly the problem :)
The the finger drag optimizations should workaround this as good as possible.

Also I think there are still issues with some BTT gestures (e.g. The finger tap)

In general it's fine to use the three finger drag, but certain btt gestures may behave a little buggy.

**Comment by proactivematter** [comment]
Ah, I see! Yes, the only problem I have with activating three finger drag optimizations is that tip-taps cease to work, hence I have to leave it off.

**Comment by fifafu** [comment]
@proactivematter you are talking about tip taps with two fingers fixed, correct? You are right, they currently don't work in combination with this option, however this may change in one of the next updates. 

For now I'm closing here as I think the state of the three finger drag has been discussed.

**Comment by jeffmann** [comment]
Sorry I didn't reply sooner. I've been testing using "three finger drag optimizations", and trying to understand exactly what effect it has.

I started noticing some strange things with three-finger drag-selecting text. The text would sometimes be selected by snapping to word boundaries. I hadn't noticed that ever happening in the past, before turning on the optimizations. I found out that it's expected on a Mac to select text by words, if you double-click then drag. Somehow I think having the optimizations on can cause (or allow?) a double-three-finger-tap to be registered at the beginning of a three-finger drag-to-select. I'm not 100% sure though, because it doesn't happen very often. Is it possible?

A summary of three-finger-dragging, please tell me if this is correct:

- There are no plans to drop support for three-finger-dragging in BTT.
- There are no additional problems with a force-touch trackpad and three-finger-dragging, compared to an older trackpad.
- If "three finger drag optimizations" are *disabled*, then when doing a three-finger tap-and-hold, or tap-and-drag, the tap-down is not registered until there is a small amount of cursor movement. This can cause several problems, such as the "back button history menu" in Safari not dropping down with tap-and-hold unless you move your fingers slightly. I think it's also the cause of the problem described by @proactivematter above as being "slower to detect" and not grabbing a window edge "quickly enough" - it's not so much a matter of slow/quick in terms of *time* but in terms of motion. If you're trying to select something very precisely like a window edge, the cursor may have already moved off it before the tap is registered. Is that correct?
- If "three finger drag optimizations" are *enabled*, then the above problem is solved, but other problems then occur:
  - two-finger-fixed tip-taps don't work. Are there any other gestures that don't work?
  - there are "negative effects" on window snapping and snap areas - what does that mean?
  - any other problems?
- According to issue #1340, there's a problem when assigning three-finger-click to mouse-click, which makes three-finger-drag not work correctly. I don't really understand the description of the problem and I can't reproduce it. 
- "In general it's fine to use the three finger drag, but certain btt gestures may behave a little buggy." Could you be more specific? Which gestures, and what does "buggy" mean? It would be really nice if someday there was an explanation in the manual, since it took me quite some time experimenting and searching the issues to figure this all out. Thanks.
