### ISSUE TITLE
2.331 crashes

### ISSUE THREAD

**Issue by mrfancyclancy** [fifafu/BetterTouchTool#2003]
#### Description of bug/feature request/question:

I just installed 2.331 (auto-update from within the app) and it worked at first but whenever the Prefs window is closed and the app is running in the background, it closes after a few seconds.

I can manually open the program and it again works briefly, but it keeps crashing. I don't see any notification or error message when it happens; instead, the icon just goes away from the menu bar and I only notice when my Touch Bar reverts to the default and my snap areas are inactive.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13.2
BetterTouchTool version:  2.331

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Workaround: I deleted 2.331 and manually installed 2.318. It seems fine again with 2.318.

crash log attached
[BetterTouchTool_2018-01-21-161013.txt](https://github.com/fifafu/BetterTouchTool/files/1649603/BetterTouchTool_2018-01-21-161013.txt)

**Comment by fifafu** [comment]
Thanks a lot for reporting and thanks a lot for the crashlog! This should now be fixed in v2.332 (it was related to Touch Bar widgets that return an empty value)

**Comment by mrfancyclancy** [comment]
Thanks for the quick response! 2.332 is working perfectly.
