### ISSUE TITLE
Add ability for BTT to show when a keyboard shortcut is overriding an application/OS shortcut

### ISSUE THREAD

**Issue by lostformars** [fifafu/BetterTouchTool#2004]
#### Description of bug/feature request/question:

When you set a keyboard shortcut in BTT for an application it overrides any shortcut that the application already had for the shortcut. Some applications have a lot of shortcuts and it is not easy to find unused shortcuts. One of the only ways to quickly see if an application has a shortcut defined is to try it. But, then you don't know what you might trigger. 

Thank you for considering this request,
Joe

**Comment by fifafu** [comment]
Unfortunately I think there is no way for BTT to check which shortcuts are used in a specific app. Thus I don't think I can add this feature. If I come across a way to do it, I'll add it. For now I'm closing here.
