### ISSUE TITLE
Crashes shortly after wake

### ISSUE THREAD

**Issue by AllPurposeBen** [fifafu/BetterTouchTool#2005]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Been having crashes for the last several weeks. Seem to happen within a few minutes of waking from sleep. Sometimes will immediately crash again when app relaunched, sometimes it then fine. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Doesn't seem tied to a specific action, will happen with no interaction to any input devices.

#### Device information:

Type of Mac: MacBookPro12,1
macOS version:  macOS 10.13.2 (17C205)
BetterTouchTool version: 2.332 (has been happening for the last 3 or 4 updates)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I have re-run the latest combo updater and tried clearing caches and clearing any BTT preferences I could find.

Attached cash report and debug info from latest crash
[BBT Crashlog and debug info.zip](https://github.com/fifafu/BetterTouchTool/files/1650559/BBT.Crashlog.and.debug.info.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by sagecedar** [comment]
I'm experiencing the same issue.  Once in a while, I would open my laptop after its sleep, and BBT wouldn't be working so had to relaunch it.

Type of Mac:  MacBookAir6,1
OS version:  10.13.2
BBT version:  2.318

**Comment by HFTobeason** [comment]
Same here.  Logs attached for this month's crashes.

BTT 2.332, MacBookPro (15-inch, Late 2016), 10.13.3 Beta (17D46a)

[Archive.zip](https://github.com/fifafu/BetterTouchTool/files/1653528/Archive.zip)

**Comment by fifafu** [comment]
@HFTobeason in your case it seems to crash when using the "Hide All Windows" action. Maybe there is a compatibility issue with the beta?

Also please check whether the crashes still continue with v2.332 as I have added some extra checks.

**Comment by HFTobeason** [comment]
FYI, in my case, the "Hide All Windows" function has never quite worked - it most often (but not always) leaves one application's windows visible.  Invoking it a second time will always close the last visible window.  Not sure what's going on...

**Comment by fifafu** [comment]
@AllPurposeBen your crash is the same as this one here: https://github.com/fifafu/BetterTouchTool/issues/1856 which is unfortunately a macOS bug that doesn't only affect BetterTouchTool. I have reported it to Apple and hope it will be fixed soon. It was introduced with macOS 10.13.2.

I'm closing here for now as I'm already tracking that crash with the other issue.
