### ISSUE TITLE
Crashes when connect the Thunderbold3(USB-C) display

### ISSUE THREAD

**Issue by yu-imai** [fifafu/BetterTouchTool#2007]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Same as the title.

#### Device information:

Type of Mac: MacBook Pro 13 2016 w/ touchbar
macOS version: 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether there are any BetterTouchTool crashlogs in the macOS Console App in "User Reports"?

**Comment by fifafu** [comment]
It's probably the same issue as #2020
