### ISSUE TITLE
Key Sequence in Finder

### ISSUE THREAD

**Issue by Bearsden** [fifafu/BetterTouchTool#201]
#### Description of your bug/question/feature request...:

I use `Key Sequence` for `Open Current Finder Selection with Specific App`. However, pressing a key in Finder moves a highlighted selection (a default feature?), making it impossible to use this feature. I want to use `Key Sequence` rather than `Shortcut` in this case.

Can you suggest a solution?

If no solution is available, I wish to suggest correcting it as a feature request.

**What kind of Mac are you using?**

MacBookPro (Retina, 13-inch, Late 2012)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Built-in keyboard in the MacBookPro

**Which versions of macOS and BetterTouchTool are you running?**

El Capitan 10.11.6
BetterTouchTool 1.963

**Comment by fifafu** [comment]
This is not possible as it would require me to block all keyboard input from reaching Finder which would cause all sorts of problems. The key sequence feature is unfortunately not suited for your use case.
