### ISSUE TITLE
BTT stop working

### ISSUE THREAD

**Issue by Teter86** [fifafu/BetterTouchTool#2010]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
My BTT stops working after a few minutes. I use Magic Mouse 2 and I need a zoom in Chrome and a middle button. I set it in gestures and act to stop working after a few minutes. I have not yet discovered the dependence on what it depends on. I do not use the Trackpad on the Macbook because I work on an external monitor. 
it works only after restarting btt
Can you help me? 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse 2

#### Device information:

Type of Mac: Macbook Pro 2015
macOS version:  Sierra 10.12.6 (16G1114)
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

DEBUG: https://www.dropbox.com/sh/s7sg9omkn2f23ga/AADEN5Q42MxYSoOgJL4piiXCa?dl=0

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird. Did you download BTT from my website? https://boastr.net? So far I only had reports of such issues with modified versions of BTT that were somehow broken.
