### ISSUE TITLE
BetterTouchTool Accessibility API Permissions

### ISSUE THREAD

**Issue by agordeev** [fifafu/BetterTouchTool#2011]
<img width="508" alt="screen shot 2018-01-23 at 11 53 18 am" src="https://user-images.githubusercontent.com/2883524/35267576-cfabfe64-0037-11e8-9c3a-ed9e63bdf545.png">

WHAT THE HELL is this and how to stop this window from showing up every minute?

I don't want to grant BTT any permissions, it's working fine without them

**Comment by fifafu** [comment]
Bettertouchtool needs these permissions to work correctly. You can grant them in system preferences -> Security and Privacy -> Accessibility.

**Comment by fifafu** [comment]
I just remembered there is an old  user defaults key you can use to disable this:
```defaults write com.hegenberg.BetterTouchTool BTTDisableAcccessibilityCheck YES```

However absolutely no support when doing that. I have spent days debugging this stuff....

**Comment by kentcdodds** [comment]
This is popping up even though I have enabled the accessibility permissions. Just started popping up out of nowhere 🤔

**Comment by kentcdodds** [comment]
<img width="844" alt="screen shot 2018-01-23 at 3 40 13 pm" src="https://user-images.githubusercontent.com/1500684/35304750-e86751d0-0053-11e8-94e9-46fc302b70a3.png">

**Comment by kentcdodds** [comment]
I rebooted and things seem to be fine now :+1:

**Comment by Nosskirneh** [comment]
Well, rebooting isn't a solution. No way am I going to close everything I'm currently doing just to prevent that annoying popup from appearing.

**Comment by fifafu** [comment]
Unchecking and re-checking the permissions should also get rid of the popup.

I'll be updating the popup with a better description for cases were macOS forgot that BTT is already enabled.

**Comment by Nosskirneh** [comment]
I see. Well, that didn't work for me. Had to reboot for it to take effect. It happens on every update of BTT.

**Comment by fifafu** [comment]
@Nosskirneh that's not normal. Do you maybe have multiple copies of BTT on your machine / in in the login items? Usually there is some reason why macOS forgets about the permission.

It can also happen when there are weird certificate issues on the Mac, however these are hard to debug...

**Comment by kentcdodds** [comment]
This actually just started popping up for me repeatedly again too. I had to restart BTT to get the accessibility preferences to take hold. It does appear to be a macOS bug rather than a BTT one.

**Comment by Nosskirneh** [comment]
I only have one BTT in `/Applications` and same for Users & Groups -> Login Items.

**Comment by liujiajingtop** [comment]
i have save problem. i already enable the permissions. but this dialog pop up every time

**Comment by petebocken** [comment]
I've been having the same issue the past couple weeks.  I noticed I had the app preference to launch app on startup and also in System Preferences Login Items.  Not sure if that contributes to the problem though.

Whenever I get the security message from BTT, I go into System Preferences and uncheck/check the security box, quit/reopen BTT twice then the message seems to go away.  I'll see if removing from System Preferences login items affects anything in the future.
