### ISSUE TITLE
Newest BTT update disables sound effects on OSX

### ISSUE THREAD

**Issue by Patrick8213** [fifafu/BetterTouchTool#2012]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I updated to the latest BTT and sound effects no longer work on OSX 10.12.6 Sierra. Removal and reinstall of BTT did not correct the issue. Sound in general does work, however volume is greatly reduced. I removed the audio device and system settings .plists as well, to no effect. I reverted back to BTT version 2304 (682) and all is back to normal.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Sound effects (output device) 

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.12.6 
BetterTouchTool version: 
Not sure of version # Which caused the issue, whichever would have been the latest regular update on 1/23/18. Reverted back to BTT version 2304 (682) corrected the problem.
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mhh honestly I don't think this is related to BTT / must have been a coincidence. I can't think of any way BTT would influence the audio, unlrss you have explicitly added some custom scripts.

**Comment by Patrick8213** [comment]
I use a 3 finger swipe up and down with BTT to control volume. I noticed that with the newest version that the "click" sound effect when adjusting the volume level didn't work. Thats when I noticed that, with volume all the way up, that there was no sound when I would receive notification popups. The audio itself ie. when playing a video would have to be much above the usual setting level to be able to hear. I have no custom scripts and reverting back to the earlier version of BTT corrected the problem.

**Comment by fifafu** [comment]
Sorry but this sound is definitely generated by the system, all BTT does is send the appropriate key command to the system. I'm pretty sure this was just a coincidence where the system sound generation "hung"  and the BTT downgrade didn't actually influence this.

Be sure the appropriate options are selected here:
![image](https://user-images.githubusercontent.com/8820811/35302948-a0110b14-0090-11e8-84b9-3e2be85f1d8f.png)
