### ISSUE TITLE
Touch Bar spacing broken with recent update (2.332)

### ISSUE THREAD

**Issue by CarterVE** [fifafu/BetterTouchTool#2013]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The most recent update has introduced a glitch in the widget spacing on the right side of the touch bar. I have many widgets with different amounts of negative spacing (internal and after widget) to reduce the overall space taken by buttons on the touch bar. With the most recent update, the spacing will initially appear correctly, but after clicking any button, collapses to a point where many (but not all) widgets on the right side simply vanish off the touch bar altogether. 

Please fix this or tell me what I am doing wrong, as it renders many of my widgets completely unusable!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.2
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Before glitch:
<img width="1085" alt="touch bar shot 2018-01-23 at 1 19 44 pm" src="https://user-images.githubusercontent.com/18474523/35293126-c56bc2f0-0040-11e8-9bac-755134058c8e.png">

After glitch:
<img width="1085" alt="touch bar shot 2018-01-23 at 1 19 51 pm" src="https://user-images.githubusercontent.com/18474523/35293153-dafe423c-0040-11e8-8efe-2edf8a918344.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

Could you please attach an export of your preset?

Of it's a bug, for now the only solution will be to downgrade e.g. to 2.218 (https://boastr.net/releases)

I'll check it and fix it with the next update.

**Comment by CarterVE** [comment]
Sure, how do I export my preset?

**Comment by fifafu** [comment]
Ah, there is the "Manage Presets" button on the bottom left of the trackpad window, after clicking it you will see the export button :-)

**Comment by CarterVE** [comment]
It appears I just have the default preset!

**Comment by fifafu** [comment]
That's just the name :-) it would still be awesome if you could select your default preset and click the export button, this will give me your exact touchbar config.

**Comment by CarterVE** [comment]
Sorry for the delay, here you go! Let me know if you can figure it out.

Thanks!

[Default.json.zip](https://github.com/fifafu/BetterTouchTool/files/1671950/Default.json.zip)

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
