### ISSUE TITLE
[Feature] BTTremote can become wireless headphones if it is able to listen to Mac audio

### ISSUE THREAD

**Issue by naeleejang** [fifafu/BetterTouchTool#2014]
It would be awesome if BTTremote can listen to Mac audio, so it can also function as wireless headphones.

**Comment by fifafu** [comment]
Sorry, unfortunately this is currently not planned as its quite complicated to get right.
I think there are other apps for iOS which can do this already (one is called headset as far as I know) - but I haven't tried them yet.
