### ISSUE TITLE
Mozilla Thunderbird Emergency Mode when starting with BTT Keyboard Shortcut.

### ISSUE THREAD

**Issue by sielo** [fifafu/BetterTouchTool#2017]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm having strange problem. I use Mozilla Thunderbird as mail client.
I configured in BTT on iMac Pro:
1. Keyboard shortcut : Launch Thunderbird.app
2. BTT Remote Action : Launch Thunderbird.app
When I start Thunderbird with BTT Remote - everything is perfect.
When I start Thunderbird straight from Dock - everything is perfect.
When I use my BTT keyboard shortcut - Thunderbird starts in Emergency Mode.

I have the same situation on my MacBookPro with TouchBar.
Starting Thunderbird from TouchBar - works fine.
Starting Thunderbird with BTT shortcut -> Emergency mode.

I've tried several shortcuts on both iMac Pro and MBP - it works always the same.

#### Device information:

Type of Mac: iMacPro, MacBookPro USB-C
macOS version: both - 10.13.2
BetterTouchTool version: 2.332 and also 2.330 (this is not an issue with the latest version).

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Restarting Mac doesn't help at all.

I tried this:
1. disabled this shortcut in BTT ;
2. configured MacOS Service to run Thunderbird App and triggered it in preferences->keyboard->Shortcuts. And this works fine. So this is not a problem with starting Thunderbird with shortcut at all.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Maybe thunderbird has some setting to start it in safe mode while e.g. holding down cmd? In general the Touchbar button calls the same code as the keyboard shortcut to launch apps.

**Comment by sielo** [comment]
Yes. You are right. I always use my shortcuts with: CTRL+OPT+CMD+<key>
But in Thunderbird Option key makes it to start in Safe Mode.
Tahnk You for quick response.



*z poważaniem*
*Michał Jasiński*
       tel. +48 501 307 938

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

W dniu 2018-01-24 o 08:57, Andreas Hegenberg pisze:
