### ISSUE TITLE
Last update completelly screwed up my Trackpad and external mouse

### ISSUE THREAD

**Issue by sebfindling** [fifafu/BetterTouchTool#2018]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

So I turn on my Macbook pro 2017 15" and suddenly the trackpad wont click, it doesn't even give the vibration feedback when I try to click it, luckily I have the OS set to let me <kb>Tab</kb> thru all elements to I manage to Swap buttons in trackpad settings, then start right-clickig the mouse to make regular clicks and try to find out wtf is going on.

After trying many things, including exiting BTT, nothing happens, until I try removing everything from Startup items, then it finally works. So I manually open BTT to see if that was the problem, and guess what? Trackpad stops working again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad and external bluetooth mouse (MX Anywhere 2)

#### Device information:

Type of Mac: Macbook pro 2017, 15"
macOS version: 10.3.2 (i updated yesterday and after that BTT started failing)
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's very weird. Nothing has changed in regards to trackpad/mouse functionality as far as I can tell. (Also there have already been like 30k updates to that version)

I'll keep an eye on this, but in any case it must be something very specific.
If possible please go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop, would be great if you could send that to me.

**Comment by sebfindling** [comment]
Hi; I just want to let you know that the problem was physically related to my trackpad, not BTT's fault. Sorry for the fake positive :)

Been using and loving BTT for over 9 years, thanks for the great job.
