### ISSUE TITLE
After Waking High Sierra (10.13.2), a Restart is Required to get User-Defined Snap Areas Working

### ISSUE THREAD

**Issue by BigPrimeNumbers** [fifafu/BetterTouchTool#2019]
After I wake my computer from sleeping at night, I have to restart BTT to get my user-defined snap areas working again. Default snap areas work okay without a restart.

Type of Mac: Macbook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.13.2
BetterTouchTool version: 2.332

**Comment by fifafu** [comment]
I'm tracking the snap area issue here: https://github.com/fifafu/BetterTouchTool/issues/1888

Should be resolved soon!
