### ISSUE TITLE
The tap gesture's feedback is not working

### ISSUE THREAD

**Issue by bingxyz** [fifafu/BetterTouchTool#202]
#### Description of your bug/question/feature request...:

The feedback of every number's finger tap is not working.
1 finger, 2 finger, 3 finger, 4 finger tap's feedback are not working on Each kind feedback.
( Other gesture feedback is working normally. )
Can you help me to solve? Thank you.

**What kind of Mac are you using?**

MacBook Pro (Retina, 13-inch, Early 2015)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackad

**Which versions of macOS and BetterTouchTool are you running?**

BetterTouchTool version : 1.961
macOS : Sierra 10.12.2

**Comment by fifafu** [comment]
That's currently a known limitation, the feedback only works while fingers are still touching the trackpad, however the tap gestures trigger after the fingers have left the trackpad.

I'll check if I can add a workaround!
