### ISSUE TITLE
crashes in HS several times a day...

### ISSUE THREAD

**Issue by fKing** [fifafu/BetterTouchTool#2020]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
i see this several times a day, for a while now...

//edit by admin: removed crashlog to make it more readable. Basically it's crashing with 
```
Assertion failed: (pendingNotifications), function -[CFPrefsSearchListSource _deferredNotify:ofChangesFromDictionary:toDictionary:], file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreFoundation/Foundation-1451/CoreFoundation/Preferences.subproj/CFPrefsSearchListSource.m, line 1113.
 ```

#### Device information:

Type of Mac: macbook 12"
macOS version: 10.13.3
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

i get those crash popups, then go back to work (and BTT seems to be working)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by JimTomlinson** [comment]
Same problem here, with the latest 15" MBP. Pretty much every time the mac wakes from sleep.

**Comment by fKing** [comment]
same here, mostly when i wake-from-sleep (but sometimes out of nowhere...)

**Comment by fifafu** [comment]
Unfortunately this is a bug in macOS 10.13.2 I have already reported it to Apple quite a while ago.... I have  not yet checked whether it has already been fixed in 10.13.3.

I'll keep you updated.

**Comment by fKing** [comment]
just updated the OS; will keep an eye on things, and report back...

**Comment by lijmehlferber** [comment]
Sorry to jump in, but I am updated to 10.13.3, and the problem seems to still be occurring.

**Comment by fifafu** [comment]
Apple has acknowledged by bugreport, I hope it'll get fixed soon. I'm currently experimenting with a workaround and will probably release a new alpha version later today - would be great if you could check whether that changes anything.

**Comment by fKing** [comment]
will do...! thx
    On Friday, February 2, 2018, 5:51:39 AM EST, Andreas Hegenberg <notifications@github.com> wrote:  
 
 
Apple has acknowledged by bugreport, I hope it'll get fixed soon. I'm currently experimenting with a workaround and will probably release a new alpha version later today - would be great if you could check whether that changes anything.

**Comment by mlevin77** [comment]
It's happening to me on 10.11 - no crash notice, nothing in the Console logs - just randomly notice every so often that it's not running and have to re-start.

**Comment by fifafu** [comment]
@mlevin77 that's a different issue then. If possible please create a separate issue

**Comment by mlevin77** [comment]
I did create a different one and I got a reply that said they were deleting it and merging it into this one!

**Comment by fifafu** [comment]
I have just uploaded v2.335 alpha and completely removed the bluetooth part that I assume could be the culprit. Would be great if you could try (get via "check for alpha version updates")

**Comment by fKing** [comment]
just emailed you (bounced back, said my account was disabled??); anyway, installed, and will keep an eye on things, and report any crashes if (they've been pretty sporadic). thanx for staying on top of things!

**Comment by lijmehlferber** [comment]
I have been using v2.335 all day and so far haven't seen a crash in BTT since updating.

**Comment by fifafu** [comment]
Closing  this issue as the workaround I have added seems to work fine.

**Comment by mlevin77** [comment]
It's still happening to me, v2.513!

**Comment by habalda** [comment]
Happening to me after upgrade to High Sierra and - simultaneously - BTT 2.6
