### ISSUE TITLE
Touchbar widgets (show return value) scripts are not running repeatedly 

### ISSUE THREAD

**Issue by Worie** [fifafu/BetterTouchTool#2021]
#### Description of bug/feature request/question:

I use Touch Bar server to emulate it as clearly mbp 2014 didn't have it. Whichever widget you choose (apple script widget with return value or shell script with return value) it does not update on the Touch Bar itself, even tough if you press a modifier key (ex. cmd) to show other widgets and release it, it'll refresh.

Battery and other widgets refeshes normally as expected. 

It used to work one version ago.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MacBook Pro mid 2014 13"
macOS version: 10.13.11
BetterTouchTool version: 2.332 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here goes my config: _the link has been removed_

And thank you so much for node.js support. That'll allow me to create a lot of widgets, you really made my day when this update came out :) I'm already thinking about how to simulate "marquee effect" for some widgets with node and a few others, if you're planning anything particular related to node.js support (perhaps async, stream support for scripts or smth) I'd be very thankful for links to those tickets / anything.

**Comment by Worie** [comment]
After some further testing, the script isn't even run automatically for specified interval. It's only rerun on "refreshing" the UI of Touch Bar itself (ex. when I switch to modifer-view via CMD, CTRL or others)

**Comment by fifafu** [comment]
Hey,

Sorry I'm currently only on my phone, will be back with access to my macbook tomorrow evening.

What refresh interval have you set? (It must be higher than 0.1s)

**Comment by Worie** [comment]
I've tried various options, both 0, 0 > x > 1 , 5.. none of them seemed to work unfortunately (i checked it via creating a script that creates a file with a timestamp, and it didn't refresh).

If you look into my config I've shell related actions attached to both widget itself (interval) and as an action (it's a twitter widget, it should refresh on various conditions and if you click it -> it points you to that tweet).

**Comment by fifafu** [comment]
Mhh, your exported preset doesn't seem to contain any script widgets. 

I have just tested a bit, but in general everything works as expected here. 

Could you try to paste this into BTT? (it should just show the date via a apple script widget and update every second):
```
{
  "BTTWidgetName" : "show date",
  "BTTTriggerType" : 639,
  "BTTTriggerTypeDescription" : "Apple Script Widget",
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTEnabled" : 1,
  "BTTOrder" : 7,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemIconHeight" : 22,
    "BTTTouchBarItemIconWidth" : 22,
    "BTTTouchBarItemPadding" : 0,
    "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
    "BTTTouchBarButtonColor" : "75.323769, 75.323769, 75.323769, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarAppleScriptString" : "return do shell script \"date\" #example: execute a shell script and use the result",
    "BTTTouchBarAlternateBackgroundColor" : "128.829533, 128.829533, 128.829533, 255.000000",
    "BTTTouchBarScriptUpdateInterval" : 1
  }
}
```

**Comment by Worie** [comment]
Sure, but what do you mean paste? Import it as a preset or what? I'll try but I'm not sure I understand what am I supposed to do exactly.

And it kinda worries me that there are no widgets in the exported preset 🤔

**Comment by fifafu** [comment]
Hey Worie,

you can just copy the JSON (cmd+c) here and paste it (cmd+v) in BTT. 
Yeah it's weird, maybe something went wrong with the export? Maybe try to export again.

**Comment by Worie** [comment]
Alright, I see. I didn't know that BTT would capture it this way :) 

Unfortunately - The widget you provided also does not work :/ I've recorded its behaviour tough: ![toucbarbug](https://user-images.githubusercontent.com/6313514/35459252-9cb48a80-02df-11e8-9797-bb0171552408.gif)

It still behaves as described in the beginning of the issue.

And i tried exporting multiple times - the JSON still misses my Touch Bar related configs (perhaps due to fact that it's emulated by server? 🤔 ) I tried rebooting multiple times and couldn't find a way around it, thus I created this thread

**Comment by fifafu** [comment]
Weird... I'm sometimes using https://sindresorhus.com/touch-bar-simulator/ when I'm on my old Macbook and it seems to work fine with that one

**Comment by fifafu** [comment]
But I remember there have been various issues with emulated touch bars that haven't been resolved yet. Apparently on some systems the emulated bar behaves differently...

**Comment by Worie** [comment]
I used TouchBarServer (https://github.com/bikkelbroeders/TouchBarDemoApp/releases) -> tough I installed the app you're using and the same issue occurs :/

And as I said I guess it used to work... But I'm not 100% sure.

I'd reinstall BTT but now knowing that I have some other issue with exporting I'm not confident enough, I really wouldn't like to loose my config :D

**Comment by Worie** [comment]
Hmm well then. I'm just using the emulator to prepare a config so when I buy a new mbp I have it already configured as I want :) 

Do you think the export issue is somehow related to that? Because that'd block my migration to newer Mac. 

If there's anything else that you think that might help solve this issue, please let me know :)

**Comment by fifafu** [comment]
Maybe go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop which contains the raw configuration. If you zip it and send it to me (boastr.net@gmail.com), maybe I can tell what's wrong (if anything)

**Comment by Worie** [comment]
Thanks - sent!

**Comment by fifafu** [comment]
Ok, so your setup is definitely working here (I can now se your widgets!). I assume it really has to do with the emulated touchbar.

**Comment by Worie** [comment]
Thank you for your help. Will I be able to import my presets with the debugging method if I migrate to newer MBP? Because regular export didn't seem to work :/

**Comment by fifafu** [comment]
Yes, you just need to copy it to ~/Library/Application Support/BettertTouchTool on the new machine.

However the json export should also work, is it possible you are trying to override an existing older export? I think there might be a bug keeping the old version when trying to do that.

**Comment by Worie** [comment]
Awesome! Yes, I did try to override it. I have tested it now and it seems like they aren't being created. I've tried to export my config to various locations with various names, and it didn't show up.

**Comment by Worie** [comment]
But perhaps this is related to some other issue, I guess this one can be closed as "emulation related" :)

**Comment by Worie** [comment]
Moved to https://github.com/fifafu/BetterTouchTool/issues/1962
