### ISSUE TITLE
Icon of App Show in Touch Bar and didn't work

### ISSUE THREAD

**Issue by r3j3c73d** [fifafu/BetterTouchTool#2022]
#### Description of bug/feature request/question:
After installation and run the application I have an Icon of Better Touch Tool and when I touch it, nothing happens.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Touch Bar

#### Device information:

Type of Mac: MacBook Pro Late 2017 15'
macOS version: 10.13.0
BetterTouchTool version: 2.233 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<img width="1085" alt="touch bar shot 2018-01-25 at 8 17 33 am" src="https://user-images.githubusercontent.com/32164769/35371263-40daa6dc-01a8-11e8-8390-2c7da81be5a6.png">

**Comment by fifafu** [comment]
You need to configure touchbar actions in the Touchbar tab in BetterTouchTool.
