### ISSUE TITLE
Annoying screen

### ISSUE THREAD

**Issue by AlexKorolkov** [fifafu/BetterTouchTool#2024]
#### Description of bug/feature request/question:
How can I get rid of this pop up dialog?
I'm using better touch tool for years and I paid for the license, I do not need any more cool features and I do not want to give any other permissions to the tool. I just want it to work as expected.
But for now I have to switch the tool off because of this annoying behavior of the tool.
Please fix it.
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Air

#### Device information:

Type of Mac: MacBook Air (13-inch, Early 2014)
macOS version: 10.12.2 (16C68)
BetterTouchTool version: 2.332 (717)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![screen shot 2018-01-25 at 19 18 02](https://user-images.githubusercontent.com/2435617/35399211-cf84f5de-0204-11e8-907c-7741c1deb3a1.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You need to grant these permissions, they got reset with a recent macOS update. BTT has always needed them.
