### ISSUE TITLE
Pinch In gesture no longer recognized

### ISSUE THREAD

**Issue by grigsby** [fifafu/BetterTouchTool#2025]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Pinch In gesture suddenly stopped working a few days ago. If I watch the "Live View" BTT doesn't register the pinch in gesture anymore, even though I have it defined as a Global Gesture (equivalent to command-W to close tabs). It was working fine for many years.

Also, I'm getting multiple crashes per day as reported by others.

Also, it seems to crash when I connect bluetooth headphones.  :-)

Thank you for a great app, though! It's made my life a lot better for many years.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook (Retina, 12-inch, 2017)
macOS version: 10.13.2
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
For pinches to work they need to be enabled on system preferences -> trackpad.
Could you check whether they are enabled there?

The bluetooth issue will hopefully be resolved by Apple soon.

**Comment by grigsby** [comment]
Yes, that was it! Thank you so much! For some reason some of my system preferences -> trackpad preferences had been lost or changed, and I didn't even think to look there. Thank you again!!

**Comment by fifafu** [comment]
Perfect, if that happens again, please let me know.
