### ISSUE TITLE
Move/resize window actions do not work well

### ISSUE THREAD

**Issue by orkank** [fifafu/BetterTouchTool#2026]
#### Description of bug/feature request/question:
**While working on network;**
Open a folder has big size PSD / Images and try to resize/move the window with BTT, you will see move/resize actions incredibly slow. This is happening only when an open window on a network.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Tested on;
iMac
Macbook Pro

#### Device information:

Type of Mac: iMac, Macbook Pro
macOS version: macOS Sierra / High Sierra
BetterTouchTool version: 2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this can not be improved given the currently available apis. The rendering is done by the specific app, and unfortunately can not be influenced by BTT.
This means it depends on how fast the specific app can rerender after being told to move/resize.

**Comment by orkank** [comment]
Yes, I thought that too, but if you do it normally with the mouse this error does not occur.

**Comment by fifafu** [comment]
yep, unfortunately most apps do behave differently when resizing them using the APIS :-(. Emulating a mouse to drag resize is also not feasible (tried that already)

**Comment by orkank** [comment]
One more problem with Finder, we need an new Finder :) Thanks for replies.
