### ISSUE TITLE
Add a Pause action

### ISSUE THREAD

**Issue by nikitavoloboev** [fifafu/BetterTouchTool#2027]
#### Description of bug/feature request/question:
I want to add a Pause action in this action here: 

![2018-01-26 at 16 35](https://user-images.githubusercontent.com/6391776/35447078-fe053e3e-02b6-11e8-943f-acff8e25ca24.png)

But I don't know how to do it. One option is perhaps to trigger Applescript and run `Delay` action there but that seems excessive. Is there a builtin BTT `pause` action I can use for this?

Thank you.

**Comment by fifafu** [comment]
Have you already checked whether the "delay next action" action works in this case?

**Comment by nikitavoloboev** [comment]
My bad. For some reason I though I searched both `Pause` and `Delay` and found nothing but `delay next action` workflows perfectly well. Thank you.
