### ISSUE TITLE
TouchBar Shell Widget not works for command without defined stdin

### ISSUE THREAD

**Issue by JulyIGHOR** [fifafu/BetterTouchTool#2028]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have made small C++ app that puts number into stdout, and BetterTouch Tool doesn't show output if there is no parameters and no predefined stdin.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MB TB
macOS version:  Latest
BetterTouchTool version:  Latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![screenshot 2018-01-27 01 04 14](https://user-images.githubusercontent.com/3390357/35451431-2e507d5a-02fe-11e8-9609-d33a325d991e.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

thanks for reporting, will be fixed with the next version!
