### ISSUE TITLE
BTT Built-in Switcher - Not All Windows Shown

### ISSUE THREAD

**Issue by mjsagert** [fifafu/BetterTouchTool#2029]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The built-in BTT window switcher is awesome; the menu shows up near the mouse making it easy to select the desired window without much mouse movement.  There are some windows that aren't listed, which I believe is due to the fact that MacOS has different app window types - I've noticed similar issues with Cmd-Tab replacement apps.  The apps that I use with windows that aren't listed on the switcher are BusyCal and Calculator.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Middle-mouse click assign on a Magic Mouse 2.

#### Device information:

Type of Mac: 2017 15" MacBook Pro
macOS version: High Sierra 10.13.3
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! I think it should be fixed with the next version (2.333, alpha should be available later today).

If not, please comment again.
