### ISSUE TITLE
3-Finger-Click haptic response does not work

### ISSUE THREAD

**Issue by Mr-iX** [fifafu/BetterTouchTool#2033]
I'm using a Magic Trackpad 2 and when I create a 3-Finger-Click Gesture, I get no haptic response when I press the 3 fingers on the touchpad.
When I remove this gesture the haptic response works fine.

What could cause this behavior?

#### Device information:

Type of Mac: MacPro5,1
macOS version: 10.13.3
BetterTouchTool version: 2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Settings for a Force Touchpad
![bildschirmfoto 2018-01-03 um 11 43 58](https://user-images.githubusercontent.com/25360303/35481098-23e7e2a2-041d-11e8-9dea-d384b70caeb1.png)

**Comment by fifafu** [comment]
Unfortunately I don't really know whats causing this. There are a handful of users who have experienced similar issues (mostly with Hackintoshs and mac pros or some very old macbooks). Currently the only working solution seems to select the "new btt default normal click" option as the haptic response in the drop down in your screenshot.

**Comment by Mr-iX** [comment]
Thanks, that click is a little bit different, but I'm happy to have a click.

**Comment by fifafu** [comment]
I'm continuing to track this here: #1558
