### ISSUE TITLE
Touch Bar button Haptic Feedback doesn't work on Widgets

### ISSUE THREAD

**Issue by matthewmason0** [fifafu/BetterTouchTool#2034]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The Default Haptic Feedback setting in General Touch Bar Settings will produce a haptic feedback when any BTT Touch Bar *Button* is pressed, but not when a Widget is pressed.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Touch Bar

#### Device information:

Type of Mac: MacBook Pro 2017, 15'
macOS version: 10.13.2 (17C205)
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks, will be fixed in the next version (alpha available later today)
