### ISSUE TITLE
Remove or move "escape key" & "x" key  <Feature request>

### ISSUE THREAD

**Issue by veitch123** [fifafu/BetterTouchTool#204]
I am constantly pressing the escape key by accident. My pinky automatically rests on it and it is driving me up the wall. If at all possible (realise Apple may have locked this down) please provide the ability to either shift the escape key (and the x that replaces it) over and/or get rid of it for good. 

[Others](https://discussions.apple.com/thread/7762774?start=0&tstart=0) seem to be [having the same problem](http://forums.macrumors.com/threads/2016-mbp-touch-bar-pressing-the-esc-button-by-accident.2016358/). 

Thanks. First GitHub post so don't know protocol hope this is ok. 

james.

**Comment by Grolubao** [comment]
This would be awesome.

**Comment by fifafu** [comment]
Unfortunately I think there is no real solution to this. The only way to get rid of the esc button and the x is to check the "show macOS Control Strip" option in the general Touch Bar settings in BTT. However this will also hide the Control Strip and the default Touch Bars. It will then only show the actions defined in BetterTouchTool.

![image](https://cloud.githubusercontent.com/assets/8820811/21715344/3f207934-d404-11e6-8fce-bd26f5a92d14.png)

**Comment by veitch123** [comment]
Thanks for looking into it anyway :) 
I hope people at Apple are having the same problem I am.

**Comment by veitch123** [comment]
I've had an idea. 

What if there were a way to tell BTT to import an app's Touchbar buttons to BTT. Then the user could turn off the system-wide or app's touchbar and just use BTT's but without the ESC key.

Possible? Thoughts? 

Even if it only imported the functions and not the icons, this would be useful.

**Comment by cleverjackal** [comment]
@veitch123 I think importing apps' Touchbar gestures would be impossible, right? There's no API to do it, as far as I know.

**Comment by chris-scheurle** [comment]
Would it be possible with the API to:

- in General Touch Bar Settings: Dropdown (where to show the Global Actions): add an option "Show Global Actions After App Specific Actions (Right Aligned)"

- in Predefined Action: Touch Bar Related Actions: add an option "Show system Control Strip (expanded)"

- when the system Control strip is collapsed again, hide it and switch back to "Show BetterTouchTool Touch Bar, hide system Control Strip" (if that option is selected for the current app)

?

=> That would allow us to mimic the system Control Strip (collapsed) via the Global Actions

**Comment by jredwards** [comment]
I definitely have this problem with the new touchbar. Apparently, I've been unconsciously resting my finger on the escape key for years and never noticed. 

I've been considering just mapping a different key combo to escape and becoming familiar with it. Incidentally, I discovered that CMD+` is a window switching hotkey (was considering that).

**Comment by Pripps** [comment]
metoo - have this problem I mean..

**Comment by nikkundra** [comment]
Has anyone figured out how to disable the ESC button altogether with BTT?  I've lost so much work and productivity at this point.

**Comment by fifafu** [comment]
If you go to the general touchbar settings in BTT and disable the "show macos control strip option" and the "show esc" option, it will be gone. However your control strip will also be hidden by that.

**Comment by fifafu** [comment]
@ikocev you can do it application specific:
![image](https://user-images.githubusercontent.com/8820811/38611254-8031b548-3d83-11e8-9c6c-3d94107d2068.png)

**Comment by PeterKindfield** [comment]
Hey All, with a lot of help from Andreas, I have a BTT solution that works for me. (1) Uncheck "Show MacOS Control Strip" and "Show Escape Button" in general touchbar settings. (2) Create a button with no action and put a bunch of blank spaces in the name and make the button black (this moves the button you'll create in the following step over to the right so your pinky won't hit it) (3) Create a "Toggle BTT Touchbar" button with "Toggle BetterTouchTool Touchbar" as its action. This let's you get the standard touchbar back if/when you need it. Hope this helps y'all as much as it helps me.

**Comment by dewimagento** [comment]
Unfortunately, there's a BTT icon that shows where the escape button used to be, which does the same as the "toggle BTT touchbar" button does. Unless this icon can be hidden, this workaround doesn't fix the problem.

**Comment by PeterKindfield** [comment]
Hey dewimagento, I use the solution I and I don't have the problem you cite. Hmmmm.....

**Comment by dewimagento** [comment]
@PeterKindfield Perhaps this icon is a new feature, that is absent from older versions? If not - how do/did you remove the icon?

**Comment by fifafu** [comment]
You probably have this checkbox set:
![image](https://user-images.githubusercontent.com/8820811/44467464-34850880-a623-11e8-8ff7-b2bbd0789a8e.png)

**Comment by dewimagento** [comment]
Bingo! I was being blind, thank you :)
