### ISSUE TITLE
[Feature Request] Delay macOS hot corners

### ISSUE THREAD

**Issue by mapsnmad** [fifafu/BetterTouchTool#2041]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I love the macOS hot corners, but they trigger more quickly than I wish. If it's possible for you to give me an option to delay them, they'd be less intrusive and more useful to me. I keep bumping into the corners. I'd wish for a 500ms or 1000ms delay, I guess.

I use hot corners for Mission Control, Application Windows, and Desktop.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All, but mostly mouse.

#### Device information:

Type of Mac: Mac Pro
macOS version: 10.12.6
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think I can add a delay option to the "move mouse to xx corner" trigger in the other section in BTT.
I'll look into it!

![image](https://user-images.githubusercontent.com/8820811/35724934-bfeafac8-07ff-11e8-92b6-d08ab1c7145a.png)

**Comment by fifafu** [comment]
This is now possible with the move mouse to x corner actions in the Other tab in BTT.
![image](https://user-images.githubusercontent.com/8820811/35931150-238f1040-0c34-11e8-82a9-77fc9a1fedda.png)

**Comment by mapsnmad** [comment]
Thanks for giving it a try! It’s not working yet.

When I add a “Move Mouse To ….” Trigger, I get a popup pane offering a
slider & entry field for delay time.

I choose .500 ms and click OK, but the trigger doesn’t work. I tried
disabling all hot corners. I also tried asking for a different Predefined
Action, as a test (I chose Caps Lock, so I could see a light if it got
triggered).

The trigger doesn’t trigger anything.

Also, there’s no gray gear icon to the left of the Trigger in the lower
pane, as you showed on the screen shot you sent me.

In fact, I still see "Please Select a Gesture" after trying to choose any
of the "Move Mouse to..." Triggers. I attach a screenshot.

Thanks for taking a look!

--mapsy
[image: Inline image 1]

On Wed, Feb 7, 2018 at 12:24 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Ah sorry, that's now fixed in v2.341 alpha (which however is very experimental as I have rewritten big parts of the keyboard shortcut handling)

You now need to click the little gear icon to get to the sheet.
