### ISSUE TITLE
I hope you can add icloud sync

### ISSUE THREAD

**Issue by Thare-Lam** [fifafu/BetterTouchTool#2042]
I don't use dropbox...

**Comment by fifafu** [comment]
Unfortunately for now there is only the dropbox option because I want to keep the complexity small. You just need a dropbox account to use it.

In the future other sync options may be coming, but it's not on my "high priority todo list" :-)

**Comment by Thare-Lam** [comment]
Ok, thank you.
I'm just using dropbox to sync it now. 
Or you can do it like iTerm2: "load preference from a custom folder or URL". Then I can set the folder as my iCloud folder.
