### ISSUE TITLE
Long Press Functionality

### ISSUE THREAD

**Issue by CarterVE** [fifafu/BetterTouchTool#2043]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Feature Request: 
Please consider implementing long press functionality for BTT buttons! It would be great to set extended app options or extra functionality, for example long pressing "Close app under mouse" to "Quit app under mouse"!

Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: Macbook Pro 15" 2017
macOS version: 10.13.2
BetterTouchTool version: 2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is on my todo list and will probably come in february.

I'm tracking this request here already: https://github.com/fifafu/BetterTouchTool/issues/374
