### ISSUE TITLE
2 fingers fixed tip taps don't work anymore(

### ISSUE THREAD

**Issue by efimovdk** [fifafu/BetterTouchTool#2045]
#### Description of bug/feature request/question:
two fingers fixed tip taps are extremely hard to trigger for last two updates. I haven't change anything though. one finger fixed tip taps are ok. What can be the problem? 
my config:
![image](https://user-images.githubusercontent.com/9094136/35613146-4397e636-067c-11e8-947b-f2321ded4acc.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
i face this issue on MacBook's Trackpad only, on magic mouse everything is fine

#### Device information:

Type of Mac: MBPro early 2015 13 inch retina
macOS version: macOS HS 10.13.2
BetterTouchTool version: 2.332(713)

**Comment by fifafu** [comment]
I think there is an issue when setting the minimum required distance to 0. Could you try setting it to something very small but higher than zero?
