### ISSUE TITLE
BTT keeps on crashing

### ISSUE THREAD

**Issue by rogersniper** [fifafu/BetterTouchTool#2046]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The title says it all. BTT keeps on crashing on me. 

#### Device information:

Type of Mac: MacBook Air 2012
macOS version: 10.13
BetterTouchTool version: 2.332
[BetterTouchTool_2018-01-02-010156_Users-MacBook-Air.crash.zip](https://github.com/fifafu/BetterTouchTool/files/1681319/BetterTouchTool_2018-01-02-010156_Users-MacBook-Air.crash.zip)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by minamhere** [comment]
I think I'm having this same issue. New clean High Sierra installation yesterday, just installed BTT, it crashes after a few minutes. 

Type of Mac: Mac Mini 2012
macOS version: 10.13
BetterTouchTool version: 2.332

[BetterTouchTool_2018-01-31-191152_Chriss-Mac-mini.zip](https://github.com/fifafu/BetterTouchTool/files/1683776/BetterTouchTool_2018-01-31-191152_Chriss-Mac-mini.zip)

**Comment by fifafu** [comment]
I have reported this issue to Apple and they are aware of it. I think it will be fixed soon.
I'm tracking it here: https://github.com/fifafu/BetterTouchTool/issues/2020 

Unfortunately I have not been able to find a workaround for the bug on my side, but I'll keep looking.
