### ISSUE TITLE
Keep having to restart BTT

### ISSUE THREAD

**Issue by dso3719** [fifafu/BetterTouchTool#2047]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by damga** [comment]
Started happening to me after High Sierra update. BTT would be randomly just not there. I think it mainly happens after wake up from sleep, but I'm not sure about this.

**Comment by mlevin77** [comment]
I have the same problem, I'm on OS X 10.11.6, it randomly quits - no error message, no crash, no notices in Console that I can see - it just quietly and randomly exits.

**Comment by fifafu** [comment]
This is probably #2020
