### ISSUE TITLE
(no issue, false alarm) no touchbar support on 10.13.3

### ISSUE THREAD

**Issue by dinpin** [fifafu/BetterTouchTool#2049]
#### Description of bug/feature request/question:
since update to 10.13.3 BTT no longer seems to have control over the touchbar. other shortcuts and gestures like the trackpad and keyboard ones keep working fine.

I already restarted the app and tried to disable/enable touchbar support. No effect

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MBP 15 / 2016
macOS version: 10.13.3
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think it's working fine, maybe you just did hide the BTT touchbar?

**Comment by dinpin** [comment]
yes, it is fine. Just confirmed on another mac and it is indeed fine. im sorry, there just seems to be something else odd with this machine. I am sorry for false a alarm
