### ISSUE TITLE
Pressing ⌘+Delete crashes the app

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#205]
when trying to delete an action pressing `⌘+Delete` crashes the app immediately

macOS 10.12.2 (16C67)
MacBook Pro (Retina, 13-inch, Mid 2014)
BTT 1.978 (569)

**Comment by Grolubao** [comment]
@moshed it would be useful to mention what version you are running and what OS

**Comment by moshed** [comment]
@Grolubao youre right. just edited it. thanks for the heads up!

**Comment by fifafu** [comment]
Thanks for reporting, it will be fixed with the next update!
