### ISSUE TITLE
New setting - Trackpad: touch area smaller

### ISSUE THREAD

**Issue by fox94610** [fifafu/BetterTouchTool#2050]
MUCH WANTED FEATURE...
Trackpad of new MacBook Pros - constrain the active area of the trackpad so it is the same size as the old MacBook Pro's trackpad. In other words ignore input from the top, right, bottom and left edges of rectangle in order to avoid accidental input, which is plaguing a huge number of users. The old trackpad's dimensions and location on front plate is great. PLEASE find some way to bring it back via code. I just downloaded the latest version of your app and combed through the settings of trackpad. I found some configs sort of like this, attempting to solve the oversized trackpad issue, but none of them stop the issue. When it comes down to it, there is just one simple issue, the pad is WAY to big. Simple solution, make it smaller. 

#### Affected input device
New MacBook Pros with ridiculously large trackpad

#### Device information:
My particular mac : MacBook Pro (15-inch, 2017)
macOS version: macOS Sierra
BetterTouchTool version: 2.33

P.S.   I would pay $80 for this single mod alone. I'm bet I'm not alone.

**Comment by fifafu** [comment]
Unfortunately this is very hard to do, as there are no good ways to block mouse movement. It's on my todo list but I currently can't promise there will be a good solution in BTT - it may require deeper system integration/hacks.

This has already requested a few times, so I'll be closing here
E.g.: 
https://github.com/fifafu/BetterTouchTool/issues/196

**Comment by cocoahuke** [comment]
@fox94610 
Here is the solution for adjust trackpad to any size, donation is welcome!
[https://github.com/cocoahuke/shrink_trackpad](https://github.com/cocoahuke/shrink_trackpad)

**Comment by fifafu** [comment]
@cocoahuke very nice! I'll refer people asking for this to your repository :-)

**Comment by cocoahuke** [comment]
> @cocoahuke very nice! I'll refer people asking for this to your repository :-)

Thanks!
