### ISSUE TITLE
 "NSSQLiteErrorDomain error 8"

### ISSUE THREAD

**Issue by pstephenwille** [fifafu/BetterTouchTool#2051]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

After using Migration Assistant, BTT is unusable because it pops up dozens of error windows with...
 "NSSQLiteErrorDomain error 8"

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard shortcuts

#### Device information:

Type of Mac: MacBook Pro, 15"
macOS version: 10.13.3
BetterTouchTool version: 2.332.713

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Reinstalled BTT too but no dice.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This usually happens when the permissions of the ~/Library/Application Support/BetterTouchTool folder have somehow been messed up.
This probably means there are also other issues with the permissions, thus I'd try this terminal command to repair/reset all of the permissions for your current user: ```diskutil resetUserPermissions / `id -u` ```

**Comment by pstephenwille** [comment]
Thanks for the follow up.  Unfortunately I won't be able to test as I re-migrated to a different machine and don't have this issue.
