### ISSUE TITLE
Feature request: web-page specific command

### ISSUE THREAD

**Issue by zavidos** [fifafu/BetterTouchTool#2052]
Hi and thanks for developing this amazing software.
I found really nice the possibility to customise the touchbar for each app, however it would be even nicer to have, for some important apps like Safari, in-app customization.
For example, I use to have brightness  and volume slider when using VLC and it would be nice to have them when I'm watching netflix too, but up to now all I can do is having them all the time I have safari opened
Thanks for the attention

**Comment by fifafu** [comment]
This is on my todo list, however it's relatively hard to achieve. I think I'll have a first version in 2-3 weeks. I'm tracking this issue here: https://github.com/fifafu/BetterTouchTool/issues/49
