### ISSUE TITLE
[Feature Request] Add widget to control strip

### ISSUE THREAD

**Issue by Vxider** [fifafu/BetterTouchTool#2053]
Hi, can I add Widget to control strip? I have hidden my macos menu and I want to add "Data/Time widget" to touchbar control strip, so I can check the time anytime and I also do not want to override application's default touchbar by customize by BetterTouchTool.

**Comment by fifafu** [comment]
That's not possible because the is no api to do that.
Btt can only replace the Touch Bar completely.

**Comment by Vxider** [comment]
Thanks for replying
