### ISSUE TITLE
Enable / Disable BTT command

### ISSUE THREAD

**Issue by Zedliminal** [fifafu/BetterTouchTool#2055]
The command isn't working as intented (I think), while BTT is active, and I input the gesture set for Enable / Disable BTT, it disables BTT, but it doesn't work while BTT is disabled. This command should be usable even while BTT is disabled so it can be enabled again through this same gesture!

**Comment by fifafu** [comment]
This is not possible because gesture recognition is turned off when disabling BTT. It's not possible to only activate parts of the gesture recognition.
However you can use a keyboard shortcut to trigger the action - that will stay active even if BTT is disabled.
