### ISSUE TITLE
Feature Request: Scheduled events

### ISSUE THREAD

**Issue by evilplanet** [fifafu/BetterTouchTool#2057]
It would be nice to do something such as launching an app at 18:00 every Monday.

I know it's not triggered by touch or keyboard and that there are other apps to do just that such as Automator.

But I already use BetterTouchTool for all my shortcuts. I think it would be an enhancing addition to the powers it already has.

**Comment by fifafu** [comment]
Definitely planned for one of the next releases!

**Comment by SouthernAtHeart** [comment]
Once I get a routine set for a shortcut, is it possible to automate it somehow like once a day at a certain time?
