### ISSUE TITLE
Applescript widget not displaying

### ISSUE THREAD

**Issue by wtluke** [fifafu/BetterTouchTool#2058]
#### Description of bug/feature request/question:

I have a basic AppleScript which pulls some JSON (using curl and JSONHelper), and displays the value (a string containing "3.2" or similar) on the Touchbar. It worked fine, for a few minutes, but not any more.

If I restart the app, the name of the widget is shown for half a second on the touchbar, and then vanishes.

To help diagnose it, I added some padding in red. This shows up on the Touchbar, but nothing from the widget (which runs fine in the app, manually)

![image](https://user-images.githubusercontent.com/4312361/35776667-92e798ca-0998-11e8-8251-01f945ca3d28.png)

The red padding is visible.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

2016 Macbook Pro Touch Bar
v2.332 (713)

#### Device information:

Type of Mac: Macbook Pro 2016
macOS version: 10.13.13
BetterTouchTool version:  v2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This probably means your apple script is returning an empty value, in that case the widget is hidden.

**Comment by fifafu** [comment]
Btw. I'd recommend the new shell script widget for downloading parsing json, e.g. using python:

![image](https://user-images.githubusercontent.com/8820811/35777011-c80cf0e6-09a6-11e8-9ca7-f1d2af701880.png)

It's more performant

**Comment by wtluke** [comment]
Oh, that's embarrassing. I saw the shell script option but assumed it was just bash; had I known it supported Python I wouldn't have bothered wasting an hour on AppleScript! Brilliant. I'll give it a go now and let you know.

**Comment by wtluke** [comment]
Five lines of clean Python. All sorted. Love the app!
