### ISSUE TITLE
Three finger swipe sensitivity

### ISSUE THREAD

**Issue by eggplantsplz** [fifafu/BetterTouchTool#206]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Any way to increase the sensitivity of three finger swipe commands? I often find myself having to swipe multiple times for the action to be acted upon. For example, I currently have '3 finger swipe up' to open a new tab in Safari, and '3 finger swipe down' to close the tab; however, I find that I'll sometimes have to elicit the swipe multiple times before the command will actually go through..

**What kind of Mac are you using?**

Mid-2015 MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra / BTT 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Currently it's not possible, but I could add sliders to change the sensitivity. I'll look into it!

**Comment by eggplantsplz** [comment]
Cheers.

From my experience, the lag/sensitivity issues is most pronounced with the '3 swipe down' gesture; whereas up, left, and right usually trigger the action on first swipe. It may be something to do with individual finger placement / spacing; nevertheless, it also doesn't trigger while testing in live-view as well (takes multiple tries).

Great software! Will definitely be purchasing a license soon.

**Comment by fifafu** [comment]
The three finger swipe sensitivity slider in the advanced settings will work better with version 2.08 sometime next week.
