### ISSUE TITLE
Lost Touch Bar Functionality

### ISSUE THREAD

**Issue by JuliaTruchsess** [fifafu/BetterTouchTool#2061]
I created a bunch of Touch Bar buttons (application launcher/switchers). It's wonderful. I also created a key sequence action on the fn key to toggle Better Touch Tool's Touch Bar, so I can go back and forth between my groovy app switcher and the normal app & system Touch Bar control functions. So far so good, but two problems, one huge and the other annoying:

1. When BTT's touch bar is disabled and the normal app controls + control strip appear, the control strip items that are in the same locations as my BTT buttons (left side of the TB), like screen brightness, keyboard backlighting, etc don't work. They highlight when pressed but they don't performa their functions. The ones at the right-hand side of the TB ((Volume, and screen brightness when the system controls are compressed to the right) _do_ work. App controls at the left side of the TB (like Back in Chrome) work. It's only the control strip items that don't work, which is kind of a drag since I can't control my screen and keyboard brightnesses. It may be coincidental that the non-working keys are those in the same general location as the BTT buttons, or maybe it's not; it's difficult to tell.

2. I cannot get the standard function keys to appear at all, unless I set the System Preferences to always show the function keys, which obviously I don't want. In fact, all this messing around seems to have somehow borked my fn key, because if I disable the key sequence in BTT, the fn key does nothing at all regardless of the Keyboard prefs setting.

These behaviors are not affected by changing the "Show MacOS Control Strip" setting in BTT's General Touch Bar Settings. I've restarted both BTT and the computer, but neither helped.

#### Device information:

MacBook Pro 2018
macOS 10.13.3
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://user-images.githubusercontent.com/36139907/35783161-e21476f6-09d0-11e8-9746-adcf4ff0e7ce.png)

**Comment by fifafu** [comment]
Very weird I haven't encountered/heard of  such an issue before.

So if you quit BTT the control strip items work correctly?

I'll try to look into this tomorrow. In general you should set the Touchbar behavior in system preferences -> keyboard  to "show app controls and control strip " when using BTT.

**Comment by JuliaTruchsess** [comment]
In the GIF below, first we see the BTT custom buttons (yay!), then we see the Chrome app-specific buttons working, then Control Strip functions on the right working, then Control Strip functions on the left not working :(

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/36139907/35783421-ce396be2-09d4-11e8-85f8-4896ea3a10aa.gif)

**Comment by JuliaTruchsess** [comment]
Actually, when I quit BTT, these controls are STILL not working, and my fn key doesn't work either. But it was all working earlier today before I started playing with BTT! My keyboard prefs are set to App Controls with Control Strip, and Fn key should show function keys.

Thanks,
Julia

**Comment by JuliaTruchsess** [comment]
Restarted in Safe Mode and everything worked. Restarted in normal mode and still broken.

**Comment by fifafu** [comment]
Mh, then it's not BTT that's causing the issue, because BTT does really nothing if it's not running.
Can you think of any other settings you changed or any other app you installed?

**Comment by JuliaTruchsess** [comment]
OK, it was Karabiner-Elements - any time that's running, the keyboard backlight controls and some others don't work. Even though the only thing I've ever used Karabiner for is to remap the right-option key to "Enter" (not Return). Not easily done with BTT, I think, but not a huge issue, as unfortunately few programs distinguish between them anymore anyway :(

Thanks for your help!
