### ISSUE TITLE
Problem chaining keyboard shortcuts in BTT 2.333

### ISSUE THREAD

**Issue by NevinBR** [fifafu/BetterTouchTool#2062]
#### Description of bug/feature request/question:

I have a pair of custom keyboard shortcuts, one of which calls the other. This worked in BTT 2.332, but does the wrong thing in BTT 2.333.

The specifics of my situation are rather involved, but here is a simple example to reproduce the problem:

1. Make a BTT shortcut for TextEdit triggered by ⌘G to paste custom text “Test”.
2. Make a BTT shortcut for TextEdit triggered by ⌘E to trigger the shortcut ⌘G.
3. Open TextEdit and press ⌘E.

Expected behavior: The text “Test” should be pasted.
Actual behavior: The text “TestgTest” is pasted.

Furthermore, if I press ⌘E, release the E, and keep holding the ⌘, then “Test” is pasted repeatedly, followed by “gTest” when I finally release ⌘. And if I press E repeatedly while holding ⌘, then I get a whole mess with many copies “Test” followed by many copies of “gTest” interspersed with many copies of “e”, and it continues pasting the latter two for some time after I release ⌘.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: 2013 retina MacBook Pro 15.4″
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.333 (716)

**Comment by fifafu** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/8820811/35824335-d535cf42-0ab2-11e8-94e2-5b5df3c23fdb.png)

(this seems to be working here, but maybe there is some other setting included?).

Maybe you can copy & paste the gesture here (if you copy something in BTT it will be copied as JSON, so you can paste the json here)

**Comment by fifafu** [comment]
Ah, maybe this behaves differently on 10.12.6 ( I made some changes to allow key repeat, but only tested on 10.13.x).
In that case I'll disable the fixes for 10.12.x

**Comment by fifafu** [comment]
Could you try v2.334?

**Comment by NevinBR** [comment]
Working again in 2.334 and 2.335, thanks!
