### ISSUE TITLE
bug: dark menu bar widget greyed out

### ISSUE THREAD

**Issue by fabi94music** [fifafu/BetterTouchTool#2063]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When using the dark menu bar, the widget is not changing to a white version. 

#### Device information:

Type of Mac: MacBook Pro 15 inch (Late 2014)
macOS version: 10.13.3
BetterTouchTool version: 2.334 (717)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![bildschirmfoto 2018-02-05 um 21 29 39](https://user-images.githubusercontent.com/29753374/35827289-b4999120-0abb-11e8-999b-81e748347c3b.jpg)

**Comment by fifafu** [comment]
Thanks for reporting, this will be fixed again with the next version.
