### ISSUE TITLE
Feature request: increase maximum interval of script execution

### ISSUE THREAD

**Issue by wtluke** [fifafu/BetterTouchTool#2064]
Would it be possible to allow more than 100 seconds between intervals when running scripts? Ideally user defined...or if it has to be limited, then 2 hours?

Thanks for a great piece of software. Upgraded on day 2 of my trial!

**Comment by fifafu** [comment]
I think you can enter any value if you click on the balue itself and don't use the slider.

**Comment by wtluke** [comment]
Oops. Thanks!
