### ISSUE TITLE
Clipboard manager pastes incorrect item

### ISSUE THREAD

**Issue by MeteC** [fifafu/BetterTouchTool#2069]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I open clipboard manager, and immediately double click on some item in the list. It is highlighted, clipboard manager disappears, but the first item in the list is always pasted - regardless of which item I double-click on. 

This does not happen if I first single click somewhere in the clipboard manager window, all functions as expected in that case.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse, regular mouse, trackpad

#### Device information:

Type of Mac: iMac
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, I cant' seem to reproduce this. Does this always happen on your machine?
What trigger are you using to open the Clipboard Manager?

**Comment by MeteC** [comment]
Yep has always happened to me on both Macbook Pro and iMac - the trigger I use is to double-click the main menubar. (Awesome feature by the way!)

**Comment by fifafu** [comment]
I can reproduce it when using this trigger :-)
(I mostly use the clipboard manager with a keyboard trigger so I never noticed).

Will fix it with the next update.

**Comment by MeteC** [comment]
😸 👏
