### ISSUE TITLE
Lock Screen Shortcut Slow

### ISSUE THREAD

**Issue by blissrage** [fifafu/BetterTouchTool#2072]
Hi, using High Sierra 10.13.3 and noticed the Lock Screen shortcut is very slow. It takes on average about 6-10 seconds to lock screen. Co-workers on similar boxes do not report this issue.

I have tried a few different keyboard maps to ensure it's not some kind of macro collision. Any hints or things to try?

I've tried ```Com+Ctrl+Q```, ```Comm+Opt+Q```, ```Comm+Opt+Ctrl+L``` . . . and so on.

Thanks much.

**Comment by fifafu** [comment]
I don't know, probably some app causes macOS to delay the lock?
The cmd+ctrl+Q shortcut is a native macOS shortcut, so this is probably not related to BTT.

**Comment by blissrage** [comment]
thanks much. i will tinker with other components. awesome tool btw.
