### ISSUE TITLE
Touchbar custom button URL : blank page

### ISSUE THREAD

**Issue by airguillaume** [fifafu/BetterTouchTool#2073]
Good evening :). I did search into the issues but couldn't find a related issue.

---

#### Description of bug/feature request/question:
When adding a shortcut to a webpage, when clicking it opens a blank page instead of the saved URL. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 15" 2017
macOS version: 10.13.3 (17D47)
BetterTouchTool version:  2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Sometimes it works, sometimes it doesn't ^^'

**Comment by fifafu** [comment]
seems to work fine here, do you have the http:// part included in your url? (that's important)
