### ISSUE TITLE
keystroke re-mapping gestures sometimes not re-mapped (v2.340)

### ISSUE THREAD

**Issue by gsisson** [fifafu/BetterTouchTool#2074]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi Andreas.  Thanks so much for your wonderfully useful product!   I really couldn't live without it!

OK, I just started seeing this problem this morning in version 2.340 that just got installed.   First, some background:  I make heavy use of BTT to "translate" keystrokes when in Outlook (and other apps, but the problem I'm seeing right now is in Outlook).   I have many keystrokes "translated", for example, I translate ^F to move the cursor forward (as it does in emacs, and the readline library).  But, just today with the latest BTT, v2.340, I noticed that my past usage pattern of holding down ^F to send multiple commands and move the cursor forward quickly, will only move the cursor a few times, and then the ^F gets captured by Outlook and I suddenly see Outlook's "Find and Replace" dialog box pop up unexpectedly.   So, it would seem that not all the ^F characters are getting captured by BTT... some are getting past BTT and into Outlook directly.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MacBookPro mid-2015
macOS version: High Sierra 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Some details on my BTT settings...  the BTT gesture in question is a keyboard gesture, and set up as "^F (trigger on key-down)" and it is assigned to the arrow-right key (to move the cursor to the right).   Also, let me note that my Mac Keyboard settings have the "Key Repeat" rate set to maximum.   But, in BTT I have set they keyboard rate to something slower.   I THINK I remember editing some sort of "repeat rate" in BTT (long ago), but I cannot see where in BTT that is configured right now :-(.   I remember that I had to set the repeat rate in BTT to a lower speed than the Mac Keyboard rate setting, because if I did not, then holding down a key would not send all the keystrokes.  I wish I remember more about that setting, but I don't remember.   Anyway, I mention it now since it may have some relation to this problem here.

Thanks again for a great product Andreas!

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by gsisson** [comment]
Glad you were able to reproduce.   I downgraded to 2.332 which seems to have fixed it for now.  Thanks.

**Comment by fifafu** [comment]
It should work again in v2.341 alpha, however this alpha is quite experimental as I have rewritten most parts of the keyboard handling (you can now also use the fn key in shortcuts)

Downgrading is easily possible if it doesn't work.

**Comment by gsisson** [comment]
Thanks Andreas.  I didn't see this until now, but I see your 4.0 version is out in "release" form, so I am using it now.   I haven't seen the problem, so I guess you fixed it.  Thanks!
