### ISSUE TITLE
Curly quotes typed in Shell script window

### ISSUE THREAD

**Issue by bobstern** [fifafu/BetterTouchTool#2077]
Bug:  If I type a shell script directly in BTT's shell script window, typing a single or double quote produces a curly quote, which then causes a script syntax error.

Workaround is to type the script in a text editor (with straight quotes) and paste it into BTT.

MacOS 10.12.6.

**Comment by waxfingers** [comment]
Cannot reproduce in 10.13.3 
Do you have smart quotes turned off?  
![quotes2_web](https://user-images.githubusercontent.com/13238340/36027556-b6d02992-0d93-11e8-9b5d-77c45cc95ffd.jpg)
![quotes1_web](https://user-images.githubusercontent.com/13238340/36027557-bb929de8-0d93-11e8-81ff-7b404c03fa72.jpg)

**Comment by bobstern** [comment]
Thanks, that was it.  Sorry for my dumb error.

**Comment by ariofrio** [comment]
This should be disabled by BetterTouchTool on it's code editor.

Smart quotes is useful in other apps.

**Comment by bobstern** [comment]
@ariofrio:  Why are you averse to disabling system-wide smart quotes in OS X prefs?  Word processors and mail clients generally provide their own smart quote feature, and smart quotes do not seem useful elsewhere.

**Comment by ariofrio** [comment]
Thanks for recommending that.

I tried that and it looks like e.g. Apple Mail and Bear Notes doesn't have smart quotes apart from the native ones, as this email demonstrates: "testing".

In general, it seems that BetterTouchTool’s script editor should work out-of-the-box, without having to modify a default system setting.

But the main reason is that it conflicts with other app’s functionality like Apple Mail and Bear Notes.
