### ISSUE TITLE
Shortcuts does not work with MICROSOFT Remote Desktop APP

### ISSUE THREAD

**Issue by kktmp1** [fifafu/BetterTouchTool#2078]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Shortcuts does not work with Microsoft Remote Desktop
- cmd+v   map to CTRL-v
- insert text (paste o type)

Also try with complex actions: using modifier keys, Press CTRL, delay, press V, and then up CTRL

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard shorcuts

#### Device information:

Type of Mac:
  Nombre del modelo:	MacBook Pro (15'', 2016)
  Identificador del modelo:	MacBookPro13,3
  Nombre del procesador:	Intel Core i7
  Velocidad del procesador:	2,7 GHz

macOS version:  High Sierra 10.13.3
BetterTouchTool version:  2.340 (719)
same with previous versions of BT

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Yep, unfortunately remote desktop doesn't handle keyboard events correctly. There may be a workaround soon. See #121
