### ISSUE TITLE
Shell Script - Alternate color flapping

### ISSUE THREAD

**Issue by blastik** [fifafu/BetterTouchTool#2079]
#### Description of bug/feature request/question:

I have the following functions as a shell script to report the latest BTC prices and the 24H change:

-------

function getTicker() {
  curl -s "https://api.coinmarketcap.com/v1/ticker/$1/?convert=EUR"  | tr -d '{}"[]' | tr ':,' '\n' | awk '/price_eur/{getline; print}' | cut -d '.' -f1
}
function change24H() {
  curl -s "https://api.coinmarketcap.com/v1/ticker/$1/?convert=EUR"  | tr -d '{}"[]' | tr ':,' '\n' | awk '/percent_change_24h/{getline; print}' 
}

echo $(getTicker bitcoin)€ $(change24H bitcoin)

-----

Alternate color should come if this RegEx happens "-[0-9]" however the main color and the alternate are flapping even if the RegEx finds the "-" character, the alternate color SOMETIMES doesn't show. I've also tested with just "-" without luck.

Any ideas?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: Pro
macOS version:  10.13.3
BetterTouchTool version: 2.340

**Comment by fifafu** [comment]
Mh, I can't seem to be able to reproduce this. Are you sure the - is returned by the API?
How often does this happen?

**Comment by fifafu** [comment]
Is the widget in a group or on the main touchbar?

**Comment by blastik** [comment]
![image](https://user-images.githubusercontent.com/3662083/36152591-d3fc24ea-10cb-11e8-836f-d5d284ccb1c6.png)
updated very 60secs

**Comment by fifafu** [comment]
I think I may have found a potential issue that could cause this. I'm looking into it!

**Comment by blastik** [comment]
thanks for looking at it.
bear in mind that only SOMETIMES fail to show the red color. I dont know it's weird, it clearly works but quite often I find '-' symbol returned by the API and the color green.

**Comment by fifafu** [comment]
Would be great if you could check whether it works better with this version: https://boastr.net/releases/btt2.342.zip

**Comment by fifafu** [comment]
Sorry this is the correct link: https://bettertouchtool.net/releases/btt2.342.zip

**Comment by fifafu** [comment]
By the way, there is a great service to create these widgets for BTT: https://chrislennon.github.io/Crypto-Touchbar-App/

**Comment by blastik** [comment]
ok it works with the version you provided.
nice link, i didnt know it exists!

**Comment by jystic** [comment]
I had this problem too and the version provided also fixed it! thanks @fifafu
