### ISSUE TITLE
[2.340] Custom "Mission Control including Desktop Previews" sequence broken

### ISSUE THREAD

**Issue by Shnub** [fifafu/BetterTouchTool#2080]
#### Description of bug/feature request/question:

I am using a custom "Mission Control including Desktop Previews" sequence (the default one is too laggy for me).

![screen shot 2018-02-08 at 15 11 54](https://user-images.githubusercontent.com/29605254/35977120-836852d4-0ce2-11e8-913a-ba0cfcfe7d94.png)

This used to work very reliably. After updating to 2.340, I only get Mission Control without the previews. No amount of fiddling with values or the order of the items helps. Downgrading to 2.332 immediately restores functionality again. I am not sure which step is broken, but I suspect it has to do with the mouse moving. Invoking Mission Control alone works fine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse, trackpad, keyboard.

#### Device information:

Type of Mac: 2012 MBP 15"
macOS version: 10.12.6
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

–

**Comment by fifafu** [comment]
Due to another bugfix the mission control actions may be executed a few ms later as in previous versions. I assume you just need to update your values a little bit.

**Comment by Shnub** [comment]
I've tried 0.1, 0.5 and 1.0 seconds for all intervals. Nothing works. It seems somewhat erratic, but I believe the Mission Control command itself is often being executed _after_ the cursor movements (no matter the delays in between). Also, I often end up with the cursor in the top left corner when invoking a second time (to close Mission Control). And larger delays sometimes produce a beachball. I'm pretty sure there's more going on than just a timing error of a few ms.

**Comment by fifafu** [comment]
Does the BetterTouchTool action for this still work for you?

**Comment by Shnub** [comment]
Yes, with about a half-second delay before the previews are activated (as before, no change). Though not perfectly—I'd say in about 1 out 10 tries, the previews also don't open.

**Comment by fifafu** [comment]
I think I have identified the issue. It's a bit tricky but I think I'll have a workaround that keeps the fixes and your usecase with the next update.

**Comment by Shnub** [comment]
Cool. Thanks!

**Comment by zenkjn** [comment]
Hi there, I have been using this for High Sierra. Hope this helps. Basically, move your mouse to top before Mission Control action.

4 Finger Swipe UP | Save Current Mouse Position
--> Move mouse to X:50.00 Y:0.00
--> Mission Control
--> Delay next action by 0.01 seconds
--> Restore Saved Mouse Position

**Comment by TheOnlyRew** [comment]
I don't mean to wake up a solved issue, but I was surprised to find that the `mission control` action is performed after all others in a set rather than 'in order', as it were. I'm curious if this is know/expected behavior, or if it's surprising to anyone else.

The demonstration I came up with for my system is;

3 Finder Swipe Up | Save Current Mouse Position
--> Move mouse to X:800.00 Y:500.00
--> Delay next action by 1.00 seconds
--> Mission Control
--> Delay next action by 1.00 seconds
--> Move mouse to X:800.00 Y:0.00
--> Delay next action by 1.00 seconds
--> Restore Saved Mouse Position

Rather than activating Mission Control after one second, it's not until the full three delayed seconds have elapsed -- and after the mouse has been moved to 800x0 and then restored -- that Mission Control opens.

**Comment by fifafu** [comment]
@TheOnlyRew I think that was a bug, the current alpha versions should behave correctly.

**Comment by zenkjn** [comment]
@TheOnlyRew Just to confirm, I had the same issue. I’m using Alpha now.

**Comment by TechplexEngineer** [comment]
Thanks SOOO MUCH!

For reference this is what I have working:

<img width="570" alt="screen shot 2018-03-10 at 8 47 17 pm" src="https://user-images.githubusercontent.com/175873/37248594-3e46dd18-24a4-11e8-80af-13cf36d1cca9.png">

**Comment by Shnub** [comment]
I can confirm that my original workflow is working properly again in 2.400. Thank you!
