### ISSUE TITLE
under which circumstances would one use the Stop recording drawing/mouse gesture pre-defined action?

### ISSUE THREAD

**Issue by dorindon** [fifafu/BetterTouchTool#2081]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I use my own gestures/drawings and use the start recording action to trigger the gesture recognition. it all works fine.
under which circumstances would one use the Stop recording drawing/mouse gesture pre-defined action?
thank you

#### Device information:
 iMac Retina display late 2014, Magic Trackpad, Sierra and BTT latest version

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can e.g. configure BTT to start the drawing when pressing a mouse button DOWN and to stop it when releasing it. Same for keyboard shortcuts.

![image](https://user-images.githubusercontent.com/8820811/36027053-ed7ffd36-0d99-11e8-8102-28e36b91ddce.png)

**Comment by dorindon** [comment]
I am sorry, I don't understand.
I have successfully been using multiple drawings for actions for quite a while. My only trigger is a key sequence Ctrl twice to START recording  ➜  i do my gesture  ➜  the action is executed.
I never used STOP recording.
You seem to suggest that STOP recording should be needed? Since I don't I should be having problems?
Since one continuous drawing is necessary, should it not be that the recording stops when you take your finger off the trackpad?
A suggestion: I know a few people who quit using drawings because of the problem of triggering the recording. I suggest you encourage users to try key sequence first (I use Ctrl twice). It works like a charm.
The right mouse click option I do not find pleasant to use.
thank you for your reply

**Comment by dorindon** [comment]
I did not understand your reply, and left a follow-up question as per below:

https://github.com/fifafu/BetterTouchTool/issues/2081 <https://github.com/fifafu/BetterTouchTool/issues/2081> 

I am sorry, I don't understand.
I have successfully been using multiple drawings for actions for quite a while. My only trigger is a key sequence Ctrl twice to START recording ➜ i do my gesture ➜ the action is executed.
I never used STOP recording.
You seem to suggest that STOP recording should be needed? Since I don't I should be having problems?
Since one continuous drawing is necessary, should it not be that the recording stops when you take your finger off the trackpad?
A suggestion: I know a few people who quit using drawings because of the problem of triggering the recording. I suggest you encourage users to try key sequence first (I use Ctrl twice). It works like a charm.
The right mouse click option I do not find pleasant to use.




thank you for your reply

Jean Lette
jlette111@gmail.com

**Comment by fifafu** [comment]
No you don't need it if you use the trackpad or magic mouse because BTT will know when to stop the drawing (after you remove your finger from the trackpad). It's only necessary when using normal mice.

**Comment by dorindon** [comment]
thank you Andreas

Jean Lette
jlette111@gmail.com
