### ISSUE TITLE
Request: New Function: Eject External Hard drive

### ISSUE THREAD

**Issue by Askern** [fifafu/BetterTouchTool#2087]
I have several hard drives and usb sticks attached to my Mac. The fastest Method to I found for now to eject them all is to click on one hard drive shown on my desktop and to hit "alt + command + e" to eject all attached hard drives. But It would be nice and more fast to have a shortcut in BTT which does this. In this way I could eject all my hard drives and usb sticks very fast, put the cables out and move out with my Mac from the office.

Many thanks!!

**Comment by CarterVE** [comment]
You can do this by having a BTT touch bar button which executes the following terminal script!

`osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'`

**Comment by Askern** [comment]
Thank you! I made an Apple Script and put them to the services and assigned them a shortcut.

Other interesting source regarding this topic: https://apple.stackexchange.com/questions/129020/ejecting-all-network-drives-via-applescript-automator-shell?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
