### ISSUE TITLE
question concerning triggering recording of drawings with 'enable right mouse drawing recognition, after mouse moved'

### ISSUE THREAD

**Issue by dorindon** [fifafu/BetterTouchTool#2088]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Concerning the right mouse click to trigger drawing recognition as per the image below, how do I emulate this gesture on a trackpad? . I  tried 2 finger tap, and all variations possible, and could not make it work. Could you describe what gesture you use? I don’t understand what is meant by enable right mouse down (=double tap on trackpad) after mouse moved.

thanks very much !

![image](https://user-images.githubusercontent.com/30017084/36025429-535e537a-0d93-11e8-8386-41dc9953a74a.png)

#### Device information:
 iMac Retina display late 2014, Magic Trackpad, Sierra and BTT latest version
Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you already looked at the "Using the gestures" part of https://docs.bettertouchtool.net/docs/drawings.html ?

The right-mouse down drawing on the trackpad can only be used by clicking the trackpad and moving the fingers while keeping it clicked. However this is only one of many possible ways to activate the drawing screen and is more suited for normal mice.

**Comment by dorindon** [comment]
Now I understand. Yes I had read it before asking you, but could not
understand it.
thanks very much

Jean Lette
jlette111@gmail.com
