### ISSUE TITLE
Placing BTT Button on control strip's right side instead of left

### ISSUE THREAD

**Issue by andresberrios** [fifafu/BetterTouchTool#2089]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Thanks for all the great work!
I've been configuring the touch bar customizations and I would love to be able to control where in the control strip the BTT button gets placed. Right now the checkbox to enable it always puts it on the leftmost position, and I haven't been able to find a way to move it.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://user-images.githubusercontent.com/3658101/36048995-77ff907e-0de1-11e8-8f51-4d4bd5321efc.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is not possible because there is no API that would allow me to place it somewhere else.
