### ISSUE TITLE
ForceTouch Trackpad freezes

### ISSUE THREAD

**Issue by Sverkel** [fifafu/BetterTouchTool#209]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
In BTT I have made a Global shortcut on the ForceTouch Trackpad that is set to "empty trash" when I swipe 4 fingers from the right and it's works fine until the panel that asks me to empty or cancel comes up, then the ForceTouch Trackpad freezes completely and I can't do anything unless I click on the TouchBar or hit ESC. If I do the same command just with the keyboard shortcut build in to Mac OS the ForceTouch Trackpad works just fine. 

**What kind of Mac are you using?**
MacBook Pro Retina 13" 2016 with TouchBar.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Pro ForceTouch Trackpad.

**Which versions of macOS and BetterTouchTool are you running?**
Mac OS Sierra version 10.12.2 (16C67)
BetterTouchTool version 1.97 (561)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Fixed with 2.15 alpha (will be released later today)
