### ISSUE TITLE
Keyboard Backwards Delete Action no Longer Works

### ISSUE THREAD

**Issue by proactivematter** [fifafu/BetterTouchTool#2090]
#### Description of bug/feature request/question:

I had programmed **Shift + Backspace** to act as **Del** (trigger on key down/repeat while pressed), and it was working fine up until this latest update. Now it works for half a second, and then reverts to **Backspace** or keeps alternating between **Backspace** and **Del**.

Many thanks!

#### Affected input device

Keyboard

#### Device information:

Type of Mac: Macbook Pro 2017 15"
macOS version: 10.13.3
BetterTouchTool version: 2.340

**Comment by fifafu** [comment]
Sorry for this bug.
I'm currently rewriting the complete shortcut & keyboard handling to make it more flexible. This will include a fix for this. I think an alpha version with the new shortcut handling will be available sometime tomorrow.

For now you could downgrade to the previous version (https://boastr.net/releases)

**Comment by proactivematter** [comment]
OK! Thank you!

**Comment by fifafu** [comment]
It should work again in v2.341 alpha, however this alpha is quite experimental as I have rewritten most parts of the keyboard handling (you can now also use the fn key in shortcuts)

Downgrading is easily possible if it doesn't work.

**Comment by proactivematter** [comment]
Solved in v2.402 (753)! Thank you @fifafu !
