### ISSUE TITLE
Remapping orange button to CMD+H and hide last window

### ISSUE THREAD

**Issue by Forturio** [fifafu/BetterTouchTool#2093]
#### Description of bug/feature request/question:
I have remapping orange button from minimization to hide CMD+H.

1.  Open for example two applications. Finder and Safari
2. Click to orange button Finder... OK, window is hide.
3. Click to orange button Safari.... Function hide is unavailable

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro trackpad and keyboard

#### Device information:

Type of Mac: MacBook Pro 2017
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
**Set Rule**
<img width="1012" alt="screen shot 2018-02-10 at 10 44 49" src="https://user-images.githubusercontent.com/22738473/36060816-09e6efcc-0e51-11e8-8dde-3df3d894873a.png">

**The window can not be hidden**
<img width="551" alt="screen shot 2018-02-10 at 10 46 41" src="https://user-images.githubusercontent.com/22738473/36060843-80ada1aa-0e51-11e8-803b-c752557aa4a5.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro trackpad and keyboard

#### Device information:

Type of Mac: MacBook Pro 2017
macOS version: 10.13.3
BetterTouchTool version: 2.340

**Comment by fifafu** [comment]
Unfortunately that's a limitation in macOS. I don't know why it's there but you should report it to Apple. I think I can't change that behavior in BTT unfortunately.
