### ISSUE TITLE
Hide All Windows possible bug

### ISSUE THREAD

**Issue by yaseent** [fifafu/BetterTouchTool#2096]
Hi,

I'm not sure if this is a bug at all, or intended behaviour.

#### Description of bug/feature request/question:
I use the Hide All Windows function in BTT.  Sometimes I'll have a Finder window open, with multiple folders opened as tabs.

When using the Hide All Windows function, it hides every one of my apps - which is perfect. But if I was to double click a folder on the desktop after doing this, it opens as a completely new window in Finder - and it does not attach itself to the Finder window that already had multiple folder tabs opened.

Furthermore, the Finder that did have multiple folder tabs, is nowhere to be found. Clicking on "Window"in the menubar only shows the newly opened folder of the newly opened Finder window.

I can minimize this new window, and when I click the Finder icon in the dock, it brings up only this new window.

If however I close the new window, then launch Finder again, the window that had the multiple folder tabs shows up, restored completely, with all the tabs there.

Please help :)

#### Device information:

Type of Mac: Mac mini (Late 2014) OSX 10.13.3 / MacBook Air (13-inch, Early 2015)
macOS version: 10.13.3  / 10.13.3 
BetterTouchTool version: 2.3

---

Thanks

**Comment by yaseent** [comment]
I was able to resolve this issue by going into BTT Advanced Settings >> Predefined Action Settings and right at the bottom setting the Hide all Windows Behaviour to:
Hide All Normal Windows, Minimize Finder Windows.

Sorry :/

**Comment by fifafu** [comment]
I think the new alpha v2.341 has an even better solution to actually hide all windows :-)

**Comment by yaseent** [comment]
@fifafu Please share please share
