### ISSUE TITLE
Feature request: ability to use any key on keyboard as a predefined action

### ISSUE THREAD

**Issue by oursu** [fifafu/BetterTouchTool#21]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I want to be able to press "Enter", "Delete", etc., using a keyboard shortcut. 
I know this seems strange, but I am using these keyboard shortcuts as inputs to the Apple Dictation software, and the built-in define command has issues with "Delete".

**What kind of Mac are you using?**
Macbook Pro 

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Keyboard

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi!
Doesn't it work to just record those keys in the "trigger other keyboard shortcut" field?
<img width="1127" alt="record_delete" src="https://cloud.githubusercontent.com/assets/8820811/20936382/b663dbce-bbe2-11e6-9bc9-bb6339c565b4.png">
