### ISSUE TITLE
Moving Spaces with Normal Mouse Shortcuts doesn't work

### ISSUE THREAD

**Issue by kevin-highmark** [fifafu/BetterTouchTool#2100]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I have my normal mouse setup with ^+Scroll Left and ^+Scroll Right for moving spaces left and right, it doesn't move the space. I have keyboard shortcuts set up and it works fine, but not for normal mouse. See screenshot below. Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal Mouse

#### Device information:

Type of Mac: MacBook Pro 13 inch 2016 no touchbar
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1012" alt="screen shot 2018-02-11 at 10 22 30 pm" src="https://user-images.githubusercontent.com/34074130/36084496-17c808da-0f7b-11e8-8c90-4cf6f14f593f.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by kevin-highmark** [comment]
Never mind, I had logitech options installed. For anyone else who has this problem, uninstall your logitech options software.

**Comment by fifafu** [comment]
Ah thanks for letting me know. I was trying to reproduce it but couldn't.

I'll try to figure out why it doesn't work with Logitech options.
