### ISSUE TITLE
just ran today's update (12feb), and my safari custom shortcuts are not working (or they work once); i redid the settings, but no change (have not yet rebooted, am in the middle of something)...

### ISSUE THREAD

**Issue by fKing** [fifafu/BetterTouchTool#2103]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Definitely possible as todays alpha contains a complete rewrite of the keyboard /shortcut functionality. 
What kind of shortcuts are you using in Safari? (If possible go to manage presets => export and attach the json here, unless it contains private data)

**Comment by fKing** [comment]
12" 2016 macbook, 10.13.4 pb2, BTT 2.341

**Comment by fKing** [comment]
right now, it's just this, in safari:  option-back arrow for cmmnd-shift-[ and the reverse)

**Comment by fifafu** [comment]
mh it seems to work correctly here but there could be various potential issues.
Is BTT still enabled in System Preferences => Security & Privacy => Accessibility ? (it sometimes gets reset on the current macOS version)

**Comment by fKing** [comment]
the privacy setting is still checked. i undid/redid those custom settings; once, the tab switched. but that's it. this has only happened in today's update...

**Comment by fifafu** [comment]
Ok, I'll investigate. 
If you have time it'd be great if you'd go to the about tab in BTT and click the export debug info button. This will create a folder called BetterTouchToolDebug - please send to boastr.net@gmail.com

Thanks for reporting! For now downgrading is probably the best option while I collect more data: https://bettertouchtool.net/releases/btt2.340.zip

Are you using any other keyboard shortcuts in BTT, or only Safari?

**Comment by fKing** [comment]
all good, files sent. right now, that's the ONLY shortcuts i'm using (and only in safari)..

**Comment by fifafu** [comment]
Unfortunately I haven't had similar reports yet and was unable to reproduce it even with your debug info :-(

If possible it would be great if you'd try whether it works when you don't assign keyboard shortcuts, but instead use the "Trigger Menubar Menu-Item" predefined action like this:

![image](https://user-images.githubusercontent.com/8820811/36151581-0c51b05c-10c8-11e8-9780-3ed04059b8a3.png)

This would clarify whether the problem is "recognizing the shortcut" or "sending the shortcut"

**Comment by fKing** [comment]
just updated the app, then got this email. then realized i'd probably just updated to the version that's NOT working for me?
am trying, in this version, to do what you've suggested. should there be NO data in the "trigger other keyboard shortcut"? and only in the other window? i've done this, but... not working. (see attached).
meanwhile, will again reinstall the previous version...
thx!



    On Tuesday, February 13, 2018, 8:14:14 AM EST, Andreas Hegenberg <notifications@github.com> wrote:  
 
 
Unfortunately I haven't had similar reports yet and was unable to reproduce it even with your debug info :-(

If possible it would be great if you'd try whether it works when you don't assign keyboard shortcuts, but instead use the "Trigger Menubar Menu-Item" predefined action like this:



This would clarify whether the problem is "recognizing the shortcut" or "sending the shortcut"

**Comment by fKing** [comment]
here's some useful info; on the previous version (2.340) this works (the 'trigger predefined action") with NO data in the "trigger other keyboard shortcut' window.

but neither method working on the latest BTT with either option (on my mac, at least).

**Comment by fifafu** [comment]
Hi fKing,

has anything changed in v2.344? I haven't had any other report about non-working shortcuts but I made some adjustments with 2.343 and 2.344.

Best,
Andreas

**Comment by fKing** [comment]
andreas,
seems fine...
thanks for all,
floyd
    On Tuesday, February 27, 2018, 8:10:38 AM EST, Andreas Hegenberg <notifications@github.com> wrote:  
 
 
Hi fKing,

has anything changed in v2.344? I haven't had any other report about non-working shortcuts but I made some adjustments with 2.343 and 2.344.

Best,
Andreas

**Comment by fKing** [comment]
2.412 will occasionally just stop working; opening & closing the app itself restores functionality
