### ISSUE TITLE
Touchbar Slow to Respond

### ISSUE THREAD

**Issue by JuliaTruchsess** [fifafu/BetterTouchTool#2107]
I've programmed a bunch of custom touch bar buttons and find that they often don't respond to a moderately fast tap - sometimes I have to really rest a large part of my finger on it for a long time and/or hit it multiple times to get it to recognize the tap. At other times it is pretty responsive - maybe the variable is skin resistance or something. I understand that this is some kind of capacitive or resistive sensor and not a physical button, but if there's any way that the response sensitivity/time/reliability can be improved that'd be really nice.

Input: Touch Bar
Type of Mac: 2018 MacBook Pro 
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719)

**Comment by fifafu** [comment]
In general BTT can't influence this - it's using the default behavior from Apple.
However maybe the actions you configured take a moment to execute? Does this happen with all your buttons or just with some?

**Comment by JuliaTruchsess** [comment]
It's a "missed press" issue, not a delay after sensing; when I said "slow" I meant that it can't sense brief touches. All of the actions are application launcher/switchers. If the application is already open, the action is instant when recognized. I'm used to 100% success with my old MacBook and physical function keys so it's really annoying when I hit a touch bar key now and it doesn't respond.

**Comment by fifafu** [comment]
In this case I'm afraid I currently can't change the behavior. (In theory it's possible to get the raw touch data from the Touch Bar, but this would require a complete rewrite of the Touch Bar functionality in BTT and require lots of testing...).

**Comment by fifafu** [comment]
Maybe it would help to enable the haptic feedback option which let's your trackpad vibrate when you hit a BTT touchbar button:
![image](https://user-images.githubusercontent.com/8820811/36113323-b849d700-102c-11e8-9863-19851e66c764.png)

**Comment by JuliaTruchsess** [comment]
Interesting idea, but in practice my hand is nowhere near the trackpad when I press the touchbar, so I don't feel the feedback :) If the TB had haptic FB that'd be great!

**Comment by fifafu** [comment]
That's true, but at least it makes a little clicking noise :-)
I also hope the Touch Bar will get haptic feedback eventually...
