### ISSUE TITLE
Screen Sharing Keyboard Override?

### ISSUE THREAD

**Issue by paulmoons** [fifafu/BetterTouchTool#211]
I often have a Screen Sharing window open while I am working and if it is accidentally in focus some of my local shortcuts stop working until I refocus on a local app/finder - For me this primarily means, command+space is sent to the remote machine whereas I would like it to be used on the local machine, despite the focus.

I thought adding a BTT keyboard shortcut might override the Screen Sharing app but when I do so, it is greyed out so I can't select it to create the app specific shortcut I need.

Is there any way you to enable custom keyboard shortcuts to override Screen Sharing or is it greyed out because this is fundamentally not possible?

In any case, I would appreciate you consider adding custom shortcuts being available to Screen Sharing as I would find it very helpful. 

I am using a 2016 MacBook Pro with TouchBar on macOS 10.12.2 and BTT v1.963, FYI.

Thanks for writing, maintaining and keeping this app awesome. And reading through all these messages of course, too. :)

**Comment by fifafu** [comment]
New versions of BTT should allow you to select the app. If you still run into issues here, please let me know.

**Comment by paulmoons** [comment]
@fifafu Thanks, will do. :)
