### ISSUE TITLE
Many haptic options in Advanced (touchpad) do not work

### ISSUE THREAD

**Issue by ffxsam** [fifafu/BetterTouchTool#2110]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

In the Advanced > Trackpad > FORCE Touchpad section, most of the haptic feedback options don't work. Here's a list of the only options that work:

* Light Then Strong Feedback
* Spring Light Feedback
* Spring Strong Feedback
* Triple Strong Feedback
* Triple Light Feedback
* New BTT Default Click Release (can barely it)
* New BTT Default Normal Click
* New BTT Default ForceClick
* New BTT SILENT Normal Click (can barely feel it)
* New BTT SILENT ForceClick (can barely feel it)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2

#### Device information:

Type of Mac: Mac Pro Late 2013
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a known issue - it depends a bit on the trackpad model and machine used (all the haptic feedback is produced by completely undocumented API, so far I haven't found a way to make every option work on all trackpads the same).
