### ISSUE TITLE
[v2.341] Bug with Touch bar macro 

### ISSUE THREAD

**Issue by spiezer** [fifafu/BetterTouchTool#2111]
#### Description of bug/feature request/question:
I have touchbar macro that performs a set of actions in the app Numbers.
It issues a command-f command, pastes some text, tabs to the next entry, and pastes more text.
Prior to this version, the macro was working fine.  
After I updated, it seems to skip through all the steps and pastes the final text.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar.

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.13.4
BetterTouchTool version: 2.341 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="534" alt="screen shot 2018-02-14 at 8 48 05 am" src="https://user-images.githubusercontent.com/20282565/36207396-cbcd8848-1163-11e8-8242-69f916e75699.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Does this still happen in v2.344 alpha?

**Comment by spiezer** [comment]
I just tried to update to 2.344 but am getting the "error occurred while extracting the archive" problem.  I see a case has been closed for it so I'm not sure if it's a weird issue with my computer or internet.  I'll give it a shot when the update works.

**Comment by spiezer** [comment]
Thanks.  I just updated and I'm still getting the issue. It seems to paste all the words into the cell I select in numbers instead of finding the term and replacing it throughout the entire sheet.   

Here's what the macro looks like if that helps.
<img width="545" alt="screen shot 2018-02-27 at 8 22 55 am" src="https://user-images.githubusercontent.com/20282565/36731028-6d42c444-1b97-11e8-879d-ab0659a15af2.png">

**Comment by fifafu** [comment]
I can reproduce the issue. For some reason the delay action seems to destroy the order of the actions.

I'll check what's causing this!

**Comment by fifafu** [comment]
Could you try v2.345? For me it seems to work like this:

![image](https://user-images.githubusercontent.com/8820811/36777123-8ab4cf64-1c68-11e8-80e9-33ac463733d0.png)

I didn't even need the delays you added

**Comment by spiezer** [comment]
Great!  Looks like it works now.  I had the delays there since there was some lag when the windows were popping up.  Not really noticing them now so I might remove them.

Thanks!
