### ISSUE TITLE
BetterSnapTool: Spaces: Feature Request: Move to Next/Previous Space

### ISSUE THREAD

**Issue by ldriscoll** [fifafu/BetterTouchTool#2113]
#### Description of bug/feature request/question:

One of the features of BetterSnapTool that I see is that I am unable to bind the keyboard to snap a window between spaces.  Currently I am able to switch monitors, but not spaces.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: 2016 MBP
macOS version: Sierra
BetterTouchTool version:  N/A

**Comment by fifafu** [comment]
Unfortunately I can't do that in BetterSnapTool as it would require private API. However there is a feature to do that in my other app, BetterTouchTool (you can get a free license if you have bought bettersnaptool. Just download BTT and click the "get free license" button in the registration view)
