### ISSUE TITLE
Can't save a gesture Move Mouse to Bottom Right Corner

### ISSUE THREAD

**Issue by dmjlambert** [fifafu/BetterTouchTool#2114]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

As of version 2.340, when I attempt to create a gesture Move Mouse to Bottom Right Corner, the delay window pops up and I select the amount of time and click the save button, and the gesture remains to what it was set before.   I have restarted my system.  Screen shot attached.  Please let me know if I am just doing something incorrectly.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

N/A

#### Device information:

Type of Mac: MacBook 13 inch late 2009
macOS version: 10.13.1
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![screen shot 2018-02-14 at 10 15 51 am](https://user-images.githubusercontent.com/12522672/36215737-884387d0-1172-11e8-8793-a5bffe6f2f87.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi, Sorry this is fixed in the new alpha already. Will be included in the next public release
