### ISSUE TITLE
Right Click Red Window Button

### ISSUE THREAD

**Issue by yaseent** [fifafu/BetterTouchTool#2115]
#### Description of bug/feature request/question:

I use right clicking the red window button to perform Command+Q, so that which ever application this is done in, quits.

With the latest built, and only the latest build, sometimes it doesn't quit the app. Instead it immediately locks my Mac and I have to type a password to get in.

I can reproduce this issue easily by doing the following:

1. Install BTT 2.341

2. Open Google Chrome. Press Command + H to hide Google Chrome completely.

3. Then open Google Chrome (from your Dock or whatever).

4. Simply right click on anywhere inside the Chrome Window. Then left click anywhere to make the right click menu disappear.

5. Right click the Red close button.

This is happening on my Air and Mini

#### Device information:

Type of Mac: Man Mini 2014, MacBook Air 2015
macOS version: 10.13.3
BetterTouchTool version: 2.341

**Comment by fifafu** [comment]
I can't seem to reproduce this. Could you check whether this still happens with v2.344 alpha?

**Comment by yaseent** [comment]
I am having a very hard time reproducing this issue on > 2.340 :/

I guess it is resolved lol :P
Thanks!!
