### ISSUE TITLE
BTT Crashes OpenOffice Draw

### ISSUE THREAD

**Issue by yaseent** [fifafu/BetterTouchTool#2116]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Tested with Apache OpenOffice 4.1.3 and 4.1.5.

When trying to use OpenOffice Draw, just clicking on workspace crashes the app. The other modules don't seem to have the same issue, like Calc & Writer. There are no crash logs generated either.

Quitting BTT stops the crashes from happening.

I feel very bad for logging all these issues. Just as a side-note, I do not use OpenOffice Draw, just decided to give it a go. But I figured if it's affecting OpenOffice Draw, then maybe it may affect other apps. That is assuming the problem is with BTT, and not OpenOffice Draw itself. I tried checking OpenOffice forums for anyone having the same issue, but could not.

#### Device information:

Type of Mac: Mac Mini 
macOS version: 10.13.3
BetterTouchTool version: 2.341

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately it's an issue in open office. Disabling window snapping for open office should fix the issue.

**Comment by yaseent** [comment]
Hi,

thanks! Sorry did not know.
