### ISSUE TITLE
Execute Shell Script - what $PATH does BTT use?

### ISSUE THREAD

**Issue by GQnzo** [fifafu/BetterTouchTool#2117]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm trying to run some Python code using the Execute Shell Script predefined action. When I test the script the Traceback tells me the executable needs to be in PATH. This script works when I run it in terminal so I know the PATH is configured correctly. Is BTT using a different shell and or PATH? And... how do I set that PATH?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:

Type of Mac: MBP
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The path variable is only set in your standard shell. BTT doesn't have it.

You can try addimg "source ~/.profile && " before your command

**Comment by fifafu** [comment]
Or alternatively just use the absolute path to the tool you want to call (get it using which geckodrive)

**Comment by GQnzo** [comment]
I'm currently using this:
![image](https://user-images.githubusercontent.com/14081076/36268783-adbda050-1234-11e8-9b79-4af2082d7bf8.png)

Are you saying that I should try using Execute Terminal Command?

**Comment by fifafu** [comment]
In this case it may be hard to inject the $PATH, however I think you could set the path to the geckodriver manually:

driver = webdriver.Firefox(executable_path=r'your\path\geckodriver.exe')

**Comment by GQnzo** [comment]
That worked! Thank you so much.
