### ISSUE TITLE
NSSQLiteErrorDomain error 8 popup after macOS restore

### ISSUE THREAD

**Issue by paulanthonyjacobs** [fifafu/BetterTouchTool#2118]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

MacBook went in for repair. Wiped and restored from TimeMachine backup on return. Now BTT constantly pops up with a dialogue containing the message:

The operation couldn't be completed.
(NSSQLiteErrorDomain error 8.)

![screen shot 2018-02-15 at 11 12 40](https://user-images.githubusercontent.com/12054648/36247039-79e3b788-1243-11e8-9e2f-5cebf6cc5935.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

N/A

#### Device information:

Type of Mac: MacBook Pro Late 2013
macOS version: 10.13.3
BetterTouchTool version: 2.34

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Have deleted accompanying AppStore copy of BetterSnapTool on which license for BTT was acquired, but can't remember when (before/after restore).

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's probably a file permission error (BTT can't write to its data file).

You can either repair the permissions in ~/Library/Application Support/BetterTouchTool manually or try to do a safe boot (which according to Apple will repair permissions).

Apple also has an article about fixing permissions here: https://support.apple.com/en-us/HT203538
However I haven't tried it yet.

**Comment by paulanthonyjacobs** [comment]
You can delete the word 'probably' in your first sentence. Thanks! I followed the steps in the apple link and it seems to be fine again.

**Comment by fifafu** [comment]
Awesome! Thanks for letting me know.
