### ISSUE TITLE
Window positions resetting when hibernating

### ISSUE THREAD

**Issue by johngb** [fifafu/BetterTouchTool#212]
Window positions don't seem to be saved with BetterSnapTool between hibernating and restarting. This has been ongoing for a few years.  I'd like a option to persist the saved window positions, or be able to reapply the last saved positions via a menu option or keystroke.

Mac kind: MacBook Pro (Retina, 15-inch, Mid 2014)
Input device: Inbuilt trackpad
OS version: 10.11.16
Monitor: Laptop screen + external Thunderbolt monitor (not mirrored)

**Comment by fifafu** [comment]
Hi,

in general window positions should stay the same unless you connect/disconnect displays. 
Also it's a system issue, not directly related to BetterTouchTool / BetterSnapTool. Apple improved this behavior with macOS 10.12.
