### ISSUE TITLE
How to trigger icon based system menus ?

### ISSUE THREAD

**Issue by erikrob** [fifafu/BetterTouchTool#2124]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi. On the OSX menu bar there are tons of app/utility icons in the system menu bar (the same one that contains the apple menu) on the right hand side. How do you trigger menu items in those menus ? So far I've been using BTT's feature 'Menubar-Item' that triggers menu items based on the menu name path such as 'File;Open' but how do you do something similar for those icon based menus ?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:
Non relevant

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Attached screenshot where I highlighted in red the item I wold like to trigger.
![screen shot 2018-02-17 at 14 28 12](https://user-images.githubusercontent.com/1157544/36341470-25b41cb8-13ef-11e8-8503-3ba8abdf43ec.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately there is no real way to do that (there is no api and no standard for menubar extras).

The only more or less reliable way seems to be to record what you want to do with Apples Automator app and then use the automator predefined action in BTT to trigger the workflow.

Alternatively you can setup a sequence of clicks in BTT.

**Comment by ben8kenobi** [comment]
macOS appears to have a default keyboard shortcut for accessing the [Status menu](https://support.apple.com/en-us/HT201956), as they call it, which is Control-F8. Note that if you have an Apple keyboard with auxiliary functions enabled (brightness/volume controls, etc.) this keyboard shortcut becomes Control-Fn-F8, where "Fn" is the function key typically located in the bottom left of an Apple keyboard.

Anyway, choose a gesture and assign it the keyboard shortcut Control-F8. This will give focus to the Status menu. From here, you can attach additional actions to that same gesture like the arrow keys to move between Status menu icons or menus of Status menu icons.

For example, I assigned the following actions all to one gesture:
1. Control-F8 - this puts focus on the Status menu's first icon
2. down arrow key - this opens the focused Status menu icon's menu
3. down arrow key - this highlights the first item of the menu
4. down arrow key - this highlights the second item of the menu
5. enter/return - this activates the highlighted menu item

Specifically this was used for the screen-tinting app Flux (now replaced by macOS functionality called Night Shift). It would focus/highlight the Flux icon in the Status menu, reveal its drop-down menu, move down two selections, and select (enter/return) the Preferences menu item for the app.

Unfortunately, not all icons in the Status menu are accessible. BetterTouchTool itself is actually not focusable/highlightable (on my system, at least). Google's Backup & Sync is another, macOS's Spotlight magnifying glass icon, Siri's icon, and the Notification Center icon are all unavailable to traverse with the keyboard once the Status menu has focus.

It's difficult for me to be concise, but I hope this helps! It worked pretty well for me. Best of luck!
