### ISSUE TITLE
Maximize Window Left/Right now uses thirds instead of halves

### ISSUE THREAD

**Issue by mcamou** [fifafu/BetterTouchTool#2125]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

At some point during the last months, the behavior of "Maximize Window Left" and "Maximize Window Right" changed. It is now identical to "Resize Window to Left Third" and "Resize Window to Right Third".

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

In my case I have the laptop screen and 2 additional monitors. This is happening on all three.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You may have changed the percentage here: 
![image](https://user-images.githubusercontent.com/8820811/36370786-410543da-1560-11e8-967c-ce59a75440bb.png)

**Comment by mcamou** [comment]
Great! That did it. No idea when I changed it. but thanks!
