### ISSUE TITLE
Silently crashes

### ISSUE THREAD

**Issue by starblastresearch** [fifafu/BetterTouchTool#2127]
I find it very often that I open the lid and the BTT is not running. I connect my mac to an external monitor very often and I think I saw some post online that mentioned an issue with BTT when using multiple monitors. Any idea how to diagnose this issue and fix it?

**Comment by starblastresearch** [comment]
Isn't anyone experiencing the same thing? I am sure there should be some people out there who have to restart ut multiple times a day

**Comment by fifafu** [comment]
I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem with the latest version of BTT, please create a new issue - I'm now much more responsive than a few months ago.
