### ISSUE TITLE
Feature request: Move Window to Previous Monitor /  Move Window to Monitor X

### ISSUE THREAD

**Issue by TheBloke** [fifafu/BetterTouchTool#2128]
#### Description of feature request:

I have four displays, and would like ability to move windows to any monitor.

Currently we have **Move Window To Next Monitor**.  At the least, it would be great to also have **Move Window To Previous Monitor**.

But ideally it would be great to have **Move Window To Monitor X**, which takes a parameter for a monitor number.   This would use macOS' Displays setting, from left to right (ie leftmost monitor is monitor 1).  

For example I often want to move windows to my primary display, which is 4K @ 3840x2160.  Sometimes this would be Next monitor, sometimes Previous.  But if I could have **Move Window To Monitor 3**, I could use the same gesture always for this common case.

Thanks very much.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

**Comment by bryansteiner** [comment]
This feature would be great!

**Comment by igorwojda** [comment]
I completely agree all next tasks should have prev counterpart

**Comment by fifafu** [comment]
I'll probably add this soon. Continue to track this here: #514
