### ISSUE TITLE
Question(s) about touch bar implementations

### ISSUE THREAD

**Issue by Eroxx** [fifafu/BetterTouchTool#213]
#### Description of your bug/question/feature request...:

1) Is it possible (or could it be possible) for global touch bar icons to be placed to the right of whatever standard icons are implemented from within the source app? As an example, I have a BTT touch bar shortcut for safari. Could I have that shown to the right of all of the other safari shortcuts that are standard?

2) Is it possible to create touch bar "palettes" so that a user could tap that and it would open up a specific set of other shortcuts?

**What kind of Mac are you using?**

15" MacBook Pro w/ Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**

10.12.2 and latest (non-alpa) version

**Comment by Eroxx** [comment]
Edit/Suggestion:

Regarding issue 1: 

One thing that might work if Mac OS prevents one from adding touch bar shortcuts on the left side, is it possible to add specific items to the OS strip on the right, other than the general BTT one?

**Comment by pallavmac** [comment]
That would be amazing!

**Comment by fifafu** [comment]
@Eroxx 1.) is not possible due to API restrictions. (Can't modify an existing Touch Bar and can't add things to the Control Strip apart from the BTT icon)

2.) Is now available using the groups feature!
