### ISSUE TITLE
Ctrl + Key cause delay in cursor

### ISSUE THREAD

**Issue by yaseent** [fifafu/BetterTouchTool#2132]
#### Description of bug/feature request/question:

I've added the following keyboard shortcut:

CTRL + V = ⌥⇧⌘V

Basically this turns Ctrl + V into OSX paste without formating.

The problem I'm facing however is that when I use Ctrl + V, it seems to causes some sort of delay with the cursor being availble immediately after the paste.

So what happens is, if I immediately start tpying after the ctrl+v paste, whatever I type sort of doesn't have any output. Whether it's hitting enter, or a space, or whatever else.

#### Device information:

Type of Mac: MacBook Air (13-inch, Early 2015)
macOS version: 10.13.3 (17D47)
BetterTouchTool version: 2.341

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I've done a screen record and uploaded the video here:
https://www.youtube.com/watch?v=P5XviNXrjqQ

I've  uploaded here as well:
https://www.dropbox.com/s/iwui79vghbiuo2u/screenrecord.mov?dl=0

**Comment by yaseent** [comment]
Just an update,

I reinstalled version 2.340 and what a difference that made. Absolutely no delay whatsoever, it goes to a new line after every paste hitting Enter. I think 2.341 has a strange lag problem.

**Comment by yaseent** [comment]
Hi 2.343 seems to resolve this issue.

**Comment by fifafu** [comment]
Ah cool, thanks for letting me know! If it happens again, please reopen.
