### ISSUE TITLE
Notes field in keyboard tab

### ISSUE THREAD

**Issue by olliebaum** [fifafu/BetterTouchTool#2136]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'd like a notes field in the keyboard tab. It's useful for labelling my BTT actions.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by TheBloke** [comment]
It's already there - maybe you need to resize the window?

[Screenshot](https://i.imgur.com/XqrwMlg.png)

**Comment by olliebaum** [comment]
Ah, sorry! I couldn't see it there. I had my assigned actions field
stretched out too much which meant I couldn't see it. Thanks for the fix
though. :P
