### ISSUE TITLE
Request: App-wide settings export / over-the-air synching of settings?

### ISSUE THREAD

**Issue by eggplantsplz** [fifafu/BetterTouchTool#214]
## _feature request_

Wondering if there are plans for some sort of account-wide personalized settings synching? Perhaps through iCloud if the app could access the API? The current export function, from what I can tell, doesn't sync app-wide settings including individual settings in 'advanced' such as tap sensitivities and delay timings. 

I imagine this would be super helpful for those who utilize BTT on multiple machines; as I have recently begun to do (workstation Mac Pro, personal MBP). 

Thanks in advance!

**Comment by kigster** [comment]
In the meantime, I tried copying the following two files to another computer, hoping to transfer the settings:

```bash
cd ~/
tar cvf ~/Dropbox/BetterSnapTool.tar \
   Library/Application\ Support/BetterSnapTool  \
   Library/Preferences/com.hegenberg.BetterSnapTool.plist
```

and then on the destination computer:

```bash
cd ~/
tar xvf ~/Dropbox/BetterSnapTool.tar 
```

Unfortunately, when I launch BetterSnapTool on the destination computer, it has zero keyboard shortcuts and all my settings are not active.

Is there another file, perhaps, that I need to copy? 

Any help on this is much appreciated.

Sync to DropBox would be amazing, but starting with the simple settings file export/import would probably satisfy 90% of users wanting to replicate their settings across multiple computers.

Thanks again for building this awesome tool.  I've used them all (ShiftIt, SizeUp, etc) and your tool by far beats them all. I purchased a family license, and couldn't be happier.

:)

**Comment by fifafu** [comment]
I think you may be missing the tilde before the Library paths.
It is ~/Library/Application Support/BetterSnapTool and ~/Library/Preferences/com.hegenberg.BetterSnapTool.plist 

Dropbox sync is very soon coming to BetterTouchTool, probably this or next weekend  (you should try the latest alpha version 2.084 which has significantly improved window snapping animations). Bettersnaptool users can register BetterTouchTool for free.

**Comment by kigster** [comment]
Well, I was doing `cd ~/` before the `tar`, hence no need for ~/.  I usually do that so that I don't end up with absolute paths in tar archive, that's meant to be unpacked on another machine :)

**Comment by fifafu** [comment]
Ah sorry I missed that.
Those are however the only two files, so if they are placed correctly (while BetterSnapTool is quit) you definitely get the settings from the other machine.

Maybe Bettersnaptool was still running?

**Comment by dougpagani** [comment]
If snap tool is running, its atomic-write (.sUmwe1rdStRInG) will over-write upon app-exit. This is the same problem for synching virtually any app's data using a launchAgent, dropbox, manually, etc.

**Comment by kigster** [comment]
Just for the record, copying the two files I mentioned above does work.

**Comment by fifafu** [comment]
Dropbox sync is integrated in current versions of BTT (in the advanced settings)

**Comment by kigster** [comment]
Thank you!!!!
