### ISSUE TITLE
Add F keys to Touch Bar

### ISSUE THREAD

**Issue by mmh-docufy-de** [fifafu/BetterTouchTool#2147]
#### Description of bug/feature request/question:

My initial testing with BTT and Touch Bar leads me to the conclusion that the Touch Bar consists of two areas: Control Strip and application features. And that BTT is able to replace the application features with a set of custom defined features.

I am looking to add custom buttons to the existing application features.

I want to use application specific F keys without having to hold the Fn key, and I was hoping to add some of them to the Touch Bar without losing (or having to re-create) all application features. 
My initial use case are Mail Act-on F key shortcuts added to Apple Mail's Touch Bar features. (I already configured some for Mail as a custom Touch Bar segment.) Is or would that be an option?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13
BetterTouchTool version: 2.340

**Comment by fifafu** [comment]
No that's not possible.
BTT can only replace, not extend application specific touchbars.
