### ISSUE TITLE
Update Touch Bar Script Widget on button press

### ISSUE THREAD

**Issue by SenshiSentou** [fifafu/BetterTouchTool#2148]
#### Description of bug/feature request/question:
Touch Bar Script Widgets can update every X seconds, but seem to be limited to this. It would be great if they could also update whenever they're pressed (preferably after their associated action has been completed).

The use case that prompted this question is a custom Play/ Pause button. There's really no need to check every second e.g., but it does feel very unresponsive at the moment.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.12.6
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
N/A

**Comment by CarterVE** [comment]
You can attach the play/pause functionality as an additional action (bottom right next to "+ Button Group", and then make the main predefined action "Run AppleScript (enter directly as text)" and paste in your AppleScript code to update the icon there. This will make it update when the button is pressed, as well as playing/pausing your music!

**Comment by SenshiSentou** [comment]
Hey, thanks for your response! My action is already AppleScript, but I couldn't find a way to update the icon from it (AppleScript Editor also doesn't show any available actions for BTT).

Would you mind sharing a quick snippet or explaining which API call(s) to use?

**Comment by CarterVE** [comment]
Sure, I've attached a screenshot of my script! I have this script in both the "Run AppleScript and Show Return Value" area, and in the "Run AppleScript (enter directly as text)" fields, so it updates every so often, but also whenever the button is pressed. You can set the widget to show the return value of the AppleScript, or to change the icon based on the return value in BTT. I've then attached an additional action to run play/pause whenever the button is pressed.

<img width="864" alt="screen shot 2018-02-28 at 11 21 16 am" src="https://user-images.githubusercontent.com/18474523/36799013-1e75a53c-1c7a-11e8-921d-e5e07931616b.png">
<img width="817" alt="screen shot 2018-02-28 at 11 20 48 am" src="https://user-images.githubusercontent.com/18474523/36799014-1ea478da-1c7a-11e8-9963-690a1f090304.png">

**Comment by SenshiSentou** [comment]
Aaah, derp! I had no idea the action's return value *also* updates the icon display! I set it to return `"yes"` or `"no"` and it shows the primary and alternate icons as expected.

Thanks for your help!

**Comment by CarterVE** [comment]
Happy to help!

**Comment by CristianMoisei** [comment]
Hey, @CarterVE how did you paste an icon in the AppleScript?

**Comment by CarterVE** [comment]
@CristianMoisei I used Unicode values for double bars (pause) and the play icon, however the newest versions of BTT supports returning the file path to icons so that might be a better way to do it now. Check out the BTT documentation, or if you look at the AppleScript widget page, there is a description of how to return an icon path in the correct format!

**Comment by CristianMoisei** [comment]
Thank you @CarterVE. I found one better, there's a method to refresh the widget by ID, so I can not only refresh that widget when it's pressed, but also the one that tells me the name of the song playing.

![screenshot 2018-07-04 20 36 06](https://user-images.githubusercontent.com/7927870/42292372-e5adb88a-7fc9-11e8-9d26-6652476aabe5.jpg)
[preset.zip](https://github.com/folivoraAI/BetterTouchTool/files/2164204/preset.zip)
