### ISSUE TITLE
BTT Remote Crash when trying to connect

### ISSUE THREAD

**Issue by tonynguyen1901** [fifafu/BetterTouchTool#2149]
Hi all,

I've been having this issue currently where when I try to connect BTT Remote through my iPhone 7 or iPad Air 2, BTT app on my Mac will crash with the message "BTT quit unexpectedly".

Both BTT Remote app and BTT app on my Mac are the latest version.

I don't have firewall enabled.

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version: MacOS High Sierra 10.13.1
BetterTouchTool version: 2.341

---

Process:               BetterTouchTool [98370]
Path:                  /Applications/BetterTouchTool.app/Contents/MacOS/BetterTouchTool
Identifier:            com.hegenberg.BetterTouchTool
Version:               2.341 (720)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           BetterTouchTool [98370]
User ID:               501

Date/Time:             2018-02-16 23:41:54.053 +1100
OS Version:            Mac OS X 10.13.1 (17B1003)
Report Version:        12
Anonymous UUID:        B6258452-2AEE-CBF3-FC7A-C9C70F4676EF

Sleep/Wake UUID:       40B97AC1-1729-449D-B2EC-BA0136FBF1FF

Time Awake Since Boot: 200000 seconds
Time Since Wake:       12 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Applications/BetterTouchTool.app/Contents/MacOS/BetterTouchTool
  Reason: image not found

Binary Images:
       0x10af0e000 -        0x10b474ff7 +com.hegenberg.BetterTouchTool (2.341 - 720) <D8E22955-9B1B-3089-BE8A-C8736DA809C9> /Applications/BetterTouchTool.app/Contents/MacOS/BetterTouchTool
       0x114834000 -        0x11487e98f  dyld (519.2.1) <CD85EFBA-B9D6-3FD5-B777-A23B2DDEF192> /usr/lib/dyld
    0x7fff3b010000 -     0x7fff3be6bff7  com.apple.AppKit (6.9 - 1561.10.101) <AC5C259A-615C-3929-8586-0BC920696AFA> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3d46e000 -     0x7fff3d501ff7  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <505A5EFB-6BCD-3E94-936F-1722C67F608E> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff3d9b0000 -     0x7fff3de4ffef  com.apple.CoreFoundation (6.9 - 1445.12) <C01736CF-D425-316C-A984-C8AF46EAD8CD> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3eaf1000 -     0x7fff3eaf1fff  com.apple.CoreServices (822.9 - 822.9) <F56B0D43-BD84-3214-AB01-346BD33C9583> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3fac4000 -     0x7fff3fe87fff  com.apple.Foundation (6.9 - 1443.14) <70D20A4F-74BC-34D6-8451-DF943C5AA42F> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff49577000 -     0x7fff49892ff7  com.apple.security (7.0 - 58286.20.16) <ED7F62C8-4E61-34E0-9F1B-59DE4B8BD334> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff49cf2000 -     0x7fff49d62ffb  com.apple.SystemConfiguration (1.17 - 1.17) <77EB81C7-7017-3777-BCB7-8DD078ABE25D> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff51a1a000 -     0x7fff51a29ff7  com.apple.framework.DFRFoundation (1.0 - 189.1) <C7DE4082-6AC1-3971-AAC7-979E33C9D0F1> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff51f1f000 -     0x7fff51f2aff7  com.apple.DisplayServicesFW (3.1 - 380) <FB1FBB24-7FD5-3B57-8D3C-39F953F8A9BB> /System/Library/PrivateFrameworks/DisplayServices.framework/Versions/A/DisplayServices
    0x7fff526de000 -     0x7fff526fefff  com.apple.EmojiFoundation (1.0 - 1) <88874A6A-7184-3C95-B7CB-A109A0FD11F1> /System/Library/PrivateFrameworks/EmojiFoundation.framework/Versions/A/EmojiFoundation
    0x7fff5c46e000 -     0x7fff5c489fff  com.apple.frameworks.preferencepanessupport (13.0 - 13.0) <BD1A760C-1450-3CE1-BABF-922ABE4751D6> /System/Library/PrivateFrameworks/PreferencePanesSupport.framework/Versions/A/PreferencePanesSupport
    0x7fff6304d000 -     0x7fff630a3fff  libc++.1.dylib (400.9) <FCF5E1F6-2B04-3545-8004-F3AB32FED172> /usr/lib/libc++.1.dylib

**Comment by fifafu** [comment]
This should be fixed in the newest alpha! (v2.342)
