### ISSUE TITLE
More on gestures not working in Microsoft Remote Desktop

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#215]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Related to #121 in Microsoft Remote Desktop:  With touch bar buttons defined to do cntl-shft-1 and cntl-shft-2, if I use them with a text editor window open in the Remote Desktop session, I see 1 and 2 appear.   Same using cntl-alt instead of cntl-shft.  In fact, if I have the TB buttons just do A and B and have special actions defined in Windows when A or B appears, then everything works fine.  So, it really seems like the modifier part is not getting sent, even though it works fine if I press the keyboard shortcut directly on the keyboard.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
10.12.2 and 1.978

**Which versions of macOS and BetterTouchTool are you running?**

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by CappyD** [comment]
and a little more:  I wonder if there is a timing issue or an issue with multiple modifiers.  If I define a TB button to use only a single modifier (like cntl+1 or alt+1 instead of cntl+shft+1) then the button generally works.

**Comment by fifafu** [comment]
There might be a solution to this problem soon (made some good progress recently). However I'm continuing to track it in #121
