### ISSUE TITLE
How do I design this to add a crypto tracker on prices? I have tried messing around with the setting on it but all it seems to do is link me to page rather than show me the actual price and changes etc

### ISSUE THREAD

**Issue by VJBorelli0217** [fifafu/BetterTouchTool#2152]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have a look at this little web app by Chris Lennon: https://chrislennon.github.io/Crypto-Touchbar-App/

**Comment by VJBorelli0217** [comment]
Wicked! Thanks!
