### ISSUE TITLE
unable to run update (26feb18)

### ISSUE THREAD

**Issue by fKing** [fifafu/BetterTouchTool#2153]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

i keep getting this error when i try to 'nstall and relaunch:

"Update Error! An error ocurred while extracting the archive"

#### Device information:

Type of Mac: 12 inch macbook (2016)
macOS version:  10.13.4 beta3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! Accidentally had the wrong version in there, should be fixed now.
However be aware that this is still an alpha release (downgrading is easy though)

**Comment by fKing** [comment]
Yep, all good now. Thanks for the fast response.
