### ISSUE TITLE
Modifier keys stuck on after actions in BTT 2.341–2.343 on Sierra

### ISSUE THREAD

**Issue by NevinBR** [fifafu/BetterTouchTool#2154]
#### Description of bug/feature request/question:

After updating BTT from v2.340 to v2.343 on my laptop running MacOS 10.12.6, I encountered a severe usability problem: BTT keyboard shortcuts which involve modifier keys cause those modifiers to remain stuck on endlessly. It acts as though the modifier keys were never released, and even the Keyboard Viewer built into the OS shows them still being pressed.

It was rather tricky to get out of that situation, since other shortcuts and even mouse clicks no longer worked properly due to the phantom modifiers that were stuck on. Notably, clicking on the BTT menu did not open it when “command” was stuck on, so I could not quit BTT that way.

When I did get back in control, I tested BTT versions 2.341, 2.342, and 2.343, which all exhibit this issue, and verified that BTT version 2.340 works correctly.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro keyboard

#### Device information:

Type of Mac: 2013 retina MacBook Pro 15″
macOS version: 10.12.6
BetterTouchTool version: 2.341 – 2.343

**Comment by fifafu** [comment]
Thanks for reporting, maybe the new shortcut system is not compatible with 10.12.x (I have tested the alpha versions only on 10.13. so far). I'll look into it.

**Comment by fifafu** [comment]
Mhh could you maybe post the example shortcut configuration you encountered this with? (I can't seem to reproduce it yet)

**Comment by NevinBR** [comment]
For testing I created a new BTT profile with only one shortcut: pressing ⌘U triggers ⌘I

In v2.343 it shows the Get Info window when I press ⌘U in Finder, and then cmd stays stuck on.

**Comment by fifafu** [comment]
Thank you, I'm now able to reproduce it on 10.12.x

**Comment by fifafu** [comment]
Would be great if you could check v2.344, I made some slight modifications and it seems to work now (on my machines at least)

**Comment by 88maomao** [comment]
Similar problem on 10.13.3. I map cmd-alt-{some key} to send a sequence `{some key}.
The last working version is v2.340. Unfortunately v2.344 is not working.

**Comment by fifafu** [comment]
@88maomao  could you post a screenshot of your example? I think this is something different.

**Comment by waxfingers** [comment]
In my case, all post 3.4.0 versions disregard F keys completely, no matter if *use F1, F2 ... as standard function keys* in sys pref is on/off. This must be an old sticky gremlin or inconp inside of BTT 'cause it used to surface once in a while, fortunately v 3.4.0 is stable =)

**Comment by fifafu** [comment]
@waxfingers if possible please create a new issue for this (what do you mean by disregard F keys?)
In 2.341 the keyboard & shortcut handling has been rewritten completely to provide more flexibility, this is why there are still some bugs in these alpha versions.

**Comment by waxfingers** [comment]
> what do you mean by disregard F keys?

@fifafu means that any BTT's shortcut that includes an F key does not work; i.e. F1 = brighten the screen.  

> In 2.341 the keyboard & shortcut handling has been rewritten completely to provide more flexibility, this is why there are still some bugs in these alpha versions.

That's versions test for... init? Anywy my love for BTT remains immovable 🗿

Okay, off to the issue tracking posting then =)

**Comment by fifafu** [comment]
@waxfingers it's just not possible to test this stuff completely without alpha testers, that's why all versions since 2.340 have only been published on the alpha channels.  Different keyboards, different operating systems and different environments (other apps running that influence this) can't be simulated unless spending some years just doing that.

**Comment by 88maomao** [comment]
@fifafu 
Here is what I've mapped
<img width="1127" alt="screen shot 2018-02-27 at 18 07 16" src="https://user-images.githubusercontent.com/35564679/36739644-1a0e9472-1be9-11e8-973c-7a0213f0e4d2.png">
Here is an example of correct behavior on `cmd-ctrl-]`
<img width="690" alt="screen shot 2018-02-27 at 17 51 16" src="https://user-images.githubusercontent.com/35564679/36739236-1f5a3df6-1be8-11e8-973e-95b787ed70f8.png">
There is no point to make screenshot with incorrect behavior, but for example when I press `cmd-alt-l` I've got `alt-l` in the application instead of sequence ``l

**Comment by NevinBR** [comment]
> Would be great if you could check v2.344, I made some slight modifications and it seems to work now (on my machines at least)

Yes, v2.344 works, thank you!

However, I am now seeing some other less-serious issues which I will post separately.
