### ISSUE TITLE
Don't see Trackpad (build-in) options on High Sierra

### ISSUE THREAD

**Issue by Alanfi** [fifafu/BetterTouchTool#2160]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac: MacBookPRO Mid 2011
macOS version:High Sierra 
BetterTouchTool version: 

I have a clean installation of High Sierra in my MBP.
When I try to configure right click on the trackpad (Build-in), it does not show the options it only says that it is looking for bluetooth devices
(The trackpad does work, but it does not show the configuration options)

Is there another way to assign a right click to the trackpad? some command per terminal?
Thank you very much!!**

Show....
![untitled](https://user-images.githubusercontent.com/36900187/36752603-80cd60e8-1bd1-11e8-8cac-b5a9fc901f52.png)

I should show the following image
![axgqg](https://user-images.githubusercontent.com/36900187/36752632-9df4aa14-1bd1-11e8-8d65-edeeb2491686.png)

I already tried

1. Reset SMC: Shut down your Mac, and then press and hold the left-side Shift (⇧) -Control (^) -Option keys along with the Power (⎋) button

2. Reset PRAM / NVRAM: Command (⌘) -Option (⌥) -P-R

3. Full new Clean Install High Sierra

And I can't find a solution

I think it's something from High Sierra Because when I install Lion, if it shows Trackpad Options

**Comment by fifafu** [comment]
Connect it with a usb cable, I think your Bluetooth Chip is too old for the Magic Trackpad 2.

**Comment by Alanfi** [comment]
Thank you so much
 it's the computer build-in trackpad, (under the keyboard)
I can not see your configuration options

**Comment by fifafu** [comment]
Bettertouchtool is not integrated in the system preferences. To see the BetterTouchTool preferences you need to click its menubar icon.

The screenshot you posted is also not related to BTT.
