### ISSUE TITLE
Shortcuts with arrow keys stop working in v2.344 on Sierra

### ISSUE THREAD

**Issue by NevinBR** [fifafu/BetterTouchTool#2161]
#### Description of bug/feature request/question:

When I updated to BTT 2.344, my shortcuts with arrow keys stopped working. For example, ⌘⌥⌃↑ is “Maximize Window”, and worked in BTT 2.340 but not in 2.344.

However, if I create a new one in 2.344, or even simply re-enter the keys for an existing one, it then works. Shortcuts without arrow keys had no problem.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro keyboard

#### Device information:

Type of Mac: 2013 retina MacBook Pro 15″
macOS version: 10.12.6
BetterTouchTool version: 2.344

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Inspecting the json files before and after re-entering the shortcuts reveals two changes.

The original version of my Maximize Window shortcut, which worked in v2.340 but not in v2.344, had:
"BTTTriggerType" : -1
"BTTShortcutModifierKeys" : 1835008

The result after re-entering the keystrokes, which works in v2.344, has no entry for “BTTTriggerType”, and has:
"BTTShortcutModifierKeys" : 10223616

All other fields are identical.

For comparison, my other shortcuts with the same modifiers, such as ⌘⌥⌃B for “Show BTT Preferences”, also lose the “BTTTriggerType” line, but their “BTTShortcutModifierKeys” remain as 1835008 through the change.

**Comment by fifafu** [comment]
Ah that's true.
Technically the arrow key produces also a FN key press which the old shortcut recorder code I had recorded. Now that BTT supports shortcuts with FN this doesn't work anymore. (It's complicated...)

I'll add some code to convert the old shortcuts!

**Comment by NevinBR** [comment]
Thanks for the info. Unfortunately, sometimes the new version of the shortcut doesn’t work in 2.344 either:

After triggering my Finder-specific BTT shortcut ⌘⌥⌃C to “Launch Google Chrome”, my BTT shortcuts involving arrow keys stop working in 2.344. 

They resume working after I trigger a non-arrow-key-using BTT shortcut, or cmd-tab between apps a couple times (merely clicking to switch apps is insufficient), or click in the Finder and trigger an arrow-key-using BTT shortcut (which has no effect, but it makes them work again thereafter.)

**Comment by fifafu** [comment]
Interesting, does this only happen with App/Finder specific shortcuts or also with global ones?

**Comment by NevinBR** [comment]
It appears to happen for app-specific shortcuts that open another app. Global shortcuts don’t cause the problem, nor do app-specific shortcuts that open a file (even if it opens in another app). Only app-specific shortcuts that open another app do.

Another oddity:

After triggering a BTT shortcut (any keyboard shortcut), the MacOS Keyboard Viewer shows extra modifier keys until I release the modifiers for the shortcut. For example, with a simple ⌘U to ⌘I shortcut, when I press cmd-U, then release U but keep holding cmd, the Keyboard Viewer shows cmd-opt-ctrl all engaged.

**Comment by fifafu** [comment]
That last oddity is part of a trick I need to use in order to map shortcuts to other shortcuts with different modifier keys (e.g. cmd + u to opt +i). In this example BTT needs to get rid of the CMD modifier although that obviously is still being pressed by the user. However this should not be a problem.

I'll check what's wrong with the app switching shortcut!

**Comment by NevinBR** [comment]
> That last oddity is part of a trick I need to use in order to map shortcuts to other shortcuts with different modifier keys (e.g. cmd + u to opt +i). In this example BTT needs to get rid of the CMD modifier although that obviously is still being pressed by the user. However this should not be a problem.

Well in BTT 2.340 it only shows the keys I’m actually pressing. And if I open the Karabiner EventViewer, in BTT 2.340 shortcuts show first exactly what I pressed, then they show exactly what got triggered. For ⌘U to ⌥I that is:

```
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
eventType:KeyDown         code:0x22       name:i               flags:Opt                                misc:
eventType:KeyUp           code:0x22       name:i               flags:                                   misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:                                   misc:
```

Conversely in BTT 2.344 the Karabiner EventViewer shows extra modifiers along with what I pressed:

```
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt Fn                        misc:
eventType:KeyDown         code:0x22       name:i               flags:Opt                                misc:
eventType:KeyUp           code:0x22       name:i               flags:                                   misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt Cmd Fn                    misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:                                   misc:
```

(And before you ask, yes I tested the BTT issues without Karabiner running, and with the standard keyboard layout. The BTT issues were the same irrespective of whether Karabiner was running and/or whether I was using my custom keyboard layout.)

**Comment by fifafu** [comment]
I think the keyboard events should now look a bit more natural in 2.345 alpha. (Have not yet worked on the "Launch App" issue, but who knows)

**Comment by NevinBR** [comment]
>I think the keyboard events should now look a bit more natural in 2.345 alpha. (Have not yet worked on the "Launch App" issue, but who knows)

Thanks, the extra modifiers no longer show up. Regarding the “Launch App” issue, I noticed something:

In Karabiner EventViewer my ⌘⌥⌃↑ shortcut shows up as ctrl-opt-cmd-fn (with no arrow key shown) when working correctly under in BTT 2.345. However after triggering ⌘⌥⌃C, it then shows up as ctrl-opt-cmd-numpad fn-up arrow, and does not work.

For comparison, in BTT 2.340 the event viewer shows it as ctrl-opt-cmd (with neither arrow key nor fn) and it works correctly.

BTT 2.345 working:
```
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Ctrl Cmd                           misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Ctrl Opt Cmd                       misc:
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Opt Cmd Fn                         misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Cmd Fn                             misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Fn                                 misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:                                   misc:
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Ctrl                               misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Ctrl Opt                           misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt Cmd                       misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:Ctrl Opt Cmd Fn                    misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt                           misc:
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
```

BTT 2.345 non-working:
```
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Opt                                misc:
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Ctrl Opt                           misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt Cmd                       misc:
eventType:KeyDown         code:0x7e       name:up_arrow        flags:Ctrl Opt Cmd NumPad Fn             misc:
eventType:KeyUp           code:0x7e       name:up_arrow        flags:Ctrl Opt Cmd NumPad Fn             misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt                           misc:
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
```


BTT 2.340 working:
```
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Ctrl                               misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Ctrl Opt                           misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt Cmd                       misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Ctrl Opt                           misc:
eventType:FlagsChanged    code:0x3b       name:left_control    flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
```
