### ISSUE TITLE
Move Mouse To Top/Bottom Right/Left Corner is broken

### ISSUE THREAD

**Issue by nhnt11** [fifafu/BetterTouchTool#2165]
#### Description of bug/feature request/question:
Can't add a new trigger with any of these gestures. A modal pops up asking for the delay and whether to include drags, but clicking "Save" doesn't properly add the gesture.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Other

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.340 (719)

**Comment by fifafu** [comment]
Sorry this is already fixed in the current alphas (stable release is planned for sunday)
