### ISSUE TITLE
2.347: Custom Keyboard Shortcut now not properly releasing some keys?  Odd result sending Control-Tab to Firefox.

### ISSUE THREAD

**Issue by TheBloke** [fifafu/BetterTouchTool#2169]
#### Description of bug/feature request/question:

I just upgraded to Alpha 2.347, which I see makes changes to keyboard shortcuts.

I have noticed an immediate negative effect with a Trackpad gesture that sends a keyboard shortcut.

Specifically: I have App->Firefox: Three-Finger-Double-Tap = Send Control-Tab.  I use this to quickly change to next tab in the browser using the Trackpad.

Since upgrading to 2.347, rather than immediately switching tab it now pops up Firefox's window switcher dialogue and that does not go away forever, until I press LMB or press a key.

Screen photo showing what happens when I do Three-Finger-Double-Tap once, sending Control-Tab to Firefox:  [link to photo](https://i.imgur.com/ifizlVh.jpg?1).

When operating Firefox normally, this UI only stays on screen if I keep Control held down after releasing Tab.  So it seems BTT must be doing that, it's not releasing the Control key in this instance.

However, other similar gestures (eg: App->Firefox: Four-Finger-Double-Tap = Command-R) do work OK and don't seem to repeat.   Though I guess in that case I wouldn't notice if Command was being held down.

I also tried rebinding the Gesture to just send 'a', and tested it to see if it kept sending multiple A's.  But it only sent one.  So maybe it only applies to multi-key custom shortcuts.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad -> Custom Keyboard Shortcut  (not tested other input devices)

#### Device information:

macOS version:  10.13.3
BetterTouchTool version:  2.347

**Comment by TheBloke** [comment]
What's really weird is that once  that Tab Switcher appears on screen, if I send the gesture again (eg 3-Finger-Double-Tap), the tab switcher GUI moves to the next tab, but doesn't disappear.

To re-create this with keyboard I would have to do:
- Hold down Control-Tab
- Release Tab but keep Control held down
- Press tab once

That's what BTT seems to be doing - it's as if Control is never being released until I click or press another key.

**Comment by fifafu** [comment]
Is this some firefox addon? (I can't seem to activate this)

I just checked with other keyboard shortcuts, but BTT seems to release all keys fine. Do you have any other keyboard related software running?

**Comment by TheBloke** [comment]
No, not a plugin.  Go to Firefox Preferences and tick "Ctrl+Tab cycles through tabs in recent-used order".  [Screenshot](https://i.imgur.com/8C4UQb7.png).

For some reason this also enables the tab-switcher GUI; there's no separate setting for that.

In terms of other Keyboard apps, I have Karabiner-Elements also installed, set to remap certain keys such as swapping " and @, putting `, |, ~ on the right place for my British keyboard, etc.

I just tried closing Karabiner-Elements and it doesn't affect the new issue I get with BTT 2.347 when sending Control-Tab to Firefox.

I haven't had an issue with any other app yet, it exclusively seems to be sending Control-Tab to Firefox.  So maybe it is an issue in Firefox?  But it worked fine before 2.347 and broke the moment I upgraded (I used my Control-Tab-to-Firefox shortcut literally 30 seconds after I upgraded, so I spotted it instantly), so it seems likely that something has changed in what BTT is doing, even if the bug isn't in BTT itself?

**Comment by fifafu** [comment]
Ah I can reproduce it when enabling this function. Will check what's causing this.

**Comment by fifafu** [comment]
For now I think you can workaround it using the compatibility mode for firefox: 
![image](https://user-images.githubusercontent.com/8820811/36897034-3e0362ee-1e15-11e8-94fa-87dddb3267a1.png)

**Comment by TheBloke** [comment]
Ah lovely, yes that's working now.  I forgot about those options.

Thanks!

**Comment by fifafu** [comment]
Would be great if you could check how 2.350 alpha behaves on your system (without compatibility mode)

**Comment by TheBloke** [comment]
That worked!  Control-Tab sent to Firefox now works in normal mode, with compatibility mode off.

Other shortcuts seem fine too.

Thanks very much for the fast resolution.

**Comment by TheBloke** [comment]
Unfortuantely this issue has re-occurred in 2.416 - Firefox is pausing on its tab-switcher, indicating the Control key is being held down when I send Control-Tab.

Setting Firefox to Compatibility mode fixes it, as before.

**Comment by fifafu** [comment]
Oops sorry, this is quite delicate and another change caused it to reappear. 
Should be working again in 2.417

**Comment by TheBloke** [comment]
Yup seems fine in 2.417, thanks
