### ISSUE TITLE
BTT crashes repeatedly even after reboot

### ISSUE THREAD

**Issue by Quantumpanda** [fifafu/BetterTouchTool#217]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Short version: 
Over the last 24 hours, BTT has been crashing and relaunching roughly every two to three hours. This has happened before, but the behavior this time has persisted past a reboot, which it has not done before.

Long version: 
I had a mess of system issues to deal with Friday evening after a cat inadvertently yanked out the power cord to my powered USB hub, which has a small stack of external bus-powered drives connected through it. The resolving of these issues led to several reboots, including one in Safe Mode.

After the final reboot of the series, I found that BTT was not visible in my menu bar, and Activity Monitor had it marked as not responding (highlighted red). I waited to see if this would clear on its own (as it often will after a while), but it was still unresponsive after roughly a half hour, so I force-quit it. BTTRelaunch failed to relaunch it and went unresponsive as well, so I force-quit that and then manually launched BTT. Once I determined that it appeared to be launching properly, I then left the computer running overnight (as I normally do) and returned to it the following afternoon.

When I returned, there were five pending notifications of BTT having crashed. (I have Notification Center limited to showing the last five entries from a single source.) I pulled up the crash reports in Console and found that starting with Time Awake Since Boot of 10000 seconds (according to the crash log), BTT had crashed and relaunched roughly every two to three hours since that time. The crash reports after the first two showed identical sequences of instructions in Thread 0 (which is the thread that crashed in all cases). 

I extracted the logs and ran an EtreCheck report. That showed a few anomalous issues that I thought had been taken care of already—nothing that was likely to be the cause of these crashes, but still reported by EtreCheck as issues. I went ahead and took care of those and then ran a new EtreCheck report. This second report took more than an hour to complete, during which time I had to leave for other business. When I returned several hours later, the report was complete, and BTT had crashed twice more. It crashed again shortly after that, while I was extracting the logs for those two newest crashes.

At that point, I rebooted my system. I had planned to run EtreCheck once more after the reboot, under the expectation that the reboot would resolve the issue as it had previous similar cyclical BTT crashes. Before I initiated that run, I ended up spending some time resolving a network issue (that eventually led to rebooting my router—yes, I have had a lot of issues to resolve in the last few days). While I was working on that, BTT crashed again.

I pulled up the crash report for the newest crash, and noticed two interesting things: it had occurred, like the initial crash in the cycle, at Time Awake Since Boot of 10000 seconds; and the instructions in Thread 0 (the crashed thread) were the same as in the log for the initial crash. I then realized that this was not a simple transient glitch resolved by rebooting, and did not bother with the additional EtreCheck run.

**What kind of Mac are you using?**
MacBook Pro 17-inch, mid-2010

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
My MBP has the standard multi-touch trackpad of this model MBP, but the problem is not related to the use of the input device—there is no correlation I have found between the crashes and my use of any BTT functions.

**Which versions of macOS and BetterTouchTool are you running?**
Mac OS X 10.10.5 (Yosemite), BTT 1.963 (552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
I have included all the crash logs since the initial crash in a zip file, along with the second EtreCheck report. I am not aware of anything of significance that changed immediately prior to the USB hub problem that kicked off this series of events, so I'm pretty sure that whatever triggered this problem was a result of that event or the process of resolving its effects. The last change of significance was roughly a week ago when I applied the latest Security Update for Yosemite. That update had not had any effect on BTT that I noticed. Also, BTT is working properly between crashes—all my shortcuts work just fine. The crashes are more of an annoyance than a major problem. But repeated crashes should be investigated regardless of whether they're a big problem for a specific user.

[BTT_logs.zip](https://github.com/fifafu/BetterTouchTool/files/691388/BTT_logs.zip)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Apparently for some reason your system is unable to execute the "hide all applications" action in BetterTouchTool. I'm not sure what exactly is causing it, but it doesn't seem to be directly related to BTT as it crashes while executing the Apple Script BTT uses to hide all applications. It crashes during a system call which makes me think something has gotten corrupted on your macOS installation.

Maybe for some reasons some BTT files got corrupted, you could first try to download a fresh copy of BTT from my website (https://boastr.net/downloads )

Best,
Andreas

**Comment by Quantumpanda** [comment]
I have redownloaded BTT and installed it fresh, so we'll see if the problem recurs. Given the circumstances that started my tinkering, I wouldn't be surprised if something in my OS has gotten corrupted, but it's a lot easier to reinstall BTT than to repair a broken OS install.

Your explanation of the problem opens a different question for me: why is BTT trying to hide all applications, and why does it do it on such a predictable schedule? I don't have anything set up in BTT that hides applications, and the crashes are happening whether I'm at the machine or not. So why is it trying to hide apps?

**Comment by fifafu** [comment]
Ah sorry, I misread the crashlog. It already crashes when trying to compile the hide all script (which it does once after starting BTT). Maybe just the script file inside the BTT app bundle got corrupted.

**Comment by Quantumpanda** [comment]
Well, the crash recurred again after reinstalling a fresh copy of BTT, so whatever is causing it wasn't resolved that way. I tried an OS reinstall last night, but something in that process seems to have horked my system worse. The full fsck that normally happens after an OS reinstall kept hanging until I unplugged the hub all my external drives are on. With all the externals disconnected,  the boot-time fsck ran, but everything was horribly slow to respond, and Disk Utility hung on attempting to verify the boot drive. So I have Disk Utility running from the recovery drive now on the boot volume. I suspect I'll be spending Monday restoring the boot volume from Time Machine to where it was just before everything went kerplunk on Friday. At this point, I doubt BTT is part of my actual problem. But thanks for the help so far. I'll keep you informed as to whether anything beneficial happens. 

Mark D. McKean
qpanda@quantumpanda.com

**Comment by fifafu** [comment]
Uh oh, sounds a bit like your hard disk is about to fail. Better backup now!

**Comment by Quantumpanda** [comment]
Fortunately, I keep multiple backups: Time Machine locally, plus Backblaze online (though that's usually a little behind due to upload speeds). And my most important stuff is in either Dropbox or Evernote. I'm preparing to do a full TM restore right now, to the last backup before the crap started, after which I'll be picking up the few things that changed between then and the trouble. And then I'm ordering my new SSD. Good thing I was getting ready to do that anyway. 

Mark D. McKean
qpanda@quantumpanda.com

**Comment by philwinne** [comment]
BetterTouchTool randomly quits and usually restarts after a brief but variable time. Running Sierra 10.12.2 (16C67) on a new 2016 MacBook Pro w/ touchbar. Redownloaded & reinstalled – continues to randomly quit then restart.

**Comment by Quantumpanda** [comment]
Just to follow up on where my story left off...

My hard drive has not failed yet, but I'm still replacing it. (I need the SSD to make up for the fact that maxed-out RAM at 8 GB on a 2010 MBP is far from enough anymore.) I did the restore as I said, and since then (nearly two weeks now), BTT has not crashed a single time. Clearly, something happened during that cat-induced incident that mucked up something, but I haven't the foggiest idea what.

Now, I have to say that @philwinne's problem with the repeated random quits is one I have experienced periodically for years (I alluded to this in my initial post). I haven't looked deeply enough into it to determine whether it correlates to anything meaningful, but every 3-6 months or so, I'll have a day when BTT repeatedly crashes and restarts. It usually stops on its own within about 8-12 hours, but if it doesn't, a reboot pretty much always takes care of it. That was why this instance was different enough to report: it didn't resolve after rebooting multiple times.

I have no idea what causes this behavior on the part of BTT. Since it's transient and short-lived, with no apparent long-term effects, I'm not overly concerned about it. But if you'd like more information about it, let me know, and I'll pull logs the next time it happens.

**Comment by fifafu** [comment]
I have made some changes in alpha 1.992, would be great if you could check if you still encounter random quits. (It should only quit & restart after the Mac wakes from sleep)

**Comment by philwinne** [comment]
Hi. Downloaded the new version & installed – all is working beautifully for the past hour or so. Will continue to monitor & email again in approx 24 hrs.

THANKS!

On 2017 Jan 22, at 12:30, Andreas Hegenberg <notifications@github.com> wrote:

I have made some changes in alpha 1.992, would be great if you could check if you still encounter random quits. (It should only quit & restart after the Mac wakes from sleep)

**Comment by philwinne** [comment]
No issues for the past 19 hrs after installing alpha 1.992. Random crashes are completely absent & trackpad response seems much better. Bravo!

**Comment by yjsoon** [comment]
Just found this, and happy to report that the app has been up for over 30 minutes... which is a feat, given how it used to crash in about 2. Thanks!

**Comment by fifafu** [comment]
@yjsoon what exactly do you mean by crash? Does it just close? Is there a crashlog in the MacOS console.app under "user reports"?

**Comment by yjsoon** [comment]
@fifafu Yes, it closed by itself. Has been up since, though. Log is at http://cld.tk.sg/itZ3
