### ISSUE TITLE
Trackpad haptic response: many options do nothing (on Magic Trackpad 2)

### ISSUE THREAD

**Issue by TheBloke** [fifafu/BetterTouchTool#2171]
#### Description of bug/question:

I don't know if this is a known/expected issue, or a bug, or maybe I just don't have the right hardware?

I have an external Magic Trackpad 2, with Force Touch/Feedback.   I thought this would support all of BTT's Haptic Response options, but the following ones do nothing - no feedback is felt when they are selected:
- Very Light
- Light
- Strong
- Double Strong
- Double Light
- Light 2
- BTT Default Click Release
- BTT Default Click
- BTT Default ForceClick
- NEW BTT Default Click Release
- NEW BTT Default Click
- NEW BTT Default ForceClick
- NEW BTT SILENT Default Click *
- NEW BTT SILENT Default ForceClick *

  * *I'm not sure whether these are meant to be felt, given they say 'silent'.  But then I don't see how they differ from 'No feedback'.

The others work as expected. 

No feedback at all is felt when any of the above list is configured as defaults for "Haptic for normal" or "Haptic for force" clicks in `Trackpad Settings->FORCE Touchpad->Haptic response for..`.  They also do nothing when added for specific gestures via `Gestures-> cog->Force Touch Feedback when this gesture is triggered`.

If they don't work with the Magic Trackpad 2 (MacBook touchpad only?), perhaps a note to that effect could be added on the `Trackpad Settings->FORCE Touchpad` screen.

Thanks.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad (tested only on external Magic Trackpad 2)

#### Device information:

Mac:  Mac Pro 5.1
macOS version:  10.13.3 (17D102)
BetterTouchTool version:  2.350

**Comment by fifafu** [comment]
Unfortunately this is a known issue / depends on the hardware.
I'll make this more clear in the UI.
See https://github.com/fifafu/BetterTouchTool/issues/2110
