### ISSUE TITLE
Feature request: both BTT and native icons on touch bar

### ISSUE THREAD

**Issue by iAmRenzo** [fifafu/BetterTouchTool#2172]
I don't know if this is already possible or not. Thing is, I couldn't find it in the settings.

I'd like to have both my BTT buttons on the Touch Bar as well as the defaults from the app I'm using. Something like this: [esc] [my global buttons] [my special app buttons] [default app buttons] [controlstrip expander]

It would be awesome if the global button could be an expandable menu (as the control strip), there are several items I'd like to keep near me) ;)

I understand that the space is limited, but for apps that allow touchbar customisation you can minimise to the bare essentials. For apps as Final Cut Pro X that not really an option.

Can this be done? How? Or can you implement it?

**Comment by fifafu** [comment]
Unfortunately this is not possible given the current Touch Bar API from Apple.
