### ISSUE TITLE
BTT crashes at startup 

### ISSUE THREAD

**Issue by cnlier** [fifafu/BetterTouchTool#2177]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

(see crashlog)

Happened after migration to new Mac

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[BetterTouchTool_2018-03-04-121956-1_6581-2.crash.zip](https://github.com/fifafu/BetterTouchTool/files/1778438/BetterTouchTool_2018-03-04-121956-1_6581-2.crash.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Your migrated files are somehow read-only. This means the permissions are wrong and you will need to repair them. Maybe have a look at this Apple guide: https://support.apple.com/en-us/HT203538

**Comment by cnlier** [comment]
Thanks, it worked.
