### ISSUE TITLE
Browser 2 finger swipes interfering...

### ISSUE THREAD

**Issue by peetwright** [fifafu/BetterTouchTool#2178]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
It appears as if in recent updates to Chrome (main browser I use - may be applicable to others) swiping with two fingers up and down easily triggers a browser native back to issue. It's overly sensitive. Watching the downward swipe, it may be 3 degrees off but the browser catches it as a two finger swipe back. In my case, I have back setup universally as three finger swipe specifically because 2 finger right click action usually gave me headaches when combined with back/forward. So the request is - add an action to force the application to ignore a given gesture. I tried creating a gesture for 2 finger swipe left/right attached with no action - but nothing happens, chrome still swipes back.
So this may be an issue or a request - thanks either way!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook trackpad

#### Device information:

Type of Mac: 15" retina, mid 2014
macOS version:  10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
What do you have selected here in System Preferences => Trackpad => More Gestures?

![image](https://user-images.githubusercontent.com/8820811/36948273-83e81984-1fd8-11e8-8a42-4d436f95c678.png)

**Comment by peetwright** [comment]
Swipe with two, as shown in the image below. Should I disable this one and just set it all in BTT?

**Comment by fifafu** [comment]
Yep, unfortunately this will probably be the only way to make it work consistently :-(

**Comment by peetwright** [comment]
Thank you for the quick reply and I’ll give it a shot! It’s been royally messing me up when dealing with php apps where a form is filled in then go back, lose content/confusion session etc etc. 

Appreciate it - please feel free to kill this request on Git.

Tschüß!
