### ISSUE TITLE
Normal Mice Action did not response for scroll and middle mouse button.

### ISSUE THREAD

**Issue by penockio** [fifafu/BetterTouchTool#2179]
#### Description of bug/feature request/question:
I use microsoft sculpt comfort mouse with bettertouchtool on Mac osx 10.13.3. 
In the tap "normal mice", I added new button "Scroll Left" with predefined action "desktop left". I did the same way to "Scroll Right" and "Middle Mouse Button" to action something. 
However, nothing happened when I did "scroll left" or "scrolll right" or "middle mouse button". 
What did I miss?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
microsoft sculpt comfort mouse. 

#### Device information:
Type of Mac: MacBook Pro Retina with Touch Bar 2016
macOS version: 10.13.3
BetterTouchTool version: 2.351 (731)

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
What action have you assigned?

You can check whether the button is recognized by making it show a little HUD overlay like this:
![image](https://user-images.githubusercontent.com/8820811/36948613-a6188188-1fdd-11e8-8ff8-a4d45dad0698.png)

**Comment by penockio** [comment]
After I set "Show HUD", it worked but still have some problem for "scroll left" and "scroll right". 
I set it to move windows one space (desktop left or right follow the mouse scroll). When I did action scroll left one time, there was a delay before the desktops was moved more than one desktop (sometime two or three or more). It happened the same with scroll right too.
What should I set more in details?

**Comment by penockio** [comment]
Thanks, I solved the problem by setting the custom key shortcut to "ctrl+right arrow" instead. It worked fine. 

The new problem is that I cannot assign the side button of sculpt mouse for action. The application cannot detect the button. I tried to use keyboard tap but it showed the symbol of "mac command button" when I pressed the side mouse button.
There is a way to solve this problem?

**Comment by fifafu** [comment]
BTT can only configure mouse buttons if the mouse driver sends "normal mouse button events". In your case it apparently sends a cmd event instead.

Here are some tips to make it work: http://docs.bettertouchtool.net/docs/normal_mice_problems.html but it depends on the mouse driver (unfortunately I never had a Microsoft mouse)

**Comment by penockio** [comment]
Fifafu. Thank you very much for your advices.
