### ISSUE TITLE
[Feature Request] Dedicated TouchBar remapping application

### ISSUE THREAD

**Issue by Imajou** [fifafu/BetterTouchTool#2182]
**Request description:**
Since a lot of people (me too) are using BTT only for TouchBar remapping (there is no any other application that supports that flexible remapping) without need of other functionality (which has not an obvious way to disable), I think it would be great to have dedicated application only for TouchBar remapping.

**Comment by fifafu** [comment]
The Touch bar remapping relies on tons of BTT functionality. Separating it out would be a lot of work and cause maintenance work I won't be able to handle.

You can hide the tabs in BTT that you don't need by right clicking them.

**Comment by Imajou** [comment]
But how do I disable completely all this functions?

**Comment by fifafu** [comment]
If you don't configure any triggers they are disabled. Window snapping can be disabled in the preferences.
