### ISSUE TITLE
Widget (touchbar):  how to run Binary instead of script?

### ISSUE THREAD

**Issue by bobstern** [fifafu/BetterTouchTool#2183]
In a touchbar Widget, is it possible to run a binary directly instead of running it in an AppleScript or other scripting environment?

I have a binary called Foo that "prints" to stdout.  

BTT does correctly display its output in the touchbar if I run it as an AppleScript Widget:
`return do shell script "/usr/local/bin/Foo"`

BTT also displays its output correctly if I call Foo as a Python 3.6.4 subprocess:
Path:  /usr/local/bin/python3
Parameter:  -c
Script:
```
import subprocess
x = subprocess.run("/usr/local/bin/Foo", stdout=subprocess.PIPE)
print(x.stdout.decode('UTF-8'), end="")
```

However, it does not work if I enter the Foo binary itself `/usr/local/bin/Foo` as the Path in BTT.  When I click the Run button, no result displays.

(In Terminal, simply entering `/usr/local/bin/Foo` also produces the desired result.)

**Comment by fifafu** [comment]
In the current alpha versions this should work, the 2.340 version had a bug that prevented this from working.

**Comment by bobstern** [comment]
Version is latest alpha: 2.353.

**Comment by bobstern** [comment]
Sometimes it displays the result in the BTT Widget Prefs dialog when I click Run, but most of the time it does not.  Regardless, when I close the BTT window, BTT never launches the process according to Activity Monitor, and it never displays the result in the touchbar button.  (I restarted BTT a few times.)

**Comment by bobstern** [comment]
fwiw, touchbar Buttons **_do_** work for running a command line program.  I enter the complete path to the program as the Path, the first argument as the Parameter, and any additional arguments as the Script.

**Comment by fifafu** [comment]
You are right I think there was still an issue with empty parameters. This build should fix it but is not yet available via autoupdate: https://bettertouchtool.net/releases/btt2.354.zip

**Comment by bobstern** [comment]
Yes, that fixed it.  Thanks, Andreas!
