### ISSUE TITLE
divide 6 size

### ISSUE THREAD

**Issue by leno-ig** [fifafu/BetterTouchTool#2187]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
This is feature request for BetterSnapTool.

(Sorry for bad english. I'm not english speaker.)
I'm using 4k monitor. so top left is too large.
I want 6 size.(top left, top center, top right, bottom left, bottom center, bottom right)

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

for such custom layouts please use the "Custom Snap Area" feature. (Click the BetterSnapTool Menubar icon and go to the "Custom Snap Area" section)

**Comment by leno-ig** [comment]
Oh, It's nice.
And i can bind custom shortcut key. Thanks!
