### ISSUE TITLE
Enable/Disable status not shown anymore in menu bar

### ISSUE THREAD

**Issue by tbgulli** [fifafu/BetterTouchTool#2188]
After updating the app (currently on 2.340) the status of enabled/disabled is no longer indicated by a greyed out symbol in the menu bar. I know, this is just a small thing but as so often, small things make life so much easier. I noticed I used this a lot now that it's gone. Could you please bring it back? Mac OS X 10.13.2

**Comment by fifafu** [comment]
True, thanks for reporting, I'll fix it!

**Comment by tbgulli** [comment]
uh das ging aber schnell!! 😄 Vielen Dank!

**Comment by fifafu** [comment]
Fixed in 2.361 alpha :-)

**Comment by tbgulli** [comment]
Awesome!! Thank so much for the quick fix!! Sorry to bother you again, but now deactivating BTT works but as it is deactivated so is the hotkey for reactivating, I guess. Say I have F19 set to enable/disable BTT, disable BTT works, but enabling it again does not.

**Comment by fifafu** [comment]
Ah sorry,  that may be related to the new shortcut system. Will be fixed with the next alpha ;-)

**Comment by tbgulli** [comment]
Perfect! Now if everybody had such great and fast support!! 😊
