### ISSUE TITLE
"Move Window One Desktop Left" appears broken in 2.355

### ISSUE THREAD

**Issue by bboc** [fifafu/BetterTouchTool#2189]
#### Description of bug/feature request/question:

I set have set up keyboard triggers  in BTT for the actions `Move Window One Space/Desktop Left` and `Move Window One Space/Desktop Right`

When I set up a shortcut for mission control (in the preferences app) that either triggers `Move right a space` or `Move left a space` to `⇧^⎇⌘[`, the BTT actions for moving a window to another desktop break:

* when I set `Move *right* a space` to `⇧^⎇⌘]`, the BTT action `Move Window One Space/Desktop *Left*` moves the windows one space to the **right**, except on the last desktop, where the window is moved one to the left. The action `Move Window One Space/Desktop *Right*` is unaffected.
* when I set `Move *left* a space` to `⇧^⎇⌘]`, the BTT action `Move Window One Space/Desktop *Right*` moves the windows one space to the **left**, except on the last desktop, where the window is moved one to the right. The action `Move Window One Space/Desktop **Left**_ is unaffected.

More observations: 

* when I set `Move left/right a space` to another trigger, e.g. `⇧^1` or deactivate that shortcut via the checkbox, both BTT actions do what they are supposed to do when triggered from the keyboard.
*triggering `Move Window One Space/Desktop Left/Right` via touchpad works regardless of the setting of `Move left/right a space`
* BTT HUD overlay shows that BTT reacts on the correct shortcut.
* I have tried to assign the action to other keys, but that does not help.
* I have also set up other shortcuts in BTT to resize windows, which work great. 

I have verified that problem exists with v2.355 / v3.340 / v2.330 / v2.320 / 2.0.5 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

External Bluetooth Keyboard, Macbook Keyboard

#### Device information:

Type of Mac: mbp 13' (2015)
macOS version: 10.12.6
BetterTouchTool version: 2.355 / 3.340 / 2.330 / 2.320 / 2.0.5

#### Edited

* Removed my erroneous statement that the behavior was not present in BTT v2.0.5
* added more info about how to trigger the behavior
* formatting to make actions and triggers more readable

**Comment by TheBloke** [comment]
Just to say that it's working OK for me in 2.355 Alpha, tested with the following shortcuts:

[Screenshot](https://i.imgur.com/vqZaTlf.png)

I have "Displays have separate spaces" enabled in System Preferences->Mission Control, in case this makes any difference.

**Comment by bboc** [comment]
@TheBloke you can add images here by simply dragging them into the text box.

I, too have "Displays have separate spaces" enabled. Just to make sure I tried the shortcuts you set, also did not help. What I find strange that v2.0.5 works fine, it's just awfully slow on my machine.

Here's my setup
![screenshot 2018-03-07 21 00 59](https://user-images.githubusercontent.com/520442/37115166-ad05f57e-224a-11e8-8844-47093dae5342.png)

**Comment by TheBloke** [comment]
Thanks @bboc , I always forget that.

Have you tried deleting and re-adding the Gestures (rather than just changing keys on the existing gesture)?  

I'd also try configuring a non-keyboard Gesture with the same action to see if it happens there too, or is specific to keyboard?  If you don't have another suitable input method you could test with the Other gestures like right-click on the orange/green window buttons.

I know Andreas has made a lot of changes to keyboard gestures recently, but it seems weird for it to register the keys but run the wrong action.  I've never seen that before.

**Comment by fifafu** [comment]
Could you check if it works correctly after disabling the "trigger on down" option?

It currently seems to work fine here however it would be interesting whether it works using other triggers (e.g. Gestures)

**Comment by bboc** [comment]
Thanks for your suggestions, that helped me a lot in figuring out what's going on. Disabling the "trigger on down" option did not help, but assigning gestures the action to a gesture worked as intended, which suggested it has something to do with the way keyboard shortcuts are processed in my system. At first I thought maybe another application is listening to these shortcuts, so I used [ShortcutDetective](http://www.irradiatedsoftware.com/labs/), to make sure that is not the case.

After some more testing, I found that when I set the following shortcuts in mission control, I could turn on and off the erroneous behavior of the action "move window one space/desktop to the left":

*   keyboard shortcuts for mission control:
     * ⇧^⎇⌘[ move one desktop left
     * ⇧^⎇⌘[ move one desktop right

When disabling these shortcuts in mission control, "move window one space/desktop to the left" works as intended. When I reactivate them, it's broken. When I set different shortcuts in mission control, e.g. ^⎇1 and ^⎇2, all works as intended. It appears that the actual combination of keys defined in BTT to trigger "move window one space/desktop to the left" does not matter. 

At least I now know how to work around this issue, but I have no idea what is causing this. If I find the time I will check again if BTT 2.0.5 fixes that on my system as I claimed in my original report.

**Comment by TheBloke** [comment]
Oh wow yeah I can re-create that.  That's so weird:

![screenshot_2018-03-08 10 30 36_bqeuka](https://user-images.githubusercontent.com/784313/37146472-c22fbb94-22bb-11e8-9d5c-4171afa765d8.png)

![screenshot_2018-03-08 10 27 45_imuqjt](https://user-images.githubusercontent.com/784313/37146347-5dd30f98-22bb-11e8-9a36-b3973f9efbbd.png)

Result:

1. BTT "Move Window Left a Space" = moves window to **right**
2. And also, my Trackpad shortcut 3F Swipe Left for "Move Left A Space" no longer works!  It now causes the UI to sort of "bounce" to the left, like it's starting to Move Left but is being blocked.  Gesture for Move Right a Space still works.

![screenshot_2018-03-08 10 31 02_qh63v2](https://user-images.githubusercontent.com/784313/37146500-d32649b8-22bb-11e8-9c3d-b10955c41169.png)

So somehow configuring that specific Mission Control shortcut breaks BTT's ability to Move Left or Move a Window Left?  Very weird.

**Comment by TheBloke** [comment]
Another workaround:  just configure Move Left a Space and Move Right a Space in BTT Keyboard Gestures; don't use Mission Control keyboard shortcuts at all (unless for cases that BTT doesn't support, like moving to a particular numbered Space.)

**Comment by bboc** [comment]
Ok, installed 2.0.5 again, and tested some more, and the problem is still present. Sorry for the confusion.

More testing revealed that this behavior can be triggered by only setting the shortcut in mission control for *move one desktop to right* to ⇧^⎇⌘[

I will edit the description of the issue to reflect both of these findings.

**Comment by fifafu** [comment]
Ohh I think that may be related to the way how BTT triggers these actions. 
I think I never expected somebody to use ⇧^⎇⌘[  as a shortcut in system preferences. 

It's complicated, but I now understand the issue - I'm not sure whether there is an easy fix though :-)

**Comment by TheBloke** [comment]
FYI I had Mission Control "Move Right a Space" set to ⇧^⎇⌘]   - **]**  not **[**   

That triggers it for me.  I can't replicate it with ⇧^⎇⌘[

**Comment by bboc** [comment]
Even more testing revealed that when I set up mission control shortcut for _Move a space to the **left**_ to ⇧^⎇⌘[, suddenly BTT's _Move Window One Space/Desktop **Right**_ moves the window into the wrong direction, and  _Move Window One Space/Desktop Left_ works as intended.

**Comment by fifafu** [comment]
yes, if possible don't use shortcuts with 4 modifiers and brackets in system preferences for now.

Short explanation:
There is no official way to trigger these actions. Thus BTT uses a hack.
When you trigger e.g. move window to right space in BTT, BTT will enable & change the shortcut for "Move Right a Space" in system preferences for a very short moment to ⇧^⎇⌘]. Then BTT sends that shortcut to the system and the system will trigger the appropriate action in response. Afterwards BTT changes the shortcut back to what it was before.

However BTT DOESN't remove any existing ⇧^⎇⌘] shortcuts that have been set by the user. To prevent this issue BTT should do that for the short moment where it changes the shortcut.

**Comment by bboc** [comment]
@TheBloke thanks, that was a typo on my part. `⇧^⎇⌘]` for me.

**Comment by TheBloke** [comment]
That's a good idea on the Hyper key using Caps.  I think I will try that.

For now I'd suggest to just put all shortcuts in BTT, at least all it supports:

![screenshot_2018-03-08 11 44 45_xnkjzj](https://user-images.githubusercontent.com/784313/37149503-256d19f4-22c6-11e8-970c-59d041661a66.png)

As long as it's BTT that is using ⇧^⎇⌘] shortcut and not the System Prefs, it won't conflict.      And I guess Andreas always uses ⇧^⎇⌘] for all his hack actions, so probably there isn't another shortcut that would conflict?

**Comment by fifafu** [comment]
Yes, I think that's a good workaround for now!

**Comment by bboc** [comment]
I hadn't thought of that, that's a great solution. 

@fifafu just curious, what keyboard layout are you using? German or US?

**Comment by fifafu** [comment]
I'm closing here as this is such an edge case I won't implement a heavy workaround.
In future versions (>= 2.417) you can however change the shortcut BTT reservers using this terminal command:

```defaults write com.hegenberg.BetterTouchTool BTTAppleKeyboardShortcut "59,58,56,55,30"```

(30 is the keycode for right-bracket).

Here are various keycodes (need to be translated to decimal)

```

enum {
  kVK_ANSI_A                    = 0x00,
  kVK_ANSI_S                    = 0x01,
  kVK_ANSI_D                    = 0x02,
  kVK_ANSI_F                    = 0x03,
  kVK_ANSI_H                    = 0x04,
  kVK_ANSI_G                    = 0x05,
  kVK_ANSI_Z                    = 0x06,
  kVK_ANSI_X                    = 0x07,
  kVK_ANSI_C                    = 0x08,
  kVK_ANSI_V                    = 0x09,
  kVK_ANSI_B                    = 0x0B,
  kVK_ANSI_Q                    = 0x0C,
  kVK_ANSI_W                    = 0x0D,
  kVK_ANSI_E                    = 0x0E,
  kVK_ANSI_R                    = 0x0F,
  kVK_ANSI_Y                    = 0x10,
  kVK_ANSI_T                    = 0x11,
  kVK_ANSI_1                    = 0x12,
  kVK_ANSI_2                    = 0x13,
  kVK_ANSI_3                    = 0x14,
  kVK_ANSI_4                    = 0x15,
  kVK_ANSI_6                    = 0x16,
  kVK_ANSI_5                    = 0x17,
  kVK_ANSI_Equal                = 0x18,
  kVK_ANSI_9                    = 0x19,
  kVK_ANSI_7                    = 0x1A,
  kVK_ANSI_Minus                = 0x1B,
  kVK_ANSI_8                    = 0x1C,
  kVK_ANSI_0                    = 0x1D,
  kVK_ANSI_RightBracket         = 0x1E,
  kVK_ANSI_O                    = 0x1F,
  kVK_ANSI_U                    = 0x20,
  kVK_ANSI_LeftBracket          = 0x21,
  kVK_ANSI_I                    = 0x22,
  kVK_ANSI_P                    = 0x23,
  kVK_ANSI_L                    = 0x25,
  kVK_ANSI_J                    = 0x26,
  kVK_ANSI_Quote                = 0x27,
  kVK_ANSI_K                    = 0x28,
  kVK_ANSI_Semicolon            = 0x29,
  kVK_ANSI_Backslash            = 0x2A,
  kVK_ANSI_Comma                = 0x2B,
  kVK_ANSI_Slash                = 0x2C,
  kVK_ANSI_N                    = 0x2D,
  kVK_ANSI_M                    = 0x2E,
  kVK_ANSI_Period               = 0x2F,
  kVK_ANSI_Grave                = 0x32,
  kVK_ANSI_KeypadDecimal        = 0x41,
  kVK_ANSI_KeypadMultiply       = 0x43,
  kVK_ANSI_KeypadPlus           = 0x45,
  kVK_ANSI_KeypadClear          = 0x47,
  kVK_ANSI_KeypadDivide         = 0x4B,
  kVK_ANSI_KeypadEnter          = 0x4C,
  kVK_ANSI_KeypadMinus          = 0x4E,
  kVK_ANSI_KeypadEquals         = 0x51,
  kVK_ANSI_Keypad0              = 0x52,
  kVK_ANSI_Keypad1              = 0x53,
  kVK_ANSI_Keypad2              = 0x54,
  kVK_ANSI_Keypad3              = 0x55,
  kVK_ANSI_Keypad4              = 0x56,
  kVK_ANSI_Keypad5              = 0x57,
  kVK_ANSI_Keypad6              = 0x58,
  kVK_ANSI_Keypad7              = 0x59,
  kVK_ANSI_Keypad8              = 0x5B,
  kVK_ANSI_Keypad9              = 0x5C
};

/* keycodes for keys that are independent of keyboard layout*/
enum {
  kVK_Return                    = 0x24,
  kVK_Tab                       = 0x30,
  kVK_Space                     = 0x31,
  kVK_Delete                    = 0x33,
  kVK_Escape                    = 0x35,
  kVK_Command                   = 0x37,
  kVK_Shift                     = 0x38,
  kVK_CapsLock                  = 0x39,
  kVK_Option                    = 0x3A,
  kVK_Control                   = 0x3B,
  kVK_RightCommand              = 0x36,
  kVK_RightShift                = 0x3C,
  kVK_RightOption               = 0x3D,
  kVK_RightControl              = 0x3E,
  kVK_Function                  = 0x3F,
  kVK_F17                       = 0x40,
  kVK_VolumeUp                  = 0x48,
  kVK_VolumeDown                = 0x49,
  kVK_Mute                      = 0x4A,
  kVK_F18                       = 0x4F,
  kVK_F19                       = 0x50,
  kVK_F20                       = 0x5A,
  kVK_F5                        = 0x60,
  kVK_F6                        = 0x61,
  kVK_F7                        = 0x62,
  kVK_F3                        = 0x63,
  kVK_F8                        = 0x64,
  kVK_F9                        = 0x65,
  kVK_F11                       = 0x67,
  kVK_F13                       = 0x69,
  kVK_F16                       = 0x6A,
  kVK_F14                       = 0x6B,
  kVK_F10                       = 0x6D,
  kVK_F12                       = 0x6F,
  kVK_F15                       = 0x71,
  kVK_Help                      = 0x72,
  kVK_Home                      = 0x73,
  kVK_PageUp                    = 0x74,
  kVK_ForwardDelete             = 0x75,
  kVK_F4                        = 0x76,
  kVK_End                       = 0x77,
  kVK_F2                        = 0x78,
  kVK_PageDown                  = 0x79,
  kVK_F1                        = 0x7A,
  kVK_LeftArrow                 = 0x7B,
  kVK_RightArrow                = 0x7C,
  kVK_DownArrow                 = 0x7D,
  kVK_UpArrow                   = 0x7E
};
```

**Comment by bboc** [comment]
@fifafu thanks for the info. 

BTW: The reason why I asked you about your keyboard is that `[` and `]` are really simple to type on a us keyboard, but hard on a German keyboard. I use US layout for that reason, and many default shortcuts make a lot more sense on that.
