### ISSUE TITLE
While BTT is active, application windows may expand when dragged.

### ISSUE THREAD

**Issue by kardvm** [fifafu/BetterTouchTool#219]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I received delivery of a new iMac 2 weeks ago, with macOS 10.12.1 preinstalled. During the first few days, I carried out a clean installation of my applications. Soon after I began to use the iMac, I noticed that an application window that was being dragged across the Desktop would sometimes suddenly expand to fill the entire space. It became apparent that this behavior only occurred when the top border of the application window was pushed up against the lower border of the Menu bar. Also, if the application window was off to either side of the Desktop when it was moved up to touch the Menu bar, the window would sometimes expand to a different size, but not full screen size. When the newly expanded window was dragged down, away from the Menu bar, it would immediately return to its previous size. This behavior also made it impossible to drag a window to the top of the Desktop so that it could be put into a different space.

This problem did not occur when I created a different User Account. When I contacted Apple customer service about the problem, they tested one of their systems using various Apple software applications, but they could not reproduce the problem. They suggested that it could be related to some other software that was running on my iMac.

Today, I finally had a chance to investigate the various applications running on my iMac. I found that the problem that I described only occurs when BetterTouchTool is running. As soon as I close BTT, the problem goes away.

**What kind of Mac are you using?**
 iMac 5K, 27 inch
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.1, macOS 10.12.2, BetterTouchTool 1.963 (552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

that's one of the main features in BetterTouchTool :-) It's called window snapping and allows you to resize windows by dragging them to the edges and corners of the screen. When dragging them away again they restore their previous position.

You can disable window snapping, see attached screenshot: 
![image](https://cloud.githubusercontent.com/assets/8820811/21744891/48c3c074-d51f-11e6-9287-60765061d606.png)

**Comment by kardvm** [comment]
Hi Andreas,

Thank you for explaining that to me.

I never saw that behavior with BTT  in OS X 10.11. My old iMac was too old to be updated to macOS 10.12. It took me by surprise, particularly as I was using the new operating system for the first time, working to put things back where they were in my old setup, and trying to get my macros and shortcuts to work in the new system. Practically every time I moved a window, it would explode to fill up the Desktop.

My biggest problem, once I got used to the strange, snapping behavior, was that I could not drag the window up to open up Spaces. Perhaps you can attach a modifier key to this feature. But for now, I will stick with deactivating the snapping feature of BTT.

Ken

**Comment by fifafu** [comment]
The feature is quite configurable in the advanced settings, maybe the highlighted settings can help you: 
![image](https://cloud.githubusercontent.com/assets/8820811/21745302/1305b12c-d529-11e6-97f6-d23a217ec473.png)

**Comment by kardvm** [comment]
Hi Andreas,

As you can tell, I do not have a deep knowledge of BTT. I use it mostly to do things with the track pad, such as control volume and open up URL links in new tabs.

I looked at the Advanced Settings section, probably for the first time. The only thing that I did was to uncheck “El Capitan: Delay Mission Control on top edge.” That works for me. I just have to develop a feel for the my timing when I push a window up to the Menu bar so that I select what I want, either snapping or moving into Mission Control.

Thank you again.

Ken
