### ISSUE TITLE
Trackpad release seems to be unrecognized

### ISSUE THREAD

**Issue by mndholder** [fifafu/BetterTouchTool#2194]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I encounter this issue quite a lot while working with Webstorm. I think IDEA, Phpstorm and other Jetbrains tools would also suffice, but I tried Webstorm only.

It seems like sometimes when I release the trackpad button, the release itself is unrecognized. More specifically, look at the gif below:

![screencast 2018-03-07 15-49-04](https://user-images.githubusercontent.com/8880741/37094156-efe1ac12-2222-11e8-9322-b5edd63d8ab3.gif)

What happens there is this:
1. I search something in the document;
2. I highlight the previously searched string by pressing the trackpad and holding my finger on it;
3. I release the trackpad;
4. I start typing again.

At some point it seems like on step 3 the trackpad release is not recognized and everything I type is being removed. 
Same thing happens if I actually do not release the trackpad and continue typing.

Disabling the BetterTouchTool for Webstorm only or for all apps resolves the problem, the issue is not reproducible anymore.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.13.2
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

- Apparently, changing some settings inside `Window Moving & Resizing Settings` tab changes how often the issue is reproduced, but I can't tell anything specific in here;
- Sometimes I encounter a drag issue, which may be related. It is better described here:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000337670-Strange-text-grabbing-behavior-in-IDEA

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Let's continue tracking this in #2198
