### ISSUE TITLE
Odd behavior with old shortcuts having "BTTTriggerType" : -1

### ISSUE THREAD

**Issue by NevinBR** [fifafu/BetterTouchTool#2196]
#### Description of bug/feature request/question:

This is a weirdly specific issue involving pre-existing app-specific shortcuts that are old enough to have the field “"BTTTriggerType" : -1”. I have not yet nailed down exactly what is required to make it happen.

I have a Finder-specific BTT shortcut for ⌘↑ set to two consecutive actions: first “Menubar-item: Go;Enclosing Folder” then “Menubar-item: View;Hide Toolbar”. (For some reason MacOS occasionally forgets that I always keep the toolbar hidden.)

The problem begins when I am in another app, say a text editor. If I cmd-tab to Finder, then back to the text editor, suddenly the standard ⌘↑ shortcut for “Move cursor to beginning of text” stops working in the text editor.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro keyboard.

#### Device information:

Type of Mac: 2013 Retina MacBook Pro 15.4″
macOS version: 10.12.6
BetterTouchTool version: 2.359

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

…and now that I tried to reproduce the issue, it is doing the exact same thing for ⌘↓ (which I have defined similarly with “Menubar-item File;Open”) and not doing it for ⌘↑.

If I update a shortcut by re-entering its keystrokes, the json no longer has “"BTTTriggerType" : -1” and the problem does not occur.

**Comment by NevinBR** [comment]
Here is a BTT profile with just the Finder-specific ⌘↑ shortcut. Using this profile I see the problematic behavior 100% of the time.

Once the problem has been triggered, disabling the shortcut in BTT restores the standard functionality, and re-enabling the shortcut breaks it again.

[Test 2.359.json.zip](https://github.com/fifafu/BetterTouchTool/files/1791930/Test.2.359.json.zip)

**Comment by fifafu** [comment]
Thanks for reporting! I can reproduce this. Should be fixed in the next alpha.

**Comment by fifafu** [comment]
Should now be working in v2.360!
