### ISSUE TITLE
current alpha works/doesn't work until open

### ISSUE THREAD

**Issue by fKing** [fifafu/BetterTouchTool#2199]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
this afternoon's alpha sometimes doesn't work after i wake my mac from sleep; just reporting that. i have to open the app, and then it works.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
keyboard

#### Device information:

Type of Mac: 12" macbook
macOS version:  10.13.4 Beta (17E170c)
BetterTouchTool version: 2.361

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Does this only seem to happen after waking from sleep, or also when you restart BTT manually?

**Comment by fKing** [comment]
a few times, i've woken my macbook, and BTT is not working. then i open the app... and it works.other times all is well.
this only started with the latest alpha btw.
let me know if you need anything else!



    On Thursday, March 8, 2018, 6:30:45 PM EST, Andreas Hegenberg <notifications@github.com> wrote:  
 
 
Does this only seem to happen after waking from sleep, or also when you restart BTT manually?

**Comment by fifafu** [comment]
So far I haven't had similar reports, thus I assume this is fixed?

If it's still happening for you, please comment again.

**Comment by fKing** [comment]
it still happens randomly (not, for example, only on waking from sleep). i'll go to use my keyboard shortcut in safari, and... no response. if i open & close bettertouchtool, it works after that. again, random... (and not often).
