### ISSUE TITLE
Delay showing of snap areas

### ISSUE THREAD

**Issue by fabien88** [fifafu/BetterTouchTool#220]
feature request

Would if be possible to delay showing of snap areas by 1 or 2 seconds. Because sometimes, I miss click and move a window and that trigger unwanted snap area and resizing.

Thanks in advance!

**Comment by dj-hedgehog** [comment]
This option exists already. Please have a look at this screenshot:

![monosnap 2017-01-15 11-24-55](https://cloud.githubusercontent.com/assets/7140800/21961854/4cd7d1e0-db15-11e6-9b19-327570df4299.png)

**Comment by fabien88** [comment]
thank you !
