### ISSUE TITLE
Enabling any trackpad gesture makes the Magic Trackpad unresponsive to clicks

### ISSUE THREAD

**Issue by ggoofer** [fifafu/BetterTouchTool#2200]
#### Description of bug/feature request/question:
Whenever a BTT profile is enabled that includes any trackpad gesture, the magic trackpad becomes extremely glitchy. Most clicks/taps not registered. Live View shows missed clicks, clicks that vanish too soon, and clicks that leave a tiny circle lingering behind. This was consistent regardless of BTT version/computer restart/sleep or not/Accessibility preference add+remove/jiggle mouse to enlarge it/etc. that I tried. The problems go away if I quit BTT or disable profile in menu bar.

Here is exactly where the glitches happened. I added blank gestures and did not fill anything in.
1. completely empty profile: ok
2. profile with one blank keyboard shortcut: ok
3. profile with one blank trackpad gesture: Error
3a. deleting the gesture in the previous profile without restarting BTT: Error
3b. after restarting BTT: ok

Strangely, it suddenly started to worked for several hours last night. Today it went back.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 1

#### Device information:[

Type of Mac: 2013 iMac 27"
macOS version: 10.13.3
BetterTouchTool version: 2.361

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Are you experiencing this in all apps or in some specific apps?

Most of the time such behavior is caused by conflicting other apps, are you running anything else that affects keyboard or mouse input?

**Comment by ggoofer** [comment]
I don't think so... I'm running Karabiner Elements and Alfred but I don't think it's either of those (and it doesn't seem to be). All I installed recently was the latest nvidia driver...they are buggy, could it be that?

**Comment by fifafu** [comment]
I haven't had reports about the nvidia driver yet.

Do the little circles in live view vanish if you touch the trackpad again?

It _**could**_ be a faulty trackpad that produces "phantom input". I have seen this a few times with the old Magic Trackpad, however then the live view should show e.g. multiple touches although only one finger is touching the trackpad and things like that.

**Comment by fifafu** [comment]
Ah one more question:
What kind of gesture did you add? Or does it happen with any gesture?

**Comment by ggoofer** [comment]
Just an empty gesture in a new profile, like so 
![screen shot 2018-03-09 at 3 25 08 am](https://user-images.githubusercontent.com/30241525/37200177-a35ee08a-2349-11e8-83c9-fca0b7a5a3a7.png)
I started with all disabled (everything is OK), make that new one master. Once enabled I have the problem, including if I restart BTT.

The trackpad is 4 years old and well used, so trackpad hardware error is definitely possible

**Comment by fifafu** [comment]
Could you reproduce the issue (i.e. produce missed clicks and the bad behavior), then go to the about tab in BTT and click the "Export debug info" button? This will create a folder called BetterTouchToolDebug on your desktop that contains some logs. Maybe they can show me some details if you send them to boastr.net@gmail.com

**Comment by fifafu** [comment]
Some weird thing is happening in your logs.
For some reason BTT thinks your trackpad constantly connects & disconnects & connects & disconnects....

I'll prepare a version that logs some more details later. You probably don't have access to a different trackpad to test, correct?

**Comment by ggoofer** [comment]
I do not have an extra trackpad (but depending what you find out, maybe I will be getting one). Thanks for the help

**Comment by fifafu** [comment]
I have added some more logs in the current alpha (get via "check for alpha updates").

Maybe also try to reset your bluetooth module (cmd+shift+click the bluetooth menubar icon)
![image](https://user-images.githubusercontent.com/8820811/37222308-df142a4e-23cc-11e8-8b74-5884b949885f.png)

**Comment by ggoofer** [comment]
Finally I found the source! Unplugging my external USB hub fixes the problem. Simultaneously it stopped my continuous system log entries 'PrintUITool[4170]: notify name "com.apple.system.powersources.source" has been registered 14240 times - this may be a leak'

Somehow my mac is having a problem with knowing whether my USB is powered on, which somehow confuses whether my bluetooth trackpad is also powered on. Not a BTT issue, just our typical High Sierra bugs that are for no obvious reason and totally bizarre

Thanks for the help. BTT works again and I am so relieved

**Comment by fifafu** [comment]
Awesome, glad you figured it out!
