### ISSUE TITLE
[Feature Request] Spotify Playback Touchbar Button ADD-ON

### ISSUE THREAD

**Issue by emiliobusnelli** [fifafu/BetterTouchTool#2201]
Hello again everyone! I am very very happy with this app so far within the last week I've had it. It makes my macbook an absolute beast for productivity! I just added the script to allow a touchbar button to display the current artist and song that is playing. I set an assigned action for the button "next" to skip the songwithout having to open up the spotify app. 

I like how it is set up currently, but is there any way to assign an action to the button so that when the spotify playback button is hit, it pulls up the default touchbar for spotify (as well as the x on the left side to get back to your global actions). I was messing around with this today but I could not figure out a way to get it to work. 

This would be an awesome feature for anyone who likes the default applications touchbar set-up. 

Thank you! 

Sincerely, Emilio.

**Comment by fifafu** [comment]
Unfortunately this is not possible. The Touch Bar API is very limited and doesn't give me access to anything that would allow to do this ;-(
