### ISSUE TITLE
Keyboard action: accessibility issue

### ISSUE THREAD

**Issue by Dom-J** [fifafu/BetterTouchTool#2202]
Hi,

When I try assigning a keyboard action to a gesture, I get this error message. Restart BTT doesn't fix it, and in System Prefs → Security → Accessibility BTT is allowed to control the computer.

Any hints ?
Version : 2.360 (744)
macOS 10.13.4 (17E170c)

![capture d ecran 2018-03-09 a 11 48 33](https://user-images.githubusercontent.com/24507414/37204813-fdeeb664-239a-11e8-952a-780d584f35a4.png)

**Comment by fifafu** [comment]
Ah thanks for reporting!
Does adding a shortcut in the keyboard tab in BetterTouchTool fix this?

**Comment by Dom-J** [comment]
Hi,
Thanks for the quick reaction ! Well, as soon as I click on the field to
enter a shortcut (⌘Q is interesting me right now) I get this error message,
I can not interact with the "custom keyboard shortcut" field at all. It's
interesting to notice that predefined actions work perfectly..
Seb

Le ven. 9 mars 2018 à 14:30, Andreas Hegenberg <notifications@github.com> a
écrit :

**Comment by fifafu** [comment]
Have you tried adding one trigger in the keyboard tab in BTT? (Not in the touchpad tab)

I think there is currently a bug that expects a keyboard shortcut to be defined (although you are configuring a gesture)

I'll upload a fix in about an hour

**Comment by Dom-J** [comment]
I'll check this as soon as I have Access on my computer again, I'll let you
know.
Thanks a lot for the quick reaction !!

Le ven. 9 mars 2018 à 14:50, Andreas Hegenberg <notifications@github.com> a
écrit :

**Comment by Dom-J** [comment]
This actually worked. I assigned the action ⌘Q to the shortcut ⌘Q, now I'm able to use any custom Keyboard shortcut. Thanks a lot !
(adding a trigger to the action was unsuccessful by the way).

**Comment by fifafu** [comment]
Thanks for confirming!

**Comment by fifafu** [comment]
It's now fixed in v2.362!
