### ISSUE TITLE
[FEATURE REQUEST] Weather Widget to TouchBar

### ISSUE THREAD

**Issue by emiliobusnelli** [fifafu/BetterTouchTool#2204]
Hello, here I am again with another feature request. Is there any possible way that we could add a weather widget to the touchbar so that it displays the current locations degrees in either fahrenheit or celsius. 

I think that many people would like this (:

I would love to learn how to write my own scripts, I am currently learning website development and soon hope to be able to write my own scripts for others to use with this amazing application.

Thank you again, sincerely,

Emilio.

**Comment by fifafu** [comment]
You can look at the weather widgets created by other users:
https://github.com/fifafu/BetterTouchTool/issues/1696

There will soon be a platform to share BTT presets so this will become easier.
