### ISSUE TITLE
Touchbar inconsistant function...

### ISSUE THREAD

**Issue by sc-surfer** [fifafu/BetterTouchTool#221]
First off, let me say that you have the killer app here. Being able to customize the touchbar is an epic leap in functionality. PLEASE don't give up on this concept!!

#### Description of your bug/question/feature request...:

I have a set of touchbar buttons created under the universal umbrella. Half of them have the checkbox for activation with the shift key on. Initially everything worked as planed. Several buttons showed normally snd where I held down shift the others appeared. EPIC functionality!! However, not it's not working. I have to hit shift many times before the alternate buttons come up, and then they don't go away when releasing shift.

**What kind of Mac are you using?**

2016 MBP 15"
MacOS Sierra

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touchbar

**Which versions of macOS and BetterTouchTool are you running?**

Sierra 10.12.2
BTT 1.978(569)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

Have already  tried reboot and restart of BTT.

PLEASE continue to support and develop this feature!!! It's an awesome concept.

**Comment by fifafu** [comment]
Could you try whether the latest update (1.979) fixes your issue? (Just released that an hour ago)

**Comment by sc-surfer** [comment]
Will do!  And thanks for this app. Much needed!!

I'll follow up my ticket with the results.

**Comment by sc-surfer** [comment]
So far the issue has not returned. Will revisit this ticket if it happens again.

Thanks

**Comment by fabien88** [comment]
I have same problem with latest version (1.980). In Global, I have setup 3 buttons triggered by ctrl key. They show correctly when I press ctrl, but when ctrl key is released, they stay active.
Thank you for your support.

**Comment by fifafu** [comment]
@fabien88 I think that specific issue should be fixed with 1.982

**Comment by fabien88** [comment]
yes it does indeed, thank you !!
