### ISSUE TITLE
TouchBar - Button Group - Keep open when changing app. 

### ISSUE THREAD

**Issue by wabiloo** [fifafu/BetterTouchTool#2215]
#### Description of bug/feature request/question:

I've created a Button Group for the Touch Bar, which allows me to control Spotify (and get the current track displaying). I've added this Button Group under Global
This works great, but unfortunately every time I switch application, the button group closes again.  Is there a way of keeping it open until manually closed with the (x) button?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac:  MBP 15" 2017
macOS version:  High Sierra (10.13.3)
BetterTouchTool version: 2.359

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screenshot: https://www.dropbox.com/s/fcp9bwx0efbovqz/Screenshot%202018-03-12%2010.58.30.png?dl=0

**Comment by fifafu** [comment]
Currently that's not possible, but it's planned for one of the next versions!
This is already being tracked here #369

**Comment by spnkr** [comment]
+1
