### ISSUE TITLE
Key Sequence doesn't work in the following situation after update

### ISSUE THREAD

**Issue by shimj** [fifafu/BetterTouchTool#2217]
#### Description of bug:
Key Sequence doesn't work in the following situation after update:
I have set a general shortcut "command + space" triggers something, and also set a key sequence "command + space + A + A". This key sequence won't  be triggered after update.
(I use "command + space + ? + ?"  to launch most of my apps, and set "command + space" shortcut to switch to an app without GUI. In this way, when I press down the key "?", it won't be enter into the current app.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.13.3
BetterTouchTool version: 2.400

**Comment by shimj** [comment]
Another issue: any new added key sequence will trigger "command+Y" before do the desired thing.

**Comment by fifafu** [comment]
On some systems there seems to be a weird problem with event handling.
You can try to enable the old keyboard implementation in the advanced preferences:

![image](https://user-images.githubusercontent.com/8820811/37287401-0ac634ae-2605-11e8-8cc4-3b5e88a2174e.png)

If possible also go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop - if you send that to boastr.net@gmail.com I may see what's going on. I really can't see any way how cmd+y would be triggered, there is no code in BTT that does that.

**Comment by shimj** [comment]
I found the following operations can solve the first problem temporarily: disable "command + space"shortcut, enable "Use old keyboard shortcut ...", re-enable "command + space". Every time I restart BTT, I must do the above operations to make it work. As for the second problem, I also think it strange, but have no solution, so weird...

**Comment by fifafu** [comment]
Ah now I understand your setup (wow that's dedicated) :-)
And I believe it's affected by a little logic change. Could you try whether this version behaves correctly on your machine?
https://bettertouchtool.net/releases/btt2.401.zip

**Comment by shimj** [comment]
Haha, this version works fine (for the first problem) whether or not enable "Use old keyboard shortcut...". Thanks for your quick reply!

**Comment by shimj** [comment]
I found that "command + Y" is triggered if I check "perform cmd+z after recognition" in the key sequence settings interface.

**Comment by fifafu** [comment]
Uh indeed. That is however an old bug :-) Thanks for finding that, I'll upload a version with a fix asap.
