### ISSUE TITLE
v2.400 (751) giving a blind guy the jitters, zoom, pinch, trackpad

### ISSUE THREAD

**Issue by DaChinski** [fifafu/BetterTouchTool#2218]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm a legally blind guy who lives by BTT to magnify my mac screen to a gazillion times magnification so I can get stuff done. I use thumb and forefinger pinch in and out on a magic trackpad v 2 with iMac and on a macbook pro (2017 haptic) to zoom the screen in and out. Pointer set to remain at or near centre of the screen.

Since today's update, the scrolling is much less smooth - more juddery - and the mouse pointer (hence viewable area)  is flicking off wildly to another part of the screen as I zoom in / out. Its as if I had set System Preferences / Accessibility / Zoom to "Zoom follows keyboard focus". (The latter is a nightmare and has never worked as the kernel seems to randomly assign keyboard focus all over the place from time to time.)

It feels like as I zoom out (especially) that one or other of the axis is being over sensitive and shooting the pointer off in a random direction.  It wasn't like that on the previous version. 

Any ideas how I might fix it please?  Sorry if this is the wrong place to ask such questions...

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
iMac magic mouse v2
macbook pro trackpad

#### Device information:

Type of Mac: iMac mid 2011 i7 quad core with 16gb ram / 2017 macbook pro i5 2.3ghz 8gb ram
macOS version: 10.13.3
BetterTouchTool version: 2.400 (751)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi!

That's weird, how have you configured the zoom in BTT?
You can always downgrade to the previous version using this link: https://bettertouchtool.net/releases/btt2.340.zip

Best,
Andreas

**Comment by DaChinski** [comment]
Hey - thanks Andreas that was quick!

Re my settings, well there's about a gazillion settings aren't there...  I'd be happy to send along my config file if that would help ...

Tony

**Comment by fifafu** [comment]
Yep, that would help! If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop - if you send that to boastr.net@gmail.com I may see what's going on.

**Comment by DaChinski** [comment]
Done!

Listen - I want to thank you from the depth of my being for such a helpful tool - I literally use it all day every day and without it, I'd achieve so much less.

**Comment by fifafu** [comment]
Thank you, it's always nice to hear if BTT helps people :-)

Could you try whether this version improves the behavior on your machine? https://bettertouchtool.net/releases/btt2.401b.zip 
 Download it & replace your current version of the app.

**Comment by DaChinski** [comment]
:-O 

Man - that's WAY better and seems to have done the trick! The old version was okay on my 7 year old i7 16gb imac but not so on my brand new i5 8gb macbook pro. So I put it down to raw power and was selling my mbp lol.  

This version is so much more smooth when pinching to zoom - and the mouse pointer stays where it should be - BRILLIANT man.

I've paid for a license but I'd happily pay again for such great service - well done. 

Out of interest, I know its an apple problem - but do you think there will ever be a solution to the old problem of "zoom follows keyboard focus" making the screen zoom area flick to random points of the screen as the kernel focuses there for whatever mad reason it chooses?

Thanks so much again - you have made my day - and saved me from selling my laptop.

Tony

**Comment by DaChinski** [comment]
I replied to your post on the forum - that new version 2.401 did the trick and all is smooth and the pointer does not wonder at all.  Thank you so much man! You have made made my day. 

RE your specific question, I have pinch-in on the track pad set to "option command -“ and pinch-out set to “option command =” so that one increases magnification and the other decreases it.  Its just wonderful for somebody with my needs.  In fact, my fully sighted son now uses it too as he feels it to be a much easier way of getting a quick closer look at something small on a high res screen.  

Amazing stuff - keep up the GREAT work,
Tony

**Comment by aitte2** [comment]
I love this ticket. :D Great job both of you!
