### ISSUE TITLE
CAPS lock changes keyboard shortcuts

### ISSUE THREAD

**Issue by bboymatt** [fifafu/BetterTouchTool#2221]
#### Description of bug/feature request/question:
When caps lock is on the keyboard shortcuts do not work.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard, haven't tested the rest.

#### Device information:

Type of Mac: Macbookpro 2015
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.400 (751)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Really annoying when cmd+Q is normally remapped...

**Comment by fifafu** [comment]
You can add a second shortcut that is recorded while caps lock is active to resolve your issue.

For BTT these are different shortcuts because different keys appear to be pressed.

**Comment by fifafu** [comment]
After thinking a bit more about it, I think you are right. Caps Lock is now ignored in v2.402
