### ISSUE TITLE
repeat keys

### ISSUE THREAD

**Issue by nzfarmer1** [fifafu/BetterTouchTool#2222]
Great product.

Would be really neat if there was an option for the short cut to repeat if it the key combo was held down.

**Comment by fifafu** [comment]
See this screenshot ;-)
![image](https://user-images.githubusercontent.com/8820811/37305499-f41bd4c2-2634-11e8-806f-72533ad06eeb.png)

**Comment by nzfarmer1** [comment]
awesome, but howdy I get this dialog? the icon where the arrow points does not respond to a click?

**Comment by fifafu** [comment]
Which version of macOS are you running?

**Comment by nzfarmer1** [comment]
10.9.5

**Comment by fifafu** [comment]
Ah sorry. 
Current BetterTouchTool versions require 10.10 or higher (the higher the better)
