### ISSUE TITLE
Touch Bar Haptic Feedback - no feedback for "esc" touch bar button

### ISSUE THREAD

**Issue by brantwedel** [fifafu/BetterTouchTool#2223]
#### Description of bug/feature request/question:

I just found the awesome haptic feedback for touch bar option. It seems like this would logically also affect the escape button, but it does not.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TouchBar

#### Device information:

Type of Mac: MacBook Pro 15 inch 2016
macOS version: 10.13.3
BetterTouchTool version: 2.402 (753)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

The options I am referring to:
<img width="758" alt="screenshot 2018-03-12 15 10 27" src="https://user-images.githubusercontent.com/1801892/37307002-88a0c0f4-2607-11e8-9105-919b0c0eeb5d.png">

**Comment by fifafu** [comment]
Thanks for reporting. Added in the latest alpha version!
