### ISSUE TITLE
Better touch tool 2.402(753) not working for keyboards shortcuts

### ISSUE THREAD

**Issue by coolgoose85** [fifafu/BetterTouchTool#2226]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I updated BTT to 2.402(753) and it stopped working. I also tried restarting the machine but still it is not working.

I am using BTT for keyboard shortcuts for Mac for e.g. function+arrow for window to maximize on right half of screen etc.

Key F6 for fullscreen etc

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook keyboard.

#### Device information:

Type of Mac: iMac
macOS version: macOS High Sierra
BetterTouchTool version: 2.402(753)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
BTT does not crash but it doesn't work either. In Activity monitor also everything looks fine.

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately there are some few systems that for (so far) unknown reasons don't support the new shortcut system. I currently believe this is a macOS bug. In that case you can switch back to the old implementation in the advanced preferences (however you won't be able to use the new feature).

![image](https://user-images.githubusercontent.com/8820811/37311446-8b5a919a-2647-11e8-8a19-bdd1a2f28a05.png)

**Comment by fifafu** [comment]
This is being tracked here: https://github.com/fifafu/BetterTouchTool/issues/2185

**Comment by coolgoose85** [comment]
Thanks that solved my issue. 👍
