### ISSUE TITLE
The shortcut cannot be triggered by the touchpad gesture in some situations

### ISSUE THREAD

**Issue by shimj** [fifafu/BetterTouchTool#2227]
#### Description of bug:
The shortcut cannot be triggered by the touchpad gesture in the either of following situations:
1. the shortcut contains all the modified keys e.g. "⌘⌥⌃⇧ + a".
2. the shortcut is set to be triggered on down.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard & MacBook Trackpad

#### Device information:

Type of Mac:MacBook Pro 2017
macOS version: 10.13.3
BetterTouchTool version: 2.402

**Comment by fifafu** [comment]
Thanks for reporting, this should be fixed in v2.403!
