### ISSUE TITLE
Action "Brightness Up (External Display)" no longer working

### ISSUE THREAD

**Issue by o6sidian** [fifafu/BetterTouchTool#2228]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Instead of "Brightness Up (External Display)" BTT executes "Brightness Up".

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MBP TB 2016
macOS version: 10.13.3
BetterTouchTool version: 2.402

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird. Could you try version 2.403 I just uploaded?

How are you triggering it?

**Comment by o6sidian** [comment]
With 2.403 it works again, beautifully :-) Thank you!

For reference: I trigger it (both, external & internal display together) by Touchpad-Gesture ("3-Finger-Swipe-Up" / "...-Down").
