### ISSUE TITLE
Quick question: why and when are items in purple?

### ISSUE THREAD

**Issue by sebastienkb** [fifafu/BetterTouchTool#2229]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Some items in the lists are in purple, and some in black. Why is that? Is there something to do? I have not found the word "purple" in the issues, the github repo, the main website nor on https://docs.bettertouchtool.net

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Any items in the commands lists

#### Device information:

Type of Mac: Seen on MacBook, Mac Mini and iMac
macOS version: High Sierra
BetterTouchTool version: 2.402 (753)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://user-images.githubusercontent.com/5427924/37335973-43c9a4ba-26b0-11e8-972c-8074d4d79139.png)

Note: Experimental Dropbox sync is enabled

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Currently items not in the current master preset are displayed purple. I'll add an option to select the preset color with one of the next updates though.

**Comment by sebastienkb** [comment]
is it true that, by definition, a dropbox-synced configuration is **not** on the master preset, or is this mere assumption?
No need to worry when there is some purple then?

Thanks

**Comment by fifafu** [comment]
When you initially merge two different configurations by syncing, BTT will put the existing configs in different presets and set the master to that of the syncing computer. This is done to prevent conflicts when merging two different config sets.

If you want to get rid of the purple you can put everything into one preset (click the manage presets button to see all your presets). However this would need to be done manually. (So you would make the preset that contains more settings the master and then add the triggers from the other preset one by one).

However there are no disadvantages other than the color by using your current setup :-)
