### ISSUE TITLE
Widgets on control strip

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#223]
#### Description of your feature request...:
Would it be possible to have the widgets such as the battery life or time, show on the control strip? I know the BTT icon can be added there but if the time can be put in the control strip it would be the best.

**Comment by fabien88** [comment]
It's already available in latest alpha version 1.980 😊
<img width="506" alt="capture d ecran 2017-01-09 a 12 23 03" src="https://cloud.githubusercontent.com/assets/279377/21765002/6cc2c22a-d666-11e6-8245-37ec953617be.png">

**Comment by pallavmac** [comment]
@fabien88 Control Strip is not the same as the touchbar

**Comment by fabien88** [comment]
oh yes, my bad !

**Comment by fifafu** [comment]
Unfortunately modifying the control strip is not possible to to api limitations. (Only a button with an icon works)
