### ISSUE TITLE
BetterTouchTool Permissions in Security & Privacy

### ISSUE THREAD

**Issue by Wobber91** [fifafu/BetterTouchTool#2233]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Whenever I scroll with 3 fingers (Up/down/left/right doesn't matter), the notice to add BTT in the security&privacy in settings appear. Eventhough I already allowed it to make changes to my mac. 
I have the option to select text with 3 fingers or move windows in the mac settings itself. But the notice every time is veeeeery annoying.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro 9,1
macOS version: 10.13.3
BetterTouchTool version: 2.403 (754)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
try to disable & reenable it, then restart btt.
Unfortunately macOS sometimes forgets about the setting :-(

**Comment by Wobber91** [comment]
Ah alright. Tried it already last week when it happened, it helped. Now did it again with the notice opened and now the text changed that BTT is ready to work (smt like that).
It doesn't pop up anymore, but I don't know how long it will take this time.

Thanks for the VERY quick response ;)

**Comment by fifafu** [comment]
I think it's related to updates, let me know if you can see any pattern when this happens to you!
