### ISSUE TITLE
Keyboard shortcuts don't work after update

### ISSUE THREAD

**Issue by JuiceL** [fifafu/BetterTouchTool#2236]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

After updating to version 2.403 (754), my keyboard shortcuts no longer work.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook pro

#### Device information:

Type of Mac: Macbook pro
macOS version: 10.13.3 
BetterTouchTool version:  2.403 (754)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See https://github.com/fifafu/BetterTouchTool/issues/2185
