### ISSUE TITLE
15" MBP Touchbar - "esc" key not working

### ISSUE THREAD

**Issue by dmultimediab** [fifafu/BetterTouchTool#2240]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm on a MacBook Pro (15-inch, 2017 with touchbar), running MacOS 10.12.6 (16G29).
Since the Feb 6 update (I believe), the escape key that the touchbar controls add does not work. If I close the BTT layout and use the OS default, that escape key does work. Other keys (including custom) seem to work fine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:

Type of Mac: MacBookPro14,3
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.403 (754) and previous regular release

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Workaround: Close BTT touchbar controls and use OS default.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Seems to work fine here.
Any specific app where it doesn't work?

**Comment by dmultimediab** [comment]
It happens in all applications, including the Finder (discovered it trying to use "cmd-opt-esc"). To verify where the failure was occurring, I turned on the haptic feedback for the touchbar buttons, and all of them trigger the feedback except for the "esc".
		
		

		-Dan Bartell
dmultimediab@gmail.com
	




On Wed, Mar 14, 2018 at 8:49 AM -0600, "Andreas Hegenberg" <notifications@github.com> wrote:












Seems to work fine here.

Any specific app where it doesn't work?

**Comment by fifafu** [comment]
That's a different issue. The haptic feedback has been added to esc in the latest alpha :-)

Also unfortunately Apple restricts opt+cmd+esc from being triggered programatically. This is indeed only possible with the real ESC button.

**Comment by dmultimediab** [comment]
It's not JUST the haptic feedback. The actual functionality of the key (regardless of use within an application or the Finder) is not working. Furthermore, prior to the last two BTT updates, it did indeed work as expected.
		
		

		-Dan Bartell
dmultimediab@gmail.com
	




On Wed, Mar 14, 2018 at 10:11 AM -0600, "Andreas Hegenberg" <notifications@github.com> wrote:












That's a different issue. The haptic feedback has been added to esc in the latest alpha :-)


Also unfortunately Apple restricts opt+cmd+esc from being triggered programatically. This is indeed only possible with the real ESC button.

**Comment by fifafu** [comment]
Could you try whether the most recent alpha  (v2.405, get via "Check for alpha version updates") changes anything? Maybe I accidentally fixed it already and can not reproduce it because of that :-)

**Comment by dmultimediab** [comment]
The haptic feedback and functionality do indeed seem to work under this
version. The only functionality that still doesn't work (that used to) is
"cmd-opt-esc".

**Comment by fifafu** [comment]
Should now be working!
