### ISSUE TITLE
Doesn't send text to apps running in Microsoft Remote Desktop

### ISSUE THREAD

**Issue by nomadkupa** [fifafu/BetterTouchTool#2242]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Instead of sending the typed text as it works in all MacOS apps it sends "aaaa" letters 
See screenshots and video in the end.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad

#### Device information:

Type of Mac:
macOS version: 10.13.3
BetterTouchTool version: 2.403 (754)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

https://www.screencast.com/t/bQOVshmJ3 
https://www.screencast.com/t/rZfgz9Yim
![2018-03-13_17-09-17](https://user-images.githubusercontent.com/30003750/37372746-dfbbaf36-26e1-11e8-9ea7-c5afd4bc1739.png)
![2018-03-13_17-11-13](https://user-images.githubusercontent.com/30003750/37372768-ee4b736a-26e1-11e8-83d1-4df317e4a86c.gif)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
sorry I currently don't think I'll be able to fix this in BTT.

Microsoft would need to update the Remote Desktop App to support the default macOS event handling, but that's probably not gonna happen.

**Comment by nomadkupa** [comment]
I got it. Unfortunately. Thank you.
