### ISSUE TITLE
Modifier + Mouse Click doesn’t work as usual

### ISSUE THREAD

**Issue by elprohabro** [fifafu/BetterTouchTool#2244]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Can’t repeat action on modifier + click anymore. 

E.g. previously I pressed cmd-opt-click to zoom out in app. (by simply holding cmd-opt and then clicking as many times as I want the action to repeat). Now to repeat the action I have to release keyboard modifiers too (so for every repeat I have to cmd-opt-click, cmd-opt-click, cmd-opt-click, cmd-opt-click. It’s as annoying as to read this.)

Unfortunately, switching to ”Old keyboard shortcut implementation” doesn’t solve the issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Apple Keyboard + Normal mouse (MX Master)

#### Device information:

Type of Mac: iMac 27'' late 2012
macOS version: 10.11.6
BetterTouchTool version:  2.403

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Nothing to add, except "please fix this" as it completely ruined my workflow. (Or is it possible to downgrade to previous version somehow?)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by mpaneghel** [comment]
Same thing here, the following setup stopped working in 2.403:

- Opt key down when "button 3" down
- Opt key up when "button 3" up
- Do something when "opt+right click"

The "Do something" doesn't happen anymore. Reverting to the previous version solved the issue.

**Comment by fifafu** [comment]
I believe this is fixed in 2.405, could you test? (get via "check for alpha version updates")

**Comment by elprohabro** [comment]
It’s fixed, thank you!
