### ISSUE TITLE
After switch the windows ctrl + tab, cpu becomes 100%

### ISSUE THREAD

**Issue by pokk** [fifafu/BetterTouchTool#2245]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I updated to version 2.343. When I switched to others window by `ctrl + tab`, the cpu usage becomes 100% suddenly. I don't use the apple script or other scripts.
But version 2.340 works really well, only 2.343 and 2.344 will happen this problem.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Keyboard

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017) with Touch Bar
macOS version: 10.13.3
BetterTouchTool version: 2.343

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I expect 2.343 can work well because there is a feature for fn key. Thank you very much!

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com then I'll look into it.

**Comment by pokk** [comment]
I've sent the report. Please have a look. 🙏

**Comment by pokk** [comment]
@fifafu 

I'm so sorry for this issue. I was so stupid to set the kind of looping instructions, that's why when I use `cmd + tab` cause looping instructions happens. :(
