### ISSUE TITLE
App specific - arrow key inputs not working

### ISSUE THREAD

**Issue by tharrisw** [fifafu/BetterTouchTool#2247]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Up until the most recent version of BTT, any shortcuts that sent the left or right arrow key to RSS app Reeder could navigate the interface fine.  With the most recent BTT update, reeder interprets all right or left arrow keys inputs in text input fields fine, but to move back and forth between panes, as one can with the actual arrow keys, does not work.  This is true regardless of the gesture or keyboard shortcut being used to send the arrow key inputs.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
I have tried remapping other keyboard keys and various trackpad gestures to arrow keys, none of which work

#### Device information:

Type of Mac: MBP (2017)
macOS version: 10.13.2
BetterTouchTool version: 2.403 (754)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you test how v 2.405 behaves with reeder? (get via "check for alpha version updates")

**Comment by tharrisw** [comment]
Updated to 2.405 and rebooted the computer - still the same behavior unfortunately.

**Comment by fifafu** [comment]
Weird. It seems to work correctly in all apps I have tested so far (e.g. Finder).
Do you experience this only in Reeder?

**Comment by tharrisw** [comment]
Yes, only reeder.  All other apps work fine for arrow keys, and even in reeder in text input fields (like the search bar) it seems to work as well.  But in the reading panes, I can hit the right arrow on the keyboard to load a story, but when I gesture to send a right arrow input (or remap, say, the space bar to do the same), it doesn't work. It was working until I updated BTT to 2.403.

**Comment by fifafu** [comment]
Ok strange. Then for now the only solution is to downgrade (https://bettertouchtool.net/releases/btt2.340.zip )

Maybe Reeder intercepts the events at a lower point than BTT uses now - I had to move one layer higher to improve compatibility with other macOS features.

Is there maybe a way to trigger the functionality you need using a menubar item? Then you could use the "Trigger Menubar Menu-Item" action instead.

**Comment by tharrisw** [comment]
Downgrading fixed it, working as expected now.  I wish there another way to trigger the functionality!  Reeder is very good about letting you remap just about any feature within reeder itself, with the one exception of the arrow keys.  There's no way to trigger via menu either that I saw.  I'll just stick to the older version of BTT for now.  Thanks!

**Comment by ryanneufeld** [comment]
Adding a Me-too here. As soon as I updated, my global arrow based shortcuts failed.


[BTTSettings.json.txt](https://github.com/fifafu/BetterTouchTool/files/1813260/BTTSettings.json.txt)

**Comment by fifafu** [comment]
@ryanneufeld your issue is different, @tharrisw had issues **sending** arrow keys to an app. 

Unfortunately your setup seem to work fine on my machines (BTT 2.405). What kind of keyboard are you using?
This may not be fixable as some systems seem to have some issues with the new shortcut implementation (I don't know why, it seems to affect super few users but for those nothing seems to help). Thus you may need to switch back to the old shortcut implementation, see this screenshot:

![image](https://user-images.githubusercontent.com/8820811/37454087-e85823a0-2839-11e8-8624-d430ee98d7ec.png)

**Comment by fifafu** [comment]
@tharrisw could you check whether BTT 2.410 fixes your issue?

**Comment by tharrisw** [comment]
Hi, I just installed 2.412 and it did indeed solve the issue.  Thank you very much!
