### ISSUE TITLE
Compatibility issues: BTT and Skim (both fully updated)

### ISSUE THREAD

**Issue by NagUNEH** [fifafu/BetterTouchTool#2249]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Keyboard shortcuts broken for BTT in Skim PDF reader app (https://skim-app.sourceforge.io)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Air keyboard shortcuts

#### Device information:

Type of Mac: MacBook Air (13-inch, Early 2014)
macOS version: 10.12.6（16G29）
BetterTouchTool version: 2.405 (756)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
[Summary]
Since recent update (previous version: 2.304?) of BTT, BTT doesn't play well with Skim (v. 1.4.32 (106)). 

[Details]
Previously working keyboard shortcuts are broken:

⌘+Fn+← = maximize left = OK
⌘+Fn+→ = maximize right, but actually maximizes left on first press, then right on second
⌘+Fn+↓ = maximize to next monitor = OK
⌘+Fn+↑ = maximize = incremental size increase (3-4 times or more) before finally maximizing
* Additionally, right maxed windows require 10 (!!) key presses to maximize to window. Only left maxed windows maximize to window on one press.

These issues don't affect other applications, including (no particular order, what I have open now) Chrome, Zotero, Finder, etc. Microsoft Word sometimes exhibits odd behavior, but this seems to be related to search, so I probably have a duplicate shortcut. This is not the case w/ Skim, though.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to work fine here. Have you already tried to restart your Mac?
I don't think there has been a change to the resizing functionalities. :-/

**Comment by fifafu** [comment]
Maybe try v2.407, I have made some small adjustments to the keyboard handling there.

However I unfortunately can't reproduce this at all :-(

**Comment by fifafu** [comment]
Should be working in current alphas
