### ISSUE TITLE
Crashing repeatedly

### ISSUE THREAD

**Issue by rozling** [fifafu/BetterTouchTool#225]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

Multiple emails sent, no response since 14/12

#### Description of your bug/question/feature request...:

BTT is crashing/quitting many times per day, often within minutes of relaunching.
The 'About' screen shows that the copy is licensed to my name.

I was getting the 'Code Signature Broken' error which specifically says to contact support at boastr.net@gmail.com

**What kind of Mac are you using?**

Macbook Pro Retina Mid 2012

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

All

**Which versions of macOS and BetterTouchTool are you running?**

MacOS Sierra 10.12.2
1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

Cannot find any crashlogs - am getting a lot of the following in Console.app:
`default	16:18:18.761013 +0200	BetterTouchTool	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG`

Also seeing this:
`default	16:18:18.609552 +0200	BetterTouchTool	MacOS error: -67052`

**Comment by csmarshall** [comment]
Getting the same errors as well :/

**Comment by mipmapman** [comment]
I'm getting this as well.

**Comment by mipmapman** [comment]
Cannot find any crashlogs.

Also getting these logs which might be related to the crashing: 

```
Jun  9 08:56:25 mechagodzilla com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.134164[11630]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[11651]
Jun  9 09:58:18 mechagodzilla com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.134164[11654]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[13436]
Jun  9 18:04:38 mechagodzilla BetterTouchTool[12967]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
Jun  9 18:05:22 mechagodzilla com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.134164[12969]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[12967]
```

**Comment by fifafu** [comment]
@mipmapman in your case BTT binary is definitely damaged. Where did you download it?

Try downloading a fresh copy from my website : https://boastr.net/downloads 

If that doesn't help try to restart your machine. Do you have a valid license installed?

**Comment by fifafu** [comment]
Ah sorr I mixed up a crashlog. In your case I can't really say what's causing it Yet :-)
