### ISSUE TITLE
Export Presets + Sync Swapping Scroll Left & Scroll Right

### ISSUE THREAD

**Issue by yaseent** [fifafu/BetterTouchTool#2250]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
So I decided to export my presets from my Mac Mini to my MacBook Air. And all of the Normal Mouse gestures that have a Scroll Left on the Mac Mini were swapped with Scroll Right on the MacBook Air. And all the ones with Scroll Right were swapped with Scroll Left.

Which is super weird. Using the same model mouse on both machines. All I do is change it back on the MacBook Air, and no problem.

But then when I enabled sync, I see this does the same thing. And the problem with sync is that it constantly syncs gestures etc etc. So everytime it syncs, it does the swap.

I tried it the other way around as well, and the Mac Mini swaps gestures around imported from the Air.

Super confused.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Microsoft Sculpt Touch (Bluetooth Mouse) x2

#### Device information:

Type of Mac: MacBook Air / Mac Mini
macOS version: 10.13.3
BetterTouchTool version: 2.4 / 2.403

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sounds like you have inverse scrolling enabled on one machine but not on the other.

I think it's called "natural scrolling" and can be set in System Preferences => Mouse

**Comment by yaseent** [comment]
OMG I DIDN'T EVEN THINK OF THIS. I use the app Scroll Reverser on my MacBook air to get UNNATURAL scrolling on my mouse but I prefer NATURAL scrolling on my Trackpad. LOL. So sorry, thanks :)

**Comment by fifafu** [comment]
You could try this option instead of using scroll reverser:

![image](https://user-images.githubusercontent.com/8820811/37457442-4fb96c9a-2842-11e8-82da-218d1e58b312.png)

**Comment by yaseent** [comment]
Yes 😄

I noticed that option about a week ago when I was digging through BTT settings, but decided to just keep Scroll Reverser as it was working fine.

But now I can use this option instead 😝 Tnx 🥇
