### ISSUE TITLE
New shortcut implementation breaks Home and End keys 

### ISSUE THREAD

**Issue by damga** [fifafu/BetterTouchTool#2253]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have following shortcuts defined:
Home  ->  ^A
End      ->  ^E

Old implementation: When I pressed Home - only cursor would go to begging of line as per ^A. 
New implementation: Now when I press Home, page scrolls up (regular behavior on Mac) and only if there is no room to go any more up, only then the cursor can move to the begging of line.
And similar thing happens with End

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mac Keyboard

#### Device information:

Type of Mac: MBPro 15 2016
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.403

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Seems to work fine here. Could you try re-recording the shortcuts? It's possible that previous versions didn't collect enough event data to describe the key correctly.

**Comment by damga** [comment]
Ok, checking "old implementation", restart, unchecking, restart and it works fine again with new implementation, I did not re-add shortcuts.
