### ISSUE TITLE
Issues with TotalFinder after upgrade to BTT 2.405

### ISSUE THREAD

**Issue by geirgot** [fifafu/BetterTouchTool#2255]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I use tip-tap gestures in my web browser to switch between tabs. Since upgrading to 2.405 tip-tap performs as intended in the browser, but in addition it opens up the TotalFinder window, and brings it to the foreground. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad.

#### Device information:

Type of Mac: MacBook Air 13 inch (2.2 GHz Intel Core i7)
macOS version: 10.12.6
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Latest version of BTT installed, system has been restarted. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mh BTT has nothing to do with Total Finder. Do you maybe somewhere have a shortcut defined to show Finder/Total Finder?

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com (reference this issue) then I'll look into it.

**Comment by geirgot** [comment]
Hi!
Thanks for the swift follow-up - much appreciated! I realise that BTT has nothing to do with TotalFinder, but the issue arose immediately after updating to BTT version 2.405, without any other changes being made to the system.

There is indeed a shortcut to show Finder/Total Finder, but only a keyboard one (Cmd + Cmd). I'll follow the instructions re. debug export, and send it to you via email. Thanks!

Kind regards,
Geir

**Comment by fifafu** [comment]
Hi Geir,

I can't seem to find the FInder /Total Finder shortcut you have configured - did you delete it before sending the debug info to me?

It seems to behave correctly.If you press opt+cmd+arrow left/right on the keyboard, this doesn't happen?

**Comment by geirgot** [comment]
Hi Andreas,
No, I didn't delete anything.

I'm using Vivaldi as my default browser, and the keyboard sequence to move
between tabs is slightly different. However, I have set up all my browsers
(Vivaldi, Chrome and Safari) to respond to the tip-tap gesture for moving
one tab left/right, and the same thing happens in all of them; the gesture
works as intended (i.e. move left/right one tab), but in addition opens up
the TotalFinder window, and brings it to the foreground. BTT is the only
app (as far as I know) where I can define the tip-tap gesture, so I'm at a
bit of a loss when it comes to solving this issue.

Kind regards,
Geir

PS. I have included a new debug folder. The only difference from the one I
sent you yesterday is that I created it while the Finder/TotalFinder window
was open and in front of the browser window.

**Comment by geirgot** [comment]
Update:

If I disable the Cmd+Cmd shortcut that I have used in the past to open
Finder/TotalFinder, and instead define a different keyboard shortcut, the
issue disappears. In other words the BTT tip-tap shortcut seems to do two
things at the same time: (1) moves between tabs, and (2) opens
Finder/TotalFinder. This didn't happen prior to my updating to the latest
version of BTT, and I haven't defined any shortcuts related to Finder in
BTT. What is even more puzzling is that I have two different Browser
tip-tap gestures, one to move one tab to the left, and another to move one
tab to the right. Both of these gestures open the Finder/TotalFinder
window.

Kind regards,
Geir

**Comment by fifafu** [comment]
Sorry I still can't seem to find the cmd+cmd shortcut you are mentioning. Where is it defined?

(if you want to send me a new debug folder you'll need to do so via email to boastr.net@gmail.com, Github removes these kind of attachments)

**Comment by fifafu** [comment]
Please try v2.407 alpha (get via check for alpha version updates)

**Comment by geirgot** [comment]
Yes, that solved the issue!

Thanks!

Geir



On Fri, Mar 16, 2018 at 4:45 PM, Andreas Hegenberg <notifications@github.com
