### ISSUE TITLE
BTT Privacy Permissions Window Constantly Propogating - Mac High Sierra

### ISSUE THREAD

**Issue by ScriptKiddie1337** [fifafu/BetterTouchTool#2256]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When BTT Starts up I get continual notifications to give BTT permission to control parts of my computer.  The permission has been granted, but the notifications and pop up windows still continue.

How do I stop the privacy notifications from appearing?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
No input device affected.

#### Device information:

Type of Mac: Air
macOS version: High Sierra
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately the current macOS version has a bug that sometimes causes it to forget this is set. Try unchecking and re-checking, then restarting BTT.
