### ISSUE TITLE
BTT keyboard shortcuts stopped working! 

### ISSUE THREAD

**Issue by eltown** [fifafu/BetterTouchTool#2257]
#### Description of bug/feature request/question:

All keyboard shortcuts stopped working. Restarting computer, restarting BTT, updating to latest version, and uninstalling and re-installing have not fixed the problem. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.13.3
BetterTouchTool version: 2.405 (756)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #2185

**Comment by eltown** [comment]
Thanks - solution in that ticket worked!
