### ISSUE TITLE
Checking "Allow crash log collection" also checks "Enable automatic update checking"

### ISSUE THREAD

**Issue by ErikMinekus** [fifafu/BetterTouchTool#2258]
#### Description of bug/feature request/question:

Checking and unchecking "Allow crash log and anonymized usage data collection" (under Advanced Settings > General Settings) also checks/unchecks "Enable automatic update checking".

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

N/A

#### Device information:

Type of Mac: 15" MacBook Pro 2016
macOS version: 10.13.3
BetterTouchTool version: 2.405

**Comment by fifafu** [comment]
Oops, thanks for reporting! Shouldn't copy & paste checkboxes :-)

**Comment by fifafu** [comment]
Fixed with next alpha.
