### ISSUE TITLE
Keyboard shortcuts no longer working

### ISSUE THREAD

**Issue by cranecj** [fifafu/BetterTouchTool#2259]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Keyboard shortcuts not working at all. I have several keyboard shortcuts set up with both the function keys and with other keys and with the most recent update, they all stopped working. 
![image](https://user-images.githubusercontent.com/702246/37487171-fe957b36-284d-11e8-8013-f90995c2e79a.png)

Before this update, all of the shortcuts worked great, and I did not change anything. All of the other BTT features still work great (Touchpad, Window snapping, mouse shortcuts etc). I tried restarting BTT, restarting my computer, deleting and reinstalling BTT. Nothing has worked so far. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard (both external and internal)

#### Device information:

Type of Mac: 13" Macbook Pro 2016 with touchbar 
macOS version: 10.13.3
BetterTouchTool version: 2.405 (756)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See #2185 :-)
