### ISSUE TITLE
App default Touchbar missing

### ISSUE THREAD

**Issue by tekavc** [fifafu/BetterTouchTool#226]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I am setting up the BTT for the first time and I have a few buttons set under "Global" and if I switch to an app like Safari (that supports TouchBar by default) nothing changes; menaning that the Global buttons are overlayed above the default Safari touchbar controls.
I have tried adding Safari to the application list and selected "Show App default touch bar" but it does not work.
App specific controls flash for a split second and are than overlyed by the Global buttons.

Is there a setting I am missing or is this a bug in the current version?

**What kind of Mac are you using?**
Macbook Pro 13 late 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
MacOS Sierra 10.12.2

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Could you check if update 1.981 fixes this?

**Comment by tekavc** [comment]
Thank you for the swift action. Tried 1.981 version. I can confirm that the new version fixes the bug, however all apps (with native Touchbar support) have to be added manually to the application list in order to set "Show App default touch bar" in app specific touch bar behavior.

Perhaps in future versions you could also consider a general setting as in:
"Show App default touch bar controls for apps that have touch bar controls" (BTT General buttons are disabled in apps that offer native touchbar controls)

I do not know if this is even possible but as I assume that more and more apps will be supporting touchbar, setting-up BTT is going to become quite hard without this option...

The latter is just a thought/feature proposal. The app is really amazing and feels and works like it was built by Apple and probably should be from the beginning.

**Comment by fifafu** [comment]
You could also do it the other way around, select one of the "Show BTT Touch Bar" options for those apps where you want to use it. Unfortunately there is no way to check whether an app has Touch Bar support.
