### ISSUE TITLE
keyboard shortcut not working for ITerm2 but for other apps (e.g., Safari)

### ISSUE THREAD

**Issue by weixie4** [fifafu/BetterTouchTool#2260]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After the very recent update of BetterTouchTool that rewrote the Keyboard functionality, I found all of my BTT Keyboard shortcuts that were set to "Execute Terminal Command" stopped working when Iterm2 ( 3.1.6beta4) is the upfront app. If pull a window of other apps, like Safari to upfront and press one of such keyboard shortcuts, then the designated Terminal command was executed as expected. This issue only started after I updated BTT to the version that had new Keyboard functionality.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
This issue affects both internal keyboard of MacBook Pro and external apple wired keyboard.

#### Device information:

Type of Mac: 2015 Macbook Pro 15
macOS version: 10.13.3
BetterTouchTool version: 2.403(754)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com (referncing his issue) then I'll look into it.

For now maybe just enable the old keyboard shortcut implementation:
![image](https://user-images.githubusercontent.com/8820811/37491790-39524910-289f-11e8-8809-9a9fe15fda11.png)

**Comment by weixie4** [comment]
Thanks Andreas. Just did it.

**Comment by fifafu** [comment]
Weird, seems to be working fine here.
Could you check whether the shortcuts in general are not recognized? (E.g. by enabling and overlay hud)

![image](https://user-images.githubusercontent.com/8820811/37492211-d4474546-28a0-11e8-92ca-078bf4c3c901.png)

**Comment by weixie4** [comment]
Hi Andreas. Sure. I confirmed that if I press the shortcut while working on iTerm2 no HUD overly came up, but if I do it elsewhere (I tried iMessage, Excel, Finder, Mail, Calendar, Safari, Chrome),  it works and a HUD overly came up.

**Comment by fifafu** [comment]
One question:
Is Secure Key Entry enabled on your iTerm?

![image](https://user-images.githubusercontent.com/8820811/37493935-0532560e-28a7-11e8-8665-c5583c6c39a7.png)

I think this may cause the issue as BTT then doesn't get access to the keyboard events anymore.

**Comment by weixie4** [comment]
Hi Andreas. Exactly, this was the root of the problem. After I turn off Secure Keyboard Entry, all keyboard shortcuts now work fine in Iterm2. Thanks a lot for the help!

**Comment by sillyfrog** [comment]
I had exactly the same issue, and the fix was also the same (disabling "Secure Keyboard Entry" in iTerm). Makes sense when you think about it, but took me _ages_ to figure out. Thanks!
