### ISSUE TITLE
Pressing "Home" key has recently been triggering as "fn ↖" not simply "↖"

### ISSUE THREAD

**Issue by arkban** [fifafu/BetterTouchTool#2266]
#### Description of bug/feature request/question:

I have a standard 104 style keyboard. I've been using BTT to map the "Home" key -- which BTT recognizes as "↖" -- to the Mac equivalent "⌘ ←" (and visa versa for "End"). But recently BTT has been recognizing the "Home" key as not simply "↖" but "fn ↖", as if the "fn" key is held down.

It seems to only do this for some keyboard actions: "Home", "End", "Insert". But "Page Up" and "Page Down" are unaffected.

I'm not sure this is only a BTT problem or not. TBH I'm not sure how to determine that.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Standard 104 USB keyboard

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.405

**Comment by fifafu** [comment]
This is expected. The system automatically adds the fn key to these keys. In previous versions BTT didn't show that, but because BTT now supports the FN key in keyboard shortcuts it is being shown.

However it shouldn't have any effect on the trigger.

**Comment by antontsvil** [comment]
It does have an effect - you have to re-input the shortcut in order for it to work. Not a big deal, but it would have been nice if after updating the home/end keys were updated to include the function key.

**Comment by fifafu** [comment]
Mhm it shouldn't :-/
I have just tried setting up the keys with an old version, then upgrading to the new one and it kept working.

Maybe it was a bug in an earlier 2.40x version that has already been fixed.

**Comment by OktarinTentakel** [comment]
I have the same problem with the current stable and alpha.

These exact bindings worked for years and stopped doing so last week.

![bildschirmfoto 2018-03-19 um 11 08 13](https://user-images.githubusercontent.com/4561418/37589603-0a26d632-2b66-11e8-9d24-2d761628bb8d.png)

**Comment by OktarinTentakel** [comment]
resetting the up/down keys now register as fn up/down, which seems to work

is this intended behaviour?

**Comment by fifafu** [comment]
Yes, however it should not have broken your existing setup.

It's possible that a very old version of BTT didn't record the complete key data. I'll check that. Re-recording the broken shortcuts should definitely fix it though.

**Comment by arkban** [comment]
> Yes, however it should not have broken your existing setup.

It definitely broke the old bindings (that's what spurned me to open this issue).

> It's possible that a very old version of BTT didn't record the complete key data. 

That is possible - I've been using BTT for at least a year now.

> Re-recording the broken shortcuts should definitely fix it though.

That does indeed work.
