### ISSUE TITLE
NSSQLiteErrorDomain error 8

### ISSUE THREAD

**Issue by soumyaray** [fifafu/BetterTouchTool#2268]
I constantly get popups from BTT saying:
"The operation couldn’t be completed. (NSSQLiteErrorDomain error 8.)"

Type of Mac: Macbook Pro
macOS version: 10.13.3 (17D47)
BetterTouchTool version: 2.405 (756)

I've restarted my machine frequently and updated to the latest version of BTT

**Comment by fifafu** [comment]
See #2118
