### ISSUE TITLE
Touch command activating when closing lid

### ISSUE THREAD

**Issue by BonfiresDown** [fifafu/BetterTouchTool#2269]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have 3 finger touch set to Cmd+W (close window) and it normally works fine. But every time I close the Macbook lid that command starts activating by itself, usually a number times before it stops. If I turn off BTT or change the command everything is ok.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook trackpad

#### Device information:

Type of Mac: Macbook Pro mid 2014
macOS version: 10.13.3
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately there is no real fix for this.
BTT doesn't get a notification from the system when the display is going to close, and unfortunately the display being near to the trackpad causes "phantom" touches on some systems.

BTT checks every 10 seconds whether the lid is closed (unfortunately this operation requires some CPU, thus I'm not doing it more often). I can add an option to execute the check more often with the next version.

This doesn't happen on all Macbooks, but on some models the display seems to be "too near" to the trackpad.

**Comment by fifafu** [comment]
actually I have found a way to recognize much faster whether the lid is being closed.
In version 2.410 (alpha) it does the check much more often without negative performance impacts. 

It may still cause occasional issues, but it probably won't get better than that.
