### ISSUE TITLE
Next/Previous BTT actions not working for iTunes

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#227]
#### Description of your bug:
I have a keyboard action setup to skip songs using the previous/next options in BTT. 
But these for some reason only control spotify and not iTunes. Something wrong on my side?

**What kind of Mac are you using?**
15" Touchbar

**Comment by fifafu** [comment]
I recently noticed that Spotify is consuming these keypresses and blocking iTunes while it is running. Maybe this is the issue you encountered?
