### ISSUE TITLE
Latest version on Mac OS High Sierra keeps crashing

### ISSUE THREAD

**Issue by imdadahad** [fifafu/BetterTouchTool#2272]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Please provide more information and if possible crashlogs from Console.app => User Reports

**Comment by imdadahad** [comment]
It was working fine until I got a notification for an update, for which I accepted and installed. The version is 2.405 (756).

Here is the crash report: https://pastebin.com/Tu1p1pqh

**Comment by fifafu** [comment]
It seems to be repeating a shortcut many times before crashing - do you have any shortcut configured with "repeat on key-down" enabled?

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com and reference this issue then I'll look into it.

**Comment by imdadahad** [comment]
Sure thing, sending it over now 👍

**Comment by fifafu** [comment]
Could you try updating to the latest alpha version (v2.411) via "check for alpha version updates"?

I can't seem to reproduce the issue here. Does it always crash for you or only after doing something specific?
