### ISSUE TITLE
Move Window To Desktop / Switch to Desktop: Feedback / request

### ISSUE THREAD

**Issue by TheBloke** [fifafu/BetterTouchTool#2273]
Firstly, thanks for adding these new actions!  I'm particularly excited by Move Window To Desktop.  This is a great feature that I've hoped for for some time.

It's also great to see that the new Move Window To Desktop actions can be chained with other appropriate actions.  For example I can do `Move Window To Desktop 1` followed by `Maximise Left Half` and it works just as intended.

#### Description of feature request:

You may be planning this already, but it would be great if instead of having separate actions per Display, there could be single actions "Move Window To Desktop" and "Switch to Desktop", with a cog icon for configuration.  Then allow entering of any number 1 to 99.   (If the user enters a number that is invalid at runtime, I'd suggest that the action simply does not excute.)

Right now I have 18 desktops configured (across five monitors), so I can't access them all with a static 1-9.  Plus it would be neater in the dropdown to have a single configurable action.

Or if you like having separate actions, then I'd request an additional configurable action for each operation.  So ten actions for each operation: static 1-9, and then a configurable action that supports 1-99 (or at least 1-32 or similar high number.)

Thanks again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

#### Device information:

Type of Mac: MP 5.1
macOS version: 10.13.4 Beta5
BetterTouchTool version:  2.410

**Comment by fifafu** [comment]
Hey,

sorry I probably won't change this (for now).
The actions are currently very simple and just trigger the apple shortcuts in System Preferences => Keyboard => Shortcut. Unfortunately Apple only has them ranging from 1-9.

The problem is that there is no public API for moving spaces and windows to spaces and I'd rather not get into the private API for now. There are other tools that are dedicated to this and have many years of experience with this private API (https://totalspaces.binaryage.com/ maybe)

**Comment by TheBloke** [comment]
OK I understand.  Actually I already own TotalSpaces, it's nice software and yes it alters macOS' handling of spaces at a low level (user now has to disable SIP to even install it).  It has a few keyboard shortcut options, like the ability to move a window left/right/up/down a space.  But doesn't provide an option to move a window or switch to a specific numbered space.   I might contact them to ask if they would add that, then I could have BTT trigger TotalSpaces.

At the least could you expand it up to Desktop 16?  macOS' will automatically expand the keyboard shortcuts up to 16 displays:
<img width="415" alt="screenshot_2018-03-18 12 25 35_mspylg" src="https://user-images.githubusercontent.com/784313/37565778-979192a6-2aa7-11e8-88a6-af26199e304c.png">

I think it adds them automatically as new Spaces are added (up to a limit of 16), as long as the shortcut is enabled for Switch to Desktop 1.  That's what Google is telling me - I've had 16 in that list for a couple of years and don't now remember if I had to do anything to make the extras appear, but it seems I probably did not.

Thanks.

**Comment by fifafu** [comment]
Ah that's interesting, yep then I will add the 16 options :-)

**Comment by TheBloke** [comment]
Thanks very much :)
