### ISSUE TITLE
Replaced "esc" key with "`", but won't work for Force Quit Applications window (⌥⌘⎋).

### ISSUE THREAD

**Issue by rcolsm** [fifafu/BetterTouchTool#2274]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I set up BTT to trigger the "⎋" (esc) key with "`" (back quote) key as I'm not using it.
But whenever I want to use the "Force Quit Application" window, it won't appear by pressing "⌥⌘`" (option+command+`). I already set up a shortcut "⌥⌘`" (option+command+`) to trigger action "⌥⌘⎋" (option+command+esc) but still the "Force Quit Applications" window.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Pro Touch Bar
macOS version: 10.12.6
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Screenshot of BTT setup
<img width="1015" alt="screen shot 2018-03-18 at 3 10 25 pm" src="https://user-images.githubusercontent.com/14244755/37563942-8cad3ef0-2abe-11e8-8700-144f53415cbd.png">

Screenshot of Force Quit Applications window when pressing "⌥⌘⎋" (option+command+esc)
<img width="338" alt="screen shot 2018-03-18 at 3 15 17 pm" src="https://user-images.githubusercontent.com/14244755/37563973-3e84db74-2abf-11e8-8a0c-388ca207c3f1.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Your setup should work in 2.411 alpha ( get via check for alpha version updates)
