### ISSUE TITLE
Cursor drag ends when switching spaces via mouse binding

### ISSUE THREAD

**Issue by Adam0000** [fifafu/BetterTouchTool#2277]
#### Description of bug/feature request/question:
Until recently it was possible to bind mouse buttons to move between macOS spaces and you could drag windows or other items (e.g. files) to the new space. Now when you change spaces whatever you're dragging is automatically "let go of" on the new space. This appears to be specific to BTT because if I switch spaces via the keyboard with ctrl+arrow the windows continue to track my cursor.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MX Master mouse

#### Device information:
Type of Mac: MacBook Pro
macOS version: 10.12.6
BetterTouchTool version: 2.411 (761)

![image](https://user-images.githubusercontent.com/5590173/37570580-e135691c-2ac7-11e8-8530-b780e91df6cc.png)

**Comment by fifafu** [comment]
Would be great if you could check whether that works correctly with v2.412 alpha (get via "check for alpha version updates")

**Comment by Adam0000** [comment]
@fifafu Looks like it's fixed in v2.412. Thanks for this excellent tool.
