### ISSUE TITLE
Activation takes two taps if close button is used to close BTT Touch Bar

### ISSUE THREAD

**Issue by fitzage** [fifafu/BetterTouchTool#228]
#### Description of your bug/question/feature request...:

When the BTT Touch Bar is showing, if I close it by tapping the close button (the x in the circle at the left side), it requires two taps on the BTT icon to show it again. If I close it by tapping the BTT icon, it appears to only require one tap to show it again. This is the same for the force touch shortcut I set up on my trackpad to try to work around it.

So if the close button is used, BTT isn't recognizing that it was closed, so when the icon is tapped, it's closing the bar that's already closed. But if I close it with the BTT icon, then it realizes it's closed and allows a single tap to open it again. I hope that makes sense.

**What kind of Mac are you using?**

2016 13" MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**

macOS 10.12.2
BTT 1.980 (572)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

**Comment by fifafu** [comment]
Unfortunately not fixable currently, see e.g. #177
