### ISSUE TITLE
Disabling BTT for App does not work reliably in Alpha 2.412 (762)

### ISSUE THREAD

**Issue by OktarinTentakel** [fifafu/BetterTouchTool#2281]
#### Description of bug/feature request/question:

I have setup BTT to disable itself completely in iTerm2. Which it does. Until it doesn't. In that moment keyboard interrupts like ctrl+c will not work until I restart BTT. The reason I have to do this, is because I mapped ctrl+c globally to cmd+c to emulate linux-style c&p.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MacBook pro
macOS version: High Sierra
BetterTouchTool version: Alpha 2.412 (762)

**Comment by fifafu** [comment]
I will look into that :

Just one hint: it's more performant to add the ctrl+c action to iterm2 and select the predefined action "do nothing or use apple default ".

**Comment by OktarinTentakel** [comment]
BTW: this is a new problem I did not have until last week or even today (not absolutely sure on the date)

**Comment by OktarinTentakel** [comment]
Thx, I'll try that tomorrow, but there are several interrupts to catch here, so I thought: well, gotta catch em all :D

**Comment by OktarinTentakel** [comment]
Does not solve the problem I'm afraid.

Native shortcuts stop working after some time and make the terminal unusable. Setting the relevant shortcuts by hand and defining them as no-ops  as you suggested does not seem to change that.

Only restarting does.

**Comment by fifafu** [comment]
Do you have secure keyboard input enabled on iTerm?

![image](https://user-images.githubusercontent.com/8820811/37650633-c4118eaa-2c35-11e8-88a1-f4c4dcf8cc73.png)

**Comment by OktarinTentakel** [comment]
No, should I?

**Comment by fifafu** [comment]
Nope, just wondering what's causing this for you (because I can not reproduce it yet)

**Comment by OktarinTentakel** [comment]
I'm scratching my head as well. This literally worked for over a year and suddently ... nope.

**Comment by fifafu** [comment]
let's see, I'll do some more testing later today!

**Comment by fifafu** [comment]
Maybe try v2.414. I have made some little adjustments but I'm not sure whether they caused the issue.

Do you have any way to reproduce this problem? Does it happen randomly or after doing something specific?

**Comment by OktarinTentakel** [comment]
Another observation: the taskbar icon changes color correctly, but the original shortcut does not work in the focused terminal nonetheless. If I just trigger a BTT reload immediately focus the window again an wait for a second everything works as expected although the icon did not even have the time to update its color again.

**Comment by OktarinTentakel** [comment]
Testing the new Alpha now.

I could not yet pinpoint the exact moment when the behaviour changes, I'll keep you in the loop.

**Comment by OktarinTentakel** [comment]
Thanks for all the effort!

**Comment by OktarinTentakel** [comment]
Well, same picture today with the new Alpha I'm afraid.

**Comment by OktarinTentakel** [comment]
With the current version 2.422 (779) the problem does not occurr anymore. Whatever you did, for the moment the dragon seems to be slain.

**Comment by fifafu** [comment]
Ah very nice. I found a little logic issue and I think fixing that also fixed this issue!
