### ISSUE TITLE
Latest BTT version keyboard shortcut does not work anymore with Lightroom

### ISSUE THREAD

**Issue by antro31** [fifafu/BetterTouchTool#2282]
Hi all,

I am experiencing issues with latest version of BTT.
My keyboard shortcuts does not work any more, even with the tag "compatibility option" set.
I experienced this for Lightroom, since I have created specific shortcut for keyword.
Note that I have tried to restart my mac without success.

I had to revert back to previous version to make this work.

Could you please help in solving the latest issue ?

Thanks,

**Comment by fifafu** [comment]
Does this alao happen with the latest alpha version? (V2.412)?

**Comment by antro31** [comment]
Just tried, no. The issue seems to be fixed on the Alpha version.
Thanks for your help.
