### ISSUE TITLE
Pressing down Two modifiers

### ISSUE THREAD

**Issue by donileo** [fifafu/BetterTouchTool#2285]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

How can two modifiers be made to press down on mouse button activation. For example on press of mouse 3 I want Opt + Shift keyboard shortcut to press down so that I am free to press another key such as D or E or F to activate different commands. Currently BTT seems to support three modifiers or two modifiers and a regular key such as D but not two. 

Attempting to get the effect via sequential actions does not work.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal Mouse

#### Device information:

Type of Mac: 15" 2014 Macbook Pro
macOS version: 10.13.3
BetterTouchTool version: 2.412

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
N/A

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
There was an issue in 2.4x versions that caused this to break.
In general it should work like this:
![image](https://user-images.githubusercontent.com/8820811/37664132-fe599e02-2c5a-11e8-9934-4b9a85187f92.png)

Would be great if you could try v2.413 alpha

**Comment by fifafu** [comment]
ah sorry, please wait a moment. Need to fix something.

**Comment by fifafu** [comment]
Ok, 2.414 should work correctly like shown in the screenshot.

**Comment by donileo** [comment]
Works great!
