### ISSUE TITLE
incorrect sequence of keyboard triggered actions 

### ISSUE THREAD

**Issue by StevGermany** [fifafu/BetterTouchTool#2287]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Since a recent update of BTT i  have the following problem.
I use Btt to insert userid and pwd into 2 field.
For that i use a keyboard triggered sequence of actions
1) typeText
2) press Tab key
3) wait for 1 sec
4) typeText...
This sequence worked fine until recently.
But now for some reason the "tab"(action 2) is executed first followed by the other 3 actions.
That results in all text to be inserted into the second field instead of userid into 1st field and pwd into 2nd field. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
keyboard

#### Device information:

Type of Mac: iMac
macOS version: latest
BetterTouchTool version: latest  2.415

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, fixed in 2.416
