### ISSUE TITLE
Parallels Inconsistent key presses

### ISSUE THREAD

**Issue by kamil6x** [fifafu/BetterTouchTool#229]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I setup remapping gestures from Command-Control-F4 to Alt-Control-left arrow.
The problem is parallels it seems the keys are not being transmitted reliably into parallels. This was tested with the setting "Optimize for games" both on and off; the keyboard keys are sometimes transmitted as control left arrow, sometimes fully, etc.

On the OS X side things seem being transmitted reliably (eg. Key Codes) software seems to be showing the proper keys.

I am writing here as it is doubtful that parallels will address any issues like this from my experience. 
I would be grateful if anyone could help.

**What kind of Mac are you using?**
Macbook Pro (Retina, 15-Inch, Mid 2015) 2.5Ghz core i7

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Various external mice (this is why I'm using BTT; to not have to remap different mice settings).

**Which versions of macOS and BetterTouchTool are you running?**
OS X El Capitan 10.11.6; BTT 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Increasing the length of time the modifier keys are pressed virtually? 

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by junglg** [comment]
I am observing a similar issues with hotkey in Parallels; when modifier keys are involved then the keypress is not being transmitted reliably. e.g. some modifier keys may be omitted.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
