### ISSUE TITLE
Feature Request: Allow all user added triggers to be disabled/enabled via toggle

### ISSUE THREAD

**Issue by donileo** [fifafu/BetterTouchTool#2290]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Shortcuts/triggers in Normal Mouse can't be enabled/disabled via a toggle yet it seems some other shortcuts in the app in different sections can be enabled/disabled. Here I am making the request that all shortcuts that can be added can be enabled/disabled so as to prevent the user from having to delete them and read them and possibly make mistakes. This is a must have quality of life improvement at least for me.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All Devices.

#### Device information:
N/A
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
N/A

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
tracking this here: #2129
