### ISSUE TITLE
customer slider and volume slider

### ISSUE THREAD

**Issue by capsterx** [fifafu/BetterTouchTool#2291]
#### Description of bug/feature request/question:
I have a volume slider widget, and added a custom slider widget.  When I move the custom slider widget, it moves the volume one.  I added a 2nd volume one and 2nd custom slider to test.  The custom sliders do not cause each other to move, but each one causes both volume sliders to move.  The volume sliders only cause each other to move and not the custom slider.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.13.3 (17D47)
BetterTouchTool version: 2.412

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Should be fixed now!
