### ISSUE TITLE
Toggling DND no longer works since the last (or recent) version

### ISSUE THREAD

**Issue by tigersoul925** [fifafu/BetterTouchTool#2292]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Toggling DND no longer works through the designated action

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard shortcut that worked fine before

#### Device information:

Type of Mac: macbook pro
macOS version: 10.13.3
BetterTouchTool version: 2.405.756

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Instead of toggling DND, the notification center is just opened, or while in fullscreen, nothing happens.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

I think this is fixed in the latest alpha version (get via check for alpha version updates)

However you can now also configure a shortcut for it in system preferences -> keyboard -> shortcut

**Comment by tigersoul925** [comment]
Will check, thanks.
