### ISSUE TITLE
'Move Window One Space/Desktop Left' (or right) is not working

### ISSUE THREAD

**Issue by ktravelet** [fifafu/BetterTouchTool#2293]
#### Description of bug/feature request/question:
The 'Move Window One Space/Desktop Left' (or right) stopped working.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Keyboard

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.13.3
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
When the shortcut activates, the mouse jumps to the upper left of the current window then back down to the original position.  The window does not move at all.

**Comment by fifafu** [comment]
I think this should be working in current versions, if not, please respond again!

**Comment by fangerya** [comment]
I have the exact same issue on v2.646 on 10.14.
