### ISSUE TITLE
Moving/Resizing while holding keys

### ISSUE THREAD

**Issue by chr0max** [fifafu/BetterTouchTool#2294]
Hi,

thank your for this wonderful tool.

I use the action "Start/Stop moving" and "Start/Stop Resizing" to immitate the KDE Move/sizing feature and make apps like zooom2, MaxSnap, Easy Move+Resize or WindowNaut needless. 

It works better like the ones, but there is no option (or I can´t find it) to set them, that the only are active while I hold a modifier. Now I have it so: I hold ctrl + click left = "Start/Stop Moving", the active windows is pinned at my cursor. I have to repeat and the window is released. In a perfect world, the window would be only moved while I hold the keys and when released instantly dropped.

I presume that for my evil plan I would need an predefined action just called "moving" that only works while the triggerkeys are pressed, but I´m thankful for suggestions!

Thanks for your time!

**Comment by fifafu** [comment]
Hi,

it's a bit hidden in the advanced prefs:
![image](https://user-images.githubusercontent.com/8820811/37708031-690eb110-2d05-11e8-97f9-f82ea89ae02c.png)
