### ISSUE TITLE
Trigger Context Menu Item not working on Word 2011

### ISSUE THREAD

**Issue by sanfm12** [fifafu/BetterTouchTool#2299]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

These actions are not working anymore on Word 2011 (14.7.7), since your last two updates:
Trigger Context Menu Item: Hyperlink;Copy Hyperlink
Trigger Context Menu Item: (9);(4)

I use shift+command+9 for both actions, then I choose the one I want from the BTT menu.
It won't work even if I try it with different shortcuts.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook pro keyboard

#### Device information:

Type of Mac: macbook pro
macOS version:  10.11.6
BetterTouchTool version: 2.405 (756)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should be working in the latest alpha version (2.418), get via "check for alpha version updates"
