### ISSUE TITLE
Update fails after download/install with "open safe files" option in Safari

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#23]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
When I downloaded BTT via Safari with the "open safe files after downloading" option turned on, I found that when I tried to update BTT from the menu bar icon or from the preferences window, it gives an error that says it can't be updated “when it’s running from a read-only volume like a disk image…”.  When I turned off the "open safe files" option, downloaded and manually opened the zip, and moved the resulting app file to ~/Applications, then the update worked fine. 

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
N/A

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
thanks for reporting!
I'll look into this, however it may just be the security feature by Safari that prevents to replace the app with an update.
