### ISSUE TITLE
Control whether right-side app buttons or global buttons are farthest right

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#230]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
There needs to be a way to resolve conflict of right-side touch bar buttons for app vs. Global.  That is, be able to make Global right-side buttons specified be farther right than app right-side buttons (or vice versa).

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.980

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
With 1.986 you can now choose whether the global or app-specific buttons are shown first. This may not solve every use-case but for now it has to do :-)
