### ISSUE TITLE
'c' being disabled on latest Alpha

### ISSUE THREAD

**Issue by yaseent** [fifafu/BetterTouchTool#2305]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I seem to be having the strangest problem.

My c key is being disabled after some time. I have to quit BTT and relaunch to resolve the problem. But the problem persists after a while. I try to find some way to force it to happen, but just can't seem to understand what is causing this to happen.

When my c key is disabled, and I select some text anywhere, and press c, the EDIT in menubar lights up. When I paste in a pastable area, it pastes the text that was highlighted when I hit c. So basically c is being turned into CMD+c. Also, when this is happening, and I hit Shift + C, then a capital C gets outputed, so it's only when c is used alone.

I've attached screenshots of my mouse/keyboard triggers.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Microsoft Sculpt Comfort Keyboard.

#### Device information:

Type of Mac: Mac Mini
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.417

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![screen shot 2018-03-22 at 04 31 31](https://user-images.githubusercontent.com/21298730/37747951-54d192be-2d8a-11e8-9613-358c342d297c.png)

![screen shot 2018-03-22 at 04 32 29](https://user-images.githubusercontent.com/21298730/37747990-82e101f8-2d8a-11e8-9419-023d96d234f6.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should also be fixed in v2.418 :-)

**Comment by yaseent** [comment]
Thanks.
