### ISSUE TITLE
Keyboard shortcut with "fn" bug

### ISSUE THREAD

**Issue by heruji** [fifafu/BetterTouchTool#2306]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I set global keyboard shortcut `fn X` to _Show clipboard/pasteboard history_. Now it seems that I can't input `x` in the password input dialog box of the Keychain Access application. Pressing `x` there always triggers `fn X` and opens the clipboard manager of BTT. After I quit Keychain Access, I can't input `x` in other applications too. I need to restart BTT to make my `x` key work again. I tried to change the shortcut to `fn` plus another key, but the same problem remains. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook keyboard

#### Device information:

Type of Mac: MacBook Pro 2017 13-inch (no touch bar)
macOS version: 10.13.3
BetterTouchTool version: 2.417 (768)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screenshot:

<img width="881" alt="2018-03-22 14 08 57" src="https://user-images.githubusercontent.com/5276960/37754640-54020802-2ddd-11e8-9773-6440ec9628f1.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Ah good point. I'll fix that. It's because keychain enables secure input which causes BTT to disable the new keyboard functionality. 

For now you can disable auto switching in the advanced prefs -> keyboard.

**Comment by yaseent** [comment]
@fifafu Hi Fifafu, might this be the same problem I as experiencing with my "c" key?

**Comment by fifafu** [comment]
@yaseent yep! Fix will be available in about an hour on alpha update :-)

**Comment by fifafu** [comment]
Should be fixed in v2.418!
