### ISSUE TITLE
Some mice cannot trigger the "3F Swipe Back/Forward" predefined actions

### ISSUE THREAD

**Issue by advicepyro** [fifafu/BetterTouchTool#2307]
#### Description of bug/feature request/question:

Recently I purchased an inexpensive mouse off Amazon. Unlike previous mice I used with macOS, this is the first mouse which isn't able to trigger the 3F Swipe Back or Swipe Forward predefined action(s) when I click Button 3 or 4.

The button clicks are being registered and BTT is able to detect a Button 3 or 4 when setting up the mouse actions.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse in question: https://www.amazon.ca/gp/product/B073LJQSH3

Device information:

```
2.4G Keyboard Mouse:

  Product ID:	0x5918
  Vendor ID:	0x062a  (ProVision Technology, Inc.)
  Version:	1.02
  Speed:	Up to 12 Mb/sec
  Manufacturer:	MOSART Semi.
  Location ID:	0x14113000 / 8
  Current Available (mA):	500
  Current Required (mA):	100
  Extra Operating Current (mA):	0
```

Also compared it to a Logitech G203 which does support the two actions.

#### Device information:

Type of Mac: 2017 MacBook Pro 13"
macOS version: 10.13.3
BetterTouchTool version: 2.403 (754)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

For now, using Command + [ or Command + ] is sufficient to replace going back/forward.

**Comment by fifafu** [comment]
That's very weird, these actions are not bound to any hardware features.
Can the mouse trigger ANY of the BetterTouchTool actions when pressing these buttons?

**Comment by advicepyro** [comment]
Huh this is weird. I tried other actions and the mouse was able to trigger them.

After a couple of restarts later, and now the 3F gestures are working again. Weird!
