### ISSUE TITLE
Two Finger Pinch Out stopped working

### ISSUE THREAD

**Issue by hangelg** [fifafu/BetterTouchTool#2308]
Two Finger Pinch Out stopped working

I usually use this to Maximize windows.

Both MacBook Trackpad and Magic Trackpad

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2016)
macOS version: High Sierra 10.13.2
BetterTouchTool version: 2.420

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
There seems to be an issue on some machines where the pinching sometimes gets disabled in System Preferences => Trackpad, enabling it again should fix it.

I'm currently looking for a way to prevent this.
