### ISSUE TITLE
Not possible to register shortcut for dead keys

### ISSUE THREAD

**Issue by amplexdenmark** [fifafu/BetterTouchTool#2309]
#### Description of bug/feature request/question:

When trying to register a keyboard shortcut for Option+` (backping) BetterTouchTool goes back and prompts me to “Click to record shortcut" as soon as I hit the key-combination

It looks like a general problem with "dead keys" like :  ´`^¨

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard
I'm using a danish keyboard layout

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13.3
BetterTouchTool version: 2.420 (777)

**Comment by fifafu** [comment]
This should be working now!

**Comment by amplexdenmark** [comment]
I sure does!! Thanks!!
