### ISSUE TITLE
Slider feature for Touch Bar

### ISSUE THREAD

**Issue by NickClark** [fifafu/BetterTouchTool#231]
#### Slider feature for Touch Bar:
It would be really nice if there was a slider control option. My current use case is that I have an LG monitor that actually has decent speakers. Due to the nature of how mac handles digital audio over HDMI/DisplayPort/etc, I cannot control the volume from my computer. Fortunately there's a little CLI program called ddcctl that allows me to control monitor values including volume. I currently have two custom touch bar buttons that I can tap to control the volume, but I would much prefer being able to slide directly to the desired volume. I'm imagining a slider control than can then pass the the current value  (0-100) to an executed Terminal Command.

**What kind of Mac are you using?**
MacBook Pro 2016 15" with TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
Sierra and 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sliders will be available soon!

**Comment by hi94740** [comment]
So 8 months passed, still no slider?
