### ISSUE TITLE
ESC on touch bar does not work in Expose

### ISSUE THREAD

**Issue by damga** [fifafu/BetterTouchTool#2310]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Few versions ago (not sure exactly when) my ESC key put into BTT touchbar stopped working when I enter Expose.
It's useful as  when I got to Expose, this is the easiest way to go back to the window that was on screen before.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar,

#### Device information:

Type of Mac: MBP15
macOS version: 10.13.3
BetterTouchTool version: 2.420(777)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this was introduced in a recent macOS update. It's not fixable as far as I know.

Sorry!
