### ISSUE TITLE
Feature Request: Create Buttons using Applescript

### ISSUE THREAD

**Issue by OrbitalTech** [fifafu/BetterTouchTool#2312]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm not sure how feasible it would be but,

Creating buttons using applescript. Practical applications of features like this would be:
Any form of menu. Such as Wifi selection, Input/Output devices, even tab selection in chrome.

A way to create buttons with certain text that do a certain feature (most likely from within a folder) would be fantastic.

While we're here, it would be incredibly useful to be able to modify properties from a widget such as icon only, or colour.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 13" 2017 512Gb with TouchBar
macOS version: 10.13.3
BetterTouchTool version: 2.405

**Comment by fifafu** [comment]
This will soon be supported. With the current alpha you can already update a widget via Apple Script, see: https://updates.bettertouchtool.net/alpharls.html
