### ISSUE TITLE
Add support for gesture-based cursor swapping

### ISSUE THREAD

**Issue by jmdye** [fifafu/BetterTouchTool#2314]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Feature Request: Please add a capability for a user-defined gesture to temporarily swap the cursor graphic to a different graphic, possibly even an animated graphic. This capability would be useful for Demos where I need to indicate to viewers of my screen that I have just clicked somewhere or performed a specific gesture. For example, I often need a way to indicate to users that I have just clicked on a button, or that I've performed a two-finger swipe. Being able to set up a keyboard shortcut where I hold down a specific set of keys to temporarily change the cursor graphic would be useful. Even better would be if BTT could automatically display perform that action when the gesture is performed if I have those BTT gestures enabled.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse 2, Magic Trackpad 2

#### Device information:

Type of Mac: MacBook Pro (13 inch)
macOS version: OSX 10.13.3
BetterTouchTool version: 2.405 (768)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry I probably won't add this.
There is no API for changing a cursor globally, so it would require some super nasty hacks (displaying a transparent window above the mouse cursor).
