### ISSUE TITLE
Enable permissions popup constantly appearing

### ISSUE THREAD

**Issue by imran0** [fifafu/BetterTouchTool#2316]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I am constantly reminded to set the Accessibility options have whitelisted BetterTouchTool even though it is. When I close the window it reappear a minute later. I am forced to close the app to stop popups.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
N/A

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.13.3
BetterTouchTool version: 2.420

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a macOS bug that happens on some systems.

You need to disable & re-enable the permissions in system preferences -> Security and Privacy -> Privacy -> Accessibility

**Comment by imran0** [comment]
I have done this but I still get the issue as described.
