### ISSUE TITLE
"Custom Click: SHIFT+CMD+Middle" disables all cursor hover events in macOS

### ISSUE THREAD

**Issue by vartiainen** [fifafu/BetterTouchTool#2317]
#### Description of bug/feature request/question:
Using assigned action **"Custom Click: SHIFT+CMD+Middle"** disables all cursor hover events.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad 2

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.13.3
BetterTouchTool version: 10.13.3 (17D102)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I recently updated BetterTouchTool.
After the update, using the aforementioned assigned action prevents all future cursor hover events from happening throughout the OS.
This is pretty annoying because for example menus don't work properly and Dock doesn't reveal itself on hover.
The cursor moves normally and click events work.
_After using the assigned action hover can be restored by restarting BetterTouchTool._
I tried using another trackpad gesture to invoke this assigned action but the problem remains.

By the way, BetterTouchTool is my favorite macOS utility.
My computer is useless without it.

**Comment by fifafu** [comment]
should be fixed in v2.422!

**Comment by vartiainen** [comment]
That was quick, thanks!
