### ISSUE TITLE
BTT messes up macOS UI

### ISSUE THREAD

**Issue by CosmicOutlaw** [fifafu/BetterTouchTool#232]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
http://imgur.com/a/QuReo

When dragging an object to the borders of my desktop, BTT does inexplicable things and I have no idea why. If all gestures/actions are disabled, the problem is still present.

**What kind of Mac are you using?**
MacBook Pro Retina 13'' Late 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.1
BTT Trial 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
http://imgur.com/a/QuReo

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
You have enabled window snapping (dragging windows to the edges to resize them) and you have added a custom snap area.

Window snapping can be disabled in the settings, to remove the snap area in the middle of the screen click the BTT menubar icon -> snap areas -> edit snap areas. Then click on the snap area and then click on the X to delete it.
