### ISSUE TITLE
Inconsistent Keyboard Shortcuts

### ISSUE THREAD

**Issue by cupcake2** [fifafu/BetterTouchTool#2321]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I've used BTT for years with great satisfaction, but I have a new issue. Ever since a recent update, many of my keyboard shortcuts don't work anymore. The odd thing is, doing some troubleshooting, I found that ctrl+alt+cmd+S can trigger any action I want, but I can't find any other combinations that work. BTW, modifiers on trackpad gestures work fine.
Is there something really simple and dumb that I'm doing? 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook keyboard

#### Device information:

Type of Mac: MacbookPro
macOS version: 10.13.3
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, there is nothing that should differentiate ctrl+alt+cmd+s from other shortcuts.

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com and reference this issue then I'll look into it.

**Comment by fifafu** [comment]
Solved by enabling old keyboard implementation in the advanced preferences => keyboard

**Comment by cupcake2** [comment]
Hi, when I open an app with a gesture, only the frontmost window appears, and the others stay hidden behind whatever other app is open. Is there any way to bring all windows of an app to the top? I can’t find a way to do that.

Thanks,
Robert
