### ISSUE TITLE
(Question) Possible to set this workflow? Save email as raw file on desktop

### ISSUE THREAD

**Issue by kfp22reg** [fifafu/BetterTouchTool#2322]
#### Description of bug/feature request/question:
I often have to save an email to OneNote, the most efficient way I found is to save the email as "Raw File" from the mail app to desktop, then drag and drop this file to my OneNote page.

Is it possible to set a workflow that saves the current highlighted email as "Raw File" on desktop?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
iMAC, Mail app

Thanks for your help !

**Comment by OrbitalTech** [comment]
This is absolutely possible. If you need it in a Raw format, you can automate the process of saving the email as a "Raw File" using automator and/or applescript. I don't personally use mail, but I'll see what I can do.

**Comment by OrbitalTech** [comment]
Alright, I've used a bit of Automator to make this. Here you go!

```

activate application "Mail"
tell application "System Events"
	tell process "Mail"
		keystroke "s" using {shift down, command down}
		-- Click the “Save” button.
		delay 1
		set timeoutSeconds to 2.0
		set uiScript to "click UI Element \"Save\" of sheet 1 of window \"Inbox (1,449 messages, 1 unread)\" of application process \"Mail\""
		my doWithTimeout(uiScript, timeoutSeconds)
		
		
	end tell
end tell
on doWithTimeout(uiScript, timeoutSeconds)
	set endDate to (current date) + timeoutSeconds
	repeat
		try
			run script "tell application \"System Events\"
" & uiScript & "
end tell"
			exit repeat
		on error errorMessage
			if ((current date) > endDate) then
				error "Can not " & uiScript
			end if
		end try
	end repeat
end doWithTimeout

```

**Comment by kfp22reg** [comment]
Thanks a lot for this!!
I am almost there, I pasted this code in "Run AppleScript" and it does open up a window with everything filled exactly as I need, with only one step for me to do manually: Click on "Save" or "Cancel"
Is it possible to also have it automatically click "Save" for me?

**Comment by OrbitalTech** [comment]
It should be clicking save automatically, but heres a shorter alternative. If its not working for you, try adjusting the delay, as your computer may be slower than mine.

```

activate application "Mail"
tell application "System Events"
	tell process "Mail"
		keystroke "s" using {shift down, command down}
		delay 1
		key code 36
	end tell
end tell

```

Its worth noting that this still takes about 1 second to complete each save (on current delay), and if you're planning on saving a lot of them, this may take a while.

**Comment by kfp22reg** [comment]
Thanks !
