### ISSUE TITLE
Can't use hotkeys for switch language in input type="password" and Google Chrome

### ISSUE THREAD

**Issue by UksusoFF** [fifafu/BetterTouchTool#2328]
#### Description of bug/feature request/question:

Assign sequence Alt+Shift shortcut for Ctrl+Space which assigned as change language.
Go to any website which contains password inputs. 
Shortcut works in all inputs except password.

![image](https://user-images.githubusercontent.com/1931442/37894532-92b0a77e-30ef-11e8-932a-d65f926311bc.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard?

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.422

**Comment by fifafu** [comment]
Hi,

This is a macOS feature called "secure input". It prevents other apps from reading password entry or other sensitive information. However it also blocks BTT from accessing keyboard events while secure elements are active.

This can not be fixed for key sequences, however normal shortcuts should work.
