### ISSUE TITLE
Feature request: option to not sync "Enabled" state across Dropbox

### ISSUE THREAD

**Issue by sebastienkb** [fifafu/BetterTouchTool#2329]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I enabled Dropbox sync so that I have the same behaviour on both my work and home computer, and new items are automatically added. I often would have the same hotkeys for similar items but requiring different apps; e.g.

- Cmd+Ctrl+D opens Dropbox at home, but OneDrive For Business at work
- Cmd+Ctrl+K opens SafeInCloud at home, but Dashlane at work

As workaround for opening items of the filesystem, I run a bash script that will effectively run `open` depending on which computer I'm on. But it is not possible to do so for some for BTT-specific items:

- Pasting text (home email at home vs work email at work)
- Capture screenshot (save paths may differ)
- Move/snap windows (different amount of screens)
- Any items will be affected if the username is not exactly the same on both computers (I assume absolute paths are saved instead of relative)

What would work for this is being able to duplicate the items that differ, so that it would be enabled on one computer, but disabled on another. For this to work, the `enabled` state would need to not be synced with the rest. For each new added item that has not yet been synced, `enabled` would be true.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Any syncable items

#### Device information:

Type of Mac: iMac at home, Mac mini at work
macOS version: macOS High Sierra
BetterTouchTool version: 2.422 (779)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi Sebastian,

unfortunately partially syncing attributes is not possible with BTT's synchronization concept. However there is a solution for your problem using mulitple presets.
See this thread were I described how to set this up: https://github.com/fifafu/BetterTouchTool/issues/2193

I'm closing here as I believe this will solve your issue, in case it doesn't please let me know then I'll reopen.

**Comment by sebastienkb** [comment]
Great! It took me a while but I got it to work! I now have a preset "Common", a preset "iMac" and a preset "Mac mini". It didn't work at first because I had put the serial number check in each *specific* preset, and not in "Common", so it never actually triggered. D'oh!

Thanks a lot! Can't wait for your next updates!
