### ISSUE TITLE
Add Keyboard Shortcut Action `Send Shortcut to Active App`

### ISSUE THREAD

**Issue by darvelo** [fifafu/BetterTouchTool#233]
#### Description of feature request:

The ability to assign a keyboard shortcut to send a key combination to the currently-focused/active app (bypassing BTT's shortcuts; this would resolve #190 for me). Currently there's an action for sending a key combination to a *specific* app, but this doesn't solve the case where I want that key combination to be passed through to any app without having to add all apps to the app-specific shortcuts list.

**What kind of Mac are you using?**

MBP 2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Keyboard

**Which versions of macOS and BetterTouchTool are you running?**

macOS 10.12.2
BTT 1.963 (552)

**Comment by fifafu** [comment]
Isn't this the same issue as #190 ?

Sending a shortcut to the current app is already possible, however bypassing BTT Shortcuts is currently not (for various reasons it's complicated to implement).

I'll leave #190 open as this may be added in a future version, but close this as it seems to be the same issue for me.

![image](https://cloud.githubusercontent.com/assets/8820811/21815263/49498fa8-d75c-11e6-8041-3762b25676b7.png)

**Comment by darvelo** [comment]
@fifafu At first glance it seems the same as #190, but I can achieve bypassing BTT global shortcuts per-app with this kind of config:

<img width="867" alt="screen shot 2017-01-10 at 10 52 25 pm" src="https://cloud.githubusercontent.com/assets/523169/21835008/a29cac40-d787-11e6-8c90-1b8994cf7c70.png">

<img width="872" alt="screen shot 2017-01-10 at 10 49 24 pm" src="https://cloud.githubusercontent.com/assets/523169/21835007/a2948114-d787-11e6-8b1f-697386789d54.png">

<img width="379" alt="screen shot 2017-01-10 at 10 58 25 pm" src="https://cloud.githubusercontent.com/assets/523169/21835099/54d358a0-d788-11e6-82f5-6196a03f4687.png">

<img width="739" alt="screen shot 2017-01-10 at 10 57 21 pm" src="https://cloud.githubusercontent.com/assets/523169/21835076/2f6ae6e6-d788-11e6-9ad6-66608b4275cb.png">

If this could somehow be configured so that it didn't say `Send foo to Firefox` and instead said `Send foo to Active App` then I think it could work. Not sure how BTT is programmed but this works per-app, Firefox gets cmd+w (thus closing a tab) and the global cmd+w (moving left a Space) isn't triggered.
