### ISSUE TITLE
Independently adjust tracking speed of fine movements?

### ISSUE THREAD

**Issue by NelsonGast** [fifafu/BetterTouchTool#2331]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm using BTT to increase my tracking speed for my trackpad, I like the max speed that it has, but it is much too slow and harder to move when doing fine movements, so the speed goes from super zippy to moving through sludge. Is there any way to adjust the speed of fine movements independently? If not, this feature would be greatly appreciated!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: El Capitan
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry this probably won't be added to BTT. However there are some tools that can do it, see http://smoothmouse.com/ (also their recommended other tools)

This is quite complicated and the necessary APIs either require kernel extensions or don't work on High Sierra anymore.
