### ISSUE TITLE
BTT doesn't seem to recognize program "Siemens Logosoft" (PLC software)

### ISSUE THREAD

**Issue by harmless182** [fifafu/BetterTouchTool#2333]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm trying to customize the touchbar in a program called Siemens Logosoft, but BTT doesn't seem to recognize the app, although it recognizes it when you select a specific running app. When I add a button to the the touchbar it will not come up as a button when the program is selected. Am I doing something wrong?

When I use the normal apple way to use F-keys with this app then it is recognized. So I think it should be possible with BTT as well ( much better program ).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Every input device.

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.12.6
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
---

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by OrbitalTech** [comment]
<img width="948" alt="screen shot 2018-03-28 at 9 01 48 am" src="https://user-images.githubusercontent.com/23006558/37991819-acd37d5c-3266-11e8-90b4-2645f8cf93a2.png">
Could you please send a screenshot of this window?

**Comment by harmless182** [comment]
My apologies. I've checked Issue #2324. When I selected "Show BetterTouchTool Bar, hide system Control Strip" it worked. This issue ( that isn't an issue so it seems ) is solved. I had "Default" selected.

Thanks for getting back to me.
