### ISSUE TITLE
Second monitor doesn't turn on

### ISSUE THREAD

**Issue by cacharrea** [fifafu/BetterTouchTool#2335]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Since I've updated BTT', my imac not recognize the second monitor. Coincidence or not?. Of course, I've tried different solutions without successful.
Thank you very much!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Second Monitor

#### Device information:

Type of Mac:        iMac 5k 2015
macOS version:   MacOS 11.6 EL CAPITÁN
BetterTouchTool version:   2.422 (779)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, this is definitely not related to BTT :-(
