### ISSUE TITLE
Doubleclick Window Titlebar -> Maximize Window doesn't work properly with Chrome

### ISSUE THREAD

**Issue by TheBloke** [fifafu/BetterTouchTool#2337]
#### Description of bug/feature request/question:

For a long time I have used BetterSnapTool alongside BTT, but today I decided to migrate all actions to BTT so I don't need two apps.  This has caused me to find that:

Other->Doubleclick Window Titlebar : Maximize Window  does not work with Chrome windows.  

The window resizes, but does not move - its top left position remains the same as before the action runs.  BST's built in feature for this worked OK with Chrome.

This is specific to "Doubleclick Window Titlebar".  If I assign a BTT KB shortcut to "Maximize Window", it does work with Chrome.   

BTT seems to work fine with other apps (tested Firefox, iTerm 2, Wavebox). 

One app that neither BTT nor BST works with is Photoshop - double-clicking the titlebar does nothing.  A KB shortcut assigned to Maximize Window does work for this app, as does dragging it to the top of the screen.  Not a big deal, just thought I'd mention it (I realise PS uses non-standard windows).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Other

#### Device information:

Type of Mac: MP 5.1
macOS version: 10.13.4 DP7
BetterTouchTool version: 2.422

**Comment by fifafu** [comment]
Could you test v 2.423 alpha? (get via check for alpha version updates")

**Comment by TheBloke** [comment]
Fixed! Chrome maximising fine on double-click.  Thanks a lot.

**Comment by DroiSDK** [comment]
I meet this issue again in 2.442(803) and this issue is only for chrome window. Double click only resize the chrome window but doesn't move the window to top-left corner.

macOS version: 10.12.6
chrome version: 65.0.3325.181 
BetterTouchTool: 2.442 (803)

**Comment by jerryctt** [comment]
I meet this issue again in 2.442(803) and this issue is only for chrome window. Double click only resize the chrome window but doesn't move the window to top-left corner.

macOS version: 10.12.6
chrome version: 65.0.3325.181
BetterTouchTool: 2.442 (803)

**Comment by fifafu** [comment]
Thanks! I'll check it again.
