### ISSUE TITLE
[Bug] Auto hide Menu Bar creates gap in top snap area

### ISSUE THREAD

**Issue by jvaldiviezo9** [fifafu/BetterTouchTool#2338]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Sometimes an app is unable to totally maximice, there is a gap where the menu bar should be. In my case I made the menu bar to autohide and this creates a gap anytime I want to use the Top Snap Area to Maximice my app

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
This happens with a mouse or trackpad

#### Device information:

Type of Mac: late 2011 15 in, i7
macOS version:  Sierra 10.12.6
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Any time I drag my window at the top to maximice it remains with a gap. This happens sometimes, and even with the restart of better touch tool the problem is not solved.

![screenshot_2018-03-27 09 52 13_qfoywi](https://user-images.githubusercontent.com/18518204/37979012-b8a9ab5a-31a4-11e8-9c73-a11e0777e352.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a bug in macOS (reporting the wrong screen frame in some cases).
This has drastically improved in 10.13.x (I'm not sure if it has been fixed completely), but I think I can't fix it in BTT.
