### ISSUE TITLE
Received Distributed Notification

### ISSUE THREAD

**Issue by alekah15** [fifafu/BetterTouchTool#2340]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm trying to use the Other trigger on a mac notification to try to "see" a notification and press a keyboard button (standard Command Q). However, it doesn't see the trigger at all (verified by switching the action to Open Finder and others). I'm not sure how to get BTT to 'see' a notification if thats part of the "Distributed Notification" trigger or not. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Other

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.13.3 High Sierra
BetterTouchTool version: 2.422 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://user-images.githubusercontent.com/22222105/37990904-9b488064-31d5-11e8-8a26-01a1af24a794.png)

![image](https://user-images.githubusercontent.com/22222105/37990925-aa2783aa-31d5-11e8-9129-9fc380b4f10d.png)
![image](https://user-images.githubusercontent.com/22222105/37990938-b32eb4b4-31d5-11e8-8072-37e7168921d4.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Why do you think this is a distributed notification that is being sent? Are you sending it from somewhere?

//edit: ah I just saw the second screenshot, unfortunately this is not a distributed notification (distributed notifications are notifications sent programatically). 

There is currently no way to react to the normal macOS user notifications in BTT ;-(

**Comment by alekah15** [comment]
If a notification can't be received, is there a way to get the 'mute' signal given by the headset?

**Comment by fifafu** [comment]
@alekah15 unfortunately that's currently also not possible, but I'm tracking this feature request already. Maybe I can add it in an upcoming update.

(I also checked again whether there is any way to get the user notifications, but it doesn't seem to be possible at all)
