### ISSUE TITLE
Delay with dialog before I can click any button

### ISSUE THREAD

**Issue by ngocphamm** [fifafu/BetterTouchTool#2345]
#### Description of bug/feature request/question:
So I was trying to create a rule so that when I hit `Cmd + Q` in Safari, it will show a dialog for confirmation first.

It's pretty straight forward with the following Apple Script, entered directly to BTT.

```
tell application "System Events"
	set theName to name of the first process whose frontmost is true
end tell
tell application theName
	display dialog "Are you sure you want to quit?"
	quit
end tell
```

It works fine, except for one thing. I noticed that I have to wait for maybe 2-3 seconds before I can really click `Cancel` or `OK` button in the dialog. I even tried to do a screen recording, with click highlighting, but the result video doesn't highlight the first 1-2 clicks (when it didn't take effect on clicking the buttons). It's odd to me that it's somehow not recognized as clicks, until I can really click the button (then it highlights the click in the recorded video).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Keyboard & External Keyboard.

#### Device information:

Type of Mac: Macbook Pro 2015 15"
macOS version: 10.13.3
BetterTouchTool version: 2.420

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![2018-03-28 at 10 52 am](https://user-images.githubusercontent.com/395123/38037078-1c2378e2-3276-11e8-93e9-c61affa46953.png)

I don't know if this is BTT bug, or that system dialog's thing, so please let me know if this is reproducible and is a BTT bug. Thank you!

**Comment by OrbitalTech** [comment]
I can recreate this issue. Could you try using display alert?

Like this:

```

set theAlertText to "An error has occurred."
set theAlertMessage to "The amount of available free space is dangerously low. Would you like to continue?"
display alert theAlertText message theAlertMessage as critical buttons {"Don't Continue", "Continue"} default button "Continue" cancel button "Don't Continue"

```

More information can be found <a href="https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/DisplayDialogsandAlerts.html">here</a>.

**Comment by ngocphamm** [comment]
Same thing @OrbitalTech  :(

```
tell application "System Events"
	set theName to name of the first process whose frontmost is true
end tell
tell application theName
	set theAlertText to "An error has occurred."
	set theAlertMessage to "Are you sure you want to quit?"
	display alert theAlertText message theAlertMessage as critical buttons {"Cancel", "OK"} default button "OK" cancel button "Cancel"
	quit
end tell
```

**Comment by OrbitalTech** [comment]
I tried the code inside script editor, and found that I had no delay before I clicked. I will leave this to @fifafu

**Comment by ngocphamm** [comment]
Yeah I can see that running the code inside script editor works just fine with clicking the buttons. It's not when running outside of BTT, which is the case that I need it.

**Comment by fifafu** [comment]
Weird I can not reproduce this on my machine. Maybe it's because I'm currently on the macOS 10.13.4 beta.

In general BTT can not really influence the behavior of Apple Scripts, it just tells the System "Please execute this Apple Script".

Maybe try to use an Automator Workflow instead:
![image](https://user-images.githubusercontent.com/8820811/38085680-c1e15782-3351-11e8-908a-b2cd55064535.png)

**Comment by ngocphamm** [comment]
@fifafu The workflow seems to work well with clicking the buttons! However, it closes Safari and somehow loses the tabs I were having. Re-opening Safari results in a blank window, and I have no way to recover the tabs 🤕

**Comment by ngocphamm** [comment]
Well I am an idiot. Checking the box "Ask to save changes" in the Quit Application action saves the day. Thank you @fifafu for suggesting this method.
