### ISSUE TITLE
Extra key commands sent with Keyboard configuration

### ISSUE THREAD

**Issue by ofayemi** [fifafu/BetterTouchTool#2346]
I'm currently using a MacBookPro Touchbar on OSX 10.13.3.  BTT 2.422 (779)

 I use the option + command + "A" command mapped to my F13 key within a Citrix environment.  This was never an issue, but since one of the recent updates BTT is sending 2 commands when I press F13.  It sends both option+command+"A" AND option+command.  Option+command activates a drop down menu with the Citrix application I'm using.   This happens to all similar commands (option+command+"Letter") mapped to a keystroke press.  

This does not happen sending the same commands using the touchbar or with trackpad gestures.  They both send just option+command+"Letter"

Thanks for your attention

t

**Comment by fifafu** [comment]
You could try to enable compatibility mode for Citrix, see this screenshot:

![image](https://user-images.githubusercontent.com/8820811/38085249-1bb6c2c6-3350-11e8-87a6-45af85ba3ad6.png)

These remote desktop softwares often don't handle macOS keyboard shortcuts correctly and require special handling...

**Comment by ofayemi** [comment]
Andreas
Thanks!  That seems to have done the trick!  I’m wondering if that preference somehow got unchecked during one of the updates?  
Anyway, touchbar, trackpad, and keyboard shortcuts are back to working they were before.  Much appreciated

Toyin

**Comment by fifafu** [comment]
No, but I have updated some parts of the keyboard functionality to use more modern Apple API and some apps don't handle that very well. For these apps I habe created the compatibility mode which uses different APIs.
