### ISSUE TITLE
Window Snapping not working with Steam client

### ISSUE THREAD

**Issue by alex-hempel** [fifafu/BetterTouchTool#235]
#### Description of your bug/question/feature request...:
The Window snapping feature does not work with the Steam client for Mac OS.

**What kind of Mac are you using?**

MacBook Pro 15" Early 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackpad, third-party mouse

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2, 1.963 (552)

I only have the standard window snapping enabled, no adfanced configurations.

**Comment by fifafu** [comment]
Thanks for reporting! I'll check if it can be supported. (Unfortunately some apps that don't use standard macOS windows can't be supported because they don't  "listen" to the resize commands.)
