### ISSUE TITLE
Arrow Keystrokes are not being passed correctly on their own, or logged in Insert/Type Custom Text action.

### ISSUE THREAD

**Issue by jeffreyscottfrench** [fifafu/BetterTouchTool#2352]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Bug: When using the Insert/Type Custom Text action, arrow keystrokes are not logged/passed. I have found no other way to send a up/down/left/right keystroke on its own. This is useful for automating navigation of lists where the choice position is always known. My use case would be in Todoist: creating a keyboard shortcut for the Inbox and Today views. Todoist method is to use their search bar to filter to that, but there is no auto selection of items. Keyboard nav allows up/down arrows to navigate the resulting search list, but I can't get BTT to send those keystrokes with the other text "/Inbox" or "/Today" to complete the full process.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard external and internal

#### Device information:

Type of Mac: MacBook Pro Retina
macOS version: 10.3.3
BetterTouchTool version: 2.421 (788) 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
It should just work like this:

![image](https://user-images.githubusercontent.com/8820811/38164162-46a3ef8e-3500-11e8-9a51-d5c2f4d7473b.png)

Or did I misunderstand something?

**Comment by jeffreyscottfrench** [comment]
Well, that works now. I hadn't tried it in about a week, so maybe either a recent update of BTT, Todoist, or MacOS altered something. Thanks for the responding!
