### ISSUE TITLE
Is there a way do disable the clipboard manager totally?

### ISSUE THREAD

**Issue by Askern** [fifafu/BetterTouchTool#2355]
Is there a way do disable the clipboard manager totally? When it is turned on I have huge delays while copying and pasting in MS Excel and MS Word. Right now it is possible to deactivate the clipboard manager for one app, but I would like to disable it totally, also because I don't need it and don't use it. Thanks!

**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Delete all triggers you have configured to show  the clipboard manager, then restart BTT.

**Comment by Askern** [comment]
Thank you very much!!
