### ISSUE TITLE
Feature Request: Prevent custom BTT Touch Bar buttons from disappearing whenever i switch between apps

### ISSUE THREAD

**Issue by spnkr** [fifafu/BetterTouchTool#2358]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
i have a great custom touchbar set in BTT, but it's a pain to have to tap the BTT icon in the touchbar control strip every time i want to use these custom buttons. (the custom BTT buttons disappear whenever i switch between apps)

the OS X Spotify app does this really well. has a toggle behavior on the control strip button that turns persisting on and off. (open spotify, tap the 'spotify' touchbar button, and then the custom spotify scrubber/play/pause buttons stay open on the tabbar forever. even between app switches)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
macbook pro w/ touchbar

#### Device information:

Type of Mac: MacBookPro14,3
macOS version: 10.13.3
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by mtrifiro** [comment]
I am also seeing this behavior after upgrading to OSx 10.13.4. I have the preferences set to NOT show the system toolbar and I also have restarted my computer twice.

![image](https://user-images.githubusercontent.com/3193268/38168265-48dfe55e-34fc-11e8-9d11-9781ae01fa42.png)

**Comment by mtrifiro** [comment]
This should be labeled a FEATURE REQUEST. This is behavior that used to work.

**Comment by mtrifiro** [comment]
I think I figured out what happened. Somehow (without me doing anything) the "Global" BTT Touch Bar setting was set to 'Disable BTT completely". I unchecked this and BTT seems to be behaving correctly again.

![image](https://user-images.githubusercontent.com/3193268/38168357-8de547e6-34fe-11e8-90c8-670f8c8a18f2.png)

**Comment by fifafu** [comment]
Yup, in general BTT keeps the Touch Bar visible. (It can't work like Spotify though because there is no API to do it like this for normal apps)

If it doesn't keep it visible make sure you don't have any app-specific settings that hide the Touch Bar. It should usually be default for everything unless you override it knowingly:
![image](https://user-images.githubusercontent.com/8820811/38376420-ca59f7dc-38f8-11e8-8731-f208a7737d34.png)
