### ISSUE TITLE
How to merge presets?

### ISSUE THREAD

**Issue by nudefireninja** [fifafu/BetterTouchTool#2360]
How do I merge two presets?

I exported the gestures from my old computer and imported them to a fresh install of BTT version 2.417. The gestures were added as a new preset and appear purple now. I've added new gestures and they appear black. Now I want to merge the new gestures into the imported preset so that I can create a new preset and basically switch between all of the gestures that I have now and new ones that I'm going to create for another purpose. I don't see a way to do that.

**Comment by fifafu** [comment]
it's not possible to merge presets. You can select which one is the master preset (appears in black).

The only way to merge presets would be by exporting both jsons, then using a text editor to merge them.

**Comment by ErikMinekus** [comment]
You can change the Master preset to your imported preset, and then add the new gestures again. When you're done, delete the duplicate black gestures and change the Master preset back to Default.

**Comment by nudefireninja** [comment]
Thanks for the tips.
