### ISSUE TITLE
Display Dialog only works if the BetterTouchTool application is opened?

### ISSUE THREAD

**Issue by liambarr** [fifafu/BetterTouchTool#2362]
#### Description of bug/feature request/question:
In the past, I've had Apple scripts assigned to a Touch Bar button/widget. I was able to use the script to display a dialog box, however, now that only works if BTT is open. The dialog box is launched from BTT, as opposed to overlay the current window.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 2017
macOS version: High Sierra (10.13.3 (17D47))
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://user-images.githubusercontent.com/23206656/38169749-f9e2a350-35b5-11e8-9166-e0100b0e25a9.png)
![image](https://user-images.githubusercontent.com/23206656/38169751-01af47d2-35b6-11e8-8f9c-a2f3579f95b4.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by OrbitalTech** [comment]
What you'll need to do is get the current front most window from System Events, and then tell that application to display the dialog.

Like this:

```

tell application "System Events"
	set theName to name of the first process whose frontmost is true
end tell
tell application theName
	display dialog "Dialog Text"
end tell

```
