### ISSUE TITLE
Caps lock as Escape and Control key simultaneously

### ISSUE THREAD

**Issue by khramtsoff** [fifafu/BetterTouchTool#2363]
#### Description of question:
Is it possible to map Caps lock act as Escape and Control key simultaneously?
When I push, then release, the Caps lock key, it will send Escape. 
When I hold down Caps lock and push another key (say A), it will send Control-A.

**Comment by TheBloke** [comment]
I'm pretty sure BTT can't do what you want at this time - it can remap Caps Lock to Escape, or to Control, but not differently according to whether it's used in isolation or simultaneously with another key.

For this kind of requirement I use [Karabiner Elements](https://github.com/tekezo/Karabiner-Elements).  It allows for low-level remapping of keys, including remapping according to whether keys are pressed individually or simultaneously.  Highly recommended, and works fine in parallel to BTT.

In fact it already has a pre-made modification that does exactly what you want:
![screenshot_2018-04-01 16 29 07_hejpru](https://user-images.githubusercontent.com/784313/38174740-fb44363c-35c9-11e8-8669-f7e8da079762.png)

**Comment by khramtsoff** [comment]
Thank you for help!
