### ISSUE TITLE
[Bug] Show / Hide hidden files always shows

### ISSUE THREAD

**Issue by waxfingers** [fifafu/BetterTouchTool#2367]
I have toggle ***Show / Hide hidden files*** associated to as shortcut and logically it would only be triggered when the shortcut is triggered; instead the de facto behaviour (log in, restart, relaunch Finder, etc.) is to **always show hidden files.** Now running BTT 2.423 and 10.13.4 but IIRC this also happened in 10.11.6. Thank you

Workaround, not as smooth though, using the boolean  
`defaults write com.apple.finder AppleShowAllFiles -bool NO`  
and  
`killall Finder`

**Comment by fifafu** [comment]
Weird, BTT basically just sends the shift+cmd+. shortcut to the system.
Could you check what happens when you press that shortcut manually?

**Comment by waxfingers** [comment]
@fifafu Nevermind Andreas, I dug a little more and seemed I had a mutiny going on within a Finder's plist, everything is working now, I should have double checked, silly me 🤡. Thanks for the lighting 
 fast response. I would close the issue but some devs don't like it, so...
