### ISSUE TITLE
Mouse triggers incorrectly routed to window with focus.

### ISSUE THREAD

**Issue by marsui203** [fifafu/BetterTouchTool#2368]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
In Other I have the following trigger set:

Other (e.g. Middle) Click Green Window Button -> Action Enter Fullscreen

This works great except I discovered a bug with regards to window focus.

If I have multiple windows open, lets say Safari and Xcode.  I click on the safari window to give it focus, if I then middle click on the Green button on my Xcode window (without first clicking on any other part of the Xcode window to grant it focus) then it will full screen safari.  So basically whatever window has focus, even if you middle click the green button on the other window, will get full screened. In fact, just testing real quick, all the other mouse triggers work this way .  Leftclick green window button, right click green window button are both triggers I use.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Affects Trackpad and my bluetooth mouse.

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: High Sierra 10.13.3
BetterTouchTool version:  2.422 (779)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Workaround, click the window I want the triggers to work on first, then click the green button, don't just go right to the green button of a window without focus.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You should be able to solve it like this:
![image](https://user-images.githubusercontent.com/8820811/38196934-eced4e36-3685-11e8-9d2d-f6b3ee2f1f3c.png)

I don't want to activate the window by default because there are also other usecases where that would be problematic.

**Comment by marsui203** [comment]
Ah ok, that works thanks!
