### ISSUE TITLE
Return key not working in 2.422

### ISSUE THREAD

**Issue by mikehdow** [fifafu/BetterTouchTool#2370]
#### Description of bug/feature request/question:
The return key does not work in BetterTouchTool scripts any longer. I noticed this a few weeks ago -- for months it worked fine. Two examples:
1) A Key Sequence is meant to type out text (not paste). The text is "Thank you,
Mike". What gets typed out is "Thank you, Mike
". With this the Return is in there, but out of order.
2) A Shortcut in Outlook does a few things, including moving items to a specific folder. Once the move item box comes up, a Type Text command should run "follow
". Follow is typed, but the return never comes through, so the mail item isn't moved.

#### Device information:

Type of Mac: MacBook Pro 2017 13"
macOS version: 10.13.3
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.): Pasting text works when I only need to have text written - like with the first example above.

**Comment by fifafu** [comment]
this should already be fixed in the current alpha (v2.424)

**Comment by mikehdow** [comment]
Hi. 2.424 does solve the first issue (typing text), but not the second (as part of a command). Is there a way to reopen this, or should I open a new issue?

**Comment by fifafu** [comment]
To do this, attach an additional action to your shortcut and just make it trigger return (without the type text action).

The type text action currently can't send returns if they come after the text.
