### ISSUE TITLE
Magic Mouse 2 not recognized

### ISSUE THREAD

**Issue by msemp** [fifafu/BetterTouchTool#2371]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Magic Mouse 2 not recognized - I must be missing some basic configuration. I initially installed BetterTouchTool in order to get a low battery warning at 10%. But the mouse doesn't seem to be recognized at all. In the BetterTouchTool interface, when I click Magic Mouse, it shows that it's at 0%, regardless of its actual battery level. So I'm assuming that BetterTouchTool isn't actually monitoring my Magic Mouse. Any debugging suggestions would be welcomed!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse 2

#### Device information:

Type of Mac: MacBook Pro 2016
macOS version: Sierra, Version 10.12.6
BetterTouchTool version: 2.355

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, the battery functionality currently doesn't work.
I'll fix this soon. 

Continue to track this here: #1672

**Comment by barryrb** [comment]
I have exactly the same issue and look forward to a fix. Thanks.
