### ISSUE TITLE
BTT restarting frequently

### ISSUE THREAD

**Issue by mikeweilgart** [fifafu/BetterTouchTool#2375]
#### Description of bug/feature request/question:

I've just recently updated BTT to the latest 2.422 (779) and also started using an external keyboard.

I'm getting BTT restarting repeatedly — at least 6 times today.

It shows this message before it restarts:

<img width="532" alt="screen shot 2018-04-02 at 8 53 56 pm" src="https://user-images.githubusercontent.com/15166719/38228453-57baf0ec-36b8-11e8-9936-2fcaa8b6c136.png">

But neither of those accurately describes the situation.

#### Device information:

Type of Mac: MBP without touchbar
macOS version: 10.11.6
BetterTouchTool version: 2.422 (779)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by robin3** [comment]
@mikeweilgart sounds similar to this: https://github.com/fifafu/BetterTouchTool/issues/2349

**Comment by fifafu** [comment]
Yup closing here, continue in #2349
