### ISSUE TITLE
AppleScript Widget (Spotify "Now Playing") does not refresh, app-specific buttons stay around after leaving the app, touch bar doesn't show on boot

### ISSUE THREAD

**Issue by capthunter** [fifafu/BetterTouchTool#2377]
#### Description of bug/feature request/question:
All of these problems began happening at the same time (a few days ago), despite all the functions previously working; the touch bar doesn't display on start up, app-specific buttons stay around (I only have one, which is just a shortcut for F4), and the applescript widget I have showing the current spotify song playing doesn't refresh.

- The refresh period for the script is 1 second.
- BTT is set to begin on startup.
- Everything refreshes correctly when I hit a modifier key - but NOT the Fn button, which displays the F-key row. But only when I hit it; it doesn't start working normally. This includes the custom TouchBar not displaying on startup (the default MacOS one does).
- Other updating things work on the TouchBar - I have a clock which still shows the correct time.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 15", 2017, with Touch Bar
macOS version: 10.13.3
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Global Touch Bar:
<img width="811" alt="screen shot 2018-04-03 at 11 38 18" src="https://user-images.githubusercontent.com/38036681/38244772-9c4a30b2-3733-11e8-9b61-1d4011456731.png">

Excel Button:
<img width="814" alt="screen shot 2018-04-03 at 11 38 35" src="https://user-images.githubusercontent.com/38036681/38244796-a85f78a8-3733-11e8-8621-01f90e725e01.png">

Spotify Script:
`if application "Spotify" is running then`
	`tell application "Spotify"`
		`if player state is playing then`
			`set artistTitle to ((get artist of current track) & " - " & (get name of current track))`
			`if length of artistTitle is less than 42 then`
				`set displayTitle to artistTitle`
			`else`
				`set displayTitle to text 1 thru 40 of artistTitle & "..."`
			`end if`
			`return displayTitle`
		`else`
			`return "Spotify"`
		`end if`
	`end tell`
`else`
	`return ""`
`end if`

**Comment by fifafu** [comment]
Your script seems to work fine here.

For the "visible on boot": BTT remembers the last visible state, so if the BTT touchbar was hidden before shutdown it will also be hidden after starting again.
In general there hasn't been a change to that functionality recently.

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com then I'll look into it.

**Comment by fifafu** [comment]
Unfortunately I can't seem to reproduce your issue on my machine  yet :(

I loaded your config and the BetterTouchTool Touch Bar was **not** visible. However this was because it was toggled off using the shortcut you defined (opt + # ).
After toggling it on it seems to work correctly here, also after restarting BTT.

Maybe I misunderstand something?

**Comment by capthunter** [comment]
Ah! How odd, I assumed since it was showing at times it was on. Turns out
it was just "off" - but still displaying?

I just toggled it again using opt + #, and the problem went away.

Well - there you go, the toggle option doesn't necessarily hide the bar if
a modifier is pressed.

Thank you for your help,
Hunter

**Comment by fifafu** [comment]
Ah that's interesting, I'll look into that!

**Comment by dicetomato** [comment]
I'm having the same problem with the latest version of BTT. For some reason stopped working for me. It now just doesn’t update when the song changes, even though my settings are correct. Anyone else having issues with the latest version of BetterTouchTool?
