### ISSUE TITLE
After using Trigger Mouse, Menus (main OS menu bar) do not work properly

### ISSUE THREAD

**Issue by DavidMBrown** [fifafu/BetterTouchTool#2386]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have a gesture set to Tigger Mouse Down, which works as expected. However, after using it, menu selection in the main OS menu bar no longer works properly. Normally, after a menu is clicked, the menu is displayed and, as the cursor is moved down the menu, the various menu selections are highlighted. But, after using Trigger Mouse Down and subsequently clicking on a menu, moving the cursor down the menu no longer results in highlighting the various menu items. (The same issue also exists when you move the cursor horizontally across the menu bar.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse 2

#### Device information:

Type of Mac: iMac Pro
macOS version: 10.13.4
BetterTouchTool version: 2.423 (problem also exists in latest non-alpha version.)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you show me how you configured your trigger?

**Comment by DavidMBrown** [comment]
My apologies for not providing a more thorough explanation. The Gesture has one Action: Trigger Mouse Down; Left Mouse Button - From the Predefined Action More Mouse Buttons and Modifiers. So the Gesture results in a click and hold. I can then do things such as move a slider (my main purpose) or move a window. In order to "dismiss" the click and hold, I click again. It is then that the Menu selections are effected. After writing to you the first time, I came up with the idea of creating a second Gesture for Trigger Mouse Up. After using those two gestures, Menu selections behave normally again. I have attached a screenshot of my preferences.
Perhaps you could add an action for Toggle Mouse Up or Down, in which case I could use the same Gesture for both initiating a click and hold and for cancelling it. Having one Gesture would be a little cleaner.
![screen shot 2018-04-04 at 5 49 07 pm](https://user-images.githubusercontent.com/4664463/38336712-bf00139e-3830-11e8-9cac-575b5b7b1e60.png)

**Comment by fifafu** [comment]
I will add an additional option to the custom click action "Toggle Click (Up/Down)". Should be available in the next version.

**Comment by DavidMBrown** [comment]
Thank you for adding the action - it is much appreciated.

**Comment by DavidMBrown** [comment]
I realize you have been busy with BTT of late, but I'd appreciate if the Toggle Click (Up/Down) was implemented in the near future. Thanks - and thanks for a great product.
