### ISSUE TITLE
Can't Add Switch Presets Button

### ISSUE THREAD

**Issue by CarterVE** [fifafu/BetterTouchTool#2387]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm experiencing an issue where I cannot add a touch bar button or keyboard shortcut to switch between presets. 

The second preset (not Default) is one I created where I exported the default, then re-imported it and edited/removed some scripts to draw less power. When I attempted to add a button to toggle between presets with your included function, the Default is checked no matter what options I choose.

If there is a way around this, or something I'm not understanding, please let me know! Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.424 (781)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1015" alt="screen shot 2018-04-03 at 11 51 12 pm" src="https://user-images.githubusercontent.com/18474523/38287863-1d688aa6-379b-11e8-98b6-178f9b4bdf66.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Ah that's a bug.
Could you try to open the exported JSON in a text editor and change the BTTPresetUUID a bit?

I'll change it so exported presets get a different UUID.
