### ISSUE TITLE
Move Window To Desktop "2, 3, 4 ..." do not work.

### ISSUE THREAD

**Issue by sk777club** [fifafu/BetterTouchTool#2388]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Move Window To Desktop "2, 3, 4 ..." do not work.

#### Device information:

Type of Mac: MacBook Pro (Retina 13 Zoll, Anfang 2015)
macOS version: macOS 10.13.4
BetterTouchTool version: 2.424

**Comment by fifafu** [comment]
They seem to work fine on my machines. 
However you need to have the desktops open already.

**Comment by sk777club** [comment]
I tried everything and it did not work. Then I deleted my master preset and suddenly it works. Strange. Thanks ;)
