### ISSUE TITLE
Create TouchBar buttons to insert Emojis

### ISSUE THREAD

**Issue by FinanceTutor** [fifafu/BetterTouchTool#239]
#### Description of your bug/question/feature request...:
In some applications where you are typing text (i.e. Mac WhatsApp application) the TouchBar does not show the Emoji button (which opens the emoji slider) on its own. To solve this problem I tried to create a workaround by adding TouchBar buttons that insert a specific emoji. **The issue is**: You can use an emoji as the TouchBar Button Name but if you put an emoji into _Custom Keyboard Shortcut_ it automatically changes it to _"A"_ (check the attached image).
<img width="578" alt="bildschirmfoto 2017-01-11 um 15 49 44" src="https://cloud.githubusercontent.com/assets/25058909/21853001/9e97a616-d815-11e6-867a-d93e134d6251.png">

**What kind of Mac are you using?**
-MacBook Pro late 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
-TouchBar 

**Which versions of macOS and BetterTouchTool are you running?**
-macOS Sierra
-BTT v.1.978

**Solution:**
1. It would be epic if one were able to make one TouchBar button insert a specific emoji.
2. Maybe you could even implement the option to activate the Emoji button on the TouchBar button in every application.

**Comment by fifafu** [comment]
Hey,

for now you can use the predefined action "Paste Custom Text", in one of the next versions I'll add a dedicated Emoji Widget.

Best,
Andreas

**Comment by fifafu** [comment]
I have just added a basic emoji picker, it will be available with the next update later today (1.998)
