### ISSUE TITLE
 is there any way to add shortcuts for custom actions onto the same page as the trackpad in the better touch tool remote?

### ISSUE THREAD

**Issue by Mas0n01** [fifafu/BetterTouchTool#2390]
#### Description of bug/feature request/question:

Hi, is there any way to add shortcuts for custom actions onto the same page as the trackpad in the better touch tool remote? I don't use functions like escape or changing the brightness often on better touch tool remote and would prefer to add my own custom actions/macros there instead.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

better touch tool remote and imac 

#### Device information:

Type of Mac: imac 
macOS version: 10.13.3 
BetterTouchTool version: 2.425

**Comment by fifafu** [comment]
Hi,

no that's not possible, sorry.
I plan a much more customizable version, but this is still a few months away.
