### ISSUE TITLE
Shortcuts not recognized when initiated without the actual keyboard

### ISSUE THREAD

**Issue by pandastick** [fifafu/BetterTouchTool#2391]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---
#### Description of bug/feature request/question:
Since the upgrade to 2.405 and the detection of left/right modifier keys, my Logitech mouse actions are not recognized anymore. 

As you mention in http://docs.bettertouchtool.net/docs/normal_mice_problems.html , I use a workaround by assigning shortcuts to each mouse button in the Logitech software (eg SHIFT ALT CMD 1 for button 1), and then assigning that combination as a shortcut to actions in BTT under the keyboard pane. Since the 405 upgrade these shortcuts are not detected by BTT when initiated through the mouse (unless i perform them by actually pressing the keys down on the keyboard). The "on down" parameter doesn't change anything. 

Can't (literally) live without this, having to revert to 2.340 until something is done.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal Mouse

#### Device information:

Type of Mac: Mac Mini, Macbook, Macbook PRO
macOS version: 10.12.6
BetterTouchTool version: 2.405+

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
For some synthetic keyboard events you need to enable the old shortcut implementation:

![image](https://user-images.githubusercontent.com/8820811/38325862-871447de-3844-11e8-8430-47b4b609f301.png)

I'll probably add an option to enable the old method for specific shortcuts only.
