### ISSUE TITLE
Release Notes typo

### ISSUE THREAD

**Issue by qayshp** [fifafu/BetterTouchTool#2393]
#### Description of bug/feature request/question:
On the latest [Release Notes](https://updates.bettertouchtool.net/bettertouchtool_release_notes.html), the date for 2.422 is listed as March 22, 2017 instead of 2018.
There are also versions not listed, but I'm guessing that is possibly as desired.

**Comment by fifafu** [comment]
Thanks, fixed!
Yes alpha versions and the like are not displayed in the official release notes
