### ISSUE TITLE
BTT lockup, 100% CPU

### ISSUE THREAD

**Issue by bdlow** [fifafu/BetterTouchTool#2394]
#### Description of bug/feature request/question:

BTT hits 100% CPU; this has been happening since shortly after v 2.332.

Repro:
- delete ~/Library/Application\ Support/BetterTouchTool
- open BTT
- import the config given below; this was exported from the brief period before BTT locks up

- wait a bit; possibly triggered by a cmd-tab
- BTT eats a core, ~95+% CPU; unresponsive

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
unknown; only keyboard and mouse configured

#### Device information:

Type of Mac: MacBookPro14,2
macOS version:  macOS 10.13.4 (17E199)
BetterTouchTool version: 2.425

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

--

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

    {
      "BTTPresetName" : "Default",
      "BTTPresetUUID" : "D920F1F2-51BA-4B84-B7CF-A57BD293CE0B",
      "BTTPresetContent" : [
        {
          "BTTAppBundleIdentifier" : "com.apple.finder",
          "BTTAppName" : "Finder",
          "BTTTriggers" : [

          ]
        },
        {
          "BTTAppBundleIdentifier" : "BT.G",
          "BTTAppName" : "Global",
          "BTTTriggers" : [
            {
              "BTTTriggerType" : 998,
              "BTTTriggerTypeDescription" : "Scroll Left",
              "BTTTriggerClass" : "BTTTriggerTypeNormalMouse",
              "BTTPredefinedActionType" : 113,
              "BTTPredefinedActionName" : "Move Left a Space",
              "BTTEnabled" : 1,
              "BTTRequiredModifierKeys" : 1048576,
              "BTTOrder" : 3
            },
            {
              "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
              "BTTPredefinedActionType" : 158,
              "BTTPredefinedActionName" : "Lock Screen",
              "BTTEnabled" : 1,
              "BTTShortcutKeyCode" : 71,
              "BTTShortcutModifierKeys" : 9437184,
              "BTTOrder" : 1
            },
            {
              "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
              "BTTPredefinedActionType" : 114,
              "BTTPredefinedActionName" : "Move Right a Space",
              "BTTEnabled" : 1,
              "BTTShortcutKeyCode" : 124,
              "BTTShortcutModifierKeys" : 9961472,
              "BTTOrder" : 3
            },
            {
              "BTTTriggerType" : 996,
              "BTTTriggerTypeDescription" : "Scroll Down",
              "BTTTriggerClass" : "BTTTriggerTypeNormalMouse",
              "BTTPredefinedActionType" : -1,
              "BTTPredefinedActionName" : "No Action",
              "BTTShortcutToSend" : "124",
              "BTTEnabled" : 1,
              "BTTRequiredModifierKeys" : 131072,
              "BTTOrder" : 4
            },
            {
              "BTTTriggerType" : 997,
              "BTTTriggerTypeDescription" : "Scroll Up",
              "BTTTriggerClass" : "BTTTriggerTypeNormalMouse",
              "BTTPredefinedActionType" : -1,
              "BTTPredefinedActionName" : "No Action",
              "BTTShortcutToSend" : "123",
              "BTTEnabled" : 1,
              "BTTRequiredModifierKeys" : 131072,
              "BTTOrder" : 5
            },
            {
              "BTTTriggerType" : 999,
              "BTTTriggerTypeDescription" : "Scroll Right",
              "BTTTriggerClass" : "BTTTriggerTypeNormalMouse",
              "BTTPredefinedActionType" : 78,
              "BTTPredefinedActionName" : "3F Swipe Right (Page Forward)",
              "BTTEnabled" : 1,
              "BTTOrder" : 0
            },
            {
              "BTTTriggerType" : 999,
              "BTTTriggerTypeDescription" : "Scroll Right",
              "BTTTriggerClass" : "BTTTriggerTypeNormalMouse",
              "BTTPredefinedActionType" : 114,
              "BTTPredefinedActionName" : "Move Right a Space",
              "BTTEnabled" : 1,
              "BTTRequiredModifierKeys" : 1048576,
              "BTTOrder" : 2
            },
            {
              "BTTTriggerType" : 998,
              "BTTTriggerTypeDescription" : "Scroll Left",
              "BTTTriggerClass" : "BTTTriggerTypeNormalMouse",
              "BTTPredefinedActionType" : 77,
              "BTTPredefinedActionName" : "3F Swipe Left (Page Back)",
              "BTTEnabled" : 1,
              "BTTOrder" : 1
            },
            {
              "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
              "BTTPredefinedActionType" : 158,
              "BTTPredefinedActionName" : "Lock Screen",
              "BTTEnabled" : 1,
              "BTTShortcutKeyCode" : 105,
              "BTTShortcutModifierKeys" : 9437184,
              "BTTOrder" : 2
            },
            {
              "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
              "BTTPredefinedActionType" : 113,
              "BTTPredefinedActionName" : "Move Left a Space",
              "BTTEnabled" : 1,
              "BTTShortcutKeyCode" : 123,
              "BTTShortcutModifierKeys" : 9961472,
              "BTTOrder" : 4
            },
            {
              "BTTTriggerType" : -1,
              "BTTTriggerClass" : "BTTTriggerTypeBTTRemote",
              "BTTPredefinedActionType" : -1,
              "BTTPredefinedActionName" : "No Action",
              "BTTEnabled" : 1,
              "BTTOrder" : 0
            },
            {
              "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
              "BTTPredefinedActionType" : -1,
              "BTTPredefinedActionName" : "No Action",
              "BTTShortcutToSend" : "55,48",
              "BTTEnabled" : 1,
              "BTTShortcutKeyCode" : 48,
              "BTTShortcutModifierKeys" : 1048576,
              "BTTOrder" : 0
            }
          ]
        }
      ]  
    }

**Comment by fifafu** [comment]
You have one shortcut defined with cmd+tab triggering cmd+tab. This will cause an endless loop unless you check "prevent recursive triggers"

![image](https://user-images.githubusercontent.com/8820811/38350734-e2889c60-38ac-11e8-8f48-e563379d694d.png)

**Comment by bdlow** [comment]
So there is. Odd, as I didn't create that. Deleting it has indeed fixed things.

**Comment by fifafu** [comment]
Hehe well that looks like an accidental add (having the shortcut recorder field active and pressing cmd+tab to switch to a different app)

Glad it was an easy fix!
