### ISSUE TITLE
Alternative for "Delete typed Characters", which is dangerous

### ISSUE THREAD

**Issue by dlohm** [fifafu/BetterTouchTool#2396]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have been using BTT to improve Window-Management via the Keyboard and especially love the ability to define **key sequences** as triggers, which is a unique feature of BTT on the Mac!

Of course, I do not want the key sequence used to trigger window management to become part of the input of the current application. So I let BTT _Delete typed Characters_. I somehow assumed that the characters will be deleted from the current application's input queue _before_ they are processed by the application, which apparently is _not_ the case.

Hence,  depending on the current context, this is a pretty dangerous thing: Invoking a trigger from e.g., Mail or Finder will "silently" delete messages and files.

#### Suggestions

1. First of all, BTT should **warn** users when ticking the _Delete typed Characters_ option. It is easy to misunderstood this or at least do not realize the full consequences
2. On the longer term, It would be great if BTT offers an option to catch key sequences _before_ they are processed by the application.

I assume (2) is a bit difficult to achieve as it may cause input lag on the application: BTT would have to make sure the last pressed key does not belong to a key sequence before it can be transmit to the application. In that case an option might be to restrict this holding back of key events only for a few _leading sequences_ (such as pressing some modifier twice in a row).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Any keybord

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2016)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.4.22

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I have added a warning, will be available in the next update. In one of the next versions I'll also add an option to make it only send the backspace key while textfields are active (this won't work in older applications though)

Catching it before they are processed is not possible, BTT can't know in advance whether you are gonna type a trigger word or not. This would introduce an delay that would completely destroy typing :-)

**Comment by dlohm** [comment]
Thanks for the quick response!

I perfectly understand the delay issue. Maybe it would option to support catch-and-delay only for one specific key (e.g., the Fn modifier)? So we would (optionally) have one key to initiate a BTT key sequence that is guaranteed to have no side effects (for the price that secondary features belonging to that key may be delayed). 

I am still insisting as basically every key can lead to unexpected side effects in the current application. (Of course, backspace is particularly problematic.)
