### ISSUE TITLE
Can't get BTT's Touch Bar back after tapping the button to temporarily toggle to 

### ISSUE THREAD

**Issue by callumlocke** [fifafu/BetterTouchTool#2398]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I followed [this blog post](http://vas3k.com/blog/touchbar/) to set up a custom Touch Bar using BTT. It was amazing, for about 5 minutes. Then I tried tapping the little button to toggle the standard macOS touch bar. And now there's no way to switch back. I am stuck on the default macOS Touch Bar.

I've tried restarting BTT multiple times, disabling BTT's touch bar, restarting, re-enabling it, restarting... Nothing works. I've tried activating the special action "Toggle BetterTouchTool Touch Bar" and that doesn't work either. I've rebooted macOS too. Nothing works.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15
macOS version: Sierra
BetterTouchTool version: 2.425

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://user-images.githubusercontent.com/250617/38366325-4edd9990-38d7-11e8-8dd3-edea610e0b10.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If you have hidden the Control Strip you need to define another trigger in BTT to get it back. E.g. a keyboard shortcut like in this screenshot: 
![image](https://user-images.githubusercontent.com/8820811/38366670-d4c2b276-38e0-11e8-9054-e33c6f02f382.png)

**Comment by callumlocke** [comment]
>  I've tried activating the special action "Toggle BetterTouchTool Touch Bar" and that doesn't work either.

**Comment by fifafu** [comment]
That definitely works, how did you try to activate it?

**Comment by callumlocke** [comment]
It doesn't work for me. I've just tried using the exact method in your screenshot, and that doesn't work. To double-check the keyboard shortcut is working, I tried changing the action to something else, and it works. But when the action is "Toggle BetterTouchTool Touch Bar", nothing happens.

Also, I just tried completely uninstalling BTT using App Cleaner, and reinstalling it, and even now I still can't get it to show me the custom Touch Bar.

**Comment by fifafu** [comment]
That is very weird.

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com and reference this issue then I'll look into it.

Maybe BTT got disabled for some reason? 
One more thing, I just saw you are using Sierra. On Sierra it is necessary to set "Touch Bar shows" to "App Controls with Control Strip" in System Preferences => Keyboard for BTT to work correctly.

**Comment by guiporto** [comment]
I've been having the exact same issue. When I set up BTT my "Touch bar shows" was set to "Expanded Control Strip". I've changed it to "App Controls with Control Strip" but no luck.
I'm using High Sierra.
I'm sending the debug info to your email

**Comment by fifafu** [comment]
@guiporto your config seems to work fine here (after pressing the BTT icon in the control strip). Which version of BTT are you using?

**Comment by guiporto** [comment]
I’ve just downloaded it. I’m using 2.425

**Comment by fifafu** [comment]
Pressing the BTT icon in the control strip doesn't do anything? 
I have never heard of such an issue before, which is why I still think it's some configuration problem, but I'll try to reproduce it on another machine!

**Comment by guiporto** [comment]
the BTT icon doesn't show up in the control strip :/

**Comment by fifafu** [comment]
Could you try to add a keyboard shortcut to toggle the touchbar like in the screenshot above?

**Comment by guiporto** [comment]
now it worked, thanks!
Here's a tip:
if the user doesn't have the "App Controls with Control Strip" selected and accidentally clicks on the BTT button, the BTT icon won't appear again.
If the user changes it to "App Controls with Control Strip", the button should appear again.

Interestingly the BTT icon wasn't showing up before, and I can't reproduce what led it to re-appear.

**Comment by callumlocke** [comment]
Switching the native settings back to `App Controls with Control Strip` worked for me too. Maybe this should be added as a note in the Touch Bar settings dialog in BTT?

**Comment by fifafu** [comment]
Yes, I once had a warning message pop up about that, but apparently it doesn't show up anymore. Will fix that.
