### ISSUE TITLE
When TouchBar is waking up from dim, apps don't scroll smoothly

### ISSUE THREAD

**Issue by janzah** [fifafu/BetterTouchTool#2399]
Hi, when TouchBar support is enabled and the TouchBar goes to dim state after few seconds of inactivity, and then I scroll down eg. content displayed in web browser, the scrolling is not smooth while the TouchBar is waking up. Instead, it jumps down. Once the TouchBar is woken up, smooth scrolling works again... I disabled TouchBar support in BTT and everything works.

Type of Mac: Macbook Pro 15" 2017
macOS version: 10.13.4
BetterTouchTool version: 2.425 (782)

<img width="826" alt="screen shot 2018-04-05 at 16 39 26" src="https://user-images.githubusercontent.com/38107397/38372799-f55356f8-38ef-11e8-9791-20335cd79beb.png">

**Comment by fifafu** [comment]
That's an issue with 10.13.4 unfortunately. As far as I know it's already fixed on 10.13.5.

**Comment by janzah** [comment]
Thank you for the fast reply. You're right, it seems it doesn't happen with default TouchBar but as soon as any app displays its own TouchBar icons (even if BTT is not running), the issue shows up.

**Comment by fifafu** [comment]
Yep (in the background an exception is thrown every time the touchbar undims, which causes the hiccups). The fix apparently didn't make it to the 10.13.4 final version....
