### ISSUE TITLE
Command-A causes "copy all gestures" menu to appear when it shouldn't

### ISSUE THREAD

**Issue by colinfoster** [fifafu/BetterTouchTool#24]
#### Description
On most device configuration screens, in the left column there is a cog for activating a menu. This menu is also activated by command-A. If you switch to News and hit command-A, it appears in the lower left corner of the current display.

**What kind of Mac are you using?**
MacBook Air 2015, 2.2GHz Core-i7

**Which input device**
Not related to a device.
News Area (and others) of BTT configuration screen

**Which version of macOS are you running?**
10.12.1

**Other information:**
Other configuration tabs that don't have this cog visible (e.g., "Basic Settings") also have this behaviour. The code just needs to check if it's on a screen where the cog appears before trying to bring up the menu.
![screen shot 2016-12-06 at 10 47 52 am](https://cloud.githubusercontent.com/assets/491234/20932107/7dd9dfc4-bba1-11e6-97f0-42c681f79ddd.png)

**Comment by fifafu** [comment]
Thanks for reporting!
