### ISSUE TITLE
Mouse button double click macros

### ISSUE THREAD

**Issue by kamil6x** [fifafu/BetterTouchTool#240]
Feature Request: 
Macbook Pro 2015
External Mouse
OS X 10.11.6, BTT 1.963

Could you add a double click option to the mouse macros.  So for example CTRL-ALT single click maximizes window, CTRL-ALT double click restores window size.

**Comment by fifafu** [comment]
Hey, 

sorry for not replying earlier.
This is now possible using the "More mouse buttons & modifiers" predefined action

![image](https://user-images.githubusercontent.com/8820811/30249224-0c523122-9638-11e7-9274-55ffa48c1b43.png)

**Comment by 03cranec** [comment]
This solves the problem of wanting to trigger double clicks. But I think what the original issue was referring to (and what I'm hoping for) is the ability to trigger ON a double click. In my case, I'd like to map an action/shortcut to a double middle click.

**Comment by YamenSharaf** [comment]
@fifafu Is there a place where I can find this double click functionality in the newer versions. I can't find it and I wanna map double-click to other keys
