### ISSUE TITLE
Keycode should not move when changing the language. Or optionally move

### ISSUE THREAD

**Issue by henri-tremblay** [fifafu/BetterTouchTool#2400]
#### Description of bug/feature request/question:

I use two keyboard layouts. When on the US keyboard, I can Cmd+` to switch window. So far so good.

But when switching to CA_fr, this key becomes Cmd+ù. But it is the same physical key (same keycode).

So, to workaround Apple being dumb I want to use BTT.

The idea is that if I press Cmd+ù, it should call the switch window. I don't think I can bind directly "switch window", I can't find it in the available actions.

And I can't forward Cmd+ù to Cmd+` because BTT is switching the letter according to the keyboard layout. It probably makes sense in most cases but not in this one.

The keycode of Cmd+` on the CA_fr keyboard is Cmd+Opt+\ on the US keyboard. So to make things simple, when on CA_fr I want  Cmd+ù to transform into Cmd+Opt+\ and when on the US keyboard, I want nothing (or anything that won't interfere with Cmd+`).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MBP (previous versio, no magic bar)
macOS version: 10.12.6
BetterTouchTool version: 2.422

**Comment by fifafu** [comment]
I haven't found a reliable way to do this. Unfortunately all the APIs BTT uses work with the keycodes. #518

**Comment by henri-tremblay** [comment]
Can't you just remap a keycode to another one when in a given language?

**Comment by fifafu** [comment]
No I probably won't tackle that. It is super complicated and ugly.

However maybe I can add a specific action that sends a shortcut via a character. In that case it wouldn't be too bad if it would break in various cases. (I already have a method that can translate a character to a keycode, but I'm 100% sure it only covers the most basic usecases and won't work in general)

Maybe you could try to use Apple Script like this
```
tell application "System Events"
	keystroke "´" using command down
end tell
```

**Comment by fifafu** [comment]
Eh sorry I was confused because I was working on another issue at the same time, the Apple Script solution obviously wouldn't work :-D

**Comment by fifafu** [comment]
Haha sorry for the complete confusion, I shouldn't have so many tabs open.

Actually the Apple Script solution may work in your case...
So again, maybe try to assign the predefined action "Run Apple Script (enter directly as text)" to the  ```cmd+ù```  shortcut and enter this apple script:

```
tell application "System Events"
	keystroke "´" using command down
end tell
```

**Comment by henri-tremblay** [comment]
You're a magician! It works perfectly!
