### ISSUE TITLE
[Bug] The functionality "inverse scrolling for normal mice only" doesn't work after BTT upgrade

### ISSUE THREAD

**Issue by star114** [fifafu/BetterTouchTool#2403]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The functionality "inverse scrolling for normal mice only" doesn't work after BTT upgrade.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Normal mouse (Microsoft Sculpt Ergonomic Mouse)

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.13.4
BetterTouchTool version: 2.424 (781)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

After upgrade!

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, this was a bug in 2.424, it's already fixed in the latest alphas (get via "check for alpha version updates")

**Comment by star114** [comment]
Thank you!
BTW, I’m just wondering when the latest alphas will be released officially.
