### ISSUE TITLE
The gesture settings for the keyboard, mouse, and others were not displayed any more. If I'm not mistaken, they were located at the top of the interface. Can you please tell us how to add and change gestures for keyboard and mouse now?

### ISSUE THREAD

**Issue by vv2002** [fifafu/BetterTouchTool#2418]
The gesture settings for the keyboard, mouse, and others were not displayed any more, only the trackpad remained as the default. If I'm not mistaken, they were located at the top of the interface. Can you please tell how to add and change gestures for keyboard and mouse now?
Screenshot of the interface by link - https://prnt.sc/j2r0as
---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

#### Device information:

Type of Mac:  Macbook Pro 13 Late 2015
macOS version: 10.13.3
BetterTouchTool version: Don't know where it is

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you set your screen resolution to something very very low? I'm that case the BTT window may not fit on screen and macOS will break the layout to make it fit.

**Comment by vv2002** [comment]
Now resolution is in "Larger Text", but I tried "Default" also, it is same.

**Comment by fifafu** [comment]
You may need to restart BTT after changing the resolution

**Comment by vv2002** [comment]
Yes, you're right. Yes, you are right, after the restart in the default mode, the controls appeared. Appeared in the same way and after returning in "Larger text" mode.  Thank you.
