### ISSUE TITLE
Touchbar settings do not load back up properly

### ISSUE THREAD

**Issue by njdwklopper** [fifafu/BetterTouchTool#242]
When the mac goes to sleep or something BTT restores it's settings in the wrong way, this causes the buttons for TouchBar to be messed up and not working. I have to import settings I exported to fix the issue every time.

Macbook Pro 2016 15" Touchbar

Touchbar section of BTT App is affected

System Version:	macOS 10.12.3 (16D25a)
Kernel Version:	Darwin 16.4.0
BTT Version   :    1.985 (578)

How to reproduce:
1.Click TouchBar Tab
2.Add new application (Mine was IntelliJ Idea)
3.Create new touchbar button 
4.Set shortcut on above button
5.Attach additional action
6.Set shorcut on additional action
7.Quit BTT
8.Open BTT
9.Go to TouchBar Tab

Expected:
TouchBar settings should have one button with two actions

Actual:
Touchbar settings have two buttons now

Correct settings:
<img width="908" alt="screen shot 2017-01-12 at 15 18 24" src="https://cloud.githubusercontent.com/assets/20532948/21891296/a5b0b3c8-d8da-11e6-9171-d6c9ed6357d1.png">

Settings that went haywire and need an import to fix:
<img width="910" alt="screen shot 2017-01-12 at 15 18 50" src="https://cloud.githubusercontent.com/assets/20532948/21891298/a64823c0-d8da-11e6-9e7c-84b3eec2a179.png">

**Comment by fifafu** [comment]
indeed, I can reproduce the issue, thanks for reporting! WIll release a fix later today!

**Comment by fifafu** [comment]
Should be fixed in v1.986!
