### ISSUE TITLE
access to the (alpha?) update Note

### ISSUE THREAD

**Issue by oliviermattelaer** [fifafu/BetterTouchTool#2428]
When BTT proposes to update (to alpha or not), you have some nice Update Note information.
However, those are lost as soon as you have updated and I did not found them online.
Did I miss the link? Can those be put online? 

Thanks,

Olivier

**Comment by fifafu** [comment]
Next alpha later today will have a menu to access them:
![image](https://user-images.githubusercontent.com/8820811/38556358-ae4c6474-3cc9-11e8-9f2c-37253831fa8f.png)

**Comment by oliviermattelaer** [comment]
Thanks, that's really great!
