### ISSUE TITLE
Touchbar shows global Buttons rather than app-specific

### ISSUE THREAD

**Issue by verstaerkermusic** [fifafu/BetterTouchTool#243]
#### Description of your bug/question/feature request...:
when I switch between apps the touchbar  shows the global-buttons rather then the app-specific
when I switch from a custom configured app to a system app ,for instance from thunderbird to safari:
i have safari open with the correct system buttons, I switch to thunderbird , wich has some custom buttons - then when switching back to safari the touchbar shows the global buttons

**What kind of Mac are you using?**
MBP 15 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2, BTT 1.985(578)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
I would expect that if I switch between apps always the state when I left the app is recovered when I switch back

**Comment by verstaerkermusic** [comment]
it doesn't happen if I delete all buttons from Global

**Comment by fifafu** [comment]
If you want to force show/hide the BetterTouchTool Touch Bar you can use the app-specific settings, see attached screenshots.

If no special handling is set, BetterTouchTool will keep it's visibility state and only hide/show the Touch Bar when pressing the BTT icon in the Control Strip.

![image](https://cloud.githubusercontent.com/assets/8820811/21909105/cb6dfbc0-d916-11e6-8212-b019f7621dbb.png)

**Comment by verstaerkermusic** [comment]
thanks ... I think I understand this options. But still as soon as I add items to the Global menu it's getting mixed up. I don't want to press a button in safari just reach for the default buttons.
Or do I need to add all apps I'm using and specify the mode? I would expect if I don't add an app it just keeps the default mode.

**Comment by fifafu** [comment]
No, so if you press the BTT icon to hide the Touchbar it should stay hidden unless you press the button again.

Isn't it like that on your machine?

**Comment by verstaerkermusic** [comment]
sorry it looks like we are talking about different thinks. 
My intended setup:
I have a set of global functions that appear when I hit the BTT button.
Also I want to run the apple apps (mail, safari, pages) without any change and have some apps that doesn't support touchbar yet (Ableton Live in my case) - when switching from safari (showing the default buttons) to Ableton Live , I want that to show my custom buttons . That works after I pressed the BTT button Ableton Live shows my Buttons. Then I switch back to Safari ... why does it show the global buttons instead of the apps default ones? My solution now would be add all apple apps and set them to app default mode. But I feel that is kind of unnecessary work - as this is to my thinking the default mode everybody would expect. No?

**Comment by verstaerkermusic** [comment]
ouch: I think messed some settings with the touchbar-behaviour of the apps up ... now it seems to work correct .. no need to add all apps that I don't want to change.

**Comment by fifafu** [comment]
Unfortunately BTT has no way of knowing whether an app does have it's own buttons. Also many users just want to have their global custom BTT Touch Bar always.

**Comment by verstaerkermusic** [comment]
ok great so far .. now one strange thing I might have setup wrong:
when im in safari and hit the BTT button my global buttons are shown. Perfect.
When I'm in Ableton Live and my custom buttons are shown and I press now the BTT button I get an empty touchbar (only the control strip is visible). I don't manage from within Live to display the Global touchbar.

**Comment by verstaerkermusic** [comment]
alright - I figured out: from custom configured apps I need to hold the BTT button a second or so in order to switch to global... thats cool.
