### ISSUE TITLE
Possible to syslink config files?

### ISSUE THREAD

**Issue by Nxt3** [fifafu/BetterTouchTool#2436]
I have a private repo of stuff I share between my personal and work laptops. What files would I have to syslink in order to maintain configuration changes for both computers?

**Comment by fifafu** [comment]
Best to use the integrated Dropbox sync (advanced prefs).

Otherwise you can try ~/Library/Application Support/BetterTouchTool and ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist (but symlinking them can be problematic)

**Comment by Nxt3** [comment]
Do you have any plans to fully support syslinking? My work blocks Dropbox so that's why I've resorted to a private repo.
