### ISSUE TITLE
BTT icon on touchbar is broken

### ISSUE THREAD

**Issue by dimagoltsman** [fifafu/BetterTouchTool#244]
The BTT icon on touchbar is broken sometimes, i dont know what causing it but only restart of BTT resets it. after some usage its broken again (image attached).

**What kind of Mac are you using?**
MacBook Pro (15-inch, 2016) with touchbar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
Mac OS Sierra 10.12.2 (16C67)
BTT 1.985 

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

![20170112_223558](https://cloud.githubusercontent.com/assets/1561226/21907595/d00cf2ec-d918-11e6-94d7-116ef392a2bf.jpg)

**Comment by fifafu** [comment]
Unfortunately that's something I can not influence as it's completely handled by the system. I have also seen this happen on 10.12.2 but not yet on the new macOS developer beta, so let's hope it'll be fixed soon!

**Comment by dimagoltsman** [comment]
ok cool, lets hope its fixed in the new osx. thanx
