### ISSUE TITLE
Date/Time Widget timezone not automatic.

### ISSUE THREAD

**Issue by cameroncooke** [fifafu/BetterTouchTool#2446]
#### Description of bug/feature request/question:

Why does the Date / Time widget need the timezone to be specified, shouldn't the widget just use the system date/time and locale settings. My clock was an hour behind because the widget settings timezone is set to 0. In the UK we have summer (GMT+1) time and winter time. Having to manually manage this in the app is a pain when the OS already handles this.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro (15-inch, 2017)

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13.4 (17E199)
BetterTouchTool version: 2.430b

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[DateWidget.json.zip](https://github.com/fifafu/BetterTouchTool/files/1906460/DateWidget.json.zip)

[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1906457/BetterTouchToolDebug.zip)

**Comment by GoldenChaos** [comment]
Seems like this was a bug introduced in the latest alpha release, I don't remember it being an issue in the previous alpha.

**Comment by fifafu** [comment]
Ah yes, the previous versions didn't allow to change the timezone.

I'll fix it with the next alpha update!

**Comment by fifafu** [comment]
Should be fixed in v2.432

**Comment by cameroncooke** [comment]
Yep appears fixed. Thanks!

**Comment by cameroncooke** [comment]
Looks like there may have been a regression in `2.500` as my clock widget is now showing the time an hour behind again. I'm in the UK and it's GMT+1 (BST) and this should be handled by the system locale and clock setting.

**Comment by fifafu** [comment]
@cameroncooke weird, what does the timezone setting in BTT say?

**Comment by fifafu** [comment]
Mh I don't know why this may have been reset. Changing it to 1 should fix the issue for now, correct?

In the next version I'll allow "location" based time zones which should make this easier.
