### ISSUE TITLE
Button dimension issue

### ISSUE THREAD

**Issue by cameroncooke** [fifafu/BetterTouchTool#2447]
#### Description of bug/feature request/question:

I'm struggling to understand how the icon sizing and button sizing works. I'm finding it quite hard to get icons to appear without appearing distorted (i.e. squashed). This is even true when using official Apple Touch Bar icons.

I'm also finding it really hard to get the buttons to appear the same size. 

Apple's official touch-bar icons include the `@2x` retina and non-retina versions. If I'm using the official icons in my buttons I would expect this to render perfectly, but they always appear smaller. Should I use the `2x` or the non-retina icon. If the `2x` do I set the icon size to match the non-retina size as you would building retina based app. With BTT there doesn't appear to be way to supply the retina and non-retina versions.

AlsoI don't really understand how the padding relates to the icon size to generate the button size. What I really would prefer is just being able to set the button size explicitly and just have the icon horizontally and vertically centred based on the supplied icon size.

In my example I've got three buttons next to each other, their padding and icon width combined all equal 33 but the actually icon images and varying widths. So I would expect all three buttons to be 33pt width but they are not the same.

![buttons](https://user-images.githubusercontent.com/630601/38755256-fbe66406-3f5c-11e8-8132-749a57e02e54.png)

As you can see the middle button is much bigger than the other two, even though all three buttons have the same combined padding and icon width so they all equal 33pt.

Touch Bar icons can be found in:
`/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car`

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro (15-inch, 2017)

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13.4
BetterTouchTool version: 2.432

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1908749/BetterTouchToolDebug.zip)

**Comment by fifafu** [comment]
I have completely rewritten the sizing stuff in v2.433, possibly this has been fixed. Would be great if you'd test that version.

Explicitly setting the button size will be possible soon!

One thing to note:
There is a "keep aspect ratio" setting. When this is enabled BTT may not be able to use the icon size you entered in the widget settings.
![image](https://user-images.githubusercontent.com/8820811/38766340-e6ba83ea-3fd0-11e8-8649-7cd7aa5a37b7.png)

**Comment by cameroncooke** [comment]
Thanks for the swift response, will check it out now.

**Comment by cameroncooke** [comment]
Icon draw seems much improved thanks. Looking forward to being able to explicitly set button size. Thanks!
