### ISSUE TITLE
Chaining keyboard shortcuts with JoyStick Mapper no long works with new keyboard rewrite

### ISSUE THREAD

**Issue by Franchan** [fifafu/BetterTouchTool#2457]
#### Description of bug/feature request/question:
I am using the application Joystick Mapper to map a gamepad to the numpad keys, and using BetterTouchTool to map numpad keys to different applications. 

Ex.
Game controller (A button) -> JoyStick Mapper (Numpad 4) -> BetterTouchTool VLC (Space bar)
and
Game controller (A button) -> JoyStick Mapper (Numpad 4) -> BetterTouchTool Chrome (Close Tab)

If I record an input in BetterTouchTool using the gamepad, the recorded input appears the same as if I typed out the numpad key on a keyboard. If I attempt to use the same input from the gamepad on an application, the application doesn't detect the right input (ie. VLC doesn't pause). If I use the keyboard to type out the keypad number that was recorded by the gamepad, the application detects the right input (VLC pauses).

Issue was introduced with BetterTouchTool 2.405 with the keyboard rewrite and can be currently worked around by using old keyboard shortcut implementation.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Wiimote

#### Device information:

Type of Mac: MacbookPro 2011
macOS version: High Sierra 10.13.4
BetterTouchTool version: 2.425

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I understand this is quite a bizarre setup :). Would be good to know if this is a bug, or if it was an unintended feature that will not be supported in the future.

**Comment by fifafu** [comment]
Sorry, this is not fixable in BetterTouchTool.
You can either ask the Joystick Mapper developer to send the shortcuts at a lower level, or continue using the old keyboard shortcut implementation.

In the future I will also allow to use the old implementation just for specific shortcuts.
