### ISSUE TITLE
How do I disable middle-click closes tab?

### ISSUE THREAD

**Issue by paulbloch** [fifafu/BetterTouchTool#246]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
How do I disable middle-click closes tab?

The main thing I use BTT for is to enable middle click on the magic mouse. I use it to open a link in a new tab, or paste selected text. I would prefer if middle-click didn't close tabs in Safari, iTerm2 and Finder.

This is not strictly a BTT problem. If I test using a Dell three button mouse, the middle-click also closes tabs. I'm asking hear because I thought you might be knowledgeable about systems mouse events.

**What kind of Mac are you using?**
Multiple. This one is a "iMac (27-inch, Late 2013)". This is true for any Mac from Yosemite (at least).

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**
This iMac is running El Capitan 10.11.6 (15G1212). It is also true on Sierra.

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

Unfortunately I don't think this can be changed. The apps specifically added that feature because many people like middle click to close tabs :-)

I can only change click events entirely, but not change the app logic they trigger in specific cases.

It's possible that iTerm/Chrome  have a setting to disable it, but otherwise it's probably not possible.
