### ISSUE TITLE
Improvement Window Buttons

### ISSUE THREAD

**Issue by yaseent** [fifafu/BetterTouchTool#2467]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Hi - I've been using Right Click Red Window Button to perform CMD + Q - so the app quits.

The problem is, if I have 2 apps side-by-side, say for example, Firefox and Notes, and I right click the Red Window Button, it does not perform the action on the app that is beneath the mouse, and instead it performs the action on active app.

So if Notes was the active (topmost app), but I right click the Red Button on Firefox's window, instead of closing Firefox, it will close Notes.

This has been an issue since I started using BetterTouchTool - but I've only now decided that it's become a problem. I unexpectedly quit a very important session of Firefox by mistake and lost my tabs LOL.

#### Device information:

Type of Mac: MacBook Air (13-inch, Early 2015)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.424

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Just configure it like this :-)

![image](https://user-images.githubusercontent.com/8820811/38865911-9157c1da-423f-11e8-9a60-11518bff9bad.png)

**Comment by yaseent** [comment]
Excellent solution thanks :)
