### ISSUE TITLE
Unattended overnight "quit unexpectedly" 

### ISSUE THREAD

**Issue by daveguerin** [fifafu/BetterTouchTool#248]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

My Mac is on 24/7,  and while unattended, normally overnight, BetterTouchTool will occasionally quit unexpectedly.

2016-12-18 19:36:34.254 +0000
2017-01-01 23:22:34.701 +0000
2017-01-04 07:12:09.135 +0000
2017-01-05 06:28:24.245 +0000
2017-01-11 05:39:24.045 +0000
2017-01-13 02:29:02.982 +0000

Always the same reasons:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9'
terminating with uncaught exception of type NSException
abort() called

**What kind of Mac are you using?**

MacBook Pro 17" Early 2009

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

The BetterTouchTool application. The MacBook has a Bluetooth keyboard and a Magic Trackpad normally attached.

**Which versions of macOS and BetterTouchTool are you running?**

Mac OS X 10.11.6

BetterTouchTool 1.963 (552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

The latest crashlog is attached.

[BetterTouchTool_2017-01-13-022904.txt](https://github.com/fifafu/BetterTouchTool/files/703745/BetterTouchTool_2017-01-13-022904.txt)

**Comment by fifafu** [comment]
This should not happen in recent versions anymore. In case it still does please comment again.
