### ISSUE TITLE
Spelling Typo in Update/Licence Information

### ISSUE THREAD

**Issue by walkintom** [fifafu/BetterTouchTool#2481]
Very minor, but on version 2.422, there is a spelling typo in the update dialog that informs me that my license needs renewing.

"Your license was purchased more than two years ago. The standard **BeterTouchTool** license includes free updates for two years."

<img width="973" alt="screen shot 2018-04-18 at 09 10 50" src="https://user-images.githubusercontent.com/6242598/38919440-822b9db8-42e8-11e8-9f2a-fe44925403e5.png">

**Comment by fifafu** [comment]
Oops, thanks a lot! Fixed.
