### ISSUE TITLE
Feature request: swap control and fn keys

### ISSUE THREAD

**Issue by mohamedhafez** [fifafu/BetterTouchTool#2485]
It would be great to have an option to swap the control and fn keys.

I'm coming to mac from windows, and am used to the control key being the furthest to the left like it is on a windows keyboard. also, sometimes I use a windows-style external keyboard where the control key is still the furthest to the left regardless of the fact that I'm using it with a mac. It would be nice to have the control key just be in the same place regardless of the keyboard I'm using, and in the position I'm used to having it in.

Currently I'm using Karabiner-Elements just to achieve this swap, it would be awesome if that functionality could be put into BTT 

Either way, thanks for making such a great product! Just purchased a lifetime license:)

**Comment by msyed-verys** [comment]
This is built into OSX already. In Preferences > Keyboard > Rebind Modifier Keys.

I just switched the keys on my Alt and Windows button

**Comment by mohamedhafez** [comment]
It looks like I can make the fn key act as the control key its true, BUT you can't make the control key (or any other modifier key) act as the fn key:

![image](https://user-images.githubusercontent.com/1011417/38960999-580394a4-431b-11e8-8ef1-9e838d6fd70b.png)

**Comment by mohamedhafez** [comment]
Actually now that I think about it, I don't remember the last time I needed the fn key, the built in changing fn to control will work for me, even if my keyboard no longer has an fn key. Thanks @msyed-verys!
