### ISSUE TITLE
issue with BetterTouchTool and InDesign.

### ISSUE THREAD

**Issue by brightpavilions** [fifafu/BetterTouchTool#25]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I’m experiencing an issue using Adobe InDesign. Originally I reported it in the Adobe CC 2015 release, but I’m experiencing the issue on multiple computers and in newer versions of InDesign.

Whenever I click on an object in InDesign such as a text or image box, there is a noticeable delay before any I am able to move items or any changes are shown on screen. It can be repositioning an element, resizing a box etc. Disabling BTT for InDesign eliminates the issue, but then obviously I can’t use BTT.

I only use a few basic gestures with my MagicMouse and all rules are set globally, not app specific. I haven't run into any issues with other Adobe applications.

Is there a known issue or can you think what might be causing this issue?

**What kind of Mac are you using?**
Two different Macs
- 15" Macbook Pro – late 2013
- MacPro - late 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse and Macbook Pro trackpad

**Which version of macOS are you running?**
MacOS 10.11.x and 10.12.x

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
BetterTouchTool Version 1.930, Hash: 078E63BD839B8B71D0FE3E99B571F829B4ADFC87, OS X Version: Version 10.12.1 (Build 16B2555)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi,

could you try if disabling window snapping for Indesign fixes this? See attached screenshot
<img width="1013" alt="screen shot 2016-12-06 at 19 20 50" src="https://cloud.githubusercontent.com/assets/8820811/20937916/34826bf0-bbe9-11e6-9920-50cb4d4828d0.png">

**Comment by brightpavilions** [comment]
Yes! That appears to have fixed the issue. Thanks very much! I'll report back if the issue reappears.

**Comment by fifafu** [comment]
Could you please post the output of this terminal command here? ``` ~/Library/Preferences/ | grep adobe ``` (I'd like to disable window snapping by default but don't have InDesign, this would give me it's identifier)

**Comment by brightpavilions** [comment]
Here's what I got from that command. Note: I've obscured my username.

-bash: /Users/username/Library/Preferences/: is a directory

**Comment by fifafu** [comment]
Thanks, I think I got it!. Should work by default with 1.964 alpha
