### ISSUE TITLE
hangs and generates extra events with Terminal

### ISSUE THREAD

**Issue by gespdove** [fifafu/BetterTouchTool#250]
BTT causes hangs for minutes at a time and generates a large number of unwanted rapid copy & paste events with Terminal.

Problem takes no particular time to start. Sometimes it begins almost immediately after starting Terminal or BTT, sometimes takes hours of use to show up. If computer sleeps with both applications running, the same unpredictable start time behavior shows next time I use Terminal.

Problem occurs with or without ssh or SonicWall VPN, so seems to only involve BTT and Terminal.

Problem does not occur when BTT is not running. Problem not noticed with other applications.

Problem started sometime in Dec 2016. Ran without BTT for several days with no problem. Updated BTT with no improvement. Problem existed in previous version of BTT.

Am currently testing with BTT running and disabled for Terminal.

**What kind of Mac are you using?**

MacBookPro6,2

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Trackpad is affected.

**Which versions of macOS and BetterTouchTool are you running?**

OSX: 10.11.6
BTT: 1.963 (552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Nothing found in syslog. No application crash reports generated. CPU usage normal. When problem is active, Terminal is not selectable with cmd-tab window switching, but is selectable with Exposé.

[com.hegenberg.BetterTouchTool.plist.txt](https://github.com/fifafu/BetterTouchTool/files/705033/com.hegenberg.BetterTouchTool.plist.txt)

**Comment by fifafu** [comment]
Hey,

could you attach an export of your setup or mail it to me (boastr.net@gmail.com). To export use the export preset button in the BetterTouchTool prefs. Usually BTT doesn't do something like this on its own :-)

Best,
Andreas

**Comment by fifafu** [comment]
Thanks for sending!
That's a really weird issue as there is really nothing in the export that could cause this (especially because you have disabled BTT for Terminal, thus it can't really send any events or the like).

Are you still able to operate your computer when this happens? If so, could you try to use Activity Monitor to sample the BetterTouchTool process? (and maybe also the Terminal process). This can be done by clicking View => Sample Process in Activity Monitor.

**Comment by gespdove** [comment]
Andreas,

Yes, the computer is responsive otherwise. I'll take samples of BTT and Terminal, but I might not get to it until Monday.

Cheers,
Peter

On Jan 13, 2017, at 13:27, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for sending!
That's a really weird issue as there is really nothing in the export that could cause this (especially because you have disabled BTT for Terminal, thus it can't really send any events or the like).

Are you still able to operate your computer when this happens? If so, could you try to use Activity Monitor to sample the BetterTouchTool process? (and maybe also the Terminal process). This can be done by clicking View => Sample Process in Activity Monitor.

-
