### ISSUE TITLE
BTT licence is not working anymore after mac upgrade to macOS High Sierra 10.13.4 on a MBP 2017

### ISSUE THREAD

**Issue by identidadgh** [fifafu/BetterTouchTool#2500]
Description of bug/feature request/question:
After upgrading to macOS High Sierra 10.13.4 the BTT says trials ended -134 days ago and NO swipe gestures work. BTT also says: "no multitouch capable trackpad found!"

I already tried to reinstall the licence file I bought in November 2017 (5 months ago), restart everything and it still does not work. Please help.

Device information:
Type of Mac: MacBook Pro 2017
macOS version: 10.13.4
BetterTouchTool version: 2.443

Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<img width="617" alt="screen shot 2018-04-19 at 10 44 59 pm" src="https://user-images.githubusercontent.com/1074783/39017506-c2feaa92-4423-11e8-8dd9-8077d671c666.png">

**Comment by fifafu** [comment]
Hi Fabio

could you check this version, the 443 build had a few issues. https://bettertouchtool.net/releases/btt2.444b.zip

Note: BetterTouchTool licenses receive free updates for two years. Afterwards the last version you received in that timeframe can still be used forever. Possibly your license is older than two years (however BTT should show a message to you about it).

If 2.444 doesn't work, try this: https://bettertouchtool.net/releases/btt2.426_recovery.zip

Best,
Andreas
