### ISSUE TITLE
Constantly asking for system permissions

### ISSUE THREAD

**Issue by raguay** [fifafu/BetterTouchTool#2503]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
BetterTouchTool Permissions dialog is constantly coming up. When I go to system preferences, BetterTouch Tool already has permissions enabled, but the program doesn't think it does.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

None.

#### Device information:

Type of Mac: MacBook Air 13"
macOS version: 10.13.4
BetterTouchTool version: 2.437

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I've restarted the system several times and it is still very persistent. But, I haven't noticed any usability issues. Just the annoying dialogue showing up over and over.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a bug in recent macOS versions.

Usually deleting the app, downloading a fresh copy and un/re-checking the permissions fixes it. (I think macOS then refreshes the database)

**Comment by raguay** [comment]
Okay, the second time I erased it using Clean My Mac, rebooted, and
re-installed. Now it hasn't bugged me all day. Hopefully it will stay that
way. Just deleting the app and re-installing did not get it at first. Must
have been something that Clean My Mac found and removed that allowed it to
reset properly.

Funny thing, one other app will now register properly also. It's like a log
jam!

Thanks.

Richard

On Fri, Apr 20, 2018 at 2:10 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Yeah, Apple knows about the issue but it doesn't seem to be very high priority ;-(
