### ISSUE TITLE
about Japanase keyboard

### ISSUE THREAD

**Issue by soarclovia** [fifafu/BetterTouchTool#252]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
As the keyboard shortcut detection function, the key '英數' ＆ 'kana' of JP keyboard can't be detected correctly. I hope you can resolve this.

**What kind of Mac are you using?** macbook pro 2016 with touchbar and JP keyboard

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
keyboard

**Which versions of macOS and BetterTouchTool are you running?**
sierra

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Man thanks.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
