### ISSUE TITLE
TouchBar customization no longer works after upgrade/license installation

### ISSUE THREAD

**Issue by nathasm** [fifafu/BetterTouchTool#2523]
#### Description of bug/feature request/question:
Upgraded to the newest version of BTT after purchasing a lifetime license. TouchBar customization no longer works.

Also, switching profiles (to try and resolve the issue) basically nuked my default/master profile. (Can you also let me know where it is stored so I can grab it from my backup?)

Restarted laptop && BTT and the problem persists.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
TouchBar

#### Device information:

Type of Mac: MacBookPro (latest)
macOS version: High Sierra
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Let me know what you need

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you go to the about tab in BTT and click the "export debug information" button?
This will create a folder called BetterTouchToolDebug. If you send that to me (andreas@folivora.ai) I can probably tell what's wrong.

**Comment by nathasm** [comment]
Well, that did it! Thanks!!
