### ISSUE TITLE
Messages contact touch bar feature request

### ISSUE THREAD

**Issue by tnaz** [fifafu/BetterTouchTool#253]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Not sure this is already a feature or if this is possible, but is there a way to have favorite contacts touch icons set up in the messages app? e.g. a few favorites names/icons easily accessible to pull up conversations directly by touching a favorite contact name

**What kind of Mac are you using?**
MBP touch bar 2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

touch bar
**Which versions of macOS and BetterTouchTool are you running?**

10.12.2
**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Good idea, I think you can do this using the predefined action "Open URL/Open URL With Selection".

iMessage specifies a custom URL scheme that let's you jump to a specific contact. So when using the predefined action enter something like this as URL:
imessage:thehonenumber, or imessage:boastr.net@gmail.com

I think adding a predefined action that makes this easier would be a good idea though.
