### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Hankao** [fifafu/BetterTouchTool#254]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

I constantly receive a message said "There was an unexpected error." And it just stops working. I've tried reboost both my mac and BTT but it didn't work. 

**What kind of Mac are you using?**
Macbook Pro 2016 13" with touch bar
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
All of them

**Which versions of macOS and BetterTouchTool are you running?**
MacOS 10.12.2
BTT 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
None
Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
That error indicates that your BetterTouchTool app bundle somehow got corrupted. Please download a fresh copy from my website.
