### ISSUE TITLE
Folders of buttons on TouchBar [feature request]

### ISSUE THREAD

**Issue by jerryevo** [fifafu/BetterTouchTool#255]
It will be great if BTT will allow to create folder of buttons on Touch Bar. This will allow to have more than one level of buttons so will greatly increase productivity.

**Comment by fifafu** [comment]
The most current versions already have support for groups (v1.987).
They'll be improved with future updates, but are already working fine.

**Comment by jerryevo** [comment]
Great, that this feature is added.
My first impression is that it is hard to rearrange buttons and move them to groups. Simple button drop on group name during dragging should move it into group.

**Comment by fifafu** [comment]
It does, however the group needs to contain at least one item before dragging others into it.

**Comment by jerryevo** [comment]
Yep, this limitation should’t exist. Simple drag should work, even if group is empty.

**Comment by fifafu** [comment]
Unfortunately that's currently not possible and would require some deeper changes to the table logic. Maybe I'll change it one day, but for now we'll have to live with that limitation.
