### ISSUE TITLE
Touchbar widget: App switcher

### ISSUE THREAD

**Issue by dj-hedgehog** [fifafu/BetterTouchTool#256]
![touchswitcher jpg 1280x720 2017-01-15 11-54-54](https://cloud.githubusercontent.com/assets/7140800/21962007/71bfdf44-db19-11e6-818b-665081645bd4.png)

The app TouchSwitcher lets you switch between apps https://hazeover.com/touchswitcher.html 
A widget that can be displayed all the time with the same functionality in BetterTouchTool would be awesome. I'd like to be able to choose the number of apps to display inside the widget myself and be able to swipe through the app list inside the widget (if that is even possible).

**Comment by fifafu** [comment]
Added something similar in v1.988 alpha.

**Comment by dj-hedgehog** [comment]
Oh that is EXACTLY what I was looking for. Could you make the space between the items configurable though?
