### ISSUE TITLE
Button group close icon

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#257]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Small issue for sure, but for consistency could you make the "x" close icon for a button group identical to the one that Apple uses for it's button groups (like in the Mail app when you tap the Move to arrow)?  It appears as an X in a light gray circle on black background.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.987

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by CappyD** [comment]
... or maybe it would be best to just automatically create a close button within the button group when the group is created.  Then you could configure it as desired (like label it Done with blue background and place it on the right side) like any other button.

**Comment by fifafu** [comment]
I like that idea, will do!

**Comment by fifafu** [comment]
Done in v1.988 alpha

**Comment by CappyD** [comment]
Looks good… Thanks Andreas.

On Jan 15, 2017, at 6:16 PM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Done in v1.988 alpha
