### ISSUE TITLE
Access to menus for icons on menu bar 

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#258]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
This doesn't seem to be possible now... for apps that place an icon on the menu bar, there needs to be a way to access their menus.  I tried using the Trigger menu-bar item action with values in parentheses large enough to count past the current app's Help menu to get to those icons, but that didn't work (and wouldn't be a good solution since a particular icon would not always have the same number depending on the active app).  

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.987

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Unfortunately I don't think that's possible as there is no standard naming scheme to address such items, also the  menus are not really standardized (look at Dropbox).

However you should be able to use macOS Automator to create a new workflow using the recording feature. You can then trigger that Automator workflow using BTT.
