### ISSUE TITLE
Single finger swipe left right (Back/Forward) not working in Safari

### ISSUE THREAD

**Issue by philwhiles** [fifafu/BetterTouchTool#260]
BTT 1.963(552) seems to interfere with back and forwards/single finger swipe left/right in Safari

Mid 2014 15" MBP

Magic Mouse 1 - the one with the batteries

Sierra 10.12.2

**Comment by philwhiles** [comment]
It works intermittently it seems - when not working safari seems to attempt the page navigation, with the current page moving a fraction, but seemingly stuck.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
