### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by lipeijia** [fifafu/BetterTouchTool#262]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
When I update the last version of BetterTouchTool, it occur unexpected error immediately, and no matter how I restart the app, no gesture that I added can work anymore :(

**What kind of Mac are you using?**
MacOS Sierra

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**
1.988

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

<img width="1005" alt="2017-01-16 12 46 52" src="https://cloud.githubusercontent.com/assets/16973150/21971461/c243f68a-dbeb-11e6-9cc1-a52f33f9e043.png">

**Comment by fifafu** [comment]
Sorry! Fixed with 1.989

Best,
Andreas
