### ISSUE TITLE
Unexpected error.

### ISSUE THREAD

**Issue by KelvinJin** [fifafu/BetterTouchTool#264]
#### Unexpected error dialogs keep showing up.

**What kind of Mac are you using?**
Macbook Pro early 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Macbook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.1 MacOS and 1.988(581) for BTT.

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
<img width="422" alt="screen shot 2017-01-16 at 9 15 58 pm" src="https://cloud.githubusercontent.com/assets/2549987/21979095/9019ef70-dc31-11e6-9bc5-02a774d0328b.png">

After closing the dialog, BTT stop working (not crashing).

The following are the exceptions indicated by the logs in Console app.
<img width="1276" alt="screen shot 2017-01-16 at 9 26 34 pm" src="https://cloud.githubusercontent.com/assets/2549987/21979342/9f8224fe-dc32-11e6-9b71-20599d7c23ca.png">

**Comment by fifafu** [comment]
Fixed in 1.989!
