### ISSUE TITLE
[Question] Swapping Command-Tab and Control-Tab

### ISSUE THREAD

**Issue by DennisSchiefer** [fifafu/BetterTouchTool#265]
I am running macOS Sierra 10.12 and BTT 1.985.

I am trying to swap Command-Tab and Control-Tab, but this does not seem to work.

Remapping Command-Tab to Control-Tab does nothing: Pressing Command-Tab still starts swapping applications.
Remapping Control-Tab to Command-Tab does something: Presssing Control-Tab switches focus but does not start swapping applications.

Am I doing something wrong or is Command-Tab functionality anchored to deep in the system so that BTT cannot change its behavior?

**Comment by fifafu** [comment]
Yes, unfortunately BTT can't change that combo as this would require much deeper system integration. 
For things like that Karabiner has always been great, but I'm not sure if it works on Sierra.

**Comment by DennisSchiefer** [comment]
Thanks for the information.
Unfortunately it is not fully functional yet for Sierra.
