### ISSUE TITLE
3-finger-tap delayed 2-3 seconds in browsers

### ISSUE THREAD

**Issue by monstermac77** [fifafu/BetterTouchTool#266]
#### Description of your bug/question/feature request...:
I want to be able to open links in a new tab by doing a 3-finger-tap while hovering over the link. I've set 3-finger-tap to be "command+click" in Global, and yet in all browsers (Chrome, Safari, and Firefox) when I 3-finger-tap over a link there is a 2 second delay before the new tab is opened. Stranger still, 3-finger-click produces no delay. 

If I move my cursor off of the link/to a new link before the end of the 2 second delay, no new tab is opened/the new link is opened, which should indicate where in the sequence of triggers the delay is occurring. 

I first tried setting this up a couple of years ago, which is when I first encountered this delay, so I believe this is a longstanding problem.

**What kind of Mac are you using?**
2012 Macbook Pro, 15"

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Built-in Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
Running macOS Sierra (10.12.2) and BetterTouchTool 1.963 (522).

**Comment by fifafu** [comment]
Do you also use a three finger double tap somewhere? (Because in that case BTT needs to wait in order to make sure you aren't about to do a three finger double-tap)

**Comment by monstermac77** [comment]
Ah! Yes, I was (I use 3-finger double tap to reopen the previously closed tab). Removing that gets rid of the delay. Thank you!
