### ISSUE TITLE
 1.988 (531) update causes unexpected error

### ISSUE THREAD

**Issue by D-elias** [fifafu/BetterTouchTool#267]
Ever since I updated to the newest version, I keep getting this error message about an unexpected error has occured. This happened after I restarted my Macbook pro on El Capitan. The drag window feature still works but none of the trackpad gestures work until BTT is restarted. This behavior seems completely random.
![window 2017-01-16 at 16 26 43](https://cloud.githubusercontent.com/assets/3038757/21999546/a8b52c12-dc08-11e6-9ef6-c9d976f85cad.png)

**Comment by fifafu** [comment]
Hey,

Sorry that was a bug in the 1.988 alpha, it's fixed in 1.989.
