### ISSUE TITLE
Sometimes BTT won't launch app with assigned keyboard shortcut

### ISSUE THREAD

**Issue by negativeions** [fifafu/BetterTouchTool#269]
I can't seem to replicate this but once in a blue moon, especially if I'm using spaces a lot, BTT won't launch the app I assigned to a keyboard shortcut in the "other" section. Maybe it's something with the specific keys (command-escape), but I was in iTunes once in another space and I pressed the keys and nothing happened. When I went back to the desktop space, clicked on the BTT icon in the menubar a couple of times then it worked. Weird. Sierra 10.12.2. BTT 1.985. Thanks.

**Comment by fifafu** [comment]
Do you still experience this issue with current versions of BTT? As I haven't had similar reports I'm closing here for now, but if you stil encounter this, please reopen/comment.
