### ISSUE TITLE
Show Control Strip inside BTT TouchBar

### ISSUE THREAD

**Issue by frogworth** [fifafu/BetterTouchTool#271]
Like many people, I keep missing the Esc key and hitting the (x) that closes the BTT TouchBar instead.
I know you can disable the Control Strip and then you don't have the close button, but I don't want to lose the MacOS Control Strip either.

So the perfect solution would be to put the Control Strip _inside_ the BTT TouchBar!
I can only imagine this is impossible, but I thought I'd suggest it anyway...

**Comment by rogersmj** [comment]
+1 !!! I've spent about 2 hours fiddling with BTT's settings, and I can't really get it the way I want it. If this were possible I would love it.

**Comment by frogworth** [comment]
OK, to be honest with the new additions of brightness & volume slider widgets, I can pretty much replicate what I need while disabling the Control Strip altogether.
It'd be lovely if the volume & brightness sliders were icons that expanded like in the Control Strip, but I'll take what I can get :)
Thanks @fifafu!
