### ISSUE TITLE
Disable cmd-q closing the actual app

### ISSUE THREAD

**Issue by frogworth** [fifafu/BetterTouchTool#272]
Whenever I've got the BetterTouchTool Preferences window showing, I can't help closing it with cmd-q, which closes the actual app and not just the preferences.
Yeah, I'm stupid.

But I'd really appreciate being able to alias cmd-q to cmd-w, and only close BetterTouchTool itself through the menu bar icon.

**Comment by pallavmac** [comment]
You could make a BTT command so that: When in the app BTT, pressing cmd-q triggers cmd-w

**Comment by frogworth** [comment]
I tried that :) But it didn't work.
I also tried seeing the shortcut for the "Quit" menu item to something different in Mac OS Preferences, but it also doesn't work. Something to do with the way the BTT Preferences window works - it's also invisible to the app switcher.

**Comment by fifafu** [comment]
I'm sorry unfortunately BTT can't be used to remap shortcuts for BTT (because BTT receives the events before remapping).

However as it is the macOS standard behavior to quit an app when cmd+q is hit, I probably won't change this :-(
