### ISSUE TITLE
[request] Start Screen Saver Option

### ISSUE THREAD

**Issue by ZV95** [fifafu/BetterTouchTool#273]
Good morning!

I am requesting the addition of a predefined action: "Start Screensaver". Lock screen exists automatically with TouchBar equipped Macs which is also the only predefined action available. It would be nice to have the option to lock and start the screen saver. 

Thanks so much!

**Comment by fifafu** [comment]
Hi!

Good idea.
For now you can already do it using the "Open Application ... " predefined action. The Screensaver App is hidden at this location: /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app

**Comment by ZV95** [comment]
Awesome! Thanks!

**Comment by fifafu** [comment]
I have added a predefined action to do it with alpha 2.15 (available later today)
