### ISSUE TITLE
3 finger tap/click not recognized on certain areas of the trackpad

### ISSUE THREAD

**Issue by tgarrett09** [fifafu/BetterTouchTool#276]
15'' MacBook Pro with touchbar (latest model)
BTT V1.989

For some reason BTT isn't recognizing the three finger tap or three finger click gestures from the middle area of the large trackpad. I've verified with another tool that those taps/clicks do register, but for some reason BTT isn't picking it up. It makes those gestures very unreliable since they only seem to work from certain parts of the touchpad.

**Comment by fifafu** [comment]
Do you still encounter this?
I'm closing here for now as I haven't had other similar reports, but will reopen if this is still an issue.
