### ISSUE TITLE
3 finger swipe down to minimize window bug

### ISSUE THREAD

**Issue by iEdwinTorres** [fifafu/BetterTouchTool#277]
#### Description of your bug/question/feature request...:
3 finger swipe down to minimize window does not work while cursor is in a "blank" area in iTunes.

**What kind of Mac are you using?**
early 2013 15" rMBP

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
built-in trackpad

**Which versions of macOS and BetterTouchTool are you running?**
latest as of 1/17/17

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
