### ISSUE TITLE
Doubletap to drag not working

### ISSUE THREAD

**Issue by myoon01** [fifafu/BetterTouchTool#278]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
"Enable doubletap to drag" doesn't work. I have tried it with the previous version of BTT but it didn't work either.

**What kind of Mac are you using?**
MacBook Pro Mid 2015 15-inch
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 / 1.989

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

in order for that to work you also need to add the gesture "single finger tap" (or "single finger tap left" ) and assign the left-click predefined action to it.

Best,
Andreas
