### ISSUE TITLE
Add feature to customize touch bar when "expanded control strip" option is selected 

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#28]
when using the "Touch bar shows: expanded control strip" option, so you dont have to tap the arrow to expand, you cant specify custom objects to be placed in the touchbar (as far as i can see) is this feature planned or possible?
<img width="780" alt="screenshot_2016-12-06 14 07 20" src="https://cloud.githubusercontent.com/assets/8683379/20939660/a2b050be-bbbd-11e6-8791-67decf9b2825.png">

**Comment by fifafu** [comment]
Unfortunately, as far as I know, this is not possible 😌.

**Comment by moshed** [comment]
hmm well i see you implemented getting rid of the control strip completely and replacing it with your own buttons so maybe we can just make a template that mimics the default expanded control strip and have that be the default that users can customize from btt

**Comment by fifafu** [comment]
Yes, one of the next versions will add the possibility to add a "BTT Control Strip"!

**Comment by moshed** [comment]
awesome!
