### ISSUE TITLE
Global to specific touchbar not switching

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#280]
#### Description of your bug/question/feature request...:
I set up a global touchbar. Then when I go to an app with specific actions set up, despite my settings saying "hide global actions when specific actions set up", switching to the app with specific actions, still shows the global touchbar. Only when I show default touchbar then back again to the BTT one, does the specific action touchbar show up. 

**What kind of Mac are you using?**
15" With Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
Latest MacOS and BTT Version 1.989

**Comment by pallavmac** [comment]
Oh! The app switcher is being layered above the specific touchbar actions. Look in this screenshot of the touchbar, you can see small grey things above the applications. Those are the specific actions I have set up
<img width="270" alt="touch bar shot 2017-01-18 at 8 32 49 pm" src="https://cloud.githubusercontent.com/assets/9432573/22064233/9930f6a2-ddbd-11e6-8a16-169994f0f619.png">

**Comment by pallavmac** [comment]
You many need to zoom in closer to the image to see the top of the grey boxes

**Comment by fifafu** [comment]
Ah, thanks for reporting! Could you send me an export of your gestures and maybe a screenshot of the general touch bar settings? (makes it easier for me to reproduce and fix)

**Comment by pallavmac** [comment]
Export of settings:
[BTT Settings.zip](https://github.com/fifafu/BetterTouchTool/files/715436/BTT.Settings.zip)

**Comment by pallavmac** [comment]
General TouchBar Settings:
![screen shot 2017-01-19 at 8 50 57 am](https://cloud.githubusercontent.com/assets/9432573/22089206/8c75924e-de24-11e6-8452-bb0501536d93.png)

**Comment by pallavmac** [comment]
App Switcher Widget Settings:
![screen shot 2017-01-19 at 8 51 03 am](https://cloud.githubusercontent.com/assets/9432573/22089214/993a2256-de24-11e6-9675-861d3cd63ee7.png)

**Comment by fifafu** [comment]
Thank you! Should be fixed with v1.991!
