### ISSUE TITLE
Cannot highlight text (easily)

### ISSUE THREAD

**Issue by WillBishop** [fifafu/BetterTouchTool#282]
**What kind of Mac are you using?**
Macbook Pro late 2013 (15")

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Macbook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
BTT 1.989, macOS 10.12.2

Now onto the issue:

When I have BTT open, highlighting text in any application becomes much more difficult, the usual click and drag rarely works.

If I click anywhere other than the text itself and begin to move by cursor, it will not highlight the text, but as soon as BTT is closed, it works perfectly.

**Comment by pallavmac** [comment]
Try enabling palm and thumb handling
<img width="1127" alt="screen shot 2017-01-18 at 9 36 09 pm" src="https://cloud.githubusercontent.com/assets/9432573/22066072/27626b1a-ddc6-11e6-8835-4af7b33e04ac.png">
