### ISSUE TITLE
Suddenly BetterTouchTool Stop to work

### ISSUE THREAD

**Issue by galklieger** [fifafu/BetterTouchTool#284]
Hey,
I am using this in order to copy\paste and more tasks like this like open a new tab, copy custom text and more... everyday it worked, suddenly i have open the app today and nothing is working. i have tried to restart and quit and open, and still does not work

**Comment by galklieger** [comment]
I am also using TipTap right and left to move between tabs, and it worked till yesterday but now when i do tiptap instead of moving one tab its moving 2-3 tabs

**Comment by fifafu** [comment]
Have you tried to restart your system? There hasn't been a change yesterday.

**Comment by galklieger** [comment]
I just deleted and did it again, and everything works beside the moving tabs with tiptapright
Its moving 3-5 ta s instead of only one... 
I ve tried to upload a short video of that but i can't upload it to here...
it alwasy worked, just now it doesn suddenly

**Comment by galklieger** [comment]
http://sendvid.com/4ryxtsb7

**Comment by galklieger** [comment]
Look at the tabs, everytime it moves I click just ones...

**Comment by galklieger** [comment]
Maybe its something with the new update ?

**Comment by galklieger** [comment]
it just do not work properly the tiptap right and left, it was always good and now sometimes it goes one sometimes it go 3 tabs

**Comment by fifafu** [comment]
Which version of BTT do you have installed?
Have you tried a system restart?

**Comment by galklieger** [comment]
1.989 (582)
Yes, I did restart for everything.
Now it worked for 3 minutes and returned to happen the same, when i make tiptapright or left it runs 3-5 tabs

**Comment by galklieger** [comment]
Actually almost everything it do twice/ several time... open link in new tabs and things like that

**Comment by galklieger** [comment]
I have also tried to do it in Safari, and its making me the same error... instead of moving 1 tab is moving 2-5 tabs at once

**Comment by galklieger** [comment]
I have uninstalled and download it again, and same issue

**Comment by galklieger** [comment]
Also now for example i want to paste custom text with 3 fingers tiptap middle, it paste twice the same text, thanks!

**Comment by fifafu** [comment]
Do you maybe  have multiple user accounts on your Mac running BetterTouchTool?

**Comment by galklieger** [comment]
mmm I do not think so... this is a new Mac

**Comment by galklieger** [comment]
How can I check that ?

**Comment by fifafu** [comment]
If it's a new mac that's probably not the issue.

Unfortunately I currently don't have any idea what could be causing the issue for you (it's working fine here). Maybe you could try to reset your BTT settings using this terminal command (while BTT is closed).

defaults delete com.hegenberg.BetterTouchTool

Also.maybe attach an export of your BetterTouchTool setup ( using the export buttonon the left side  in the BetterTouchTool preferences)

**Comment by galklieger** [comment]
It does not let to attached it here 
https://drive.google.com/open?id=0B2TKVtOaJCtUdExVNVE5NU5kZGs

**Comment by vartiainen** [comment]
Just wanted to chime in to say I love Better Touch Tool.
But some of the four finger gestures stopped working today.
Tried: update, restart, reboot.

**Comment by ricardoaugusto** [comment]
I was having a similar issue this week, custom buttons disappeared on a recently formatted MacBook Pro.

The command `defaults delete com.hegenberg.BetterTouchTool ` worked for me as well. https://github.com/folivoraAI/BetterTouchTool/issues/284#issuecomment-273904649

**Comment by galklieger** [comment]
Hey, by any chance can you get to me the files that I have in the other
mac? In the other computer? with the same configurations? Thanks!
