### ISSUE TITLE
switching to an application that has app-specific touchbar buttons resets the whole touchbar 

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#285]
when i switch to an application that has app-specific touchbar buttons the whole touchbar goes blank inldung my global actions. i have noticed that when i have some buttons set to show only if a modifier key is pressed pressing that key gets everything to show as normal though.

macOS 10.12.2 (16C67)
MacBook Pro (Retina, 13-inch, Mid 2014)
BTT 1.989

**Comment by fifafu** [comment]
Mhh I currently can't reproduce that, could you attach an export of your setup (and if possible also a screenshot of you general Touch Bar settings in BTT).

This will help me reproduce/fix the issue.

**Comment by moshed** [comment]
[BTT.zip](https://github.com/fifafu/BetterTouchTool/files/715657/BTT.zip)
![2017 01 18-22 46 31](https://cloud.githubusercontent.com/assets/8683379/22093001/02da1a72-ddd0-11e6-8c25-33ded3de8f9e.png)
it seems to throw everything into a bit of a mess. the control strip sometimes shows as well as other apps replacing my custom touchbar even though those options are not checked in the settings

**Comment by fifafu** [comment]
Wait, Retina, 13-inch, Mid 2014? So you don't have a Touch Bar? Or was this a typo?

**Comment by moshed** [comment]
no no touch bar im using an app to mimic the touchbar. touche https://red-sweater.com/touche/

**Comment by fifafu** [comment]
Ah, that's interesting. I'll check if I can reproduce it using that app. (It seems to work fine on the real Touchbar)

**Comment by fifafu** [comment]
mhm I can indeed reproduce something similar when running Touché, however I'm not yet sure if this is fixable (on either my side or Touché's side).

**Comment by moshed** [comment]
hmmm yeah i should have included that thats what i was using. ok if i cn do anything to help let em know
