### ISSUE TITLE
Why no duplicate action for BTT shortcuts

### ISSUE THREAD

**Issue by chrisduong** [fifafu/BetterTouchTool#287]
Hi,

When I need to add a similar shortcut, I cannot find the "duplicate action" for it. This can save a lot of time.

**Comment by chrisduong** [comment]
By the way, I think it is time to add a good Menu Bar (click action) to quickly Duplicate, Modify a shortcut.

**Comment by fifafu** [comment]
You can use cmd+c and cmd+v to copy & paste a gesture.

**Comment by chrisduong** [comment]
Hi,

I tried but it didn't work.

I'm using version 1.989, MacOS 10.12.2.
