### ISSUE TITLE
Feature Request: Show TouchBar when no App Actions

### ISSUE THREAD

**Issue by Moballo** [fifafu/BetterTouchTool#288]
#### Description of your bug/question/feature request...:
Feature Request: I think it would be awesome if there was an option to show the BetterTouchTool TouchBar when there were no actions defined by an application (like a fallback TouchBar)

I also think it would be awesome if there was a button we could add to our TouchBar (like in the Keyboard->Customize TouchBar settings panel) to show the BetterTouchTool TouchBar without replacing the now-playing indicator and instead putting the button in place of some other control like brightness.

**Comment by fifafu** [comment]
Unfortunately both is not possible due to API limitations. If I ever find solutions to do this I'll add it, however currently this is not doable for me.
