### ISSUE TITLE
Feature Request: Close TouchBar on Click

### ISSUE THREAD

**Issue by Jason-Morcos** [fifafu/BetterTouchTool#289]
#### Description of your bug/question/feature request...:
It would be nice to have an option to automatically dismiss the BetterTouchTool TouchBar after an option on the TouchBar was selected (automatically trigger the left side cancel after a button is tapped)!

**Comment by fifafu** [comment]
You can do this by using the "add additional action" option like this:

![image](https://cloud.githubusercontent.com/assets/8820811/22119960/d3de6184-de7d-11e6-88bd-014ebf6ab6fe.png)

**Comment by Moballo** [comment]
What about when selecting an app in the app switcher widget?

**Comment by fifafu** [comment]
Good point, I'll make it possible to attach an action to that widget. 

Maybe I can also make it a global setting.
