### ISSUE TITLE
Feature Request: Show BetterTouchTool TouchBar while key pressed

### ISSUE THREAD

**Issue by Moballo** [fifafu/BetterTouchTool#290]
#### Description of your bug/question/feature request...:
macOS allows a user to specify a modification to make to the touchBar while holding down the function key. Would it be possible to make it so that the BetterTouchTool touchBar would be displayed while some other modifier key was held down and would automatically close when the key was released? I'm thinking while holding control or fn-control for instance. This would make it really easy to access actions on the BetterTouchTool touchBar and minimize time toggling showing and hiding the bar. Love the BetterTouchTool touchBar so far by the way! Great work!

**Comment by fifafu** [comment]
You can assign modifier keys to Touch Bar buttons to achieve this:

![image](https://cloud.githubusercontent.com/assets/8820811/22123039/6f8bae0a-de8a-11e6-891a-20aecb4cbbd0.png)
