### ISSUE TITLE
Click is not registered at same pressure as forcetouch feedback

### ISSUE THREAD

**Issue by oliverpolden** [fifafu/BetterTouchTool#292]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Sometimes the force touch pad generates a click but the actual click is not registered by the OS. It seems the click is registered by the OS at a slightly stronger pressure than the trackpad itself. I do have the click force set to lightest but I think this still happens at other settings.

**What kind of Mac are you using?**

MacBook Pro late 2016 with Touchbar. Also experienced with an early 2016 MacBook.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Pro TrackPad

**Which versions of macOS and BetterTouchTool are you running?**

Sierra 10.12.2 but also other versions. BT 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
