### ISSUE TITLE
Feature request: Allow shortcut actions to be repeated

### ISSUE THREAD

**Issue by harrygallagher4** [fifafu/BetterTouchTool#294]
#### Allow shortcut actions to be repeated:

Hi there, I think it would be pretty useful to allow an action to be repeated at the regular key-repeat rate. For instance, I have ^J bound as an alias for the down arrow so I'd like to just be able to hold J down and keep sending the down arrow.

Thanks!

**Comment by fifafu** [comment]
You can do this by clicking the little gear icon on the left side of the shortcut field, then setting it up like in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/22175549/0a638a34-dff7-11e6-99ed-54ebfbdccdca.png)
