### ISSUE TITLE
BTT doesn't "wake up"

### ISSUE THREAD

**Issue by simonbaev** [fifafu/BetterTouchTool#295]
#### Description of your bug/question/feature request...:
Most of the time BTT works well, but when the lid is closed for a while (I experienced it several times when I didn't use my MacBook for at least 12 hours) BTT doesn't seem to "wake up". It still responses to menubar operations, I can go to Preferences and disable or restart it, but all TrackPad gestures no longer work. 

In Preferences, when I use "Show live view", it doesn't recognize any gestures. 

**What kind of Mac are you using?**
MacbookPro Late 2016 13" with TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
1.989 (582)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
I found a workaround to this: I remove one of the TrackPad actions (in my case 3 fingers down swipe) and re-create it from scratch. It recovers recognition of all TrackPad gestures.

**Comment by fifafu** [comment]
Do you still encounter this?
I'm closing here for now as I haven't had other similar reports, but will reopen if this is still an issue.

**Comment by simonbaev** [comment]
It no longer bothers me. Thank you.

--
Simon
