### ISSUE TITLE
Remote does not connect

### ISSUE THREAD

**Issue by kbecker87** [fifafu/BetterTouchTool#296]
#### Description of your bug/question/feature request...:

I’ve been using BTT and BTT Remote for a long time, but did not use BTT remote for the last year or so. Now if I want to connect it says I need to update BTT on my Mac (see Screenshot), sometimes it doesn’t even find the Mac, sometimes it works (but does not reconnect in those cases).

I’ve checked my Firewall and HandsOff! Configuration, everything is allowed for BTT.

**What kind of Mac are you using?**

* MacBook Pro Retina late 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

* BTT Remote (iOS, iPhone 6 & iPad Air 2)

**Which versions of macOS and BetterTouchTool are you running?**

* macOS 10.11.6, BTT 1.991

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

![](https://cldup.com/uu2haN1nToG/ETfEtb.jpeg)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
That's weird, it seems to work fine here. Does this happen on your iPhone and iPad?

Could you check what this Terminal command returns on your Mac?
```defaults read com.hegenberg.BetterTouchTool version```

**Comment by kbecker87** [comment]
That outputs `1.991`

All devices are on the same WiFi Network (5Ghz, FritzBox). Should I try with a direct Wifi Network?

On the iPad I never got the "Update required" error but cant connect most of the time as well.

**Comment by fifafu** [comment]
Do you maybe have a Firewall enabled on your Mac?

**Comment by kbecker87** [comment]
Yes, the built in one and HandsOff! - disabled both to test BTT Remote Connection, made no difference.
