### ISSUE TITLE
Feature Request: Preview of Desktops

### ISSUE THREAD

**Issue by deakins** [fifafu/BetterTouchTool#297]
First of all, love this app. Really unlocks the touch bar!

I currently switch between my various Desktops by mapping the system hotkeys (CMD+1, CMD+2, etc.) to a global group. In practice however, I quickly lose track of which desktops my various apps are on. Would it be possible to use a preview of the Desktops (as shown at the top Desktop bar when activating Mission Control, and similar to the Safari tab preview) as the button icons? 

**What kind of Mac are you using?**
Macbook Pro (15-inch, 2016)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2, 1.991

**Comment by fifafu** [comment]
Sorry, unfortunately that would need to be implemented by Apple as I can't get a picture of those desktops (at least not without major performance drawbacks)
