### ISSUE TITLE
Send Shortcut to Specific app issue.

### ISSUE THREAD

**Issue by inugi15** [fifafu/BetterTouchTool#299]
#### Description of your bug/question/feature request...:
I'm used to some key to "Send Shortcut to Specific app" of predefined action trigger. 
And I also use the option 'Switch back immeadiately after sending the shortcut',
But it sends shortcut current activated windows about 50%. 
Could you fix this on next build?
Thank you.

**What kind of Mac are you using?**
2013late 15" MBPR

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
all.

**Which versions of macOS and BetterTouchTool are you running?**
osx 10.11 El Capitan.  BTT 1.963

**Comment by fifafu** [comment]
Hi,

thanks for reporting, could you check if this is fixed with the new alpha version? (1.992)

**Comment by inugi15** [comment]
Thank you for unbelievable response! It works like a charm.

**Comment by fifafu** [comment]
Cool, let me know in case the issue reappears!
