### ISSUE TITLE
With BetterTouchTool active and open, going to another desktop space then going back, it immediately hides the BetterTouchTool app

### ISSUE THREAD

**Issue by nikitavoloboev** [fifafu/BetterTouchTool#30]
#### Description of your bug/question/feature request...:
I tried to be descriptive in my title. I can replicate it 100 % of times and I think it is a bug as no other app does this and it is very annoying when you map something, want to test it and this happens.

**Comment by ZV95** [comment]
I am unable to replicate this issue. Upon moving from both spaces with full-screen apps and apps that are not full-screen, I do not have the BTT Settings on the Touch Bar go away. In fact, they correctly update if I move between apps with separate TouchBar settings (i.e. Safari I have different buttons than those in "Finder"). 

MacBook Pro (15-inch, Late 2016)
2.6 GHz i7 // 256GB // 16GB // Raedon Pro 450 2GB // Intel HD 530 1536MB

**Comment by fifafu** [comment]
@ZV95 he's talking about the BetterTouchTool preferences window :-) (and he is right).

I currently don't know what's causing this but it is a bug!

**Comment by ZV95** [comment]
OH! I see now, yeah, that does happen for me. Ignore that previous post!

**Comment by moshed** [comment]
i get this too but to add in case it helps you  narrow it down this also happens after leaving mission control without switching spaces

**Comment by fifafu** [comment]
Fixed in latest alphas.
