### ISSUE TITLE
Trigger Menubar Menu command does not work with menu's with "..."s in them

### ISSUE THREAD

**Issue by DTowersM** [fifafu/BetterTouchTool#300]
Version 1.989 (582). 

Using TouchBar on 13 inch 2016 MacBook Pro running Mac OS Sierra Version 10.12.2. 

The Trigger Menubar Menu-item Command does not work with menu items that include a ... in them. Such as "Layer;New Fill Layer;Solid Color..." or "Filter,Filter Gallery..."

Thank you for your time

**Comment by fifafu** [comment]
Thanks for reporting! Will be fixed with the next update later today.

(Previously they were using the combined … symbol, now they are actually using three dots, not sure if this was a change in macOS or Adobe software)

**Comment by DTowersM** [comment]
Thank you <3
