### ISSUE TITLE
2 Finger Click Gesture makes regular "right click" fail

### ISSUE THREAD

**Issue by sethblumberg** [fifafu/BetterTouchTool#301]
#### Description of your bug/question/feature request...:

Doing a regular 2 Finger Click is supposed to bring up a context menu like right-clicking (because I have checked off "Secondary Click" in System Preferences > Trackpad).  But when I create a gesture for Google Chrome triggered by *cmd + 2 Finger Click*, then the regular 2 Finger Click no longer works in Chrome.  I have tested it and removing this one gesture from my list makes right-clicking work again.

What I expected was that, so long as the gesture I make requires a modifier key, the regular functionality would still work correctly.

**What kind of Mac are you using?**

2016 MacBook Pro 13" with Touch Bar.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Pro Trackpad (with force touch)

**Which versions of macOS and BetterTouchTool are you running?**

macOS Sierra 10.12.2
BTT 1.991 (583)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

**Comment by fifafu** [comment]
Unfortunately if you want to use a two finger click in BTT you'll have to disable it in the System Preferences. (You can however re-configure a right-click in BTT).

I agree it would be nice if it'd continue to work when modifier keys are added, however it's not possible due to API limitations.

**Comment by sethblumberg** [comment]
Ah, I understand now.  I thought the red warning only applied to "2 Finger Click, Right Finger Harder" instead of to all of the 2 Finger Gestures, because the warning is only under that one.  I think it would be clearer that applies to all 2 finger gestures if the warning was at the top of those gestures (but still after the divider line).
