### ISSUE TITLE
4 finger force click feedback

### ISSUE THREAD

**Issue by SchwiftyLife** [fifafu/BetterTouchTool#302]
the 4 finger force clicks feedback is messed up , although i did set it to silent force click in the settings its feedback is clicky and its not a single click its a burst feedback . changing feedback type doesnt have any effect. and it does not happen with the three finger force click and its fine.

mac version : MJLQ2

input device : MacBook Trackad

 macOS 10.12.3 Beta (16D30a) , BTT 1.992

**Comment by fifafu** [comment]
Do you maybe have an additional feedback set in the gestures advanced config? 
![image](https://cloud.githubusercontent.com/assets/8820811/22184482/9a3c7824-e0d2-11e6-96e9-daf928b84645.png)

**Comment by SchwiftyLife** [comment]
ok yes i had an additional deefback but when i set it to no feedback the feedback is silent but it isnt a clean silent force click, its like a vibrating force click or a triple silent force click. but the three finger force click is fine.

**Comment by SchwiftyLife** [comment]
i found out something else :
the problem is when i set the action for 4finger force touch to run the ⌘+Q shortcut , otherwise its a single silent force feedback

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
