### ISSUE TITLE
Right Option Key to Forward Delete issues. 

### ISSUE THREAD

**Issue by theg1nger** [fifafu/BetterTouchTool#303]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

I'm trying to remap the right option key to forward delete. When I try to type it in the "Shortcut" box it will show the option key icon in grey while its pressed but when I lift it up it disappears. The only way I seem to be able to remap the right option key BY ITSELF to forward delete is to record the sequence. Even when checking the "allow repeat without key up" it does not repeat the key. So basically I can't hold down the right option key and forward delete continuously. 

Am I missing something?

**What kind of Mac are you using?**
Mid-2012 MBP 13" Unibody
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Macbook built-in keyboard

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.989 (582)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry, BTT is really not suited for such key-remapping tasks. You should look into a tool called Karabiner Elements, I think it will do exactly what you need!
