### ISSUE TITLE
Feature Request - Icon for the Slider Bar

### ISSUE THREAD

**Issue by edgardluz** [fifafu/BetterTouchTool#305]
First BetterTouchTool is the main reason why I'm still using a Mac! Love everything about it. I also love the new slider widget! Thanks for all the great work! 

Down to business, it'd be cool when we replaced the slider widget icon (functionality which is in place already on the left side of widget selection) it would replace the actual white touch square of the slider. That way we don't need to show the left/right icons and the middle button could be replaced with a volume/brightness/whatever icon used. It'd take less space, be super intuitive and give us better control of what our bar looks like.

What do you guys think?

**Comment by fifafu** [comment]
Hi!
I wanted to do it like this, but unfortunately the slider provided by Apple doesn't support setting an image on the white knob. Maybe I'll create my own slider implementation eventually, so I'll leave this open for now.

**Comment by edgardluz** [comment]
Fun.. can we at least customize the knob color/size? just curious.

If you're building your own, it'd be good to have the touch/hold/slide that is default for the Control Strip.

**Comment by fifafu** [comment]
I'll check if I can somehow hack it, by default it doesn't offer any customization options besides the track color :-)

**Comment by childrenof9** [comment]
yess would be great a special slider implementation :)

**Comment by fifafu** [comment]
This is now possible
