### ISSUE TITLE
Feature Request: Add (non-active) labels to touch bar

### ISSUE THREAD

**Issue by tillnagel** [fifafu/BetterTouchTool#307]
Would be great if BTT allows adding labels to the touch bar, with slightly different style and no action. At the moment, adding a new "TouchBar Button" with only text and no action still renders as button.

See this example from the Finder touch bar (the "Sort By").
<img width="1085" alt="touchbar-with-labels" src="https://cloud.githubusercontent.com/assets/908847/22213483/b57e3a6a-e194-11e6-9395-2487906c9e6d.png">

MacOS Sierra 10.12.2 with latest BTT 1.992 (584)

**Comment by fifafu** [comment]
Hi Till,

for now you could change the background color of the button to black, but you are correct - it's still slightly different than the labels.

Best,
Andreas
