### ISSUE TITLE
Displaying Spotify Track Name

### ISSUE THREAD

**Issue by mark248am** [fifafu/BetterTouchTool#308]
Hey, so I'm trying to get the track name to display in the TouchBar but instead of it appearing in the touch bar i am getting it as a system notification. Whats the right way to do it?

I went to TouchBar in BetterTouchTool. 
I clicked on +Widget
I chose Run script/command
I copy pasted the "Another Simple Example" code from https://developer.spotify.com/applescript-api/
I clicked save.

Now I get a button that just says "Apple Script" and the track names are showing up system notifications every 5 seconds.

thanks!

<img width="1440" alt="screen shot 2017-01-23 at 10 41 32 pm" src="https://cloud.githubusercontent.com/assets/25271366/22219771/2f042b60-e1bd-11e6-8864-7ff36be63f36.png">

**Comment by fifafu** [comment]
Hi,

use this script:
```
tell application "Spotify"
	return name of current track
end tell
```

**Comment by mark248am** [comment]
oh wow that was super quick and it worked!!
How can I show artist as well?

**Comment by fifafu** [comment]
```
tell application "Spotify"
	set currentArtist to artist of current track as string
	set currentTrack to name of current track as string
	
	return currentArtist & " - " & currentTrack
end tell
```

**Comment by mark248am** [comment]
Damn thats perfect! Can't believe you got this feature done. Thanks!!

**Comment by mark248am** [comment]
Would it be technically possible to add a forward button in the Touch Bar as well?

**Comment by fifafu** [comment]
Forward is currently not possible I think, however skipping to the next song should already work using the predefined "next" action

**Comment by mark248am** [comment]
I meant skipping to the next song, I was looking for the predefined "forward" or "skip" option didn't think of "next".

Also there is a minor but at the moment with track display. If the track name is too long it doesn't scroll. It also messes up the buttons, for example in the attached photo you can see my "Full Screen" button is now under the "Esc" button. This only happens after the script reloads. So it displays correctly when the new track starts, but on refresh it messes up.

![overlap](https://cloud.githubusercontent.com/assets/25271366/22220672/aab4b376-e1c0-11e6-9dbb-a0951ccd07f9.jpg)

**Comment by fifafu** [comment]
Could you attach an export of your setup? (Makes it easier for me to reproduce the exact issue)

**Comment by mark248am** [comment]
Here you go


[chrome.zip](https://github.com/fifafu/BetterTouchTool/files/724834/chrome.zip)

**Comment by mark248am** [comment]
I changed the item placement for the 3 buttons on the left from "Scrollable Main Container" to "stick to left" and now instead of my button falling under "esc" its over "esc". Track still doesn't scroll.

**Comment by fifafu** [comment]
http://boastr.net/releases/btt1.993.zip could you check if this version fixes the layout issue?

**Comment by mark248am** [comment]
Ok Yes and No. The below tests was done with a long track name.

So if I have the item placement for track name to the left. It works. It no longer pushes the buttons to over lap or fall under the "Esc" button. 

If I have the item placement for track name to "scrollable" it works like having it to the left. No scrolling, but also doesn't move any buttons under or over "esc".

On the other hand 

If I have the item placement for track name to the right then the track name overlaps the buttons to its left. check below. Not a big deal honestly since it works fine when aligned left.

![10002](https://cloud.githubusercontent.com/assets/25271366/22221890/d039ef1c-e1c5-11e6-97c8-ba53deb9b3fb.jpg)
![1000](https://cloud.githubusercontent.com/assets/25271366/22221889/d0393af4-e1c5-11e6-9831-78892b61e129.jpg)

**Comment by pallavmac** [comment]
Is it possible to add an if statement in apple script? So IF Spotify is open, show track. ELSE, leave blank

**Comment by pallavmac** [comment]
Right now, every time I quit spotify, it reopens :(

**Comment by pallavmac** [comment]
Also a max size for it too. Because some songs take up the whole touchbar length

**Comment by fifafu** [comment]
@pallavmac 

something like this will check if Spotify is running and also only display max 20 characters:
```
if application "Spotify" is running then
	tell application "Spotify"
		set currentArtist to artist of current track as string
		set currentTrack to name of current track as string
		
		set completeString to currentArtist & " - " & currentTrack
		set numberOfCharacters to length of completeString
		if numberOfCharacters > 20 then
			return text 1 thru 20 of completeString
		else
			return completeString
		end if
	end tell
	
else
	return ""
end if


```

**Comment by lucameier** [comment]
My Script checks if Spotify is running and if so, shows the track name, artist name and album name.

I configured the widget, that it change its color to red, if the result matches "Spotify not running". Also i configured a predifined action to open Spotify with a click on the widget.

Here is my Code:


```AppleScript
tell application "System Events"
	set num to count (every process whose name is "Spotify")
end tell

if num > 0 then
	tell application "Spotify"
		set playState to (player state as text)
		if playState is equal to "playing" then
			set trackName to name of current track
			set artistName to artist of current track
			set albumName to album of current track
			set trackInfo to trackName & " | " & artistName & " | " & albumName
		else
			set trackInfo to "Nothing playing"
		end if
		return trackInfo
	end tell
else
	set trackInfo to "Spotify not running"
	return trackInfo
end if
```
credits to [CaptainAverage](https://obsproject.com/forum/threads/how-to-display-current-song-is-x-on-mac.23444/#post-128864) on obsproject.com

**Comment by mark248am** [comment]
How did you make it appear in red? can you export and share your setup?

**Comment by Pogopooc** [comment]
Hmm, nice! What's about a Album Cover? 😊

**Comment by lucameier** [comment]
@mark248am 
>How did you make it appear in red?

when the widget is selected, click on **Advanced Configuration**. Then you can define an alternative color and put the text in the textfield on the right.

<img width="825" alt="bildschirmfoto 2017-01-26 um 18 59 31" src="https://cloud.githubusercontent.com/assets/1733147/22343894/249ffd5e-e3fa-11e6-8fff-845ef4cb930b.png">

> can you export and share your setup?

of course 😄  have fun: [btt settings2.zip](https://github.com/fifafu/BetterTouchTool/files/733131/btt.settings2.zip)

**Comment by mark248am** [comment]
ah, i thought you could change the actual color of the font to red not the box. got confused.

**Comment by bhagya7893** [comment]
Is it possible that the widget disappears when Spotify isn't playing?

**Comment by Touchy28** [comment]
Is this possible for iTunes too?

**Comment by theikid** [comment]
Hey guys, this is fantastic work! Is it possible to show the cover art for the song playing in itunes ? Thanks !

**Comment by bnsena** [comment]
Hey, all of this is wonderful! Is it possible to only show this information, say, when a new track plays. Then after like 10 seconds or so it disappears. 
Like it takes over the touch bar while showing the song information and then once a specific time has passed it will go away and show what was there originally?

**Comment by Tompz** [comment]
Hi all,

Just a quick ask - as I've just used the following with great results:

Is there any way to have the Artist and Track name as scrolling text please?  

I really like the idea of being able to limit the size of touchbar info by number of characters displayed, but would love to have the info scrolling.

Code I used on BTT:

tell application "System Events"
	set num to count (every process whose name is "iTunes")
end tell
set maxSize to 20

if num > 0 then
	tell application "iTunes"
		set playState to (player state as text)
		if playState is equal to "playing" then
			set trackName to name of current track
			set artistName to artist of current track
			set albumName to album of current track
			if length of trackName is greater than maxSize then
				set trackName to text 1 thru (maxSize - 3) of trackName & "..."
			end if
			if length of artistName is greater than maxSize then
				set artistName to text 1 thru (maxSize - 3) of artistName & "..."
			end if
			set trackInfo to trackName & " | " & artistName
		else
			set trackInfo to ""
		end if
		return trackInfo
	end tell
else
	set trackInfo to "iTunes close"
	return trackInfo
end if



Thanks,

Dave

**Comment by fifafu** [comment]
Scrolling text is currently not possible, but I'm looking for solutions to this.

**Comment by samuelthng** [comment]
Hi people.

Just in case anyone wanted to have an AppleScript Predefined Action for the Spotify Widget.

If Spotify isn't running when you tap on the widget, it will open the application.
If Spotify is already running, it will toggle play/pause then update the track info.
Credits to the guys who posted before. This is really just a Frankenstein of their work.

```
tell application "System Events"
	set num to count (every process whose name is "Spotify")
end tell

if num is 0 then
	tell application "Spotify"
		activate
	end tell
	set trackInfo to "Spotify"
else if num > 0 then
	tell application "Spotify"
		playpause
	end tell
	delay 0.25
	tell application "Spotify"
		set playState to (player state as text)
		if playState is equal to "playing" then
			set trackName to name of current track
			set artistName to artist of current track
			set albumName to album of current track
			set trackInfo to trackName & " | " & artistName & " | " & albumName
			set numberOfCharacters to length of trackInfo
			if numberOfCharacters > 20 then
				set trackInfo to (text 1 thru 17 of trackInfo) & "..."
			end if
		else
			set trackInfo to "Nothing playing"
		end if
	end tell
end if
return trackInfo
```

Enjoy!

**Comment by stass69** [comment]
Hi everyone!

just want on long press to make previous track and make spotify icon active like press on it it will open spotify. so how is it realize?

**Comment by stass69** [comment]
can i changed color of font though?

**Comment by tmaier-nordisk** [comment]
Can the text (Artist - Track) be running through when it is too long for the area it can be displayed?

**Comment by Tompz** [comment]
Never said thanks for this - Thank you!

**Comment by dicetomato** [comment]
This for some reason stopped working for me. It now just doesn’t update when the song changes, even though my settings are correct. Anyone else having issues with the latest version of BetterTouchTool?

**Comment by BirkhoffLee** [comment]
@tmaier-nordisk @fifafu @Tompz Scrolling is possible, all credits to https://imgur.com/gallery/cHwJ5. Use the following code snippet:

```
set stringToScroll to trackInfo # the text you want to scroll
set speed to 2 # letters per second
set maxLength to 20 # max letters

if length of stringToScroll < maxLength then
	return stringToScroll
end if

set stringToScroll to stringToScroll & " - " # append scroll separator
set len to ((length of stringToScroll) - 1)
use framework "Foundation"
set t to (current application's NSDate's timeIntervalSinceReferenceDate) as real
set p to (t * speed) mod len

return (text (p + 1) thru (p + 1 + maxLength - 1) of (stringToScroll & stringToScroll & stringToScroll)) #& "..." # the & "..." at the end of this is optional
```
