### ISSUE TITLE
Regular crashes in 1.991; cannot create Force Touch rules

### ISSUE THREAD

**Issue by johndavi** [fifafu/BetterTouchTool#309]
[crash.txt](https://github.com/fifafu/BetterTouchTool/files/724965/crash.txt)

**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

I am consistently unable to create gestures using Force touch and even simpler ones (2-finger-click, 3-finger-click) fail to work consistently. They trigger correctly in the live view but do not in the "real world," i.e. in the actual app.

Most of the time creating new rules results in crash. See attached log.

**What kind of Mac are you using?**

Macbook Pro early 2015

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Macbook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**

Sierra 10.12.3 Beta + 1.991

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

See attached stacktrace.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
That's a very weird crash, could you check whether changing the force feedback in the advanced settings fixes it? (see attached screenshot)

![image](https://cloud.githubusercontent.com/assets/8820811/22223084/d0b5dfd4-e1b9-11e6-956a-4c70f3bf0af6.png)

**Comment by johndavi** [comment]
Sure thing, will do and report back. I should note that I got that crash without any Force Touch rules. (My entire current list is in the attached PDF.)

[rules.pdf](https://github.com/fifafu/BetterTouchTool/files/724985/rules.pdf)

**Comment by johndavi** [comment]
Got a crash even with the updated haptic feedback settings.

[crash2.txt](https://github.com/fifafu/BetterTouchTool/files/724999/crash2.txt)

**Comment by johndavi** [comment]
I don't know if this is related but the simple rule I'm trying to make is "two fingers + thumb click" = "right click." For the life of me I cannot do it. I have Trackpad two-finger click disabled in my System Prefs, and I have tried all configuration of thumb-handling, and all variants of:

two-finger click == right click (both with/without "Map 3-finger clicks that include thumb...")
three-finger click == right click (both with/without "Map 3-finger clicks that include thumb...")

...and none will work. It's typically in my frustrating tests of these that I get a crash. Are all of the sub-checkboxes in the Thumb/Palm Handling preference working?

**Comment by fifafu** [comment]
The thumb handling settings filter thumbs that have been resting on the trackpad for a while, BTT currently assumes that if you lift your thumb before clicking, you actually want to do a three finger click.

Does it work if you configure both and also enable the Map 3-finger click....?
Also make sure to disable two finger right-click in the system preferences => trackpad

![image](https://cloud.githubusercontent.com/assets/8820811/22224241/4af487ba-e1be-11e6-8c5b-df8905036cb1.png)

**Comment by johndavi** [comment]
It does not work even with both rules in place, "Secondary click" disabled in Trackpad, and any of the thumb-mapping configs. In fact: I got another crash just trying to test this!
[crash3.txt](https://github.com/fifafu/BetterTouchTool/files/725053/crash3.txt)

**Comment by fifafu** [comment]
Mhm I'm currently out of ideas as it seems to work fine here, but I'll try it on another machine tomorrow!

**Comment by johndavi** [comment]
Thanks for the responsiveness. No idea what's going on. With your two-rule approach the live view almost never registers the gesture; moreover the trackpad will frequently refuse to even register a click (i.e., it is frozen) with the two-finger-plus-thumb click attempt.

**Comment by johndavi** [comment]
Even with a full settings restart I cannot get 2- or 3-finger click to trigger right-click.

**Comment by fifafu** [comment]
Also not when doing it without the thumb?

**Comment by johndavi** [comment]
> Also not when doing it without the thumb?

Sorry, whenever the thumb is involved. 3-finger-click using forefinger+middle+ring does work.

**Comment by johndavi** [comment]
I've had a few days sans crashes (though I haven't tried to modify any rules), but just now started to add a Force-Click rule -- and am unable to. The rule is there, but any FORCE click action does not trigger a response outside of BTT. (In BTT the FORCE click will register; outside of the app it will not -- I can push as hard as possible without feedback or triggering.)

This may be overloading this issue, I realize, given the focus that the crash took at first.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
