### ISSUE TITLE
create "folders" on touchbar

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#31]
i think implementing a "folder" like feature on the touch bar open up a world of possibilities. for instance a spotify button could expand (much the way pressing volume or brightness from the non-expanded control strip expands to a slider) to a like and dislike song button (impelmennted through applescript or however the user likes)

**Comment by fifafu** [comment]
Yes, this will be one of the next features coming as soon as everything else works smoothly!

**Comment by fifafu** [comment]
Basic implementation has been added for nextbversion (release tomorrow). More options like sliders etc. Will be added soon.

**Comment by ThePantsThief** [comment]
Can this issue be closed then?

**Comment by fifafu** [comment]
@ThePantsThief for now yes, I'm tracking various improvements in other issues :-)
