### ISSUE TITLE
Volume widget doesn't respect modifier keys

### ISSUE THREAD

**Issue by rogersmj** [fifafu/BetterTouchTool#311]
#### Description of your bug/question/feature request...:
The new touch bar volume widget ignores the selection of modifier keys in its advanced configuration panel. When I try to select "Control" and hit "Save", upon opening the control panel again the "Control" checkbox is not selected, and the volume control widget remains on the primary touch bar without pressing a modifier key.

**What kind of Mac are you using?**
15" MacBook Pro Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.2, BTT 1.993 (586)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks a lot for reporting! Should be fixed in 1.994 alpha :-)
