### ISSUE TITLE
Need indicator of right or left in BTT prefs interface

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#313]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
In the BTT prefs window when displaying touch bar gestures, it would help to have some indicator of whether a button is assigned to left or right side... such as a column showing R or L, or display the right-side buttons in a section at top, the buttons in main container in the middle, and left-side buttons in a section at the bottom.  

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.993

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Good idea! For now I have added the indicator to the name column. Will be available with next alpha later.

![image](https://cloud.githubusercontent.com/assets/8820811/22264078/0eef42e6-e277-11e6-91f0-f4baf6488d91.png)
