### ISSUE TITLE
Record shortcut support for silent keys like ^ and ¨

### ISSUE THREAD

**Issue by zwacky** [fifafu/BetterTouchTool#316]
#### Description of your bug/question:

I'm using a Swiss German layout and there are silent keys that need to be pressed twice for it to appear. E.g. with `^` I could press it once and then press `a` which would make it a `â`.

In the **Click to record shortcut** it doesn't recognize any of these silent keys. I worked around it with the key sequence, but it has in some special cases problems (*).

(*): I use it as the closing bracket `]` with `option + ¨`. If I want to write `[]` at once while pressing `option` for the first bracket `[`, it obviously doesn't print the closing bracket `]`, because the sequence needs key down of `option` for it to work.

**What kind of Mac are you using?**

macOS Sierra 10.12.3
MacBook Pro (Retina, 15-inch, Mid 2014)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Keyboard

**Which versions of macOS and BetterTouchTool are you running?**

1.994

**Comment by ayalon** [comment]
I have the same issue. I already wrote an email to the author of the tool with a detailed report but I never got an answer. Can this be fixed?

**Comment by fifafu** [comment]
Hi,

Sorry, but those keys are not supported by the default macOS keyboard shortcut mechanism. (E.g. They won't work in system preferences -> keyboard -> shortcuts either)

Currently this can't be fixed, maybe if I ever change to a custom shortcut interception system, but that's currently still in "idea" state and I'm not sure if I'll ever  be able to integrate it.

**Comment by ndrizza** [comment]
Hi @ayalon and @zwacky . Did you find any workaround (e.g., other software) for this?

**Comment by ayalon** [comment]
Jup! I found one. I completely got away from Better TouchTool. It's not true, that this is a limitation. Other tools can handle this special keys. I guess it's just not implemented.

I'm using now khd
https://github.com/koekeishiya/khd

It's great and easy to use if you already have brew installed. Here is my config file:

~/.khdrc
```
# mapping
# https://cloud.githubusercontent.com/assets/6175959/18551554/35137fc6-7b59-11e6-81a0-bef19ed5db5e.png

# Alt 2 = @
ralt - 2: khd -p "ralt - g"

# {} remapping
ralt - 0x27: khd -p "ralt - 8"
ralt - 0x2A: khd -p "ralt - 9"

# [] remapping
ralt - 0x21: khd -p "ralt - 5"
ralt - 0x1E: khd -p "ralt - 6"

#  remapping
ralt - 0x18: khd -p "ralt - n"
```

**Comment by fifafu** [comment]
@ayalon, as I wrote this is not supported by the macOS default shortcut handling. Khd uses an alternative API I mentioned above, however that has other limitations.

But khd is probably a good solution for your use case, an even better one might be this tool: http://www.hammerspoon.org/
