### ISSUE TITLE
Feature request: Touchbar App Switcher Widget badges

### ISSUE THREAD

**Issue by gasranas** [fifafu/BetterTouchTool#317]
Hi,

Would it possible to include the badge icons (eg unread count in mail) as an option in App Switcher Widget for the touchbar?

This would possibly make the touchbar an alternative to the dock in some cases, such as when running fullscreen apps. I find myself wanting to know if I have any unread mail, and would be great to see without switching the dock back on, or switching to the mail app.

Thanks in advance for considering it!

**Comment by fifafu** [comment]
Hi!

This is already tracked here: #283

**Comment by gasranas** [comment]
Thanks for looking into it, and sorry for not noticing the duplication.
