### ISSUE TITLE
Feature Request: Additional Icons

### ISSUE THREAD

**Issue by chrispolus** [fifafu/BetterTouchTool#318]
Since BTT allows to have specific window positions (left third, left half) it would be nice to have those icons for window positions also in the icon list so I can have the corresponding icon in the Touch Bar. I've scrolled through all 3 icon groups but haven't found anything that would fit.

**Comment by fifafu** [comment]
Hi Chris,

you can drag any icon you find on the web into BTT!
I currently don't plan to add more predefined icons, but I think it's easy to find almost anything by using google picture search.

**Comment by finnef** [comment]
A related question: How can I re-use or export an icon? I made one and assigned it, but now I want to drag it to the desktop or copy and paste it to another action or a graphics program...

**Comment by fifafu** [comment]
@finnef that's currently not possible. You'll need to drag in the original file again.

**Comment by finnef** [comment]
I know it isn't possible :-)
Should I open a separate feature request?
(It is possible to decode the icon info from the preset json export, but not easily)

**Comment by fifafu** [comment]
I think there is already an issue for that (I'm currently on my iPhone, need to look it up later, I'll link it here then.)

**Comment by mkhalife** [comment]
Just an FYI if you're looking for good icons, I've been using [Google's Material Icons](https://material.io/icons/)...they have a lot of nice ones and they're free. Check this out: https://github.com/fifafu/BetterTouchTool/issues/1433
