### ISSUE TITLE
No action keyboard gesture doesn't undo action of global gesture

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#319]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Suppose you define a global keyboard gesture that does some action (such as making \ do forward delete).  For a particular app, if you don't want the key to do that action, I would think that you would create an app-specific gesture for the the key and leave it assigned to No Action.  When I try this, I find that the global action still happens in the app where it should now do no action. 

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.995

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

please use the "Use Apple default or do nothing" action instead :-)
The "no action" action makes it behave like nothing is configured for that app.

**Comment by CappyD** [comment]
Thanks Andreas.  I didn't think of that.
