### ISSUE TITLE
Mac Preview App - Window Resize glitch

### ISSUE THREAD

**Issue by sjamesparsonsjr** [fifafu/BetterTouchTool#320]
In Mac os x app, 'Preview' when reading PDF and using keyboard (option + ->) [Maximize window right], or (option + <-) [Maximize window left], or (option + Up arrow) [Maximzie Window] using BBT, the window moves a little and stops, works with all over apps correctly just not with 'Preview'.

Macbook Pro macOS 10.12.3, BTT 1.963

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
