### ISSUE TITLE
Control strip screenshot menu disappears

### ISSUE THREAD

**Issue by arielge** [fifafu/BetterTouchTool#321]
#### Description of your bug/question/feature request...:
In Apple's expanded control strip there is an option for a screenshot button, which opens a menu to set the screenshot settings. When the BTT touch bar is open, this menu opens _behind_ the BTT touch bar. That is, I expand the control strip, tap the screenshot button, and instead of seeing the screenshot menu I see the BTT touch bar. Only after toggling off the BTT touch bar the menu appears.

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2, BTT 1.995

**Comment by fifafu** [comment]
Thanks for reporting! Unfortunately this can't be changed due to API limitations :-(
