### ISSUE TITLE
Feature Request: Default app / control strip functions

### ISSUE THREAD

**Issue by pauloruberto** [fifafu/BetterTouchTool#322]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
It would be great if we could somehow mix and match BTT toucher actions with the built in buttons for that app. For example if I wanted to keep the address bar from the default safari touch bar, but add some of my own buttons. Or if I remove the control strip, but still have the volume / brightness icons that I can simply slide my finger on to adjust.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3 & 1.995

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Unfortunately this is not possible due to API limitations.
