### ISSUE TITLE
Feature Request: Change icon / text on press

### ISSUE THREAD

**Issue by pauloruberto** [fifafu/BetterTouchTool#325]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
It would be cool if we could have icons that change when pressed, for example how the play/pause button works. Not sure if possible, but would be great if it is.  

**What kind of Mac are you using?**
2016 13" MacBook Pro 

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
TouchBar

**Which versions of macOS and BetterTouchTool are you running?**

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by kbaley** [comment]
Other examples: Mute/Unmute and toggling notifications on and off. My current workaround is to keep the native control strip for now with just the Play, Mute, and Notifications buttons on it. But I look forward to the day when I can remove it completely.

**Comment by pauloruberto** [comment]
Solved in https://github.com/fifafu/BetterTouchTool/issues/838#issuecomment-299023824.
