### ISSUE TITLE
Unmoveable screenshot window when opened with Edit in Better Touch Tool

### ISSUE THREAD

**Issue by gdufford** [fifafu/BetterTouchTool#326]
When using an app in full screen (Chrome in my case) and saving a screenshot with a keyboard command and the Edit in BTT setting the resulting window cannot be moved. Taking the app out of full screen allows the screenshot window to be moved and manipulated. If the Edit Screenshot button is clicked the edit window is not visible and 

It seems to be the full-screen app needs to be the leftmost one in the Mission Control view.

Macbook Pro - 8GB - 10.12.2
BTT 1.963
Saving of screenshot with keyboard (shift-option-command-4)
Tried attaching .spx file but GitHub didn't like it. If you'd like it emailed let me know.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

**Comment by gdufford** [comment]
Thanks, and amazing tool btw. Quick question, didn't I see something about
you are eventually going to add drag lock? Now I'm doing that with
accessibility settings, would prefer BTT.

Thanks!

On Thu, Apr 5, 2018 at 11:15 AM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
What exactly do you mean by drag lock? (In general if the system already offers such an option - definitely use that, I usually don't duplicate system functionality in BTT unless there are valid reasons)

**Comment by gdufford** [comment]
I have my Mac currently setup to do a mouse drag with three fingers by
setting System Preferences -> Accessibility -> Trackpad Options -> Enable
Dragging -w- Drag Lock. Anything I'd normally use my thumb to hold down the
click on the trackpad is now done with a three finger move. I love it.

That's a good point about not duplicating functionality, just thought I'd
read somewhere that you had planned to hook into that with BTT. It's a
little challenging to setup at first.

On Thu, Apr 5, 2018 at 11:47 AM, Andreas Hegenberg <notifications@github.com

**Comment by gdufford** [comment]
Oops, I'm a little off, the setting I use is:  System Preferences ->
Accessibility -> Trackpad Options -> Enable Dragging -w- Three Finger Drag

**Comment by fifafu** [comment]
Ah now I understand!
Currently there is no plan to reimplement that in BTT as I got most of the conflicts with the system three finger drag resolved (I once discussed it because the three finger drag broke many things in BTT).
So currently please continue with your current setup :-)
