### ISSUE TITLE
Show finder feature broken

### ISSUE THREAD

**Issue by jere343** [fifafu/BetterTouchTool#327]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...: The shortcut to find finder with a mouse click does not work properly

**What kind of Mac are you using?** macbook pro 13 retina

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?** trackpad

**Which versions of macOS and BetterTouchTool are you running?** seira, 1.994

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

I'm not sure what you mean exactly. Do you have a screenshot?

**Comment by jere343** [comment]
I can't really screenshot it, the show finder feature just won't work about
half the time

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group/>*

Best regards,
Jeremy Konrad Young
B.Sc., M.D.
https://ca.linkedin.com/in/jeremykyoung
T: 318-606-8255 (USA); 416-835-6446 (CAN)

On Fri, Feb 10, 2017 at 4:59 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
