### ISSUE TITLE
Touch Bar Bug: brightness slider widget mimics volume slider widget at first

### ISSUE THREAD

**Issue by ThePantsThief** [fifafu/BetterTouchTool#329]
I have both slider widgets on my global section, and I have the control strip hidden. When toggling the BTT menu from the app controls, the brightness slider has the same value as the volume slider at first, then quickly jumps back to the value it's actually set to.

Version `1.995`

**Comment by fifafu** [comment]
Should be fixed with the next update (1.998)

**Comment by ThePantsThief** [comment]
Sweet
