### ISSUE TITLE
timer to close BTT Touch bar

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#332]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
: Feature request: auto close BTT Touch bar after 2-3s(timer setting), so it will automatically return to the app's touch bar after using BTT Touch bar

**What kind of Mac are you using?**
: 15" MacBook Pro late 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
: Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
: BTT v1.995, macOS 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by anas2204** [comment]
Hey, I post the same request:
https://github.com/fifafu/BetterTouchTool/issues/314

**Comment by fifafu** [comment]
Tracking this in #314
