### ISSUE TITLE
3 Finger Swipe difference

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#333]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
: Question/fix - all my 3f swipe gesture works fine except now I have to swipe it longer to activate, is there anyway swipe length setting, so I can set it to trigger in shorter swipe

**What kind of Mac are you using?**
: 15" MacBook Pro late 2016(shorter swipe works fine before with 13" MacBook Pro 2013)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
: Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
: 15" MacBook Pro late 2016

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
I have added sliders to adjust the swipes in the advanced trackpad settings!

**Comment by justinpma** [comment]
Hi,

I'm aware of the slider for the 2f swipe but didn't see any slider for 3f swipe. 

Thank you 

Justin. P

**Comment by justinpma** [comment]
There's slider for 2f swipe but didn't see any slider for 3f swipe
