### ISSUE TITLE
Adding "2 finger force click" gesture breaks normal 2 finder right click

### ISSUE THREAD

**Issue by seweil** [fifafu/BetterTouchTool#334]
I added a trackpad gesture "2 finger force click" mapped to "Maximize window"

When I did this, normal two finger tap for right-click stopped working.

Repros on MBP touchpad and external Magic trackpad

BTT version 1.963
OS X 10.11.6

Deleting the gesture restores normal 2 finger tap behavior

**Comment by fifafu** [comment]
Hi,

yes that is expected. You should disable right-clicks in system preferences => trackpad if you want to use any sort of two finger click in BTT. (You can then reconfigure it in BTT).

The reason is that otherwise every 2 finger force click would also produce a right-click.

Best,
Andreas

**Comment by seweil** [comment]
Thanks!
