### ISSUE TITLE
restart and shutdown action

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#335]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
feature request : please add the action for restart and shut down.

**What kind of Mac are you using?**
: 15" MacBook Pro late 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
: want to use it on touch bar

**Which versions of macOS and BetterTouchTool are you running?**
: BTT 1.955, macOS 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi,

you can use the "Trigger Menubar Menu Item" action to trigger the shutdown or restart commands.
Alternatively here someone posted many useful terminal commands that can be triggered by BTT: http://apple.stackexchange.com/a/103633

**Comment by justinpma** [comment]
Hi, 

I tried sudo shutdown -r now on terminal itself, it works fine.
But when I pasted it on the BTT ‘execute terminal command’ and put it on touch bar. 
It didn’t work.


Regards,
Justin Poh
Brunei +673 882 0066
Singapore +65 9156 0820
Email: Justinpma@me.com

**Comment by cleverjackal** [comment]
@justinpma Maybe you shouldn't post your phone number/email here

**Comment by cleverjackal** [comment]
@justinpma try the menu bar action instead, then

**Comment by justinpma** [comment]
I think it's a direct reply from my email. 

Already remove it. 
thank you

**Comment by cleverjackal** [comment]
@justinpma No problem, glad you fixed it! If you still need help with your issue, then try the menu bar action in BTT instead :)

**Comment by finnef** [comment]
Another alternative is to execute an applescript:

```
tell application "Finder"
	activate
	display dialog "Are you sure you want to shut down your computer?" buttons {"Cancel", "Restart", "Shut Down"} default button "Shut Down" with icon caution
	
	if button returned of result is "Shut Down" then
		shut down
	else if button returned of result is "Restart" then
		restart
	end if
	
end tell
```
this emulates the dialog that you get when pressing control-eject (on keyboards with eject key)
