### ISSUE TITLE
BUG: Touch bar Apple script widget resizing ALL Buttons 

### ISSUE THREAD

**Issue by aaronweewee** [fifafu/BetterTouchTool#336]
Hi :)

Everytime the apple script widget changes size. all other buttons are affected
This occurs when the next song on Spotify starts playing, the number of text would differ and cause the widget size to change. When it changes size, all the icons on the touch bar will be resized and continue to resize with each track.

It only affects buttons that has the _inner padding value changed_. I've exported my touch bar below, to quickly experience the issue turn on chrome and start skipping tracks on Spotify.
[BTT 3.4.zip](https://github.com/fifafu/BetterTouchTool/files/734293/BTT.3.4.zip)

**What kind of Mac are you using?**
Macbook touch bar 13"
MacOS 10.12.2

**Comment by fifafu** [comment]
Thanks for reporting, will be fixed with the next update! (1.996)
