### ISSUE TITLE
Script widget: add option for button to appear/disappear

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#337]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
The new script widget is very cool and powerful!  One thing that would make it even better would be an option that allows the button to appear only at completion of execution of the script. Otherwise, the button would not appear and would not take up any space.  This would be rather than have the button always displayed.  The button would be dismissed when you tap it.  Or, I suppose you could do essentially the behavior Apple has when a pop up window appears - you get a new touch bar with the buttons for that window. But I kinda prefer the idea of it appearing in the current TB and moving buttons out of the way as needed.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.995

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

If you return an empty string the button should be hidden.
