### ISSUE TITLE
Broken Blog Button

### ISSUE THREAD

**Issue by alex-taffe** [fifafu/BetterTouchTool#338]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
When hovering over the "User Feedback/Website" button and then clicking "Visit My Blog" redirects you to https://blog.boastr.net. That link is broken and just appears to be a login page. Should redirect to https://www.boastr.net/blog/.

**What kind of Mac are you using?**
2010 13" MacBook Pro
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
N/A

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3/1.963(552)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks for reporting! (I switched to a new server yesterday and need to fix some subdomains.)
