### ISSUE TITLE
Touch bar bug: cannot open Force Quit window

### ISSUE THREAD

**Issue by zhaidoudou123** [fifafu/BetterTouchTool#339]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I added a touchbar button whose assigned action is command+option+escape, which was aimed to open Force Quit window. 
But when I press this button, nothing happened.
I also added a button with action: command+option+shift+escape to force quit the current program and this one works very well.

**What kind of Mac are you using?**
2016 MBP 13.3

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3&1.994(587)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by zhaidoudou123** [comment]
By the way, is there any way to prevent BetterTouchTool's bar from displaying after waking up?

**Comment by fifafu** [comment]
Hey,

I think force quit is handled differently by the system than other shortcuts. However you can use the  predefined action "Trigger Menubar Menu Item" and use this string to trigger it: "apple;Force Quit...".

As for the Touch Bar after sleep: BTT remembers it's last visibility state, so if you had the Touch Bar showing before sleep it will also show after sleep, if not not.

Best,
Andreas

**Comment by zhaidoudou123** [comment]
@fifafu 
Hello Andreas,

"Trigger Menubar Menu Item" works, thank you!

As for the second question, it seems that BTT cannot remember its last visibility state on my computer.
When I wake up my computer (it was asleep with BTT's bar hidden), there are only 4 icons except BTT's icon in Control Strip and the current application's bar displays. However, after a few seconds, BTT's bar shows up the same way as I press BTT's icon.
And when I wake up my computer which was asleep with BTT's bar displayed, I can see: the bar hides and BTT restarts with bar showing up. 
I think BTT may crash after I wake up computer, and this may be a bug.

**Comment by zhaidoudou123** [comment]
@fifafu
Hi Andreas,

Today I tested again, if I hide BTT's bar by pressing the X button on the left, the bar will show again.
If I hide the bar by pressing the BTT's icon on Control Strip, the bar will not show after the computer wakes up.
