### ISSUE TITLE
5 Finger Tap broken in new Alpha 1.996

### ISSUE THREAD

**Issue by NoWayBehind** [fifafu/BetterTouchTool#342]
Hello,

5 finger Tap is not being recognized by BTT anymore. Instead a 4 finger tap is applied every single time. It's not app specific and It started happening when I installed the new alpha an hour ago. Restart didn't fix the issue (MacBook Pro 2016 15 and current Sierra Public Beta, if important).

And yes, I checked, I didn't loose a finger. I swear!

**Comment by fifafu** [comment]
Ah, thanks for reporting! Should be fixed in 1.997 :-)

**Comment by NoWayBehind** [comment]
Yep, working :)
