### ISSUE TITLE
BetterTouchTool Causes trackpad errors, erratic behaviour and short System Freezes!

### ISSUE THREAD

**Issue by cyberfunk** [fifafu/BetterTouchTool#345]
Out of nowhere the latest build of BetterTouchTool as of January 28th 2017 is causing errors on my 15" MacBook Pro Retina 2012 with MacOs Sierra 10.12.1 and 10.12.3 and El Capitan 10.11.6. This is really frustrating because up until today I've NEVER had an issue with BetterTouch Tool on any version of MacOS or OSX including Sierra and El Capitan and I've used it on more installs and across more versions of OSX than I can count. 
Very frequently my trackpad won't respond to click input and the system freezes for short moments making me unable to switch windows or make any changes or inputs by clicking the trackpad. Was there a recent update to the BTT software? I'm baffled. I disabled and completely uninstalled Better Touch Tool and the issue seems to have vanished. At first I was thinking maybe Apple updated my computers trackpad firmware or drivers with the latest MacOS Sierra 10.12.3 update but as I mentioned the issue persisted even after I downgraded back to El Capitan. Once I removed better touch tool the issue has gone away. Any input or tips are much appreciated:-)

**Comment by fifafu** [comment]
Hey,

I don't think there has been an update that could cause something like that.
Which version of BTT do you have installed exactly?

Have you already tried to restart your machine?

Best,
Andreas

**Comment by cyberfunk** [comment]
Hello and thanks for your reply. I was running the latest version. I'm not sure of the exact dot release number but it was there latest update. I restart, reset smc pram and did fresh installs of Sierra and El Capitan. After installing better touch tool the issue begins. As soon as I removed it the problem vanished. I've never seen anything like it. I'm a bit freaked out because my setup is always super stable.

**Comment by fifafu** [comment]
Please check the version number (by clicking the BetterTouchTool icon).
There are various versions depending on the update channel you are on.

**Comment by cyberfunk** [comment]
I keep a copy of BTT zipped in a folder with other programs I install. Could that zipped copy become corrupted somehow? I unzip and install that and then check for updates. I use the same procedure for all of my programs and never have issues.

**Comment by cyberfunk** [comment]
Version 1.989 (582) on the Regular Channel.

**Comment by cyberfunk** [comment]
Just as a test I downloaded a fresh copy of BTT directly from your site and loaded it. The click issue begins immediately. Sometimes I have to click an object 2 or 3 times to get it to register the action. This might sound funny but sometimes I have to use a narrower edge of my finger to click. If I rest the full surface of my finger on the trackpad and press then it won't register the click. I wish I had access to one of your older builds just to see if it's my computer or the app. As I mentioned above BTT has always been flawless with zero issues up until a few days ago and my MacBook behaves 100% normal once I have removed the latest build of BTT.

**Comment by fifafu** [comment]
bettertouchtool.net/releases/ here you can download previous releases. The last stable release was 1.963, the last alpha was 1.999!

**Comment by cyberfunk** [comment]
Thanks so much! 1.963 is working beautifully!!! Everything is smooth and back to normal. I'm not sure how I ended up with 1.989 but it definitely has issues at least on my MacBook retina 2012. I've turned off automatic updating so I'll stay at this stable release for now. I appreciate the support and thanks again for creating such a wonderful app!!!

**Comment by fifafu** [comment]
@cyberfunk ah that's good to know! It would however be awesome if you could take a look at 1.999 and check if that works correctly on your machine.

**Comment by cyberfunk** [comment]
1.999 is broken on my machine. I have all of the issues in my original post. I deleted 1.999 along with preferences and re-installed 1.963 fresh and everything is perfect again! It's a night and day difference between the two versions. 1.963 is a transparent and smooth experience while 1.989 and 1.999 are struggling to communicate with the operating system and having difficulty translating any click input from my track pad. That's the best way I can describe my experience.

**Comment by fifafu** [comment]
Very weird, I can't seem to replicate this on my machines and haven't had similar reports yet :-(
Do you maybe have other mouse related tools installed?

Or maybe something in your settings is causing this, have you previously tried to delete the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist ? If not, could you maybe send me that file?

Problem is, if we don't fix it now you'll run into problems with the next macOS update that breaks 1.963

**Comment by cyberfunk** [comment]
I don't have any other mouse or track pad programs loaded. All of the programs I have are basically the same across all of my installs since as far back as I can remember. I use app cleaner to delete my programs so all traces of previous BTT installs are cleaned including preferences. I also go in manually and delete whatever remnants app cleaner misses. The weird thing is I have installed and re-installed all of my OS setups the exact same way literally hundreds of times 10.9, 10.10, 10.11 and 10.12 (up to 10.12.1) and never had an issue with BTT. I always use the same apps and the same settings in Mac OSX system preferences. Like you said there must be something in one of my apps or settings that's causing a conflict with newer builds of BTT. I'll try to discover what it is but it will be tough because from my perspective nothing has changed with my setup except BTT stopped working all of the sudden. I bet something changed when I loaded Sierra 10.12.3. Are you on that release? I bet apple changed a firmware or something and even when I downgraded back to El Capitan 10.11.6 that firmware change stayed. That's the only explanation I can come up with. Upgrading to Sierra 10.12.3 might be the cause of my troubles with BTT. All of my issues started after that update even though I've since downgraded my machine.

**Comment by cyberfunk** [comment]
By the way the 1.999 I loaded from your releases page was btt1.999.zip. I didn't try the  btt1.999b.zip or the two btt1.999c.zip releases.

**Comment by cyberfunk** [comment]
In my track pad settings I always disable EVERYTHING as I can't stand any of the enhancements that Apple provides. Even their split screen function is not nearly as good as your window snapping feature in BTT so I disable that as well:-) BTT is great!

**Comment by fifafu** [comment]
One question: Does the live view in BTT show one dot or two dots when you are clicking? 

Maybe version 2.01 fixes your issue, but it's just a guess, maybe I'm wrong.

**Comment by cyberfunk** [comment]
What do you mean when you say live view? I have BTT in my menubar only but I don't know where to look to see dots. The only clicking function I use is 3 Finger Click for Right Click. That's it and I also use window snapping. Let me know how to find the dots and I'll get back to you.

**Comment by cyberfunk** [comment]
Good news!! 2.01 fixed the issue!!!! I could tell immediately that it works the same as 1.963. Thank you so much. If possible can you tell me what you changed?

**Comment by fifafu** [comment]
![image](https://cloud.githubusercontent.com/assets/8820811/22444757/9a5f15c8-e744-11e6-8bcc-d9609e89d165.png)


BTT blocked some clicks if it recognized two fingers touching the trackpad (but only in sone specific situations).

**Comment by cyberfunk** [comment]
Awesome. That's the one reason why I started using BTT years ago. Three finger right click! Apples two finger click option is garbage because you always accidentally touch an extra finger to the track pad. Thanks again! I just tested it and there is no issue with two finger click in 2.01 of BTT. Solved!

**Comment by villancikos** [comment]
Hi there. I just had similar problems. First theory was a hardware problem but somehow on safe boot  nothing happens. I was running the latest Alpha before deleting the app (which I've been using since forever :D ) sadly now my trackpad goes crazy. Normally starts to behave in the "opposite way". What I mean is that If I go to the upper right corner in my trackpad the pointer goes to the lower left corner on the screen. I don't know how to replicate it but normally happens when I try to do a multi finger action or a touch. MBP 15'' early 2011 is the mode.
