### ISSUE TITLE
Touch bar close group not working

### ISSUE THREAD

**Issue by gasranas** [fifafu/BetterTouchTool#346]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
When using a group in the TouchBar, the group will open, but the close button (x) doesn't work.

**What kind of Mac are you using?**
15" 2016 MBP with TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
touchbar

**Which versions of macOS and BetterTouchTool are you running?**
sierra, 1.997 (590) alpha.

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by gasranas** [comment]
Edit - I think it might be "All Touchbar Related Actions" are not working from the predefined actions.

**Comment by fifafu** [comment]
Mh, this seems to work fine for me. Could you attach an export of your setup so I can have a look?

**Comment by gasranas** [comment]
Problem seems to be fixed as of 2.02 (598), so I'll close this, and if it re-occurs, I'll let you know. Thanks for looking into it for me.
