### ISSUE TITLE
Feature request: trigger touchbar group with a keyboard shortcut

### ISSUE THREAD

**Issue by gasranas** [fifafu/BetterTouchTool#348]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Would it possible to have a keyboard shortcut (or other action) that will activate a certain touch bar button group? Thank you!

**What kind of Mac are you using?**
15" 2016 macbook with touchbar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
touchbar, keyboard, trackpad

**Which versions of macOS and BetterTouchTool are you running?**
sierra, 1.997 (570) alpha

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
This is possible with current versions of BTT using the "Open Touch Bar Group With Name" action.
