### ISSUE TITLE
BTT doesn't work for me

### ISSUE THREAD

**Issue by carlito666** [fifafu/BetterTouchTool#349]
I'm using a normal mouse for my MacBook air. I created an action, how to trigger it? I thought it would be as simple as in Windows based app (like JustGestures), but it's not.

I'd like to use my right mouse button to trigger the key combination. This is what I expect from your app.

Thanks for help.

**Comment by fifafu** [comment]
Hi,

Sorry, BTT currently doesn't have such mouse gestures, but this may be added with a future version.

Best
Andreas

**Comment by carlito666** [comment]
thanks!
