### ISSUE TITLE
snap areas and window snapping not working for iMessage

### ISSUE THREAD

**Issue by jakobsperry** [fifafu/BetterTouchTool#350]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

**What kind of Mac are you using?**
Macbook Pro 13" early 2015
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook force touch trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.4 beta
BTT 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Neither window snapping nor snap areas are working, but just for iMessage

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
