### ISSUE TITLE
Feature request: button-only counterparts for the Touch Bar volume/brightness sliders

### ISSUE THREAD

**Issue by ThePantsThief** [fifafu/BetterTouchTool#351]
Like the ones you can add to the expanded control strip from system preferences! I like the brightness slider, but I'd rather use the buttons alone for volume.

**Comment by fifafu** [comment]
Hey,

you can just add normal buttons and assign the volume / brightness predefined actions or am I missing something?

Best,
Andreas

**Comment by ThePantsThief** [comment]
Well, what I really want is the ability to use the actual system buttons from System Preferences instead of having to basically build them myself (same with the emoji button you added; it's nice, but it would be ideal to have the actual one). 

Do you need help looking into that? Do you know which framework might contain them? I can dig around in the disassembly with ya.

**Comment by fifafu** [comment]
It's in the normal Cocoa framework, but it's not possible to use them in the context of BTT.
If you find a way I'm happy to add it, but I don't think it's doable without major hacks.

**Comment by ThePantsThief** [comment]
The system button classes are just in Cocoa.framework? Wouldn't you just be able to create them with `NSClassFromString` and friends?

**Comment by fifafu** [comment]
Yes, but I can't display them due to Touch Bar limitations (they require to use popover Touch Bars, but BTT itself is a popover Touch Bar. Only one of them is allowed).

I can pull out some of the views and stuff (that's where I get the recent emoji) but I can't just add them as they are added in the system Touch Bar. I

**Comment by ThePantsThief** [comment]
Ohhhh I see. I'll look into it and let you know here if I find anything useful. Thanks!

**Comment by fifafu** [comment]
Good luck, but don't waste too much time :-) (I gave up on this after I tried quite a few things, got it working a bit but never completely)
