### ISSUE TITLE
Feature Request: support for java or game specific Touch Bar settings

### ISSUE THREAD

**Issue by NSExceptional** [fifafu/BetterTouchTool#354]
I realize how niche this is, but this would be awesome for Minecraft or other games that don't necessarily run out of a .app folder. Configurable buttons for all sorts of things etc

**Comment by rscosworth** [comment]
I am also having this issue with a terminal 3270 app which runs on Java - any update to when this may be implemented?

**Comment by fifafu** [comment]
Current BTT versions allow you to select apps from the list of currently running applications, this should help.
