### ISSUE TITLE
midi output from widgets

### ISSUE THREAD

**Issue by hoi1234567889** [fifafu/BetterTouchTool#356]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
It would be great if you can ad widgets that can output midi, so people can link slider for examples
to faders in their DAW  

**What kind of Mac are you using?**
mb pro 15 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
touchbar

**Which versions of macOS and BetterTouchTool are you running?**
sierra 10.12.3
1.999
**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
See #173.
