### ISSUE TITLE
Issue: Brightness slider is being reset to Mac-Setting after a few seconds.

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#357]
When i change the brightness via the touchbar slider, it will slowly reset itself back to the brightness that was set in the system settings (about 1-5 seconds after i changed it with the slider) . I can not get it to stick when using the brightness slider over the BTT-touchbar.

When i change the brightness over the system hotkeys or the system settings, everything works fine. as soon as i use the btt-slider again, it wont stick.

**Comment by fifafu** [comment]
I think you may not be using the most current version (1.999)

**Comment by fantaaaaaa** [comment]
you were right. unfortunately BTT does not show me all existing updates automatically even though i activated the settings and even joined alpha update. did the update manually now.

back to topic: 
- i am still experiencing brightness changes when using the slider which i dont experience when using the system-brightness change. My observation is that the btt-slider will react to the smallest change of light or even my movement with a brightness-reset back to the systemsetting while the default slider will stick when the light changes...
- when using an external monitor the slider will only change the brightness of my internal display, not the external monitor.

**Comment by fifafu** [comment]
Mhh are you sure you are on v1.999?

To change the external monitors brightness keep ctrl pressed while sliding :-)

**Comment by fantaaaaaa** [comment]
i was on 1.999 and now switched to 2.0. but its same behaviuour though. i have made a video for you where you can see what happens. basically i set the brithness and opened monitor prefs so you can see how the brithgness changes. whenever i set the brightnes in the touchbar it will get reset to the system setting but when i set the brightness via monitor prefs it will stick. at the end i used the touchbar once more and it reset itself again:

its just 1:30 so should be no biggie to watch :)
https://www.dropbox.com/s/unv4x247r6ore6i/IMG_3341.MOV?dl=0

**Comment by fifafu** [comment]
Weird. Probably for now the only solution is to disable automatic brightness adjust in system preferences => display. I'll look into this1

**Comment by fantaaaaaa** [comment]
This is a temporary workaround but not a really good solution of course. good luck you find something! thanks! and keep up the good work, glad to see the progress here! greatly valued tool, thanks!

**Comment by leleSahil** [comment]
I'm having the same issue as well

**Comment by fantaaaaaa** [comment]
Andreas did you have the chance to look into this? I have reverted back from the slider although i would really love to use it since its much more intuitive and can save a lot of space instead of using two buttons and repeatedly having to hit them :) 

is there a possible solution for this?
thanks a lot for your tool (once again). i just today said to a colleague that i could not live without a tool like this. its the peace that makes working with a mac so brilliant and different from other systems. makes you so much more productive and flexible! thanks a million times (as my usage shows) :) 

<img width="1127" alt="screenshot 2017-02-23 20 20 56" src="https://cloud.githubusercontent.com/assets/24585031/23275679/bfdcb7f8-fa07-11e6-9194-83f99afbeda9.png">

**Comment by fifafu** [comment]
Hey,

yes I got a solution. It will be in the next update this weekend. (Sorry currently under heavy load @work thus I can only work on BTT on the weekends)

**Comment by fantaaaaaa** [comment]
i've already reinserted the slider right now and will report if it works!

**Comment by fifafu** [comment]
@fantaaaaaa would be great if you could check v 2.08 alpha. On my machine the new API I use seems to work fine, but it's undocumented so there may be some hidden things that may depend on the specific system.

**Comment by fantaaaaaa** [comment]
yeeees, it works, thanks!!! :)

**Comment by fantaaaaaa** [comment]
this can be closed with the new alpha

**Comment by fantaaaaaa** [comment]
(fixed)
