### ISSUE TITLE
General bug: BTT Preference window disappears after expose (can somebody confirm?)

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#359]
From at least a few months up until 2.0 there is an issue where the BTT preferences window will go into the background after invoking Expose and picking the BTT window. It will briefly come to the front and disappear in the back. Using CMD+Tab works as it should though.

Here is a video of the bug. Is this reproducable?
https://www.dropbox.com/s/unv4x247r6ore6i/IMG_3341.MOV?dl=0

**What kind of Mac are you using?**
Macbook Pro late 2016 with Touchbar

**Which input device is affected by this?**
Macbook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.3, BetterTouchTool all versions up until 2.0

**Comment by fifafu** [comment]
this has already been reported (see #30) however I still don't have the slightest clue what could be causing it :-)
I'll continue to track it in issue #30
