### ISSUE TITLE
Gets stuck on key repeat

### ISSUE THREAD

**Issue by zippomanhollis** [fifafu/BetterTouchTool#36]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Gets stuck when using a key remap with key repeating:
I have the 'hjkl' keys combined with the <command> key remapped to the arrow keys with key hold repeating enabled.  Twice while using <command>+'h' to move the cursor 'left', the cursor has gotten stuck moving left and I am unable to regain control of it without killing btt.

**What kind of Mac are you using?**
MacBook Pro (13-inch, Early 2011) 2.7 GHz Intel Core i7  

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
At this time, I only know that my mac's internal keyboard is affected since I haven't used my external keyboard in a few days.

**Which version of macOS are you running?**
macOS 10.12.1 (16B2555)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Dont know how to fix, I had to kill btt just to regain control of computer, because the remap was to an arrow key, making it nearly impossible to select "nice" quit from btt menu.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
I think this should be fixed with the next alpha version that I'll release later today (1.978).
