### ISSUE TITLE
Spread / Pinch with Thumb and 2 fingers Broken in 2.0.1

### ISSUE THREAD

**Issue by eggplantsplz** [fifafu/BetterTouchTool#361]
Hi there,

Thanks for your continued efforts with the software!
I currently have Spread and Pinch with Thumb and 2 Fingers set to trigger CMD+T and CMD+W respectively. This seems to have broken in the latest version of the software? I can't get it to trigger in the apps nor in the 'live feedback' testing mode.

Would greatly appreciate some advice here!

Thanks.

**Comment by eggplantsplz** [comment]
@fifafu sorry - replied to the wrong thread. Thumb handling is not enabled.

**Comment by fifafu** [comment]
@eggplantsplz which version of macOS are you running?

**Comment by eggplantsplz** [comment]
Apologies - 10.12.2

**Comment by fifafu** [comment]
Could you check whether it works if you **enable** thumb handling in the advanced trackpad preferences?

**Comment by eggplantsplz** [comment]
@fifafu weird. Works now. Are the permissions reversed or something? I don't recall having thumb handling enabled in 1.96. Irrespective, that did the trick!

**Comment by fifafu** [comment]
it's a bug. I'll upload a new build :-)

**Comment by eggplantsplz** [comment]
Cheers!
