### ISSUE TITLE
bug report: fail to perform shortcut

### ISSUE THREAD

**Issue by zkg03mjmk** [fifafu/BetterTouchTool#362]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

**What kind of Mac are you using?**
MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Keyboard

**Which versions of macOS and BetterTouchTool are you running?**
MacOS Sierra ver 10.12
BTT ver: 2.01

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
![screen shot 2017-01-30 at 4 36 49 pm](https://cloud.githubusercontent.com/assets/25445038/22447899/533585d6-e70a-11e6-9235-887020040d6a.png)
I created two shortcut for mouse actions. I would like to select and open file use keyboard entirely. 
Bug:
left click short cut does't work. In following example, I want to left click NMB_turbo.txt. I use arrow first select the file first. 
![screen shot 2017-01-30 at 4 47 59 pm](https://cloud.githubusercontent.com/assets/25445038/22448120/ee6483a8-e70b-11e6-8e84-7a55233348aa.png)
After the left click shortcut. It goes to a random file. Here is the screenshot of results (it goes to NMB_FAN1 copy.txt):
![screen shot 2017-01-30 at 4 49 24 pm](https://cloud.githubusercontent.com/assets/25445038/22448146/1400cf54-e70c-11e6-9b2f-6a444603a7c1.png)

Since the left click doesn't work correctly. To perform right click short cut, I have to use mouse to select, which makes the short cut useless.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by zkg03mjmk** [comment]
I found out that the current action is based on the the location of the mouse. That is the reason why left click shortcut can not performed on the cursor 

Is it possible to add a future to make the action based on cursor? That would be more practical in use.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

To open a selected file in Finder you could just send the cmd+o shortcut or if you want to open with a specific app  use the predefined action "Open Current Finder Selection with Specific App"
