### ISSUE TITLE
Triangle Swipe No Longer Works with version 2.01

### ISSUE THREAD

**Issue by EDeutsch90** [fifafu/BetterTouchTool#363]
#### Description of your bug/question/feature request...:
Triangle swipe no longer works after the latest update (2.01). Commands are still assigned to the triangle swipe gestures, but the triangle swipe gestures are not even recognized in the Live View. Computer restart does not resolve the problem.

**What kind of Mac are you using?**
Macbook Pro (2014), 15" Retina

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
OS X Yosemite 10.10.5 and BetterTouchTool version 2.01

**Comment by eggplantsplz** [comment]
having a similar issue but with spread/pinch with thumb. BTT 2.01

**Comment by fifafu** [comment]
weird, do you maybe have thumb **filtering** enabled in the advanced settings? (thumb handling shouldn't be a problem)

![image](https://cloud.githubusercontent.com/assets/8820811/22455522/4e4d7960-e78d-11e6-9e9d-b869febb0938.png)

**Comment by eggplantsplz** [comment]
Hey @fifafu , thanks for the reply.

Nope - I don't. What's even more weird is that the gesture also isn't being recognized in live-view.

**Comment by parthi64434** [comment]
I do have the same issue. Please give me a solution.

**Comment by EDeutsch90** [comment]
Two updates to BTT and still no solution. Anybody?

**Comment by fifafu** [comment]
It seems to be working fine on my machines, but maybe it depends in the trackpad type.

In 2.04, if you disable thumb recognition and thumb filtering the old behavior should be back. Could you try that?

Otherwise you can always downgrade to an okder version for now (https://Bettertouchtool.net/releases)

**Comment by EDeutsch90** [comment]
Yup, looks like disabling both thumb handling AND thumb filtering did the trick. Thank you!
![screen shot 2017-02-09 at 4 16 11 pm](https://cloud.githubusercontent.com/assets/25444531/22805449/2cf9376a-eee3-11e6-8012-2b20b58753d2.jpg)
