### ISSUE TITLE
Bug: Volume slider on touchbar doesn't go all the way down

### ISSUE THREAD

**Issue by joreilly02** [fifafu/BetterTouchTool#365]
On the touchbar, if you have a volume slider, the slider doesn't go all the way down (even though the volume is).    It will, but as soon as you switch away from the app you're using, it goes back to being just slightly up. 
![img_2269](https://cloud.githubusercontent.com/assets/17679418/22451951/bb2a1324-e740-11e6-97a3-f58f4a4e2e8f.JPG)

**What kind of Mac are you using?**

2016 15" Macbook Pro w/ Touchbar 

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3 and 2.01 (597)

**Comment by SuttJ** [comment]
I have the same problem. Although the actual computer volume will be at 0, the slider icon will always be poking out a little.

**Comment by dafurman** [comment]
I've noticed this issue as well. It's not a huge deal, but does make me a little bit wary of my volume levels when in a public setting.

**Comment by TroutDeep** [comment]
Same behavior here.  Drives me nuts.  I'm constantly re-sliding the volume slider to 0, but it always creeps back up.

What kind of Mac are you using?

**2016 15" Macbook Pro w/ Touchbar**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.5 and 2.267

**Comment by SuttJ** [comment]
Same here. Annoying issue.

**What kind of Mac are you using?**
2016 13" Macbook Pro w/ Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.4 and 2.270

**Comment by fifafu** [comment]
Should be fixed in the latest alpha v2.282 (https://bettertouchtool.net/releases/btt2.282b.zip)
