### ISSUE TITLE
Launch vs. Open an application

### ISSUE THREAD

**Issue by NickHibma** [fifafu/BetterTouchTool#368]
In the screenshot you can see that in the list the opening of an application is called 'Launch XYZ.app', but in the 'trigger action' menu it is called open (you cannot find the action type by searching for 'launch'). So I first type in 'launch' in that search box, go "huh?" and "right, it's 'open'", type in 'open' and get to the action type I need to be.

Just a minor thing, but I like things to be consistent, so here you go!

![image](https://cloud.githubusercontent.com/assets/572576/22456941/95be5780-e795-11e6-8ac6-b1e6ff470f6b.png)

**Comment by fifafu** [comment]
This will finally be fixed with the next version :-)
