### ISSUE TITLE
Customized touch bar goes back to default after 'command' press

### ISSUE THREAD

**Issue by maudan380** [fifafu/BetterTouchTool#37]
Using a late 2016 MacBookPro - Sierra
Totally customized touch bar - thanks to bettertouchtool - however after 'command' or 'shift' press, the touch bar goes back to default. - as if I am trying to tab between apps.

**Comment by fifafu** [comment]
Mhh I can't seem to reproduce that. Could you maybe send me an export of your setup (via the export button in BTT) to boastr.net@gmail.com?

**Comment by maudan380** [comment]
Hi Andreas,

Thank you.

Attached is my set up. It basically happens any time I am typing something and I hit command or shift.

Thank you!

**Comment by moshed** [comment]
@fifafu i get this also. but only if show MacOS control strip is not toggled then pressing cmd or shift reverts it to being toggled. [heres my exported settings](https://mega.nz/#!aEEnhT7D!IY496C28chQ4oHYzmJ2myS9gGkJe136hKQ3-vWpgQRg)
maybe be related to #29

**Comment by maudan380** [comment]
@moshed Thanks man, you described it better than I did - it is in fact exactly what happens to me as well.
