### ISSUE TITLE
'Start/stop Moving' (moving the window under the cursor) not working on macbook pros with touchbar

### ISSUE THREAD

**Issue by jordn** [fifafu/BetterTouchTool#371]
Macbook Pro 13" 2016 with Touch bar (also confirmed on a Macbook Pro 15" 2016 with Touch bar)

The assigned action 'start/stop moving' associated with a touchpad (some selection of modifier keys — i use fn + shift — without any touchpad gesture) is not working on the new macbooks. This works on an old 2012 rMBP. It's a super useful feature for moving windows around without having to be careful to drag the top bar.

Running version BTT 2.02
MacOS 10.12.3

**Comment by jordn** [comment]
😞

**Comment by fifafu** [comment]
Hey,

this definitely still works, the Touch Bar MBP doesn't differ from other MBPs here.
Are you sure BTT is configured like in the screenshot attached?

Also make sure BTT is activated in System Preferences => Security & Privacy => Privacy => Accessibility. Also make sure you are running the latest version of BTT.

![image](https://cloud.githubusercontent.com/assets/8820811/23824745/68771ed2-067c-11e7-98a7-849a77ce13a2.png)
