### ISSUE TITLE
Touch Bar `esc` button behaves strangely with App Switcher

### ISSUE THREAD

**Issue by sethblumberg** [fifafu/BetterTouchTool#372]
#### Description of your bug/question/feature request...:

When I have the app switcher open (`cmd`+`tab`, and then keep holding down `cmd` key), normally the `esc` key (with `cmd` still held down) is supposed to exit the app switcher without switching to the currently highlighted app.  The regular Touch Bar `esc` key does this properly.

With the BTT Touch Bar open, this is not what happens.  There are three ways to get an `esc` key in the BTT Touch Bar, and they each behave differently when the app switcher is open:

1. In *General Touch Bar Settings*, check off "Show ESC Button on the left side of the Touch Bar".
    - This `esc` button brings up the *Force Quit* dialog.

2. Manually make a Touch Bar button, selecting as action from the *Predefined Action* menu *Keyboard Keys > ESC (Escape Key)*.
    - This button switches to the highlighted app, just like hitting `Return` or releasing `tab`.

3. Manually make a Touch Bar button, selecting as action a *Custom Keyboard Shortcut* and then hitting the `esc` key.
    - This button works correctly - canceling the app switcher without changing apps.

All three of these work the same regardless of whether *Use special application switcher* is checked off in *Advanced Settings > Predefined Action Settings*.

**What kind of Mac are you using?**

MacBook Pro 2016 13" with Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**

macOS Sierra 10.12.3
BTT 2.02

**Comment by RamRS** [comment]
+1. I came here to report this bug - glad I ran a search first!

**Comment by fifafu** [comment]
I think this should be fixed with the current alpha

**Comment by RamRS** [comment]
Updated to 2.08 (610). Bug still persistent.

**Comment by fifafu** [comment]
@RamRS what exactly? For me the three points mentioned above seem to be working correctly with 2.08 (unless I misunderstood one of them)

**Comment by RamRS** [comment]
I'm looking at the default behavior - the default Esc provided by BTT. Cmd + Esc switches to the highlighted app and doesn't quit the app switcher without switching.

**Comment by fifafu** [comment]
My hardware keyboard with ESC button also doesn't switch to the selected application, instead it just closes the App Switcher. I think this is the default behavior of macOS when the ESC button is being pressed?
Actually the behavior of the ESC provided in the predefined actions seems to be a glitch :-)

However if you need that behavior, you can just disable the ESC button in the general Touch Bar settings in BTT, then add a new global Touch Bar button and assign it the predefined action.

**Comment by RamRS** [comment]
Exit App Switcher without any change is how Cmd+Esc should behave. It is not how the default BTT Esc works. I'll try adding a new global button now.

**Comment by RamRS** [comment]
Tried adding a new button as you recommended, still same behavior. Cmd+Esc keeps switching apps.

**Comment by fifafu** [comment]
@RamRS sorry I think I misunderstood your previous message - I agree that it shouldn't switch apps.
For me this seems to work correctly, but I'll look into what could be causing this!

**Comment by RamRS** [comment]
Thank you, @fifafu !

**Comment by Leksat** [comment]
I normally don't use touchbar at all and mapped the top left physical key (paragraph sign on my keyboard) to esc. I experience the same problem. If I hit my mapped esc key during cmd-tab - it does not quit the app switcher. But esc from the touch bar works.

(Also I have the same behavior with ctrl-tab dialog in PhpStorm.)

I tried to map the top left keyboard key to
- Trigger Predefined Action > ESC (Escape Key, respects pressed modifiers)
- Trigger Other Keyboard Shortcut > escape

None works.

BTT Version: 2.310

**Comment by fifafu** [comment]
Unfortunately the issue has gotten worse with newer macOS versions as the BTT esc button is now completely disabled when opening the app switcher.

Continue to track this here: https://github.com/fifafu/BetterTouchTool/issues/1988

**Comment by RamRS** [comment]
The workaround above has a bug. If I were to dismiss BTT using the `X` touch button, and after a few seconds press `Cmd`, when I release the `Cmd` the BTT panel appears again. Given that I dismissed it, should it not stay dismissed? Is the on-Cmd-release trigger enabling BTT irrespective of what the pre-Cmd-press setting was?
