### ISSUE TITLE
Snap area coordinate system origin is in bottom-left corner rather than top-left

### ISSUE THREAD

**Issue by brumm** [fifafu/BetterTouchTool#377]
Traditionally, computer screen coordinate systems originate in the top left corner.

Today I realized to my surprise that the (much appreciated!) Snap Area feature does things differently, and originates at the bottom-left corner of windows and the screen. This makes it unnecessarily cumbersome to adjust positioning, because adjusting the height of a snap area will change the `y` value as well.

As you can see in the screenshot, the `y` value should be `9`

<img width="659" alt="screen shot 2017-02-01 at 09 28 09" src="https://cloud.githubusercontent.com/assets/170500/22499873/8122b362-e861-11e6-96d1-76729badea8d.png">

**Comment by fifafu** [comment]
I know it's unusual but it's how the used Apple Accessibility API handles the coordinates. I don't want to do conversions because in my experience they can be quite tricky on multi monitor systems.

**Comment by brumm** [comment]
Fair enough, thanks for the explanation 👍
