### ISSUE TITLE
Touch bar bug: BTT cannot remember its last visibility state after waking from sleep

### ISSUE THREAD

**Issue by zhaidoudou123** [fifafu/BetterTouchTool#378]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I mentioned this issue in [https://github.com/fifafu/BetterTouchTool/issues/339](url) but since it was closed, maybe you will not be able to see it.

The issue is that if I hide BTT's bar by pressing the X button on the left and sleep, the bar will show again after waking.
And if I hide the bar by pressing the BTT's icon on Control Strip, the bar will not show after the computer wakes up.

**What kind of Mac are you using?**
2016 MBP 13

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3 2.02(598)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Unfortunately that's currently not fixable (the x is a system button and BTT doesn't know whem it's pressed).
I have not found a workaround for this yet.

**Comment by zhaidoudou123** [comment]
@fifafu
That means I should try to get used to pressing the icon :)
Thank you very much!
Hope that Apple will do something to this soon.

**Comment by nhooyr** [comment]
Is it possible we could set the default state of the BTT touch bar when waking from sleep? I'd like it to be hidden until I press the button.
