### ISSUE TITLE
use capslock as hyperkey

### ISSUE THREAD

**Issue by brumm** [fifafu/BetterTouchTool#379]
I'd love to be able to remap `Capslock` to `SHIFT+CTR+ALT+CMD` to introduce another layer of possible shortcuts, without having to hold up all of these keys, i believe that's called a 'hyperkey'

a key combination of `CAPSLOCK+A` would be sent to the system as `SHIFT+CTR+ALT+CMD+A`

Would that be possible?

**Comment by fifafu** [comment]
Hi!

Very nice idea, but unfortunately this would require deeper system integration than BTT can do. I think apps like Karabiner may be able to do this (although as far as I know it's not yet fully compatible with Sierra)
