### ISSUE TITLE
Option to download old versions due to bugs in newer releases

### ISSUE THREAD

**Issue by KTruong888** [fifafu/BetterTouchTool#38]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Can we please have an option to download old versions of BetterTouchTool. I upgraded to the latest today, 1.96, and found bugs with multiple gestures that worked the day before.

Three finger double tab - Command + Click (Open in a new tab): inconsistent on links, as it would open two instances of the link. I tried spreading out my fingers, slowing the interval between taps, speeding the interval, but found a lot of inconsistency as to when it would open one, or two (though it should have never opened two in the first place)

1 finger fix, 1 finger tap - Ctrl tab and Ctrl shift tab (to switch tabs): I think something changed with the sensitivity here. I found it not registering the action and I'd often have to repeat the action for it to work

Also, I'm not sure if I was going crazy but it did feel like the gestures were less responsive in general. Especially the three finger double tap to open a tab in a new window. It felt like it took half a second longer at times, but felt normal at others.

**What kind of Mac are you using?**

macOS Sierra 10.12.1
Macbook Pro 13" 2016 Edition with TouchBar, only upgraded 16gb of ram

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackpad

**Which version of macOS are you running?**

macOS Sierra 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

I was able to fix the above issues by digging into my trash and installing an old version (1.93).

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Old versions can always be downloaded here: https://boastr.net/releases

However it's really important to report any issue you encounter, because otherwise it may never be fixed and the next OS update that breaks the old BTT version would leave you stranded.
