### ISSUE TITLE
Usb Mighy Mouse jumps 

### ISSUE THREAD

**Issue by tardegard0** [fifafu/BetterTouchTool#380]
Using Btt since long time, never had such a problem. But now, since few days, my usb mighty mouse pointer jumps. Sometime, not always, but sometimes when I left click somewhere, the pointer disappears to reappear elsewhere. Very frustrating. 
I have very few tweaks on Btt though. 

Btt 2.02 version. 
MacBook Air 10.12.2. 
A deep uninstall (via AppCleaner) and reinstall was useless. 
Thanks.

**Comment by tardegard0** [comment]
Since no one answers, I am gonna answer myself: 
it seems that the application Smart Scroll conflicts with btt. 
I have disabled it, no more jumping mouse.

**Comment by fifafu** [comment]
Thanks for letting me know!

**Comment by tardegard0** [comment]
is there a chance it will addressed?
