### ISSUE TITLE
Feature request: Have ESC stay left of (x) in touchbar

### ISSUE THREAD

**Issue by ftolsson** [fifafu/BetterTouchTool#381]
Using MBP 13" 2016 with touchbar:

Would it be possible to keep the "close BTT toolbar" X button one step further right, thus keeping the ESC key leftmost on the touchbar?

Muscle memory dictates that the esc key is the furthest button to the left — causing me to repeatedly close the BTT app specific keyboard instead of escaping dialogs etc. 

Highly appreciated — and while possibly late in the game: Thanks for a great tool!

/F.

**Comment by fifafu** [comment]
Unfortunately, that's not possible due to API limitations ;-(
If I ever find a way to get rid of the x button I'll add it.

For now the only way to achieve this is to hide the macOS Control Strip in the general Touch Bar settings in BTT.
