### ISSUE TITLE
Option to hide Close button(X) on touch bar

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#382]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Feature request to have the close button(X) to be hidden or shown

**What kind of Mac are you using?**
15" MacBook Pro late 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
touch bar

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.3, BTT 2.02

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fantaaaaaa** [comment]
shouldnt your close button just be a simple button that you can remove from your list of buttons?

**Comment by fifafu** [comment]
Unfortunately removing that X button is only possible when unchecking the "Show macOS Control Strip". It's an API limitation I haven't found a workaround for yet.

Closing because it's a duplicate #204, #163, #123, #381
