### ISSUE TITLE
Impossible to set 0px margin for touchbar button

### ISSUE THREAD

**Issue by x600** [fifafu/BetterTouchTool#383]
I have BTT touchbar for parallels and the rightmost button is [Del]. When i try to stick it to the right setting margin to 0 defaults to 5px, while -1px cuts 1px from the right side ;)

So minimum padding is 1px. Can it be 0 still?

**Comment by fantaaaaaa** [comment]
experiencing the same here.

**Comment by fifafu** [comment]
Should be fixed in the new alpha 2.08  (available in about an hour)
