### ISSUE TITLE
Touchbar Apple Script Widget: Option to "rerun" the script after running the action

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#385]
![screenshot 2017-02-01 22 53 07](https://cloud.githubusercontent.com/assets/24585031/22527908/3a0a0320-e8d1-11e6-82b6-b239831794d1.png)
It would be great it we could get a script widget to rerun each code when the button was triggered.

For example: I keep reading a status of a lamp every 5 minutes and return it in the script and toggle the color of the button. When i trigger the lamp-button it will toggle the light and save the status. But the status on the button will be refreshed every five minutes. Additionally it would be great to have an Option "Run the script every time the button is pressed" so i can refresh my status after every press.

**Comment by fifafu** [comment]
Good idea. For now you can just attach an additional action to the widget and use the "Run Apple Script" action to trigger the script again.

(I just noticed a bug when doing this.... it shouldn't show the name, icon, and advanced configuration views, just ignore them)

![image](https://cloud.githubusercontent.com/assets/8820811/22528077/019e9978-e8d2-11e6-8c12-1069f01e04e0.png)

**Comment by fantaaaaaa** [comment]
Wow, blazing fast reply!
But attaching an additional action with a script wont re-color the button fitting to the response of the script, right?

**Comment by fifafu** [comment]
Yes too fast :-D should have thought a bit more about it first :-)

**Comment by fantaaaaaa** [comment]
However, your option or a setting to retrigger the script after invoking the button would both work perfect. is that something that might be possible to add?

**Comment by fifafu** [comment]
Yes, I'll add it!

**Comment by fantaaaaaa** [comment]
great! thanks a lot! is this something that i will read about in the release notes or is there a way to get informed when it was/will be added?

**Comment by fifafu** [comment]
yes I'll add it to the release notes but will also close this issue when it's done.

**Comment by fantaaaaaa** [comment]
edit: in my case it would be better if i could rerun the code instead of adding an action. that way, you use the same code instead of having it in multiple instances. i would end up having lots of duplicate codes that need to be taken care of.

**Comment by fantaaaaaa** [comment]
https://github.com/fifafu/BetterTouchTool/issues/475
same here

**Comment by fantaaaaaa** [comment]
Hi Andreas,

im not sure: has this been implemented already?

**Comment by fifafu** [comment]
It's implemented, however you need to assign it the "run apple script (enter directly as text)" action. I know this causes duplicate scripts, however it was a much more flexible solution that covers also other use cases.

**Comment by fantaaaaaa** [comment]
i dont really understand. do i need to attach an additional actions? Its an applescript widget so it already has. a script that runs on press and it has one script that checks every x minutes.

**Comment by fifafu** [comment]
Here is a small example (copy & paste into BTT):

```
{
  "BTTWidgetWidth" : "Example",
  "BTTTriggerType" : 639,
  "BTTTriggerTypeDescription" : "Apple Script Widget",
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : 172,
  "BTTPredefinedActionName" : "Run Apple Script (enter directly as text)",
  "BTTInlineAppleScript" : "return \"From Manual Press\"",
  "BTTEnabled" : 1,
  "BTTOrder" : 0,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemPadding" : 20,
    "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
    "BTTTouchBarButtonColor" : "213.562500, 58.650001, 58.650001, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarAppleScriptString" : "return \"From timed execution\"",
    "BTTTouchBarColorRegex" : "Manual",
    "BTTTouchBarAlternateBackgroundColor" : "109.650002, 109.650002, 253.569894, 255.000000",
    "BTTTouchBarScriptUpdateInterval" : 5
  }
}
```

It will trigger the timer based apple script every 5 seconds and the manual apple script on every button press.

**Comment by fantaaaaaa** [comment]
sorry for being stupid bow how do i add this? :)

**Comment by fifafu** [comment]
Just cmd+c the text and cmd+v it in BTT :-)

**Comment by fantaaaaaa** [comment]
ah, didnt set focus to the proper area of the BTT window.

while your simple example works, i cant figure out why it does not work in my case.
the timer-part of the script works and returns the proper values and triggers color and icon. however after pressing the widget it makes the widget disappear:

```
property baseURL : "http://xxxx:8099/zuhause/assets/php/homekitHandler.php?device=SCHLAFZIMMER_LAUTSPRECHER&action=2"
set ergebnis to "emtpy"
try
	set ergebnis to do shell script "curl --max-time 3 '" & baseURL & "'"
	if ergebnis = "1" then set ergebnis to "on"
	if ergebnis = "0" then set ergebnis to "off"
	return ergebnis
on error
	set ergebnis to "error"
end try
delay 0.5
return ergebnis
```

when i remove my script text and replace it with something simple, it works. cant figure out where the error in the script is supposed to be since it works fine when running it manually.

**Comment by fifafu** [comment]
strange, that sounds like it's returning an empty string (because in that case the widget would be hidden).

Maybe try to add a "display dialog ergebnis" instead of the return, to check what it is returning

**Comment by fantaaaaaa** [comment]
shame on me. the specific action that i ran on a press did not return the proper value. all other actions did, but this one didnt... sorry for bothering you, my mistake. and thanks for implementing this.

**Comment by fifafu** [comment]
Perfect!
