### ISSUE TITLE
Touchbar Apple Script Widget: Is it possible to swap icons depending on "return" value?

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#386]
![screenshot 2017-02-01 23 08 45](https://cloud.githubusercontent.com/assets/24585031/22528408/67702626-e8d3-11e6-9bf0-73a19168567c.png)

It would be awesome if we could swap out the button-icons depending on the returned value additionally to the color. That way you could set a default icon for example a "switched off lamp" and swap it out against a "switched on lamp" when the returned value is appropriate....

**Comment by fantaaaaaa** [comment]
<img width="1085" alt="screenshot 2017-02-01 23 12 21" src="https://cloud.githubusercontent.com/assets/24585031/22528508/ebc14914-e8d3-11e6-97d6-472b5aba192a.png">

Edit: Thats my setup and i would love to be able to swap out the lamp icons for "shining bulb" and "switched off bulb" depending of the returned value and keep the color on one value independent of the value. currently im toggling colors of the button but i dont like how it looks :)

**Comment by fifafu** [comment]
yep, this is already on my todo list :-)

**Comment by fantaaaaaa** [comment]
you might close this as it has been implemented since aprox. version 2.10

**Comment by agrublev** [comment]
This would be great, im trying to replace my dock with btt, and i have a script as follows:


```
set plistpath to (path to preferences folder as text) & "com.apple.dock.plist"

tell application "System Events"
	set plistContents to contents of property list file plistpath
	set pListItems to value of plistContents
end tell
set persistentAppsList to |persistent-apps| of pListItems

on is_running(appName)
	tell application "System Events" to (name of processes) contains appName
end is_running

set dockAppsList to {}
repeat with thisRecord in persistentAppsList
	set safRunning to is_running(|file-label| of |tile-data| of thisRecord)
	if safRunning then
		
	else
		set end of dockAppsList to |file-label| of |tile-data| of thisRecord
	end if
	
end repeat
set saveTID to text item delimiters
set text item delimiters to ", "
set Final to dockAppsList as text
set text item delimiters to saveTID
return Final
```

So i get list of my sticky apps that are not running as text, i would love them as images.

Short term hack you do support emojis : ) ❤️

**Comment by fifafu** [comment]
Current versions of BTT allow you to select an alternate icon, like the alternate color!

**Comment by proactivematter** [comment]
I am trying to write AppleScript (I am not a coder) so I can use this feature to switch pause/play buttons but cannot for the life of me get it to work. I wonder if any of you gentleman could lend me a hand?

This is what I got so far. It does nothing and shows no result (same as return value?).

`on appIsRunning("iTunes")
	tell application "iTunes"
		try
			set currentstate to (get player state)
		end try
		if currentstate = playing then
			pause
		else
			currentstate = paused
			play
		end if
	end tell
end appIsRunning`

**Comment by fantaaaaaa** [comment]
thanks @proactivematter.

unfortunately i dont have the MBP with touchbar anymore. however, i dont miss the touchbar to be hones.

thats my paus/play script which should work and should also allow to set a different icont with the "ergebnis" variable.

```
set ergebnis to "empty"

try
	try
		tell application "iTunes" to playpause
	end try
	tell application "iTunes" to set ergebnis to player state as string
	if ergebnis = "playing" then set ergebnis to "on"
	if ergebnis = "paused" then set ergebnis to "off"
	return ergebnis
on error
	set ergebnis to "error"
end try

```

**Comment by proactivematter** [comment]
Hey @fantaaaaaa! Ahh, really? What happened, if you don't mind me asking?

Thank you so much for your script! It works, but I still have one issue - I actually have media commands set up to show only when I press the OPT key, and when I do that, the script will run and play / pause. I wonder if there is a way to work around that?

**Comment by fantaaaaaa** [comment]
@proactivematter the laptop was company-owned and i changed jobs. i am using a 12" macbook without touchbar now :)

can't help you with the above problem though, sorry.

**Comment by proactivematter** [comment]
Fixed it! I'd actually saved another link in my bookmarks that explained a fix for this (though I can't figure out why). Here's the link: https://github.com/fifafu/BetterTouchTool/issues/838

Anyway, for future reference:

- set the ACTION to "Run Applescript in Background (Paste Text)" and put the actual code there.
- in the actual button Applescript, fill in with "return test" (if you don't do this, button size will not adhere to its specifications unless it is pressed at least once).

Thanks everyone!
