### ISSUE TITLE
Touchbar Apple Script Widget briefly shows "Apple Script" while working

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#387]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

https://www.dropbox.com/s/5b4wspctswtsyp9/trim.4855DC45-A6BA-4CC7-B736-7EB5C667A4E3.MOV?dl=0

While processing an apple script the widget will show a title "Apple Script" which results to some very un-mac-like visual glitch :) would it be possible to hide the title and show the button "icon-only" while processing? this would look much better i think :)

**What kind of Mac are you using?**
Macbook Pro Late 2016 w TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
TouchBar

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fantaaaaaa** [comment]
is there a chance to fix this? thanks! :)

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
