### ISSUE TITLE
Request: Touchbar and Flux

### ISSUE THREAD

**Issue by Afrovis** [fifafu/BetterTouchTool#388]
I'm a huge fan of BetterTouchTool for the touchbar!

I'm also an avid F.Lux user, so I was wondering if it could be possible to have an option to dim the all colors of the Touchbar, specifically the colors of the BetterTouchTool part. That would be really awesome, since my Touchbar could match the brightness of my display!

**Comment by fifafu** [comment]
It's probably possible but I think think you should request this at Flux. BTT doesn't influence the displays and I don't want to add something like this (can be very complex).
