### ISSUE TITLE
Problem in 2.02

### ISSUE THREAD

**Issue by sdboody** [fifafu/BetterTouchTool#389]
I have an assignment for a right bottom corner tap and right bottom corner click. Since updating click now also activates the tap option. This didn't used to be the case.

MBA 2013

MacBook Trackad

OSX 10.10.5

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
