### ISSUE TITLE
Click issues in 2.02

### ISSUE THREAD

**Issue by Seb9876** [fifafu/BetterTouchTool#390]
Since the last update, clicks (normal, double, right) are often not processed.
This is getting better when I deactivate BTT. However, the mouse gestures continue to work for some time after deactivating BTT for all apps.

BTT 2.02, OS X 10.11.6, Magic Mouse 2, MBP 13 retina early 2015

**Comment by shanesmith** [comment]
Same here on a MacBook Pro 2015 touchpad with macOS 10.11.6

I've tested back to BTT 1.999 and been finding the same issue....

**Comment by ryansommers** [comment]
Same. MBPr 2012 macOS 10.12.3

**Comment by fantaaaaaa** [comment]
Same here. MBP 2016 TB mac OS 10.12.13. Around 30-50 times a day, quite annoying :(

**Comment by fifafu** [comment]
Have you seen any pattern when this occurs for you?  Is your palm/thumb resting on the trackpad?

**Comment by fantaaaaaa** [comment]
Unfortunately not. Can not confirm any pattern or my palm being the problem when this happens. If this might be some connection to the palm i will track if this happens the next days and report back. any settings we should check?

**Comment by ryansommers** [comment]
It happens to me on a 1st gen Magic Mouse, no palm or other fingers touching.

**Comment by Rzah** [comment]
Issue still exists in 2.04, disabling and reenabling BTT temporarily fixes the issue but it seems to get worse over the next 24hrs until a reset is required again.

MacPro, 10.11.6, Magic Trackpad (Gen1) System set to never sleep.

**Comment by emanuelthedude** [comment]
I have the same problem. I'm using Android Studio and the right click does not work there but works fine everywhere else.
MacOS 10.12.3; BTT 2.04(603)

**Comment by jphalip** [comment]
I too am having issues as all my BTT right-click events recently stopped working (currently using BTT v2.07 on OSX 10.12.3). This might be related to #113.
