### ISSUE TITLE
Touch bar "Esc" doesn't support "shift" modifier

### ISSUE THREAD

**Issue by Aivean** [fifafu/BetterTouchTool#391]
#### Description

In the [app that I use](https://www.jetbrains.com/idea/) <kbd>Shift</kbd> + <kbd>Esc</kbd> performs certain action. It works fine if I use <kbd>Esc</kbd> from system panel (holding <kbd>Fn</kbd>), but doesn't work when I'm using <kbd>Esc</kbd> from BTT panel.

My guess is that BTT fires <kbd>Esc</kbd> key without modifiers when <kbd>Esc</kbd> is pressed on BTT panel.

**What kind of Mac are you using?**

<img width=250 src="https://cloud.githubusercontent.com/assets/2865203/22543904/7d1a2b84-e8e7-11e6-9e94-e3e955a69c58.png">

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch bar

**Which versions of macOS and BetterTouchTool are you running?**

BTT version 2.02

**Comment by koro-xx** [comment]
Same issue with other modifiers. Example: cmd+esc (which is a key combination used by Quicksilver).

**Comment by dploeger** [comment]
Or Ctrl+Alt. It's probably *all* modifiers. 😉

**Comment by fifafu** [comment]
This should be fixed in the latest alpha (v 2.282) https://bettertouchtool.net/releases/btt2.282b.zip
