### ISSUE TITLE
3 Finger Swipe Left/Right mislabeled

### ISSUE THREAD

**Issue by Squash019** [fifafu/BetterTouchTool#394]
#### Description the your "bug":
BTT shows mislabeled info for 3 finger swipe predefined actions for Page Back/Forward.

**What kind of Mac are you using?**
MacBook Air 13" early 2014

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.11.6 & BTT 2.02

**Other information:**
It's just a little bug, but the Left/Right labels for Page Forward/Backwards on 3 Finger Swipe are crossed. It can be clearly seen in this screenshot:
![BTT Screenshot](https://cloud.githubusercontent.com/assets/1979154/22554045/0f391508-e95f-11e6-8cf0-0b7bd173ba4b.png)

**Comment by fifafu** [comment]
Those actions mimic the three finger swipe gestures that where available in older versions of macOS. I think they are labelled correctly,moving from right to left goes back, moving from left to right goes forward).

**Comment by Squash019** [comment]
Actually, I think it's the opposite, moving from left to right should go back, moving from rigth to left should go forward, just like it does on Safari or iOS, right?

**Comment by fifafu** [comment]
Well, that everybody can decide for themselves. Personally I like it better if left to right goes forward as the touchpad is not a touchscreen.

Anyways, the action is still labeled correctly as it just tells the system to perform a three finger swipe left or right. Most (if not all) apps interpret a three finger swipe left to go backward and a three finger swipe right to go forward.

The good thing about BTT is, you can just swap it if you don't like that behavior :-)

**Comment by Squash019** [comment]
> The good thing about BTT is, you can just swap it if you don't like that behavior :-)

Yeah, that's one of the many awesome things about BTT.

Anyway, I guess I just misunderstood the labels. Thank for your patience ;)

**Comment by fifafu** [comment]
Well, it's complicated :-)
Maybe I'll just rename them to page back and forward as most users won't care that they actually perform a three finger swipe internally 😀 this would probably  solve the confusion.
