### ISSUE TITLE
Request: Additional "Hide" Options

### ISSUE THREAD

**Issue by HFTobeason** [fifafu/BetterTouchTool#395]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...: Under "Window Interaction" BTT offers "Hide All Windows".  I have not, however, been able to find any option to "Hide Front" or "Hide Others", both of which would be very useful. 

**What kind of Mac are you using?** MacBookPro Late-2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?** Keyboard

**Which versions of macOS and BetterTouchTool are you running?** 10.12.4 Beta (16E144f) and 2.02

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
you can just use the default macos shortcuts for that:
cmd+opt+h to hide others
cmd+h to hide front (only possible if more than one window is open)

You can of course assign those shortcuts to any gesture/click/button in BTT.
