### ISSUE TITLE
Idea to Show Battery %

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#399]
Can you make an apple script that returns the battery value after doing something like this:

```
do shell script "pmset -g everything | grep Cycles"
set x to the result
set battery to log word 5 of x
set check to word 1 of x
if check contains "No" then
	return "" 
else
	return battery
end if
```

The only thing I can't figure out is the `return battery` line. But it does give me the value of my battery percentage.

**Comment by pallavmac** [comment]
I got it!
do shell script "pmset -g everything | grep Cycles"
set x to the result
set battery to log word 5 of x
set check to word 1 of x
if check contains "No" then
	return word 5 of x & "%"
else
	return ""
end if

**Comment by fifafu** [comment]
Thanks for sharing! Maybe I should add a percent option to the battery widget because if I do it natively it will be a bit more performant than using apple/shellscript.

**Comment by pallavmac** [comment]
If you are not adding battery percentage because of a coding limitation then I understand. But otherwise it is extremely useful! Really hoping that it can be implemented.

**Comment by timothyBoye** [comment]
@fifafu Will be great to see this implemented natively for performance (I have an applescript battery indicator as well).

@pallavmac you don't need pmset -g everything, that's a lot of data you can get a battery percentage from pmset -g batt with far less data to then filter out. batt will output something like this:
Now drawing from 'AC Power'
 -InternalBattery-0 (id=3145827)	100%; charged; 0:00 remaining present: true

**Comment by nlpthk** [comment]
A battery percent widget would be perfect!

**Comment by nlpthk** [comment]
Hi @fifafu ! Any plans on adding the battery percent widget?

**Comment by mofirouz** [comment]
I've made this little script, might be useful for someone later on: https://gist.github.com/mofirouz/cbcfc1aa08561d2b8ad82363359bafd2

**Comment by fifafu** [comment]
The latest BTT alpha has added support for showing the battery percentage (activate in the widget options)
