### ISSUE TITLE
Touchbar "x" doesn't close menu

### ISSUE THREAD

**Issue by martindsouza** [fifafu/BetterTouchTool#4]
MBP 2016 13" Touchbar
macOS: `10.12.1 (16B2657)`
BTT: `1.9.4`

Clicking on the left "x" doesn't close the window. In the image it's the 2nd from the left icon (the top left one is from the Xcode simulator)

![snip20161203_6](https://cloud.githubusercontent.com/assets/2925726/20863843/1365d942-b997-11e6-90c0-bf5949e09447.png)

**Comment by pallavmac** [comment]
BTT version 1.9.5 fixes this

**Comment by fifafu** [comment]
Yes, this should work now. The only issue is that when using the close button, it's necessary to press the BTT icon twice to  bring back the Touch Bar. Hope to find a solution to that in a future update.
