### ISSUE TITLE
Add toggle dark mode feature 

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#40]
currently im using an applescript 

`tell application "System Events" to tell appearance preferences to set dark mode to not dark mode`

but for people that cant hack applescript this would be useful. 

i think this applescript only works on sierra though so maybe test it out

**Comment by sdeluxe** [comment]
How about..

tell application "System Events" to tell appearance preferences to set dark mode to not dark mode
tell application "System Events" to tell appearance preferences to set dark mode to dark mode

Switching back and forth ?

Works on El Capitan too :-)

**Comment by moshed** [comment]
@sdeluxe does the one i posted not toggle back and forth? if it works to toggle one way it should work for both

**Comment by fifafu** [comment]
Just added this as new action for the next version.
