### ISSUE TITLE
Tap to click doesn't work anymore

### ISSUE THREAD

**Issue by ferama** [fifafu/BetterTouchTool#400]
I use better touch tool only for the feature in subject but with the last update (2.02) it stopped working.

I'm using a Mac mini (late 2014) with Sierra 10.12.3 and a Magic Mouse

I've tried to remove and add again the gestures without success

P.S.
There is a way to install the older version?

**Comment by ferama** [comment]
Nevermind. Commenting here just in case someone have the same problem. I solved hitting Reset All Settings button in Advanced Settings Pane

**Comment by ferama** [comment]
Reopened this one
I need to "Reset All Setting" everytime my mac recover from sleep

**Comment by fifafu** [comment]
Please try if the current alpha version fixes your problem (v2.03)

**Comment by ferama** [comment]
It seems to work, thanks
