### ISSUE TITLE
Eclipse 4.6 now let you pinch in/out to resize font, BTT cannot disable it

### ISSUE THREAD

**Issue by alanwilter** [fifafu/BetterTouchTool#402]
I hate the fact that some application let you resize their font with a pinch in/out gesture, like in Chrome/Safari so BTT to salve me by disabling these gestures. However, it does not seem to work on Eclipse 4.6.2

**What kind of Mac are you using?**
Mac Book 

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Mac Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
Mac OSX 10.12.2

**Comment by fifafu** [comment]
Unfortunately this probably means that eclipse intercepts the pinch events at a lower level than other apps. In this case BTT can not block them :-(

**Comment by alanwilter** [comment]
I don't know if you're trying to address that somehow, but with BTT 2.04, now SqlDeveloper (based on Java), two finger clicks is playing havoc here. I have to disable BTT for this app.
