### ISSUE TITLE
2.02 (598)  BTT no longer responding to Magic Mouse Gestures

### ISSUE THREAD

**Issue by qwertypo** [fifafu/BetterTouchTool#405]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

None of my gestures are firing any more since latest update.  I have tried removing and adding back gestures.  I have tried reinstalling BTT.   I have reboot.  Live View shows gesture, but does not recognize gesture.

**What kind of Mac are you using?**

Mac Pro (Mid 2010)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**

10.11.6 with 2.02 (598)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
What kind of gestures/actions are you using? Could you attach an export of your setup (using the export button in BTT)?

**Comment by qwertypo** [comment]
Here is an export.  But strangely after everything I tried, it started working again today after the system woke from sleep.  Not sure how to recreate the problem, but it is working now and has survived a couple sleep/wake cycles.

On Sun, Feb 5, 2017 at 1:21 AM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:

What kind of gestures/actions are you using? Could you attach an export of your setup (using the export button in BTT)?

**Comment by lhenze** [comment]
Hi, I have the same problem; none of my gestures are working anymore. 
I have mac OS 10.11.6 with BTT 2.02 (598)

I also have tried removing and re-adding gestures, restarting BTT, restarting machine.

**Comment by jonathantelfer** [comment]
I have the same issue. Upgraded to 2.02 this morning and no Magic Mouse 2 gestures are working on my 2015 MacBook Pro 13". 

Also noticed that in the mouse settings it's showing the current mouse charge level at 0%.

**Comment by lhenze** [comment]
Hi, I rebooted the machine another time and that seems to have done the trick -- BTT now working as expected.

**Comment by Relequestual** [comment]
I rebooted and I'm still experiencing this issue.

I also seem unable see gestures being picked up from the trackpad also.

The "Live view" doesn't seem to pick up any gestures also.

OS X 10.11.6
BTT 2.02

**Comment by fifafu** [comment]
Hi Ben,

Could you check if 2.03 alpha fixes your issue? (Use the check for alpha version updates button in the BTT menu)

**Comment by Relequestual** [comment]
Hey Andreas, YUP that fixes it for me. Phew!
BTT seriously helps my workflows, so super thanks for your continued hard work! Hope it's paying off! =]

**Comment by jonathantelfer** [comment]
Fixed for me too. Incidentally if I set up middle click as the gesture with middle click as the action it doesn't display the action being triggered in live view, but it does work in applications.
