### ISSUE TITLE
past custom text pastes the wrong text *Bug

### ISSUE THREAD

**Issue by hoi1234567889** [fifafu/BetterTouchTool#406]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have made a touchbar button that first puts on a few keycombinations and then pastes a specific text. The problem is that a lot of times he doesn't paste that specific text but the last text i copied.

**What kind of Mac are you using?**
mb 15 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
touchbar

**Which versions of macOS and BetterTouchTool are you running?**
latest,latest

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
<img width="802" alt="screen shot 2017-02-04 at 00 55 38" src="https://cloud.githubusercontent.com/assets/25424737/22612999/e550ba72-ea74-11e6-8b05-08b726906aa0.png">

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
This should be fixed with the next update!

**Comment by fifafu** [comment]
Alpha version 2.021 hopefully fixes this.
