### ISSUE TITLE
Left/right three-finger swipes not registering with easy-to-trigger sensitivity

### ISSUE THREAD

**Issue by ah-** [fifafu/BetterTouchTool#408]
Hi Andreas,

I'm using BTT 2.02 (598) on a 2016 15" MBP running 10.12.3.
I love using BTT for browsing and have set 3-finger swipe left/right to switch between tabs and up/down to open/close tabs.

But when I try to set the sensitivity to really easy to trigger so I have to move my fingers less the gestures don't register properly. It only affects left/right swipes, up/down swipes work fine even with sensitivity set to 0.

To reproduce:
Open live gesture view.
Go into advanced trackpad settings, swipes and set three finger swipe sensitivity to 0. Up/down 3 finger swipes register, left/right swipes never register.
Increasing the sensitivity number to 0.1 makes the swipes register occasionally. Reverting to the default of 0.3 makes gesture recognition reliable, but requires large movements due to the larger trackpad.

I also noticed that if the gesture recognition does not work it tries to scroll instead.

It might have to do with the new trackpad/osx version, I had a similar sensitivity on my old 2013/10.11 MBP and it worked fine there.

Any help would be really appreciated, this seriously messes with my muscle-memory.

**Comment by fifafu** [comment]
Thanks for reporting, there definitely seems to be an issue here. I'll look into it!

**Comment by fifafu** [comment]
This will be fixed with the next alpha later next week.

**Comment by ah-** [comment]
This is working perfectly now, thanks a lot!
