### ISSUE TITLE
Update to 2.02 completely breaks touchbar support

### ISSUE THREAD

**Issue by xxyxxyxyx1** [fifafu/BetterTouchTool#410]
my specs: 13" with touchbar
<img width="318" alt="screen shot 2017-02-04 at 7 50 39 pm" src="https://cloud.githubusercontent.com/assets/25559220/22623532/3d8b846c-eb13-11e6-9758-80f5b1a71f6d.png">

I have one Global configuration for the touch bar, and everything worked nicely until this update. Now, the BTT buttons will not display no matter what app I am using; instead, whatever is selected in the system Keyboard settings (expanded control strip, app controls, etc) is displayed. The BTT buttons are only displayed if I modify one of the radio boxes in the BTT "General Touch Bar Settings" dialogue, but then it goes back to system touchbar once I switch applications. 

(That is, I open BTT and General Touch Bar Settings, and the system controls are still displayed. I then check or uncheck, for example, "Show ESC button on on left side of touch bar." Then my BTT buttons display correctly. I close that dialogue using "done," and close the whole BTT preferences app using the top left red button. Still working correctly, and the menu bar displays the name of another app, like Chrome. I then click anywhere, in chrome or on my desktop, and it's back to the system buttons.)

I've tried loading backups of my BTT settings from before the update, and the behavior is the same.

**Comment by fifafu** [comment]
Mhh maybe try updating to macOS 10.12.3 as Apple fixed quite a few issues with the update.

At this point almost all users have updated to 2.02 and the feedback so far has been very positive, I don't think this is a general problem.

Does this also happen when you create a new preset? Could you post a screenshot of your "General Touch Bar settings"?

**Comment by xxyxxyxyx1** [comment]
I now have the current macOS 10.12.3. The behavior has not changed. 

My general settings: 
![image](https://cloud.githubusercontent.com/assets/25559220/22634238/bed40db8-ebdc-11e6-9549-5d9c14f9e2b2.png)

I have tried toggling every checkbox in that menu, with no change in the problem behavior. I'll also note that if I have the "show ESC" unchecked, I get an ESC, and if I have it checked, I get two: 

![image](https://cloud.githubusercontent.com/assets/25559220/22634276/fd1c7c4a-ebdc-11e6-9205-10c6b659c354.png)

I have now tried creating a new preset with just one button set to "copy," and behavior is the same. I have also tried every combination of "Touch bar shows" and "Press Fn key to" in the Keyboard system preferences, and no change in the problem. 

Anything else I can try / send to you? 

Thank you for the fast response!

**Comment by xxyxxyxyx1** [comment]
I've just noticed that my multifinger gestures aren't working either (same computer). I use the following four gestures to change spaces, and change tabs in chrome:

https://cloud.githubusercontent.com/assets/25559220/22634276/fd1c7c4a-ebdc-11e6-9205-10c6b659c354.png)

None of the four gestures works now, and they did before the 2.02 update. I have not changed any system settings

When I open "live view," everything looks normal, with up to four jiggly circles where my fingers are. But when I try swiping left or right with 3 or 4 fingers, the "Last Recognized Gesture" field remains a series of dashes:

![image](https://cloud.githubusercontent.com/assets/25559220/22634998/40d4384a-ebe4-11e6-8988-1e49e590dbe3.png)

**Comment by fifafu** [comment]
Very weird. Could you maybe send me the logs saved in ~/Library/Application Support/BetterTouchTool/Logs to boastr.net@gmail.com? Maybe something crashes internally.

Also if possible try if re-downloading a fresh copy from my website fixes the issue, maybe something got corrupted. For testing purposes you could also try to add a new preset and check if the problem also appears with that preset.

**Comment by xxyxxyxyx1** [comment]
I will send the logs

I have tried a new preset, and deleted the app in the Applications folder and downloaded a new one. I didn't mess with any other files/folders, so it wasn't fully "reinstalling," if that's what I should try.

**Comment by xxyxxyxyx1** [comment]
Logs are sent. The issue with gestures persisted through restarting my computer, but this morning it works fine after the computer was asleep all night. 

At this point, I would rather take the time to remake my touchbar buttons and gestures if completely wiping BTT from my computer and starting over might help. Would you recommend this? If so, what do I need to delete other than the .app in the Applications folder?

Thanks

**Comment by fifafu** [comment]
you could try to reset the BTT settings using this terminal command:

"defaults delete com.hegenberg.BetterTouchTool"

Could you also send me an export of your preset?

**Comment by xxyxxyxyx1** [comment]
here it is, compressed into a zip so GitHub will accept it

[xxyxxyxyx1 preset 2-6-2017.zip](https://github.com/fifafu/BetterTouchTool/files/756096/xxyxxyxyx1.preset.2-6-2017.zip)

**Comment by xxyxxyxyx1** [comment]
I closed BTT and typed that terminal command. Reopening BTT gives me the welcome screen like I just installed it. Made a totally new preset with one button that does "command-C." I cannot get anything to display instead of the normal system command strip - the trick of toggling a settings button no longer gets it to temporarily function properly. 

-

I have now changed my system Keyboard settings to "touch bar shows app controls; press Fn to show control strip." Now there is behavior I have not seen before: whenever I focus the BTT preferences window, the BTT touch bar is displayed, with double ESC buttons. (I have not touched any BTT settings since the delete terminal command.) As soon as I focus another App (chrome, finder, or MS word), it goes back to the system contents:

![image](https://cloud.githubusercontent.com/assets/25559220/22670856/111ac992-ec80-11e6-9732-24710cdae52c.png)

![image](https://cloud.githubusercontent.com/assets/25559220/22670861/16280440-ec80-11e6-8895-bafcf29999a1.png)

**Comment by fifafu** [comment]
that's normal, BTT can only work correctly if the setting in system preferences is set to always show the control strip (+App controls)

Unfortunately I am currently still quite clueless what could cause this for you. If you want you can download previous versions from https://bettertouchtool.net/releases/ for now

**Comment by xxyxxyxyx1** [comment]
Really! Back before 2.02 with everything working well, I had my Keyboard settings to just App Controls. weird. 

This is usable now at least, thank you for helping.

**Comment by xxyxxyxyx1** [comment]
Actually, my trackpad gestures are back to not working at all. Four-finger swipe (set in BTT to change spaces) triggers the system action for two-finger swipe (browser forward/back buttons).

**Comment by fifafu** [comment]
Mhh, I don't think that's possible as BTT has always needed the control strip to display it's own bar.

**Comment by xxyxxyxyx1** [comment]
Perhaps I am remembering my Keyboard settings incorrectly. In any case, I was using the touch bar with only BTT content displayed across the whole bar, as in the above image: 

![image](https://cloud.githubusercontent.com/assets/25559220/22671566/cf7b4eea-ec83-11e6-9a57-1e8b7b9ec16d.png)

(minus the ESC buttons, this is what it looked like before 2.02)

Unless I am misunderstanding what you mean by "needed the control strip to display it's own bar."

**Comment by fifafu** [comment]
Hey,

yes even if you want to use the whole Touch Bar for BTT, the Control Strip feature must be enabled in System Preferences (because BTT uses the Control Strip APIs to show the BTT bar)
