### ISSUE TITLE
Bug: Update 2.02 is breaking it very frequently

### ISSUE THREAD

**Issue by anas2204** [fifafu/BetterTouchTool#411]
**What kind of Mac are you using?**
Macbook Pro 2016 with Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
BTT - 2.02
OSX - 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Before this update, BTT hardly crashed. But now, very often after the screen dims or goes to sleep, the BTT icon from touch bar is missing, and I have to restart BTT (often twice) to get it to properly work.

**Comment by jnanin** [comment]
Same problem here with a Macbook Pro Mid-2012 and 10.12.3

**Comment by fifafu** [comment]
Have you already tried to restart your system? This seems to work fine here and I haven't had any reports about something like that yet, however it could be some specific combination of settings that causes such behavior.

However I don't think there have been any changes in 2.02 that could cause this.

Could you post a screenshot of your "General Touch Bar settings" in BTT?

As an alternative you could assign the "Toggle BetterTouchTool Touch Bar" to a keyboard shortcut or gesture, then you may not need the icon.

**Comment by anas2204** [comment]
<img width="825" alt="screen shot 2017-02-05 at 5 48 42 pm" src="https://cloud.githubusercontent.com/assets/8613978/22630614/807b0014-ebcb-11e6-9e88-42ce45859c2d.png">

These are me General Touch Bar Settings.
I'll restart the system, and post again if it continues to persist.

**Comment by fifafu** [comment]
If it persists, please let me know if disabling "Allow system apps like iTunes or XCode to replace the BTT Control Strip icon" improves the behavior.

**Comment by anas2204** [comment]
With or without the specified setting, it is crashing sporadically when the laptop wakes up from sleep. On my laptop, this was EXTREMELY rare before the 2.02 update. If you want, I can export my settings and put it here.

**Comment by jnanin** [comment]
Hi, I just woke up my computer and it crashed again. Checking the system.log file I found this:

`Feb  6 11:31:36 *username* com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.230592[18853]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[21049]`
`Feb  6 11:31:38  *username* BetterTouchTool[21049]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked`
`Feb  6 11:34:20  *username* com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.230592[21089]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[21049]`

**Comment by anas2204** [comment]
I notice that it's happening almost 50% of the times that my laptop wakes up from sleep! Is there any way that I can give you more information or logs?

**Comment by anas2204** [comment]
@fifafu The issue still persists. It's crashing very frequently when laptop wakes up. Any other reports of the same? Is there a way I can send you application logs?

**Comment by anas2204** [comment]
Sometimes when I restart, it also renders the Touch Bar like this:
<img width="1085" alt="touch bar shot 2017-02-09 at 10 47 51 am" src="https://cloud.githubusercontent.com/assets/8613978/22790848/7f1c70da-eeb5-11e6-8585-1cbeb45e1b4e.png">

**Comment by fifafu** [comment]
If this is still happening, please create a new issue. (I'm currently closing many old issues)
