### ISSUE TITLE
Touch Bar Bug: Causes a globe to overtake application controls

### ISSUE THREAD

**Issue by aaronweewee** [fifafu/BetterTouchTool#413]
Long pressing certain buttons on **non global icons** will result in the non global portions of the touch bar to be replaced with a globe emoji. It also only seems to affect the buttons that have been sticked to the **left side** of the touch bar 
Solution: Restart BTT

Here are the screen shots of the normal touch bar with marked icons that causes the issue. 

<img width="1085" alt="touch bar shot 2017-02-05 at 10 42 10 pm" src="https://cloud.githubusercontent.com/assets/24728980/22627046/90f47b94-ebf5-11e6-898a-3040e196e670.png">
<img width="1085" alt="touch bar shot 2017-02-05 at 10 42 18 pm" src="https://cloud.githubusercontent.com/assets/24728980/22627048/92fa251a-ebf5-11e6-86fa-6c380f0e87fb.png">

Here is the screen shot of the globe bug
<img width="1085" alt="touch bar shot 2017-02-05 at 10 42 29 pm" src="https://cloud.githubusercontent.com/assets/24728980/22627052/9d05a20a-ebf5-11e6-92e2-0cbdc30e0bc3.png">
This globe will remain there until BTT is restarted. The globe does nothing but can be pressed

Here is the export of my Touch Bar settings
[Final BTT 1.2.zip](https://github.com/fifafu/BetterTouchTool/files/753042/Final.BTT.1.2.zip)

I've only set up workflows for **spotify** and **chrome**. Thats where the bug would occur. I hope the information I've given is good enough :))
BTT 2.02
Mac OS 10.12.3 | 13" Pro w Touch Bar
Thanks in advance :))

**Comment by fifafu** [comment]
Thanks for the details! I'm tracking it in #412

**Comment by MiracleBlue** [comment]
If I may go off-topic for a second: omg your buttons!  Look at them!  Puts my basic setup to shame :)
