### ISSUE TITLE
Unable to add new drawings

### ISSUE THREAD

**Issue by aneurofen** [fifafu/BetterTouchTool#414]
I'm on a MacBook Pro (Retina, 13-inch, Late 2013) with MacOS Sierra (10.1.2) using BetterTouchTool 2.02 but have had issues with adding new drawings for a while now. These issues occur when using my trackpad (I haven't attempted this with any other external input devices).

I can trigger the action for recording drawings when outside of the bettertouchtool preference pane, and nonetheless draw whatever I'd like in that recording window (e.g. an S). However, when trying to add a new drawing within the bettertouchtool pane, all I can 'draw' is a dot (see screenshots). I'm not sure what I'm doing wrong here. I've followed the instructions several times but to no avail. 

I'm thinking this might have something to do with the native OS trackpad settings I have setup?

Would love if someone knew the solution to my problem, I feel I already have too many gestures setup!

Thanks!!

Aidan
<img width="1006" alt="screen shot 2017-02-05 at 3 46 30 pm" src="https://cloud.githubusercontent.com/assets/19768301/22627413/a27d746e-ebba-11e6-8dca-d29660336be0.png">
<img width="1280" alt="screen shot 2017-02-05 at 3 51 35 pm" src="https://cloud.githubusercontent.com/assets/19768301/22627434/14e16a42-ebbb-11e6-8241-8ad37e9efb8d.png">

**Comment by fifafu** [comment]
That's weird, are you sure you are clicking the trackpad while drawing?

Is BetterTouchTool activated in System Preferences => Security & Privacy => Privacy => Accessibility?

**Comment by aneurofen** [comment]
Hi Andreas,

Thank you for such a quick response! 

I am definitely clicking the trackpad while drawing.

Within BetterTouchTool, when trying to add a new drawing, my trackpad movements aren’t recognized unless I click down on the trackpad. However, no matter if I click and hold and raw or click and then proceed to draw, the drawing is not recognized. Interestingly, outside of BetterTouchTool I’m able to both initiate drawing recordings and make a drawing (without clicking, just proceeding from my ’Start recording drawing’ gesture.

And BetterTouchTool is activated in that preference pane, yes.

**Comment by fifafu** [comment]
Strange! Would it be possible to get an export of your BTT setup? (using the export button).
You can also send it to me via email in case you don't want to attach it here (boastr.net@gmail.com)

**Comment by aneurofen** [comment]
I feel like the issue might be with the trackpad settings I have turned on in System Preferences?

I currently have no known issues of conflict between BetterTouchTool and my native trackpad preference settings, but perhaps this is one?

I have all settings on asides from: ‘Look up data detectors’, ‘Mission Control’ and ‘App Expose’

**Comment by fifafu** [comment]
Mhh, I'm not sure what setting could interfere with this.

Thanks for sending your setup, "unfortunately" the issue seems to be somewhere else. I'll test on an older Macbook tomorrow. Maybe it's something with force touch and non-force touch trackpads.

**Comment by aneurofen** [comment]
Great! Thanks for getting back to me so quick. 

Let me know if you find anything or if there's anything else to try.

**Comment by SteveJobzniak** [comment]
MacBook Pro 2010 with non-force touchpad: I can create new gesture drawings in the "add new drawing" window. No problem.

**Comment by blackbox33** [comment]
Having the same issue as the topic. I cannot add new drawings. The actual gesture never gets saved. 

![untitled](https://user-images.githubusercontent.com/29488559/27237579-ac373992-5297-11e7-809d-2b3ae502b0d5.gif)

MacBook Pro 15-inch
macOS Sierra v 10.12.5
BTT v2.20 (641)
External USB mouse

**Comment by fifafu** [comment]
Unfortunately I'm still unable to reproduce this issue. 

If possible please reproduce the problem, then open the BTT Preferences and go to the About tab. Click the "Export Debug Info" button. This will create a folder called "BetterTouchToolDebug" on your Desktop. Would be great if you'd send me the contents of that folder to boastr.net@gmail.com.

**Comment by fifafu** [comment]
Just in case somebody else runs into this issue: I think it's important you do the drawing by pressing the LEFT mouse button. Apparently some users had been using other mouse buttons and the recording screen doesn't like that :-)

**Comment by SteveJobzniak** [comment]
@fifafu Hehe. Funny. What madmen would draw with other buttons?

But I guess the code can be updated to either support other buttons or block them entirely?
