### ISSUE TITLE
[Question] Config management

### ISSUE THREAD

**Issue by gitetsu** [fifafu/BetterTouchTool#415]
Hi.
Is it safe(okay) to upload exported config file(NOT the license) to github?

P.S. Thank you for creating this great product!

**Comment by fifafu** [comment]
Yes (as long as your actions don't contain private data)

I'll soon add a better export system that gives you more control over what shall be exported and what not.

**Comment by gitetsu** [comment]
Thank you for your quick reply!
It's so exciting. 👍
