### ISSUE TITLE
Show text on touchbar

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#42]
#### Description of your feature request:
Can you have a really cool feature where maybe through a keyboard shortcut, it shows copied text, on the touchbar. This is super useful for if we need to copy text from one place to another but either can't paste or need to type it. Please tell me if this is possible because it would be immensely useful!

**Comment by ddqp** [comment]
yes, it's really practical!

we would like also to have a kind of information dynamically show on touchbar

**Comment by timothyBoye** [comment]
@ddqp and @pallavmac In the meantime you can add a widget set it to "Run Apple Script" and click advanced configuration. In the big box underneath where you enter a name for the widget type "return (the clipboard)" without the quotes and then edit any other settings you like and hit save, that widget will now show the contents of the clipboard so when you copy text it'll show in the widget.

**Comment by ddqp** [comment]
got it, cool!!!
thanks for your help!

**Comment by fifafu** [comment]
There will soon be a integration of BTTs Clipboard Manager in the Touch Bar. Thus I'm closing this issue. For now please use the method described by timothy!
