### ISSUE TITLE
Docs button gives 404 page

### ISSUE THREAD

**Issue by thunderrabbit** [fifafu/BetterTouchTool#420]
#### Description of your bug/question/feature request...:

Clicking docs button should show documentation instead of 404 page.

**What kind of Mac are you using?**

old Macbook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

N/A?

**Which versions of macOS and BetterTouchTool are you running?**

OS X 10.12.3    BTT 2.02

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

![screen shot 2017-02-06 at 4 44 13 pm](https://cloud.githubusercontent.com/assets/21597/22638599/762d904c-ec8c-11e6-8006-1480642e6af4.png)

**Comment by fifafu** [comment]
Thanks for reporting! Should be fixed now.

**Comment by thunderrabbit** [comment]
Fix confirmed!  Thank you.
