### ISSUE TITLE
Mirroring magic trackpad is no longer working

### ISSUE THREAD

**Issue by ming-jen** [fifafu/BetterTouchTool#422]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
The magic trackpad mirroring was working until the 4th of Feb, 2017. Now it does not work at home with MacMini and at work with MacBook Pro. I have restarted the machine with no effect. This coincides, roughly, with when I tried to get betterTouchRemote to work, but never got the cursor to work.

**What kind of Mac are you using?**
Macbook Pro and Macmini
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
magic trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3 on MacOS and version 2.02 for BTT.

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports
I have latest version and have restarted the machine.

**Comment by hugothebear** [comment]
**Description of your bug/question/feature request...:**
To confirm the **[Mirror complete Magic Trackpad orientation for "upside-down" usage]** selection no longer works after I experimented with BTT Remote on my iPhone 5s.

**What kind of Mac are you using?**
iMac (21.5-inch, Late 2013)

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Trackpad A1339

**Other information:**
BTT version 2.02
Have tested uninstalling BTT app including all related files & prefs and removing BTT Remote from iPhone. Reinstall BTT only and relicensing does not fix this issue.

**Comment by fifafu** [comment]
I don't think this can be related to BTT Remote, maybe the update to macOS 10.12.3 killed it. I'll check if I can bring it back.

**Comment by hugothebear** [comment]
Did a downgrade to my older 1.963 version from TimeMachine FTW :-) Everything working again.
Bye the way my current OS is OSX 10.12.3 FYI.
Good luck with debugging the latest version, I'll keep an eye out for info. All the best!

**Comment by ming-jen** [comment]
Just did the same, pull version 1.963 out of Time Machine and it is working. Thanks for the info.

**Comment by plaxdan** [comment]
Confirmed. I have BTT 2.02 on MacOS 10.12.3 and paid for the licence just for this one capability! Can I download an older version until a fix is in?

**Comment by fifafu** [comment]
Ahh, does this mean you didn't have any gesture configured in BTT?

(The new version disables the trackpad functions if that's the case). I'll add a fix for that with the next alpha.

**Comment by plaxdan** [comment]
> Ahh, does this mean you didn't have any gesture configured in BTT?

Correct. The only setting I changed was to check this box:

![btt](https://cloud.githubusercontent.com/assets/382348/22746580/76626f5a-ede1-11e6-935c-73d31f3c7132.png)

**Comment by fifafu** [comment]
should be fixed in v2.03 alpha!
