### ISSUE TITLE
[question] Global for All Applications except Windows Apps (Parallels)

### ISSUE THREAD

**Issue by kenbailey** [fifafu/BetterTouchTool#423]
The app works great, but I'm attempting to use it to remap command to ctrl key for all my mac applications and leave my windows applications as is. I would like to basically use the Global setting for all applications except those running under parallels. Is there a way to exclude applications from Global, or create a "Global (Non-Parallels)" group?

The only way I've found to handle this thus far is to explicitly identify each of the Mac apps and copy the configuration settings. The down side is that I have lots of duplicated shortcut settings and it is causing a performance hit as it pauses when switching between applications (so I can't immediately drag a window when clicking on it for instance).

Running on a MacBook Pro 2016 15" with touchbar (2.9 GHz, 4GB graphics card model) and macOS Sierra (10.12.3).

**Comment by fifafu** [comment]
Unfortunately there is currently no other way to do this in BTT.

However as far as I remember Parallels lets you set the modifier mapping, doesn't it?

So you could just change it for all Mac apps in System Preferences => Keyboard => Modifiers, and then remap it in parallels.

![image](https://cloud.githubusercontent.com/assets/8820811/22845259/09272676-efe2-11e6-838c-51f286646134.png)

**Comment by kenbailey** [comment]
Thanks for the reply and additional information. I've went down the road of remapping the keys via OS X and then using the Parallels to adjust. I found a few scenarios and key strokes that I couldn't get to work. I may try that approach again. 

The last update 2.04 (603) made a big improvement on performance as I have a lot of shortcuts defined currently. Thanks!
