### ISSUE TITLE
Mission Control bugs with 2.021

### ISSUE THREAD

**Issue by philwhiles** [fifafu/BetterTouchTool#425]
#### dragging apps into spaces in Mission Control has stopped working with 2.021 update
Also find that cannot add new space with '+' in mission control.
Quit BTT and problem gone.
Is reproducable.
 

**What kind of Mac are you using?**
Mid 2014 15" MBP

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad and magic mouse v1

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2
2.021

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

could you check if 2.023 alpha fixes the issue?

best,
Andreas

**Comment by philwhiles** [comment]
Andreas,

Wow that was quick. 
Yes - a quick test seems to indicate you have fixed it. 
Will give it a more detailed going over later, and will let you know if I find any probs. 

Thank you!

Phil
