### ISSUE TITLE
2.021 causes issues with click+drag and control+click

### ISSUE THREAD

**Issue by frogworth** [fifafu/BetterTouchTool#426]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Using version 2.021, I find clicking and dragging often fails - I need to try multiple times, and often it registers as a double click instead. This is using a Magic Trackpad but also the laptop trackpad.

Also, I found frequently when trying to select multiple files within Parallels - using ctrl+click - I was getting the secondary mouse click (i.e. right-click) rather than multiple selection.

Downgrading to 2.02 resolves both issues.

**What kind of Mac are you using?**

Late 2016 MacBook Pro with Touchbar.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackpad, Magic Trackpad, keyboard

**Which versions of macOS and BetterTouchTool are you running?**

MacOS 10.12.2
BTT 2.0.21

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

could you check if 2.023 fixes the issue?

Best,
Andreas

**Comment by DanDilla** [comment]
Hi,

got the same Problem, especially the Drag&Drop from the expandable Downloads folder (directly opens the file) didn't work for me.
 
Also in Safari when I click the url/search-field and the bookmarks open, I'm not able to click on them. Just nothing happens when clicking on them. 

Both problems solved by going back to 2.02.

Sorry, but I didn't find 2.023 anywhere yet, where can I get it to try it out?

Daniel

**Comment by fifafu** [comment]
@daniel, it should show whem clickjng the "check for alpha version updates" item in the BetterTouchTool menubar item menu.

**Comment by DanDilla** [comment]
Jep, thanks for your quick reply, my fault.

**Comment by frogworth** [comment]
Thanks Andreas, yes it does seem to fix these issues - all good now!
