### ISSUE TITLE
Option-click Touch Bar groups broken with update

### ISSUE THREAD

**Issue by kerim** [fifafu/BetterTouchTool#427]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Before the latest update (2.02) I had Touch Bar groups that only appeared when I pressed down the option key. Those groups still appear, but clicking on them no longer opens the group to let me see what is inside.

**What kind of Mac are you using?**
Late 2016 MBP

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.3
BTT 2.02

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

I restarted the system. Problem still persists.

**Comment by fifafu** [comment]
Ah that's interesting.
It's because the buttons inside of the group don't have the modifier key assigned, thus BTT doesn't load them. I'll think about I can handle that case.

For now you can workaround it by assigning the modifier to all buttons inside of the group.

**Comment by kerim** [comment]
Thanks, this solution sort of works, but now it is kind of weird in that once I click on the group, the sub-items in the group won't go away unless I select one of them. It did not work this way before...

**Comment by fifafu** [comment]
Well, they go away when you press the close button, don't they?

I have made a little change in v2.03 alpha which makes touchbar buttons in groups show up, even if they don't have modifier keys assigned - however only if none of the buttons in that group have modifiers assigned.

**Comment by kerim** [comment]
Thanks. This is working better now. 

But am I wrong to remember that it used to behave differently if one chose not to select something? The "close button" seems to close BTT altogether, not just the current group. I have to tap the BTT icon to get back to the default BTT touch bar view....

**Comment by fifafu** [comment]
Ah, I don't mean the global close button. Each group should have it's own close button (it's added like a normal group button when creating a new group)

The behavior was different previously, but only because groups ignored modifier keys completely, which was not desired. Also back then touching any modifier key closed the current group. There are many bug reports about the old behavior here, the new one seems to work much better for most.

**Comment by kerim** [comment]
I see. The close group button seems to be new with the update? I was able to add it to my existing groups, so now it works as expected. Thanks.
