### ISSUE TITLE
Write certain text or activate a key sequence

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#43]
#### Description of your feature request:
Could you add key sequences to BTT. This would work in two ways:
1. Where when triggered, the action would write a predefined text (very useful for people who write things like their email address a lot). 
2. A sequence of keyboard actions are triggered such as cmd-tab + "text" + cmd-tab + cmd-q. Just like you can record key sequences to trigger an action, this would execute a key sequence once an action is triggered. 

This is I think an extremely useful feature. Would you be able to add it soon? I would find it super useful for coding where I can just tap on the touchbar to make it write common coding terms or if I need to copy alternating lines from one file to another, then the key sequence can do it for me! 

Hope this will be something possible. Thanks for all the features so far!

**Comment by moshed** [comment]
in regards to writing predefined test you can do that through applescript
```
delay 0.2
tell application "System Events"
	keystroke "email@test.com"
end tell
```
note: the delay is so your not pressing whatever modifier keys you used to trigger the script while its typing and potentially firing of multiple key combinations so adjust the delay as neccessary.

in regards to your 2nd request you can also carry that out through applescript. use  [this page](http://macbiblioblog.blogspot.com/2014/12/key-codes-for-function-and-special-keys.html) to find out key codes. 

```
delay 0.2
tell application "System Events"
	key code 0 using command down
	key code 8 using command down
	key code 124
	key code 36
	key code 9 using command down
end tell
```
that script does `⌘-a`, `⌘-c` `→` `Return`, `⌘-v`

**Comment by fifafu** [comment]
Have you already seen the "paste custom text" predefined action? It should allow you to insert any text.

Also you can use the "attach additional action" button to trigger many keyboard shortcuts in sequenxe.
