### ISSUE TITLE
2.02 broke everything

### ISSUE THREAD

**Issue by snickers2k** [fifafu/BetterTouchTool#430]
nothing is working anymore for me .. not a single thing i have set up
can't understand you.. you push alphas to normal users and you don't even have old-versions to downgrade to on your site.. 
update: now it's working without me having done anything.. omg

**Comment by fifafu** [comment]
2.02 is not an alpha.

It had been tested for weeks and thousands of users have already upgraded to it. Bugs will always be possible, this is why I have this issue tracker.
