### ISSUE TITLE
BTT 2.023 (601) Drawings - visible rectangle with each right click under mouse pointer

### ISSUE THREAD

**Issue by maziman84** [fifafu/BetterTouchTool#431]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
When right click while having dravings gestures enables i see red dot and dark rectangle

**What kind of Mac are you using?**
Mac mini (Late 2014)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**
MacOS 10.12.3 (16D32) 
BTT 2.023 (601)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
![screenshot 2017-02-08 08 02 47](https://cloud.githubusercontent.com/assets/15727395/22726688/1ed2bd6e-edd5-11e6-85fe-ae7978efdb5c.png)

**Comment by fifafu** [comment]
Hey,

That's the new right -click drawing functionality which is enabled by default during the alpha phase.

You can disable it in the advanced settinga in the drawings tab (there you can also change the background color to transparent)

**Comment by maziman84** [comment]
Hey, thanks for quick reply. Problem resolved with transparency change :-)

Michal

**Comment by fifafu** [comment]
You can also choose to not highlight the start point in those settings :-)

**Comment by maziman84** [comment]
Thanks for tip.
Can you advise how to add modifier key to start the gesture? Like start gesture while holding “control” key. I cant add it to existing drawing.

Michal

**Comment by fifafu** [comment]
@maziman84 that's not yet possible, but I'll add support for that soon.

**Comment by maziman84** [comment]
Ok thanks

**Comment by fifafu** [comment]
Or well, it would work if you set up a key sequence like this in the keyboard section:

![image](https://cloud.githubusercontent.com/assets/8820811/22727814/3be7879e-eddb-11e6-8cf7-ede7072319e1.png)

![image](https://cloud.githubusercontent.com/assets/8820811/22727816/40d5673a-eddb-11e6-844e-ec00f39e756a.png)

However then it will always draw while holding control, right mouse button can not yet combined with this.

**Comment by maziman84** [comment]
Got it, thanks for that tip :-)
