### ISSUE TITLE
Issue Prerelease/Alpha Finder Affected

### ISSUE THREAD

**Issue by jacobmilli10** [fifafu/BetterTouchTool#432]
Topic: Alpha Bug Issue Notice/Information (Bug Report For Future Stable Releases)
System: 2016 MacBook Pro TB 15in
Issue Affects: Finder App and System Navigation 
Versions: Affected Version 2.023 Alpha/ Stable Version Fixes It 2.02

Description:
I just have a bug report for you kinda a serious one with alpha. When using your app in the background on my Macbook pro (2016 TB 15in). it seems that if I have better touch tool running in the background without menus bar and dock icon showing the app somehow affects finder on opening folders, and resizing windows and other resizing items. It causes me to have to click alot more to open a folder as in normal it only takes 2 clicks to open a folder, to making me have to click 10 or more times to open a folder. I have no idea what would cause this behavior from In the app to do this. Also I only use better touch tool to set a keyboard shortcut to refresh the touch bar (thermal command) thats the only thing I do with the app. So I uninstalled the Alpha and downgraded to the stable version and it fixed my issue. Its weird that better touch causes that issue. (I isolated the issue though safe mode and found it was alpha better touch tool causing the problem).

**Comment by fifafu** [comment]
Are you sure this happened with 2.023? Other users had reported a similar problem with 2.021 but said it was fixed with 2.023

**Comment by jacobmilli10** [comment]
Maybe It is I just assumed it was that version I don’t remember updating to
another version in the past day or two. But okay If you have already heard
of the issue everything is good I just wanted to pass to you info that that
is happening.
Thank you


On February 8, 2017 at 5:32:14 AM, Andreas Hegenberg (
notifications@github.com) wrote:

Are you sure this happened with 2.023? Other users had reported a similar
problem with 2.021 but said it was fixed with 2.023

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fifafu/BetterTouchTool/issues/432#issuecomment-278303482>,
or mute the thread

**Comment by fifafu** [comment]
Yep, thanks for reporting!
Would be great if you could try 2.023 again at some point to make sure it's not another issue you encountered on your machine.

I'm closing here for now, but if you encounter the issue again just reply again.

**Comment by jacobmilli10** [comment]
Okay I will Ill report if I have another issue



On February 8, 2017 at 5:37:04 AM, Andreas Hegenberg (
notifications@github.com) wrote:

Yep, thanks for reporting!
Would be great if you could try 2.023 again at some point to make sure it's
not another issue you encountered on your machine.

I'm closing here for now, but if you encounter the issue again just reply
again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fifafu/BetterTouchTool/issues/432#issuecomment-278304393>,
or mute the thread
