### ISSUE TITLE
Magic Mouse gestures not working

### ISSUE THREAD

**Issue by Zedliminal** [fifafu/BetterTouchTool#433]
#### Description of your bug/question/feature request...:

**What kind of Mac are you using?**
iMac 27" (Late 2013)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**
OS X 10.9.5 Mavericks

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Recently formatted, made a backup of my settings before doing so, installed BTT and imported them. Nothing happens when trying to trigger any gesture using the Magic Mouse. I've restarted a couple times already.

I'm up to date, on version 2.02 (598)

**Comment by fifafu** [comment]
hey, 

have you already tried to reconnect your mouse by powering it off an on again?

Alternatively try this alpha version, I think it might improve Magic Mouse handling: 
http://bettertouchtool.net/releases/btt2.023.zip

**Comment by fifafu** [comment]
Should ne fixed  with current  version.

**Comment by Zedliminal** [comment]
Sorry for taking long in answering back, the problem actually fixed itself after a while, for whatever reason.. thanks for your help!
