### ISSUE TITLE
BetterTouchTool injects additional mouse events in browsers

### ISSUE THREAD

**Issue by somebee** [fifafu/BetterTouchTool#435]
I'm on 2.021 with TouchBar MBP 15"

Been debugging a strange web-issue for a while, until I discovered that it is caused by BetterTouchTool.

See codepen: [Codepen example](http://codepen.io/anon/pen/VPGEJg). Open the console and then tap the "Tap here" div. When BetterTouchTool is enabled, an additional mouseup-event is triggered BEFORE each mousedown.

If this is not fixable, is there any way I can completely disable mouse-handling in BTT and just use it for keyboard shortcuts and touchbar support?

**Comment by fifafu** [comment]
Hey,

Please try upgrading to 2.023, I think this might have been a bug in the 2.021 alpha

**Comment by somebee** [comment]
Thanks, that worked :)

Btw, is there any way to simply disable all mouse-handling? I _love_ BetterTouchTool for the touchbar but I don't need to be able to tweak any mouse or trackpad behaviour.

**Comment by fifafu** [comment]
@somebee unless there is a bug like this one it is basically disabled when you haven't configured anything for it
