### ISSUE TITLE
Add Widget to Mute Microphone

### ISSUE THREAD

**Issue by BalassaSamuelson** [fifafu/BetterTouchTool#436]
I wanted to add a widget that mutes and unmutes my microphone and returns the current input level (I saw that a dependent icon is not possible yet)

This is the Apple script I was using:

`set inputVolume to input volume of (get volume settings)`
`if inputVolume = 0 then`
	`set inputVolume to 100`
	`return inputVolume`
`else`
	`set inputVolume to 0`
	`return inputVolume`
`end if`
`set volume input volume inputVolume`

However, pressing the widget causes the microphone to alternate between inputVolume 0 and 100. Where did I go wrong?

**What kind of Mac are you using?**
MacBook Pro 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.4, 2.023

**Comment by fifafu** [comment]
I think I would do it like this:

```AppleScript
if input volume of (get volume settings) = 0 then
	set level to 100
else
	set level to 0
end if

set volume input volume level

return input volume of (get volume settings)
```

**Comment by BalassaSamuelson** [comment]
It's still jumping between 100 and 0, although I only pressed the widget once.

**Comment by fifafu** [comment]
ah sorry I just realized you were using it as a touchbar widget :-)
Those are currently executed every few seconds.

With one of the next versions I'll add an option to execute a script on button press instead of time based.

**Comment by BalassaSamuelson** [comment]
Cool. If https://github.com/fifafu/BetterTouchTool/issues/386 is also available then, this could be a really useful widget

**Comment by BalassaSamuelson** [comment]
Any updates on this one?

**Comment by leovogel** [comment]
+1 for execute on button press instead of time based. Would greatly appreciate this feature.

**Comment by djohnsen** [comment]
See my horrible time-based hack on #1331 that accomplishes this.

**Comment by fifafu** [comment]
You can already execute scripts on button press by assigning the predefined action "run apple acript" to the widget.  They will also update the display of zhe widget based on the return value.
In addition you can still have the interval based execution, but if you don't need that just set the interval to 0.

**Comment by AliKarpuzoglu** [comment]
For anyone that sees this and wants to use the microphone mute toggle: I put in a line to display a notification. The code needs to be run as apple script, **not in background**.

`if input volume of (get volume settings) = 0 then
	set level to 100
	display notification "mic on" with title "Microphone Toggle"
	
else
	set level to 0
	display notification "mic off" with title "Microphone Toggle"
end if

set volume input volume level

return input volume of (get volume settings)`
