### ISSUE TITLE
Force Touch tracking on corners collide with external mouse click events

### ISSUE THREAD

**Issue by fabien88** [fifafu/BetterTouchTool#437]
#### Description of your bug/question/feature request...:
Hi
In BTT, I registered an event for tracking force touch on upper left corner. It works well, except that sometimes my finger is touching the corner of the trackpad (only touching it, no pressure & no click) and then if I click with my external mouse at the same time, the system completely ignores the click.
It seems that the external mouse events are ingored during 3 seconds after detecting a touch on the trackpad.

Thank you for your support

**What kind of Mac are you using?**
2016 with TB

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Force touch track pad and a logitech mouse

**Which versions of macOS and BetterTouchTool are you running?**
12.3 & BTT 2.023

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
unfortunately BTT can't see where the click is coming from. Thus if you use corner clicks BTT needs to block all clicks that happen while touching the corners of the trackpad, otherwise every corner click gestures would also produce a normal click.

Currently this can't be changed, only way to fix it is to remove the corner click gestures.

**Comment by fabien88** [comment]
Thank you for your answer. But I think there's a bug somewhere that can be fixed, because sometimes the external click become disabled forever even with no fingers left on the trackpad :( (I have to touch the trackpad again to make external mouse work again. Sometimes it is disabled 3 seconds after a touch occurs. Restarting BTT solve the problem : the click event is enabled instantly after finger has left the touch zone. But after a while, the problem happens again.
