### ISSUE TITLE
4 Finger click is triggering 3 Finger clicks

### ISSUE THREAD

**Issue by Blueyo12** [fifafu/BetterTouchTool#440]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
After updating to Bettertouchtool version 2.02 my 4 finger clicks is triggering 3 finger clicks very often. It usually happens when my right hand fingers are vertical with my index finger placed on the bottom of the trackpad and sometimes happens when my fingers are horizontal, however this did not happen before the update. I have been using this setup for about 5 years or longer with my 2009 Macbook Pro and currently with my 2015 Macbook pro without any problems until now.

**What kind of Mac are you using?**
Mid 2015 15 inch Macbook pro
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
The Macbook Pro's trackpad

**Which versions of macOS and BetterTouchTool are you running?**
MacOs Sierra 10.12.2 and Bettertouchtool version 2.02 (598)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Does disabling thumb recognition fix this for you?

![image](https://cloud.githubusercontent.com/assets/8820811/22757720/40308fb4-ee4c-11e6-817e-0a32dfb14a1e.png)

**Comment by Blueyo12** [comment]
Thank you for the quick reply! I have tried settings but it does not fix the problem. This is what the program is registering my fingers as

<img width="504" alt="screen shot 2017-02-08 at 1 20 56 pm" src="https://cloud.githubusercontent.com/assets/25647653/22758063/e58f5f4e-ee01-11e6-951f-92aa1c734ddd.png">

**Comment by fifafu** [comment]
Weird, could you send me an export of your gestures (boastr.net@gmail.com) ? I can't seem to replicate it on my current machine but will try on an older MacBook tomorrow.

**Comment by Blueyo12** [comment]
I just updated to the Alpha 2.023 you suggested and the problem still occurs. I tried Bettertouchtool version 1.963 on a 2012 Macbook Pro with my fingers out of range and the 4 finger click still registers. 
![screen shot 2017-02-08 at 1 51 18 pm](https://cloud.githubusercontent.com/assets/25647653/22759271/aa278cc4-ee06-11e6-96fa-dc66a74259ec.png)

**Comment by fifafu** [comment]
would be great if you could also test v2.03 I just uploaded (make sure to disable thumb handling and thumb filtering)

Starting with v2.0 BTT uses information given by the system to check whether a finger is valid or if it should be ignored. I think when holding your fingers like this maybe the system thinks those are invalid touches (for most users they would probably be invalid/not wanted).

With 2.03 I disable that functionality if thumb handling and thumb filtering are disabled.

**Comment by Blueyo12** [comment]
Wow thank you so much for the update, the problem does not occur anymore. I currently do not have any Palm & Thumb Recognition settings checked and everything is working like before. 4 finger click still registers even with 2 of my 4 fingers barely touching or half way off the trackpad, like you said, it must be the thumb portion of the trackpad having issues. Thanks again for fixing the issue so quickly!
