### ISSUE TITLE
Future request: option to turn off Trackpad customizations

### ISSUE THREAD

**Issue by Nostravinci** [fifafu/BetterTouchTool#441]
I am starting to exclusively use the TouchBar functions in BTT.

Would it be possible to add an option to disable the Trackpad and Magic Mouse customizations?

**Comment by fifafu** [comment]
If you dont add any gestures they are disabled. Or what do you mean exactly?

**Comment by Nostravinci** [comment]
I'm referring to the gesture sensitivity and the mouse/trackpad speed. Aren't those customizations active whenever BTT is running?

**Comment by fifafu** [comment]
the gesture sensitivity only works for BTT gestures, not for system gestures :-)
The mouse speed is always active however it just mirrors the value from System Preferences.
