### ISSUE TITLE
BetterTouchTool not working with Google Chrome

### ISSUE THREAD

**Issue by tomasb-asl** [fifafu/BetterTouchTool#442]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I tried to set up some bookmarks using the go to URL commands on BetterTouchTools but whenever I'm in google my icons wont show up when I press my modifiers 

**What kind of Mac are you using?**
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Macbook touchbar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 Sierra
2.03 BetterTouchTool

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports
TouchBar While holding modifier (shift)
<img width="1085" alt="touch bar shot 2017-02-08 at 23 30 39" src="https://cloud.githubusercontent.com/assets/21587325/22762302/a60b4ab8-ee56-11e6-9037-9076363814b5.png">

<img width="1014" alt="screen shot 2017-02-08 at 23 29 53" src="https://cloud.githubusercontent.com/assets/21587325/22762320/b69aa9f0-ee56-11e6-825d-dbb94ba5714d.png">

<img width="1018" alt="screen shot 2017-02-08 at 23 28 33" src="https://cloud.githubusercontent.com/assets/21587325/22762325/ba0aac34-ee56-11e6-8dd0-0d0a600cdfd0.png">

**Comment by fifafu** [comment]
Weird. Seems to be working fine here. Do you maybe have an app-specific override for the Touch Bar visibility?

![image](https://cloud.githubusercontent.com/assets/8820811/22845073/3be2517c-efe1-11e6-888c-67e8fe37e090.png)

**Comment by tomasb-asl** [comment]
No, I dont think so
<img width="1016" alt="screen shot 2017-02-11 at 22 25 57" src="https://cloud.githubusercontent.com/assets/21587325/22857992/4361f6f0-f0a9-11e6-90cf-36c2eb704e8f.png">

**Comment by tomasb-asl** [comment]
Oh nvm, I fixed it by doing this:
<img width="1015" alt="screen shot 2017-02-11 at 22 29 09" src="https://cloud.githubusercontent.com/assets/21587325/22857999/8a9da712-f0a9-11e6-8efa-677d1a3d4795.png">
