### ISSUE TITLE
Minimize all windows command does not minimize Calendar window

### ISSUE THREAD

**Issue by dmunoz1097** [fifafu/BetterTouchTool#443]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Assigned "minimize all windows" command to option-command-m.  Works for all browser windows, but let Mac OS calendar app window up.

**What kind of Mac are you using?**
Macbook Pro with Retina display mid 2012 model 10,1

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook built-in keyboard

**Which versions of macOS and BetterTouchTool are you running?**
Mac OS v10.12.3  BetterTouchTool v2.03

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Mhh BTT doesn't have a minimize all windows as far as I remember, or does it 😀?

Do you mean the "Hide all" action?
