### ISSUE TITLE
Show MacOS Control Strip seems to make no difference?

### ISSUE THREAD

**Issue by ftolsson** [fifafu/BetterTouchTool#447]
Hi,

This may of course be misunderstanding something — but: Should the setting Show MacOS Control Strip (under General Touch Bar Settings) do anything?
I can't really see any difference at all whether ticking or unticking that box...

I was hoping to see the control strip (including the chevron) go away — I'd rather just use the Fn key for accessing MacOS's control buttons, and use the entire Touch Bar for Apps/BTT.
Am I interpreting that setting incorrectly?

I'm on a 2016 MBP 13", 3.3GHz/16GB, MacOS 10.12.2
BTT version 2.02 (598)
System setting for Touch Bar is "App controls with Control Strip" + Fn to "Expand Control Strip."

Thanks,

/Fredrik.

**Comment by fifafu** [comment]
This only works for the BetterTouchTool Touch Bar.
So if you have buttons configured in BTT the Control Strip should be hidden. Make sure you have no app-specific settings that override the setting:

![image](https://cloud.githubusercontent.com/assets/8820811/22797921/63410650-ef00-11e6-90e7-a45aa3555005.png)

Also if this doesn't work maybe try updating to 10.12.3

**Comment by ftolsson** [comment]
Got it! And more importantly: "Only for the GLOBAL BTT touch bar." Right? 

In my eyes, it reads like it would generally affect all instances of BTT touch bars, including app specific ones — which would be a nice touch if I had a couple of app specific touch bars set and wanted to get rid of the Mac Control Strip for all of them.

I might want to argue that there is potentially something slightly confusing (at least for me) to have this setting here, and then the per-app-setting in the drop down.
I see no real solution to it now that I've understood how it works, but maybe (for daft people like myself) clarify that the checkbox in the "General Touch Bar Settings" dialog is rather _"Show MacOS Control Strip in BTT Global Touch Bar"_ (or something less wordy — but you see my point)...

Anyways, thanks! I got it now but it took some time. :)

**Comment by fifafu** [comment]
Mhh it should work for all app-specific Touch Bars that you have defined in BTT. Doesn't this work for you?

Could you send me an export of your BTT setup (using the export button in BTT)? (boastr.net@gmail.com)

I'll think about the wording!

**Comment by ftolsson** [comment]
Okay, now I AM confused. Especially since I can suddenly get it to work if I add a new app. Then, as expected, turning that checkbox off rids me of the control strip. Hm.
Don't know what I did wrong, but I guess it works for me now.

On the other hand, this makes me wonder something else instead: how does this differ from the App Specific setting "Show BTT Touch Bar, Hide ctrl strip"? Is it just that the App Specific setting has precedence — or something more?

I may be both daft and tired — it's very likely, in fact — but should perhaps the "default" in the App Specific drop down selection rather be "as per the setting in the general settings box" (again, with better words) to illustrate that it's not a *setting* per se, but just the app-specificness being turned off? Unless I'm wrong, of course, in which case nothing probably helps but a smack on my head.

And: All these questions aside, I love what you've created here!

**Comment by fifafu** [comment]
It's like this: The setting in the "General Touch Bar settings" is the default for all apps where you don't explicitly specify an app-specific behavior. If you specify an app-specific behavior that always overrides the General Touch Bar settings.

**Comment by ftolsson** [comment]
Yeah. So I guessed. Sort of. And eventually. :)
So in my mind, default would mean a default value, while in yours default means defaulting back to whatever value is set elsewhere — I guess one is not more wrong than the other. 
Sorry for the confusion. And thanks for the answer.

**Comment by fifafu** [comment]
I'll try to make this more clear with the next update!
