### ISSUE TITLE
[Feature req]Screensaver Buttons on Touchbar

### ISSUE THREAD

**Issue by verstaerkermusic** [fifafu/BetterTouchTool#452]
#### Description of your bug/question/feature request...:

can the buttons shown when the screensaver turns on be modified (I'd like to have a skip track function)

**What kind of Mac are you using?**
MBP2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Tocuhbar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Unfortunately the API doesn't allow that as far as I can tell (probably for security reasons while the screen is locked/a screensaver is running)
