### ISSUE TITLE
gap above dock unless dock is moved to left/right in System Preferences

### ISSUE THREAD

**Issue by jeremybundgaard** [fifafu/BetterTouchTool#454]
#### Description of your bug/question/feature request...:
gap above dock unless dock is moved to left/right in System Preferences

**What kind of Mac are you using?**
 Model Name:	iMac
  Model Identifier:	iMac13,2
  Processor Name:	Intel Core i7
  Processor Speed:	3.4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	24 GB
  Boot ROM Version:	IM131.010A.B0A
  SMC Version (system):	2.11f14

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

window snapping

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.2 (16C67)

**Comment by fifafu** [comment]
You mean the gap when the dock is hidden?
Unfortunately this is a limitation given by the system :-(. I haven't found a way to workaround that.

(Try resizing a window manually, it will also have that gap).

**Comment by jeremybundgaard** [comment]
It's app dependent. Unfortunately both atom and iterm have this issue and I use them all day ;) no big deal though...Finder, Chrome, Mail, others take up every pixel except the corners.

Thanks for building BTT!

I LOVE the "Execute Terminal Command"...SO! GOOD! I map so000 many bash scripts to hotkeys...just wonderful! A mac without BTT literally blows...they should give you millions bucks for you code and deeply integrate it with macOS! keep it up 🤘🏻

![jeremys-imac local_10feb17_1641 24](https://cloud.githubusercontent.com/assets/25033626/22848234/3efd82ea-efb0-11e6-8c5c-3199f8e5f89c.png)

**Comment by jeremybundgaard** [comment]
nevermind about iterm...they fixed months ago

![screen shot 2017-02-10 at 5 19 22 pm 2](https://cloud.githubusercontent.com/assets/25033626/22848903/172b8adc-efb5-11e6-94e3-03f41593166c.png)

**Comment by fifafu** [comment]
Update: this has been fixed in high sierra
