### ISSUE TITLE
Feature Request: TouchBar font size

### ISSUE THREAD

**Issue by timothyBoye** [fifafu/BetterTouchTool#456]
I don't know how much control you have with font sizes and Apple's TouchBar API but if it is possible I'd love to be able to increase font sizes of some controls. 

I have a vision impairment so if stuff like the clock I made using AppleScript could have a larger font that would be very handy as I could read it at a glance rather than having to move up close to the bar to read it.

Late 2016  15" Macbook Pro w/TouchBar
BetterTouchTool 2.04

**Comment by fifafu** [comment]
Hey,

yes, this is already planned for the next version!

**Comment by MrStarktastic** [comment]
Since my request is pretty much related to this, is it also possible to change the font type for a button's label? Like Helvetica, Myriad and such...

Love your work, thanks a lot!

**Comment by edgardluz** [comment]
One more vote for Font Face and Font Size to mac our touch bar look even more awesome! Thanks for your hard work.

**Comment by cong8341** [comment]
how to set touch bar button name font size?

**Comment by fifafu** [comment]
In current versions of BTT you can change the default font size. See this screenshot:

![image](https://user-images.githubusercontent.com/8820811/35757987-e98d3540-0871-11e8-8cb5-48e4fa4e9f9c.png)
