### ISSUE TITLE
docs website down 

### ISSUE THREAD

**Issue by abaileyb** [fifafu/BetterTouchTool#457]
http://docs.bettertouchtool.com/

yields 

<img width="769" alt="screen shot 2017-02-11 at 7 34 08 am" src="https://cloud.githubusercontent.com/assets/438881/22854478/862b9b80-f02c-11e6-9958-1b3b2d54cafe.png">

**Comment by fifafu** [comment]
Ah sorry, need to configure that domain in my new server. For now you can use https://docs.bettertouchtool.net

**Comment by abaileyb** [comment]
Thanks!
