### ISSUE TITLE
allow manual input of delay time

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#46]
currently its very hard to get a precise value with the slider 
<img width="1127" alt="image" src="https://cloud.githubusercontent.com/assets/8683379/20979587/7df84d08-bc7b-11e6-96bf-84d9dd87f6fc.png">
allowing manual input would really increase usability

**Comment by fifafu** [comment]
Good point!

**Comment by fifafu** [comment]
fixed with next update (release tomorrow)
