### ISSUE TITLE
Feature Request: Stateful/Modal shortcut support

### ISSUE THREAD

**Issue by ShaneDelmore** [fifafu/BetterTouchTool#460]
As I was sitting down today configuring vim keys in an application for the umpteenth time today I realized I would love support for states in BetterTouchTool.

My first pass at what that would look like:

- The ability to define and enter states (for example browsing, music, navigation)
- Some indicator of state so I don't accidentally enter a state and get lost.  Maybe the tray icon could turn a different color per state for example
- Speaking of indicators, this would be a neat place for the touchbar to show the current state, and to be able to switch states via touchbar buttons
- The ability to grab all keystrokes in non-default state so I can make shortcuts from single keys.
- The ability for all shortcuts to be redefined in each state

Now an example of how I would use this.

- Define state navigationMode (loosely based on Vi normal mode).  I use this mostly to enter other states
- Define state windowNavigationMode
- Define state applicationNavigationMode

I would still largely use BetterTouchTool as I do today, but there are some shortcuts that require multiple actions, and for those a dedicated state would be very useful.

I will use a couple of my existing shortcuts as the basis of one further example:

- tip tap left -> cmd + shift + [
- tip tap right -> cmd + shift + ]

Proposed example starting with today's current functionality, which I will refer to as defaultMode:

- cmd + alt + n -> navigationMode
  - esc -> defaultMode
  - a -> applicationNavigationMode
    - h -> cmd + shift + [
    - l -> cmd + shift + ]
    - esc -> navigationMode
  - w -> windowNavigationMode
    - h -> focus application to the left
    - H -> snap application to left border
    - l -> focus application to the right
    - L -> snap application to right border
    - tip tap left -> focus application to the left
    - tip tap right -> focus application to the right
    - two finger swipe direction -> snap application to direction
    - esc -> navigationMode
  - s -> spaceNavigationMode
    - h -> select space to the left
    - j -> select display above (in the case monitors are arranged one above the other)
    - k -> select display below 
    - l -> select space to the right
    - two finger swipe left or right -> move application to space left or right
    - two finger swipe up or down -> move application to display up or down
    - esc -> navigationMode

So that's the gist of it, I tried to make the example small, but enough to communicate the idea.  Let me know if I can provide any further information.

**Comment by fifafu** [comment]
I think you can use presets for something like this.

Just create a new preset in BTT and call it "navigation" or similar. Then use the predefined action "switch to preset" to switch from one preset to the other.

**Comment by ShaneDelmore** [comment]
Not quite.  I just did a quick experiment, add a preset Navigation, then made a shortcut to map h to cmd + shift + [.  I switched to navigation, pressed h, and moved a tab left.  Success!  Then I switched back to default, tried to type h, and it swallowed the h, now I can't type any work with h in it.  The foundation is definitely there for the feature, but it doesn't quite work as is.

**Comment by fifafu** [comment]
Oh, that's definitely a bug then :-) I'll fix that with the next update!

**Comment by fifafu** [comment]
The bug should be fixed in the new alpha version (available in about an hour)!
