### ISSUE TITLE
Feature request: Windows tiling for Mac

### ISSUE THREAD

**Issue by robertcch** [fifafu/BetterTouchTool#461]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Windows is superior to Mac in one important way: Tiling. With the click of a button, all open windows are proportionally resized. Yes, there is Mission Control, but it's not the same as the ability to see all windows fully resized, because each window is shrunk slightly instead. There is snap functionality, but all windows must be individually resized, which can be time consuming when working with multiple windows. You would be a hero to many for making this feature available.

Another useful feature would be the ability to reinstate a window after minimizing it (sometimes accidentally, sometimes just to view the windows beneath it). There is no way to bounce a window back to its original position after minimizing it without manually scrolling down to the dock to retrieve it.

Thank you for creating such a wonderful and useful product!

P.S.

Signing up with GitHub failed in the pop-up window from the BetterTouchTool section of the site. It kept saying my new user name couldn't be accepted. When I closed the pop-up window and went to the GitHub main page, I was able to sign up without any issues.

**What kind of Mac are you using?**

MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

N/A

**Which versions of macOS and BetterTouchTool are you running?**

10.12.3, 2.02

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.

Unfortunately this is not something that I'll be adding to BTT. There are however tools that may do similar things, maybe have a look at https://github.com/ianyh/Amethyst

**Comment by robertcch** [comment]
Thank you very much for letting me know about Amethyst.

I was excited to hear that tiling was finally a feature for Mac—alas, the app is only supported on OS X 10.12 and not 10.13.3.

However, I signed up to their development page and asked to be alerted once the app can be used on High Sierra.

Much appreciated,

Robert

**Comment by fifafu** [comment]
Where are they saying that? I thought I saw it working on 10.13.x already

**Comment by robertcch** [comment]
Go to https://github.com/ianyh/Amethyst <https://github.com/ianyh/Amethyst>

Scroll down to “Getting Amethyst.”

It says "Note: that Amethyst now is only supported on OS X 10.12+.”

Oh, wait. That should mean it is available on 10.13.3? It’s just that, when I opened it, nothing happened.

Hm. I’ll keep tinkering with it.

**Comment by robertcch** [comment]
It was definitely user error. Thanks for following up.
