### ISSUE TITLE
touchbar - remove the close touchbar icon left of ESC

### ISSUE THREAD

**Issue by aavelyn** [fifafu/BetterTouchTool#463]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Hi, Is there a way to remove the close btt touchbar icon on the left side of ESC? (it's a circle with x)

**What kind of Mac are you using?**
macbook pro 15inch 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
 macOS Sierra 10.12.03 and btt 2.0.4

**Comment by fifafu** [comment]
Due to API limitations the only way is to completely hide the macOS Control Strip in the BTT General Touch Bar settings.

![image](https://cloud.githubusercontent.com/assets/8820811/22865398/caf3d7d6-f163-11e6-8463-c439649c9826.png)

See e.g. #123
