### ISSUE TITLE
Caps Lock Key Not Working At All

### ISSUE THREAD

**Issue by matose** [fifafu/BetterTouchTool#464]
My caps lock key is not working and it is not a hardware issue as Apple just replaced the keyboard. 

The caps lock key will work before I log into my mac (light will come on and up arrow shows in password entry box) but not after I log in. 

I am still in the free trial period with BetterTouchTool. Is there a known bug or simple fix? Of course, I don't know for sure it is BTT. I am troubleshooting and will uninstall BTT soon and test other things. 

I have an Early 2015 Macbook Air, OSX Sierra 10.12.3 and BTT 2.02(598)

Thanks for any help or direction you can provide.

**Comment by fifafu** [comment]
You can easily test that: just close BTT. If it's not running it doesn't do anything.
However I really doubt that caps lock could be influenced by BTT :-) Are you sure you haven't reconfigured it in System Preferences => Keyboard => Modifiers ?
