### ISSUE TITLE
2.04 Crashes on 4 finger force touch

### ISSUE THREAD

**Issue by robotink** [fifafu/BetterTouchTool#465]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
can reliably crash v2.04 by doing 5-10 4-finger force touches.

the only BTT settings i have are for 4-finger force touch => middle click
and reduced pressure required to trigger 4-finger force touch
and custom vibration for force touch

older versions of BTT do not crash using the same settings, only started happening when upgrading to 2.04

**What kind of Mac are you using?**
2016 macbook pro 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Trackpad. did not test macbook trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3, 2.04. previous versions of BTT do not crash

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

[BetterTouchTool.zip](https://github.com/fifafu/BetterTouchTool/files/769652/BetterTouchTool.zip)

**Comment by fifafu** [comment]
Weird, what kind of custom vibration do you have set?

**Comment by robotink** [comment]
<img width="865" alt="screen shot 2017-02-12 at 4 03 30 pm" src="https://cloud.githubusercontent.com/assets/5317888/22866478/e3643ac6-f13c-11e6-9cbf-faf563e773ed.png">

these are the vibration/pressure settings
oh, and i have the magic trackpad inverted. otherwise all other settings default

**Comment by fifafu** [comment]
Hey,

could you check how 2.06 alpha is working for you?

Best,
Andreas

**Comment by robotink** [comment]
problem is fixed! thanks!
