### ISSUE TITLE
Dog snout registers as 4 finger click 

### ISSUE THREAD

**Issue by cosmonate** [fifafu/BetterTouchTool#466]
I know this is silly thing, but recently my dog has taken to resting his snout on my trackpad when he wants attention. BTT detects this as a 4 finger click, which unfortunately for me, I have set to Command-W windows out of existence.

Thumb / Palm filtering is turned on, but seems to be no match for the mighty snout. Dog was not cooperative with attempts to screenshot his snout on the live view, but picture of said dog has been included so that you can examine said snout. He's got little chin hairs that might be causing the problem, maybe some sort of "too many fingers" detection would help? 

![img_1405](https://cloud.githubusercontent.com/assets/8390044/22866544/4937e2ea-f146-11e6-8367-78c7c794a986.JPG)

Macbook Pro Retina Trackpad, Mid 2012 on Sierra with BBT 2.04

**Comment by fifafu** [comment]
I'm not sure if I'll be able to add a reliable dog snout detection, especially because dog snouts vary greatly in size and shape. 

If possible please ask your dog again to put his snout on the trackpad so you can get a live view screenshot, this could be very helpful.

**Comment by cosmonate** [comment]
I wasn't able to get him to rest his snout long enough to get a screenshot, but I was able to replicate what I saw with the back of my hand. His snout usually causes the trackpad live view to freak out a bit, but usually there is one large oval in there somewhere. 
<img width="495" alt="screen shot 2017-02-12 at 5 42 48 pm" src="https://cloud.githubusercontent.com/assets/8390044/22866879/fd6d15f6-f14a-11e6-9557-2f4d283e3adf.png">

**Comment by fifafu** [comment]
So maybe having an option to ignore everything if >= 1 very large touch is being recognized would solve the issue!

I'll look into this tomorrow 😀

Thank you for this bug report, now I can go to sleep.

**Comment by oqibidipo** [comment]
LOL! A new version of "My dog ate my homework!" :rofl:
