### ISSUE TITLE
Lagging Drag to Resize on new Macbook Pro 2016

### ISSUE THREAD

**Issue by danielwyb** [fifafu/BetterTouchTool#467]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
When dragging the window to the sides of the screen, the animation of the dark overlay that shows how the window would be aligned is really slow and choppy. Makes me not want to use the drag feature anymore because it feels broken. Works great with touchbar commands.
Would be great to have this back!

**What kind of Mac are you using?**
Macbook Pro 2016 
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
Sierra 10.12.3
Latest BTT 2.04

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

unfortunately I think there is not much I can do about the animation (it just uses the standard system animations), however you can turn off the animation completely which will make if much snappier.

![image](https://cloud.githubusercontent.com/assets/8820811/22942813/5451b5c4-f2eb-11e6-9382-1e6589bdefc6.png)

**Comment by danielwyb** [comment]
Perfect, thanks!
