### ISSUE TITLE
after issuing keystroke shortcut 5-second delay until next one is accepted 

### ISSUE THREAD

**Issue by johnpane** [fifafu/BetterTouchTool#468]
#### Description of your bug/question/feature request...:

After issuing a keystroke shortcut, the shortcuts are ignored by the system for 5 seconds (the raw keystrokes are transmitted to the application instead of the remapped keystrokes).

**What kind of Mac are you using?**

Macbook Pro 15" Retina Late-2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

External keyboard with numeric keypad, specifically:
Apple Keyboard:
  Product ID:	0x0220
  Vendor ID:	0x05ac  (Apple Inc.)
  Version:	0.69

**Which versions of macOS and BetterTouchTool are you running?**

MacOS 10.12.3
BTT 2.04

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

<img width="718" alt="screen shot 2017-02-13 at 10 46 22" src="https://cloud.githubusercontent.com/assets/14841761/22890223/b0a8c5d2-f1d9-11e6-8e8d-5ecac6f29023.png">

**Comment by fifafu** [comment]
Hey,

what exactly are you trying to achieve with those mappings?
You map the shortcuts onto theirselves, thus triggering an endless loop.

Best,
Andreas

**Comment by johnpane** [comment]
Hi,

I am remapping keystrokes on the numeric keypad to their equivalents on the row of number keys on the main part of the keyboard. This is because the OS no longer treats them as the same. Without this remapping I cannot use those numeric keys when the keyboard is attached and the main keys on my laptop keyboard when the keyboard is disconnected. By remapping the numeric keypad I am able to use either set of keystrokes to control Spaces.

If there is an endless loop it is not directly evident -- only one keystroke is issued -- though maybe that is the reason for the delay I do observe?

Thanks,
John

**Comment by johnpane** [comment]
<img width="762" alt="screen shot 2017-02-14 at 16 29 26" src="https://cloud.githubusercontent.com/assets/14841761/22952476/dfe63df8-f2d2-11e6-8738-99117778ffc0.png">

**Comment by fifafu** [comment]
ah, now I see! I'll look into this, this should be fixable.

**Comment by johnpane** [comment]
Here is a little more information that might help you track this down.

I turned on the HUD overlay and this overlay is displayed even during the 5-second period when the keystroke remapping does not work.

**Comment by johnpane** [comment]
This is now working. Not clear if an OS update (to 10.12.4) fixed it, or you did.
