### ISSUE TITLE
Continually shuts down on MacBook Pro

### ISSUE THREAD

**Issue by nhbean123** [fifafu/BetterTouchTool#471]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
The tool keeps shutting down completely while running in the background. Has to be restarted manually over and over. This issue persists even after restarting and checking for updates.

**What kind of Mac are you using?**
MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Logitech mouse M705

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra Version 10.12.3
BetterTouchTool Version 2.04

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by anas2204** [comment]
I have faced the same issue in version 2.02. I tried to go back to version 2.0. It didn't break for a few days, but now it has started shutting down frequently in version 2.0 as well.

@fifafu Could you find out a reason for these frequent crashes? Although it keeps running in the background (and trackpad gestures work), it disappears from the Touch Bar.

**Comment by nhbean123** [comment]
my app constantly crashes and stops functioning with my external mouse and touchpad.

**Comment by fifafu** [comment]
Definitely not normal, could you send me a crashlog? (they are stored in the macOS console.app under "User Reports")

**Comment by anas2204** [comment]
[Anas-CrashReports-2.02.zip](https://github.com/fifafu/BetterTouchTool/files/772351/Anas-CrashReports-2.02.zip)

@fifafu These are my crash reports (Sorry for posting it in another thread). These belong to version 2.02). Could you see if it gives you an insight into the frequent crashes?

Thanks!

**Comment by nhbean123** [comment]
Where to find User Reports in App?

**Comment by fifafu** [comment]
@anas2204 interesting, those crashes seems to happen when BTT tries to produce haptic feedback on your trackpad.

Have you changed any settings in the advanced touchpad settings? Maybe there is a bug with a specific combination of settings there.
![image](https://cloud.githubusercontent.com/assets/8820811/22902819/b387f0c2-f236-11e6-97d6-0d5a78f08401.png)

@nhbean123 in the macOS app called "Console"

**Comment by nhbean123** [comment]
[Archive.zip](https://github.com/fifafu/BetterTouchTool/files/772376/Archive.zip)

@fifafu thanks

**Comment by fifafu** [comment]
@nhbean123 yours is a very strange crash, it seems to crash in a system framework.

One question, do you have any plugins for the macOS color picker installed? (in ~/Library/ColorPickers)? (the crash seems to be somehow related to the macOS color picker and Snap Areas in BTT)

**Comment by anas2204** [comment]
<img width="1011" alt="screen shot 2017-02-13 at 4 09 04 pm" src="https://cloud.githubusercontent.com/assets/8613978/22903501/cdac5ac2-f206-11e6-92a5-59d2351adf70.png">

@fifafu Yes, I did change the settings to custom, not realizing it will result to my crashes. Let me know if you think it is causing the crashes. Is your screenshot the default settings?

**Comment by nhbean123** [comment]
@fifafu i do have Adobe products installed (which might be causing the problem) but do not have any plugins installed directly

**Comment by nhbean123** [comment]
@fifafu i have turned off Snap Areas, i already use HyperDock for that. Perhaps those two were fighting each other. Hopefully the crashes stop now.

**Comment by fifafu** [comment]
I think I may have found workarounds for both crashes, I'll release a new alpha version tomorrow.

**Comment by esteinborn** [comment]
@fifafu I am also crashing multiple times a day, shoudl I open a new issue, or paste my cashlog here as well?

**Comment by anas2204** [comment]
@fifafu I uninstalled BTT after exporting my gestures, removed the preferences and all files. Re-installed (Latest version) and imported my gesture file with Default settings.
Even now, it randomly breaks (disappears from the Touch Bar). There is no crash log generated. Could you please point me to a direction that can make me help you in finding the problem.

Before the release 2.0 and forward, it NEVER broke like this. But with 2.0 and forward, it is the same behavior.

**Comment by fifafu** [comment]
@anas2204 did you try the 2.05 alpha? If you say it disappears from the Touch Bar, does that mean the BetterTouchTool icon in the menubar is still visible?

**Comment by anas2204** [comment]
@fifafu I have not yet tried the 2.05 alpha, but I am surely going to, and will give you feedback on it.

About your question: Yes, it disappears from Touch Bar, but NEVER from the menubar. It always is a problem on the Touch Bar, and that too ONLY when the computer wakes up. If it starts, it goes on fine, until the computer sleeps.
Also, this is surprising because it never happened in the earlier versions, and no crash reports are being generated. Also, when I restart, sometimes the Touch Bar icon breaks like the photo below:
https://cloud.githubusercontent.com/assets/8613978/22790848/7f1c70da-eeb5-11e6-8585-1cbeb45e1b4e.png

**Comment by anas2204** [comment]
@fifafu I installed the latest version yesterday, and although it did not break initially, the same behaviour is starting to show now. Many times it gets disappeared from the Touch Bar like:
<img width="1085" alt="touch bar shot 2017-02-16 at 5 41 43 pm" src="https://cloud.githubusercontent.com/assets/8613978/23049206/8f6aa7b2-f488-11e6-8908-771c2e803cf0.png">

When I try to restart it manually from menubar, it sometimes goes into unusable states (Half/Full blank icon) like:
<img width="1085" alt="touch bar shot 2017-02-16 at 2 01 26 pm" src="https://cloud.githubusercontent.com/assets/8613978/23049217/a4adbc0e-f488-11e6-8fb8-4d412921e70a.png">
<img width="1085" alt="touch bar shot 2017-02-16 at 3 59 51 pm" src="https://cloud.githubusercontent.com/assets/8613978/23049226/a986a2e0-f488-11e6-96cc-aae62b1c6f44.png">

Could you find the solution to this? There are no crash logs in Console App. Attached below is my Touchbar setting:
<img width="814" alt="screen shot 2017-02-16 at 8 45 57 pm" src="https://cloud.githubusercontent.com/assets/8613978/23049291/1b948974-f489-11e6-9146-95fbd900ba70.png">

**Comment by fifafu** [comment]
This seems like something BTT can't influence. For some reason your system doesn't seem to react correctly to BTT's commands (Unfortunately this is all not supported by Apple, otherwise I'd file a bug report)

I'm however not sure why this happens on your machine as it seems to work fine for most users :-/ Do you maybe have another Touch Bar related app installed?

Are you sure you have tried to reset all BTT settings? (You can use this terminal command while BTT is closed : "defaults delete com.hegenberg.BetterTouchTool"

**Comment by anas2204** [comment]
No, I'm not using any other Touch Bar app. And I tried using your terminal command + restarting the system. It still crashed.
I guess it's really unfortunate that it happens on my machine! My workflow is almost unusable without BTT now, and always having to restart it when the laptop wakes up is a pain.
Do let me know if others are reporting the same or you can replicate the issue.

**Comment by natebrunette** [comment]
This happens to me every day.

[BetterTouchTool_2017-03-03-165348_Nates-MacBook-Pro.crash.zip](https://github.com/fifafu/BetterTouchTool/files/821682/BetterTouchTool_2017-03-03-165348_Nates-MacBook-Pro.crash.zip)
