### ISSUE TITLE
Using Predefined action: Paste Custom Text puts the same text into (BTT)@clipboard(BTT)

### ISSUE THREAD

**Issue by murawskikrzysiek** [fifafu/BetterTouchTool#473]
#### Description of your bug/question/feature request...:
When having a list of actions comming one after another if Paste Custom Text occurs before usage of (BTT)@clipboard(BTT) the content in the @clipboard gets overwritten by what was in the Paste Custom Text...

**What kind of Mac are you using?**
MacBook Pro 15, Mid 2015
2,8 GHz Intel Core i7
16 GB 1600 MHz DDR3
AMD Radeon R9 M370X 2048 MB
Intel Iris Pro 1536 MB

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

This was spotted for keyboard shortcuts

**Which versions of macOS and BetterTouchTool are you running?**

10.12.3 / 2.04 (603)

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into that!

**Comment by fifafu** [comment]
Hey,

could you check if this works correctly again with the 2.05 alpha?

**Comment by murawskikrzysiek** [comment]
Hi,

the 2.05 alpha fixes the issue for my workflow! 
Thanks!
