### ISSUE TITLE
Window Snapping does not maximise completely

### ISSUE THREAD

**Issue by svdvonde** [fifafu/BetterTouchTool#474]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
The Window Snapping feature leaves a small border under a maximised application. 

**What kind of Mac are you using?**
Late 2016 15" with touch bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
None

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3, 2.04

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Screenshot of maximised browser (by dragging it to the top) which leaves a small border under the application: http://i.imgur.com/8SxOOUV.png
Screenshot of my btt settings: http://i.imgur.com/ga5ld7q.png

<img width="1920" alt="screen shot 2017-02-14 at 10 56 37" src="https://cloud.githubusercontent.com/assets/2751783/22924344/0e2baa0a-f2a5-11e6-837c-fde02422a476.png">
<img width="1012" alt="screen shot 2017-02-14 at 10 58 26" src="https://cloud.githubusercontent.com/assets/2751783/22924345/0e2ce41a-f2a5-11e6-9976-7de12be190ac.png">

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Unfortunately that gap is enforced by the system (try resizing a window manually, it will also leave that gap in case the dock is hidden).

Currently I don't think there is a workaround.
