### ISSUE TITLE
Refresh applescript-generated button when button is clicked

### ISSUE THREAD

**Issue by kojoru** [fifafu/BetterTouchTool#475]
#### Description of your bug/question/feature request...:

**What kind of Mac are you using?** 
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?** 
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3/2.0.4

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

"Run AppleScript and return value" refreshes once a couple of seconds. This is not cool when the state of returned value changes when button is clicked. E. g. I wanted to build a language-changer which displays current language and changes it when I click the button. The lag on button display is several seconds, so that's basically unusable.

Can we have "run applescript again when button is pressed" option? Or a language-change widget :)

**Comment by fantaaaaaa** [comment]
same here: https://github.com/fifafu/BetterTouchTool/issues/385
