### ISSUE TITLE
[CONFIRMED BUG] Gesture detection sometimes multi-triggers itself from a single gesture

### ISSUE THREAD

**Issue by SteveJobzniak** [fifafu/BetterTouchTool#477]
#### Description of your bug/question/feature request...:

My 3 finger tap is bound to middle click.

I perform a 3 finger tap. Just 3 fingers. Formed in a straight line. And I perform a single tap and instantly letting go of the touchpad.

BTT sends 1 middle click most of the time. Sometimes it sends 2, which opens two Safari tabs!

I have attached a zip file with a video showing the bug (I click once every time, but sometimes you will see the click counter goes up by 2 when the bug happens!).

I have also included my complete gestures file.

[tapbug.zip](https://github.com/fifafu/BetterTouchTool/files/775123/tapbug.zip)

And here is the jsFiddle I used to count clicks:
http://jsfiddle.net/pd3o58ze/

**What kind of Mac are you using?**

MacBook Pro 2010

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook's own trackpad

**Which versions of macOS and BetterTouchTool are you running?**

macOS Sierra and BetterTouchTool 2.04

**Comment by SteveJobzniak** [comment]
Update: I tried deleting my 4 finger tap gesture to only keep the 3 finger tap. But that did not fix it. 3 finger taps still send two middle-clicks occasionally, so it wasn't a conflict between those two gestures.

**Comment by SteveJobzniak** [comment]
Update: I created a brand new Gesture Profile (the New button in the left side of the GUI), and added ONLY a 3 finger tap and set it to Middle Click. This is as pure as it gets. And the bug still happens.

**Comment by SteveJobzniak** [comment]
Update: I tried a brand new profile and added ONLY a FOUR finger tap and set it to Middle Click. This has the same bug. The middle click sometimes triggers twice.

So yeah it's reproducible with the smallest possible profile, a single gesture... and it does not matter that it was a 3 finger tap. It can be 4 finger tap and probably any other gesture too.

Now the only question is: Is every gesture multi-detected, or is it a problem only with middleclicks and sending multiple ones of those...

**Comment by SteveJobzniak** [comment]
Update: I tried 4 Finger Tap, send Option-Click. Same bug. Sometimes it clicks twice.

This leads me to conclude two possible bugs:

- Either every gesture (at least tap gestures) have a "multi-repeat bug" where they trigger multiple times.
- Or the "simulate mouse click" code is bugged and sends two clicks sometimes.

**Comment by SteveJobzniak** [comment]
Update: I tried 4 Finger Tap, set to "Brightness Up". Set my brightness to lowest and tapped one by one... It went up by 1... by 1... by 1... by 1... by 2!

**Conclusion: It is not a bug with the mouse-related actions. There is a bug in the actual touch-detection code which triggers a touch's action multiple times.**

**Comment by fifafu** [comment]
Hi Steve,

thanks for reporting! This will be fixed in the next version (will release alpha tomorrow).
It was a bit tricky to track down because it doesn't happen on all trackpad types.

Best,
Andreas

**Comment by SteveJobzniak** [comment]
@fifafu That's fantastic Andreas, I am impressed at your speed. Thank you so much for finding the bug! I will try the Alpha when it comes out and let you know.

Hopefully this fix won't make "3 Finger Tap" less sensitive again. I used to barely be able to make "3 Finger Tap" react in BTT (50% of the time nothing happened), but as of a recent version that gesture finally works reliably. Maybe that's thanks to taps being over-sensitive now. We'll see what happens.

**Comment by SteveJobzniak** [comment]
@fifafu Hi Andreas! I just installed 2.05 alpha and made a small modification to the click-tester, to make it show an alert if it detects more than 2 clicks within each 250ms period. Then I created two new profiles, one for 3-finger and one for 4-finger, bound to middle click, and tried each profile for about 300 clicks. Didn't get a single warning about too many clicks, so it seems to be working!

http://jsfiddle.net/v3oeoe31/

Could you just briefly explain what the problem was, by the way? I am curious how come my trackpad was "one of the ones that it happened on".

**Comment by fifafu** [comment]
@SteveJobzniak accidentally registered a callback more than once for some trackpad types due to a recent change. Because of this the "zero fingers" case was called more than once. Just a silly typo, nothing special ;-)

Let's see if this really was the issue, please let me know in case it happens again.

**Comment by SteveJobzniak** [comment]
@fifafu Oh, phew, glad it was something that simple. I thought my trackpad may have had faulty hardware. ;-)

I gave the new clicktester page above another 300 taps and still did not get any double-registrations so yes this seems to have fixed it. Excellent. Thank you! :-)
