### ISSUE TITLE
Bug: Control Strip Disappearing

### ISSUE THREAD

**Issue by leleSahil** [fifafu/BetterTouchTool#478]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...: 
When the btt tool bar is open, occasionally the control strip part of the sidebar will disappear (see attached screenshot). I have not been able to determine what the cause of this error is

**What kind of Mac are you using?**

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
BTT 2.04 (603) and 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
<img width="1085" alt="touch bar shot 2017-02-14 at 3 43 32 pm" src="https://cloud.githubusercontent.com/assets/5100798/22950889/c7941b22-f2cc-11e6-9933-00001105a7c4.png">

Note: the missing control strip from the right of the touchbar

**Comment by anas2204** [comment]
@leleSahil I suppose your bug is similar to the one some of us are experiencing, as documented in https://github.com/fifafu/BetterTouchTool/issues/471#issuecomment-280107895

**Comment by fifafu** [comment]
@leleSahil @anas2204 I don't think this is related. Actually a disappearing control strip may not be connected to BTT at all, the Control Strip is a separate Apple process which I have seen crashing for unrelated reasons.

Are you sure you have enabled the control strip in BTT? And also not overwritten it using app-specific settings?

![image](https://cloud.githubusercontent.com/assets/8820811/23011168/b39d1246-f41f-11e6-823f-7cd59f87b44f.png)

![image](https://cloud.githubusercontent.com/assets/8820811/23011187/caf9407c-f41f-11e6-98c3-3d1c4df1db4d.png)
