### ISSUE TITLE
Left click w/ delay doesn't seem to work as expected

### ISSUE THREAD

**Issue by Nxt3** [fifafu/BetterTouchTool#480]
#### Description of your bug/question/feature request...:
I have the following setup:
![screen shot 2017-02-15 at 3 32 29 pm](https://cloud.githubusercontent.com/assets/2940826/22994396/ccfdf70e-f394-11e6-9a81-21162a0968be.png)

This is what is happening:
https://www.dropbox.com/s/21dl8byp6lrb0z1/Preview_with_Mouse_BTT_bug.mov?dl=0

As you can see, it seems like the `Spacebar` action is triggered before the `Left Click` on all occasions. I'd expect the Middle Mouse Button to: `Left Click` the file (meaning, it's highlighted), then perform the `Spacebar` action. It doesn't seem to do that though.

**What kind of Mac are you using?**
2015 rMBP 13in

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Microsoft Bluetooth Mouse

**Which versions of macOS and BetterTouchTool are you running?**
macOS v10.11.6
BTT v2.04

Hopefully I'm not missing something to the `Delay Next Action` action.

**Comment by fifafu** [comment]
Hey,

this seems to work fine here, however if you are using in Finder,try to add an escape key press at the beginning because otherwise the quicklook will only work on the first try.

![image](https://cloud.githubusercontent.com/assets/8820811/22995197/3210173c-f3ca-11e6-9722-34949cb58dfc.png)

**Comment by Nxt3** [comment]
Thanks. That seems to have done it. Didn't think of that!

**Comment by Nxt3** [comment]
But shouldn't that delay perform the first action? i.e. if I set the delay to 9 seconds, shouldn't I see the item selected for the `Left click` action and then 9 seconds would pass and then the `Spacebar` action would be triggered?
