### ISSUE TITLE
[Enhancement] Disable drawing functionality 

### ISSUE THREAD

**Issue by ldong** [fifafu/BetterTouchTool#481]
#### Description of your bug/question/feature request...:

I cannot find doc here http://docs.bettertouchtool.net/docs/drawings.html, for disable drawing functionality without deleting all drawing gestures.

I want to disable the drawing board from popping up, after disabled all drawing gestures.

Screenshot at the end

**What kind of Mac are you using?**
new mac book pro with touch bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad, Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**
macOS: 10.12.3
BTT: 2.04

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

![feb-15-2017 13-32-14](https://cloud.githubusercontent.com/assets/5491695/22996314/3b375dee-f383-11e6-9165-d99f3f1c9956.gif)

**Comment by ldong** [comment]
A more crisp gif
![untitled](https://cloud.githubusercontent.com/assets/5491695/22996448/a92bc6aa-f383-11e6-9fa3-cb190fa95e30.gif)

**Comment by fifafu** [comment]
hey,

you can disable right mouse drawing in the advanced settings:
![image](https://cloud.githubusercontent.com/assets/8820811/22996551/7a8a91b8-f3cf-11e6-9116-51d3b4db87c7.png)
