### ISSUE TITLE
Keyboard Illumination not working on touchbar

### ISSUE THREAD

**Issue by pbullion** [fifafu/BetterTouchTool#482]
#### Description of your bug/question/feature request...:
On the touchbar...
When you add button to bring the keyboard illumination up or down, when clicked it just brings up the system preferences for the keyboard.

**What kind of Mac are you using?**
2016 Macbook Pro touchbar
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
BTT 2.05
Sierra 10.12.3

**Comment by fifafu** [comment]
Hey,

are you pressing a modifier key while touching the Touch Bar button?
There are some system shortcuts (I think option+illumnination up or something like this) that open the System Prefs.

Best,
Andreas

**Comment by pbullion** [comment]
yea im clicking option but i also tried it on control, and command shift. it does work on the main one without having a modifier. so is that not something thats going to be possible.

**Comment by fifafu** [comment]
unfortunately no, the system will always interpret this shortcut to open the system preferences if modifiers are included.

However I'll soon be adding a keyboard brightness slider widget.

**Comment by pbullion** [comment]
@fifafu awesome yea that would be awesome for the slider
