### ISSUE TITLE
Speed of additional actions

### ISSUE THREAD

**Issue by cgibs13** [fifafu/BetterTouchTool#483]
#### Description of your bug/question/feature request...:
I primarily use BTT as a way of handling macros through the touchbar. I have a few actions setup that are really just a way of quickly typing things that I use a lot. ("System.out.println();" as an example) It has worked great, however, after recently updating it seems to type at a much slower rate. The macros are simply setup as each key press being its own additional action (For the above example the first action is S then another is y then another is s, etc.) and it seems the additional actions aren't as quick as they used to be. Is this not the proper way to do this or is there some way to speed up the additional actions?

Thanks

**What kind of Mac are you using?**
Newest macbook 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
Sierra 10.12.3 and BTT 2.04

**Comment by fifafu** [comment]
Hey,

I think it would be much faster to use the "paste custom text" action. Have you tried that?

**Comment by cgibs13** [comment]
That hasn't ever worked for me. It simply doesn't paste the text when I press the button.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
