### ISSUE TITLE
Two-Finger Click Does Nothing in Android Studio (2.2.3)

### ISSUE THREAD

**Issue by hentercenter** [fifafu/BetterTouchTool#484]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Only while running BTT 2.04 (603), two-finger clicking does nothing in Android Studio. CTRL+Click does open the right-click menu as intended.

Pressing harder activates a different BTT shortcut (Gesture drawing)

**What kind of Mac are you using?**
Model Name:	MacBook Pro
Model Identifier:	MacBookPro11,4
Processor Name:	Intel Core i7
Processor Speed:	2.8 GHz
Memory:  16 GB

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad, Touch Bar) is affected by this?**
MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3, 2.04 (603)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
All shortcuts created: http://i.imgur.com/w9GF1S8.png

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

could you check whether disabling the right-mouse drawing in the advanced settings fixes your issue?


Best,
Andreas

![image](https://cloud.githubusercontent.com/assets/8820811/23084838/ae7c3544-f564-11e6-9565-fb948da8be35.png)

**Comment by fifafu** [comment]
if this doesn't help, the issue should be fixed in 2.06 alpha
