### ISSUE TITLE
Feature: BTT Touch Bar strip remembers open/close state

### ISSUE THREAD

**Issue by anas2204** [fifafu/BetterTouchTool#486]
#### Description of your bug/question/feature request...:
Is there a way where the Control strip remembers the last open/close state of Individual apps. Suppose I keep BTT strip always open in Global State but closed in Chrome, is there a way I can do it now?

**What kind of Mac are you using?**
Macbook Pro 2016 with Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
OSX 10.12.3
BTT 2.05

**Comment by fifafu** [comment]
You can override/set the behavior for specific apps like this:

![image](https://cloud.githubusercontent.com/assets/8820811/23081803/d33cbbe6-f556-11e6-82c5-408c4420d435.png)

**Comment by anas2204** [comment]
Thanks a lot. Solved my problem
