### ISSUE TITLE
Why aren't my tip taps registering in terraria?

### ISSUE THREAD

**Issue by TearsInMyRamen** [fifafu/BetterTouchTool#490]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

Today I had the bright idea to use BTT to make my Terraria experience a little easier by assigning left and right tip taps (1 finger fix) to scroll through my hotbar. I set the BTT and changed the bindings within the game
![screen shot 2017-02-17 at 22 35 59](https://cloud.githubusercontent.com/assets/25858218/23090331/84bb792a-f561-11e6-8fcc-a5401b097470.png)
 and when I tip tap, nothing happens... suggestions?

Late 2011 MBP

Trackpad

MacOS Sierra; BTT Version 2.04

**Comment by sn0wyfall** [comment]
Do normal taps (not clicks) work for you in Terraria? Seems to be a Terraria bug.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
