### ISSUE TITLE
[Feature Request] Fine Tune Volume Options?

### ISSUE THREAD

**Issue by xiaoken** [fifafu/BetterTouchTool#493]
Errm, macOS is capable of fine tuning audio by pressing shift+option+volume keys
This would be particularly useful when using Siri remote with the mac.
Thanks

**Which versions of macOS and BetterTouchTool are you running?**
10.11.6, 2.07

**Comment by fifafu** [comment]
Current alpha version has new predefined actions to trigger the small volume steps.
