### ISSUE TITLE
lock screen doesn't work

### ISSUE THREAD

**Issue by malpania** [fifafu/BetterTouchTool#497]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

**What kind of Mac are you using?** Imac

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
imac, macbook pro

**Which versions of macOS and BetterTouchTool are you running?** 2.07

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by enki** [comment]
Confirmed. Came here to report the same problem!

**Comment by enki** [comment]
(have keyboard shortcut apple-shift-l mapped to lock screen), and that keyboard shortcut just stopped working.)

**Comment by iTolyan** [comment]
Same problem here!  I have Shift + 4 finger double tap set to Lock screen and it no longer works.

**Comment by iamcaner** [comment]
Confirmed. Shortcut doesn't matter, action just broken.

**Comment by fifafu** [comment]
Hi,

sorry for the bug! A ":" went missing in the code and caused that issue :-)
Version 2.071 I just uploaded should fix this.

**Comment by malpania** [comment]
Fixed in latest version
