### ISSUE TITLE
%@ insert no longer works

### ISSUE THREAD

**Issue by cupcake2** [fifafu/BetterTouchTool#498]
Macbook, El Capitan, Magic Trackpad.

After the latest update, the %@ replace field for URLs doesn't work anymore. It pastes an actual "%@" instead of the clipboard contents.

btw, is there a way to downgrade to the previous version?

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into that. What action are you talking about exactly? 

 You can always download previous versions from https://Bettertouchtool.net/releases 

Also the previous version will always be in your trash after upgrading.

However you may have to reimport an older preset backup as the newer versions often have different formats.

**Comment by fifafu** [comment]
Should be fixed in version 2.071 :-)

**Comment by cupcake2** [comment]
Hi, thank you for your quick response!

The way I use the “%@“ is shown below. I’m a translator, and from my translation application, when I need to research a word, I select it, do a TipTap Left (2 fingers fix), and search is at the URL of a dictionary. I added the Delay because the clipboard needed a moment to work.

For now I’m back to the previous version, works great. I look forward to trying out 2.071 when it’s ready. I LOVE your app,  use it in plenty of other ways too.

Thank you :)
robert
