### ISSUE TITLE
[Feature Request] Open New Desktop Action

### ISSUE THREAD

**Issue by moshed** [fifafu/BetterTouchTool#5]
Currently I'm using a hacked up applescript but it gets wonky sometimes and doesnt work. A nice solution would be to have an action that simply open a new desktop.

MacBook Pro (Retina, 13-inch, Mid 2014)

MacBook Trackpad

macOS 10.12.2 (16C53a)

**Comment by fifafu** [comment]
Could you post your Apple script here?
Maybe I can use it as a base for that feature.

**Comment by moshed** [comment]
oh hey sorry i thought i was using an applescript but at some point i switched over  to just using a bunch of built in actions (probably because i ran into a limitation using AS)
 http://imgur.com/kcIoLvl 
i dunno if that would be reliable enough for you to use

**Comment by fifafu** [comment]
Unfortunately this is more complicated than I thought it would be. I have found some private API that will allow me to do it, but I'll have to move it to the next version.

**Comment by fifafu** [comment]
I have added such an action for the next alpha. It's a bit hacky but there doesn't seem to be a good programmatical solution :-(
