### ISSUE TITLE
Possibility to adjust three, four or five fingers swipe sensitivity

### ISSUE THREAD

**Issue by bstasse** [fifafu/BetterTouchTool#50]
#### Description of my feature request...:

On the new 15-inch Macbook Pro, I noticed that my three fingers swipe gestures are harder to trigger than on previous models: I have to make a bigger movement — which is exhausting :(. I guess this is due to the fact that they are triggered if the fingers move on a certain distance, distance whose value is proportionate to the size of the trackpad (trackpad which is huge on the new MBP...), and not absolute.

My request is to fix this problem, which I think could be done by two ways if my assumptions are correct:
- either by setting the distance required to trigger the swipe gestures with an absolute value, so that it won't change no matter the size of the trackpad;
- add the possibility to adjust three, and even four and five fingers swipe sensitivity, as done for the two fingers swipe;
- or both :)

I hope I did not miss this feature in the interface. Thank you for considering the request and for this amazing app!

**Comment by Grolubao** [comment]
Yes exactly. It's not necessarily to do with BTT, but the sensitivity sucks and it seems not possible to adjust :(

**Comment by fifafu** [comment]
BTT 2.01 added sliders for three and four finger swipes in the advanced preferences. Using those you can adjust the sensitivity.
