### ISSUE TITLE
feedback - software updates

### ISSUE THREAD

**Issue by pedroponte** [fifafu/BetterTouchTool#500]
Hi, just wanted to suggest that the software gets packaged nicely and not updated every week.
I'd suggest the option to set the pref. to check for updates weekly, monthly, every quarter etc so that it doesn't keep running software update checks and prompting us every other day.

**Comment by fifafu** [comment]
Sorry I won't add something like this, however you  can disable automatic update checks in the preferences and just check manually every now and then.
