### ISSUE TITLE
Feature to work with Logitech trackpads?

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#501]
Right now BTT doesn't work with Logitech trackpads. Or probably another non-apple trackpad. Would it be possible to implement it?

I am using the Logitech T651 Wireless trackpad. 

Thanks

**Comment by fifafu** [comment]
Unfortunately Logitech doesn't offer an API for their trackpads thus it's not possible for me.

I have already contacted Logitech a long time ago but was told there are no plans to offer an API.
