### ISSUE TITLE
Cannot copy gestures between preset profiles

### ISSUE THREAD

**Issue by junglg** [fifafu/BetterTouchTool#502]
When attempting to copy App Specific gestures and then switching to another preset profile to paste it there, this does nothing.

The paste menu items becomes 'Paste & union all gestures from '(null)' instead of 'Global' or whatever the app was, as shown in my screenshot.

<img width="511" alt="screenshot" src="https://cloud.githubusercontent.com/assets/25881045/23102999/4edf6d84-f6ab-11e6-95c8-2ca94ffe43a0.png">

**Comment by fifafu** [comment]
This is currently a known limitation (basically the presets defined the complete context of the app).
However I'm reworking this completely and it will soon be possible to copy between applications.

**Comment by fifafu** [comment]
In alpha v2.097 you can now copy between presets. (Cmd + shift+c copies the whole app, cmd+ c copies the selected gestures.)

**Comment by patrickrushton** [comment]
Copying and pasting gestures doesn't work for me (2.281). It would certainly be useful to be able to do this in order to consolidate gestures from multiple presets after syncing via dropbox.
