### ISSUE TITLE
Please add ability to invoke the emojibar like in apple messages in some of the system actions

### ISSUE THREAD

**Issue by owashe** [fifafu/BetterTouchTool#508]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

**What kind of Mac are you using?**

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

have you seen the emoji widget in BTT? It's not the same, but can still get you all the smilies on your Touch Bar :-)

**Comment by jonnyenglish** [comment]
Hey @fifafu this is just out of personal interest: Why is it not the same? It always messes with my clipboard as the emoji gets copied to the clipboard 😄 also the favourites don't update. Do you think it's somehow possible to extract the widget from the messages.app? Already scrolled a bit through the package contents but couldn't find anything but the BTTTouchBarEmojiWidget.nib 😄
