### ISSUE TITLE
Tap + three finger drag doesn't select whole word in Safari with tiptap (3 fingers fix)

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#509]
#### Description of your bug/question/feature request...:
When you tap + three finger drag starting from the middle of a word, the whole word gets selected along with the text you're selecting. With the BTT gesture tiptap (3 fingers fix) active, if you tap + three finger drag starting from the middle of a word, the whole word _doesn't_ get selected. Only the part you started dragging from does.

**What kind of Mac are you using?**
MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Pro Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
> suggestions how to fix

Deleting this gesture ;)

**Comment by fifafu** [comment]
Unfortunately this can't be fixed. BTT and three finger drag is not a good combination as enabling three finger drag significantly changes the behavior of the trackpad. 

Problem is that BTT needs to block left-clicks while three fingers are touching the trackpad when two finger tip taps are used. However the three finger drag requires the left-clicks...
