### ISSUE TITLE
Possibility to disable the BTT touchbar tool whit specific apps.

### ISSUE THREAD

**Issue by davide-piovani** [fifafu/BetterTouchTool#51]
I mean, I have added new touchbar buttons for almost every application which not support touchbar and I always have the BTT touchbar tool active in order to use touchbar with every application.
What I need is that specifics apps which I decide, like itunes or safari for example, show their original touchbar buttons instead that the global buttons I added. #

**Comment by fifafu** [comment]
Hi,

please have a look at the bottom most screenshot here: http://boastr.net/docs/docs/touch_bar.html
