### ISSUE TITLE
Shortcuts not working with Atom & iTerm2

### ISSUE THREAD

**Issue by chmac** [fifafu/BetterTouchTool#515]
* I have app specific shortcuts setup for Atom
  - I have three finger swipe **left** configured to send <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>]</kbd>
  - I have three finger swipe **right** configured to send <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>[</kbd>
* When I press these keys manually in Atom, I switch one tab right or left respectively
* When I 3 finger swipe **left** in Atom, I move one tab to the **left**
  - I should move one tab to the **right**
* When I 3 finger swipe **right** in Atom, nothing happens

**What kind of Mac are you using?**

* iMac (Retina 5K, 27-inch, Late 2014)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

* Magic Trackpad 2

**Which versions of macOS and BetterTouchTool are you running?**

* macOS Sierra 10.12.3
* BTT 2.071

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

I have this same keyboard shortcut mapped to tab-right / tab-left in many other apps. I have 3 finger swipes disabled under Trackpad settings.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
That's weird, I'll look into it. The default in atom is cmd+option+arrow to switch tabs, isn't it? That seems to work fine here.

**Comment by chmac** [comment]
Interesting. I have <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>left</kbd> and <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>right</kbd> mapped to global shortcuts. But if I disable those, then <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>left</kbd> moves one tab left, but <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>right</kbd> does not. Unclear why that is, I've checked my Atom settings and both of those shortcuts are configured.

However, by going through the keymap, I found that <kbd>ctrl</kbd>+<kbd>pg up</kbd> and <kbd>ctrl</kbd>+<kbd>pg dn</kbd> also cycle through tabs. When I map these two to my trackpad gestures, then everything works as I'd expected. The bug still exists, but this is a usable workaround for me.

**Comment by cleverjackal** [comment]
@chmac Why don't use you use the control-tab gestures? I thought they were default?

**Comment by chmac** [comment]
@cleverjackal <kbd>cmd</kbd>+<kbd>tab</kbd> is different. It switches based on last used tab, not based on the next / previous tab to the right / left of my current tab. So <kbd>cmd</kbd>+<kbd>tab</kbd> !=  <kbd>ctrl</kbd>+<kbd>pg up</kbd>.

**Comment by cleverjackal** [comment]
@chmac Ah, now I remember. I remapped it so that control+tab and shift+control+tab actually work as they do in Safari. 

<kbd>hi</kbd>

**Comment by chmac** [comment]
I now have the same problem with iTerm2 v3.0.15. It's exactly the same as the problem I had with Atom. Is there some kind of bug around <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>[</kbd> and <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>]</kbd> shortcuts?

**Comment by chmac** [comment]
Adding to the issue. If I swap the directions so that:

* I have three finger swipe **right** configured to send <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>]</kbd>
* I have three finger swipe **left** configured to send <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>[</kbd>

I see the precise opposite of the behaviour above. The **left** swipe does nothing. The **right** swipe sends the opposite shortcut, the one that is mapped to swiping right.

Is there any way to reset BTT entirely and reimport my settings? I've already tried deleting and recreating these specific settings multiple times, etc.

**Comment by chmac** [comment]
I've just tried changing the next tab / previous tab shortcuts in iTerm via System Settings > Keyboards > Keyboard Shortcuts. I then made the same matching changes in BTT. Exactly the same behaviour, still broken. I've tried resetting all my BTT settings and deleting and reimporting my triggers. Exactly the same behaviour, still broken.

**Comment by chmac** [comment]
I've now tried deleting all my triggers and creating just 1 new trigger. iTerm 2, 3 finger swipe left, send <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>]</kbd>. It sends <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>[</kbd> instead.

**Comment by fifafu** [comment]
Weird, maybe the shift modifier changes the keycode, which keyboard layout/language are you using?

For now I'd recommend to use the "trigger menubar menu item" action instead.

**Comment by chmac** [comment]
@fifafu Phew, I can get back to work now, thanks for the fast reply, workaround works. Good enough for now.

**Comment by chmac** [comment]
Oh yeah, sorry, I have the keyboard set to US although it's physically a UK keyboard with a double height enter key and a £ sign.

**Comment by chrisduong** [comment]
I have the same issue. I have to disable 'shift-command-]' in the Global section to make it worked.

**Comment by fifafu** [comment]
Sorry for not replying earlier :-(

Unfortunately I think I can not solve this in BTT. However the trigger menubar menu-item workaround should work, thus I'm closing here for now.

In case you have questions feel free to comment again.
