### ISSUE TITLE
No pinch actions

### ISSUE THREAD

**Issue by al3xandru** [fifafu/BetterTouchTool#52]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Pinch actions don't seem to work on the Touch bar MBP 13" late 2016. I have enabled the "Zoom in or out" for Trackpad and then defined Pinch actions for 2, 3, 4, 5 fingers. But none triggered any actions.

Playing with the Live viewer, I've noticed that these actions are almost never recognized (I defined some fake ones in the Global).

**What kind of Mac are you using?**

Touchbar MBP 13" late 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

The trackpad of the Touch bar MBP

**Which version of macOS are you running?**

10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

BTT: 1.963 (552)

**Comment by sl1974** [comment]
I encounter the same problem with my TouchBAR MBP 15 " late 2016 with BTT 1.963 and macOS 10.12.1.

**Comment by fifafu** [comment]
Working on it!

**Comment by fifafu** [comment]
Should be fixed in 1.964 alpha

**Comment by sl1974** [comment]
Unfortunately, the problem seems to persist with BTT 1.964. Even after a reboot, two finder pinch in and out gestures don't work.

**Comment by fifafu** [comment]
Mhh, could you check if thumb

**Comment by fifafu** [comment]
Could you please check if thumb filtering is activated in the advanced trackpad settings -> palm/thumb? Only thumb/palm handling should be active

**Comment by sl1974** [comment]
I just checked and thumb filtering is *not* activated.

**Comment by fifafu** [comment]
Weird, it seems to work fine here, but it's possible I'm missing something.

Is pinch to zoom activated in system preferences -> trackpad? (It's the only gesture that needs to be active in system preferences in order to work with BTT)

**Comment by sl1974** [comment]
Pinch to zoom is activated and works fine in Preview, Safari pp. – I’ll try it with my Mac mini and Magic Trackpad 2 this afternoon and will report whether the issue exists there too.

Thanks a lot for your efforts!

**Comment by fifafu** [comment]
Thank you for testing!

I think I may have found something that could be the culprit and just uploaded a new build (1.965)
Let's see if that helps :-)

**Comment by sl1974** [comment]
Thanks for fixing it, pinching is working again with 1.965!

**Comment by al3xandru** [comment]
First quick tests show that 3 and 4 finger pinches work again. I'll do more testing later. Thanks a lot @fifafu!
