### ISSUE TITLE
Single Click Force Touch Advanced Option

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#521]
Can you please add single finger force touch?
I know that it won't be able to filter out normal click, but I can think of many actions where that is ok. For example I have a shortcut where I need to do something under the mouse, so it is fine if the finger first clicks to selected the object and then triggers the force touch command.

**Comment by franklinyu** [comment]
+1, for example I wish to map it to "open link in new tab" in Chrome (by mapping to Middle Click).

**Comment by gennady-lebedev** [comment]
+1, it will be amazing. really want this customization

**Comment by fifafu** [comment]
I have added it with the latest alpha (2.315). It works great as cmd+click to open a new tab in browsers :-) (although many use cases are tricky to realize because of the mentioned left-click that always happens)
