### ISSUE TITLE
When touch bar goes dim, it only comes back partially

### ISSUE THREAD

**Issue by bizplay** [fifafu/BetterTouchTool#524]
When the touch bar goes dim after a few minutes of not being used and BetterTouchTool is active, it doesn't come back fully by touching it. Instead you have to tap in several areas to get it back again.

**What kind of Mac are you using?**
MacBook Pro 15-inch, 2016 with Intel Core i7, 2.9GHz

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
MacOS 10.12.3
BetterTouchTool 2.071 (608)

**Comment by cleverjackal** [comment]
What do you mean by "getting _it_ back again?"

**Comment by bizplay** [comment]
Sorry for the fuzzy description. With "it", I mean the Touch Bar as a whole, or better: the whole set of Touch Bar icons. Here are 3 pictures of what I see when this happens, each after I tapped the Touch Bar another time:
* https://dl.dropboxusercontent.com/u/8616886/github-issue-images/IMG_7353.jpg
* https://dl.dropboxusercontent.com/u/8616886/github-issue-images/IMG_7354.jpg
* https://dl.dropboxusercontent.com/u/8616886/github-issue-images/IMG_7355.jpg

When you touch the dimmed area and happen to hit an icon, the icon will appear back. But as you can see: sometimes it even only pops back partially. This does not seem to happen when BetterTouchTool is inactive.

**Comment by cleverjackal** [comment]
Oh, okay, I see what you mean now. By the way, you can take screenshots of the TouchBar using the shortcut ⇧⌘6

**Comment by bizplay** [comment]
Ah! That I didn't know! :) Thanks for that cool tip.

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
