### ISSUE TITLE
Why doesn't BetterTouchTool's window act like a normal window?

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#526]
#### Description of your bug/question/feature request...:
I've noticed that BTT's window doesn't act like a normal window. I'm definitely not the first person to notice this, but it's been slightly nefarious, so I decided to ask here. I couldn't find anything about it in the issues tracker.

Essentially BTT's window comes up in every single desktop ("space") that you have. When you move to a new space, there's the BTT window! It flashes up but then disappears quickly (which, truth be told, seems a bit annoying). Then there's the fact that when you switch to another application, BTT goes all the way to the back of the app switcher, making it hard to switch back to it again.

This is not an exhaustive list of oddities I've noticed with BTT's window, but it strikes me quite a bit! I just wanted to know exactly *why* this happens, and why (I'm assuming) you (the developer!) decided to leave it in. I would have thought that using Apple's APIs would be _easier_ and allow you to make ana application window that coheres with Apple's standards.

**What kind of Mac are you using?**
MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
N/A

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.3
BetterTouchTool 2.07 (607)

**Comment by fantaaaaaa** [comment]
I am seeing this too and it is quite annoying in my usecase. i switch windows with cmd+tab and when i choose BTTs icon it also briefly appears and dissapears again.

i have absolutely no explanation for this and would love to see if its fixable.
thanks andreas!

**Comment by fifafu** [comment]
I have improved the behavior for the next version ( alpha will be available this weekend).

Thus I'm closing here already, but please comment if the next update (2.08x) doesn't fix your issue.

**Comment by fantaaaaaa** [comment]
technically, andreas still has a few hours :) i'm expecting the new update as much as you are for a few reasons but we need to let the man do his magic.... :)

**Comment by cleverjackal** [comment]
@fifafu Yep, BTT's window now acts normal again. I am overjoyed.

**Comment by fantaaaaaa** [comment]
thanks a lot for fixing this :)
