### ISSUE TITLE
The program doesn't differentiate between Word versions

### ISSUE THREAD

**Issue by jacobmolby** [fifafu/BetterTouchTool#529]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

As the title states the program doesn't differentiate between Microsoft Word versions. I have both Word 2011 and Word from Office 365, but when I choose Word 2011 in BTT to make pinch-to-zoom gestures. They also apply for the Office 365 version, which means the build in pinch-to-zoom feature stop working.

**What kind of Mac are you using?**

MacBook Pro (13-inch, Late 2011) 

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**

macOS Sierra Version 10.12.2

BTT Version 2.071 (608)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or encounter problems, please create a new issue - I'm now much more responsive than a few months ago.
