### ISSUE TITLE
Use fn key for shortcuts

### ISSUE THREAD

**Issue by dploeger** [fifafu/BetterTouchTool#53]
Is it possible to use the fn key on mac keyboards for shortcuts? I've looked at the app settings and googled for a configuration in BTT, but found nothing.

Recording a shortcut using the fn key doesn't work, however.

**What kind of Mac are you using?**

iMac (late 2013)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Keyboard

**Which version of macOS are you running?**

10.12.1

**Comment by fifafu** [comment]
Unfortunately not, you can only use it in key sequences, but not in shortcuts currently.

**Comment by dorian-grey** [comment]
Are you planning make FN available in shortcuts? This would be my most wanted feature!

**Comment by cazssiew** [comment]
In case this applies to you dorian-grey, you can in fact use fn as a predefined action. I did this to activate the standard dictation shortcut.
![screenshot](https://user-images.githubusercontent.com/33767000/33281696-1c76a41a-d374-11e7-9de3-5b717c3b07a2.png)

**Comment by dorian-grey** [comment]
Unfortunately not! :(
As Andreas (and you) pointed out, you can use fn in key sequences, but I need it in shortcuts to remap FN+JKLI to the arrow keys.
