### ISSUE TITLE
Feature Request: Save/restore settings

### ISSUE THREAD

**Issue by patrickmast** [fifafu/BetterTouchTool#531]
Is there a way to save/restore all my settings?

**Comment by fifafu** [comment]
Yes:

![image](https://cloud.githubusercontent.com/assets/8820811/23273409/2de338a2-f9ff-11e6-8222-80ef7cfc676c.png)

**Comment by patrickmast** [comment]
Thank you. Is this saved per application or global?

**Comment by fifafu** [comment]
This saves all configured applications and all their assigned gestures.
There will soon be a better export system which will give you more control about what is exported.

**Comment by jimmyodonnell** [comment]
I'm leaving this to help others who want to load, import, or restore settings on a new or updated machine. I could not find this documented anywhere, and the screenshot above was not representative of my version (macos 10.12.6 Sierra; BTT 2.340 (719)).

To load a backup (in my case, only keyboard settings):

1. Click bettertouchtool icon in menu bar, select `Preferences`.

2. Click `Manage Presets` (bottom left of window; screenshot below)

3. Click `Import`

4. Select your backup file.

![screen shot 2018-02-06 at 9 21 04 am](https://user-images.githubusercontent.com/6019046/35873714-5db79f28-0b1f-11e8-8857-552da12cc71a.png)

**Comment by mliq** [comment]
Does this backup include Advanced/Basic Settings? It seems that it may not, since when clicking "Print current setup" it only shows Gestures.
