### ISSUE TITLE
Sorting of Gestures

### ISSUE THREAD

**Issue by sorttouchtool** [fifafu/BetterTouchTool#532]
I've been using BetterTouchTool for four years. Love it. But I always thought the settings should allow sorting by Gestures. If I click the column header, nothing happens. Can you please allow sorting, maybe alphabetically, as a default behavior when clicking the "trackpad gesture" header? Thanks!

<img width="672" alt="screen shot 2017-02-23 at 7 09 48 am" src="https://cloud.githubusercontent.com/assets/25984071/23264770/675118b0-f997-11e6-9221-e0f51c956326.png">

Macbook Pro 2013 Retina 13

Macbook Trackpad

Latest Versions

**Comment by fifafu** [comment]
Sorry, as BTT allows for manual ordering (which in my opinion is much more important) I can't add alphabetical sorting.

**Comment by sorttouchtool** [comment]
ok thanks

**Comment by sorttouchtool** [comment]
Andreas,

If it is possible, please consider to have a checkbox option within 
advanced, to allow alphabetical sorting by gestures. Thank you!

Tony

**Comment by fifafu** [comment]
Mhm, would that really be helpful though?

I mean, how often do you change the order of your gestures? Just dragging them into the order you desire should be doable or not?

**Comment by sorttouchtool** [comment]
It would help me greatly!

I have so many gestures and yes... I change my gestures at least a few 
times a year. When I want to change a set of gestures (for example, 
attached to four finger tap), I have to go back and search for the 
gestures within my list, because I haven't ordered them before. And then 
I get duplicates etc, if I haven't been able to check the entire list 
for all previous instances of four-finger tap.

Interestingly, at some point when I clicked on the modifier column 
header, the list would re-sort based on the modifier! I am afraid to try 
it now, because it totally messed up the order :)  But I assume it still 
does that.

If you would consider, I would be really grateful!

Regardless, this program really makes the Mac awesome - really thankful 
for it.

Tony

**Comment by fifafu** [comment]
Ah, the modifier key column shouldn't be sortable :-) I'll fix that.

I'll check if I can add a advanced setting, but I'm not sure yet.

**Comment by sorttouchtool** [comment]
Thanks!

**Comment by chrisduong** [comment]
Please make it happens

**Comment by fifafu** [comment]
Sorry after looking at this again I decided it's currently not feasible to make gestures sortable (would require various changes in the data model setup). You'll need to reorder them manually.
