### ISSUE TITLE
Screen keeps dimming on my Macbook Pro with touch bar

### ISSUE THREAD

**Issue by lazee** [fifafu/BetterTouchTool#533]
When running BTT and Show MacOS control strip is turned off the screen keeps dimming. Even though I have everything off in energy settings. 

I'm on a new MacBook Pro with touch bar and latest Sierra.

**Comment by fifafu** [comment]
Hey,

which screen?
I don't think BTT can cause screen dimming, have you maybe enabled automatic brightness adujustment in System Preferences => Displays?

**Comment by fantaaaaaa** [comment]
might be related to this?: https://github.com/fifafu/BetterTouchTool/issues/357

**Comment by lazee** [comment]
Ah, thank @fantaaaaaa . This seems to be the problem yes. The weird thing is that I have disabled brightness adjustment in System Preferences. But lets close this one @fifafu and I will make sure to test as well and follow the #357 thread. Thank you for your hard work on BTT!

**Comment by fantaaaaaa** [comment]
maybe this is closed now?
