### ISSUE TITLE
Left thumb resting on touchpad uppper left corner is disturbing BTT

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#534]
#### Description of your bug/question/feature request...:
I have the new MBP with touchbar and since the touchpad is quite bit my left palm tends to rest on the uppper left corner of it. this causes BTT to sometimes trigger wrong or no gestures. for example it swiping gestures or more-finger-taps get interpreted incorrectly. maybe due to wrong finger coun since it seems to recognize the thumb as a finger...

![img_3527](https://cloud.githubusercontent.com/assets/24585031/23275018/2453b32e-fa05-11e6-993a-dd0cd2ed58c1.JPG)

this leads to about 10-30 erratic gesture actions throughout one day, which is really quite annoying and might frustrate many of the users of the new MBP with the huge trackpad.

is there a way to fix this or to ignore a certain area of the trackpad in BTT?
i would really love your input and would love to participate in feedback and testing.
thanks a lot andreas

**What kind of Mac are you using?**
2016 MacBook pro with TouchBar

**Comment by fifafu** [comment]
You can activate thumb filtering in the advanced settings (however some gestures won't be possible while that's active):

![image](https://cloud.githubusercontent.com/assets/8820811/23275183/cb259a78-fa05-11e6-95ca-b43d231127ca.png)

**Comment by fantaaaaaa** [comment]
<img width="1127" alt="screenshot 2017-02-23 20 27 55" src="https://cloud.githubusercontent.com/assets/24585031/23275377/95c7a3c0-fa06-11e6-8bed-1ae9911ef8c0.png">

i already have this enabled, it does not seem to do the trick.

i also remember that i am having issues when using the macbook in bet since the lower border seems to get confused but i guess that might be another issue?

**Comment by fantaaaaaa** [comment]
Hey andreas! Any idea on this?

**Comment by fifafu** [comment]
I will add stronger thumb detection for the upper corners soon. Currently I don't think there is a solution. (Maybe the "disable trackpad gestures after hitting a keyboard key" option could help, depending on your usecase)

![image](https://cloud.githubusercontent.com/assets/8820811/23342830/60479496-fc61-11e6-81a8-824359a29f52.png)

**Comment by fantaaaaaa** [comment]
<img width="1127" alt="screenshot 2017-02-27 07 55 45" src="https://cloud.githubusercontent.com/assets/24585031/23351570/42ca4b96-fcc2-11e6-8c1b-ebcfa31f884d.png">


is this supposed to help here? then i would track if the issue still persists...

and if this helps, would it maybe possible to add how big the area is and add the bottom arrea as an option too? when in bet, the shirt or blanket always interfere and BTT will miss out on gestures...

**Comment by fantaaaaaa** [comment]
@fifafu have you been able to figure something out here? i tried your setting above (it was already activated for a long time) but i can reproduce the problem pretty well by just resting my left thumb in the upper left corner... happens in at least 4 out of 10 gestures, which is pretty heavy

**Comment by fifafu** [comment]
I'll add dedicated options to ignore the corners of the trackpad soon. I'll make it configurable so you will be able to choose how much to ignore.

For now you could try these two terminal commands while BTT is closed.
```
defaults write com.hegenberg.BetterTouchTool BTTIgnoreTrackpadTop YES
defaults write com.hegenberg.BetterTouchTool BTTIgnoreTrackpadTopValue 0.7
```
0.8 means that the top 20% of the trackpad would be ignored.

**Comment by fantaaaaaa** [comment]
Appreciate to quick workaround but are you sure ignoring the complete top bar for gestures is a good solution? Could it be possible to exclude 20of the top + 20% of the left? just the upper corner?

**Comment by fifafu** [comment]
yep, as mentioned I'll options to ignore only the corners soon.

**Comment by fantaaaaaa** [comment]
Sorry for not readying properly! Any ETA on this maybe? 2.1?

**Comment by fifafu** [comment]
Yes, not sure if the UI will be ready then, but it will be possible using terminal commands.

**Comment by fantaaaaaa** [comment]
That would be perfectly fine for me! :) Thanks a lot, excited to have this nasty problem gone soon!

**Comment by fantaaaaaa** [comment]
Does this work with BTTIgnoreTrackpadBottom too?

defaults write com.hegenberg.BetterTouchTool BTTIgnoreTrackpadBottom YES
defaults write com.hegenberg.BetterTouchTool BTTIgnoreTrackpadBottomValue 0.2

did not do the trick to disable the lower bottom of the trackpad.

**Comment by fifafu** [comment]
Nope, there is no setting for the bottom yet.

**Comment by fantaaaaaa** [comment]
<img width="571" alt="screenshot 2017-03-03 00 30 34" src="https://cloud.githubusercontent.com/assets/24585031/23531838/b4373954-ffa8-11e6-9d81-af0802084da6.png">

i have been able to reproduce the behaviour in the live view: i am doing the 3 finger swipe up gesture every second and as soon as i place my thumb on the upper left corner it will either stop registering my swipes as long as i dont remove the thumb or it will randomly register 3 finger swipes down instead of 3 finger swipes up. that happens also with 3 finger swipes left and right (they mistakingly get reversed) i guess that has to do with the thumb not being filtered out properly. interestingly, the thumb is not always visible as a finger in liveview when the behaviour above happens...

i hope that was maybe helpful in your solution?

**Comment by monstermac77** [comment]
I also have the 2016 Macbook Pro and this is driving me completely crazy. 

Very much appreciate BetterTouchTool for coming to the rescue.

**Comment by monstermac77** [comment]
Would it be possible to disable all input from the top 20% of the trackpad? My issue is that even normal pointing of the mouse is getting interfered with by my thumb resting on the top left corner of the trackpad.

**Comment by fantaaaaaa** [comment]
unfortunately the new option to filter thumbs in resting on the top edges does not seem to help me at all :/ i have activated it but as soon as my thumb is on the upper left corner my gestures stop to work (for exampe three finger swipes in safari for switching tabs).

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu item). I have changed the palm/thumb recognition quite a bit, let's see if that helps

**Comment by fantaaaaaa** [comment]
After some minutes of testing it seems much better. I've made a reminder to give you some more feedback in a day or two after proper use. Thanks @fifafu, very much appreciated!

**Comment by fantaaaaaa** [comment]
Seems fine now, thank you!!!
