### ISSUE TITLE
BTT is not logging Touchbar actions together with the other usage

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#535]
#### Description of your bug/question/feature request...:

<img width="1127" alt="screenshot 2017-02-23 20 20 56" src="https://cloud.githubusercontent.com/assets/24585031/23275277/30ba01d0-fa06-11e6-9af0-10664b848151.png">

BTT logs keyboard shortcuts and and snapping perfectly and i find it really useful but it does not yet log touchbar actions. I would like to track those to the same way all the others are possible already.

thanks for considering this!

**What kind of Mac are you using?**
2016 MacBook Pro with Touchbar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Tochbar

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.4

**Comment by fifafu** [comment]
Yep, I'll add this soon!

**Comment by fantaaaaaa** [comment]
Oh man, you are too quick. I wasn't even done editing my post and you already replied 👍
