### ISSUE TITLE
BTT Click and Tap Top Corners & BTT Slowing Computer

### ISSUE THREAD

**Issue by JRDNXr** [fifafu/BetterTouchTool#536]
1. In BTT versions 1.51 and earlier, I used to be able to click the top right and top left corners without the program thinking it was a tap. Now (in later and current versions) whenever I go to click a corner, it recognizes the click, but immediately after lifting my finger it inputs a tap (I tested this using the "Show Live View" monitor). Was this change done on purpose?

2. I have over 100 keyboard gestures (most of these gestures are opening links into a web browser). It is slowing my computer down a bit. I'm wondering if I have too many gestures or if this is a BTT bug?

Using a Mid-2015 MacBook Pro 15-inch Retina, 16 GB of memory running on macOS v10.12.3. I'm currently running BTT v2.071. I have restarted my computer and tried shutting down other applications that use a lot of ram in the hopes it would speed up BTT. It didn't work.

**Comment by fifafu** [comment]
Thanks for reporting. 1.) definitely seems to be a bug. I'll fix that with the next update.

100 shortcuts is a lot, however it still shouldn't be noticeable because the shortcuts are completely handled by the system. Are you sure your system gets faster if you quit BTT?

**Comment by JRDNXr** [comment]
1) Anytime, and thank you! Very much appreciated. I know this sounds bad, but do you know when you will release the updated version? You don't have to answer this if you can't or don't want to.

2) Yes, it is. I press the option key on the far right then tap three letters on my keyboard that align with the website name. For example, CNN: option(r)+C+N+N will automatically open up a new tab and go to CNN.

But to answer your question yes. (Mail and Notes were already opened). I had BTT running and switched between Chrome to Mail and tried to start scrolling. It lagged noticeably. I went back to Chrome, disabled BTT for all apps, then went to Mail again. I was instantly able to scroll. I did the same with other apps (Notes, iTunes, etc.) and was instantly able to scroll. I enabled BTT again from Chrome and did the same process but the lag was noticeable.

**Comment by fifafu** [comment]
The corner click issue should be fixed with the new alpha (2.08)

**Comment by JRDNXr** [comment]
I can verify that is has worked on my end. Thanks a ton!
