### ISSUE TITLE
Right tip-tap became harder

### ISSUE THREAD

**Issue by RubenVerborgh** [fifafu/BetterTouchTool#537]
#### Description of your bug/question/feature request...:

I frequently use right tip-tap. Since the latest version, more than half of my right tip-tap gestures fail. I have to do it with much more emphasis.

**What kind of Mac are you using?**

2011 MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**

10.9.5 – 2.05 (605)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by RubenVerborgh** [comment]
It seems that the allowed distance between fingers has become smaller.

**Comment by fifafu** [comment]
Hey,

You can change the max allowed distance in the advanced settings in BTT.
Maybe this will fix the issue for you.

**Comment by RubenVerborgh** [comment]
@tifafu Which setting exactly? I can't seem to find it.

(Has this changed recently BTW? I didn't have problems before with this gesture—it's by far my most common one.)

**Comment by fifafu** [comment]
Sorry I was on the train earlier.
Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/23324921/778f683e-faf1-11e6-98f8-892d8524ce3a.png)

**Comment by RubenVerborgh** [comment]
That's where I looked, but I don't have this option (BTT 2.05):

![image](https://cloud.githubusercontent.com/assets/675313/23331069/4beae10a-fb5e-11e6-9171-20336bc9b0c0.png)

**Comment by fifafu** [comment]
ah sorry, just noticed you are on 10.9.5.
There the only way to change it is via terminal command: (while BTT is quit)
```defaults write com.hegenberg.BetterTouchTool BTTMaxTipTapDistance 0.7```

**Comment by RubenVerborgh** [comment]
Indeed, that does the trick!
