### ISSUE TITLE
Rocker mouse gestures

### ISSUE THREAD

**Issue by emattias** [fifafu/BetterTouchTool#54]
#### Description of your bug/question/feature request...:
I would like support for rocker gestures for a normal mouse. I found [this little video](https://www.youtube.com/watch?v=NsQctzyqxto) showing what rocker gestures are!

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Normal mouse

**Comment by fifafu** [comment]
Hi,

sorry, this would require some deeper changes in BTT and I currently don't think I will add this feature. I'll close this issue for now, but keep it in mind!

Best,
Andreas
