### ISSUE TITLE
Click and drag with Magic Mouse

### ISSUE THREAD

**Issue by Benambridge** [fifafu/BetterTouchTool#540]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Hi - BTT is working great, and I'd never need to click the horrible Magic Mouse buttons again IF ONLY I could figure out how to do dragging. Does this feature already exist? And, if not, are you going to implement it at any point? (Sorry if this has been asked before - I could only find these types of question relating to trackpad use)

**What kind of Mac are you using?**

2012 Macbook Pro Retina

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**

10.12.3 / 2.071

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

if you have enabled "double tap to drag" in the advanced settings (it's on by default) you can configure a single finger tap mapped to leftclick and it will let you drag if you double tap.

![image](https://cloud.githubusercontent.com/assets/8820811/23324829/b8add6e4-faf0-11e6-808b-f8371d0b81aa.png)

![image](https://cloud.githubusercontent.com/assets/8820811/23324862/ff157f1a-faf0-11e6-8dbe-f958c81b03d0.png)
