### ISSUE TITLE
Backup/Restore settings?

### ISSUE THREAD

**Issue by Nxt3** [fifafu/BetterTouchTool#542]
Is there a way to backup all of our settings? I know about the presets, but do I have to do that for each application specific commands?

**Comment by fifafu** [comment]
Presets include all applications

**Comment by Nxt3** [comment]
Awesome, thank you!

**Comment by mbigras** [comment]
Hi @fifafu,

I'm trying to automate the configuration of my BetterTouchTool installation.
I exported my triggers. It looks like the configuration is a JSON file.

Is it possible to place the JSON file somewhere in the `~/Library/Application\ Support/BetterTouchTool/` directory?

I looked in that directory but it looks like they hold a bunch of sqlite databases.

Is there some way to automatically import the settings?

Thank you!

**Comment by fifafu** [comment]
@mbigras it will be loaded automatically if you name it .btt_autoload_preset and put it directly in your user directory

**Comment by mbigras** [comment]
@fifafu Thank you for the quick response!

>put it directly in your user directory

Do you mean my home directory or my Application Support directory or a different directory?

I put it in both spots; however, my configuration isn't loading:

```
file ~/.btt_autoload_preset ~/Library/Application\ Support/BetterTouchTool/.btt_autoload_preset
/Users/max/.btt_autoload_preset:                                             ASCII text
/Users/max/Library/Application Support/BetterTouchTool/.btt_autoload_preset: ASCII text
```

Is the contents of .btt_autoload_preset sensitive?
Would it help if I posted it?
