### ISSUE TITLE
Feature request - remove image/icon

### ISSUE THREAD

**Issue by istrasci** [fifafu/BetterTouchTool#543]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Can you please move this image out of the way (as well as the one on the **Trackpads** tab)?  It covers up part of the gesture in that column.

**What kind of Mac are you using?**

MBP 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

No input device affected

**Which versions of macOS and BetterTouchTool are you running?**

macOS - 10.12.3
BTT - 1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

<img src="http://i.imgur.com/5VuPkUz.png" alt="commercial photography locations">

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by cleverjackal** [comment]
I personally find it very helpful!

**Comment by fifafu** [comment]
Sorry, I like it there and I think the tradeoff of saving space/obstructing the view is OK. Just add some separator gestures at the end so you can scroll down ;-)

**Comment by istrasci** [comment]
Fair enough. Thanks for your consideration.
