### ISSUE TITLE
Feature Request: Add "Move Window to Previous Monitor" action

### ISSUE THREAD

**Issue by cH40z-Lord** [fifafu/BetterTouchTool#544]
#### Description of your feature request:

Right now I'm on a three monitor setup using BTT and I'm desperately missing a `Move Window to Previous Monitor` action, especially since there is also one for `Move Window to Next Monitor` action.

**What kind of Mac are you using?**

Mac Book Pro Late 2016 TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

All

**Which versions of macOS and BetterTouchTool are you running?**

BetterTouchTool Version v2.071 (licensed)

**Comment by fifafu** [comment]
Yep, I'll add this!

**Comment by clothmother** [comment]
I would love this feature!

**Comment by Nosskirneh** [comment]
I would also appreciate this feature!

**Comment by sebastianhaberey** [comment]
Yes, this would be great!

**Comment by cH40z-Lord** [comment]
Is there a rough ETA when we might get it? I'm dying in a large multi-monitor setup without it. :)

Thanks again for your hard work. Really appreciate it.

**Comment by fifafu** [comment]
Tracking this here: #514  (it probably will be added with one of the next versions, soon!)
