### ISSUE TITLE
[ENHANCEMENT] Better looking gesture drawing window

### ISSUE THREAD

**Issue by SteveJobzniak** [fifafu/BetterTouchTool#548]
My gold standard for gesture drawing slickness on the Mac is https://www.jitouch.com/characters/ (see the video there).

Nice, thick, antialiased lines. Unobtrusively draws directly onto the screen (emanating from a "start position dot" in the middle of the screen), and with hints as to what character it is detecting your drawing as. And has no ugly "overlay square" (the way BTT does it). No thin, emaciated lines. It just looks great!

Try it for some inspiration. :-) Hopefully BTT's drawing window can look as good one day. ;-)

**Comment by fifafu** [comment]
You can configure the overlay background  and line color in the advanced settings.

I'm leaving this ticket open, but it's very unlikely that there will be big changes to the drawing mode.

**Comment by SteveJobzniak** [comment]
Good idea. I was able to make it look less intrusive by making the drawing area a bit smaller, more transparent and changing the line color to calm blue instead of angry red. Thank you for that!

Now it looks quite good and less geeky! ;-)

**Comment by SteveJobzniak** [comment]
@fifafu Would it be possible to have a slider for making the drawing lines thicker? They look anorexic. 👯  ;-)

**Comment by SteveJobzniak** [comment]
@fifafu Thank you so much for 2.08 and all your incredible work, Andreas! The drawings look great at stroke width 6px on this screen! :)
