### ISSUE TITLE
Color reset button in Touch Bar Item Customization Options doesn't save

### ISSUE THREAD

**Issue by R-V-S** [fifafu/BetterTouchTool#55]
System: Late 2016 Macbook Pro with touch bar

OS: macOS 10.12.1

When editing touch bar item customization options by clicking on the gear on the left, clicking the "reset color" icon appears to work – the color changes back to the default on the menu. However, the change does not save after hitting the "Save" button. Only changes made through the "Colors" pop-up window seem to save.

**Comment by pauloruberto** [comment]
Having the same issue here, came to report it as well.

**Comment by fifafu** [comment]
Fixed in 1.964 alpha
