### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by troutymtl** [fifafu/BetterTouchTool#550]
Using a Mcbook with toutch.  For some reason my version of touch no longer works as previously. I can no longer display access to my applications?  When I am in a created application the various menus no longer show up?  Any ideas?

**Comment by fifafu** [comment]
Have you already tried to restart your Mac?

**Comment by troutymtl** [comment]
I have it comes up then dissapears again.

Luc Nocente
Ln@norpix.com<mailto:Ln@norpix.com>
Tel: 514-824-2517




On Fri, Feb 24, 2017 at 5:52 PM -0500, "Andreas Hegenberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you already tried to restart your Mac?

**Comment by fifafu** [comment]
I'm not exactly sure what you mean. Do you maybe have screenshot or a video?

**Comment by troutymtl** [comment]
Basically my custom touch bar no longer comes up. It no longer appears





Luc Nocente
Ln@norpix.com<mailto:Ln@norpix.com>
Tel: 514-824-2517




On Fri, Feb 24, 2017 at 6:07 PM -0500, "Andreas Hegenberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not exactly sure what you mean. Do you maybe have screenshot or a video?

**Comment by troutymtl** [comment]
I’ll let you know, seems to work now.

Luc Nocente
Ln@norpix.com<mailto:Ln@norpix.com>
Tel: 514-824-2517
