### ISSUE TITLE
TipTap Left (2 Fingers Fix) conflicts with TipTap Left (1 Finger Fix)

### ISSUE THREAD

**Issue by SteveJobzniak** [fifafu/BetterTouchTool#554]
Found this now: If I put two fingers on the trackpad, and then tap with a 3rd to the left, it still always triggers "1 finger fix" (which is 1 finger on the trackpad, and then tap with a 2nd to the left).

I know you've got various code to make BTT decide which gesture the user wanted if some gestures are similar. I guess this is another case needing that. :-)

**Comment by fifafu** [comment]
Mhh I don't think this can happen, but if it does it's definitely a bug. Could you check in the live view if it really detects a 1 finger fix tip tap in that case?

I can't seem to reproduce this here, but maybe it's related to the trackpad type.

**Comment by SteveJobzniak** [comment]
@fifafu Oh, I just discovered the cause! I had old leftover "TipTap Left (2 Fingers Fix)" actions under "Safari" for my old BTT profile. And I was working on Global actions and doing all testing in Safari, so I didn't notice! Doh.
