### ISSUE TITLE
[BUG] Drawing Direction & Certainty Not Saving

### ISSUE THREAD

**Issue by SteveJobzniak** [fifafu/BetterTouchTool#555]
"Required recognition certainty to trigger" is always 0.7. And "Drawing direction does NOT matter for this gesture" is always off.

Changing them and clicking "Finish & Save Gesture" does nothing.

**Comment by fifafu** [comment]
Should be fixed in the latest alpha (2.08). I have also added a stroke-width setting and a max-rotation slider.

**Comment by SteveJobzniak** [comment]
@fifafu Thanks so much! It's fixed. Settings are now saved.

And thanks so much for the stroke width and rotation. I'm very happy with the drawing engine in BetterTouchTool now :) Looks nice and detects accurately!

By the way I found someone's old, related ticket that you can also close: https://github.com/fifafu/BetterTouchTool/issues/45
