### ISSUE TITLE
[ENHANCEMENT] Drawings misdetect most complex form instead of simplest one

### ISSUE THREAD

**Issue by SteveJobzniak** [fifafu/BetterTouchTool#556]
Alright, I'm done porting all settings from Jitouch to BTT and uninstalling Jitouch. Great to be back home!

I did however notice that the drawing recognition engine doesn't pick the closest (simplest) drawing.

Here's an example:

- A: A straight line going right, like this: o------>
- B: A straight line going right, exactly like the above. But then it goes straight DOWN after that. Like half of a "T".

So I trigger BTT's drawing window, and draw only a line going to the right (A)...

And it picks... B. The more complex form, which I wasn't even remotely close to drawing.

It also picks things like my N shape and so on, when I draw a single straight line going to the right.

I don't know what's going on. Is the engine not tuned towards picking the closest match first?

I've attached my BTT preset file here. You can try them all. The straight-line ones (left, right, / up, / down) are the worst. Any ideas how this can be improved?

[BuggedDrawing.zip](https://github.com/fifafu/BetterTouchTool/files/800778/BuggedDrawing.zip)

I wanted to try using the "gesture recognition certainty" to perhaps fix it, but as shown here, it's bugged: https://github.com/fifafu/BetterTouchTool/issues/555

Well, I'm in no rush to get this resolved. So don't mind me. :-)

**Comment by fifafu** [comment]
Hey,

Straight lines are currently not supported by the algorithm but I'll add an additional recognition layer for those soon.

See http://docs.bettertouchtool.net/docs/drawings.html

**Comment by SteveJobzniak** [comment]
@fifafu Oh that explains it.

I've resorted to using more complicated shapes now.

But I also noticed something else: A character like "N" and "Z" are basically the same thing but rotated by 90 degrees. And the algorithm seems to have some "fuzzy matching" to allow such rotations during drawing. And that in turn means that the Z is always detected as N (probably because it is tested earlier in BTT's comparison tree, and the rotation is accepted).

So I guess that needs some tweaking (or better yet a user-configurable slider) to say "how much is a drawing allowed to be rotated before we ignore it during matching?".

**Comment by fifafu** [comment]
@SteveJobzniak yes that's true. I'll limit the max allowed rotation to something like 20 degree for the next version. Making it per-drawing configurable may not be possible though - I will check that.

**Comment by SteveJobzniak** [comment]
@fifafu Thanks, sounds like that small change will make things a lot more helpful. I struggled today with coming up with shapes I hadn't already used. ;-)

Btw I didn't mean rotation per-drawing.  I meant a global slider in the advanced settings. 20 degrees may be a bit too narrow, but maybe 45. That's half of a 90 degree rotation.

**Comment by SteveJobzniak** [comment]
@fifafu Thank you so much for 2.08! Wow. The stricter rotation rules means that drawings aren't constantly misdetected anymore <3 👍
