### ISSUE TITLE
TouchBar not working with all apps

### ISSUE THREAD

**Issue by BrianSiimAndersen** [fifafu/BetterTouchTool#558]
I have downloaded and installed the CEWE Photoworld app (https://cewe-photoworld.com/). But when I create app specific TouchBar buttons for it, they never appear in the touchbar.

I have app specific TouchBar buttons for several apps and all others work fine. In BTT they all appear with name and icon. But the CEWE app only shows the name and not the icon - so it looks like the app is somehow not supported.

Screenshot from BTT:
![image](https://cloud.githubusercontent.com/assets/3057386/23330459/7f43ba5a-fb4e-11e6-8230-86781b551223.png)

**Comment by fifafu** [comment]
Hey, I'm tracking this issue here: #354 
There will be a solution soon.
