### ISSUE TITLE
Adding more usage statistics

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#559]
Would it be possible to add more usage statistics for BTT? For example, the trackpad TipTap gestures. I really like those stats!

**Comment by fifafu** [comment]
Hey,

yes I'll be adding the remaining missing things to the statistic soon!
However I think tip taps should already be included?

Best,
Andreas

**Comment by cleverjackal** [comment]
Thanks! I'm on 2.071 (608) and I have no tip taps in my usage section. I tried it just now. Also I had exactly 1000 gestures as I checked right now :) and I installed it just under a week ago after our email conversations. Would have had more though with the tip taps ;)

**Comment by fifafu** [comment]
Weird, what action have you assigned to the tiptaps?

**Comment by cleverjackal** [comment]
For the two finger tip taps, I've assigned **⌃⇥** and **⌃⇧⇥**

For four finger ones I've assigned **⌘W** and **⌘T**

They're in global

**Comment by cleverjackal** [comment]
@fifafu Do you want me to provide more information about the issue? They still don't show up for me using the latest alpha version in usage :(

**Comment by cleverjackal** [comment]
@fifafu You see, I need to be able to show off to my friends how much I use BTT

**Comment by fifafu** [comment]
I'll add more usage statistics this weekend ;-)
I think there may actually a bug that causes the statistics to ignore gestures that trigger keyboard shortcuts. I'll fix that.

**Comment by cleverjackal** [comment]
Thaaaank you!

**Comment by fifafu** [comment]
Just fixed it, alpha release will be on Tuesday or Wednesday.

**Comment by cleverjackal** [comment]
Can't wait :) thanks!

**Comment by cleverjackal** [comment]
@fifafu I noticed that although I remapped ⌘Y to ⌘+Shift+Z, when I press ⌘Y, it doesn't get registered in the usage statistics.

**Comment by fifafu** [comment]
Yes, that was the bug I mentioned above :-) Will be fixed with the update.

**Comment by cleverjackal** [comment]
Ahh okay. Now I understand :) thanks

**Comment by cleverjackal** [comment]
@fifafu Still no update? I'm getting my pitchfork ready... 

&nbsp;

&nbsp;

&nbsp;

&nbsp;

:D

**Comment by cleverjackal** [comment]
@fifafu could you pleaseeee upload this one alpha update? If you do, I will be happy. This is the only bug I really would like to be fixed and since (I think) you've fixed the problem, I guess all you have to do is upload it. Thanks! :)

**Comment by cleverjackal** [comment]
@fifafu THANK YOU! I just noticed that the new build was uploaded. My prayers have been answered. Thanks again!!!
