### ISSUE TITLE
app switch widget

### ISSUE THREAD

**Issue by elfraty** [fifafu/BetterTouchTool#562]
app switch widget on latest MBP touch bar 15". Works fine BUT after deactivating apps in the macosx dock they do not disappear immediately from the touch bar, but stay visible, as if still active . wouldn't it be nice if the really did disappear instantly after deactivating them in the dock?

Much obliged,

Elzo

**Comment by fifafu** [comment]
This should be fixed in the latest alpha (v2.097)
