### ISSUE TITLE
Can "X" be removed from BTT Touch Bar?

### ISSUE THREAD

**Issue by anas2204** [fifafu/BetterTouchTool#565]
**What kind of Mac are you using?**
Macbook Pro 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Is there a way that I can remove the "X" from the Left end of the BTT Touch Bar. I just wish to have "esc" but not the "X" to close (Since it is buggy and requires me to tap BTT twice).

**Comment by fifafu** [comment]
No that's not possible.

See #163
