### ISSUE TITLE
Space being put in before text insertion in Ulysses

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#566]
#### Description of your bug/question/feature request...:
After using a keyboard shortcut to "Paste Custom Text", a space is placed before the text string in [Ulysses](https://ulyssesapp.com).

1. Create new keyboard shortcut
2. Set it to Option + P or something like that
3. Use it to "Paste Custom Text" such as "Text"
4. In the app, try the shortcut. A space is always inserted before "Text" although this doesn't happen in other apps.

**What kind of Mac are you using?**
MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Keyboard

**Which versions of macOS and BetterTouchTool are you running?**
macOS 12.1.3.
BTT v2.071 (608)

**Comment by fifafu** [comment]
Mh, does that also happen if you press cmd+v in that app?

**Comment by cleverjackal** [comment]
Uhh... yeah. Yes, it does. I don't know how you figured that one out!
