### ISSUE TITLE
Search for selected text with youtube

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#568]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Feature request for the search selected text with youtube

**What kind of Mac are you using?**
MacBook Pro 15" 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
trackpad

**Which versions of macOS and BetterTouchTool are you running?**
10.12.4,2.071

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
You can use the "Open URL" action with this url: "https://www.youtube.com/results?search_query=%@"

The %@ will automatically be replaced by the selected text.
