### ISSUE TITLE
Misplaced action list in keyboard section.

### ISSUE THREAD

**Issue by benwubbleyou** [fifafu/BetterTouchTool#569]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

**What kind of Mac are you using?**

I am using a hackintosh, so it may be the machine.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

My Logitech K750 Wireless Keyboard

**Which versions of macOS and BetterTouchTool are you running?**

Yosemite and newest BTT.

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

![screen shot 2017-02-26 at 10 52 00 am](https://cloud.githubusercontent.com/assets/14141760/23342570/e074cbc0-fc11-11e6-9f20-fa54d4f08ee2.png)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Weird, Yosemite seems to interpret the layout differently... Could you try if the new alpha (2.08) fixes this?
