### ISSUE TITLE
[Bug] Screenshot touchbar presets disappear

### ISSUE THREAD

**Issue by anas2204** [fifafu/BetterTouchTool#571]
**What kind of Mac are you using?**
MBP 2016 with Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
BTT 2.071
macOS 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

For Chrome, I have selected the setting: "Show BTT Touch Bar; Show Control Strip", which is the 2nd setting in Touch Bar behavior. The default TouchBar screenshot button is on my EXTENDED Mac Control strip. When I click that, instead of the usual Screenshot options (Selected Portion/Window/etc), it goes back to my BTT Touch bar icons.
However, this doesn't happen when my BTT bar is not open (which isn't the behavior I want). Is this a bug or there is no workaround it?

**Comment by anas2204** [comment]
@fifafu

**Comment by fifafu** [comment]
Unfortunately this is a limitation given by the Touch Bar API. I currently can't fix that.
