### ISSUE TITLE
BTT icon goes to the back in app switcher menu

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#573]
#### Description of your bug/question/feature request:

The BTT icon goes to the back of the app switcher (the one when pressing ⌘⇥).

1. Make sure you have a few apps open
2. Open a full screen Safari window
3. Open the BTT window on top of that (by using Spotlight or the menu bar icon)
4. Click on the Safari window
5. Press ⌘⇥. You'll see that the BTT icon is the last one in the app switcher, although it should be the second one

**What kind of Mac are you using?**
MacBook Pro

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.3
BTT v2.08 (610)

**Comment by fifafu** [comment]
I have no idea what could be causing this. BTT doesn't actively interfere with the app-switcher, thus I think this is a bug in macOS. I'll open an issue with Apple about this but will close here for now as I don't think I can change the behavior.

I assume it has to do with the fact that BTT is a background app which changes it's type to a foreground app when the preferences window becomes visible.
