### ISSUE TITLE
Support X11 / XQuartz Window Snapping

### ISSUE THREAD

**Issue by haz-mat** [fifafu/BetterTouchTool#575]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Feature request to support snapping of X11 windows

MacBook Pro 15" 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Keyboard shortcuts, edge snapping

**Which versions of macOS and BetterTouchTool are you running?**
BTT 2.071
OSX 10.12.13

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi,

I'm very sorry but this won't be added to BTT. Personally I don't have any app that still uses X11, thus my motivation to work on this is very small (I know it's somehow possible but a lot of work).

I'm not sure if there are other window managers for macOS that support X11, but maybe it's worth looking into other options!

Best,
Andreas

**Comment by haz-mat** [comment]
No worries @fifafu thanks for your response. I figured it wasn't reasonably possible but thought I'd ask.

**Comment by jeremybundgaard** [comment]
As someone who works on remote linux clusters analyzing physics data many hours daily, having x11/xQuartz window snapping is so nice!! 

I use [ShiftIt](https://github.com/fikovnik/ShiftIt) to handle my basic window snapping eg left/right, corners, maximize...and I use BTT for more elaborate snapping like 1/3 or 2/3 left/right which I love for my dual screen interface.

Cheers
