### ISSUE TITLE
Can't copy, paste, or delete with shortcuts keyboard gestures that run AppleScripts

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#576]
#### Description of your bug/question/feature request...:
It's not possible to do the above using keyboard gestures for the action of running an AppleScript.

**What kind of Mac are you using?**
MacBook Pro

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.3
BTT v2.08 (610)

**Priority:**
Low

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
