### ISSUE TITLE
Need more Predefined Actions

### ISSUE THREAD

**Issue by enphit** [fifafu/BetterTouchTool#58]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
It's a cool App, and there are many predefined actions, but some common actions can not be found, and I strongly need them, such as 
quit app
switch to previous tab(some app has many tabs)
switch to next tab
close current tab
copy
paste
and more...

of course those actions can  be success by keyboard shortcut, but 
1.shortcut changes between apps
2.shortcut can only work to focused windows, but predefined actions can work to window below mouse cursor.
3.sometime shortcut doesnot work, but predefined actions always works well.

so, I hope there will be more predefined action, tks!

**What kind of Mac are you using?**

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which version of macOS are you running?**

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by moshed** [comment]
you can send keystrokes to no  activated apple apps through applescript (i think) let me know if you need something specific i might be able to help you if andreas decides to not incorporate this request

**Comment by fifafu** [comment]
Hi,

the general rule I follow is to add predefined actions only if it's not doable by keyboard shortcuts or menubar items.

Predefined actions can't work on "the window below the mouse cursor", this works only for some specific things.

However I think one predefined action I should add is "send keyboard shortcut to window below cursor"

**Comment by enphit** [comment]
thanks

**Comment by fifafu** [comment]
The predefined action "Send Shortcut to Specific App" now supports to send the shortcut to the app below the mouse cursor .
