### ISSUE TITLE
Trackpad becomes non functional on using five finger gesture to create new file in current folder and clicking cancel.

### ISSUE THREAD

**Issue by adityareddy67** [fifafu/BetterTouchTool#581]
System: MacBook Pro 2016, 15 inch with TouchBar

Input Device: MacBook Trackpad

Using macOS 10.12.3 and BTT 2.071 (608)

Issue: I set up 5 finger click for a new file in the current folder (from system actions under predefined actions). When I use click using 5 fingers, the window pops up asking me to enter the filename, and two options: cancel or OK. Whenever I click cancel whole trackpad becomes non functional, I can move cursor using trackpad but taps don't get recognized, and just can't click or force click on trackpad, the trackpad just doesn't move. Have to bring up activity monitor and force quit BTT using touch bar to get trackpad functional again.

**Comment by fifafu** [comment]
Fixed with 2.15 alpha (will be available in about two hours)
