### ISSUE TITLE
Move window to next desktop doesn't work for System Preferences

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#582]
#### Description of your bug/question/feature request...:
The action "Move window to next desktop" doesn't seem to work for System Preferences, although it does work for other windows.

**What kind of Mac are you using?**
MacBook Pro 

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.3
BTT v2.08 (610)

**Comment by fifafu** [comment]
Mhh, this seems to work fine here. Are you sure you can still reproduce this? Which System Preferences pane did you have open?

**Comment by cleverjackal** [comment]
@fifafu That's funny, now it works for me too. Wait, though! I have another "bug" to report. You've probably seen it. It happens to me for any window. When I move the window to another desktop using the shortcut, the mouse moves from its position to some other position, and then moves back again. You've seen this before, right?

**Comment by fifafu** [comment]
Hehe, this is how it moves the window to another space. 
It uses a relatively unkown feature of macOS - if you drag a window and simultaneously press the keyboard shortcut to switch spaces, it will take that window to the other space. BTT does exactly this. It moves the mouse to the top left of the window ( right next to the window buttons), then triggers a space switch while keeping the mouse pressed

**Comment by cleverjackal** [comment]
@fifafu Oh wow, that's really cool! Didn't know about that before :)
