### ISSUE TITLE
False detecting TipTap until scroll with two fingers

### ISSUE THREAD

**Issue by alexesnsk** [fifafu/BetterTouchTool#583]
I use TipTap Right (1 finger) and TipTapLeft (1 finger) to switch tabs.
The problem is that when I scrolling content up and down using two fingers - I'm getting false detecting these TipTap events and switching tabs.

Settings:
![Settings](https://cloud.githubusercontent.com/assets/10667619/23453007/22b18fe4-fe99-11e6-9ff8-fd4a17be14e1.png)

**BTW: why don't add native tab switching action - instead emulating it in menu?**

**What kind of Mac are you using?**
MacBook Pro 13 2016 with touch bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

TrackPad

**Which versions of macOS and BetterTouchTool are you running?**
Sierra, BetterTouchTool is 2.071

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

It affects afters restart. ALso I tried different settings to decrease sensitivity of gestures - no results. Same false events.

**Comment by cleverjackal** [comment]
@fifafu Sometimes I get this too. I'm not sure how to reproduce it, but it seems to happen randomly sometimes when I'm just trying to scroll.

**Comment by fifafu** [comment]
yes I also get that sometimes. I'm investigating what causes it.

**Comment by fifafu** [comment]
This should be fixed with alpha 2.15 (will be available in ~2hours)

**Comment by cleverjackal** [comment]
Nice, I'm excited to try it out! Thanks!
