### ISSUE TITLE
BTT Freezing during execution of TouchBar Applescript

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#584]
Hi Andreas,

is there a way not to freeze up BTT and the Touchbar when i initiate an AppleScript Widget. Some of them take quite a few seconds to execute fully and its sad that you can not use BTT in this time until the applescript is done...

**Comment by fifafu** [comment]
What exactly do you mean by initiate an Apple Script widget?

**Comment by fantaaaaaa** [comment]
<img width="1099" alt="screenshot 2017-03-02 22 11 55" src="https://cloud.githubusercontent.com/assets/24585031/23527195/473a3f62-ff95-11e6-9116-1fe5bb4387b6.png">

this is an example script thats running on a remote computer and taking a few seconds. during this time, BTT locks up completely and wont respond...

i would guess that scripts that run locally but take longer will also lock up BTT?

**Comment by fifafu** [comment]
Ah! So not a widget but just the "run apple script" action. Indeed, this action doesn't run on a background thread yet (this wasn't supported on previous macOS versions). I'll fix this with the next alpha.

**Comment by fantaaaaaa** [comment]
I also have scripts running in an Apple Script Widget (on button press) which might take longer, same issue here.

**Comment by fifafu** [comment]
Yep, but the apple script widget scripts (those that update the text on the widget) already run on a background thread. Only the run apple-script predefined action blocks the app.

**Comment by fantaaaaaa** [comment]
perfect, thanks for letting me know. I am looking forward to the next alpha :)

**Comment by fantaaaaaa** [comment]
i see that 2.084 still has the same behaviour. unforuntately its not possible to anything BTT related while the schript above is running? :(

**Comment by fifafu** [comment]
There is a new action to run apple script asynchronously in the background. The old synchronous one still works like before.

**Comment by fantaaaaaa** [comment]
Nice, thanks it works!
