### ISSUE TITLE
Pinch in + out stop working randomly

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#585]
Since a few weeks i notice that the default gestures for pinching stop working randomly. I dont have any gestures assigned to this in the apps where they stop working so it seems that BTT conflicts with the system gestures. Other gestures continue to work.

A restart of BTT helps or toggling pinch gestures in system settings.

Any idea? Pretty annoying :)

**Comment by hanul0310** [comment]
i have same problem....pinch zoom is not working in basic application like photos, safari....

**Comment by fifafu** [comment]
It's possible that this has been fixed by the latest btt alpha (v2.097)

**Comment by james-rose** [comment]
Pinching in and out stopped working completely for me for the last few weeks.  Tried it on Chrome and Safari.   
MBP 15 2015
Sierra 10.12.6
BTT 2.293

**Comment by fifafu** [comment]
@james-rose are you sure pinch and rotate is enabled in system preferences => trackpad => scroll & zoom? It seems to be working fine here with the latest version.

**Comment by james-rose** [comment]
@fifafu That fixed it.   I don't remember deselecting it, but I must have.   Thanks.
