### ISSUE TITLE
Aluminium Apple Remote not working 

### ISSUE THREAD

**Issue by dbahnan** [fifafu/BetterTouchTool#588]
I am trying to use an aluminium Apple remote with a 2009 iMac running macOS Sierra and BTT 2.071 but nothing happens when I map the buttons to actions. 
Thanks

**Comment by fifafu** [comment]
Hey,

are you sure the Apple Remote plugin is activated in BTT? Does the Remote work without BTT? (e.g. for iTunes?)
![image](https://cloud.githubusercontent.com/assets/8820811/23526669/31259f48-ff93-11e6-97c2-2ccbec9b71a4.png)


Best,
Andreas

**Comment by dbahnan** [comment]
Hi Andreas,

Yes I've made sure the Apple Remote plugin is checked. I also unchecked it,
restarted BTT, rechecked and restarted BTT. The remote is working with
iTunes and the rest of the computer and I checked it's reliability on
photobooth. If no one else is having this problem, is there anything else I
can do?

Thanks,
Dylan.

On 2 Mar 2017 8:57 p.m., "Andreas Hegenberg" <notifications@github.com>
wrote:

Hey,

are you sure the Apple Remote plugin is activated in BTT? Does the Remote
work without BTT? (e.g. for iTunes?)
[image: image]
<https://cloud.githubusercontent.com/assets/8820811/23526669/31259f48-ff93-11e6-97c2-2ccbec9b71a4.png>

Best,
Andreas

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fifafu/BetterTouchTool/issues/588#issuecomment-283777823>,
or mute the thread

**Comment by dgbeecher** [comment]
I'm using BTT 2.071, and I may be having the same problem. I have "Enable Apple Remote Plugin" checked in advanced preferences. But, when I control-click at the black bar at the top of my gestures list to try to add a tab for Apple Remote, it is not there as an option. (I see "BTT Remote" and "Siri Remote" but no other kinds of remotes.) I am hoping to be able to use my old white plastic Apple Remotes with BTT, which is something I used to be able to do. Thanks and let me know if I can help troubleshoot this.

**Comment by fifafu** [comment]
@dgbeecher the old apple remote is hidden under the arrow (as there are almost no users left with a mac that supports them): 
![image](https://cloud.githubusercontent.com/assets/8820811/24884317/2539cd74-1e49-11e7-8c78-8816b1a30047.png)

However I'm currently unable to test it, because I also lack a Mac with an integrated IR receiver...

**Comment by dgbeecher** [comment]
Thanks, that looks promising! But, I do not see the greenish arrow that you have in your screenshot. There is just a black space to the right of the "Other" tab. I've tried hovering in that area, control-clicking there, holding down various modifier keys ... How do I find the green arrow?

**Comment by dgbeecher** [comment]
Ah, yes that works, and now I can see my old Apple Remote gestures again, which I thought had vanished! Cool, thank you for figuring this out for me! I appreciate the continued support for my old computer and remotes :)
