### ISSUE TITLE
Allow altering Icon of Apple Script Widget (like altering the color)

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#590]
Would it be possible to implement the possibility to toggle two icons depending on the return of an apple script? Instead of having only one icon we would have two,

thanks!

**Comment by fifafu** [comment]
Yes, I'll add this soon.

**Comment by fifafu** [comment]
Included in next version.

**Comment by fantaaaaaa** [comment]
THANK YOU! THIS IS A HUGE IMPROVEMENT! 💯
