### ISSUE TITLE
[Bug] Some global shortcuts not working on external keyboard

### ISSUE THREAD

**Issue by cphorvath21** [fifafu/BetterTouchTool#591]
#### Description of your bug/question/feature request...:
In the latest update of BTT, some of my global shortcuts on my external keyboard have stopped working but normal laptop keyboard is fine. I then tried upgrading to latest alpha version as well, and issue persisted. 

This includes the main shortcuts I use - Maximize Window Left (control option left), Maxmize Window Right (control option right), Maximize Window (control option up), Move window to next monitor (control option command right), among others. Some shortcuts I have for other such as CMD Shift control 4 (mapped to F13),  CMD Shift 4 (F14), and other individual application shortcuts still work. 

**What kind of Mac are you using?**
MP 13" early 2015 model

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
External keyboard via USB (A1243)

**Which versions of macOS and BetterTouchTool are you running?**
OS X El Capitan 10.11.6
2.08

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Screenshots of my settings are given below. Must have something to do with the latest release of BTT as it coincided with the update. I've also tried restarting computer. Could it be related to OSX I'm running?
![btt screenshot of shortcuts](https://cloud.githubusercontent.com/assets/26130805/23493173/e51f967e-ff5d-11e6-9859-aa320c9eb805.png)

**Comment by fifafu** [comment]
Mhh that's weird, BTT doesn't differentiate between keyboards.
Have you already tried to restart your system?

**Comment by cphorvath21** [comment]
Thanks for the reply. Yeah I thought it was quite strange as well. When I opened my computer this morning from sleep, I was able to do these particular shortcuts for about 15s with the external keyboard, and but then it stopped working again. I've just completed another restart of my system but the issue persists.

**Comment by cphorvath21** [comment]
Hi again, strangely enough it just started working again the other day. I haven't been able to figure out the reason why, but am quite glad to have it back in working order
