### ISSUE TITLE
Double tap 4 finger trackpad gesture crash on screenshot

### ISSUE THREAD

**Issue by tamo888** [fifafu/BetterTouchTool#592]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

When pressing the escape key or cancel for taking a screenshot, BTT will crash (4 finger double tap). This is on a trial version but this does not happen on the paid version.

**What kind of Mac are you using?**

MacBook Pro 15" 2017 with Touch Bar.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

MacBook Trackpad.

**Which versions of macOS and BetterTouchTool are you running?**

2.071 & also the latest alpha version.

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into this and add a fix very soon.

**Comment by fifafu** [comment]
Mhh I can't seem to reproduce this. Could you send me a screenshot or export of your exact setup?

**Comment by tamo888** [comment]
Let me ask the user who's experiencing this as he's on the trial version.

**Comment by fifafu** [comment]
Can you still reproduce this? I'm closing for now, if this still happens please reply here.
