### ISSUE TITLE
Logitech T651

### ISSUE THREAD

**Issue by Gkyl** [fifafu/BetterTouchTool#596]
Description of your bug/question/feature request...:

Is it possible to support Logitech T651 bluetooth trackpad ?

What kind of Mac are you using?
Mac Pro 2008

Which versions of macOS and BetterTouchTool are you running ?
El Capitan
BTT 2.71

**Comment by fifafu** [comment]
Sorry, unfortunately Logitech doesn't offer an API for their trackpads thus I can't support them in BTT.

**Comment by Gkyl** [comment]
:(
