### ISSUE TITLE
[BUG] Settings Button Look and Use

### ISSUE THREAD

**Issue by ZV95** [fifafu/BetterTouchTool#6]
Hello!

I was able to reproduce an issue with one of the more advanced settings buttons, when trying to add a new TouchBar shortcut. 

To reproduce: 

1. Make a TouchBar shortcut that relies on a Custom Keyboard Shortcut instead of a Predefined Action.  
2. Upon completion, clicking the settings button directly to the right of that area will illuminate a larger area than the button** and then fail to perform any actions. 

** this occurs on both the keyboard shortcuts and on predefined actions

I believe this should be corrected by either eliminating the button when Keyboard Shortcuts are used, OR by giving additional settings for those shortcuts (though, not entirely sure what that would be). 

A video is included to detail the issue: 
[Incorrect Behavior with Serttings Icon.zip](https://github.com/fifafu/BetterTouchTool/files/629758/Incorrect.Behavior.with.Serttings.Icon.zip)

Version 1.955 (545) Alpha // 10.12.2 Beta (16C53a)
MacBook Pro (15-inch, Late 2016)
2.6 GHz i7 // 16GB // 256GB // Radeon Pro 450 (2GB)

**Comment by fifafu** [comment]
Thanks for reporting and thanks for the video. Just fixed it and will upload a new build shortly.
