### ISSUE TITLE
"Momentary hold" keyboard shortcut for BTT Touch Bar

### ISSUE THREAD

**Issue by andrewatwood** [fifafu/BetterTouchTool#60]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Sort of got it set up how I'd like with additional actions and attaching 'Toggle Touch Bar' to any Touch Bar shortcuts, but I'd really like a feature like the built-in 'hold Fn to see F keys/expanded Touch Bar' but with the BTT Touch Bar. I don't necessarily want it to always show up but I do want to be able to quickly use it, dismiss, and get back to the normal app/OS Touch Bar if I'm not always showing the BTT Touch Bar for that app.

**Comment by fifafu** [comment]
You can already do that. Just configure it like in the screenshot below. (Add the shortcut twice, make one of them trigger on key down by pressing the little gear icon)

![image](https://cloud.githubusercontent.com/assets/8820811/21074365/6320646a-bef7-11e6-9123-3f667373dbba.png)
