### ISSUE TITLE
Bug: BTT stops working if the main interface has not been launched for some time

### ISSUE THREAD

**Issue by Proxy305** [fifafu/BetterTouchTool#602]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/question/feature request:

BTT stops working on my Mac if the main interface has not been launched for some time. I will have to relaunch the application from launchpad, spotlight etc. to have it work again.

#### What kind of Mac are you using?

MacBook Pro (Late 2016, 15 inch)

#### Input device affected (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar):

All, BTT simply stopped working.

#### BetterTouchTool and macOS version:

macOS 10.12.3

BetterTouchTool v 2.071 (Evaluation version)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
