### ISSUE TITLE
Trackpad gestures on MacBook Pro 2016 15"

### ISSUE THREAD

**Issue by PazzaVlad** [fifafu/BetterTouchTool#603]
#### Description of bug/question/feature request:
I've noticed little problem with trackpad gestures on the new MacBook Pro 2016 15": in compare to MacBook Pro Retina 2012 (or Air), I have to swipe much longer distance to make swipe gesture works. Maybe it's because of larger trackpad, I don't know... Apple "system" gesture works great, but gestures that was added using BTT need more hand movement to work. Can it be fixed?

#### What kind of Mac are you using?
MacBook Pro 2016 15"  (base model)

#### Input device affected (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar):
Trackpad

#### BetterTouchTool and macOS version:

macOS 10.12.3 

BetterTouchTool v2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I'me using these gestures.
![screen shot 2017-03-03 at 21 25 44](https://cloud.githubusercontent.com/assets/7755205/23565903/3610ab9a-0058-11e7-9790-e02ca5efae1d.jpg)

P.S. Thank you for such an amazing program!

**Comment by PazzaVlad** [comment]
P.P.S - Adjusting sensitivity doesn't solve the problem and seems like doesn't work on my mac at all (try to set sensitivity to min and max and didn't notice any difference).

**Comment by gustavoavena** [comment]
I think I'm having the same issue...
I just traded my MacBook Pro 13" (2015) for a 15" MacBook Pro with Touch Bar.

I've noticed that my trackpad gestures are not working as well as before... I use _3 Finger Double Tap_
all the time to play/pause my music and BTT is not recognizing it well anymore. I would say it only recognizes it 30% of the times...

With my old MacBook Pro, BTT worked flawlessly. =(

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
