### ISSUE TITLE
How to disable global shortcut for a specific app?

### ISSUE THREAD

**Issue by Grogs** [fifafu/BetterTouchTool#608]
#### Description of bug/question/feature request:
I want the Function keys to be media keys, except in one application (IntelliJ IDEA).

I do this by:
* Configuring then as Fn keys in OSX
* Adding Global shortcuts to make them media keys
* Add shortcuts for IntelliJ IDEA to make them Fn keys.

Unfortunately, this doesn't quite work:
* If I press a modifier key (e.g. shift) plus an Fn key, it works as expected.
* If I press an Fn key by itself... It acts as a media key... And stays pressed forever until I change app.
  * So it acts like it's using the Global setting not the app specific one. And locks on.

#### What kind of Mac are you using?
Mid-2015 MBP with Yosemite (10.10.5)

#### Input device affected (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar):
Keyboard

#### BetterTouchTool and macOS version:
Yosemite (10.10.5)

BetterTouchTool v2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Workarounds: 
* Disable BTT for app (but I lose all the other stuff I want enabled!)
* Modifier+Fn key still works, which is 50%+ of my usage
* When I press an Fn key and it repeatedly presses... Then I Cmd+Tab apply and it stops.

This has happened for a long time, I just never reported it. I think Fn key without a modifier used to just do nothing rather than pickup Global behaviour and infinitely repeat though.

Global keyboard shortcuts:
<img width="1021" alt="screen shot 2017-03-04 at 20 54 40" src="https://cloud.githubusercontent.com/assets/1212907/23582201/e49c79cc-011c-11e7-9314-46bc6dd1a461.png">

IntelliJ overrides:
<img width="1022" alt="screen shot 2017-03-04 at 20 54 57" src="https://cloud.githubusercontent.com/assets/1212907/23582204/f304a174-011c-11e7-8ba1-2fa6008304da.png">

**Comment by cleverjackal** [comment]
Interesting. When I have a function key as an override in Karabiner Eventsviewer, it doesn't seem to recognize the function key as a normal function press.

**Comment by fifafu** [comment]
@Grogs I think you should be able to fix this by unchecking the "Enabled Checkbox" for those shortcuts in IntelliJ. BTT will then use the system default.

**Comment by cleverjackal** [comment]
@Grogs Additionally if BTT's method doesn't work for you, you could use [Fluor](https://seo-michael.co.uk/fluor-for-macos/) as it does exactly what you're trying to achieve.

**Comment by Grogs** [comment]
Thanks for the responses!

Unchecking the 'Enabled' checkbox didn't help, it fell back to the Global shortcut. Changing it to "Use Apple Default or do nothing" also didn't work. In both cases they just operated as media keys.

I've now installed Fluor which is doing what I need. Thanks @cleverjackal for pointing out Fluor. Thanks @fifafu for the suggestions - I really expected the "Use Apple Default or do nothing" approach to work.

I'll close this as I can use Fluor, but I do consider this a bug in BTT...

**Comment by fifafu** [comment]
@Grogs that's weird this seems to work fine here. Are you sure in System Preferences they where set to be F Keys?
