### ISSUE TITLE
Better Key Mapping

### ISSUE THREAD

**Issue by lbrndnr** [fifafu/BetterTouchTool#61]
I mainly use BTT to remap some keys. So in oder to write letters like ö ä or ü I use a shortcut to invoke the 'paste custom text' action predefined by BTT. This works pretty good, apart from the fact that it's kind of slow. Whenever I use the specified shortcut, it lags for an instant. 

I was wondering whether it would be possible to make a new action that allows the user to remap keys as described above which is preferably a little faster. I think many people that come from Karabiner would really appreciate an improvement in this direction. What do you think?

Thanks anyways for this great app, I love it :)

**Comment by fifafu** [comment]
Unfortunately BTT works very differently than Karabiner and will never be as fast for key remapping.

However the paste custom text is especially slow for various reasons. I'll add new action that will be significantly faster for typing characters, however it will still not be as fast as Karabiner!

**Comment by lbrndnr** [comment]
That sounds perfect! :)

**Comment by fifafu** [comment]
In the current alpha version the paste custom text action supports two modes "by pasting" and "by typing". One of them may be faster depending on the use case. 

Unfortunately it probably won't get faster than that.
