### ISSUE TITLE
Test issue (please ignore)

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#612]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Hardware/software:

Device type:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cleverjackal** [comment]
How do I delete this

**Comment by fifafu** [comment]
Github doesn't allow to delete issues as far as I know.

**Comment by cleverjackal** [comment]
oops
