### ISSUE TITLE
Delay desktop switching on side edges during window snapping

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#616]
#### Description of bug/feature request/question:

There is an option in BTT to "Delay Mission Control on top edge". This is very useful because when dragging a window to the top edge, normally macOS activates Mission Control. This option makes it harder to activate Mission Control by dragging the window to the top, which allows you to make windows fullscreen via dragging.

However, when moving a window to the left or right side of the screen, the desktop is usually changed very easily. Would it be possible to delay this desktop switching as well?

**Comment by fifafu** [comment]
You can use this terminal command (2.0 is the delay in seconds):
```
defaults write com.apple.dock workspaces-edge-delay -float 2.0; killall Dock
```

**Comment by cleverjackal** [comment]
This is awesome, thank you
