### ISSUE TITLE
Drawing Gesture Window not showing up until movement of finger?

### ISSUE THREAD

**Issue by eggplantsplz** [fifafu/BetterTouchTool#617]
Having an issue with the draw feature window not showing up until after you start the gesture.

In the past, the big black box indicating draw mode is active would show up upon triggering the draw command. It doesn't do that anymore - currently on version 2.8 using Sierra 10.12.4 Public Beta. 

Let me know if you need more information. I currently have "Draw Mode" to be triggered via bottom right trackpad tap. It does indeed work (and as soon as I move my finger to draw the action, the black box shows up); but sometimes I'm wondering if I properly trigged draw mode to begin...

Thanks!

**Comment by fifafu** [comment]
That's true there has been a change to prevent the drawing feature from starting the recognition before the mouse moves. (Mainly because now right-mouse drawing is possible and you wouldn't want to show the highlight window on every right-click).

I'll add an option to adjust that behavior.

**Comment by eggplantsplz** [comment]
Cheers. Appreciate the continued app development as always.

**Comment by fifafu** [comment]
So I have just modified the behavior a bit:
Starting with v2.09 alpha the area will be highlighted if triggered by anything but a right-click. I'm closing here already but please let me know in case this doesn't fix your issue.

v2.09 alpha should be available sometime on Tuesday.
