### ISSUE TITLE
Caps Lock

### ISSUE THREAD

**Issue by charmaex** [fifafu/BetterTouchTool#619]
#### Description of bug/feature request/question:
I would love to be able to map my caps-lock button to another button/sequence.
Since I've got the new MBP I mapped my caps lock button to escape.
While I don't use caps lock this often there are cases where I would like to enable it. 
I thought of double tap shift to toggle caps lock. But unfortunately BTT isn't supporting caps lock and using Karabiner Elements to map F19 to caps lock and then use BTT to trigger F19 wasn't working either.

**Comment by fifafu** [comment]
I have just added a "Toggle Caps Lock" predefined action, it will be available with the next alpha sometime this week.
