### ISSUE TITLE
TouchBar Customizations DIsappear

### ISSUE THREAD

**Issue by jbhelicon** [fifafu/BetterTouchTool#623]
(*) Create global customizations; they appear in the touchBar
(*) As soon as I click out to another application, they all disappear
I'm assuming this is some simple settings issue, but i'm baffled on where to look next

New MacBook Pro with the TouchBar, running Sierra 10.12.3

**Comment by milesmarkstein** [comment]
I've had luck with adding every application individually (so they're listed under Global, under where it says "Select Application:"). Then, for each I clicked the settings button (the gear icon next to "App Specific"), went down to "Touch Bar Behavior", and selected "Show BetterTouchTool Touch Bar, hide system Control Strip". A mild pain in the ass, but worked solidly for me, even after restarts.

**Comment by jbhelicon** [comment]
Hi Miles,
That seems to work; thanks so much for the help!
Cheers
J
