### ISSUE TITLE
Repeat action while shortcut is pressed not working.

### ISSUE THREAD

**Issue by juskaiser** [fifafu/BetterTouchTool#626]
#### Description of bug/feature request/question:

The shortcuts are not being repeated after selecting "Trigger on Key down instead of key up" and "Repeat action while shortcut is pressed". I am using Karabiner-Elements to change my caps lock key to an option key. Then in BTT I am using the capslock(now option) key with (j,k,l,i)  as shortcuts to trigger arrow keys.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Native keyboard on Macbook Pro Retina (11,5)

#### Device information:

Type of Mac: Macbook Pro Retina (11,5)
macOS version: OSX Sierra 10.12.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[Screenshot of my preferences](https://www.dropbox.com/s/37ndpedly9aeiom/Screenshot%202017-03-07%2012.52.59.png?dl=0)
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.
