### ISSUE TITLE
Thumb rejection of 2 finger right click doesn't work when "3 Finger Clickswipe Up" gesture is set

### ISSUE THREAD

**Issue by nrmilstein** [fifafu/BetterTouchTool#629]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I set the gesture "3 Finger Clickswipe Up" in an app (e.g. setting it to command-n in Chrome or Firefox), then I can no longer use the system default right click gesture (2-finger click) with my thumb resting on my trackpad. If I remove the gesture, it functions properly again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (13-inch, Mid 2010)
macOS version: 10.12.3
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu). I have changed the palm/thumb recognition quite a bit, let's see if that helps

**Comment by nrmilstein** [comment]
Yes, it appears to be working properly again in the Alpha release. Thanks!
