### ISSUE TITLE
upload image sound settings

### ISSUE THREAD

**Issue by johnypony3** [fifafu/BetterTouchTool#631]
#### Description of bug/feature request/question:
i just started using the screenshot shortcut, its awesome that i can upload to imgur, but even if i have the 'no sound' setting enabled for the screenshot, it makes an awful notification sound when the upload has completed. please allow this to be configurable to off.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
all host devices

#### Device information:

Type of Mac: mac book pro late 2013
macOS version: sierra 10.12.3 (16D32)
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

you should be able to deactivate the notification sound in System Preferences = Notifications:

![image](https://cloud.githubusercontent.com/assets/8820811/23721386/d6aa245e-0441-11e7-8842-fe6d05b36262.png)
