### ISSUE TITLE
needing to restart BTT whenever i retart computer

### ISSUE THREAD

**Issue by bobqwerty** [fifafu/BetterTouchTool#633]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

i need to restart BTT when ever i restart my computer - the program is open, the trackpad short cuts just dont work

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook pro trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version: X yosemite 10.10.1
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

this only started happening with recent updates 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by alexanza** [comment]
I got something similar when I woke up the macbook sometimes btt shortcut are not working until I restart btt or put it to sleep and woke up again, happening since 2.08 too

**Comment by taiyangc** [comment]
I have the exact issue as @alexanza, started happening with recent builds. I am on 10.12.3 btw. After waking up from sleep shortcuts don't work. But if I open Preferences window and close again, BTT will work without a restart. Seems that BTT never wakes up unless Preferences is accessed.

**Comment by andoro** [comment]
For me the same. It's very annoying :(
What I see is: there is an error when I open the Magic mouse gestures. It says driver error?
BTT restart solves the issue.

**Comment by jayk3368** [comment]
Same here. Issue has been going on for at least about a month now, if not longer. After waking from sleep, I will need to restart BTT or open up Preferences. 

Funny thing is, it only happens on my MacBook Air, while I've had no problems on my iMac. Both are running the latest public version of macOS and BTT.

**Comment by JKGisMe** [comment]
Same for me on a MacBookPro... essentially every time I go to use BTT it's closed and I have to reopen. I didn't know what triggered it but sleep would make sense since I'm waking/sleeping my laptop all day.

**Comment by sundarv85** [comment]
+1 Me too. Will be good if this is fixed.

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
