### ISSUE TITLE
[FEATURE REQUEST] Custom Hot Corners

### ISSUE THREAD

**Issue by sausehuhn** [fifafu/BetterTouchTool#636]
As one of those people who indeed still use hot corners, I would love to see BetterTouchTool support. 

macOS only supports up to four hot corners. That includes modifier keys. There’s no way use _hot corners_ + _hot corners with modifier keys_. This way, one could use hot corners for app switching to specific frequently used apps, occasional actions like screen saver or locking the screen etc. 
And of course one could use _Mission Control and Immediately Show Desktop Previews_ with hot corners.

Maybe there’s also a way to draw custom hot corner areas (could be useful for multiple monitor setups). But that’s just an idea for an additional feature.

**Comment by fifafu** [comment]
Hey,

BTT supports hot corners including modifier keys, although their area is not configurable.
See this screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/23809632/b6a9a01a-05ce-11e7-8ab6-594c68268a18.png)

**Comment by sausehuhn** [comment]
Huh! Completely missed that. Well – good work then, thanks for the heads up! I’ll definitely check this out. Keep up the good work!
