### ISSUE TITLE
[Feature Request] Disabling BTT for specific app

### ISSUE THREAD

**Issue by hachi8833** [fifafu/BetterTouchTool#637]
I'd be glad if you'd add a feature to disable BTT's global keyboard settings on specific app.

We can add/customize keyboard settings for specific app, but no way to disable that for specific app.

(As for me, I'd like to disable BTT global keyboard settings only for RubyMine; RubyMine reserves several functions keys F1-12, and BTT blocks them.

Best regards,

**Comment by cleverjackal** [comment]
Create function keys actions in RubyMine remapping for example F1 to F1. It will virtually be "blocked"

**Comment by fifafu** [comment]
You an assign the "Apple Default or do nothing" action for that app:

![image](https://user-images.githubusercontent.com/8820811/37531781-72380c8a-293d-11e8-895c-1b8a1a8b34be.png)
