### ISSUE TITLE
Feature Request: Edit existing IP Address for BBT Remote

### ISSUE THREAD

**Issue by petemackay** [fifafu/BetterTouchTool#638]
My IP is not dynamic in my school, so I have to set it up each day so I can teach with BTT and my phone. Currently, I have to delete the entire configuration from the previous day and start over. My feature request is to be able to edit a current setting. Typically, I only need to change the last 2 or 3 digits...

**Comment by fifafu** [comment]
Mhh, that's already possible, isn't it? Just click the edit button on the top right in BTT Remote.

**Comment by petemackay** [comment]
You're right! I tried that but the red DELETE function shows up - I did not go further, thinking it was the only option. Thanks for the reply and the tip.
