### ISSUE TITLE
4 finger swipe down with thumb rejection

### ISSUE THREAD

**Issue by m3kwong** [fifafu/BetterTouchTool#64]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
There seems to be a bug on CMD + 4-finger swipe down with conjunction with the new new thumb rejection.

It works first time, but if I continue to rest my palm on it and try it a few more times, it will not recognize the gesture anymore till i completely lift it up and then try again.

**What kind of Mac are you using?**
Macbook pro 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
trackpad

**Which version of macOS are you running?**
Sierra

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi,

sorry that's currently a limitation of the palm/thumb recognition. For the four finger swipes it's required to really do them with only four fingers on the trackpad. If I wouldn't do it like that five finger swipes wouldn't work anymore.

I'll work on this in future updates.

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu item). I have changed the palm/thumb recognition quite a bit, let's see if that helps
