### ISSUE TITLE
Crashing every 30m since update to v2

### ISSUE THREAD

**Issue by AdamDrobotij** [fifafu/BetterTouchTool#641]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

BetterTouchTool silently crashes every 30m or so since the latest update. Restarting does not solve the issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All devices - the software itself.

#### Device information:

Type of Mac: Macbook Pro Retina 15-inch, Mid 2015
macOS version:  Sierra 10.12.3
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

that's definitely not normal, you could either try to update to the latest alpha (2.08) or to download a fresh copy from my website, maybe your local copy somehow got corrupted.

**Comment by cleverjackal** [comment]
You could even try the alpha version if it still doesn't work, I guess

**Comment by cleverjackal** [comment]
@AdamDrobotij try the latest alpha. It might solve this issue.
