### ISSUE TITLE
Alt + Click in OSX Menu Bar Broken

### ISSUE THREAD

**Issue by Infrabass** [fifafu/BetterTouchTool#643]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hey!

I wanted to report a bug with BetterTouchTool.
The possibility of alt+click some OSX menu bar icon to show some advanced settings seems to be broken.
If I just deactivate BTT it's working again.

Thanks for the support.

#### Device information:

Type of Mac: MacBookPro Mid 2012
macOS version: 10.10.5
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I don't think this can be related to BTT (unless you have some strange config in the normal mouse tab in BTT)

![image](https://cloud.githubusercontent.com/assets/8820811/23815100/b955d532-05e6-11e7-9d71-291245216e84.png)

**Comment by cleverjackal** [comment]
Alt click work for me on my Trackpad

**Comment by cleverjackal** [comment]
@Infrabass Duplicate your profile and procedurally delete items until the issue doesn't occur anymore. Then you can get to the bottom of the issue.
