### ISSUE TITLE
If "trigger on mouse cursor touches menubar" is set, it should resume normal function when not touching it

### ISSUE THREAD

**Issue by zivzulander** [fifafu/BetterTouchTool#644]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I'm trying to set scroll on menubar to change desktops (I like how in Ubuntu you can do it when the mouse if hovering over the desktop) but it causes scroll to no work anywhere else. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal Mouse

#### Device information:

Type of Mac: iMac
macOS version: 10.12.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I have fixed that for the next alpha (sometime this weekend), however I'm not sure how good it will be performance wise (BTT needs to check whether Dock or Menubar is being touched on every scroll event).
