### ISSUE TITLE
Forward-Delete repeat

### ISSUE THREAD

**Issue by mark3785** [fifafu/BetterTouchTool#646]
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

I'm using BTT to provide Forward-Delete by using Shift-Delete, but found that keyboard repeat is disabled for this particular function. Any way to enable the key repeat function?

#### Device information:

Type of Mac:  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B21
  SMC Version (system):	2.19f12

macOS version: 10.12.3

BetterTouchTool version: 2.0.71

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cleverjackal** [comment]
+1 for making me laugh with the device information :)

**Comment by cleverjackal** [comment]
Jokes aside, I'd love this feature!

**Comment by mark3785** [comment]
I was going to leave an EtreCheck dump but thought that might be overkill.

**Comment by fifafu** [comment]
Mh, I think this should already work when configured like in this screenshot:
![image](https://cloud.githubusercontent.com/assets/8820811/23825254/ad129710-0686-11e7-9a31-5686e426fd22.png)

**Comment by mark3785** [comment]
That would be too easy.

**Comment by cleverjackal** [comment]
Works perfectly, thanks!

**Comment by cleverjackal** [comment]
@fifafu I set my repeat rate to 0.02 but it doesn't look like it deletes more than 10 times a second (it should be 50). Is this a bug or a system limitation?

**Comment by mark3785** [comment]
Ii get no repeat regardless of the setting. I'll try reinstalling it and see if that helps.

**Comment by cleverjackal** [comment]
Don't forget to try the alpha as well if it doesn't work. I'm on the alpha and it mostly works for me

**Comment by fifafu** [comment]
@mark3785 are you maybe using an external keyboard? I think some of those don't support the mechanism BTT needs for the key repeat option.

Also, are you aware that fn + backspace does forward delete by default?

**Comment by mark3785** [comment]
Just the MBP keyboard. fn + backspace are too far apart since I type one handed due to a disability.

Where would I find the alpha?

**Comment by fifafu** [comment]
You can use the "check for alpha version" button in the BTT menubar menu. However I don't think there has been a relevant change in the current alpha. This should already work fine on v2.071

If possible attach an export of your setup here, maybe I can see a problem or reproduce the issue with that. (using the export preset button in the BTT preferences)

**Comment by mark3785** [comment]
There isn't much in the menu bar. Here's the file...
[FD.txt](https://github.com/fifafu/BetterTouchTool/files/836811/FD.txt)

**Comment by fifafu** [comment]
Ah, try changing the repeat rate to something bigger than 0.02 (that's probably the issue @cleverjackal identified above)

BTT menubar menu:
![image](https://cloud.githubusercontent.com/assets/8820811/23834944/0c599de4-075f-11e7-9741-5833bca71c04.png)

**Comment by mark3785** [comment]
Eureka! The delay was the problem. The help is greatly appreciated.

**Comment by fifafu** [comment]
Nice, will fix this soon!

**Comment by cleverjackal** [comment]
Ah yeah. I did notice it didn't work under a certain threshold, right.
