### ISSUE TITLE
[Feature request] Allow four corner (quadrant) resize

### ISSUE THREAD

**Issue by jakubroztocil** [fifafu/BetterTouchTool#647]
I'm happy to discover that I'm able to replace the combination of MagicPrefs and Zooom/2 with the excellent BetterTouchTool. There's only one thing I'm missing to be completely happy.

When `Window moving & resizing` is enabled, the window is always resized by moving the position of the lower right corner:

![actual](https://cloud.githubusercontent.com/assets/326885/23822531/c6b2f0e4-064e-11e7-9658-7ab7a30c2738.png)

I'd love to be able to choose from which corner to resize the window by placing the cursor to one of its quadrants before resizing it:

![desired](https://cloud.githubusercontent.com/assets/326885/23822568/e7a584f6-064e-11e7-8c57-de1ac6a10aac.png)

This is the behaviour many window managers that implement window move & resize via mouse provide. There's also a setting for this in Zooom/2. For inspiration:

<img width="649" alt="zooom2" src="https://cloud.githubusercontent.com/assets/326885/23822448/20cf3ca6-064d-11e7-81e1-0f39a754d956.png">

Thanks for an amazing app ☺️

**Comment by fifafu** [comment]
Sorry, unfortunately I have decided to not implement something like this. See #952 for more information. :-(
