### ISSUE TITLE
Caps Lock as an action?

### ISSUE THREAD

**Issue by ccsasuke** [fifafu/BetterTouchTool#65]
Hi,

It seems I did not find Caps Lock as a keyboard or modifier key action. Is it because CapsLock is a special key? Is there any plan to support it as in Seil etc.?
Thanks.

**Comment by fifafu** [comment]
Sorry, this requires deeper integration into the system than BetterTouchTool does (because it's a special key). Thus it's currently out of scope for BTT.

One note: macOS now allows you to remap capslock to esc in system preferences -> keyboard -> mosifiers

**Comment by ccsasuke** [comment]
Hi, thanks for the prompt response.
I was thinking of mapping esc to caps lock rather than the other way -- I've already mapped capslock to esc.
I was using Karabiner-elements for this, but it's having some problems with the touch bar version.
I really like the latest touch bar support efforts in BTT (it's awesome!), but I could not get the capslock action, even with the help of Karabiner.
I tried to add a CapsLock button in touch bar and map it to some useless function key (f13), and map f13 to capslock in Karabiner, but it didn't work. Maybe that was simply not how it works..

**Comment by fifafu** [comment]
Ahh you meant it that way around :-)
That would actually be possible. I'll add that option to one of the next updates!

**Comment by bjarthur** [comment]
since this issue is still open, am i to presume the ability to put a caps lock button in the control strip with BTT is still unimplemented?  i am waiting with baited breath for this feature!

**Comment by fifafu** [comment]
I have just added a "Toggle Caps Lock" predefined action, it will be available with the next alpha sometime this week.

**Comment by lindsaymarkward** [comment]
> Sorry, this requires deeper integration into the system than BetterTouchTool does (because it's a special key). Thus it's currently out of scope for BTT.
Hi. The above comment was from last year, so I'd like to know if this might be in scope now.
I want to remap caps lock to backspace. I was using Karabiner Elements, but it breaks fn key on the Touch Bar Mac. 
Please let me know if this might be possible or coming with BTT. Thanks!
