### ISSUE TITLE
every time i update BetterTouchTool have to add it into login items 

### ISSUE THREAD

**Issue by mikyegy** [fifafu/BetterTouchTool#653]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

every time i update BetterTouchTool have to add it into login items 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: MacBook Pro (Retina, Mid 2012)
macOS version:  10.12.3 (16D32)
BetterTouchTool version:  2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

every time i update BetterTouchTool have to add it into login items 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cleverjackal** [comment]
Enable "Launch BTT on startup" from BTT's settings
