### ISSUE TITLE
[Feature Request] Rotate screen short cut

### ISSUE THREAD

**Issue by aarcro** [fifafu/BetterTouchTool#658]
#### Description of bug/feature request/question:

I'd love to use BTT to rotate my external display so I can easily switch from portrait to landscape. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Any? Keyboard shortcut or touch bar button would be great

**Comment by fifafu** [comment]
Sorry I probably won't be able to add this to BTT. It's a relatively complicated feature and I believe the number of users would be VERY small. Currently I need to focus on other things. 

However there is an opensource utility called fb-rotate which should be able to do what you want. You could trigger it using BTT's Run Terminal command or via Automator. Have a look at this thread: https://www.reddit.com/r/applehelp/comments/3zffdk/is_there_any_way_to_make_a_command_or_script_that/

**Comment by aarcro** [comment]
I can make that work. Thanks for the tip!
