### ISSUE TITLE
Applications not switching on touchpad click

### ISSUE THREAD

**Issue by ccdwyer** [fifafu/BetterTouchTool#66]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Since the latest update, when I try to click between applications on my Macbook Pro 2016, it takes two clicks for it to change the focused application.  I tried rebooting my system, and as soon as I close BTT the issue goes away.

**What kind of Mac are you using?**
2016 15" Macbook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which version of macOS are you running?**
10.12.1 (16B2659)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
I'm currently unable to reproduce this issue. Are you sure you have the latest BTT installed? (1.963)

**Comment by eyesuk** [comment]
Same issue here on 1.963, MBPr 2016, External LG Utrawide monitor, external trackpad and keyboard via BT, is so bad I have to disable BTT in order to avoid the issue

**Comment by fifafu** [comment]
Could you try if this is still happening with BTT 1.967? (get via auto-update)

**Comment by eyesuk** [comment]
Negative, same behavior.

**Comment by fifafu** [comment]
Very strange, I can not reproduce this at all ;-(
Does this also happen when you are sure only one finger is touching the trackpad?

Can you think of any possibly conflicting software you have installed?

**Comment by eyesuk** [comment]
I have a screencast but is 250mg, got somewhere I could upload it

**Comment by fifafu** [comment]
Dropbox maybe? (or Youtube?)

If possible, it would be great if you'd send me an export of your setup (using the export preset button in the BetterTouchTool preferences) to boastr.net@gmail.com

**Comment by eyesuk** [comment]
come in here and I will show you https://join.me/236-316-727

**Comment by eyesuk** [comment]
Sent the preference file, I will hang on the screen share for a few more minutes and end if you don't join.

**Comment by eyesuk** [comment]
Sent a link to the uploaded screencast... let me know if you need anything else for me

**Comment by ccdwyer** [comment]
Sorry for the lack of update.  I am not experiencing this issue any more with the newest BTT.
