### ISSUE TITLE
Bug: 2.082's new Drawing Behavior broke Tap-Triggers

### ISSUE THREAD

**Issue by SteveJobzniak** [fifafu/BetterTouchTool#660]
Hi Andreas.

First I thought "cool!" when I read "_Starting with v2.09 alpha the area will be highlighted if triggered by anything but a right-click._" (from https://github.com/fifafu/BetterTouchTool/issues/617).

I wish I didn't have to say this, but the new change has broken BTT's tap-triggers for drawing. But hey that's what public testing is for. I know that we as developers can't try every test case. :)

Here's what happened before the latest patch:

- Do the 4 Finger Tap gesture which I have bound to Start Drawing.
- Nothing happens on screen.
- As soon as I put one finger on the trackpad to begin moving and drawing something, the drawing window appears and starts drawing the line.
- Great.

But here's what happens from now on:

- Do the 4 Finger Tap gesture which I have bound to Start Drawing.
- The dark drawing frame instantly appears.
- As soon as I put one finger on the trackpad to begin moving and drawing something, the drawing window closes.
- Impossible to draw anything.

However I do like the "instantly show the window when triggered by anything other than right click" change. That was a great idea.

So, I think perhaps the drawing window just needs some code: "If drawing was started by any of the tap-and-let-go touchpad gestures, handle the drawing window as follows: Tap and let go again without moving cursor = close window. Tap again and start moving cursor = draw."

That way you could do this to abort: "4 finger tap and let go", "see drawing window", "tap once with a finger or whatever to close the drawing window". And this to draw: "4 finger tap and let go", "see drawing window", "tap and hold and drag to draw a line in the drawing window."

Thoughts?

**Comment by fifafu** [comment]
Weird, it seems to work correctly here. (I think there hasn't been a change to the logic that handles this)

Have you already tried to restart BTT?

**Comment by SteveJobzniak** [comment]
BetterTouchTool (612) v2.082 introduced the bug. The drawing window frame appeared alone, with no drawing dot in it, and tapping and moving the cursor after that just closed the drawing window (If I was LUCKY! Often it would bug and stay on screen as an empty drawing window).

v2.083 (613) today fixes it. Now my 4-finger tap makes a dot in the center of the drawing window as soon as it appears.

👍 

I am loving the great work you are doing on all the improvements. Fun times!
