### ISSUE TITLE
Bug with new usage statistics v2.082 (612)

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#663]
#### Description of bug/feature request/question:

Hello! So I think I've found a few bugs with the updated usage statistics in BTT's usage area.

* When I use the TipTap Left gesture which is set to ⌘W, the "total" section goes up by one, but it does not appear in the breakdown below it. What's funny is that when I updated to this beta, I could see the ⌘W action in the breakdown. However, now I can't see it anymore for whatever reason. 

* The same thing happens for remapping `^Backspace` to `Delete`. The total gesture number is increased, but it doesn't appear in the individual area.

* I have key repeat for the above on. _Each_ of these repeats is counted as a gesture in the usage stats. I feel like this is cheating, in a way. I could simply keep it pressed for a minute or two, and it would increase the number of uses by 500 or something. This wouldn't then be truly representative of how useful BTT has been to me.

#### Device information:

Type of Mac: MacBook Pro
macOS version: macOS Sierra
BetterTouchTool version: v2.082 (612)

**Comment by fifafu** [comment]
The most used section only shows up to 50 elements, is it possible that Tip Tap left wouldn't make it to the list?

**Comment by cleverjackal** [comment]
I don't think that's the problem. I actually think the problem may lie in some unforeseen incompatibility between my old usage data and the new usage data. I have reset my data usage _cries_ and I will monitor it from now on and check whether there are any problems. If this solves it, I'll close this issue :)

**Comment by fifafu** [comment]
Ok, please let me know!
I have also added some checks to prevent logging repeats for the next alpha

**Comment by cleverjackal** [comment]
All right, I'm pretty sure it's fixed here. There don't seem to be any problems anymore. Thanks a lot! I'm happy now.
