### ISSUE TITLE
Four finger tap for middle mouse button sometimes presses it twice

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#664]
#### Description of bug/feature request/question:

I've been noticing an issue since the latest alpha update. It seems as though when I tap the trackpad with four fingers (which I have set to pressing the middle mouse button), it is pressed _twice_ instead of once. This happens when, for example, I perform the action on a link – two new tabs open as if I've pressed the button twice. This did not use to happen in previous versions.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MBP Trackpad

#### Device information:

Type of Mac: MBP
macOS version: macOS Sierra 
BetterTouchTool version: v2.082 (612)

**Comment by fifafu** [comment]
Weird, does this happen right after you start BTT, or does it only start later after using BTT for a while?

**Comment by fifafu** [comment]
Ah I think I can reproduce the issue. Will release another alpha in a few hours :-)

**Comment by cleverjackal** [comment]
Cool, thanks! It's a good thing you figured it out, because I had no idea how to reproduce it ;)

**Comment by cleverjackal** [comment]
I assume this has been fixed (I haven't tested it out yet), so I'm closing this. I'll reopen it if needed.

**Comment by cleverjackal** [comment]
@fifafu Seems like this problem occurs with the latest version 635 now! It came back.

**Comment by fifafu** [comment]
Ah good point, the logic has been changed completely because of thumb recognition. I'll update this again.

**Comment by fifafu** [comment]
@cleverjackal should be fixed in v2.16 alpha

**Comment by cleverjackal** [comment]
Oh, nice! Thanks very much!
