### ISSUE TITLE
Debugging "Execute Terminal Command" actions

### ISSUE THREAD

**Issue by tonglil** [fifafu/BetterTouchTool#665]
#### Description of bug/feature request/question:
How do I debug/view why my terminal command action isn't getting executed?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:
Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.11.6 (15G1217)
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Trying to run a bash script but I can't tell why it isn't working (it works in the terminal).
I would like to know where I can find the traces or logs for this action?

**Comment by cleverjackal** [comment]
Are any terminal commands executed? Did you set the directory from which the command should be executed from?

**Comment by tonglil** [comment]
Yes, I am using the absolute path to the script.
Does this not source the terminal's $PATH (aka I can't depend on sourcing for commands)?

**Comment by cleverjackal** [comment]
Hmm, I think it does but I'm not fully sure how it works. Do any other commands run for you? Simple commands, for example moving files?

**Comment by tonglil** [comment]
I can mv files. It seems like it is not sourcing my `$PATH`, so things installed by Brew for example must be referenced with an absolute path.

**Comment by cleverjackal** [comment]
Ah, okay. So that's the problem? Then it seems like it's a bug, right?

**Comment by tonglil** [comment]
Yes, this seems like a bug!

**Comment by fifafu** [comment]
Does sourcing manually work? 
Something like

```
source ~/.profile && yourcommand
```
