### ISSUE TITLE
˙´¬¬ø ∑ø®¬∂

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#666]
#### Description of bug/feature request/question:
Trying to type in "hello world" using the "Insert text by typing produced the following result:

`˙´¬¬ø ∑ø®¬∂`

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
None

#### Device information:

Type of Mac: MBP
macOS version: Sierra
BetterTouchTool version: v2.083 (613)

**Comment by fifafu** [comment]
Huh that's strange, does this always happen?
Basically what that action does is using the Apple Script Objective-C bridge to call this command:
```tell application "System Events" to keystroke "hello world"```

**Comment by cleverjackal** [comment]
Ahaha. I think I know the problem. I am using a keyboard shortcut to insert this which involved the `⌥` button (`⌥H`). If you press `⌥` and then try to type in `hello world`, you'll see that you get the text in the title of this issue.

So basically the system is trying to type `hello world` with the `⌥` button pressed. If I assign this to a trackpad gesture, however, it works absolutely fine. It's being typed in on a user-level or something so it does get affected by `⌥`. That's cool to know.

For what it's worth, it doesn't seem like this happens in Keyboard Mastero.

**Comment by fifafu** [comment]
I think this should be fixed in build 614 (I uploaded about 9days ago)

**Comment by cleverjackal** [comment]
It's not completely fixed, but I'm continuing this in #669
