### ISSUE TITLE
Bugs with new "Insert text by typing" option

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#669]
#### Description of bug/feature request/question:

There are a couple of bugs with this which I want to report, actually. They are numbered below.

I set the keyboard shortcut ⌥A to the action to "Insert text by typing" for the letter `ä`. When I try this keyboard shortcut, however, there are two bugs:

1. The text is only inserted once I release the ⌥ key, not immediately after I press down ⌥A (which should technically be the normal behavior)

2. The character isn't inserted for some reason. What I get is a plain `a`. Maybe this is related to #666 and the alt button is being "double pressed" or something like that. In any case, I think that fixing that issue should might most likely fix this one as well.

3. Using this shortcut can increase the statistic for the usage by multiple times. I've actually increased the usage statistic for this shortcut 5000 times with one press, haha. Here's how you can reproduce it:
* Press down the ⌥ key
* Press down the A key
* Release the A key
* Keep the ⌥ key pressed. The number of times the shortcut statistic will be incremented according to how long you keep holding it down. It increases about 250 times a second per second you hold it down, haha. Crazy.

#### Device information:

Type of Mac: MBP
macOS version: Sierra
BetterTouchTool version: 613

**Comment by fifafu** [comment]
Hey,

sorry I didn't get to reply earlier - had two very busy weeks :-)
Have you already tried buil 614? I think I had fixed a few of those issues already.

**Comment by cleverjackal** [comment]
Hi, no worries. I tried it out and it looks like it's been fixed, albeit with some minor (though significant) problems. 

Let's say you want to insert the text `b**i**n **u**t**i**l` by pressing `option + o`. I have a system shortcut making `option + i` invert the screen colors and a BTT shortcut `option + u` to type the u with an umlaut. Both of those are invoked. 

Issue 3 still exists, though.

(These are with 614)
