### ISSUE TITLE
Unified Interface Please

### ISSUE THREAD

**Issue by rodgerwerner** [fifafu/BetterTouchTool#67]
#### Description of your request...:

I would really appreciate it IF BTT could be unified, following the Human Interface Guidelines.
I have done a quick mockup of what I mean and it is below.  Fonts use system sizes, and the same goes for buttons and boxes etc.  Overall it is much easier on the eyes and easier to pick out the elements we want/need when making shortcuts.

Also, I have changed the device selector to be more like TABS in the macOS interface.  It's not necessarily the BEST option, but I find it a bit better than using 2x images and scaling them down for non retina displays, as is the case with my display.

If all of this were unified, the fonts and buttons would scale nicely with ALL displays, retina or not.

**What kind of Mac are you using?**

iMac 27-inch, Late 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Magic Mouse, Magic Trackpad, Apple Wired Keyboard, Apple Wireless Keyboard

**Which version of macOS are you running?**

macOS 10.12.1 (16B2657)

**Other information:** (Unified Mockup)

![betterbettertouchtool_unified](https://cloud.githubusercontent.com/assets/23433246/21046680/c839b6c8-bdd3-11e6-890a-f4ec47d8e76f.png)

**Comment by fifafu** [comment]
Hi Rodger,

thanks for the suggestions.
There will be continuous little interface optimizations, however I have to admit it's not my highest priority. During the last few years the current UI has proven to result in a low amount of support requests and thus I'm mostly happy with it. However I certainly know that it could be more appealing visually.

Some thoughts on the mockup:
* I would never replace the text+icon toolbar with just icons. That's just guaranteed to lead to more support requests :-). Also in e-mails it'd be much harder for me to explain what a user should do. It looks nice but just makes things harder.
* The device selection bar is not really a tab bar, thus I think it may not be appropriate to use the macOS tab design. Also I like having little icons there, macOS/iOS uses @2x icons everywhere so I don't see this as a big issue.
* The BTT gesture and action selection buttons are no popover buttons, neither is the preset selection menu. Thus I shouldn't use the default popup button appearance. (However I agree that they don't look very nice currently)
