### ISSUE TITLE
Treating left/right modifier keys individually

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#671]
#### Description of bug/feature request/question:

I think it would be nice to treat left/right modifier keys individually if one so wants to. For example, there's a shortcut I'd like to add involving the right shift button but _not_ the left shift button. Would this be possible?

**Comment by fifafu** [comment]
Unfortunately this is is currently only possible for KeySequences and not for shortcuts.
However I'm planning to move to a new shortcut interception system that may allow for such things - unfortunately I'm not yet sure if it's feasible and I can't provide a timeline.

**Comment by cleverjackal** [comment]
All right, thanks!

**Comment by fifafu** [comment]
Current versions of BTT support this.
![image](https://user-images.githubusercontent.com/8820811/38385984-a8f9615c-3913-11e8-8057-df6a4004c6f5.png)
