### ISSUE TITLE
Leave small gap above dock for auto-hidden Dock

### ISSUE THREAD

**Issue by grigorye** [fifafu/BetterTouchTool#672]
#### Description of bug/feature request/question:

It would be nice if "Leave small gap above dock" would work in case of auto-hidden Dock. Currently windows are maximized without the gap in this case. But Mac OS X maximizes windows leaving a small gap (4-8 pixels?) above the screen edge from which dock slides in. Hence default maximize behaviour of Mac OS X does not match the one of BetterSnapTool. At least some apps "restore" maximized state of windows, but they do it "Mac OS X" way, even if the window was previously maximized with BetterSnapTool without a gap. That's a bit annoying (because I see that gap that is enforced every such time). And I have no way to tell BetterSnapTool to respect that gap in this case.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro/Mac Pro/Mac mini

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.x (any of them)
BetterTouchTool version: 1.7

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screenshot of gap enforced by Mac OS X in case of auto-hidden dock at the left side of the screen. Note the edge of other window (maximized with BetterSnapTool) visible below the top window (maximized with Mac OS X Zoom).

<img width="71" alt="screen shot 2017-03-15 at 19 01 24" src="https://cloud.githubusercontent.com/assets/803905/23963564/fccf10de-09b1-11e7-81aa-14e76166055d.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by icymind** [comment]
feature request +1
The gap is quite annoying

**Comment by jeremybundgaard** [comment]
@fifafu 

Hi Andreas! BetterTouchTool is an indispensable app for my macOS workflow...I am compelled to profess this _every time_ I comment on it ;) keep up the great work!

I know you have been addressing issues with the [pixel gap linked to the dock orientation](https://github.com/fifafu/BetterTouchTool/issues/454) via many different issue reports. Do you understand exactly what is causing this? Any work arounds that come to mind?

Jeremy

**Comment by fifafu** [comment]
@jeremybundgaard @icymind this has been fixed in High Sierra.
