### ISSUE TITLE
BUG: Corner Click Haptic Feedback Issue

### ISSUE THREAD

**Issue by pauloruberto** [fifafu/BetterTouchTool#675]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When using my corner click force click in the top trackpad corners, the feedback received is now more like it vibrates, instead of the normal two stage click. Also it will occasionally repeat the action numerous times, or sometimes not at all. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Force Touch Trackpad

#### Device information:

Type of Mac: 2016 MacBook Pro
macOS version: 10.12.4 beta
BetterTouchTool version: 2.084

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by frogworth** [comment]
Confirmed, macOS 10.12.2 (otherwise same).

**Comment by fifafu** [comment]
Indeed :-) Feels funny.

I'll look into it!
