### ISSUE TITLE
[Feature Request] Any way that I can create my own multi-touch gestures?

### ISSUE THREAD

**Issue by hpat0003** [fifafu/BetterTouchTool#677]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Say, I'd like to create 3 finger tipTap with middle finger fixed. Can you implement a feature that allows the users to do so? Please?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad

#### Device information:

Type of Mac: Macbook Pro 15" (Late 2016)
macOS version: 10.12.3
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, custom gestures like that are not feasible, however you can submit feature requests for specific new gestures.
