### ISSUE TITLE
Clicking buttons produces very weird behavior

### ISSUE THREAD

**Issue by sinansays** [fifafu/BetterTouchTool#678]
#### Description of bug/feature request/question:
Sometimes clicking a button (any button in any program) produces this odd effect of the cursor splitting into two smaller cursors with a hand/grab cursor in the middle. It's extremely bizarre.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (15-inch, Late 2016)
macOS version: 10.12.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Comment by fifafu** [comment]
Huh, I have never seen something like this - and I don't think BTT can cause this. Can anybody else reproduce this?

**Comment by sinansays** [comment]
Not sure. It might be another piece of software I’m running that’s causing this. But the cursor getting stuck (when using a trackpad) is 100% tied to BTT. When I quit BTT the cursor automatically releases. So there is something to this bug.

MS

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.

**Comment by sinansays** [comment]
Thank you Andreas. Truth be told, I haven’t encountered the issue in a while. Much appreciation for your continued development of this software.
