### ISSUE TITLE
Touch Bar activating with a modify-key hold down 

### ISSUE THREAD

**Issue by jiaoshou2009** [fifafu/BetterTouchTool#68]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

You know there is a system feature that when we hold down the Function key, we could get the classical F1 - F12 key, but we could also change it to display full control bar. I hope that BTT could support this feature too. For example, when I hold down the option key, the BTT control button will appeared in Touch Bar, because, sometimes, we don't want BTT Touch Bar control appearing all the time. 

**What kind of Mac are you using?**

15' MacBook Pro with Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which version of macOS are you running?**

macOS 10.12.1 (16B2659)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi,

you can already do that. See the attached screenshot:
![image](https://cloud.githubusercontent.com/assets/8820811/21058857/43b3d286-be40-11e6-8f55-0f34dbe34692.png)
