### ISSUE TITLE
No option for 1 finger force-click

### ISSUE THREAD

**Issue by tevyaw** [fifafu/BetterTouchTool#682]
#### Description of bug/feature request/question:

I don't find force-click very helpful, so I thought I'd use it for "middle click" instead. However, I don't see an option to select 1-finger force click. Is it there and I just don't see it?

There's 2 and 3 finger force click, but 1 finger only seems to work for various corners and such.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Touchpad 2, (haven't tried on the built-in force touch trackpad, but I assume the software doesn't magically make that option appear when I'm using the built-in trackpad.

#### Device information:

Type of Mac: MacBook Pro 2015 edition
macOS version: 10.12.3
BetterTouchTool version: 2.071

**Comment by tarvos21** [comment]
Yes, I also find one-finger force click will be great, for closing a  tab in Safari or iTerm2.

I have searched and found some old issues requesting for this feature, they are closed for a technical reason:
https://github.com/fifafu/BetterTouchTool/issues/141
https://github.com/fifafu/BetterTouchTool/issues/88

**Comment by fifafu** [comment]
Closing this as duplicate, however I may soon add a 1 finger force click (which however also will trigger a left-click due to the technical limitations)

**Comment by theonlygusti** [comment]
@fifafu I would love to be able to map a force click, regardless of whether it's possible to block the previous click or not.

E.g. in finder I'd like to be able to re-map single finger force click to "Get Info" rather than preview.
