### ISSUE TITLE
Feature Request: only start gesture recognition after distance x

### ISSUE THREAD

**Issue by mbrasch** [fifafu/BetterTouchTool#684]
I use xGestures for many years. I configured my Wacom pen with lower button == CTRL and upper button == CMD. CTRL+tip opens the context menu and CTRL+drag draws a gesture. This is very convenient and I would like it in BTT too.

With the new 2.084 alpha the gesture recognition is much better. :-)

**Comment by fifafu** [comment]
Minimum distance has been added in v2.10!
![image](https://cloud.githubusercontent.com/assets/8820811/25771422/9df4efbc-3250-11e7-8113-f3b1113a6350.png)

However ctrl+click is not yet supported. I'll add that soon.

**Comment by mbrasch** [comment]
Thank you. :-)

> However ctrl+click is not yet supported. I'll add that soon.

:-)
