### ISSUE TITLE
Corner window snapping happens even with snapping disabled

### ISSUE THREAD

**Issue by Stever888** [fifafu/BetterTouchTool#685]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have snap areas defined, but I want edge-snapping disabled. I have unchecked the "Enable window snapping" setting in Simple/Basic Settings and "Window Snapping Enabled" in Advanced/Advanced Settings/Window Snapping Settings.

Windows still snap when I drag the current windows to the corners of the screen.

#### Device information:

Type of Mac: iMac
macOS version: 10.12.3
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Stever888** [comment]
Enabling Window Snapping in the Advanced settings, then unchecking "Corners: resize to quarters" then re-disabling Window Snapping seems to solve the problem. It may be that the "Corners" setting isn't honoring the "Window Snapping Enabled" checkbox being clear.

**Comment by fifafu** [comment]
Thanks for reporting! Should be fixed with the next version.
