### ISSUE TITLE
Disabling an Attached Action doesn't disable it

### ISSUE THREAD

**Issue by truth1ness** [fifafu/BetterTouchTool#688]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I created a keyboard trigger with an attached action. I disabled the Enabled checkbox for the attached action but when I press the keyboard trigger it triggers both the main and attached action. Rebooted btt no difference. Had to delete attached action to disable it. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple keyboard

#### Device information:

Type of Mac: macbook pro 2016
macOS version: 10.12.3
BetterTouchTool version: 2.017

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting. Should be fixed with the next update!
