### ISSUE TITLE
Touch ID option for the admin password when prompted.

### ISSUE THREAD

**Issue by amilcruise** [fifafu/BetterTouchTool#689]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Implementation of Touch ID option for the admin password when prompted.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: Macbook Pro 2016
macOS version: 10.12.13
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

To make it specific, I got the prompt when calling an applescript file when pressing a touch bar button. It will be good to have an option to use touch id for the password.

![image](https://cloud.githubusercontent.com/assets/7702046/24086910/b078cc1c-0d6b-11e7-8f90-9ebf0be4e98a.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by MrJarnould** [comment]
I thought about this too.  I haven't had time to set up or look into it, but maybe using BBT to trigger 1Password will do the trick!

[https://support.1password.com/touch-id-mac/](url)

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or still encounter this problem, please create a new issue - I'm now much more responsive than a few months ago.

These dialogs are handled by the system. Unfortunately BTT can't influence them.
