### ISSUE TITLE
Xcode Code Signing

### ISSUE THREAD

**Issue by macg4dave** [fifafu/BetterTouchTool#693]
#### Description of bug/feature request/question:

Using Xcode to build a different program,  Changed the code signing of the project.
Had a password dialog that contained text from the BetterTouchTool accessibility dialog.

#### Device information:

Type of Mac: Macbook Pro (2016) touch bar
macOS version: 10.12.3
BetterTouchTool version: 2071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Screenshot 
<img width="437" alt="screen shot 2017-03-20 at 13 33 13" src="https://cloud.githubusercontent.com/assets/16404168/24100160/1b5467a6-0d73-11e7-81d7-d11f1773bc95.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I asked Apple a while ago what this means, this is the reply I got:

> The password prompt dialog is new in OS X v10.11.4. It appears when the system detects that the initial permissions alert received a synthetic event (an event posted programmatically, as opposed to an event generated by the user).

> This is a security hardening change to prevent apps from granting themselves access to the keychain by posting a click on the Allow or Always Allow buttons. Instead, the user must now provide their password to ensure that an app isn't attempting to grab access to the keychain.

> This new alert should only appear on systems that have a source of synthetic events installed, such as a graphics tablet driver or a virtualization app like Parallels or VMWare Fusion.
