### ISSUE TITLE
Feature Request: Presets -- Dropbox or iCloud

### ISSUE THREAD

**Issue by rwross1776** [fifafu/BetterTouchTool#694]
Not much more to add from subject line.

Been a long time user and have always wanted this feature.  Once it went paid, I'd always been meeting to post it and now am finally getting around to it.

I have several Macs and routinely come up with new gestures or touch bar items, but then have to remember to either manually export and copy presets to other machines or recreate them manually.

I'd assume the Dropbox solution would be easiest, but all I really need is the ability to designate where BTT looks to find the preset file.

**Comment by fifafu** [comment]
I'm working on this. Hope to have it ready soon.
Closing here as I'm already tracking it in this issue:  #214
