### ISSUE TITLE
Cursor Speed on Sierra

### ISSUE THREAD

**Issue by brainelink** [fifafu/BetterTouchTool#695]
I have been a fan, user, donator and promoter for many years now.

On one computer (2011 iMac), I just upgraded to Sierra and now one of my most favorite features seems missing.

That is the cursor speed feature.

Can you tell me if Apple has blocked your app from using that?

If so, I will have to move back to El Capitan JUST to get the BTT feature back.

Thanks in advance for your advice AND for providing such a valuable resource!!

**Comment by fifafu** [comment]
Unfortunately with Sierra changing the mouse speed is not possible anymore - at least not to higher values than in System Preferences.

I'll keep looking for a solution, but currently I think it's not possible :-(

**Comment by brainelink** [comment]
*First of all, thanks SO MUCH for getting back to me!*

*I am SOOOOO sorry this has happened since that capability is one of the
key benefits of BTT.*

*Will just have to move back to El Capitan until (IF) you find a solution.*

*BTW, keep up the AWESOME job. I am forever in your debt.*

*“GRIFF”*




*          "GRIFF"           Robert "GRIFF" GriffithFounder & Market
Positioning StrategistTHINK-TANKPHONE: 316.636.2552WEB: www.THINK-TANK.com
<http://www.think-tank.com/>*

On Tue, Mar 21, 2017 at 3:20 PM, Andreas Hegenberg <notifications@github.com

**Comment by cleverjackal** [comment]
Could you possibly add a note of that in? I kept on changing it and it wouldn't work, and I thought it was a bug. Just a small disclaimer under the slider or something would be great.

**Comment by fifafu** [comment]
@cleverjackal Good point, I'll add this to the slider!

**Comment by brainelink** [comment]
What is the most recent OS that supports this functionality?

**Comment by fifafu** [comment]
El Capitan (10.11)

**Comment by brainelink** [comment]
Any updates that make cursor speed in High Sierra workable? There are some apps that require this OS version in order to work effectively.

**Comment by cleverjackal** [comment]
@brainelink Maybe this would be possible with a high DPI mouse? I remember a friend telling me he got one on Windows and it make the mouse go crazy fast. Of course it's not a solution for the trackpad, and not as nice as a software solution, but something to consider.

**Comment by brainelink** [comment]
@cleverjackal Thanks for your feedback. I'm using Mac Magic Mouse (ver 1, still powered by batteries).
