### ISSUE TITLE
pbpaste "Execute Terminal Command" doesn't work with unicode characters

### ISSUE THREAD

**Issue by benkamin** [fifafu/BetterTouchTool#697]
When using 'pbpaste' in Execute Terminal Command unicode characters get messed up.
For example, I tried the command: pbpaste >~/a.txt
When I had 'não' in my clipboard, after running the shortcut, a.txt has: 'n<8b>o'.

Running the command 'echo não >~/a.txt' does work as expected however.

Type of Mac: MacBook Pro
macOS version: 10.12
BetterTouchTool version: 2.071

**Comment by fifafu** [comment]
This isn't a BTT issue, is it?
I think you need to specify the LC_CTYPE and run the command like this:
```bash
LC_CTYPE=UTF-8 pbcopy > ~/a.txt
```
