### ISSUE TITLE
Help/Feature Request: Open link from Safari in Google

### ISSUE THREAD

**Issue by catsnotdrugs** [fifafu/BetterTouchTool#698]
I'm not sure if there is currently a way to do this or not but I would like to be able to click on a link in safari and have it open in chrome.  

Thanks

**Comment by fifafu** [comment]
Ok, this is a bit complicated but it should work like this:

1. Use the "Trigger Context Menu Item" and enter "Copy Link" there.
2. Add a small delay using the predefined action "Delay Next Action" (attach additional action)
3. Use the Run Apple Script predefined action and enter the following Apple Script:

```AppleScript
set theLink to the clipboard as text
tell application "Google Chrome"
	activate
	open location theLink
	
end tell
```

It should look like this:
![image](https://cloud.githubusercontent.com/assets/8820811/24291176/27a14e1c-1088-11e7-96c2-fe1fbfe47579.png)

**Comment by catsnotdrugs** [comment]
Ok great…I’ll give that a try.  Thanks 

On Fri, Mar 24, 2017 at 6:51 AM Andreas Hegenberg

<
mailto:Andreas Hegenberg <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Ok, this is a bit complicated but it should work like this:

Use the "Trigger Context Menu Item" and enter "Copy Link" there.

Add a small delay using the predefined action "Delay Next Action" (attach additional action)

Use the Run Apple Script predefined action and enter the following Apple Script:

set

theLink

to

the

clipboard

as

text

tell

application

"

Google Chrome

"

activate

open

location theLink

end tell

It should look like this:
https://cloud.githubusercontent.com/assets/8820811/24291176/27a14e1c-1088-11e7-96c2-fe1fbfe47579.png

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/fifafu/BetterTouchTool/issues/698#issuecomment-288991119
, or
