### ISSUE TITLE
Feature Request: Brightness controller for alternate monitors?

### ISSUE THREAD

**Issue by timothyBoye** [fifafu/BetterTouchTool#699]
Hey

I have an LG UltraFine 4K Display connected bia USB-C to my MacBook Pro w/ TouchBar when I use the brightness slider that BetterTouchTool provides for the TouchBar it only effects the laptop display not my external monitor.

I can turn the brightness up and down for it in the OS System Panel under Displays so the control for the LG monitor are tied up into MacOS's software somehow. Was wondering if it was possible to make a brightness slider for that monitor like the brightness slider that affects the main display.

Cheers

P.S. love your work!

**Comment by fifafu** [comment]
Hey,

Currently you can press ctrl while using the BTT  brightness slider, however I haven't tested whether that works on the 4k monitor.

**Comment by timothyBoye** [comment]
Oh that's awesome, I didn't realise! Works on the 4k.
