### ISSUE TITLE
TipTap Middle Not Working on New Macbook Pro

### ISSUE THREAD

**Issue by mikeytrafton** [fifafu/BetterTouchTool#7]
I have a brand new 13 inch Macbook Pro with the touchbar. The TipTap Middle gesture wasn't working for me on the built-in trackpad, so I tried to troubleshoot it. It turns out that if I space my outside fingers very far apart, it does work, but if I have my outside fingers close together, it does not recognize it as a TipTap Middle.

For example, if I use my first finger and last finger as the outside fingers and my second finger as the middle finger, BTT will recognize the TipTap Middle. But if I use my first and third fingers as the outside fingers, as I have done for years, it does not recognize it. 

Perhaps this has something to do with the fact that the trackpad is not MUCH wider than it was before. 
 
I am using MacOS 10.12.1.

**Comment by pallavmac** [comment]
Yea. Ideally if the fingers are far apart, it shouldn't work. Else if a small part of the hand is touching the trackpad then a tip tap get's registered.

**Comment by fifafu** [comment]
If I remember correctly this issue has been solved by adding a slider to choose how far the fingers are allowed to be apart (see screenshot)

Closing as I'm cleaning up the issue list a bit. If it's still a problem please comment again.

![image](https://cloud.githubusercontent.com/assets/8820811/22175671/f94d7036-dff9-11e6-924c-69ddd5b7deba.png)
