### ISSUE TITLE
Modifiers causing touchbar buttons to not appear

### ISSUE THREAD

**Issue by oliverpolden** [fifafu/BetterTouchTool#70]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
When adding a touchbar button with a modifier key (shift, fn, ctrl etc.) that button will not appear.

**What kind of Mac are you using?**
MacBook Pro 2016 with touchbar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which version of macOS are you running?**
Sierra 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
The same keyboard shortcut will appear if the modifier is removed.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hey,

The button should appear whem pressing the modifier key, doesn't that work for you?

FN is currently problematic.
