### ISSUE TITLE
[Feature] CMD+TAB Switch App

### ISSUE THREAD

**Issue by ldong** [fifafu/BetterTouchTool#701]
Is it possible to do the following using better touch tool?

For example, 
CMD TAB ->  1 (Hit CMD + TAB, then hit 1)
Switch App to the first of CMD+Tab list

CMD TAB -> 2 
Switch App to the second of CMD+Tab list

CMD TAB -> 9
Switch App to the last of CMD+Tab list
etc,.

I saw this app here, http://commandtab.noteifyapp.com/, and I wonder if it is possible to do that. 
I tried to do it myself, but its complicated and I could use your help.

<img width="1127" alt="screen shot 2017-03-22 at 1 52 29 am" src="https://cloud.githubusercontent.com/assets/5491695/24189452/4d802e38-0ea2-11e7-89dd-392579650478.png">

Thanks.

**Comment by fifafu** [comment]
I think this would be quite hard to achieve with the system app switcher. The commandtab app looks nice, I think it's best to use that instead of trying to replicate it in BTT.
