### ISSUE TITLE
Unexpected behavior on Google Chrome

### ISSUE THREAD

**Issue by jlhg** [fifafu/BetterTouchTool#702]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I set a Trackpad Gesture "5 Finger Tap" which binds Cmd-W on global applications (see below screenshot). Normally this gesture closes the current tab on Chrome browser. However, it has a chance to close a window instead a tab.

<img width="771" alt="2017-03-22 16 49 17" src="https://cloud.githubusercontent.com/assets/2265716/24189536/543ab5f8-0f20-11e7-90f3-a4d117f992fe.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpads

#### Device information:

Type of Mac: MacBook Pro Retina
macOS version: 10.12.3
BetterTouchTool version: 2.017 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

are you sure you had multiple tabs open when this happened? Google Chrome will automatically close the window if only one tab is left and cmd+w is pressed.

**Comment by jlhg** [comment]
It happened for multiple tabs, and I'm not sure if Chrome crashed or not (no crash message). 
I decided to close this issue first as I can't reproduce.
