### ISSUE TITLE
Lost my Global icon

### ISSUE THREAD

**Issue by Danzo100** [fifafu/BetterTouchTool#705]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Not sure what I did but my GLOBAL icon in the preferences panel isn't showing up... just the icons for the apps I selected.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All of them.

#### Device information:

Type of Mac:  MacBook Pro
macOS version: 10.12.3
BetterTouchTool version: 2.084

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's very weird, I have not yet head of such an issue :-)
Could you try to also delete the Finder application and then restart BTT? (I think it should then recognize that something is wrong and add the global section again).

Alternatively you could create a new preset or import a backup (using the import button)

![image](https://cloud.githubusercontent.com/assets/8820811/24267709/7a14c070-100b-11e7-8c09-0fc3341aa45b.png)

**Comment by Danzo100** [comment]
First the bad news:  The Finder icon was gone as well — all that was there was an item for an Application I was modifying.  I did as you suggested and everything is back! 

Question:  Is it possible to move the ESC key on the TouchBar? I’ve spent the past 30 years resting my fingers of my left hand above the keyboard and now I hit ESC about 50x a day and I’m not interested in remapping my muscle memory when I can remap the touch bar.


So… what’s the best way to move the damned  ESC button?  And who at Apple do I have to hate for putting it there? 

Thank you for your program and great support!

Dan

**Comment by fifafu** [comment]
Sorry for not replying to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions, please create a new issue - I'm now much more responsive than a few months ago.
