### ISSUE TITLE
BTT seems to reset remapped modifier keys from keyboard preferences back to system default

### ISSUE THREAD

**Issue by bkw** [fifafu/BetterTouchTool#707]
#### Description of bug/feature request/question:

I have CapsLock permanently set to "No Action" via System Preferences → Keyboard → Modifier Keys.

This worked for as long as I can remember. Only after I purchased BTT to remap § (top left key on us intl keyboard) to Escape, I noticed that every once in a while CapsLock suddenly starts working again. I checked in Keyboard Prefs and sure enough it was back to default "CapsLock".

I cannot prove BBT is the culprit, but since it also remaps keys and this never happened before but happens a lot after I purchased BBT, I thought a bug report might be justified.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Keyboard

#### Device information:

Type of Mac: Macbook Pro Late 2016, 15", US-Intl Keyboard
macOS version: 10.12.3 (16D32)
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I don't think BTT can cause this, it doesn't interact with those settings  (I'm also using Caps Lock remapped to ESC and haven't had such issues yet).

How often does this happen? Can you think of any pattern that causes it?

**Comment by bkw** [comment]
Please accept my apologies for wasting Your time on what seems to be a [bug with the current Sierra version](https://discussions.apple.com/thread/7796554?start=0&tstart=0). I should have googled more thoroughly before accusing your fine piece of software. All good.
