### ISSUE TITLE
[Bug] Trigger Context Menu Item does not work in iTunes

### ISSUE THREAD

**Issue by chrisduong** [fifafu/BetterTouchTool#709]
I tried to add 1 keyboard shortcut to Duplicate the Playlist in Context Menu of iTunes but it only shown 
the context menu only without select the option **Duplicate** that I defined in the BetterTouchTool.

It is strange that the "Trigger Context Menu Item" worked in Safari but not iTunes (12.6.0.95)

#### Device information:

Type of Mac: MacBook Pro 2016 Touchbar
macOS version: 10.12.3?
BetterTouchTool version:  2.071(608)

**Comment by fifafu** [comment]
Hi,

thanks for reporting!
I was able to reproduce and fix the issue. It will be solved with the next update.

Best,
Andreas
