### ISSUE TITLE
Create a new functionality to restart BBT every xx minutes

### ISSUE THREAD

**Issue by masa229** [fifafu/BetterTouchTool#71]
#### Description of your bug/question/feature request...:
After for a while since BBT starts, BBT gets heavy and cannot recognize gestures. So I need to restart it. It is really annoying to manually restart BBT every xx minutes. So, please add a new functionality to automatically restart BBT every xx minutes.

**What kind of Mac are you using?**
MacBook Pro (Retina, 13-inch、Early 2015)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackad and Magic Trackpad 2

**Which version of macOS are you running?**
10.11.6

**Comment by fifafu** [comment]
Hi,

I'd much rather fix your issue. Could you maybe send me an export of your setup (via the export button in the BTT preferences) to boastr.net@gmail.com?

How long can you usually use BTT? Any gesture that triggers the bug more than others?

Best,
Andreas
