### ISSUE TITLE
Hold down key for repeats

### ISSUE THREAD

**Issue by dotherightthing** [fifafu/BetterTouchTool#711]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I've remapped the forward delete key to my broken back delete key. If I held down the back delete key for a second, it would keep deleting, but if I hold down the remapped key, it only deletes once.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Wired full-size Apple aluminium keyboard.

#### Device information:

Type of Mac: Macbook Air 11" (Mid-2012)
macOS version: Sierra 10.12.3
BetterTouchTool version: 2.08 (610)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

have you enabled key repeat?
See this screenshot:
![image](https://cloud.githubusercontent.com/assets/8820811/24290230/7c0b3b6a-1084-11e7-9fef-557af348c4a5.png)

**Comment by dotherightthing** [comment]
Oh, great! I I completely missed the settings/edit cog. All working well now thanks.
