### ISSUE TITLE
Crashes right after opening

### ISSUE THREAD

**Issue by damirharasic** [fifafu/BetterTouchTool#713]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac: IMAC
macOS version: 10.9.5
BetterTouchTool version: better snap tool 1.7

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

there currently seems to be a bug in combination with MacOS 10.9.5. Could you try if this fixes your issue:

1. Go to System Preferences => Security & Privacy => Privacy => Accessibility
2. Enable BetterSnapTool there (you may have to click the little lock icon on the bottom left first)

Afterwards it should be working

**Comment by damirharasic** [comment]
That did it. Thank you very much. Cheers

Damir Harasic
+569 8189 6871
damirharasic@oliverfilms.cl
www.oliverfilms.cl
