### ISSUE TITLE
[Feature Request] action to activate Application below cursor

### ISSUE THREAD

**Issue by devvithelopper** [fifafu/BetterTouchTool#714]
On any gesture, allow to select the predefined Action to activate (e.g. what you would do with the application switcher) the application whose window is below the mouse cursor or where the touch happened (in case of a pen).

**Comment by fifafu** [comment]
You can abuse the "Send Shortcut To Specific Application" action to do this like shown in this screenshot (don't assign a shortcut):

![image](https://cloud.githubusercontent.com/assets/8820811/24304823/14961d6a-10bb-11e7-9cc5-094d51ef8785.png)

**Comment by devvithelopper** [comment]
Oh wow thanks, I would not have found this one. Do you think it might make sense to add an action just for convenience?

**Comment by devvithelopper** [comment]
I would like to change the feature request to something more specific: "Activate the Window below the cursor" not just the application, and it should work on the dock too, activating the application then.

**Comment by devvithelopper** [comment]
As you might have guessed, I cannot do what I wish to do by abusing "Send Shortcut To Specific Application". Basically I want to activate the window I am clicking on, or the Application if I click on the Dock or the window again if I click on it in exposé and then I want to send a shortcut to this application. I used a delay before, but sometimes apps do not respond fast enough (10ms) so another app get's the keyboard shortcut...

**Comment by devvithelopper** [comment]
Hey great you implemented "Activate hovered App in Dock": With this I implemented it like so:

```
5 Finger click -> Send (null) to App under Cursor
                       -> Activate hovered App in Dock
                       -> Send cmd+q
```
