### ISSUE TITLE
Lock Screen action fails most of the time.

### ISSUE THREAD

**Issue by zapman449** [fifafu/BetterTouchTool#715]
#### Description of bug/feature request/question:
The "Lock Screen" action fails 3-4 times in a row before succeeding.  Screen goes dark, but comes back to unlocked screen.  Most of the time, if I see the screensaver, I'm fine, but that's not perfect.  Perfect is watching the screensaver for 5 seconds.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard shortcut.  <shift><cmd>-L

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version:  El Cap and Sierra
BetterTouchTool version:  2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Only 'work around' is to hit the keyboard shortcut for "lock screen" 3-5 times until it takes.

Problem has gone on for several weeks, and persists across MacOS version upgrades, reboots etc.

**Comment by fifafu** [comment]
Sounds like something is interfering (BTT just sends the command to lock the screen but if something else gets inbetween BTT may not succeed).

You could try to use the "Switch To Loginscreen" action instead, that one should not be disturbed by other software.

**Comment by zapman449** [comment]
I've enabled the hot-corner lock for my mouse, and it doesn't have any issues.  FWIW.
