### ISSUE TITLE
Widgets for Touch Bar

### ISSUE THREAD

**Issue by fifafu** [fifafu/BetterTouchTool#72]
Reminder for myself:

Add Touch Bar widgets:

* customizable time/date widget
* battery widget
* current clipboard content widget (only show if content available)
* wheather widget

**Comment by pallavmac** [comment]
😄

**Comment by pallavmac** [comment]
Will this be possible by Jan 1st?

**Comment by fifafu** [comment]
It already looks promising but probably won't be completely finished until the 9th of January.

**Comment by fifafu** [comment]
Battery and date / time widget are added for the next update, other widgets will be added during the next few weeks.

**Comment by pallavmac** [comment]
Would a battery widget be coming soon?
