### ISSUE TITLE
Feature request: Separate trackpad mirroring preferences; one for x-axis, one for y-axis

### ISSUE THREAD

**Issue by BourneLoser** [fifafu/BetterTouchTool#720]
#### Description of bug/feature request/question:
Currently, when the "Mirror complete Magic Trackpad orientation for upside-down usage" checkbox is set both the x and y axes are mirrored. Supposedly this is for upside-down usage but when I put my trackpad upside-down one of the axes still goes the opposite way. This is my use-case. It's for ergonomic reasons. It actually took me a while to figure out the upside-down being referenced in the preference was the user, not the trackpad :p And I can confirm that when I lay down on my back and look at my computer then yes, mirroring of both axes is the desired behavior however it is not useful when the user is right-side up and the trackpad is upside-down.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 1 (ultimately I'd like to use it on my Magic Trackpad 2)

#### Device information:

Type of Mac: Mac Mini (ultimately I'd like to use it on my 2016 MBP)
macOS version: 10.10 Yosemite (ultimately I'd like to use in on 10.12 Sierra)
BetterTouchTool version: 2.08

**Comment by fifafu** [comment]
I'm not exactly sure what you mean because it works fine for me when rotating the trackpad by 180degree, however I won't be able to  change it anyways because this is the only rotation option the trackpad driver offers. (BTT just enables this option)
