### ISSUE TITLE
Possible to show keymap in context menu

### ISSUE THREAD

**Issue by chrisduong** [fifafu/BetterTouchTool#727]
Hi,

When you assign the custom keymap in default MacOS system settings, the keymap will show in the context menu like this 

<img width="403" alt="1d1ceb3b-4bae-44b6-872f-eec6fdaa39ed" src="https://cloud.githubusercontent.com/assets/1848882/24338845/880d5ace-12d2-11e7-8def-3e7f9e6356f2.png">

It is very useful so that you don't have to go to BetterTouchTool to figure out which keymap for an action.

**Comment by fifafu** [comment]
I'm not sure what your feature request is.
You want a context menu showing your shortcuts?

**Comment by chrisduong** [comment]
Yes, keyboard shortcuts, keymap, the same thing 😄

**Comment by fifafu** [comment]
But where would you want to show them ? 
BTT can't modify the menubar of existing apps.

**Comment by chrisduong** [comment]
I've just known that BTT can't modify the menubar of existing apps. I think I should close this issue, since it is what I want. Thanks.

**Comment by fifafu** [comment]
Ah thanks for clarifying!
