### ISSUE TITLE
Disable Fn Key while using toucher

### ISSUE THREAD

**Issue by dysquard** [fifafu/BetterTouchTool#729]
#### Description of bug/feature request/question:

I use karabiner to swap my Command and Fn key.
Then I have the problem that when I press the new CMD(old Fn) the Touch Bar still think I'm pressing Fn so it just show the control strip or F1 to F12.
Though this is caused by Apple I hope you guys could fix this ,thanks

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac:Macbook Pro 15 2016 Late
macOS version: 10.12
BetterTouchTool version :2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Comment by fifafu** [comment]
You can use system preferences -> keyboard  -> modifier keys to swap them, then everything will work correctly.

If not you should report it to Karabiner Elements. In BetterTouchTool I can't influence this.
