### ISSUE TITLE
TipTap with 2 or more fingers fix not working

### ISSUE THREAD

**Issue by Zhangyx39** [fifafu/BetterTouchTool#73]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
TipTap gesture with 1 finger fix works very well in my computer. I use it to switch applications and I think it's really great! However, when I try to use TipTap middle with 2 fingers fix, it just doesn't response. Same issue with other TipTap gesture with 2 or more fingers fix. Why is that?

**What kind of Mac are you using?**
MacBook Pro (13 inch with touch bar)

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which version of macOS are you running?**
macOS 10.12.1 Sierra

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Does it work if you spread your fingers a bit more?

**Comment by Zhangyx39** [comment]
It does! Thank you so much~
Besides, pinch with thumb and 2 fingers cannot be recognize. Is it because that I enable the 4 fingers pinch and spread in system preferences?

**Comment by fifafu** [comment]
That's probably because of the palm/thumb rejection logic I added for the new Macbook. I'll further improve that soon (it currently filters out most thumbs)

**Comment by Zhangyx39** [comment]
Oh! Thank you!
I think you did this to prevent touching the trackpad by mistake since the trackpad is much more larger than before, right? :)

**Comment by fifafu** [comment]
Yes!
