### ISSUE TITLE
Click and shortcut key actions NOT WORK in some games

### ISSUE THREAD

**Issue by wadxm** [fifafu/BetterTouchTool#730]
#### Description of bug/feature request/question:
Configure better touch tool for the Touch Bar customization of Don't Starve, and all the actions about mouse actions (clicks, right clicks, etc) and keyboard actions are not working, but mouse movement actions work nicely.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 2016, 15 inch
macOS version: 10.12.3
BetterTouchTool version: 2.071(608)

**Comment by fifafu** [comment]
Sorry, but probably the game doesn't get it's events via the normal macOS event mechanisms. Thus the BTT events are ignored.

I don't think I'll be able to fix that.
