### ISSUE TITLE
Feature Question "Copy Link To Trigger This Gesture"

### ISSUE THREAD

**Issue by nrcarnevali** [fifafu/BetterTouchTool#731]
When right clicking on a trackpad gesture this is the option you can choice. When selecting this option the text on the clipboard looks something along the lines of "btt://100". I've searched everywhere I could find and DONT understand what this function/feature does.

Can you please explain?

Thanks so much

**Comment by fifafu** [comment]
I needed this once for a personal project ;-)
If you copy that link and e.g. paste it in Safari, BetterTouchTool will perform the actions assigned.

You can also trigger it via Apple Script like this

```AppleScript
tell application "BetterTouchTool"
	open location "btt://170"
end tell
```
