### ISSUE TITLE
Corner Force click

### ISSUE THREAD

**Issue by disccomp** [fifafu/BetterTouchTool#732]
#### Description of bug/feature request/question:
Corner Force click top left & top right -> Maximize windows left/right not working

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad 2
#### Device information:
Type of Mac: Late 2009 27" iMac
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.084

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Haptic feedback is rapidly pulsating.

**Comment by seriouslynow** [comment]
having similar issue on new touchbar 15" MBP

top left corner force-click to open url in browser, haptic feedback pulses rapidly and many tabs open with url

**Comment by fifafu** [comment]
This should be fixed in the most current alpha (v2.095)
