### ISSUE TITLE
Strangest bug for 

### ISSUE THREAD

**Issue by tmmcz** [fifafu/BetterTouchTool#733]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think you forgot to write about the bug ;-) Please create a new ticket.

**Comment by tmmcz** [comment]
Haha, what the hell happened to my post?
