### ISSUE TITLE
tipTap left/right (1 finger fix) is not working after update to latest version

### ISSUE THREAD

**Issue by smthvitas** [fifafu/BetterTouchTool#74]
MacBook Air

OS:  macOS sierra 10.12.1

input: trackPad

My tiptop left/right gestures is not working after update to latest version( 1.963/552). Nothing changes after restart.

**Comment by smthvitas** [comment]
It's been set to Ctrl+Shift+Tab/Ctrl+Tab in all browsers.

How can I revert to an old version?

thanks for any help!

**Comment by fifafu** [comment]
Hi,

see #18

**Comment by smthvitas** [comment]
Thanks, I got it. Exactly what I need.
Excellent product!
