### ISSUE TITLE
Feature request: Is it possible to add JavaScript widget support

### ISSUE THREAD

**Issue by jimmyqum** [fifafu/BetterTouchTool#741]
Similar to Apple script widget

**Comment by fifafu** [comment]
Do you mean Java Script based Apple Scripts? (https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjb9di7-trTAhVCOBoKHW2WAEYQFggyMAE&url=https%3A%2F%2Fdeveloper.apple.com%2Flibrary%2Fcontent%2Freleasenotes%2FInterapplicationCommunication%2FRN-JavaScriptForAutomation%2FArticles%2FIntroduction.html&usg=AFQjCNGKxiOJHtDzj8LU6np6oriNj7_7mg&sig2=bvjAPH5bM1i6p3mdkCOksw )

**Comment by little-big-h** [comment]
I'd love that too: javascript for automation scripts in addition to AppleScript.
