### ISSUE TITLE
Preference for maximum gesture rotation

### ISSUE THREAD

**Issue by jonnyenglish** [fifafu/BetterTouchTool#744]
I love your app! I use it so much and makes the mac so much more powerful. Even bought a track pad cause I don't want to loose all my gestures when I'm in the office 😄 

But now since I got the new 2016 MacBook, I find myself using the huge trackpad a bit more from the side, which make my TipTap gestures a bit more vertical than usual. I've seen in the live view that they only get recognised as TipTaps when they have a certain angle. That makes me often do them a couple of times before they finally fire. Do you think something like a max angle feature would make sense? At least for me on the new MacBook it would 😉

**Comment by fifafu** [comment]
Hey,

the angle should be an issue, however you may need to increase the allowed distance between fingers, see this screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/25771118/b06a0f40-3248-11e7-9dab-70a1f7f664bb.png)


I'm closing here for now, as the angle is not considered for the Tip Tap gesture, if increasing the distance doesn't help, please let me know.
