### ISSUE TITLE
Feature Request: Click-through

### ISSUE THREAD

**Issue by rodalpho** [fifafu/BetterTouchTool#745]
#### Description of bug/feature request/question:
MacOS won't allow you to click on most controls, links, or buttons unless the window is focused. 

I run multiple monitors, and often watch a YouTube video on my second screen while working on the primary. When I want to interact with that browser window, I mouse over and click the pause button (or a link or anything except window controls, really) and nothing happens. Since MacOS doesn't support click-through, even though my mouse is directly over the pause button I need to first left-click the window to focus it and then click AGAIN in the exact same spot to pause the video.

Coming from Windows which supports click-through I find this behavior incredibly annoying and would like to change it.

Here's Gruber's take on it. He's against. Which is fine, for the default, I just want to change it!

http://daringfireball.net/2003/05/the_problems_with_click-through

And here's the FOSS sourcecode for an old non-maintained app that fixed the problem a couple years ago. Unfortunately it crashes on Sierra.

https://github.com/rgraciano/XClickThrough

Can this be added to BTT?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
integrated trackpad and external USB mouse

#### Device information:

Type of Mac: tMBP 15"
macOS version: 10.12.4
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
n/a

**Comment by fifafu** [comment]
Sorry, this probably won't be added to BTT.
It's quite complicated to get right, and there have been almost no requests for such a feature during the last few years. It's just too much work for a very small audience :-(

Maybe XClickThrough will work if you enable it in System Preferences => Security & Privacy => Privacy =>  Accessibility.
Although I doubt that it will work correctly with all apps.

Best,
Andreas

**Comment by rodalpho** [comment]
No, it doesn't. :/

Thanks anyway!
