### ISSUE TITLE
Bug: Control strip reappears if app-specific TB behavior set to Show BTT, hide control strip

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#75]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Have defined touch bar buttons for an app.  Bug scenario is:

-in app-specific settings for the app, set touch bar behavior to Show BTT bar, hide control strip.  Now, the app-specific touch bar is displayed and the control strip is now shown.  this is correct.
-in the app, if press Fn key, the function keys appear in touch bar
-But when you release Fn key, the BTT touch bar AND control strip appears
-if activate another window, and then return to the app, the display is correct (BTT touch bar, no control strip)

Note that the Sierra keyboard options are at their default (app controls with control strip and Fn shows function keys).  It is worse if set Sierra keyboard setting to "touch bar shows: app controls".   Then, releasing the Fn key leaves the touch bar blank in the app.

**What kind of Mac are you using?**
2016 MacBook Pro 13" 

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Thanks for reporting, will be fixed with 1.966 alpha in a few minutes!
