### ISSUE TITLE
Text in snap areas settings is editable.

### ISSUE THREAD

**Issue by zyumbik** [fifafu/BetterTouchTool#756]
#### Description of bug/feature request/question:
In Advanced Settings > Snap Areas the text below the image is editable.  

#### Device information:

Type of Mac: iMac, MacBook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Screenshots:
![image](https://cloud.githubusercontent.com/assets/16729927/24583186/4c5e2bb8-1785-11e7-9e5c-a9196bd8020e.png)
![image](https://cloud.githubusercontent.com/assets/16729927/24583182/35108d70-1785-11e7-91ab-a13cf7a34025.png)

**Comment by fifafu** [comment]
Will be fixed with next update.

**Comment by zyumbik** [comment]
Great, it's fixed! 
But now this area is scrollable. 
![image](https://cloud.githubusercontent.com/assets/16729927/25738464/a3871b34-31c0-11e7-81e6-22d7488f3b0c.png)
