### ISSUE TITLE
No default checkmark in app-specific touch bar behavior

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#76]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
In the "app-specific" menu below the list of apps, if you have not made a previous selection of "Touch bar behavior" none of the three possible settings shows a checkmark.  I assume that the first one (show BTT bar, show system control strip) is actually the default and should be checked.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Fixed with 1.967 alpha!
