### ISSUE TITLE
How to get return value of an Applescript pasted to clipboard

### ISSUE THREAD

**Issue by ColdOxygen** [fifafu/BetterTouchTool#765]
#### Description of bug/feature request/question:
I've found the AppleScript following fail to return the result to clipboard. I'm new to AppleScript, thanks very much for anybody could give a piece of suggestion.

tell application "Evernote"
	set theSelection to the selection
	return note link of item 1 in theSelection
end tell

**Comment by fifafu** [comment]
if you want to change the clipboard using Apple Script you need to use the 
```
set the clipboard to "xxx"
``` command

so something  like ```set the clipboard to note link of item 1 in theSelection```

**Comment by ColdOxygen** [comment]
Wow, I see how it works. Thanks a lot for your patience.
