### ISSUE TITLE
Move To Next monitor appears to have broken for me after latest MacOS update

### ISSUE THREAD

**Issue by crifkin** [fifafu/BetterTouchTool#768]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
One of my most frequent go-to actions "Move to Next monitor" isn't working anymore and the only change I can track it to is MacOS security update (10.12.4) installed on 4/1. 
I've tried changing the trigger, and confirmed that BTT is correctly taking other actions based on the trigger, so it's not a change in the keyboard settings or anything else. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard- - both internal and external wired Mac keyboard.

#### Device information:

Type of Mac: MacBook 12" Retina (both with and without external wired Mac keyboard)
macOS version: 10.12.4
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
No stack traces, no crashes, just can't get that action to fire. 

Note: Live View correctly registers the trigger and shows the text for "Move Window to Next monitor"
Other Snap actions are working properly, such as "Resize Window to Bottom Left Quarter/Corner", etc. 
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Is it possible you have changed any of the options shown in this screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/25013442/d56fa05c-2073-11e7-8305-de12c246fe0d.png)

**Comment by crifkin** [comment]
You are magic. 
Yes, it looks like the checkbox for "Use the monitor the mouse is on for all... " got checked. Unchecking that (and having Focused Window selected) fixed the problem. THANK YOU!!!
