### ISSUE TITLE
Disabling Acceleration

### ISSUE THREAD

**Issue by fxjkhr** [fifafu/BetterTouchTool#77]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
how do I disable mouse acceleration in the trackpad?  I searched your blog and I see three entries that mention it, but I cannot find the feature in the settings.

**What kind of Mac are you using?**
MacBook Pro (13-inch, Late 2016, Four Thunderbolt 3 Ports)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which version of macOS are you running?**
10.12.1 (16B2657)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Hi,

Sorry, BTT can not do that.

Best
Andreas
