### ISSUE TITLE
 N key not working

### ISSUE THREAD

**Issue by yesJB** [fifafu/BetterTouchTool#770]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The keyboard 'n' key does not work when BetterTouchTool is open. I recently downloaded BTT for trial testing so I'm not sure if that's a factor to consider.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro Early 2015
macOS version: 10.12.4
BetterTouchTool version: 2.08 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Steps to Reproduce:
1. Run BTT 
2. Type n key.
Expected: words like 'ninite' works fine
Result: 'iite'

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by rodalpho** [comment]
Did you map it somewhere? Try exporting your settings (to back them up) then wiping all your settings and see if the N key works.

**Comment by fifafu** [comment]
You have probably added it in the keyboard tab in BTT. Just delete it from there and it should be working again.

**Comment by yesJB** [comment]
I probably misclicked inputting one of the commands. It works fine now.
Thanks for the help!
