### ISSUE TITLE
Remained vertical gray line on right side of black menu bar when hide "other triggers" section

### ISSUE THREAD

**Issue by rambokang** [fifafu/BetterTouchTool#772]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question

When I hide "other triggers" section, vertical gray line is remained in Rt. side of black colored menu bar

#### Device information:

Type of Mac: New MacBook Pro 2016 non-touchbar
macOS version: Sierra
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Should be fixed in v2.097 alpha.
