### ISSUE TITLE
action pop-up menu almost invisible

### ISSUE THREAD

**Issue by diemoschwarz** [fifafu/BetterTouchTool#774]
#### Description of bug/feature request/question:

the action menu is almost hidden (see screenshot), 
just a few pixels are visible underneath the "attach additional action" button

#### Device information:

Type of Mac: retina MBP 13" 
macOS version: 10.10.3
BetterTouchTool version: 2.071
<img width="1127" alt="screen shot 2017-04-06 at 15 08 51" src="https://cloud.githubusercontent.com/assets/378151/24755740/9abee2bc-1adb-11e7-9b43-d028ad6b7204.png">

**Comment by fifafu** [comment]
Ah I think that's an autolayout issue with OS X 10.10 (autolayout was quite broken  back then...). It should be fixed in the current alpha version of BTT.
