### ISSUE TITLE
Question: What binary format is the preset export file?

### ISSUE THREAD

**Issue by bill-improbableio** [fifafu/BetterTouchTool#777]
#### Question
What binary format is the preset export file? And can it be easily converted to/from a human-readable text format e.g. JSON? Was hoping to write some scripts that modify the presets directly.

Thanks for all of your hard work!

**Comment by fifafu** [comment]
Hi,

don't invest time figuring out the old binary format (it's a core data binary store). The next version will completely change the format (to SQLLite) and offer JSON export. Should be ready sometime this weekend.

**Comment by fifafu** [comment]
With alpha 2.09 you can already have a preview of the new JSON import/export functionality. I'm thus closing here.
