### ISSUE TITLE
TouchBar Apple Script Widget does compute the widget size correctly

### ISSUE THREAD

**Issue by paulrouget** [fifafu/BetterTouchTool#778]
#### Description of bug/feature request/question:

TouchBar Apple Script Widget: the computation of the width of the widget is wrong. The text is cropped too early.

Here is 2 examples:

Printing "mmmmmm" will crop the text to "mmmm…"
While printing "012345678012345678012345678012345678012345678999990123456789" will show the full text.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: Macbook Pro 13"
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

In these screenshots, you can see that the first widget is cropped for no reason:

`echo mmmmmm`

<img width="1085" alt="touch bar shot 2017-04-07 at 3 25 01 am" src="https://cloud.githubusercontent.com/assets/373579/24781709/c88a858c-1b41-11e7-8b3e-bb638e5d1076.png">

`echo 012345678012345678012345678012345678012345678999990123456789`

<img width="1085" alt="touch bar shot 2017-04-07 at 3 26 08 am" src="https://cloud.githubusercontent.com/assets/373579/24781725/e48dc852-1b41-11e7-9c66-46fc25c0e5a0.png">

**Comment by fifafu** [comment]
Thanks for reporting! Should be fixed with the upcoming update.

**Comment by paulrouget** [comment]
Version 2.20 (640), this is still happening.
