### ISSUE TITLE
Touch ID Button

### ISSUE THREAD

**Issue by paulmoons** [fifafu/BetterTouchTool#78]
I was wondering if you would consider adding customisation for the Touch ID button (as opposed to the TouchBar) on the new MacBook Pros.

My understanding is that by default, triple clicking the button brings up an accessibility menu. It would be nice if this could be customised as well as enabling a double click action too.

Thoughts?

**Comment by fifafu** [comment]
I like the idea, but I have no idea if this will be possible ;-)
I'll look into it.

**Comment by paulmoons** [comment]
Thanks for taking the time and happy holidays. :)

**Comment by dogoku** [comment]
One more idea for the touch id button, would be to click it to lock screen/sleep (instead of wasting space on the touchbar)

**Comment by paulmoons** [comment]
> One more idea for the touch id button, would be to click it to lock screen/sleep (instead of wasting space on the touchbar)

+1 @dogoku Great idea if it's possible.

**Comment by niklasfink** [comment]
Hey @fifafu, are there any updates on this feature request yet? I think this is a highly anticipated feature and I don't understand why Apple didn't implement that as a sleep button by default. 
Would be awesome to have control over the Touch ID button! 🙂

**Comment by fifafu** [comment]
Sorry I have not yet found a way to make this work

**Comment by fifafu** [comment]
Closing as I still haven't found a way to achieve this.
