### ISSUE TITLE
[FeatureRequest] Sharing of recipes

### ISSUE THREAD

**Issue by torsday** [fifafu/BetterTouchTool#781]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Feature request: **sharing of recipes**. Notably the Touch Bar. This would be a killer feature! e.g. I have a Touch Bar button to run PSR Fixer on the file I have open in PhpStorm. I'm sure other developers would love to do this without having to figure out how.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro w/ Touch Bar
macOS version: Sierra
BetterTouchTool version: Newest stable

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

the next version (currently in alpha) supports JSON Export and Import. I'll also provide better ways to load such presets easily and I'm working on a platform that lets users share their setups online.

Best,
Andreas

**Comment by fifafu** [comment]
I will soon (2-3 weeks) present a little platform for sharing presets. Stay tuned :-)
