### ISSUE TITLE
BTT Remote server for windows

### ISSUE THREAD

**Issue by bschlenk** [fifafu/BetterTouchTool#787]
#### Description of bug/feature request/question:

It would be cool to be able to use the BTT Remote app to control a Windows machine. I have my desktop connected to my TV and use a wireless mouse/keyboard, but being able to whip out my phone and use it instead would be so much more convenient. The BTT Remote app has a very useable interface and it would be nice to have a consistent interface between controlling a Mac and Windows computer.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

N/A

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, unfortunately I'm really not a windows developer, thus this won't be possible for me to do (without spending a whole lot of time on it). Unfortunately the existing code couldn't be reused at all on windows.
