### ISSUE TITLE
key repeat issue

### ISSUE THREAD

**Issue by mhatsis** [fifafu/BetterTouchTool#789]
#### Description of bug/feature request/question:

dont see the cog for key repeat next to key recorder field as says in the update docs. see something that resembles a key repeat "allow to trigger again by repeating last key-down..." when i click "Key sequence" 

tried using that and doesn't seem to repeat anything- basically, I'm trying to map the '=' key to zoom in   , by default zoom is '+', so i gotta hit 'SHIFT & =' everytime i wanna zoom . 
BTT does it but no repeat on there - which is the way the default zoom out works ( keeps zooming until key is released ) program I'm tryin to get this to work in is Ableton Live 9.7
any help would be greatly appreciated

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
keyboard 

#### Device information:

Type of Mac: macbook air 11inch early 2014
macOS version: 10.10.5
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

Key Sequences don't support key repeat currently. However you should be able to add a normal shortcut.

![image](https://cloud.githubusercontent.com/assets/8820811/25012403/abca9db8-2070-11e7-8da8-f738d80e2278.png)

**Comment by mhatsis** [comment]
what? still no cog either way. How do i get to the cog? or why is it missing?
![screen shot 2017-04-13 at 5 43 30 pm](https://cloud.githubusercontent.com/assets/21162618/25025420/392ecc20-2070-11e7-867b-b0a47811394e.png)

**Comment by fifafu** [comment]
ah you are probably still using OS X 10.10, I think there was an autolayout bug that causes this to not show up. This should be fixed in the latest alpha version of BetterTouchTool. 

Best,
Andreas

**Comment by mhatsis** [comment]
yeah, mentioned in the OP that i'm on 10.10.5. I don't plan on upgrading for a while as there's nothing in the new OS's that I need, and all upgrading OSX does these days is give me headaches. Would still be on Mountain Lion if programs still supported it. Anyway, thanks Ill check out the alpha.

**Comment by mhatsis** [comment]
OK so I got the new alpha and the key repeat function doesnt work. The shortcut works when I don't have key repeat enabled, but when I enable Key repeat as shown below, it does not trigger the shortcut at all - nor does it repeat. It will only trigger the shortcut when repeat is turned off. Maybe I'm doing something wrong? Thanks!
![screen shot 2017-04-13 at 6 09 29 pm](https://cloud.githubusercontent.com/assets/21162618/25026329/fe2f34b2-2073-11e7-963f-6afce2163fb3.png)

**Comment by mackdata** [comment]
I also have the issue, where the 'wheel' doesn't show up, next to the 'shortcut'.
- System: OSX 10.10.5; with BTT version 20.71 build 608.  

![screen shot 2017-05-03 at 10 01 32](https://cloud.githubusercontent.com/assets/15065392/25652257/95e68526-2fe7-11e7-91b4-fd7c65107bfa.png)
