### ISSUE TITLE
Wacom Intuos Tablet Gestures

### ISSUE THREAD

**Issue by jacobj2** [fifafu/BetterTouchTool#791]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question: 
Gestures work great on the MacBook trackpad but do not work on Wacom Intuos tablet. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Wacom Intuos Pen and Touch Small (CTH-480)

#### Device information:

Type of Mac: 2016 MacBook Pro 13" with TouchBar
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.08 (610)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The new btt alpha 2.315 brings back basic wacom support (needs to be enabled in the advanced settings):

<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/32994291-5417df16-cd65-11e7-96cb-964b60e14b9d.png">

However I have only tested it on the Bamboo tablets. The API should be the same for all tablets though.
