### ISSUE TITLE
Right-click gesture start sensitivity 

### ISSUE THREAD

**Issue by poof86** [fifafu/BetterTouchTool#795]
#### Description of bug/feature request/question:

Using the right button to start a gesture sometimes interferes with the normal right click action. Especially while using a stylus the cursor can move a tiny bit when you right click. This unintentionally starts a gesture and sometimes even matches it with one of the gesture commands. (this makes it more a bug than a feature request)

Maybe have tiny gestures be ignored or only start gestures when the right mouse button is hold a little longer?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mostly Stylus?

#### Device information:

Type of Mac: iMac 15,5
macOS version: Sierra 10.12.3
BetterTouchTool version: 2.08 (610)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This problem makes it quite impossible to use the gesture commands with my stylus. :(

**Comment by fifafu** [comment]
Yep, I have also noticed this.
With the next version I'll make the necessary movement bigger before starting the drawing recognition!

**Comment by fifafu** [comment]
This has been added with v2.10!
![image](https://cloud.githubusercontent.com/assets/8820811/25771296/56351758-324e-11e7-984d-688298d11064.png)
