### ISSUE TITLE
F1-F12 does not show on TouchBar

### ISSUE THREAD

**Issue by mattPiratt** [fifafu/BetterTouchTool#797]
#### Description of bug/feature request/question:
After installing BTT the way Fn button worked, does not work anymore. Pressing Fn does not show F1-F12 buttons on TouchBar. Even after uninstalling the BTT. Even after un-checking "Enable TouchBar support" in "General TouchBar settings.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MackBook Pro Touch bar

#### Device information:
Type of Mac: Pro 2016
macOS version:  10.12.4
BetterTouchTool version: 2.09

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
No additional info. I dont know how to get byck my Fn key functionality
But double tapping Fn key correctly triggers "Speach to text" function.

**Comment by fifafu** [comment]
Have you already tried to restart your Mac? BTT doesn't change the FN behavior as farnas I can tell. Or maybe did you disable that behavior in System Preferences -> Keyboard?

**Comment by mattPiratt** [comment]
Yes, few Mac restarts. Also in  System Preferences -> Keyboard all is ok. Tried to google this, but no one has this issue. I dont believe this is a coincidence that after playing with BTT this has broken.

**Comment by fifafu** [comment]
BTT doesn't alter any settings, thus if it's quit it doesn't influence the system anymore.
Maybe in System preferences => Keyboard try to change "Press FN Key To" => "Expand Control Strip", then quit System Preferences and afterwards change it back to "Show F1, F2, etc. keys"

**Comment by mattPiratt** [comment]
Hey again. I figured it out! This problem was caused by Karabinier-Elements. Have installed it same time as BTT. Uninstalling it fixed my issue. Had nothing to do with BTT. Sorry for confusion.
