### ISSUE TITLE
2.09 alpha: Tap sequences not upgraded

### ISSUE THREAD

**Issue by aitte2** [fifafu/BetterTouchTool#798]
After the upgrade to the new JSON format, I noticed that the "trackpad gesture" field was blank for two of my actions under the Trackpads tab.

Clicking on them revelead that BTT thought it was a "tap sequence" gesture, but nothing showed up in their "trackpad gesture" field in the table.

So I manually set them to the tap sequence gesture and set them up again.

That made the field say the usual: "Tap Sequence: [4] [3] [2] [1]".

Everything else seems to have migrated fine. All drawings. All keyboard keys. All other predefined gestures. It's all there as far as I can see.

**Comment by fifafu** [comment]
Thanks a lot for reporting. I'll fix that.

**Comment by fifafu** [comment]
Found and fixed the issue!
