### ISSUE TITLE
MacBook Pro Trackpad keeps vibrating when you force click in the corner.

### ISSUE THREAD

**Issue by YunchengHua** [fifafu/BetterTouchTool#799]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When you force clicked in one of the four corners of the trackpad, the trackpad will keep vibrating.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac:macbook pro 2016
macOS version: 10.12.4
BetterTouchTool version: 2.09

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! Will be fixed with the next update. Closing here as I'm tracking it in this issue already: #675
