### ISSUE TITLE
[TouchBar] 0px free space after button resets to 5px

### ISSUE THREAD

**Issue by ErikMinekus** [fifafu/BetterTouchTool#8]
#### Description of your bug/question/feature request...:
- Go to customize a Touch Bar button
- Set "Free space after button" to 0px and click Save
- Go back to customize the button
- The value is reset to 5px, however on the Touch Bar the button correctly has 0px spacing

1px and higher seems to work correctly. Also, the default spacing Apple uses seems to be more like 8px, with 1px for back/forward buttons.

**What kind of Mac are you using?**
15" MacBook Pro 2016 w/ Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which version of macOS are you running?**
macOS 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
BTT 1.96

**Comment by fifafu** [comment]
Thank you, I'll fix that soon!

**Comment by ErikMinekus** [comment]
Not sure if I should create an issue for every small problem, since it's still very much in development, but the "Enable Touch Bar support" checkbox doesn't do much either. It says you need to restart BTT for it to take effect, but after restarting it's enabled again.

**Comment by fifafu** [comment]
Ahhh, thanks for reporting! Yes, please create an issue for everything if possible :-)

**Comment by fifafu** [comment]
Should be fixed in 1.964 alpha

**Comment by ErikMinekus** [comment]
"Free space after button" still resets to 5px when set to 0px in BTT 2.071.

**Comment by fifafu** [comment]
Weird, could you try the latest alpha? It seems to be a fine here.

**Comment by ErikMinekus** [comment]
You're right, does seem to be fixed in the alpha build, so nevermind then :)
