### ISSUE TITLE
Too much palm rejection 

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#80]
#### Description of your bug/question/feature request...:
The palm rejection works. But a bit too much. I checked using live view that BTT rejects the edges of the trackpad. However this is actually too much rejection since palms are only usually accidentally being activated in the corners of the trackpad so making the parts of the trackpad between the corners disabled is actually harmful since often when try to do a 4 finger click on the trackpad where my fourth finger is in the bottom edge but in the middle, the finger get's rejected and the 3 finger gesture is triggered instead.  

**What kind of Mac are you using?**
MPB Touchbar 15"

**Which version of macOS are you running?**
10.12.1

**Other information:** (suggestions how to fix)
Either add an option or by default, enable the bottom edge of the trackpad but only disable the corners. Please ask if you need a video demonstrating this or need more info. Thank you.

**Comment by fifafu** [comment]
I have created a completely new palm/thumb rejection in 1.964 alpha, but there is still room for improvement. Will get better over the next few days as I do more testing.
