### ISSUE TITLE
single tap in 2.09Alpha is severely sluggish.  

### ISSUE THREAD

**Issue by stormystormy** [fifafu/BetterTouchTool#802]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

- Single tap on trackpad registers less than 25% of the time.  
- However, if I quit BTT, the tap sensitivity is back.  
- Once I rolled back to 2.04, the tap functionality was restored.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.09Alpha 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mh I can't seem to reproduce this. Are you touching the trackpad only with one finger or are other fingers resting on the trackpad?

**Comment by stormystormy** [comment]
Just one finger.  Has always been responsive until I installed the new alpha.  Then it stopped working.  No settings were changed.

**Comment by hhorigian** [comment]
I have the same issue.  Single tap 25% or more of the times not recognized. Running on alpha 2.091
Where can I download previous versions to try and prevent this issue. It's almost impossible to work.
Thanks!!

**Comment by fifafu** [comment]
Unfortunately I can't reproduce this on any of my machines.
Could you attach an export of your settings? What kind of Macbook are you using exactly?

**Comment by fifafu** [comment]
Could you try if **disabling** thumb handling / thumb recognition fixes this? Maybe there is a bug somewhere in that functionality. See this screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/25071461/88db68f6-22b8-11e7-9bb5-fe9ed39ea3b8.png)

**Comment by stormystormy** [comment]
Andreas -- Today's Alpha release 2.094 fixed the unresponsiveness single tap issue.   
All is well again.  :-) 
-Rob
FYI - The thumb handling whether on/off made no difference.
<img width="272" alt="screen shot 2017-04-16 at 2 20 57 pm" src="https://cloud.githubusercontent.com/assets/9405817/25074077/386dcfb4-22b1-11e7-8a33-8506834c89a9.png">

**Comment by fifafu** [comment]
Thanks a lot for testing!

**Comment by hhorigian** [comment]
Hi, how are you!
I was out for some time as I travelled and got back home. 
I still have the same issue with the trackpad not recognizing single tap.

Any ideas?
Version 2.12 (631)


![2017-05-26_12-46-00](https://cloud.githubusercontent.com/assets/4301655/26501933/5b656c96-4211-11e7-8f00-a0919d41038d.png)
