### ISSUE TITLE
[BUG] Double tap required to open BTT Touchbar

### ISSUE THREAD

**Issue by itxsvv** [fifafu/BetterTouchTool#803]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Double tap on control strip icon required to open btt touchbar ;(
But sometimes its works from one tap

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 13 with touchbar
macOS version: MacOS Sierra
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That happens when you close the bar using the x button on the left (close it by pressing the BTT icon instead). Unfortunately this can not be fixed currently due to API limitations.

**Comment by itxsvv** [comment]
Hi!
It is possible remove x button?

**Comment by fifafu** [comment]
Unfortunately only if you disable the control strip in the "general touchbar settings" in BTT

**Comment by itxsvv** [comment]
Can you remove x button in future release? ;-) or add on/off switch?
Its is 100% possible - TouchSwitcher has control strip icon , but not have x button

**Comment by fifafu** [comment]
That's interesting, I currently don't know of a way to get rid of the x button but I'll check again.

However TouchSwitcher also seems to show the x button on my machine

**Comment by itxsvv** [comment]
Uhh.. yes.. its show 'Esc' if TouchSwitcher in focus and show 'x button' in other apps.
Anyway - tnx for great app ;) Touchbar now useful with BTT!
