### ISSUE TITLE
BTT crash when new iPhone instal tries to open preferences on Mac

### ISSUE THREAD

**Issue by KrisGL** [fifafu/BetterTouchTool#804]
After upgrading my Mac version of BTT (i.e. paying for it) I downloaded the BTT remote app onto my iPhone SE which connected fine.  However directly after connection a message appeared on the iPhone recommending "Tap here to open the Preferences on you Mac" as no remote actions were configured.  On tapping in the recommended place the app on Mac promptly crashed and has done so repeatedly even after unloading and reloading apps on both Mac and iPhone.  This error is completely consistent. The remote app connects each time on ip 192.168.1.92 if this is of any help.

15" Macbookpro retina  (mid2012) running  Sierra 10.12.4
Iphone SE running iOS 10.3.1
BTT ver 2.071 (Mac)

[BetterTouchTool_2017-04-15-175351_CGL-MBPro15-1.docx](https://github.com/fifafu/BetterTouchTool/files/923739/BetterTouchTool_2017-04-15-175351_CGL-MBPro15-1.docx)

**Comment by fifafu** [comment]
Thanks, this should be fixed with the next update!
