### ISSUE TITLE
Any way to get the same back/forward 2finger swipe feature on safari in ifinder with BTT?

### ISSUE THREAD

**Issue by ksally** [fifafu/BetterTouchTool#805]
#### Description of bug/feature request/question:
Title. A way to get the "back/forward" feature 2finger swipe on safari in ifinder using BTT?

**Comment by rodalpho** [comment]
Yes, map command-[ and command-]. I do this myself.

**Comment by ksally** [comment]
I dont even have these keys on my macbook pro 2016 nTB keyboard haha. But thnx anyways ! :) maby u could export your commands and share ?

**Comment by rodalpho** [comment]
Yes you do. I'm looking at my tMBP 15" right now. The command key is just to the left of the spacebar. The right and left square bracket keys are to the right of the P key.

**Comment by ksally** [comment]
Yea, should have said that I don't have US keyboard but NOR. So iguess i need to find out what the shortcuts are on this keyboard.

**Comment by rodalpho** [comment]
Go to system prefs, keyboard, shortcuts, app shortcuts, Finder.app, and remap the menu actions "Back" and "Forward" to buttons you have on your NOR keyboard. Then you can map to those buttons in BTT.

That way you can go back/fwd in Finder.app both using your keyboard and swiping on the touchpad.

**Comment by ksally** [comment]
Thanks alot !:) Finally got it working.
