### ISSUE TITLE
BTT 2.093 Quits on launch

### ISSUE THREAD

**Issue by gasparschott** [fifafu/BetterTouchTool#806]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

BTT V.2.093 quits on launch.

#### Device information:

Type of Mac: MacBook Pro Early 2015
macOS version: 10.12.4
BetterTouchTool version: 2.093

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

CRASH REPORT:
---
Process:               BetterTouchTool [2485]
Path:                  /Applications/Utilities Other/*/BetterTouchTool.app/Contents/MacOS/BetterTouchTool
Identifier:            com.hegenberg.BetterTouchTool
Version:               2.093 (619)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           BetterTouchTool [2485]
User ID:               503

Date/Time:             2017-04-16 09:35:34.356 -0700
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        56F78BEB-AAB5-D3A8-A0DE-CB1CEB219096

Time Awake Since Boot: 480 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007fff4f750fdf
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x7fff4f750fdf:
    MALLOC_SMALL           00007f8135800000-00007f8137800000 [ 32.0M] rw-/rwx SM=PRV  
--> STACK GUARD            00007fff4bf51000-00007fff4f751000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                  00007fff4f751000-00007fff4ff51000 [ 8192K] rw-/rwx SM=COW  thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_trace.dylib         	0x00007fffc9f41c98 _os_log_fmt_flatten_data + 46
1   libsystem_trace.dylib         	0x00007fffc9f46a86 _os_log_impl_flatten_and_send + 1856
2   libsystem_trace.dylib         	0x00007fffc9f4870d _os_log_with_args_impl + 464
3   libsystem_asl.dylib           	0x00007fffc9d3bef9 syslog + 290
4   libcopyfile.dylib             	0x00007fffc9c4b775 copyfile + 6561
5   com.apple.Foundation          	0x00007fffb60a79eb -[NSFilesystemItemCopyOperation _handleFTSEntry:] + 476
6   com.apple.Foundation          	0x00007fffb60a7688 -[NSDirectoryTraversalOperation main] + 312
7   com.apple.Foundation          	0x00007fffb5fd9644 -[__NSOperationInternal _start:] + 672
8   com.apple.Foundation          	0x00007fffb60ee293 -[NSFileManager copyItemAtPath:toPath:options:error:] + 263
9   com.hegenberg.BetterTouchTool 	0x000000010fcd02b7 -[BetterTouchToolAppDelegate createCopyOfFileAtPath:withExtension:] + 224
10  com.hegenberg.BetterTouchTool 	0x000000010fcd0448 -[BetterTouchToolAppDelegate backupOldDatabase] + 244
11  com.hegenberg.BetterTouchTool 	0x000000010fcd0ddc -[BetterTouchToolAppDelegate persistentStoreCoordinator] + 53
12  com.hegenberg.BetterTouchTool 	0x000000010fcd2119 -[BetterTouchToolAppDelegate managedObjectContext] + 53

**Comment by fifafu** [comment]
Thanks for reporting! Could you check whether 2.094 alpha fixes this?  https://bettertouchtool.net/releases/btt2.094.zip

**Comment by gasparschott** [comment]
Yes, thanks! This version works.
Happy Easter!
