### ISSUE TITLE
Bottom of "Keyboard" tab garbled

### ISSUE THREAD

**Issue by jchayat** [fifafu/BetterTouchTool#808]
#### Description of bug/feature request/question:

Bottom of "Keyboard" tab garbled. See Screenshot:

![image](https://cloud.githubusercontent.com/assets/1694029/25072875/77bd8a98-22e2-11e7-94c3-d7c692709074.png)

Problem seems to have started after one of the latest BTT updates (can't pinpoint exact version).

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.10.5 (14F2315)
BetterTouchTool version: 2.071

**Comment by fifafu** [comment]
Hey,

that's a bug with OS X 10.10, but you can try upgrading to the latest alpha of BTT, there it should already be fixed.
