### ISSUE TITLE
Touch Bar - individual App behaviour

### ISSUE THREAD

**Issue by lucaingold** [fifafu/BetterTouchTool#809]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Would be great if there will be an option to disable BetterTouchTool Touch Bar in certain applications. For example, I want the default touch bar in safari permanently without enabling it every time manually. It should have a setting

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:
Type of Mac: MacBook Pro 2016
macOS version: 10.12.4
BetterTouchTool version: 2.084

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Click the "app specific" button below the app list in BTT, there is a setting for that ;-)
