### ISSUE TITLE
One finger scrolling

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#81]
#### Description of your bug/question/feature request...:
Is there a one finger scrolling option? I see how to disable it but how is it enabled?

<img width="508" alt="screen shot 2016-12-11 at 10 58 19 am" src="https://cloud.githubusercontent.com/assets/9432573/21077756/d972fb2a-bf90-11e6-86e5-e01cef60a043.png">

**Comment by fifafu** [comment]
Ah, this is for magic mouse only, I'll make that more obvious in the next version :-)
