### ISSUE TITLE
Predefined Action to Enable/Disable Night Shift

### ISSUE THREAD

**Issue by bronzini** [fifafu/BetterTouchTool#811]
#### Description of bug/feature request/question:
Add predefined action to enable/disable night shift. For former users of flux, which had a menu bar item to quickly disable color shifting, this would be super handy.

E.g. if I'm watching a video or looking at an image that I want to see with true color, I may want to quickly turn Night Shift on/off—that requires opening System Preferences, clicking Display then Night Shift and then turning the feature off. A BTT shortcut would be awesome!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
This would be a new predefined action on macOS.

#### Device information:
Type of Mac: N/A
macOS version:  macOS 10.12.4+
BetterTouchTool version:  N/A

**Comment by fifafu** [comment]
Added in v2.10!

**Comment by Jendker** [comment]
Is this action the reason why Flux requests the access to BetterTouchTool in automation in Mojave? Is it somehow coupled here?
![bildschirmfoto 2018-11-29 um 11 54 33](https://user-images.githubusercontent.com/14967831/49217335-92b54a80-f3cd-11e8-99be-afcf23c23790.png)

**Comment by fifafu** [comment]
Sorry, no idea why Flux needs access to BTT. I don't think it's related.
