### ISSUE TITLE
Pinch stop working

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#812]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
pinch stop working after latest update

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

trackpad

#### Device information:

Type of Mac: MacBook Pro 2016 15"
macOS version:  10.12.4
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mh I don't think there has been a change to pinches. Don't they work at all for you out do they stop working after a while?

**Comment by justinpma** [comment]
Sorry, I found a gesture on the global section. Remove it and working now.
