### ISSUE TITLE
Magic Mouse gestures won't work until i open BetterTouchTool's pref

### ISSUE THREAD

**Issue by MiRO92** [fifafu/BetterTouchTool#813]
with the last alpha update 2.094, the magic mouse gestures don't work and i have to open BetterTouchTool's pref each time i start up my MacBook Pro so it work again.

**Comment by fifafu** [comment]
Does this still happen with v2.10?

**Comment by MiRO92** [comment]
yes it's still present :(

**Comment by MiRO92** [comment]
Oh please, fix this damn issue, i'm really getting sick of it :(
