### ISSUE TITLE
Close Window Below Cursor does not work in Mission Control

### ISSUE THREAD

**Issue by danjjl** [fifafu/BetterTouchTool#815]
#### Description of bug:

Assigning a shortcut to *Close Window Below Cursor* in the *Mission Control* *Application* does not close the window below the cursor.

The action seems to never be triggered.

I tried assigning a *Normal Mouse* shortcut (*Middle Mouse Button*) and using a *Keyboard shortcut* (`^Q`).

#### Affected input device:

- Normal Mouse (middle click)
- Keyboard (`^Q`)

*(I did not try any other devices)*

#### Device information:

Type of Mac: MacBook Pro (13-inch 2016)
macOS version: 10.12.4
BetterTouchTool version: 2.071

*(Do let me know if you can reproduce this bug and if I can provide any extra useful information)*

**Comment by fifafu** [comment]
This seems to work fine for me, however it may not work with all kind of windows.
What application's window did you try to close?
![image](https://cloud.githubusercontent.com/assets/8820811/25562892/ef5d059e-2dcb-11e7-8cf6-03c2e2f9dc94.png)

**Comment by danjjl** [comment]
I probably configured the shortcut wrong.

This is what I was doing:
<img width="1018" alt="screen shot 2017-05-02 at 10 01 16" src="https://cloud.githubusercontent.com/assets/747240/25609231/9c493504-2f1e-11e7-8469-cb2f0c0d4640.png">

**Comment by fifafu** [comment]
ah yes, unfortunately you can't assign any actions specifically to the mission control app, as there is no way to detect whether the mission control app is active.
You'll have to put that shortcut in the global section.
