### ISSUE TITLE
[Feature Request] Emulation of system/app-specific touch bar functions within BTT

### ISSUE THREAD

**Issue by DTowersM** [fifafu/BetterTouchTool#816]
#### Description of bug/feature request/question:
Add a widget that lets us emulate system/app-specific touch bar (TB) buttons, within the BTT TB profile. Right now, I find myself constantly switching between BTT TB Profile, and the default TB Profile to get the best parts of each. Some apps have a "Customize Touch Bar..." option which shows the different possible TB-buttons available to the user, this could possibly be integrated or emulated in BTT.

In Photoshop (for example) theres a wonderful opacity scrubber, history scrubber, and blending mode scrubber which I would love to be able to integrate into my Photoshop BTT TB profile. In Safari, theres a tab switcher/video scrubber which I would love to be able to use without switching out of BTT.

Also last little bit, if you do add these functions, please let us change the colors and icons for these added buttons.

Thank you for looking over this,

Daniel T.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:

Type of Mac: 2016 13" Touch Bar MacBook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.094 (620)

**Comment by fifafu** [comment]
Hey,

unfortunately that is not possible because BTT can not access the custom touch bars other apps provide due to technical limitations. 

What do you mean exactly by changing the color and icons of the buttons? You can already change the color & icons of the buttons defined via BTT. Or do you mean something else?
