### ISSUE TITLE
imported presets with empty gestures/commands

### ISSUE THREAD

**Issue by alexanderswoo** [fifafu/BetterTouchTool#818]
#### Description of bug/feature request/question:
exporting presets works on one mac, when i want to import it to another mac the actions and apps are not imported.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
-

#### Device information:

Type of Mac: macbook pro 15" 2009 + 2013
macOS version: el capitan on 2009er macbook pro + sierra on 2013 macbook pro
BetterTouchTool version: both 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

Could you forward the exported json to me (boastr.net@gmail.com) or attach it here?

Best
Andreas

**Comment by alexanderswoo** [comment]
Hi Andreas,


thank you!



Alex

**Comment by fifafu** [comment]
Hi Alex,

I'm sorry in case I missed it, but did you send that export to me? Or did Github maybe remove the attachment ?

Best,
Andreas

**Comment by alexanderswoo** [comment]
the .json should be attached.

Alex

**Comment by fifafu** [comment]
Seems like Github is removing the attachment then. Could you send it directly to boastr.net[at]gmail.com? (or attach via the website? I think it's only removed if you reply by email)

**Comment by fifafu** [comment]
Thank you, now I got it :-)
However it seems to import correctly here - are you sure your other machine is also running the BTT alpha? (2.094)?

**Comment by Meflou** [comment]
Importing is not working for me too. It only import the Application icons but not the gestures.
