### ISSUE TITLE
Cannot click when palm touching edge

### ISSUE THREAD

**Issue by notsosuperman** [fifafu/BetterTouchTool#82]
The palm rejection allows me to two-finger scroll when my palm is touching the edge of the trackpad. However, I cannot single click when my palm is touching the edge of the trackpad. I feel the haptic feedback, but as long as some palm is touching, macOS doesn't register a click.

**What kind of Mac are you using?**
Late 2016 15" MBP

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Built-in trackpad

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Running 1.963

Thanks!

**Comment by fifafu** [comment]
Should be fixed in 1.964 alpha
