### ISSUE TITLE
[Bug] Flickering Touchbar Button with Applescripts Widget 

### ISSUE THREAD

**Issue by DTowersM** [fifafu/BetterTouchTool#825]
#### Description of bug/feature request/question:
Your program is amazing, I'm slowly figuring out how to completely replace the standard touch bar provided.

This bug only occurs when an Applescripts Widget is imbedded within a button group. Pressing the command, option, control, fn or shift keys causes the applescripts widget to momentary freak out, and for a split second the widget will display the default icon (instead of its alternate icon) as well as displaying the name of the widget (instead of the return value).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:
Type of Mac: 13" MacBook Pro 2016 with Touchbar
macOS version: 10.12.4
BetterTouchTool version: 2.04

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

**Comment by johnw188** [comment]
Came here to report the same thing. Only happens when a modifier key is pressed. At one point I was able to get it to stay stuck in the default state for a few seconds by mashing shift really fast.

**Comment by AndenIDK** [comment]
I still have this issue.. :(

**Comment by fifafu** [comment]
This should be much better with v 2.331 (currently in alpha). You can try it by using the "Check for alpha version updates" button.
