### ISSUE TITLE
Touchbar BTT not working after press close

### ISSUE THREAD

**Issue by jjalonso** [fifafu/BetterTouchTool#828]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Everytime you have some BTT controls opened in the touchbar and you press the (X) button at left, it screw up the bar, for example, if the BTT button to open it was in control strip, it require now 2 taps to open it again, in case was not in control strip and was binded to a key like cmd for example, it doesnt show anymore when you press it.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

touchbar

#### Device information:

Type of Mac: macbook pro 13" touchbar
macOS version: 10.12.4
BetterTouchTool version: 2.094 (620)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is currently not fixable. See e.g. #177

**Comment by jjalonso** [comment]
Thanks you for the note.
