### ISSUE TITLE
OSX 10.12.5 beta crash

### ISSUE THREAD

**Issue by fregattegit** [fifafu/BetterTouchTool#835]
Hi,

are there any known issues with OSX 10.12.5 beta.

Since my last update btt crashes after start:

Date/Time:       2017-04-23 00:29:14 +0200
OS Version:      Mac OS X 10.12.5 (Build 16F60a)
Architecture:    x86_64
Report Version:  25

Data Source:     Stackshots

Command:         BetterTouchTool
Path:            /Applications/Tools/BetterTouchTool.app/Contents/MacOS/BetterTouchTool
Version:         2.09 (616)
Parent:          launchd [1]
PID:             58742

Event:           timeout
Duration:        0.39s (process was unresponsive for 2 seconds before sampling)
Steps:           4 (100ms sampling interval, 97 samples avoided due to audio)

Hardware model:  MacBookPro10,1
Active cpus:     8

Fan speed:       3021 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  4  start + 1 (libdyld.dylib + 21045) [0x7fffc8f29235]
  4  NSApplicationMain + 1237 (AppKit + 24078) [0x7fffb0cb5e0e]
  4  -[NSApplication run] + 926 (AppKit + 242651) [0x7fffb0ceb3db]
  4  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796 (AppKit + 8136686) [0x7fffb14727ee]
  4  _DPSNextEvent + 1120 (AppKit + 289364) [0x7fffb0cf6a54]
  4  _BlockUntilNextEventMatchingListInModeWithFilter + 71 (HIToolbox + 199462) [0x7fffb275db26]
  4  ReceiveNextEventCommon + 184 (HIToolbox + 199673) [0x7fffb275dbf9]
  4  RunCurrentEventLoopInMode + 240 (HIToolbox + 200380) [0x7fffb275debc]
  4  CFRunLoopRunSpecific + 420 (CoreFoundation + 542020) [0x7fffb31fd544]
  4  __CFRunLoopRun + 2221 (CoreFoundation + 544845) [0x7fffb31fe04d]
  4  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9 (CoreFoundation + 802153) [0x7fffb323cd69]
  4  _dispatch_main_queue_callback_4CF + 925 (libdispatch.dylib + 60076) [0x7fffc8f00aac]
  4  _dispatch_client_callout + 8 (libdispatch.dylib + 6396) [0x7fffc8ef38fc]
  4  _dispatch_call_block_and_release + 12 (libdispatch.dylib + 42276) [0x7fffc8efc524]
  4  __20+[BTTTouch mt_stop:]_block_invoke + 1345 (BetterTouchTool + 406869) [0x10a419555]
  4  MTDeviceStop + 240 (MultitouchSupport + 12254) [0x7fffc326ffde]
  4  usleep + 54 (libsystem_c.dylib + 526950) [0x7fffc8fdea66]
  4  __semwait_signal + 10 (libsystem_kernel.dylib + 106310) [0x7fffc9057f46]
 *4  semaphore_wait_continue + 0 (kernel + 1107152) [0xffffff800030e4d0]

Process:         BetterTouchTool [58742]
Path:            /Applications/Tools/BetterTouchTool.app/Contents/MacOS/BetterTouchTool
Architecture:    x86_64
Parent:          launchd [1]
UID:             504
Task size:       34.79 MB
CPU Time:        0.008
Note:            Unresponsive for 2 seconds before sampling
Note:            3 idle work queue threads omitted

  Thread 0x1c7957           DispatchQueue 1           4 samples (1-4)           priority 46 (base 46)     cpu time 0.008
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [253], IO tier 0>
  4  start + 1 (libdyld.dylib + 21045) [0x7fffc8f29235] 1-4
    4  NSApplicationMain + 1237 (AppKit + 24078) [0x7fffb0cb5e0e] 1-4
      4  -[NSApplication run] + 926 (AppKit + 242651) [0x7fffb0ceb3db] 1-4
        4  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796 (AppKit + 8136686) [0x7fffb14727ee] 1-4
          4  _DPSNextEvent + 1120 (AppKit + 289364) [0x7fffb0cf6a54] 1-4
            4  _BlockUntilNextEventMatchingListInModeWithFilter + 71 (HIToolbox + 199462) [0x7fffb275db26] 1-4
              4  ReceiveNextEventCommon + 184 (HIToolbox + 199673) [0x7fffb275dbf9] 1-4
                4  RunCurrentEventLoopInMode + 240 (HIToolbox + 200380) [0x7fffb275debc] 1-4
                  4  CFRunLoopRunSpecific + 420 (CoreFoundation + 542020) [0x7fffb31fd544] 1-4
                    4  __CFRunLoopRun + 2221 (CoreFoundation + 544845) [0x7fffb31fe04d] 1-4
                      4  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9 (CoreFoundation + 802153) [0x7fffb323cd69] 1-4
                        4  _dispatch_main_queue_callback_4CF + 925 (libdispatch.dylib + 60076) [0x7fffc8f00aac] 1-4
                          4  _dispatch_client_callout + 8 (libdispatch.dylib + 6396) [0x7fffc8ef38fc] 1-4
                            4  _dispatch_call_block_and_release + 12 (libdispatch.dylib + 42276) [0x7fffc8efc524] 1-4
                              4  __20+[BTTTouch mt_stop:]_block_invoke + 1345 (BetterTouchTool + 406869) [0x10a419555] 1-4
                                4  MTDeviceStop + 240 (MultitouchSupport + 12254) [0x7fffc326ffde] 1-4
                                  4  usleep + 54 (libsystem_c.dylib + 526950) [0x7fffc8fdea66] 1-4
                                    4  __semwait_signal + 10 (libsystem_kernel.dylib + 106310) [0x7fffc9057f46] 1-4
                                     *4  semaphore_wait_continue + 0 (kernel + 1107152) [0xffffff800030e4d0] 1-4

  Thread 0x1c79b1           Thread name "com.apple.NSEventThread"               4 samples (1-4)           priority 46 (base 46)
  <thread QoS user interacti
.....

Thanks!

fregatte

**Comment by fregattegit** [comment]
Problem solved; uninstalled btt; rebooted; installed; rebooted; working.

Finally an easy fix.

Thanks!

**Comment by fifafu** [comment]
Maybe something was in a strange state after updating. I'm closing here for now, if it happens again please let me know.
