### ISSUE TITLE
Tip Tap occurs twice 

### ISSUE THREAD

**Issue by diiiv9** [fifafu/BetterTouchTool#837]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Tip Taps are triggered twice , this wasn't happening earlier , but happen frequently now . Force/Click Tip Tap doesn't have this problem . 

Also can add window specific shortcuts ? Like if two XCode Projects are open , I want a different shortcut to be triggered for different project for the same trackpad gesture . Do you know anyway to achieve this ?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad . 

#### Device information:

Type of Mac: Macbook 2015
macOS version: Mac Sierra
BetterTouchTool version: Latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Which BetterTouchTool version are you using? (Unfortunately latest doesn't help, because there are various update channels)

Currently it's not possible to have window specific shortcuts, but this will be added soon.

**Comment by diiiv9** [comment]
BetterTouchTool Version 2.071

So if I have a left tip tap  to  close a safari or xcode tab , two are closed in quick succession . So I use click/force click tip tap now . 


Thanks , The window specific was solved with appleScript .

**Comment by fifafu** [comment]
Could you check whether the issue still exists in the most current alpha version (v2.095)? You can get it by clicking the "Check for alpha version updates" menu item

**Comment by diiiv9** [comment]
Feels perfect . No problems in this version . 

Thanks .

**Comment by diiiv9** [comment]
Hi Andreas , 

I am having the same problem with Triple Tap . When I triple tap , it executes twice , Its not application specific , Its happening in Safari and Xcode .

**Comment by fifafu** [comment]
Which version are you using currently?

**Comment by diiiv9** [comment]
Apologies !

I wasn't on the latest version , I have updated it now . However I assumed I would be since "Enable Automatic Update Checking" is enabled , as well as Alpha version so I assumed ...


I was on 2.15 .  I'll get back to you if I have any problems with the current version (2.17) with alpha updates .

Thanks !

**Comment by diiiv9** [comment]
Hi Andreas , 

I feel I may be pestering , but thats a testament to how much BTT is part of my workflow ...

My Three finger taps are missing the first few times that I tap them . This is across various apps  . After its recoginized once , it work everytime after that . I didn't have this issue before . I have restart BTT and macOS . 

I am on the latest alpha build ( I checked ! ) .

Great App !

Thanks .
