### ISSUE TITLE
[Feature Request] Touchbar Applescript Widget: Only run on-click

### ISSUE THREAD

**Issue by bestbrian** [fifafu/BetterTouchTool#838]
For the TB widget "Run Apple Script and Show Return Value", it is set to execute script every "x" seconds from 0 to 100. I would like for it to **only run the script when I tap the button**.

Initially I thought that setting the value to 0 would do what I just requested but it doesn't, at least not for me. When I set it to anything under 0, it still executes every 5 seconds. 

The goal of my script was to make a TB button change from play icon to pause icon depending on whether something was playing. I used this script: https://gist.github.com/Oblongmana/5479296 minus the "on run, end run" parts because that didn't allow the script to run. I may be wrong with this because I don't have much knowledge with scripts. 

Thanks for all your hard work!

Type of Mac: Macbook Pro 2016 with TB
macOS version: 10.12.2
BetterTouchTool version: 2.094

**Comment by fifafu** [comment]
With the new alpha you can use the Apple Script widget, but leave the script box empty. Then assign the predefined action "run apple script (enter directly as test)".

Now every time the button is pressed it will execute that predefined action and deliver the result to the widget.

I may need to add some improvements, but basically this should work

**Comment by bestbrian** [comment]
Thanks for your suggestion, it worked!!

**Comment by mnordsletten** [comment]
This worked for me as well, but it would make more sense if setting the value to 0 made the script only run when the button was pressed.

**Comment by pauloruberto** [comment]
@fifafu, this no longer seems to be working for me on the 10.13 GM (17A362a). The AppleScript is still called when I press the button, but it seems that the return value is not being passed to the AppleScript widget.

**Comment by fifafu** [comment]
@pauloruberto seems to work fine here, but maybe your Apple Script doesn't work correctly anymore. You can verify that the BTT action still functions properly by using a script like this:

```
return "test"
```

**Comment by pauloruberto** [comment]
@fifafu, even when having: `return "test"` as the "run apple script (enter directly as text)" action, it is still not being recognized as the return value in the widget. The script I am using is:
```
tell application "iTunes"
	playpause
	if player state is paused then
		return "paused"
	else
		return "playing"
	end if
end tell
```
It will successfully play/pause iTunes, so I know that the script is still running correctly.

**Comment by fifafu** [comment]
Ahh, sorry the Touch Bar widget currently only supports "Run Apple Script **in background** (enter directly as text)"

**Comment by fifafu** [comment]
Ah, but it also does internall just redirect it to the other one, so this shouldn't be the issue.

**Comment by pauloruberto** [comment]
Yeah, same thing is happening with running it in the background 👎

**Comment by fifafu** [comment]
Here is one that's working fine here: (you should be able to select it, copy it and paste it in your BTT)

```
 {
                          "BTTWidgetName" : "Test",
                          "BTTTriggerType" : 639,
                          "BTTTriggerTypeDescription" : "Apple Script Widget",
                          "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
                          "BTTPredefinedActionType" : 195,
                          "BTTPredefinedActionName" : "Run Apple Script in background (enter directly as text)",
                          "BTTInlineAppleScript" : "tell application \"iTunes\"\r\tplaypause\r\tif player state is paused then\r\t\treturn \"paused\"\r\telse\r\t\treturn \"playing\"\r\tend if\rend tell",
                          "BTTEnabled" : 1,
                          "BTTOrder" : 0,
                          "BTTTriggerConfig" : {
                              "BTTTouchBarItemPadding" : 0,
                              "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
                              "BTTTouchBarButtonColor" : "58.650001, 58.650001, 58.650001, 255.000000",
                              "BTTTouchBarAlwaysShowButton" : "0",
                              "BTTTouchBarAppleScriptString" : "tell application \"iTunes\"\r\tplaypause\r\tif player state is paused then\r\t\treturn \"paused\"\r\telse\r\t\treturn \"playing\"\r\tend if\rend tell",
                              "BTTTouchBarAlternateBackgroundColor" : "109.650002, 109.650002, 109.650002, 255.000000",
                              "BTTTouchBarScriptUpdateInterval" : 5
                          }
                      }
```

**Comment by pauloruberto** [comment]
Wait, I figured it out, it was my fault! I attached it as an addition action instead of setting it as the action for the actual widget. Thanks for taking the time to try and help me haha

**Comment by fifafu** [comment]
perfect! glad we could solve it :-)
