### ISSUE TITLE
"BTT Version Expired" message

### ISSUE THREAD

**Issue by P-Champagne** [fifafu/BetterTouchTool#839]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Getting this message and unable to use BetterTouchTool.
" BTT Version Expired
This version of BetterTouchTool is no longer
supported. Gestures etc. will no loger work.

Please update to most current version.

For more information please visit
https://..."
Option: "Quit BTT" or "Check For Updates"
<img width="427" alt="capture d ecran 2017-04-26 a 16 09 54" src="https://cloud.githubusercontent.com/assets/28067374/25455235/0b009996-2a9d-11e7-8065-ad3db7340369.png">

When I check for update I get:
"You're up-to-date!
BetterTouchTool 2.08 is currently the newest version
available"
<img width="428" alt="capture d ecran 2017-04-26 a 16 10 16" src="https://cloud.githubusercontent.com/assets/28067374/25455232/0470e86a-2a9d-11e7-9e05-ead72552a913.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All BetterTouchTool gestures on mouse don't work anymore.

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: macOS Sierra 10.12.4
BetterTouchTool version: 2.08 (610)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by pierce27** [comment]
@P-Champagne I was having same issue. Click on the menu icon and select Check For Alpha version and install latest. After that my BTT started working again

**Comment by fifafu** [comment]
Hey,

Were you using the trial version? Or do you have a license installed?

Best 
Andreas

**Comment by trwrt** [comment]
I'm having the same issue and I'm still on the trial version of 2.08, if that helps.  2015 MacBook 12" on Sierra.

**Comment by vaiomouse8** [comment]
I have the exact same issue to the letter. I also have the "no multitouch capable trackpad found" error. Im on a MBP and it was working fine this morning. Restarting the app and the computer haven't helped. 

I am on the trial version rn but I did buy BTT previously (new computer). Just haven't had time to look up my info with college finals next week...

<img width="1015" alt="screen shot 2017-04-26 at 6 11 03 pm" src="https://cloud.githubusercontent.com/assets/28072629/25460986/09104dac-2aac-11e7-9bb5-c1c0234ae5f5.png">
<img width="518" alt="screen shot 2017-04-26 at 6 13 41 pm" src="https://cloud.githubusercontent.com/assets/28072629/25460999/1c75bc4c-2aac-11e7-8b77-ff735ab90277.png">

**Comment by vaiomouse8** [comment]
pierce27's advice worked, don't know why the auto update said it was up to date if it was not. Why would I think to update if it said "you're up to date" lol 

LOVE THIS SOFTWARE!!! 20 mins w/o it and I was freaking out. 
I'm just going to buy an additional new license bc I love it that much and its super valuable to me. 
Thanks Andreas!

**Comment by rodalpho** [comment]
I wouldn't suggest going to the alpha unless you have no other choice, it's still pretty buggy. Also note that you can't revert back to 2.08 once you go to the alpha as the configuration file format changed-- so be sure to backup your settings first!

**Comment by fifafu** [comment]
@rodalpho, please report any bug you encounter, the alpha is already pretty stable and installed on many machines without critical bug reports yet. It will be released next week with some minor fixes to the import/export mechanism.

Also you cnan always go back because BTT keeps the previous configuration file.

**Comment by scottb908** [comment]
had the same issue, upgrading to alpha fixed it

**Comment by rodalpho** [comment]
@fifafu When I tried it a couple weeks ago it corrupted my configuration and the automatically created backup file was somehow overwritten. Good to hear it's more stable now, but I'll be waiting on the release. :)

**Comment by P-Champagne** [comment]
@fifafu : Yes I'm on the trial version. I that what causing the problem?

**Comment by fifafu** [comment]
@P-Champagne, yes was a little oversight on my part. Updating to the alpha should do for now.

I'm closing here, more info here: https://www.boastr.net/trial-version-expired-early/

**Comment by svititom** [comment]
Same problem just happened for me, On trial version 12 days left
OSX 10.12.6
BTT 2.313 (691)

**Comment by StaverDmitry** [comment]
Hi! Having the same trouble, updating to the alpha version didn't help.
Symptoms are the same: update message, no update (except for alpha version) available and the `no multitouch capable trackpad found` message. 
v 2.3.16 trial about 40 days left
mbp 2017 high sierra

**Comment by StaverDmitry** [comment]
Update: just wanted to reinstall it and it showed me an update message immediately, works fine after update, thanks :) Really enjoy using you app, going to buy a license soon, keep up the good work 👍

**Comment by svititom** [comment]
Update: new update available which fixed it. Thanks @fifafu
