### ISSUE TITLE
Terminal commands not executes

### ISSUE THREAD

**Issue by HenrikEckermann** [fifafu/BetterTouchTool#840]
If I use the 'Execute Terminal Command', the shortcut does not work. No terminal command gets executed. What could be the mistake I make? If I open a new terminal window manually and type 'open Downloads' or 'jupyter qtconsole', this works but if I use the created BTT shortcut...

**Comment by insanityfarm** [comment]
My guess is that you've got a couple different things going on here...

The command `open Downloads` is referencing a path that's relative to your current working directory. When you open Terminal you are probably in your user's home directory. But when BTT executes your command it's running from a different context. It may work if you use an absolute path like `open /Users/YourUserName/Downloads`.

As for `jupyter qtconsole` I'm guessing you modified your bash profile to add the location of the `jupyter` binary to your $PATH, at some point. Or maybe the binary is located in your home directory? Either way, I suspect the BTT execution context doesn't know about it. Again, you may have more luck if you use an absolute path: `/usr/local/bin/or/whatever/the/path/is/jupyter qtconsole`

**Comment by HenrikEckermann** [comment]
Thank you insanityfarm. That worked out!
