### ISSUE TITLE
Minus button below application list doesn't work.

### ISSUE THREAD

**Issue by ErikMinekus** [fifafu/BetterTouchTool#842]
#### Description of bug/feature request/question:
Selecting an application from the list and clicking the - button doesn't do anything.

#### Device information:

Type of Mac: MacBook Pro 15" w/ Touch Bar
macOS version: 10.12.4
BetterTouchTool version: 2.094

**Comment by fifafu** [comment]
Hey,

thanks for reporting! Will be fixed with next update tomorrow.

Best,
Andreas
