### ISSUE TITLE
How do I move the soft esc key?

### ISSUE THREAD

**Issue by erights** [fifafu/BetterTouchTool#845]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

How do I move the soft esc key?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.4
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I keep hitting the soft esc key accidentally. Googling, I found
https://discussions.apple.com/thread/7762774?start=0&tstart=0
where one of the answers said they used BetterTouchTool to move it as they show at
https://discussions.apple.com/servlet/JiveServlet/downloadImage/2-31376442-810093/1200-900/IMG_0966.jpg
So I downloaded and installed just for this purpose. But I cannot figure it out.

How do I use BetterTouchTool to move the soft esc key, or even to remove it?
Thanks.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by asyd** [comment]
Any update? I'm really interest by moving the `esc` touch too, or at least disable "padding" of the key on the left

**Comment by zabbaskeema** [comment]
Same here!  There is a way to keep it to the LEFT or add padding to the RIGHT.  We want the exact opposite!!  Add padding to the LEFT of ESC.

**Comment by fifafu** [comment]
Due to Apple API restrictions it is only possible to hide the esc key if you also hide the macOS Control Strip in the general BetterTouchTool touchbar settings.
