### ISSUE TITLE
4 Tap don't work anymore. Other (1,2,3,5) works great.

### ISSUE THREAD

**Issue by mrbodich** [fifafu/BetterTouchTool#846]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

4 Tap don't work anymore. Other (1,2,3,5) works great.

#### Device information:

Type of Mac:
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Seems to work fine here, what action did you assign?
Could you try upgrading to the current alpha version? (Maybe it's already fixed)

**Comment by mrbodich** [comment]
Hi. Updated to alpha. It works now, thanks!
