### ISSUE TITLE
Can't delete specific application that i just add

### ISSUE THREAD

**Issue by mukeymonster** [fifafu/BetterTouchTool#848]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I just add specific app but accidentally wrong one and want to delete it.
i try push the " - " button but nothing happen.
I even try the bettertouchtool menu > delete selection but still nothing happen
Help 

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

the app that i want to delete is parallels desktop
<img width="1015" alt="screen shot 2560-04-29 at 7 55 28 pm" src="https://cloud.githubusercontent.com/assets/28192024/25555645/4c8c1c16-2d16-11e7-8e47-a8629b1f5d08.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks a lot for reporting. This will be fixed with the next update tomorrow!

**Comment by mukeymonster** [comment]
where can i download the update ?

**Comment by fifafu** [comment]
Via the integrated auto updater. (After it's released)
