### ISSUE TITLE
Preset switching bug

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#849]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
In Default preset, define touchbar button with action to switch preset to master preset=Test.  Then when that touchbar button is pressed, the touchbar is blank (except for Esc).  Only way to get nonblank TB is to define the action to switch preset to Default with Test as additional, but then that results in a TB with all the buttons in Default and Test. I want to just show the buttons in Test.  Either this is a but or I need to know how to display just the Test preset's buttons.  Before the recent change in the preset infrastructure, what I had worked fine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
touchbar

#### Device information:

Type of Mac: 2016 MBPro 13"
macOS version: 10.12.4
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If I understood correctly you just need to add a button to the "Test" preset which will switch back to the default preset.

New buttons/triggers/gestures etc. are always added to the master preset. Thus to achieve this, select Test as Master, then add a button and assign the action to switch back to the default preset..

I'll work on the naming and the UI of the new preset functionality.

**Comment by CappyD** [comment]
Thanks Andreas. Yes, I have a button to switch back to the default preset. And that works fine. But is it correct that if I want to replace the default touchbar with one defined in a preset that I would define a button with Master=Test and no additional presets selected?  That seems like what the UI intends. Then I would have a button, as you suggested, defined with Master=Default (and no additional presets) to switch back?  I actually had essentially this set up a long time ago before you added Groups.  And without an Open Group action (which I suggested in another open issue), this preset method is still better because it allows switching directly from one group of buttons to another without having to jump back to the Default set in between.
--Dave
