### ISSUE TITLE
Shift + Mouse Move?

### ISSUE THREAD

**Issue by MLModel** [fifafu/BetterTouchTool#85]
#### Where is shift + mouse move set?

[MacBook Pro; MacBook Trackad, Magic Mouse, Magic Trackpad; OS X 11.6]

A couple of weeks ago I set something somewhere so that as I move the cursor with the mouse or trackpad when a certain modifier key is down the window the cursor is over moves following the cursor.  I can't at all figure out which of my many utilities does this. Well, maybe I can — if I disable BTT it doesn't happen anymore; when I reenable BTT it does. Where would I find such a setting? It doesn't even fit into BTT‘s scheme of things, so I can't imagine where it would be.

If not BTT, would someone else know where this intriguing feature is found?

**Comment by fifafu** [comment]
Hi,

yes this may very well be BTT, have a look at the attached screenshot:
<img width="1127" alt="screenshot_2016-12-12 23 31 54_divtwo" src="https://cloud.githubusercontent.com/assets/8820811/21119529/4b47868e-c0c3-11e6-960d-3ef503ec8048.png">
