### ISSUE TITLE
Need Open Group action

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#850]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
We need an Open Group action (matching the Close Group action) so that you can define a button to switch directly from an open group to another group if desired.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: 2016 MBPro 13"
macOS version: 10.12.4
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by JayPalm** [comment]
This would be super useful. For example, tapping the "Now Playing" AppleScript widget could open a play/pause/fast-forward/rewind group.

**Comment by unknowdata** [comment]
I wish this could happen soon. I'm using a lot of custom AppleScript widgets. So when I press on of the button it will then show the group. Ex. Pressing on today's weather will show full weekly forecast in the group.

**Comment by fifafu** [comment]
I have added such a action to the latest alpha (2.301)
