### ISSUE TITLE
How can I customise location for Screenshots? (p.s. your email link on github is 404)

### ISSUE THREAD

**Issue by laughingboy9000** [fifafu/BetterTouchTool#852]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cleverjackal** [comment]
Well, double click the action and then you'll find a ton of options there.

**Comment by laughingboy9000** [comment]
Not sure what you mean - my screenshot is assigned to a four-finger click and then i drag and click to take my shot - it stores these shots in my pictures folder - i would like to change that folder

**Comment by fifafu** [comment]
use BetterTouchTool's configurable screenshot predefined action. It gives you many options including the save path:

![image](https://cloud.githubusercontent.com/assets/8820811/25628932/2ecdc2d4-2f68-11e7-9aa4-d7c0fe826265.png)

**Comment by laughingboy9000** [comment]
cheers
