### ISSUE TITLE
[Major annoyance] Profile gets deleted when name is set to nothing

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#853]
#### Description of bug/feature request/question:

Basically, if you rename your BTT profile to nothing and then press enter, _it gets deleted._ Luckily I had made a recent backup to test a bug I was facing, so I am able to restore it without much trouble. This is, however, a major annoyance/bug which can easily wipe your profile if you don't make backups of it.

#### Device information:

Type of Mac: MacBook Pro
macOS version: 12.4
BetterTouchTool version: 614

**Comment by fifafu** [comment]
Hey,

thanks for reporting!
However as the upcoming new version (including the current alpha) have a completely new preset system, this won't be an issue anymore. (The name of the preset is not important anymore)

Best,
Andreas

**Comment by cleverjackal** [comment]
Awesome, thanks
