### ISSUE TITLE
Volume Slider Touch Bar widget buttons do not display HUD

### ISSUE THREAD

**Issue by dndrsn** [fifafu/BetterTouchTool#855]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The Touch Bar volume slider widget buttons do not display the volume change HUD.  For comparison, the brightness slider buttons do, as do standard buttons that perform the volume up/down/mute actions.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 15" MBP
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately I don't know of any way that would make the HUD appear. I could build my own HUD, but I think it'd be too much work to get right. Thus I'm closing here.

**Comment by dndrsn** [comment]
Ok.  Thanks.  I guess I'll try to fake it by hiding the buttons and using the default button types on each side of the sliders.
