### ISSUE TITLE
Exporting presets to JSON strips inline AppleScripts

### ISSUE THREAD

**Issue by targumanu** [fifafu/BetterTouchTool#858]
#### Description of bug/feature request/question:

When exporting presets to the new JSON format, all inline AppleScripts (in `Run Apple Script (enter directly as text)` actions) get stripped.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Any

#### Device information:

Type of Mac: iMac 21.5-inch, Late 2012 (13.1)
macOS version: macOS Sierra 10.12.5 Beta (16F67a)
BetterTouchTool version: 2.094 (620)

**Comment by fifafu** [comment]
Thanks for reporting, this will be fixed in an update later today!

**Comment by fifafu** [comment]
New alpha is now available
