### ISSUE TITLE
Swipe between pages in Safari doesn't work sometimes

### ISSUE THREAD

**Issue by targumanu** [fifafu/BetterTouchTool#860]
#### Description of bug/feature request/question:

Sometimes, swiping with two fingers to go back/forward in Safari stops working. A page starts sliding and partially reveals the previous page, but then gets stuck and wouldn't slide all the way. Some sites (e.g., Google and GitHub) seem to be more prone to this bug than others.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2

#### Device information:

Type of Mac: iMac 21.5-inch, Late 2012 (13.1)
macOS version: macOS Sierra 10.12.5 Beta (16F67a)
BetterTouchTool version: 2.094 (620)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This bug is usually fixed by restarting BTT.

**Comment by fifafu** [comment]
see #859
