### ISSUE TITLE
Single clicks are not detected sometimes

### ISSUE THREAD

**Issue by targumanu** [fifafu/BetterTouchTool#861]
#### Description of bug/feature request/question:

After introducing `1 Finger Tap Left/Right Side Middle`, system default single clicks sometimes do not work and require a second click to be detected.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2

#### Device information:

Type of Mac: iMac 21.5-inch, Late 2012 (13.1)
macOS version: macOS Sierra 10.12.5 Beta (16F67a)
BetterTouchTool version: 2.094 (620)

**Comment by fifafu** [comment]
If you use the side taps BTT has to disable that area for normal clicks (otherwise the taps would always trigger a click in addition to the action you choose).

**Comment by targumanu** [comment]
I do use side taps in some apps. However, single clicks are ignored in all apps. I tried to resolve this by assigning `Use Apple Default Or Do Nothing` action to side taps in the Global settings, but apparently this doesn't help.

**Comment by fifafu** [comment]
That's a good point. I'll check if I can limit the blocking to specific apps!

**Comment by Murgatroyd314** [comment]
I've been having a similar issue intermittently for the last few days (possibly starting when I upgraded Sierra to 10.12.4, though I'm not certain of that). I get haptic feedback from the trackpad, but the click doesn't seem to do anything. Thumb clicks seem more likely to be ignored than finger clicks. I do not have any side tap actions set up. I tried disabling BTT today, and haven't noticed any unregistered clicks since.

Touchbar MBP, Sierra 10.12.4, BTT 2.11 (630) and whatever the version before the latest upgrade was.

**Comment by digitalself** [comment]
This has become a critical issue for me - BTT is essentially unusable at the moment as it stops my Magic Mouse clicks from registering 50% of the time. 

On Sierra 10.12.5, 2013 MBPr, BTT version 2.11

**Comment by mikejcooper** [comment]
## **My current fix:** 

1. Download previous version v2.05: [v2.05 Mountail Lion](https://bettertouchtool.net/releases/btt2.05_final_10_9.zip)
2. Link to old backup (auto generated by BTT): /Users/$USER/Library/Application\ Support/BetterTouchTool/bttdata2.oldVersionBackup*.rar

**Comment by fifafu** [comment]
If this is still happening to you, please update to alpha version 2.17,  then if it happens again try to reproduce it as often as possible. Then open the BetterTouchTool preferences and go to the about tab, click the "export debug information" button.

This will create a folder "BetterTouchToolDebug" on your desktop. It would be great if you could send me the contents to boastr.net@gmail.com.

Best
Andreas

**Comment by soysauce365** [comment]
Agree with Mike Cooper's post. I have had to resort back to version 2.05 and so far the single clicks have been recognized more consistently again.

**Comment by Murgatroyd314** [comment]
Since updating to the alpha version, I have not noticed any failed clicks.

**Comment by planetsizebrain** [comment]
After upgrading to 2.19 (which I had to download manually, because the automatic install couldn't correctly unpack) I haven't noticed the clicking issue in the 1st hour after installing.

**Comment by planetsizebrain** [comment]
After half a day everything still seems to work OK and I haven't noticed any problems clicking yet.

**Comment by petersyden** [comment]
Issue persist with mbp touchbar :(

**Comment by fifafu** [comment]
@petersyden please follow the instructions above, then I'll be able to diagnose the problem!
