### ISSUE TITLE
Maximised Left or Right is only 20% of screen

### ISSUE THREAD

**Issue by jamonntoast** [fifafu/BetterTouchTool#866]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I've used BetterSnapTool and using the maximised left or maximised right command - will show the Current screen maximised either left or right side of the window.

When I try it with the current version 2.071 using keyboard commands, it shows the panel at 1/5 of the screen vertically. This is for both left and right.

The maximised top and bottom works which takes over 50% at the top or 50% at the bottom

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Only tried with keyboard command as don't use the rest.

#### Device information:

Type of Mac: 15" 2016 touchbar
macOS version: 10.12.3
BetterTouchTool version:  2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
http://bit.ly/2pSqhpj

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Did you maybe accidentally change the advanced window snapping options? See screenshot:
![image](https://cloud.githubusercontent.com/assets/8820811/25629114/d1f2423c-2f68-11e7-9903-87f187f41e6e.png)

**Comment by jamonntoast** [comment]
Thanks fifafu - Removed the configuration has suggested and it snapped to 25% instead of 20%.

I hence deleted BetterSnap + BetterTouchTool and did a clean install. All default settings; added each keyboard short cut. Switched off Windows Snapping feature as well - it now works. All I've configured to date are keyboard shortcuts as haven't had time to play with other features.
Thanks again.
