### ISSUE TITLE
2 Finger Swipe Left/Right hardly ever register

### ISSUE THREAD

**Issue by istrasci** [fifafu/BetterTouchTool#869]
#### Description of bug/feature request/question:
Recently my 2 Finger Swipe Left/Right seem to not be registering hardly at all.  I turn on **Show Live View** to check, and it is not picking them up most of the time (picks up 3 and 4 Finger swipes just fine).  I've tried several Apple Magic Mice to test it, so it seems it's not a problem with the hardware.

(Side note: **Show Live View** has a weird vertical black line in it)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse v1 and v2

#### Device information:
Type of Mac: MBP (2013?)
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Screen recording of my **Show Live View**:  https://youtu.be/gEyLpUG5jtY

**Comment by istrasci** [comment]
Yes, the black line remains if I disconnect the Magic Mouse, or even if I close BTT and reopen it.

I will reboot my machine (although I'm sure I have since I noticed the problem), and pending that, I'll try to reinstall BTT.

**Comment by fifafu** [comment]
That could mean that the black line is somehow coming from the macbook trackpad (which could interfere with the two finger swipes if it produces false input).

Has your trackpad been working correctly lately?

**Comment by istrasci** [comment]
OK, rebooting seems to have helped.  The gestures are working properly and the black line is gone (not sure if the trackpad is working properly; I always use my MBP in a docked mode with external keyboard, mouse, and monitors).

So, not sure what happened.  Apologies that I didn't reboot before posting the issue.  I thought I had, but I guess not.

**Comment by fifafu** [comment]
Interesting. Is the MBP lid closed in docked mode? If this happens again, please try opening the lid and check whether that fixes the issue.

**Comment by istrasci** [comment]
No, lid is always open, as I use the screen as an additional monitor.
