### ISSUE TITLE
Advanced mouse spped settings issue

### ISSUE THREAD

**Issue by donnie-darko** [fifafu/BetterTouchTool#87]
#### Description of your bug/question/feature request...:
Despite I set the mouse speed the highest level it doesn't seems like faster. On the login page it's feels faster than after I logged in and BTT loaded properly. I use BTT on a multi-account system. 

**What kind of Mac are you using?**
Mac mini Late 2012

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Magic Mouse 1

**Which version of macOS are you running?**
macOS Sierra 10.12.1

**Comment by fifafu** [comment]
Unfortunately Apple has limited the ability to set higher values than in system preferences with macOS Sierra. I haven't found a workaround for that yet, but will continue looking into it.

**Comment by donnie-darko** [comment]
one additional note: the highest setting is feels like faster with Magic Mouse 2 than with Magic Mouse 1. Is it possible?
