### ISSUE TITLE
3 Finger swipe not working with any apps on 10.12.3 (16D30) - MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

### ISSUE THREAD

**Issue by plainspace** [fifafu/BetterTouchTool#870]
#### Description of bug/feature request/question:
3 Finger swipe (all swipes) not working with any apps on 10.12.3 (16D30) - MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
macOS version: 10.12.3 (16D30)
BetterTouchTool version: 2.095

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Turned off all 3 finger swipes in System Prefs

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This should work fine. What actions have you assigned to the gestures?

**Comment by plainspace** [comment]
It's works fine on my older 15" fwiw. option-command left arrow or right arrow to emulate switching tabs in things like Chrome.

**Comment by fifafu** [comment]
@plainspace could you check whether this is fixed in the new alpha v2.096?

**Comment by plainspace** [comment]
Just tried and it still doesn't work.

**Comment by fifafu** [comment]
Thanks for testing!
Are you sure this is a BTT issue? Does pressing those shortcuts in Chrome work for you?

Could you try to assign a different action to see whether the gesture is recognized correctly? (e.g. assign the mission control action)

**Comment by plainspace** [comment]
Fixed it! Somehow changing the gesture and changing it back made it work!
