### ISSUE TITLE
BTT gestures stop working after 5-10 mins. Restarting BTT from the menubar fixes the gestures for 5 mins, then stops again

### ISSUE THREAD

**Issue by gro0** [fifafu/BetterTouchTool#871]
---

#### Description of bug/feature request/question:

BTT was working fine till version 1.9, while I was trying the application out in the 45 day trial period after I updated to version 2.02 I think, I started having these problems.

What happens is BTT's gestures stop working after 5-10-15 mins, and the only fix is restarting the application from the BTT's menubar. This seems to fix the issue for a few minutes, but then it stops working again, I tried googling to see if this was a common problem but did not find anything.

I then tried to reinstall the first version of BTT that worked well for me, that is 1.9, but got an error message that this is not the latest version and that BTT will now exit.

This is my first MacBook Pro, and while deleting BTT 2.094 via the app- AppCleaner, I stumbled across some log files, and googling the error got me to github, so I have made an account to try and get to the bottom of this. I do not know if this was the correct course of action. I am not very familiar with MacOS or Git

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Mid 2012 (9,2), trackpad

#### Device information:

Type of Mac: MacBook Pro 13 non retina mid 2012.

macOS version: 10.11.6
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[BetterTouchTool_2017-05-03-001736_MacBook-Pro.pdf](https://github.com/fifafu/BetterTouchTool/files/972551/BetterTouchTool_2017-05-03-001736_MacBook-Pro.pdf)
[BetterTouchTool_2017-05-03-063245_MacBook-Pro.pdf](https://github.com/fifafu/BetterTouchTool/files/972554/BetterTouchTool_2017-05-03-063245_MacBook-Pro.pdf)
[BetterTouchTool_2017-05-03-003919_MacBook-Pro.pdf](https://github.com/fifafu/BetterTouchTool/files/972552/BetterTouchTool_2017-05-03-003919_MacBook-Pro.pdf)
[BetterTouchTool_2017-05-03-085103_MacBook-Pro.pdf](https://github.com/fifafu/BetterTouchTool/files/972553/BetterTouchTool_2017-05-03-085103_MacBook-Pro.pdf)
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird. Do you have a valid license installed now?

**Comment by gro0** [comment]
This issue started when I auto update it from version 1.9.something that I had downloaded from they site directly to 2.02 (not sure, I think), while the trail period was going on. 
The issues started then, so I uninstalled the updated version, and tried to install the 1.9 .DMG that I had, but I couldn't downgrade, got the error that this is not the latest version, and that the app will not exit. 

So I downloaded the latest version again from the site and that said my trail had expired, and the app was exiting, when I should have had 10-15 days of trail left.


So I thought of confirming if this issue was in the pro version as well, since I couldn't install a trail and see if it was fixed, I went to a site and installed a cracked version (just to test before buying the app, I have no intention of using a pirated copy, and stealing money from the devs).  No, I don't have a valid license installed.

**Comment by fifafu** [comment]
That's what I  thought.
The issue is caused by the bad crack.

**Comment by gro0** [comment]
This started happening on the trial version first, when I hadn't thought of installing a cracked version.

**Comment by fifafu** [comment]
You can purchase a license, download a fresh copy from my website and then contact me via boastr.net@gmail.com in case you still run into issues. There is a 30day period where you can return your license.

**Comment by fifafu** [comment]
I saw the comments on Macbed and that you obviously lied here. 
Quite an effort you go through in order to save a few dollars eh?

**Comment by gro0** [comment]
I did say I was using a cracked version didn't I?

It's not a few dollars, the exchange rate puts it around 800 bucks, quite a bit of money for a student.

Nevertheless, I apologise for wasting your time.
