### ISSUE TITLE
Problem when switching keymap

### ISSUE THREAD

**Issue by obeone** [fifafu/BetterTouchTool#873]
#### Description of bug/feature request/question:

I'm using two (very) differents keymaps everyday : QWERTY and BÉPO. When I register a shortcut action, I think BTT save keycode and not directly the keys pressed. So when I register a shortcut like cmd + alt + R with qwerty, it become cmd + alt + L when I switch to my bépo keymap…

Is there any solution ?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

At least Touch Bar

#### Device information:

Type of Mac: MacBook Pro 13" 2016 with TouchBar
macOS version: 10.12.4
BetterTouchTool version: 2.095

**Comment by fifafu** [comment]
Hi, 

Sorry, there is no solution for that use case. You could create multiple presets, one for each layout.
