### ISSUE TITLE
Snap Areas gone! (2.10)

### ISSUE THREAD

**Issue by mrdampsquid** [fifafu/BetterTouchTool#878]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Window snap areas have disappeared.  Though they seem to be in the JSON export!  Re-importing the JSON didn't fix the problem.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mouse

#### Device information:

Type of Mac: MacBook Pro 2015
macOS version: 10.12.4
BetterTouchTool version: 2.10

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cesalazar** [comment]
Same problem. Can't get back my snap areas.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Trackpad

**Device information:**
Type of Mac: MacBook Pro 13-inch, Mid 2012
macOS version: 10.11.6
BetterTouchTool version: 2.10

**Comment by fifafu** [comment]
That's interesting, the snap area migration seems to work fine on my machines - maybe I forgot to migrate a specific display parameter or similar.

It would be great if you could open the BetterTouchTool preferences and go to the About tab. Then press the export debug info button.  This will create a folder "BetterTouchToolDebug" on your Desktop, if possible please send the contents of that folder to me (boastr.net@gmail.com).


![image](https://cloud.githubusercontent.com/assets/8820811/25734862/421e317e-3167-11e7-8ea6-973d55e126e7.png)

**Comment by fifafu** [comment]
Hey,

could you check whether this version brings back your snap-areas?  https://bettertouchtool.net/releases/btt2.101.zip

I'm not yet exactly sure whats causing them to not being shown, but I have some ideas.

**Comment by mrdampsquid** [comment]
Hi

Well, first I thought ‘but, I have already recreated them..’  then I looked, the recreated ones had now gone too!  So I used 2.101, this did not bring back the snap areas.  I have no created two more.  What I have not found, is what triggers them to disappear… :-/

Bob

**Comment by mrdampsquid** [comment]
by the way, if you want to see/control  my machine remotely we can do this via Webex anytime.  I have an account.
Cheers
Bob

**Comment by fifafu** [comment]
@Bob, thanks for the offer, but probably that won't help a lot (I can't really debug the code on your machine)
One thing to note: snap areas are dependent on the display and even on the display resolution - if the resolution changes the areas will not be shown anymore.

I have made some more changes in https://bettertouchtool.net/releases/btt2.10d.zip, however I'm still not sure whether they'll fix the issue as I still can't reproduce it here :-(
Also that would require to trigger the migration process again (which will delete all changes you have made since updating to 2.10)

If you want to try that, download the version above, then quit BTT and run these terminal commands:

```
defaults write com.hegenberg.BetterTouchTool BTTMigratedToSQLLite NO; mkdir ~/Library/Application\ Support/BetterTouchTool/backups/;  mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2* ~/Library/Application\ Support/BetterTouchTool/backups/
```
