### ISSUE TITLE
tiptap is very hard to trigger in chrome 

### ISSUE THREAD

**Issue by derek-zhang** [fifafu/BetterTouchTool#882]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I used 'TipTap Left(1 Finger Fix)' as 'switch to next tab' in Chrome with BTT v1.86 very well.
However with the latest version BTT, I found it's very very hard to trigger a TipTap.

Please Help !

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac:  Mac air
macOS version:  10.11.5
BetterTouchTool version:  2.10(626)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Try to increase the allowed distance between the fingers:
![image](https://cloud.githubusercontent.com/assets/8820811/25771118/b06a0f40-3248-11e7-9dab-70a1f7f664bb.png)

**Comment by derek-zhang** [comment]
Thanks!
works !
