### ISSUE TITLE
Update to V2.10 (the update posted on 5/5/2017 resulted in lost of all the snap areas I had mapped.

### ISSUE THREAD

**Issue by roamingbob** [fifafu/BetterTouchTool#883]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by roamingbob** [comment]
I just did the update to V2.10 (the update posted on 5/5/2017.  Unfortunately it did not capture all my snap areas that I had carefully created under the prior versions.  I assume these are lost for me, but wanted to let you know of the bug.

**Comment by fifafu** [comment]
Hey,

Sorry for the issues. I'm already looking into that.
The are definitely not lost - you can either downgrade to the previous version (v2.071 https://boastr.net/releases) or wait for the next update!

**Comment by roamingbob** [comment]
Thanks!  I’ll try that.

**Comment by fifafu** [comment]
Could you try whether this version works for you: https://bettertouchtool.net/releases/btt2.101.zip?

**Comment by dvanoni** [comment]
@fifafu I encountered this issue as well. I tried downloading the version you posted here, but I run into issue #901 as I did with v2.11.

**Comment by roamingbob** [comment]
The latest update V2.12 has the same problems.  My snap areas are still lost upon the update.  I had to roll back all the way to V2.071 to get them to function again.  I'll either repeat the roll back to that version again, or recreate them under the new version.  
Is there any bullet proof way to save the snapping area preferences?  Have I missed something?  
- Bob

**Comment by fifafu** [comment]
@roamingbob unfortunately I haven't been able to figure out what's wrong yet - the snap areas are still there, but for some reason not being shown.

Could you try if triggering the migration process again changes anything? (This will however remove the changes you made  since upgrading to 2.1x, it will move them to a backup folder).
This terminal (while BTT is quit) will cause the migration process to start again:
```
defaults write com.hegenberg.BetterTouchTool BTTMigratedToSQLLite NO; mkdir ~/Library/Application\ Support/BetterTouchTool/backups/; mv ~/Library/Application\ Support/BetterTouchTool/btt_data_store.v2* ~/Library/Application\ Support/BetterTouchTool/backups/
```
