### ISSUE TITLE
Key Sequence won't work with the "Key UP" option

### ISSUE THREAD

**Issue by enigma2k** [fifafu/BetterTouchTool#885]
#### Description of bug
There is a bug using Key Sequence: When I create a Key Sequence using a key e.g. the left shift key and select "Key UP" the sequence won't work. So when I press on shift and lift my finger, nothing is triggered. The key sequence only works if I don't select "Modifier Up" but then it already triggers when I press the key which is not what I want.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Keyboard

#### Device information:
Type of Mac: Mac Mini
macOS version: 10.12.4
BetterTouchTool version: 2.10

**Comment by fifafu** [comment]
Maybe try to increase the max allowed time to pass between (or after) keystrokes:
![image](https://cloud.githubusercontent.com/assets/8820811/25771126/00d9a328-3249-11e7-9d53-c4c76d606c46.png)


In general this seems to be working fine here

**Comment by enigma2k** [comment]
Thank you Andreas, this fixed my problem!  I think I have also tried this in the past a few months ago and it didn't work. Is this something you've recently fixed?

**Comment by fifafu** [comment]
@enigma2k yes, it's possible that there has been a fix lately!
