### ISSUE TITLE
Four finger swipe right/left is only recognised if done too explicitly

### ISSUE THREAD

**Issue by Grolubao** [fifafu/BetterTouchTool#89]
Macbook Pro 2016 TB

Mac OS Sierra 10.12.1

I'm using a Four finger swipe to switch between tabs in Chrome. In order to register the swipe right left I need to do it very explicitly, meaning the sensitivity is quite low. I changed the sensitivity and it's still the same issue.

**Comment by bstasse** [comment]
I guess it is the same problem I encounter with the three finger swipe gestures. I created an issue for this here: https://github.com/fifafu/BetterTouchTool/issues/50

**Comment by fifafu** [comment]
Latest alpha has a slider in the advanced settings to configure the sensitivity.
