### ISSUE TITLE
Preset export omits negative padding values

### ISSUE THREAD

**Issue by RichardTsc** [fifafu/BetterTouchTool#890]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I am working on a Touch Bar configuration for MS PowerPoint where I need a very condensed collection of buttons which I realised with negative paddings (e.g., -10px). 
<img width="1085" alt="ctrl - coloring" src="https://cloud.githubusercontent.com/assets/6375308/25767218/b91520b8-31f7-11e7-8217-e2322cfd5a9d.png">

But when I export these presets, the negative padding values are just omitted (they do not appear in the .json file), so when I import the presets again, the padding is back to 0. That way, I can't share these presets with my colleagues.

PS: With manually adding them to the json-file, the import works just find. So its an issue during the export. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 2.10

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting, I didn't think about negative values :-)
Will allow them with the next update.
For now only solution is to edit the json manually.

**Comment by RichardTsc** [comment]
Great! Just saw, that copy & paste inside BTT also omits these negative values

**Comment by fifafu** [comment]
Yep that uses the same code! Will also be fixed :-)

**Comment by RichardTsc** [comment]
Works great now! Trying to convince my company to buy corporate licenses for our Mac users (~30). Such a great tool - keep it up!
