### ISSUE TITLE
"Move mouse to coordinate" feature failure

### ISSUE THREAD

**Issue by inugi15** [fifafu/BetterTouchTool#893]
#### Description of bug/feature request/question:
Sometimes "Move mouse to coordinate" feature doesn't work after lastest update (2.10).

#### Device information:
Type of Mac: Macbook pro
macOS version: 10.11.6
BetterTouchTool version: 2.10 lastest.

**Comment by fifafu** [comment]
I don't think there has been a change to that action, what gesture or shortcut are you using to trigger it?

**Comment by inugi15** [comment]
Oh, I'm sorry to bother you. I figure it out.
I combined 2 actions "move mouse to coordinate" and "left click" 
but it runs at the same time and ignore one action sometimes in this 2.10 version.
So I just put the delay action between them.
