### ISSUE TITLE
`Trigger on key down` forcing `Repeat action while shortcut is pressed`

### ISSUE THREAD

**Issue by sdrygalski** [fifafu/BetterTouchTool#895]
#### Description of bug/feature request/question:

When `Trigger on key down` is selected in shortcut configuration, shortcut will be repeated with max speed after pressing. Doesn't matter if we turn off/on `Repeat action while shortcut is pressed` or change values in this option. 

(bug appeared after updating from 2.08 to 2.10).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MackBook Pro Keyboard

#### Device information:

Type of Mac: MacBook Pro (Retina, 15, mid 2015 r.)
macOS version: 10.11.5 (15F34)
BetterTouchTool version: 2.10

**Comment by sdrygalski** [comment]
For now I downgraded to 2.08 and it helped.

**Comment by fifafu** [comment]
Weird, this seems to work fine for me.
Could you try to press cmd+c on one of the shortcuts that shows this bad behavior and paste it here? (You'll need v2.10 for this)

I just tried it with this:
```
{
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : 198,
  "BTTPredefinedActionName" : "Volume Up (Small Step)",
  "BTTRepeatRate" : 0.1748502604166667,
  "BTTRepeatDelay" : 0.2147569444444444,
  "BTTTriggerOnDown" : 1,
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 31,
  "BTTShortcutModifierKeys" : 1835008,
  "BTTOrder" : 2
}
```

**Comment by sdrygalski** [comment]
```
{
  "BTTGestureNotes" : "center mouse",
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : 153,
  "BTTPredefinedActionName" : "Move Mouse To Position",
  "BTTMoveMouseToPosition" : "{755.29998779296875, 400.95999145507812}",
  "BTTMoveMouseRelative" : "0",
  "BTTTriggerOnDown" : 1,
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 34,
  "BTTShortcutModifierKeys" : 1966080,
  "BTTOrder" : 45,
  "BTTTriggerConfig" : {
    "BTTHUDDetailText" : "Center mouse",
    "BTTShowHUD" : 1
  }
}
```

And when I keep pressing shortcut for this I keep seeing HUD that constantly show up. Another shortcut is alias for Cmd-H - and when I press it, I will practically hide all my apps instantly. Like it was repeating itself really fast.

All shortcuts that will do something when repeated are now repeating very fast. Whatever options I choose (repeat or not). Only way to fix it is to turn off `Trigger on key down`. Or downgrade. ;)

**Comment by fifafu** [comment]
Ah! Thanks, I can reproduce it. I'll issue a little update later today and will include a fix for this.

**Comment by sdrygalski** [comment]
It works now, great!
