### ISSUE TITLE
BUG: TouchBar running all applescripts every time i switch applications?

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#896]
Hi Andreas,

i am experiencing a strange bug: I have set up several applescripts widgets in my touchbar, mostly for curling some urls and returing the results. Whenever i switch applications (cmd+tab or dock etc.) BTT refreshes all the widgets although they are set up to refresh only every 5 minutes.

as you can imagine this causes a lot of load since you switch aplications every x seconds while working on the mac (which is about 10hours per day for me)

can you reproduce this with the current 2.10 version? if theres anything you want me to to to support here, let me know! thanks!

**Comment by fifafu** [comment]
Hey,

are you switching between different "Display States" of the Touch Bar? (e.g. with control strip hidden, control strip visible, BTT bar hidden)?

In that case BTT refreshes the scripts, however this should have been the case for all versions since quite a while

**Comment by fantaaaaaa** [comment]
I dont use groups, neither switch any states. i have had some keyboard shortcuts for "close current touchbar group" so i could force refreshes previously, but i have removed them all..

**Comment by fifafu** [comment]
Could you check whether this has changed with v2.11? (just released)

**Comment by fantaaaaaa** [comment]
https://www.dropbox.com/s/u91u6ie337gm0l1/Screenshot%202017-05-07%2010.16.38.png?dl=0
https://www.dropbox.com/s/1qflrm01kp69z9k/Screenshot%202017-05-07%2010.17.40.png?dl=0

BTT does not show the update.

**Comment by fifafu** [comment]
Ah sorry, due to the "inbetween" version you are currently using, you'll need to update manually: https://boastr.net/releases/btt2.11b.zip

**Comment by fantaaaaaa** [comment]
yup, fixed it. no more visible refreshes of the applescript widgets.
