### ISSUE TITLE
BUG: AppleScript Widget repeated execution crashes BTT

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#897]
Hi Andreas,

i am using the latest 2.10 version and running some apple script widgets. While the script for checking and returning value works properly, actually pushing a button and running a script will fail (nothing is executed) and doing this 2-3 times in a row will crash BTT. here are my settings and my scriprt:

https://www.dropbox.com/s/sdruq51c4k40qdc/Screenshot%202017-05-06%2015.11.35.png?dl=0

```
property baseURL : "http://rvg4jqcyhoe5asck.myfritz.net:8099/zuhause/assets/php/homekitHandler.php?device=SCHLAFZIMMER_LAUTSPRECHER&action=2"
set ergebnis to "emtpy"

try
	set ergebnis to do shell script "curl --max-time 3 '" & baseURL & "'"
end try

return ergebnis
```

funny enough, "Run Script" in the edit window works properly but when i save and push the actual button, it will crash...

the script has been working for months now, i have just added the max-time parameter but even without it, it still crashes. i have also tried running the script with the regular command and with the optinal "run script in background" feature.

would be nice if you could help out, currently the buttons are unusable.

**Comment by fifafu** [comment]
Weird, running scripts seems to work fine here. (I just triggered your script :-D did it start playing?)

Could you maybe try to restart your Mac? BTT doesn't handle anything of this, it just tells the system to execute the script, maybe something got into some sort of weird state.

**Comment by fantaaaaaa** [comment]
I've found that it happens because of the attached additional action "close currently open touch bar group" which has been there for some months now without any problems...

**Comment by fifafu** [comment]
That also seems to work fine here:

```
{
  "BTTTouchBarButtonName" : "TestGroup",
  "BTTTriggerType" : 630,
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTEnabled" : 1,
  "BTTOrder" : 1,
  "BTTAdditionalActions" : [
    {
      "BTTWidgetWidth" : "Example",
      "BTTTriggerType" : 639,
      "BTTTriggerTypeDescription" : "Apple Script Widget",
      "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
      "BTTPredefinedActionType" : 172,
      "BTTPredefinedActionName" : "Run Apple Script (enter directly as text)",
      "BTTInlineAppleScript" : "return \"From Manual Press\"",
      "BTTEnabled" : 1,
      "BTTOrder" : 0,
      "BTTAdditionalActions" : [
        {
          "BTTTriggerType" : -1,
          "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
          "BTTPredefinedActionType" : 191,
          "BTTPredefinedActionName" : "Close currently open Touch Bar group",
          "BTTEnabled" : 1,
          "BTTOrder" : 17
        }
      ],
      "BTTTriggerConfig" : {
        "BTTTouchBarItemPadding" : 20,
        "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
        "BTTTouchBarButtonColor" : "213.562500, 58.650001, 58.650001, 255.000000",
        "BTTTouchBarAlwaysShowButton" : "0",
        "BTTTouchBarAppleScriptString" : "return \"Fom timed execution\"",
        "BTTTouchBarColorRegex" : "Manual",
        "BTTTouchBarAlternateBackgroundColor" : "109.650002, 109.650002, 253.569894, 255.000000",
        "BTTTouchBarScriptUpdateInterval" : 5
      }
    },
    {
      "BTTTouchBarButtonName" : "Close Group",
      "BTTTriggerType" : 629,
      "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
      "BTTPredefinedActionType" : 191,
      "BTTPredefinedActionName" : "Close currently open Touch Bar group",
      "BTTEnabled" : 1,
      "BTTOrder" : 1,
      "BTTIconData" : "Standard Close Icon",
      "BTTTriggerConfig" : {
        "BTTTouchBarButtonColor" : "0.000000, 0.000000, 0.000000, 255.000000",
        "BTTTouchBarOnlyShowIcon" : 1
      }
    }
  ]
}
```

**Comment by fifafu** [comment]
Ah wait - I think I was just able to reproduce a crash! Looking into it :-)

**Comment by fantaaaaaa** [comment]
thank god, i was starting to doubt my abilites to maintain a working set of settings in BTT :)

**Comment by fifafu** [comment]
Could you check whether this version fixes this? https://bettertouchtool.net/releases/btt2.101c.zip

**Comment by fantaaaaaa** [comment]
yep, still crashed as soon as closing the group is added.

**Comment by fifafu** [comment]
Ok, it seems to be working here now: https://bettertouchtool.net/releases/btt2.102.zip

**Comment by fantaaaaaa** [comment]
nope, still crashes. i assume it has something to do with the script rerunning after press or something similar? i was able to remove the "close currently open touchbar group" to refresh the button (as you showed me in the other ticket) so i have removed them all again. but when i add that as additional action, it will keep crashing:

my current setup again:

https://www.dropbox.com/s/da9clkt66f7533j/Screenshot%202017-05-06%2016.59.41.png?dl=0

https://www.dropbox.com/s/7mn4kvocx88if3u/Screenshot%202017-05-06%2016.59.58.png?dl=0

https://www.dropbox.com/s/l9gg4h186ju1207/Screenshot%202017-05-06%2017.00.13.png?dl=0

**Comment by fifafu** [comment]
Could you select the group and press cmd+c and then paste the output here via cmd+v? (or in case it contains private data send it to boastr.net@gmail.com)

Are you sure you are running v2.102 now?

**Comment by fantaaaaaa** [comment]
whoops, seems like replacing the app did not work out properly. now its fine and the bug is gone, thanks!
