### ISSUE TITLE
Shortcuts crash BTT within specific app, since 2.10

### ISSUE THREAD

**Issue by gbr04** [fifafu/BetterTouchTool#898]
#### Description of bug/feature request/question:
Any keyboard shortcut triggered when the [RuneScape NXT client](https://www.runescape.com/download) is in focus crashes BTT. This only occurs since 2.10, and it doesn't matter whether the shortcut is global or specific to this application.

I haven't tried any other input device types but they might also be affected.

For example, having → as a shortcut for `Left Click`, or triggering any key press like `;`.
I have tried restarting, full BTT reset etc but the issue still occurs.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MBP, Late 2013
macOS version: 10.12.3
BetterTouchTool version: 2.10 (627)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid predicate: nil RHS'
```

[Full crash report](https://gist.github.com/gbr04/a7dd68fef79ecb81b592274d3f83f207)

**Comment by fifafu** [comment]
Thanks for reporting, your crash report helped me identify the issue.
I'll release a little update later today!
