### ISSUE TITLE
5 finger click not getting recognised

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#9]
BTT verse 1.96 not recognising 5 finger clicks on the 15" MPB. It is working fine on BTT version 1.952. 
Even on the "live view", resting 5 fingers only registers 4 fingers. Maybe this is an issue with the palm recognition.

**Comment by fifafu** [comment]
Thank you! Will be fixed in 1.61 later today!

**Comment by fifafu** [comment]
Should be fixed now with 1.961. Will close for now. If it still happens, please comment again.
