### ISSUE TITLE
Activate window when mouse is over

### ISSUE THREAD

**Issue by rodolphb** [fifafu/BetterTouchTool#90]
Hi,

Is there an option that allow to activate a window when the mouse cursor is over it ?

I would like to write text more quickly on different windows.

Thanks.

**Comment by pallavmac** [comment]
That is such an awesome idea! Would this be possible to implement?

**Comment by fifafu** [comment]
In theory it would be possible, but it's quite complicated to get right (performance & usability).

I'm sorry, but I currently don't plan to add such a feature to BTT.
