### ISSUE TITLE
Corner Tap - Delay 

### ISSUE THREAD

**Issue by Vandaze** [fifafu/BetterTouchTool#900]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hey,

I'm using the corner taps to adjust volume and brightness of the screen. Until today I was able to tap multiple times in a row and it changed fast from 0 bars volume to maximum bars. 

Starting today there is a big delay of around 0.5-1sec after each tap before it increases volume/brightness again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: Macbook Air 2013
macOS version: 10.12.3
BetterTouchTool version:  2.11

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Atair1** [comment]
same here - corner tap for volume, since a few days the delay is present..

**Comment by GJRobert** [comment]
Same here, same as @Atair1 said.

Type of Mac: Macbook Air 2013
macOS version: 10.11.6
BetterTouchTool version: 2.11 (630)

**Comment by Vichulee** [comment]
Same here but more serious.
I use corner tap for highlight in reading. It's worked very well in the previous version but now I need to take my chance and do it again and again.

Type of Mac: Macbook Pro 2015'15
macOS version: 10.12.4
BetterTouchTool version: 2.12

**Comment by herbs** [comment]
I wonder if this is related to my problem too. I have Tap = Left Click along the bottom of my Magic 
Trackpad 2. I used to be able to do two quick taps in a row and get a Double Click. Starting with BTT 1.95 and continuing through 2.12 I need a much longer delay between Taps for it to get detected as a Double Click.

Type of Mac: 21" iMac 2011
macOS version: 10.12.4/5
BTT version: 2.12

**Comment by tonynguyen1901** [comment]
I have the same problem too! Anyone found the solution?

**Comment by fifafu** [comment]
This should be fixed in the new alpha (v2.14, get via "Check for Alpha Version Updates")

**Comment by herbs** [comment]
> On May 25, 2017, at 10:49 AM, Andreas Hegenberg <notifications@github.com> wrote:
> 
> This should be fixed in the new alpha (v2.14, get via "Check for Alpha Version Updates")
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howdy,

This also seems to fix the problem I was having with setting Tap=Left Click not registering a Double Tap as a Double Click without a long delay between taps.

Thanks!

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by GJRobert** [comment]
Thanks for the fix!!! Love your work!
