### ISSUE TITLE
Bug: Deleting group leaves nested items 

### ISSUE THREAD

**Issue by scottb908** [fifafu/BetterTouchTool#903]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
if you have a nested group, inside another nested group  then delete the top nest item it does not delete the entire tree.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: Macbook pro
macOS version: 10.14.4
BetterTouchTool version: 2.18.626

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![example](https://cloud.githubusercontent.com/assets/12705830/25777297/3cf7b206-32a7-11e7-9080-602a2b27c349.jpg)

In the screenshot, if I delete the top nested group called criticals, the item for MSN.com would still be present, but all other items would get deleted.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
sorry, nesting is currently not supported officially ( I know there is this workaround by dragging a group into another group - this shouldn't be possible but I'll leave it because I know some users are doing it ;-)).

This will at some point be fixed if I add official support for nesting groups.
