### ISSUE TITLE
Feature request - open finder to a specific folder

### ISSUE THREAD

**Issue by scottb908** [fifafu/BetterTouchTool#904]
Is there a way to have a touch bar button open finder to a specific folder? Maybe I am just being stupid and missing on how to do that.

**Comment by fifafu** [comment]
You can use the "Execute Terminal Command" and enter e.g. "open ~/Downloads"

**Comment by duongel** [comment]
what about opening Terminal's current directory in Finder? `open .` or ` open pwd` do not work.

**Comment by fifafu** [comment]
Something like this apple script:

```
tell application "Terminal"
	do script "open ." in front window
end tell
```

**Comment by duongel** [comment]
ah didn't think of that! Thank you, it worked :-)
