### ISSUE TITLE
"f" key not working once I installed BetterTouchTool

### ISSUE THREAD

**Issue by macbookprouser** [fifafu/BetterTouchTool#905]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I would love to get this application to work, and it does, but when I open it the "f" key doesn't type anymore. I have tried uninstalling, reinstalling, and restarting my macbook pro. It does work as a capital F, it that helps. Thank you. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Brand new Macbook Pro 2016 13" with TouchBar (literally bought it yesterday)

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

you have probably added the f key to the keyboard tab in the BTT Preferences.
Delete it and it should be fixed!

Best,
Andreas

**Comment by macbookprouser** [comment]
This fixed my problem! Thank you so much!
