### ISSUE TITLE
Crashing upon waking up my MBP from sleep

### ISSUE THREAD

**Issue by haynar** [fifafu/BetterTouchTool#907]
#### Description of bug/feature request/question:
I'm pretty sure it crashes, but I don't have any explicit evidence of crash (no crash reporting dialog or anything else except that the app is not running). I noticed that every time I close my mac at home and open it at the office I have to run BTT  as it's not running. I've noticed that behavior mainly from going from home to office because at home I don't use any external display, while at the office there are monitors connected, so I suppose it may be somehow related to connecting external monitors.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
So I think it happens when I connect the monitors (2xDELL U2414H via thunderbolt) to my MacBook Pro (Retina, 15-inch, Mid 2015). I haven't noticed any issues when disconnect the monitors so far. Maybe it happens but not so often, so I missed it.

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.10 / updated to 2.11 a couple of minutes ago, will report if the issue is fixed, however I've noticed the issue even before version 2.10

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Attached is the crash log I believe is logged upon the latest crash (approximately at the time I connected monitors to my mac)
[BetterTouchTool_2017-05-07-132443_Nareks-MacBook-Pro.crash.zip](https://github.com/fifafu/BetterTouchTool/files/981842/BetterTouchTool_2017-05-07-132443_Nareks-MacBook-Pro.crash.zip)

**Comment by fifafu** [comment]
This is the same crash as here: #831, unfortunately currently the only solution is to hide the BTT icon from the menubar (I still have no idea what could be causing this and even suspect it's an Apple bug)

I'm closing here as this issue is tracked in #831.

**Comment by haynar** [comment]
@fifafu ok, sorry for duplicate report.
