### ISSUE TITLE
Mac pinch gestures blocked if pinch set in BTT, even in combination with modifier key (old title: Mac zoom gestures won't work anymore if application added to BTT)

### ISSUE THREAD

**Issue by PhilippS1990** [fifafu/BetterTouchTool#909]
#### Description of bug/feature request/question:
I cannot use the (standard) pinch to zoom gesture in an application I have added to BTT.
This seems to be independent of any gesture added to this application.
I.e. when I want to zoom in Safari, Numbers or Preview and have the respective application in BTT, it doesn't work, also if there isn't any BTT gesture. If I "Disable BTT completely for '...'", the zoom gesture immediately works again. Gestures added by BTT aren't influenced by this, I can still change my Safari tabs with my 3 fingers swipe down gesture etc. Also, other app-specific gestures like rotate in Preview still work, it's only the zoom that doesn't.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: 13" MacBook Pro mid 2012 (A1278)
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.11

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
* I experienced some non-functional zoom gestures especially in Safari with earlier versions of BTT, but usually a simple restart of BTT would have fixed it
* The issue described above began during the last days; I'm not sure if it was there before 2.11
* I deleted the Better Touch Tool folder in my user Library and reproduced the issue without any  setting changed / gestures added (just added Safari and Numbers to the list)
* Restarting my Mac didn't work either.

Thanks a lot in advance! Also thanks for developing and maintaining BTT during the last years, I love it and it's one of my most favorite mac apps of all time, keep up the good work! :)

Best wishes,
Philipp
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you maybe have a pinch gesture somewhere in your setup? In that case BTT may block the standard pinch.

If possible please go to the About tab and click the "Export Debug Information" button. This will create a folder on your Destkop called "BetterTouchToolDebug". The contents could be helpful - if possible please send them to boastr.net@gmail.com

Best,
Andreas

**Comment by PhilippS1990** [comment]
Hey Andreas,

Thanks a lot for your quick reply and support! I started troubleshooting in deleting different gestures and investigating the effect on the pinch to zoom functionality in Safari. I pretty soon came to the conclusion that a "opt + Pinch In / out -> cmd -" gesture in "Global". So it seems like this gesture replaced the system pinch to zoom functionality even without the option key pressed.

So everything works perfect again as I don't need the global gesture anymore. I guess that I had it sitting there for a while - either I just noticed its effect recently or a recent update caused trouble with this.

Having found the issue, I guess there's no need anymore for the BetterTouchToolDebug, right? In case you need it anyway, please just drop a line. :)

Thanks again for your help! Keep up the good work, Grüße an die Heimat (München ;)) and best wishes,
Philipp

**Comment by bretello** [comment]
I'm having the same issue. Check your mail for the debug info

**Comment by fdiog** [comment]
Yeah, I have this too. 
In my case I have this global shortcut "fn + pinch in". Killing BTT process brings back pinch to zoom systemwide. So it's the same case.

**Comment by fifafu** [comment]
Ah I think there has really been a small change that causes this - currently as soon as the pinch gesture is used it will block all pinches.

I'll bring the old behavior back soon. If you need it now, please downgrade to v2.071 (https://boastr.net/releases )

**Comment by fifafu** [comment]
This will be fixed in alpha version v2.15 (which will be released in about an hour)
