### ISSUE TITLE
Undo action

### ISSUE THREAD

**Issue by Nxt3** [fifafu/BetterTouchTool#91]
A way to undo a change would be nice. For example, if I make a window maximized through a command, then I'd be able to return it to the state it was in before I maximized it.

**Comment by fifafu** [comment]
You can use the predefined action "restore old window size" to do that.

Best,
Andreas

**Comment by Nxt3** [comment]
This doesn't work then. I trigger the action "Start/Stop resizing" and then try to run the "Restore Old Window Size" action to no avail. Tested this with Google Chrome if that matters.

**Comment by fifafu** [comment]
Ah sorry this only works for discrete actions like "mwximize window".  I'll check if I can extend this to the continuous actions.

**Comment by Nxt3** [comment]
Has this been implemented? If not, I think this issue should be re-opened.

**Comment by fifafu** [comment]
Sorry, but for continuous resizing actions I won't be able to add a "undo" function.
The way this is integrated in BTT works only for the discrete resizing actions.

**Comment by Nxt3** [comment]
Bummer. Oh well. Thanks anyways!
