### ISSUE TITLE
Issue : Touchbar just keeps showing action name not result - solved

### ISSUE THREAD

**Issue by TheBartoMan** [fifafu/BetterTouchTool#912]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Updated today and having all sorts off issue. Its running badly and forever hanging and showing the spinning icon.

Instead of showing the results on the Touch Bar, i very often just the action name instead.

#### Device information:

Type of Mac: Macbook Pro 2016
macOS version: Latest
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by TheBartoMan** [comment]
Solved : This turned out to be due to an Applescript which was taking a long time to run, hence holding everything up.

Could it be worth implementing the ability for scripts to auto disable if they run over a selected amount of time. (Also the ability to manually disable some triggers manually?)

**Comment by fifafu** [comment]
There will be a way to run the scripts in the background soon, this will also allow to cancel them after a specific time.
