### ISSUE TITLE
Feature Request:  print directly from screen capture window

### ISSUE THREAD

**Issue by queryquandary** [fifafu/BetterTouchTool#917]
#### Description of bug/feature request/question:
It would be very handy to be able to print a screenshot directly from the window that opens after you do a screen capture using BTT.  Right now I have to copy to clipboard and then paste into Word and then print from there.  I do a lot of this.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can use the configurable screenshot action and on the bottom choose "After Capture" => "Open in Application".
![image](https://cloud.githubusercontent.com/assets/8820811/25872343/a5b3920a-350a-11e7-8757-f4e25a149814.png)

The application would be a custom automator workflow. To create one that prints a image do this:

1. Start Automator
2. Select Application as type
3. Add the "Print Images" action to the workflow.

![image](https://cloud.githubusercontent.com/assets/8820811/25872356/aa0e8e9a-350a-11e7-8b23-9ddae0a90c65.png)

**Comment by queryquandary** [comment]
Thanks, that worked great however I don't always want screen captures to go straight to the printer. 
To get around that I created an alternate screen capture action that sends the image to the printer.  Thanks for the quick reply!
