### ISSUE TITLE
Palm Rejection not working well

### ISSUE THREAD

**Issue by thewellington** [fifafu/BetterTouchTool#918]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Since v2.10 Thumb/Palm Handling is no longer enough to filter out occasional brushes aginst the trackpad on my 2016 15" MBP.  I currently have it on, 
along with Map Three Finger Clicks, and Map Four Finger Clicks.

Recently I turned on Also handle/filter thumbs resting...   but that has not solved the problem.  My palms touch this massive trackpad ever so slightly and that causes the cursor to skip off elsewhere or else not respond at all.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Trackpad - but NOT the external Magic Trackpad 2

#### Device information:

Type of Mac: 15" MacBook Pro (2016)
macOS version: 10.12.14
BetterTouchTool version 2.10: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Improved palm/thumb recognition will come with the next bigger update approximately end of may!

In case the previous palm rejection really worked better for you, you can load the previous version here: https://boastr.net/releases, for me the current one seems to work much better - but that depends probably a lot on how we touch the trackpads. In which area do most of your "accidental" touches happen?

**Comment by thewellington** [comment]
In the bottom right corner of the touchpad mostly

**Comment by kingds** [comment]
I'm also having this issue with the latest version, on a 2016 Macbook. I thought my trackpad was broken! Clicks don't register if my palm is touching the bottom right corner of the trackpad.

**Comment by fifafu** [comment]
Could you try to activate thumb/palm **filtering?**

![image](https://cloud.githubusercontent.com/assets/8820811/25921080/6c60bdc8-35d4-11e7-88d0-8945114178ab.png)

**Comment by thewellington** [comment]
Activating thumb/palm filtering solves the problem, but disables the five finger gestures that I have been using for years..   So sad.

**Comment by thewellington** [comment]
No problems before 2.10

**Comment by fifafu** [comment]
For now try downgrading to v2.071, if possible try the upcoming alpha versions as I'll be working on the thumb/palm recognition during the next few weeks.

**Comment by notsosuperman** [comment]
I am also having this issue, just noticed it today. For me, it is only happening when the palm is on the bottom right AND a bottom right corner click or force click gesture mapped. Disabling the bottom right corner clicks eliminates the problem for me. Hope that helps you track it down, and hopefully that is what others are experiencing as well. Thanks!

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu item). I have changed the palm/thumb recognition quite a bit, let's see if that helps

**Comment by thewellington** [comment]
I installed 2.15 yesterday.  The palm/thumb recognition on the 2016 MBP is much more better...  I likes.

**Comment by notsosuperman** [comment]
I installed 2.17 today and it did seem to fix the issue, however, the
corner clicks and corner FORCE clicks seem unreliable. Sometimes they
register, other times not. Sometimes they register with feedback, other
times they register but give no feedback. Thanks!

Gabe Proulx

On Fri, May 26, 2017 at 12:15 PM, W. S. Wellington <notifications@github.com

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. Please excuse not being able to solve/reply to this earlier.
