### ISSUE TITLE
3 finger double-tap doesn't work (with certain system gesture setting)

### ISSUE THREAD

**Issue by chadschan163** [fifafu/BetterTouchTool#919]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

3 finger double-tap doesn't work on my MacBook for months, including recent several versions of BTT.

I assigned 3 finger double-tap to keyboard shortcut "cmd + W" globally,  turns out it doesn't response, while other gestures works fine. It used to be fine few months ago.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro Retina  early 2015 13"
macOS version: 10.12.4
BetterTouchTool version: 2.11(630)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Maybe this helps: I turned on three finger drag in system preference accessibility. I turn it on all the time,  BTT used to get along well with it.

<img width="780" alt="screen shot 2017-05-10 at 11 06 43 am" src="https://cloud.githubusercontent.com/assets/23233331/25881982/aade6008-3572-11e7-997b-8212d4d2ada0.png">

UPDATE: BTT gets to work when that system function was turned off. but I really need that three finger drag system gesture.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by chadschan163** [comment]
UPDATE2: I found when three finger dragging is on, Touchpad preference Look up & data detectors setting to tap with three fingers makes BTT work, setting to Force click with one finger makes BTT no work (In my case, 3 finger double-tap gesture).

Please fix this~
<img width="780" alt="screen shot 2017-05-10 at 11 32 07 am" src="https://cloud.githubusercontent.com/assets/23233331/25882426/faddaa0c-3575-11e7-8a0d-530386febaf9.png">

**Comment by fifafu** [comment]
Sorry for not replying earlier.
Unfortunately BTT is not really compatible with three finger dragging as it changes various fundamental parameters of the trackpad. This probably won't change in the near future, thus I'm closing here :-(
