### ISSUE TITLE
Shift + Select 

### ISSUE THREAD

**Issue by dwbelliston** [fifafu/BetterTouchTool#92]
#### Description of your bug/question/feature request...:
Apps will not let me select many by using shift and selecting with mouse click. For example in Finder, I select Desktop and then hold shift. When I click on Download I want to select Desktop, Documents and Downloads but I get this popup. Not sure why this happens.

![image](https://cloud.githubusercontent.com/assets/11450118/21106369/1876ec36-c04b-11e6-86ab-fab187ed4fa2.png)

**What kind of Mac are you using?**
MacBook Pro (Retina, 15-inch, Mid 2014)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Trackpad.

**Which version of macOS are you running?**
Sierra 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

**Comment by fifafu** [comment]
Hey,

Thanks for reporting!
Is it possible that you have added leftclicks in the normal mouse tab in BetterTouchTool but not assigned a shortcut or modifier key to them?

If so, deleting them should fix the issue!

Best 
Andreas

**Comment by dwbelliston** [comment]
yep that was it. i thought i had checked all the gestures, but I did end up finding it this time. thanks.

sorry for creating an issue about it, but really appreciate the help.

**Comment by fifafu** [comment]
Yes, it's still an issue. I'll improve the message that is shown!
