### ISSUE TITLE
BetterTouchTool not recognizing media keys when not on actual F keys mode.

### ISSUE THREAD

**Issue by Rxywyn** [fifafu/BetterTouchTool#93]
Hi there,

am currently using a mid 2012 macbook pro, trying to configure BTT to set my volume media keys to fine-control volume keys (opt+shift+F11/F12), but however I configure them on the app, it does not appear to work if my function keys aren't being set as actual F keys from system preferences. I'm currently on macOS Sierra, 10.12.1. some users may note that I'm trying to replicate what I could in Karabiner, so it'll be great if this could fix my problem. Thanks in advance!

**Comment by fifafu** [comment]
Recording those keys is currently not possible. However for the next alpha I have added "Volume Up (Small Step)" and "Volume Down (Small Step)" actions.
