### ISSUE TITLE
Sorting trackpad gestures

### ISSUE THREAD

**Issue by dzeruel** [fifafu/BetterTouchTool#930]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of feature request:
Hello!

BTT is awesome, but recently I'm having hard time configuring my trackpad gestures because I have so many.
Would it be possible to sort those gestures by not only modifier keys but gesture names, comments, maybe date added?
Same question for any other configuration, keyboard, drawings etc. 

Thank you for your excellent app!
dz

#### Device information:

Type of Mac: MacBook Pro (Early 2015)
macOS version: 10.12.4
BetterTouchTool version: 2.11

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

Sorry no, this won't be added. However you can sort them yourself by dragging them around.

Sorting in BTT is complicated for various reasons and I currently can't invest time to implement it.
