### ISSUE TITLE
Everytime there's an update the app is removed from the login items

### ISSUE THREAD

**Issue by SnitramDev** [fifafu/BetterTouchTool#931]
#### Description of bug/feature request/question:

Everytime there's an update the app is removed from the login items

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.12.4
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

sorry for the delayed response!
Are you sure launch on startup is activated in the BTT Preferences? See this screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/26458884/e9398374-4174-11e7-9adb-58797ea22fb3.png)



Best,
Andreas

**Comment by SnitramDev** [comment]
Oh i didnt know about that. Thanks

A qui, 25/05/2017, 4:06 da tarde, Andreas Hegenberg <
notifications@github.com> escreveu:
