### ISSUE TITLE
BTT not responding after waking up from sleep

### ISSUE THREAD

**Issue by taiyangc** [fifafu/BetterTouchTool#939]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

BTT occasionally stops responding after waking up from sleep. I have to force quit from activity monitor. This happens probably 1/10 times.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Everything

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.11 (630)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Where could I find more logs or stacktraces when the app stops responding?

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu).

In general I'm tracking the issue here: #915 thus I'm closing here.
