### ISSUE TITLE
Corner Force Clicks Hit & Miss -- last 2 alphas

### ISSUE THREAD

**Issue by pauloruberto** [fifafu/BetterTouchTool#94]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Hey! Ever since the last two alphas, my rules for force touching the top corners of my trackpad have been pretty hit and miss in regards to actually firing. Sometimes they work, sometimes not so much.

**What kind of Mac are you using?**
13" TouchBar MacBook Pro
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which version of macOS are you running?**
10.12.2 beta

**Comment by fifafu** [comment]
Will be fixed in 1.966 in a few minutes.

**Comment by pauloruberto** [comment]
Perfect! Thanks.
