### ISSUE TITLE
BTT hangs after sleep? or just use for a long time.

### ISSUE THREAD

**Issue by andrew-luhring** [fifafu/BetterTouchTool#943]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Not entirely sure what causes it, but BTT hangs and I have to force quit it. It seems to happen after my computer goes to sleep for a while and then after I wake it up BTT doesn't work and hovering over the icon in the top...part (by the time and wifi stuff) shows a spinny ball of death. In order to fix it I have to force quit BTT via activity monitor.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Everything. It just freezes and won't work. Nothing else is affected but I can't use BTT.

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.12.4
BetterTouchTool version: 2.11

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

[Archive.zip](https://github.com/fifafu/BetterTouchTool/files/999556/Archive.zip)

**Comment by rickbatka** [comment]
I'm having the exact same issue. Most of the time when I wake from sleep, I find the gestures aren't working. When I hover over the BTT tray icon, I get the spinning ball. Have to force quit through activity monitor and restart BTT.

This just started happening in the last week or two. I've been using BTT for several years and this never happened; now it happens every time I wake the computer.

MacBook Pro (Retina, 15-inch, late 2013)
macOS 10.12.5 Beta (16F71b)
BTT version 2.12 (631)

Let me know if there's any way I can send helpful diagnostics. This is a great product that I can't live without and I'm happy to help!

**Comment by kdbertel** [comment]
I am also experiencing this, where after waking my computer up from sleep, BTT is "Not Responding" according to Activity Monitor, and moving my cursor over the icon shows a spinning beach ball.

MacBook Pro (Retina, 13-inch, Late 2013)
macOS 10.12.4 (16E195)
BTT 2.11 (630)

Oddly enough, I do not seem to experience this on my work laptop, which is one of the new Retina MacBooks Pro with TouchBar.

**Comment by pkernevez** [comment]
Hi all,

Same issue with my mac.
Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2013)
macOS version: 10.12.4
BetterTouchTool version: 2.11

**Comment by ccc7574** [comment]
Me too, when will this bug be fixed?

**Comment by vekkt0r** [comment]
Same issue for me.

macOS 10.12.4
MacBook Air (13-inch, Late 2010)
BetterTouchTool 2.11 (630)

**Comment by fifafu** [comment]
Thanks a lot for the samples! Would be great if you could test this version: https://bettertouchtool.net/releases/btt2.13.zip

I'm not yet entirely sure if this will fix the issue, but at least I now know the area I need to look at.

**Comment by teicherus** [comment]
That seems to have fixed it for me.

**Comment by anick08** [comment]
Same issue. 
Restarting BTT works, but its rather tedious to do so often.

**Comment by rickbatka** [comment]
Still happens for me with that new version. I'm looking in Console.app, but I don't see anything relevant to bettertouchtool. Is there a specific log you want? There are no crash reports when this happens, I guess because it is a hang, not a crash.

**Comment by madeagithubaccount4btt** [comment]
Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2012)
macOS version: 10.12.5
BetterTouchTool version: 2.12

Same issue, spinning pinwheel over mini app icon and it does not function. I also cannot force quit the application because it does not even show up in "force quit applications" window. Usually requires a computer restart or shutdown for me. I'm a noob, so if someone knows a quicker way to restart BTT w/o restarting the computer it would be much appreciated. Thanks

<img width="921" alt="1" src="https://cloud.githubusercontent.com/assets/28798946/26233716/2df59234-3c14-11e7-9682-67a593e1a70f.png">
<img width="920" alt="2" src="https://cloud.githubusercontent.com/assets/28798946/26233715/2df41882-3c14-11e7-880c-fb5873318a90.png">

**Comment by teicherus** [comment]
You could open the terminal and type in "killall BetterTouchTool".

**Comment by rsperl** [comment]
Having the same problem, and after using 2.13, I also got the spinning beachball. I killed it, restarted it, and it seems to be working again. I have not had time to put my mac to sleep and wake it up again to see if it's fixed the original issue.

**Comment by fifafu** [comment]
Sorry for not having a fix ready yet, I have been quite busy at work lately. This week we have a long weekend in Germany and I'll definitely try to fix the issue.

**Comment by fifafu** [comment]
I'll continue to track the issue here: #927
