### ISSUE TITLE
Not recognizing keyboard shortcut with SHIFT

### ISSUE THREAD

**Issue by jshrek** [fifafu/BetterTouchTool#946]
#### Description of bug/feature request/question:
If I assign these Global keyboard key sequences as follows, they works fine:
Right_Command_Key triggers Command_Key+Left_Arrow  (move to beginning of line)
Right_Option_Key triggers Command_Key+Right_Arrow  (move to end of line)

If I assign the following Global keyboard key sqeuences in addition to the ones above, these do not work, and the ones above are always triggered instead. The order does not matter, whether these are before or after the ones above:
Shift+Right_Command_Key triggers Shift+Command_Key+Left_Arrow (move to beginning of line and select all text)
Shift+Right_Option_Key triggers Shift+Command_Key+Right_Arrow  (move to end of line and select all text)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook keyboard and external keyboards

#### Device information:
Type of Mac: MacBook Pro (13-inch, late 2011)
macOS version: 10.12.4 Sierra
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
This bug has been noticeable to me for a couple of years, so for several previous versions of both Better Touch Tool and several previous versions of macOS.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In that case you have to add a "min pause before first keystroke" to your first key sequences. Like in this screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/26471353/a7c46332-41a1-11e7-8db9-48c32db1c7f9.png)
