### ISSUE TITLE
[Bug] Maximize window doesn't position window correctly on OS X 10.12.5.

### ISSUE THREAD

**Issue by ubnt-jeff-hansen** [fifafu/BetterTouchTool#949]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When I click and drag a window to the top of the screen (to maximize the window), it maximizes to the correct size, but it is off-center. I have my dock on the left side of my screen.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MBP 2016, when dragging any window to top of the screen that has my dock (on the left)

#### Device information:

Type of Mac: MBP 2015 Touch Bar
macOS version: 10.12.5
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

would be great if you could try to restart the system. Sometimes after such an update the system is somehow confused.

**Comment by ubnt-jeff-hansen** [comment]
Interesting, it's working fine again (didn't restart or anything). Anyway, I'll keep an eye on it. Thanks!
