### ISSUE TITLE
Ability to hold a key like 'D' and make it act as a modifier key for the trackpad

### ISSUE THREAD

**Issue by nikitavoloboev** [fifafu/BetterTouchTool#95]
#### Description of your bug/question/feature request...:
This is a really awesome idea I just had and would change the way I use my computer if it could be implemented. 

I have also [opened an issue](https://github.com/tekezo/Karabiner/issues/778) of this to [Karabiner](https://github.com/tekezo/Karabiner), perhaps it can be done from there as well. 

I am curious whether it would be something that would be possible to do? That is I press down some letter key like 'a' and it would then change the way the trackpad behaves, same as setting these modifier keys : 

![2016-12-12 at 19 45](https://cloud.githubusercontent.com/assets/6391776/21111820/9de175dc-c0a3-11e6-88ee-f9754960bbd1.png)

Thank you for any help.

**Comment by fifafu** [comment]
Mhh, I don't think that could be done in a useful way because it would also produce the character a? Or didn't I understand correctly?

**Comment by nikitavoloboev** [comment]
Well Karabiner has this notion of launcher mode and that is you can make your normal alphabet keys into modifier keys. I guess it is my bad to think that BetterTouchTool can do this as it requires something to be done on a more lower level, something that only Karabiner can do.

**Comment by fifafu** [comment]
But how does Karabiner do that? Do you first have to switch to that launcher mode?
(BetterTouchTool could do that also, but I'm not sure if it'd be useful to many)

**Comment by nikitavoloboev** [comment]
No it is an always on behaviour. Here is [more info on how I use it](https://github.com/nikitavoloboev/dotfiles/tree/master/karabiner). Essentially I press 'a' key and it doesn't send a signal to 'a' until I release it alone, if I hold 'a' and some other key, it makes a custom key binding of my own.

The problem with that though is that I don't know how I can make it be some kind of modifier key when pressed with the trackpad.
