### ISSUE TITLE
BTT on Mac hangs after sleep

### ISSUE THREAD

**Issue by jamiechong** [fifafu/BetterTouchTool#951]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I can't confirm that this is always the case, but it seems to happen after my Macbook wakes up from sleep. I hover over the BTT icon in the menu bar and the cursor is a SWOD. I have to open Activity Monitor to force quit the BTT process and restart. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro trackpad

#### Device information:

Type of Mac: Macbook Pro
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.12(631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Prophe-T** [comment]
+1 for this issue.

Description of bug/feature request/question:
I don't have BTT in the menubar, but realize my shortcuts don't work anymore. Opening BTT via launchpad doesn't work then. I have to kill the process via ActivityMonitor (it shows BTT isn't responding). I can relate to this: "I can't confirm that this is always the case, but it seems to happen after my Macbook wakes up from sleep."

Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro trackpad, normal mice

Device information:
Type of Mac: Macbook Pro
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.12(631)

No additional info

**Comment by DRevanGCR** [comment]
Same issue.

**Description of bug/feature request/question:**
Almost every time i wake up my mac BTT stops responding and the cursor turns into a Spinning Wheel of Death when hovering over the icon in the menu bar. I have to kill the process via Terminal (killall BetterTouchTool) or ActivityMonitor.
My BetterTouchTool version is 2.11, it says it's the newest one.

**Device information:**
Type of Mac: Macbook Air (mid 2012)
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.11 (630)

**Comment by fifafu** [comment]
Thanks for reporting, I'm tracking the issue here: #943  and will try to fix it this weekend. Closing herw.
