### ISSUE TITLE
Window Resizing - Allow all four corners

### ISSUE THREAD

**Issue by petfik** [fifafu/BetterTouchTool#952]
When resizing a window by mouse+modifier key the top left corner stays fixed and the bottom right corner is active.

I would love to be able to switch to a mode when the active corner is the one closest to the mouse pointer, i.e. use all four quadrants of any window (like in ubuntu).

**Comment by SteveJobzniak** [comment]
+1. I've seen apps that do this. It was a bit choppy because the resizing must move the window, then resize it, then move it, then resize it, over and over... But it makes up for it in coolness of being able to extend/shrink a window in a specific corner.

**Comment by fifafu** [comment]
Sorry, unfortunately I won't implement this.
It's very hacky and doesn't work well because of the API limitations @SteveJobzniak mentioned.+

I like the idea, but it's too much work and still won't work very well afterwards.

**Comment by SteveJobzniak** [comment]
@fifafu That is okay and understandable. :)

**Comment by petfik** [comment]
No problem, even the standard resizing is great. Thanks for the swift
response!

Dne 27. 5. 2017 10:00 napsal uživatel "SteveJobzniak" <
notifications@github.com>:
