### ISSUE TITLE
Keyboard shortcut - Menubar-Item generates an unexpected menu click

### ISSUE THREAD

**Issue by alottem** [fifafu/BetterTouchTool#953]
#### Description of bug/feature request/question:
When I define a TextEdit keyboard shortcut to trigger menubar items, it looks like BetterTouchTool sends an extra menu item click in addition to the expected click.

For example, these are keyboard shortcuts to switch TextEdit writing direction, to Right to Left, and Left to Right.

- First example: `(5);(2);(5);(4)`, Format -> Text -> Writing Direction -> Right to Left
- Second example: `(5);(2);(5);(3)`, Format -> Text -> Writing Direction -> Left to Right

The shortcuts work, but with following unexpected side-effects:
In first example, (5);(2);(5);(4), I get an extra, unexpected click on Format -> Prevent Editing
  this is **4th** element in Format menu

In second example, (5);(2);(5);(3), I get an extra, unexpected click on Format -> Make Plain Text
  this is **3rd** element in Format menu

It seems that BetterTouchTool mistakenly sends an extra click on the first menu hierarchy (Format in this example), position specified by last item in the menu hierarchy (4, 3 in the above examples).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:
Type of Mac: MacBook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.12

**Comment by fifafu** [comment]
That's weird, I'll look into it!

For now you can probably use the text based version, spelling out the menu items.

**Comment by alottem** [comment]
It doesn't work, I think because of the way this menu item is built: there
are multiple lines with same same.
Please see attached screen shot.
If you could provide a workaround for this, it would be great.  Thanks!

On Tue, May 16, 2017 at 9:41 AM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
The issue should now be fixed in v2.17 alpha. (Get via "Check for alpha version updates")

**Comment by alottem** [comment]
Confirmed, thanks.
