### ISSUE TITLE
Is it possible to move defined actions from one mac to another?

### ISSUE THREAD

**Issue by basseltx** [fifafu/BetterTouchTool#957]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
 TouchBar

#### Device information:

Type of Mac:  MacBook Pro late 2016 with TouchBar
macOS version: 10.12.4
BetterTouchTool version: 2.11(630)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi!

Sorry for the late response. I was quite busy at work during the last few weeks :.-(

Yes, this is possible. You can use the preset import/export options that appear after pressing the "Manage Presets" button.

![image](https://cloud.githubusercontent.com/assets/8820811/26445304/0b08c0d0-4140-11e7-8975-3a8eeb27f449.png)
