### ISSUE TITLE
Can't import old plist settings file into newer version of BTT

### ISSUE THREAD

**Issue by jshrek** [fifafu/BetterTouchTool#958]
#### Description of bug/feature request/question:
I have some older settings that were in the ~/Library/Preferences plist file and when I try to import it says they are not proper json format.

#### Device information:
Type of Mac: MacBook Pro 13 inch late 2011
macOS version: 10.12.4 Sierra
BetterTouchTool version: 2,12

**Comment by fifafu** [comment]
The plist doesn't contain any gestures, it's just for general settings.
However the plist format is still the same, so you can copy it back to the preferences folder while BTT is quit.

Only the files from ~/Library/Application Support/BetterTouchTool can be imported

**Comment by jshrek** [comment]
I reformatted hard drive and reinstalled OS and then downloaded and reinstalled BTT. If I want to find my old custom keyboard shortcuts and gestures (I have them saved on a time machine backup) what file(s) would I need to copy over?

Thanks

**Comment by fifafu** [comment]
Sorry for the delay.

You'd need to copy the folder ~/Library/Application Support/BetterTouchTool and the file ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist
