### ISSUE TITLE
Dragging bug on Sierra

### ISSUE THREAD

**Issue by cuzer** [fifafu/BetterTouchTool#96]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
While dragging a file/folder, the movement is jittery, it will lag and/or the item will be dropped by itself. It prevents me from using BTT, since it creates drag and drop accidents which makes me undo my actions all the time. Reproduction rate is 3/5.

**What kind of Mac are you using?**
MBP early 2011

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Mouse (universal)

**Which version of macOS are you running?**
Sierra 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Running on BTT v. 1.963 (552)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Does this still happen with more current versions of BTT?

**Comment by cuzer** [comment]
Hi,

Thanks for reaching out. It does not happen anymore. I'm thinking maybe it
was due to my own mouse.

Best regards,

Can Uzer
Sound designer
www.canuzer.com
LinkedIn <https://www.linkedin.com/in/cuzer/> | Twitter
<https://twitter.com/audiocan>

On Fri, Mar 24, 2017 at 6:11 PM, Andreas Hegenberg <notifications@github.com
