### ISSUE TITLE
[Bug] Experiencing a general error with latest BTT

### ISSUE THREAD

**Issue by d-edery** [fifafu/BetterTouchTool#961]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Every once in awhile I get a general "BetterTouchTool Error" dialog.
I'm using BetterTouchTool for years now and it's the first time something like this happens.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All configured BetterTouchTool peripherals are affected. No configuration works and I need to restart the application/open and close the preferences dialog.

#### Device information:

Type of Mac: MBPR 15 Mid 2014
macOS version: Sierra 10.12.1
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://cloud.githubusercontent.com/assets/10434994/26140748/1fc869d6-3ae1-11e7-9161-a2b629b30acc.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Try to download a fresh copy from my website. Seems like yours somehow got damaged.

Https://boastr.net/downloads
