### ISSUE TITLE
[Feature Request] Apple Watch support for BTT Remote

### ISSUE THREAD

**Issue by winterflags** [fifafu/BetterTouchTool#962]
I use AirPods paired with my Mac to play music from it while I'm not at the computer in my home. Unfortunately, Apple didn't provide a convenient way to adjust the volume of the Mac from the AirPods.

I use BTT Remote for iPhone to login to the Mac, and then adjust the volume using the iPhone's volume buttons. However, I seldom take my iPhone with me everywhere I go at home – but I do have an Apple Watch, and realized that it would be awesome with a BTT Remote app for WatchOS, whereby volume and other things (like shutdown etc) could be done via the Watch.

I realize that this is a quite narrow request and usage case, but then again, there are no Apple Watch apps that I know of today, which can control a Mac.

**Comment by fifafu** [comment]
Yes, a Watch App is on my TODO List. It probably won't come soon, but I hope sometime this summer.

**Comment by ithieund** [comment]
@fifafu ,
Great to hear that.

Thanks.

**Comment by fifafu** [comment]
Continue to track this here: #170
