### ISSUE TITLE
pasting (BTT)@clipboard(BTT) pastes some older clipboard content

### ISSUE THREAD

**Issue by murawskikrzysiek** [fifafu/BetterTouchTool#963]
#### Description of bug/feature request/question:
I have a shortcut that triggers a few commands. First of them is copying path to a file with cmd opt c and later on I use pasting with use of (BTT)@clipboard(BTT). It pastes something that was copied a few hours earlier.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Keyboard

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.12.3 (16D32)
BetterTouchTool version: 2.12

**Comment by fifafu** [comment]
Could you try to add a little delay after you trigger cmd+opt+c using the "Delay Next Action" predefined action? Maybe the system has not yet copied the path when the next action already triggers.

**Comment by murawskikrzysiek** [comment]
I tried doing this and it did not work unfortunately. 
Restarting BTT helped and since this is a macro that I rarely use I have not seen it anymore, but it seems like the clipboard was stuck on something


On 25 May 2017, at 11:45, Andreas Hegenberg <notifications@github.com> wrote:

Could you try to add a little delay after you trigger cmd+opt+c using the "Delay Next Action" predefined action? Maybe the system has not yet copied the path when the next action already triggers.

**Comment by fifafu** [comment]
If it happens again please reply here again. I'm closing for now but will keep an eye on this.
