### ISSUE TITLE
[Feature Request] Add this from BetterSnapTool to BetterTouchTool

### ISSUE THREAD

**Issue by MiRO92** [fifafu/BetterTouchTool#964]
Hey, I own both BetterSnapTool and BetterTouchTool but since snap areas are already in BetterTouchTool so i decided to uninstall BetterSnapTool but i miss this feature

can you please add it to BetterTouchTool?

<img width="672" alt="screen shot 2017-05-18 at 15 02 59" src="https://cloud.githubusercontent.com/assets/3205572/26201420/83c1d5bc-3bdb-11e7-9d9b-b6b8fdd665a1.png">

**Comment by fifafu** [comment]
This is already in BetterTouchTool, you can find the options in the "other" tab.

**Comment by fifafu** [comment]
This is already in BetterTouchTool, you can find the options in the "other" tab.

**Comment by MiRO92** [comment]
i'm aware of this but "Quit App" is not in predefined actions
