### ISSUE TITLE
Force Touch Trackpad Fail

### ISSUE THREAD

**Issue by tVVVt** [fifafu/BetterTouchTool#965]
#### Description of bug/feature request/question:

After upgrading BTT to 2.12 the Force Trackpad on my MBP15 is highly unusable. I basically have to click three or four times on anything to get the system to register the click and usually have to click very very hard. If I quit BTT the touchpad works normally. If I go to Preferences > Advanced Settings > Reset All Settings everything works normally for about 60 seconds and then the old problem returns. Never had any kind of issue with BTT until 2.12

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MBP 15 Late 2016
macOS version: 10.12.4
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by dimasyt** [comment]
Same problem for me!
My touchpad is unusable with this update.
Before this update this app helped me to be more productibe but after update it slow down all my workflows.

It will be great to know when developers gonna fix this problem.

**Comment by fifafu** [comment]
Are you touching the trackpad with more than one finger when that happens?

**Comment by dimasyt** [comment]
Even with one finger!
If I tap trackpad with one finger with btt running sometimes there no action or action happens after long delay. Without btt running everything working perfectly. It happened with last update.

**Comment by dimasyt** [comment]
Is it possible to downgrade version somehow?
Because version before this big upgrade worked perfectly on my mac. But after this upgrade it made my mac unusable.

**Comment by fifafu** [comment]
Yes, you can download previous versions here : https://boastr.net/releases

**Comment by dimasyt** [comment]
Awesome! Thank you. I will try version 2.10

**Comment by tVVVt** [comment]
It seems to be far worse with two fingers. I usually click with my thumb while moving the cursor with my index finger so usually have two fingers in the trackpad. Seems to be better with only my index finger

**Comment by dimasyt** [comment]
It seems to be that version 2.12 (631) is working fine on my computer.
But I still testing it.

Thank you for listening!

**Comment by mortenkleveland** [comment]
I got problems with some of the 3 finger gestures on v. 2.12 in Chrome (3 finger swipe down doesn't work at all, 3 finger click is only registering clicks occasionally) - reverted to 2.1 and all is ok. 

I am using a 2015 MBP with Force Touch with the latest macOS.

**Comment by dimasyt** [comment]
I still expecting some problems with 2.12 on my latest Macbook Pro. This problems not stable - sometimes toches working fine, sometimes - not.

Just downgraded again to 2.10. This version is stable for me.

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu). I have changed the palm/thumb recognition quite a bit, let's see if that helps

**Comment by dimasyt** [comment]
Sure! Thanks for listening. I will try. Everything was OK before latest updates. But! I am not sure, maybe it is not just fault of BTT, Apple issued OS X update. Maybe they changed something.

**Comment by dimasyt** [comment]
For now it seems to be everything is OK with my trackpad and new alpha of BTT. But I still have to use it for longer time to be completely sure. BTT is so essential for me and my workflow so I literally can't use my mac without it :)

**Comment by dimasyt** [comment]
Unfortunately I still expecting issues with touch pad and latest beta BTT 2.14 (633). Just now I got my touchpad unresponsable again.

Here is my specs:

**mac OS X Sierra**
10.12.5 (16F73)

**MacBook Pro (15-inch, 2016)**
2,7 GHz Intel Core i7
16 GB 2133 MHz LPDDR3

It’s latest MacBook pro with touchbar.

Here is the description of my problems:

1. Touchpad with BTT running sometimes getting really slow. I tap and then (roughly) after half a second I see response from the Software. If I quit BTT everything working super fast. 
2. Sometimes its getting worse - I have to press firmly (even using force touch) to get response from the touchpad.
3. And finally sometimes it’s getting really crazy - I have to press multiply times with different force to get results from touchpad. 

Then I have to quit BTT and start it again. And only after this everything working fine again for some time.

I hope it will help.

**Comment by fifafu** [comment]
Latent Version is 2.20, have you already tried that?

**Comment by dimasyt** [comment]
Oh, no. I do not know about new update, because i did not received any notification from the BTT about new update (maybe because it was Alpha version) Just upgraded to 2.20 (640). 

Thanks for help. I will try new version. And I will hope that all troubles will gone with new version :)
