### ISSUE TITLE
1 Finger corner taps really slow

### ISSUE THREAD

**Issue by elgar-groot** [fifafu/BetterTouchTool#969]
---

#### Description of bug/feature request/question:

I have multiple gestures on the corners of the trackpad and since a couple of days they are suddenly very slow. I use volume up and down on top right and top middle for example and you want to do multiple taps fast to adjust the volume. It now only seems to register a tap every half a second.
I updated to mac OS Sierra and tried reinstalling BTT but it didn't help.
Btw, I love the program. I use it for many years.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: Macbook Pro 15" mid 2010
macOS version: mac OS Sierra/ OS X Yosemite
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Comment by tonynguyen1901** [comment]
haha I have the same issue, I used to use tap left and right corners for the volume and it used to be fast, but I noticed maybe after updating to a newer version of BTT that I cannot do that anymore.

I'm not sure if it is a bug or it is intended by the developer but it pissed me off a little bit...

Did you find the solution for this?

**Comment by fifafu** [comment]
This should be fixed in alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu). If not, please post here again, then I'll reopen the issue.
