### ISSUE TITLE
Show/Hide Files not re-opening Finder - Touch Bar

### ISSUE THREAD

**Issue by realdannys** [fifafu/BetterTouchTool#97]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Using Touch Bar to show/hide files, would be ideal if it would reopen finder afterwards. I have tried to do this by adding "open finder" after the show/hide command, though for some reason it open re-opens Finder when you show hidden files, hiding them won't reopen Finder.

**What kind of Mac are you using?**
Touch Bar 15" MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?** Touch Bar

**Which version of macOS are you running?** 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Weird, it seems to be working for me. Maybe try to add a little delay before calling the Open Finder action:
<img width="1127" alt="screenshot_2016-12-12 23 17 34_eeqcu3" src="https://cloud.githubusercontent.com/assets/8820811/21119091/38043e84-c0c1-11e6-9381-352d7e7d6e2e.png">

**Comment by realdannys** [comment]
Ah yes that works, although I have to set a minimum of 0.5secs for it to be reliable.

But yes, up and working now!
