### ISSUE TITLE
Ctrl - Tab Behavior in Firefox when made into a gesture

### ISSUE THREAD

**Issue by Etrit1** [fifafu/BetterTouchTool#973]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

So, Ctrl -Tab on the keyboard pops up the tab switcher with the tab thumbnails which is great.  However, setting that shortcut up at a gesture only lets me switch between the last two used tabs.. totally weird  and makes no sense. 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, I don't know anything about the internals of Firefox. You'd probably need to report the issue to them.

However keep in mind that when BTT triggers a shortcut it just sends a key down and key up event to the system. If Firefox requires this shortcut to be hold down, this can't be realized with BTT.

**Comment by Etrit1** [comment]
Ahhh!    You're right, it is a holding the key down thing.

*sighs*

Oh well, I found a workaround though.  Install the firefox addon Showcase
and make a gesture for it's shortcut key.   It pops up a small window with
all the open tabs.

Thanks for the message! :)

On Thu, May 25, 2017 at 2:37 AM, Andreas Hegenberg <notifications@github.com

**Comment by GJRobert** [comment]
Thanks for sharing the limitation of BTT (pity). Is the ability of sending "holding down a shortcut" blocked by macOS?
