### ISSUE TITLE
I have set bettertouchtool up with custom apps to show things in the touch bar. Since those apps show blank touch bars by themselves I right clicked and selected show bettertouchtool touch bar and control strip. However I now get a big cross button to the absolute left of the touch bar which I don't want. It also moves the escape key to the right which is very frustrating. I have enabled always keep esc key to the left in bettertouchtool touchbar preferences. I would like to remove this cross button from the side of the touch bar. 

### ISSUE THREAD

**Issue by chessisamazing27** [fifafu/BetterTouchTool#974]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have set bettertouchtool up with custom apps to show things in the touch bar. Since those apps show blank touch bars by themselves I right clicked and selected show bettertouchtool touch bar and control strip. However I now get a big cross button to the absolute left of the touch bar which I don't want. It also moves the escape key to the right which is very frustrating. I have enabled always keep esc key to the left in bettertouchtool touchbar preferences. I would like to remove this cross button from the side of the touch bar. 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If you want to do this, the only possibility is to hide the control strip in the General Touch Bar settings 

![image](https://cloud.githubusercontent.com/assets/8820811/26370813/42b5ad6a-3ff9-11e7-9d39-89c5796d4c95.png)

**Comment by fifafu** [comment]
Also see e.g. #382
