### ISSUE TITLE
Cannot right click when using 3 finger tiptap

### ISSUE THREAD

**Issue by rfrowe** [fifafu/BetterTouchTool#976]
#### Description of bug/feature request/question:
3 finger tiptap eats two finger right click w/ thumb. If I enable any 3 finger tiptap, I can no longer right click with two fingers and a thumb on the trackpad. I can right click with just two fingers, however.

Also, with no 3 finger tiptap gestures defined, the only way to get 2 finger right clicking w/ thumb to work is to enable Thumb filtering. Even with Thumb handling checked (and "Map Three Finger Clicks..." checked) right clicking with 2 fingers and thumb does not work. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Force Trackpad 

#### Device information:

Type of Mac: 2015 15" MacBook Pro
macOS version: 10.12.5
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

None

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu item). I have changed the palm/thumb recognition quite a bit, let's see if that helps

**Comment by rfrowe** [comment]
That seems to have done it! I can now right click with this gesture enabled, but I'm only able to trigger the gesture about half the time even after trying to adjust the tiptap sensitivity.
