### ISSUE TITLE
Enable leap motion mouse control fails

### ISSUE THREAD

**Issue by MetaDev** [fifafu/BetterTouchTool#977]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I use a button combination to trigger the action of enabling the mouse control I git a pop up notifying that the mouse control is enabled but I cannot. The leap motion is connected and tracking with the leap motion app, other apps/games using the leap motion do work

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Leap motion

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version:  10.11.4
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by caipivara** [comment]
I dont even see how to enable leap motion support now on version `2.332`

**Comment by fifafu** [comment]
@caipivara leap motion support is only available until v2.297 (https://boastr.net/releases)

**Comment by caipivara** [comment]
@fifafu sorry but why it was removed?
