### ISSUE TITLE
Disable shortcuts in insert mode

### ISSUE THREAD

**Issue by jtran064** [fifafu/BetterTouchTool#978]
#### Description of bug/feature request/question:
I like to use vim keybinding in my workflow to navigate,  such as the "hjkl" keys for arrow keys . When I type text or when the cursor becomes a blinking cursor, is there a way for BTT to recognize this and disable the shortcuts. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: Pro Retina 2015
macOS version: 10.12.5
BetterTouchTool version: 631

**Comment by fifafu** [comment]
Sorry, unfortunately I think this is not possible and I'm not sure how this could be realized, thus I'm closing here.
