### ISSUE TITLE
First right click after login makes mouse pointer jump

### ISSUE THREAD

**Issue by brenncom** [fifafu/BetterTouchTool#979]
#### Description of bug/feature request/question:

As the title already says, every time I log in after a restart or after opening the screen lid, the first right click makes the mouse pointer jump to the same spot (see the attached screenshot).
It doesn't happen when I disable BTT first before right clicking.

Edit: Just updated to 10.12.5, still the same issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Force Touch Trackpad

#### Device information:

Type of Mac: MBP Retina 2015
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.12 (636)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screenshot: Mouse pointer jumps to where the context menu is shown.

<img width="1680" alt="bildschirmfoto 2017-05-22 um 19 38 24" src="https://cloud.githubusercontent.com/assets/28872130/26321641/df09363c-3f27-11e7-897d-ff14498d4599.png">

**Comment by Locotenenu** [comment]
I have this issue too.

**Comment by Will-Bill** [comment]
I have this issue too - betterTouchTool is causing my mouse pointer to jump when right clicking (tap with two fingers). If I quit betterTouchTool the behavior goes away. It isn't limited to just after login, but I am having difficulty getting it to reproduce consistently otherwise. Putting the lip down and back up seems to reproduce the issue however.

**Comment by fifafu** [comment]
That's weird, do you have the two finger right-click configured in BTT or in System Preferences?

If possible please open the BTT Preferences and go to the About tab. Then press the "Export Debug Info" button. This will create a folder on your Desktop called BetterTouchToolDebug. Would be great if you could send me the contents to boastr.net@gmail.com

**Comment by fifafu** [comment]
Thanks for the debug info! I was able to reproduce and fix the issue. The fix will be in alpha v2.15 which will be released in about an hour.
