### ISSUE TITLE
[Bug Report] On Launch, overlay over "ESC" button

### ISSUE THREAD

**Issue by ZV95** [fifafu/BetterTouchTool#98]
Hello,

With the newest update to 1.965, I noticed that on the initial launch of BTT, if I click the BTT icon in the TouchBar it immediately puts the left most icon over the escape key. That said, as bugs go this isn't the worst because as soon as I click on shift, command, or really any other key, the layout is fixed. Just looks a bit odd at first. Picture included below. 
![img_0885 jpg](https://cloud.githubusercontent.com/assets/18543749/21115058/8b86c138-c07d-11e6-97fa-5e718c5a1453.jpeg)

10.12.2 Beta (16C63a)

**Comment by fifafu** [comment]
Thanks for reporting! Will be fixed with the next alpha in a few minutes.
