### ISSUE TITLE
BTT Crash

### ISSUE THREAD

**Issue by hukangha** [fifafu/BetterTouchTool#980]
#### Description of bug/feature request/question:
It stop responding(seems to happen after wake up, I'm still trying to find the pattern.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Every function of BTT

#### Device information:

Type of Mac:                       MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version:                  10.12.4 (16E195)
BetterTouchTool version:   2.11(630)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I don't know where the log is placed. I'm not a developer of this tool.

I did not find the "User Diagnostic Reports" section in console.app

this is what I found in "System Reports" section:

[diag.zip](https://github.com/fifafu/BetterTouchTool/files/1022361/diag.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by manuel0097** [comment]
I'm having the same problem as you, can't find pattern that's triggering it...

Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.12(631)

**Comment by dionysos283** [comment]
I have the same problem. BTT suddenly doesn't respond anymore (only rotating volley ball). It almost always happens after my Mac was asleep for a longer time.

**Comment by bewebste** [comment]
I've had this happen several times as well, with BTT hanging after having recently woken the Mac from sleep. I took a sample using Activity Monitor and have attached that, hopefully that will offer some clues.
[Sample of BetterTouchTool.txt](https://github.com/fifafu/BetterTouchTool/files/1025963/Sample.of.BetterTouchTool.txt)

**Comment by ytagger** [comment]
Same here, needs to go to activity monitor and force close the app.

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu item).

In general I'm tracking the issue here: #915, thus I'm closing here.

**Comment by hukangha** [comment]
Hi, @fifafu
The crash pattern seems to be found.
It happens at the second wake up of my macbook pro(open lid).
and #915  seems not the same, In my crash, the CPU is not consumed.
I'll test alpha version.
