### ISSUE TITLE
Crash on wake up

### ISSUE THREAD

**Issue by zaygraveyard** [fifafu/BetterTouchTool#985]
#### Description of bug:

At night before going to sleep I close the lid of my macbook air. 
And in the morning when open it, I see that the BTT icon has disappeared from the menu bar.
After a few time of that happening I looked in the Console.app and saw the BTT had crashed.
I should also mention I have an external monitor which I disconnect before closing my mac and reconnect after reopening it.

It seams the crash happens when I wake up the mac.

#### Device information:

Type of Mac: MacBook Air (13-inch, Mid 2013)
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.11 (630)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[BetterTouchTool.crash.zip](https://github.com/fifafu/BetterTouchTool/files/1024826/BetterTouchTool_2017-05-24-095908_Ziads-MacBook-Air.crash.zip)

**Comment by fifafu** [comment]
This is being tracked here: #831 
I hope it'll be fixed with the next update!
