### ISSUE TITLE
Zoom pinch in / out fails in BTT 2.12

### ISSUE THREAD

**Issue by elpulgui** [fifafu/BetterTouchTool#986]
Trackpad MacBook Pro (2011), 10.12.5 and  MacBook Pro (2015) 10.10.5. 
Zoom pinch in and pinch out fails in BTT 2.12. Downgrade to 2.071 and runs ok. Previously I've tried on/off Control Panel OS X. 
Thanks.

**Comment by fifafu** [comment]
Hey, what exactly doesn't work for you?
The zoom gesture in BTT or the system zoom gesture?

**Comment by fifafu** [comment]
I believe all zoom related stuff should be fixed in v2.17 alpha.

**Comment by elpulgui** [comment]
Hi Andreas. 
Actually the problem is always in system, with Finder, Preview and so on. Only 2.12.  
Thanks. 


Desde mi iPhone
