### ISSUE TITLE
Request: Password dialog for scripts

### ISSUE THREAD

**Issue by brandondrew** [fifafu/BetterTouchTool#991]
#### Description of bug/feature request/question:

There are many things I would like to do through BTT scripts, but cannot, because (as far as I know) there is no way to enter a password.  

It would be very useful to be able to have BTT ask for my password when a Terminal command or AppleScript needs it.

For example, I often have to type `sudo pkill 'VDCAssistant'` because my cameras get locked (presumably because of a bug in the last application that was using the camera).  It would be super-convenient to trigger the command through BTT, and then have an operating system dialog appear for the password.

That example may not be useful to many people, but of course there are thousands of other things someone might want to do that require entering a password.

**Comment by fifafu** [comment]
Hey 

I think you should be able to achieve this using the "run apple script" action and using this script :

```
do shell script "sudo pkill VCDAssistant" with admin privileges
```

**Comment by fifafu** [comment]
Ah sorry, the correct command is ```do shell script "pkill VCDAssistant" with administrator privileges```
