### ISSUE TITLE
Option to disable (specific) trackpad gestures in specific apps

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#993]
I think this would be nice. Some trackpad gestures mess with the three finger drag feature _in specific apps_. This is why it would be nice to disable these gestures in these specific apps. I can disable BTT for these apps entirely using the menu bar icon, but that's not the nicest as keyboard shortcuts get disabled as well.

**Comment by fifafu** [comment]
In general assigning "Use Apple Default or do nothing" should deactivate the gesture. Doesn't this work in your case?

**Comment by cleverjackal** [comment]
Hmm... I thought I tried this. Seems like it might have worked. I'll close this and reopen it if it doesn't work.
