### ISSUE TITLE
Bluetooth LE Device List Could Not Recognize All My Devices At The Same Time

### ISSUE THREAD

**Issue by kklliu** [fifafu/BetterTouchTool#996]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Question:
When configuring Apple Watch as the trigger to lock/unlock my mac,
I could see my Apple Watch in the nearby Bluetooth LE Device list.
However, it seems BTT could not recognize my Apple Watch because the "Last Seen" are couple minutes ago.
However, BTT could find my iPhone.
When I turn off the bluetooth of my iPhone, BTT could not find my iPhone(that's for sure), 
and starting recognising my Apple Watch.
Is it possible for BTT to recognize several bluetooth LE Devices at the same time?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple Watch

#### Device information:

Type of Mac: Mac mini
macOS version: 10.12.5
BetterTouchTool version:2.12 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Probably the Apple Watch doesn't "advertise" when it's connected to the iPhone. This explains why it shows up when you turn off your iPhone.

In general BTT can recognize multiple devices at once.
