### ISSUE TITLE
Left click mouse still with problem...

### ISSUE THREAD

**Issue by RexTheHut** [fifafu/BetterTouchTool#998]
Since 3 months ago I'm having problems with the left click mouse.
When I'm using my MacMini (Sierra) with the BTT enabled, after some time the click stops working well. The click only works after many clicks.
This problem resolves after closing BTT ..
I already tested older version (BTT 2.05) and also Alpha and the latest versions, but they shows problemas too.
I use BTT only to do WINDOWS SNAPING (to maximize and organize the windows on the screen).
I have legal purchased license and I'm need some help to solve this problem!

**Comment by fifafu** [comment]
What kind of input device are you using exactly?
Are you using any other mouse/keyboard related tools?

**Comment by RexTheHut** [comment]
Currently I’m using a Bluetooth mouse (Logitech M535), but I already tried with Wirelles mouse (2 different models) and also with a traditional USB mouse, but all have the same problem.

I have been using BTT for some time, but since 3 months ago I have had this problem.
I use the BTT just to organize the windows on the screen (snapping), because I use many programs at the same time and I like the way the BTT allows snapping (like the Windows 10).

I do not use any other mouse or keyboard control tools ...

I've done a clean install of Mac OSX Sierra ...
I have already tried Mac SMC reset and PRAM reset.

Nothing solved the problem ....

If you want to test my Mac via TeamViewer or another app you can see the problem .....

Thankls a lot.



Eduardo Lorena
elorena@icloud.com

**Comment by fifafu** [comment]
Please udpate to v2.17 alpha  (via check for alpha version updates).
Then if this problem occurs again, please try to click multiple times and then immediately open the BTT Preferences and go to the About tab. Then click the "Export debug info" button.

This will create a folder on your desktop called "BetterTouchTOolDebug", please send that folder to boastr.net@gmail.com. This will help me solve the issue.

**Comment by RexTheHut** [comment]
Ok. I Will do this. 
Tks. 
		

		Obter o Outlook para iOS
	





On Sat, May 27, 2017 at 4:37 AM -0300, "Andreas Hegenberg" <notifications@github.com> wrote:












Please udpate to v2.17 alpha  (via check for alpha version updates).

Then if this problem occurs again, please try to click multiple times and then immediately open the BTT Preferences and go to the About tab. Then click the "Export debug info" button.


This will create a folder on your desktop called "BetterTouchTOolDebug", please send that folder to boastr.net@gmail.com. This will help me solve the issue.

**Comment by RexTheHut** [comment]
Today I had the left click mouse problem again and I done the suggested by you.
Attached in this mail, the debug data.

I wait for news…

Best regards.
Eduardo Lorena
elorena@icloud.com

**Comment by jrodan** [comment]
Still have a left click problem with v2.20. Anything I should provide?
I have to click multiple times sometimes to execute a left click - mouse independent.

**Comment by kuba142** [comment]
This is still occurring in v2.266. Any info to supply?

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.
