### ISSUE TITLE
Window snapping doesn't work for Adobe Illustrator and InDesign 

### ISSUE THREAD

**Issue by zanotab** [fifafu/BetterTouchTool#999]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Window snapping seems to work with all my programs except for Adobe Illustrator and InDesign. It works fine for Photoshop. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad, MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: El Capitan 10.11.6
BetterTouchTool version: 2.16

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by chr0max** [comment]
I can confirm that with Sierra and Illustrator 2018.

Any workarounds?

**Comment by fifafu** [comment]
Unfortunately Illustrator and InDesign have some bugs that cause big performance drops if Window Snapping is enabled for them. This is why it's currently disabled there. I'll enable it as soon as these bugs are resolved.
